.TH "O:/GitHUBMINIPRoject/Assets/LeapMotion/Modules/InteractionEngine/Scripts/Utility/ActivityManager.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/LeapMotion/Modules/InteractionEngine/Scripts/Utility/ActivityManager.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLeap\&.Unity\&.Interaction\&.ActivityManager< T >\fP"
.br
.RI "\fBActivityManager\fP is a wrapper around PhysX sphere queries for arbitrary \fBUnity\fP objects\&. 'Active' objects are objects found in the latest query\&. It's also possible to get the sets of objects that just began or stopped being active since the last query; this requires enabling the trackStateChanges setting\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLeap\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\&.Interaction\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
