.TH "ArmMovementRight" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArmMovementRight \- It captures the right controller and the right leap hand coordinates and places them on the right IK End effector\&. Then the IK works fine  

.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBBone\fP"
.br
.ti -1c
.RI "GameObject \fBRightInterationHand\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
It captures the right controller and the right leap hand coordinates and places them on the right IK End effector\&. Then the IK works fine 


.PP
Definition at line 11 of file ArmMovementRight\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject ArmMovementRight\&.Bone"

.PP
Definition at line 13 of file ArmMovementRight\&.cs\&.
.SS "GameObject ArmMovementRight\&.RightInterationHand"
Taking the right end effector 
.PP
Definition at line 15 of file ArmMovementRight\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
