.TH "O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/DataStructures/AssetFolder.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/DataStructures/AssetFolder.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLeap\&.Unity\&.AssetFolder\fP"
.br
.RI "A convenient serializable representation of an asset folder\&. Only useful for editor scripts since asset folder structure is not preserved for builds\&. The asset folder struct itself is still available at runtime for serialization ease, but the Path property will not be available\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLeap\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBUnityObject\fP = UnityEngine\&.Object"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBUnityObject\fP =  UnityEngine\&.Object"

.PP
Definition at line 12 of file AssetFolder\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
