.TH "O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/Attachments/AttachmentHand.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/Attachments/AttachmentHand.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLeap\&.Unity\&.Attachments\&.AttachmentHand\fP"
.br
.RI "This MonoBehaviour is managed by an \fBAttachmentHands\fP component on a parent MonoBehaviour\&. Instead of adding \fBAttachmentHand\fP directly to a GameObject, add an \fBAttachmentHands\fP component to a parent GameObject to manage the construction and updating of \fBAttachmentHand\fP objects\&. "
.ti -1c
.RI "struct \fBLeap\&.Unity\&.Attachments\&.AttachmentHand\&.AttachmentPointsEnumerator\fP"
.br
.RI "An enumerator that traverses all of the existing AttachmentPointBehaviours beneath an \fBAttachmentHand\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLeap\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\&.Attachments\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
