.TH "O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/Attributes/AutoFind.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/Attributes/AutoFind.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLeap\&.Unity\&.Attributes\&.AutoFindAttribute\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLeap\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\&.Attributes\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLeap\&.Unity\&.Attributes\&.AutoFindLocations\fP { \fBLeap\&.Unity\&.Attributes\&.AutoFindLocations\&.Object\fP = 0x01, \fBLeap\&.Unity\&.Attributes\&.AutoFindLocations\&.Children\fP = 0x02, \fBLeap\&.Unity\&.Attributes\&.AutoFindLocations\&.Parents\fP = 0x04, \fBLeap\&.Unity\&.Attributes\&.AutoFindLocations\&.Scene\fP = 0x08, \fBLeap\&.Unity\&.Attributes\&.AutoFindLocations\&.All\fP = 0xFFFF }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
