.TH "chidcamera" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chidcamera \- This class was never used  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetTarget\fP (Transform target)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBplayerTransform\fP"
.br
.ti -1c
.RI "int \fBdepth\fP = \-20"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class was never used 


.PP
Definition at line 8 of file chidcamera\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void chidcamera\&.setTarget (Transform target)"

.PP
Definition at line 22 of file chidcamera\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int chidcamera\&.depth = \-20"

.PP
Definition at line 11 of file chidcamera\&.cs\&.
.SS "Transform chidcamera\&.playerTransform"

.PP
Definition at line 10 of file chidcamera\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
