.TH "O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/Attributes/CurveBounds.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/Attributes/CurveBounds.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLeap\&.Unity\&.Attributes\&.CurveBoundsAttribute\fP"
.br
.RI "You can use this attribute to mark that an AnimationCurve can only have values that fall within specific bounds\&. The user will be prevented from entering a curve that lies outside of these bounds\&. "
.ti -1c
.RI "class \fBLeap\&.Unity\&.Attributes\&.UnitCurveAttribute\fP"
.br
.RI "You can use this attribute to mark that an AnimationCurve can only have values that range from 0 to 1\&. The user will be prevented from entering a curve that lies outside of these bounds\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLeap\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\&.Attributes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
