.TH "deprecated" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBClass \fBLeap\&.Unity\&.DisconnectionNotice\fP \fP" 1c
Use \fBConnectionMonitor\fP in new code\&. 
.PP

