.TH "DitzelGames.FastIK.FastIKFabric" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DitzelGames.FastIK.FastIKFabric \- Fabrik IK Solver  

.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBBone\fP"
.br
.ti -1c
.RI "int \fBChainLength\fP = 2"
.br
.RI "Chain length of bones "
.ti -1c
.RI "Transform \fBTarget\fP"
.br
.RI "Target the chain should bent to "
.ti -1c
.RI "Transform \fBPole\fP"
.br
.ti -1c
.RI "int \fBIterations\fP = 10"
.br
.RI "Solver iterations per update "
.ti -1c
.RI "float \fBDelta\fP = 0\&.001f"
.br
.RI "Distance when the solver stops "
.ti -1c
.RI "float \fBSnapBackStrength\fP = 1f"
.br
.RI "Strength of going back to the start position\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float [] \fBBonesLength\fP"
.br
.ti -1c
.RI "float \fBCompleteLength\fP"
.br
.ti -1c
.RI "Transform [] \fBBones\fP"
.br
.ti -1c
.RI "Vector3 [] \fBPositions\fP"
.br
.ti -1c
.RI "Vector3 [] \fBStartDirectionSucc\fP"
.br
.ti -1c
.RI "Quaternion [] \fBStartRotationBone\fP"
.br
.ti -1c
.RI "Quaternion \fBStartRotationTarget\fP"
.br
.ti -1c
.RI "Quaternion \fBStartRotationRoot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fabrik IK Solver 


.PP
Definition at line 9 of file FastIKFabric\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject DitzelGames\&.FastIK\&.FastIKFabric\&.Bone"

.PP
Definition at line 12 of file FastIKFabric\&.cs\&.
.SS "Transform [] DitzelGames\&.FastIK\&.FastIKFabric\&.Bones\fC [protected]\fP"

.PP
Definition at line 45 of file FastIKFabric\&.cs\&.
.SS "float [] DitzelGames\&.FastIK\&.FastIKFabric\&.BonesLength\fC [protected]\fP"

.PP
Definition at line 43 of file FastIKFabric\&.cs\&.
.SS "int DitzelGames\&.FastIK\&.FastIKFabric\&.ChainLength = 2"

.PP
Chain length of bones 
.PP
Definition at line 17 of file FastIKFabric\&.cs\&.
.SS "float DitzelGames\&.FastIK\&.FastIKFabric\&.CompleteLength\fC [protected]\fP"

.PP
Definition at line 44 of file FastIKFabric\&.cs\&.
.SS "float DitzelGames\&.FastIK\&.FastIKFabric\&.Delta = 0\&.001f"

.PP
Distance when the solver stops 
.PP
Definition at line 34 of file FastIKFabric\&.cs\&.
.SS "int DitzelGames\&.FastIK\&.FastIKFabric\&.Iterations = 10"

.PP
Solver iterations per update 
.PP
Definition at line 29 of file FastIKFabric\&.cs\&.
.SS "Transform DitzelGames\&.FastIK\&.FastIKFabric\&.Pole"

.PP
Definition at line 23 of file FastIKFabric\&.cs\&.
.SS "Vector3 [] DitzelGames\&.FastIK\&.FastIKFabric\&.Positions\fC [protected]\fP"

.PP
Definition at line 46 of file FastIKFabric\&.cs\&.
.SS "float DitzelGames\&.FastIK\&.FastIKFabric\&.SnapBackStrength = 1f"

.PP
Strength of going back to the start position\&. 
.PP
Definition at line 40 of file FastIKFabric\&.cs\&.
.SS "Vector3 [] DitzelGames\&.FastIK\&.FastIKFabric\&.StartDirectionSucc\fC [protected]\fP"

.PP
Definition at line 47 of file FastIKFabric\&.cs\&.
.SS "Quaternion [] DitzelGames\&.FastIK\&.FastIKFabric\&.StartRotationBone\fC [protected]\fP"

.PP
Definition at line 48 of file FastIKFabric\&.cs\&.
.SS "Quaternion DitzelGames\&.FastIK\&.FastIKFabric\&.StartRotationRoot\fC [protected]\fP"

.PP
Definition at line 50 of file FastIKFabric\&.cs\&.
.SS "Quaternion DitzelGames\&.FastIK\&.FastIKFabric\&.StartRotationTarget\fC [protected]\fP"

.PP
Definition at line 49 of file FastIKFabric\&.cs\&.
.SS "Transform DitzelGames\&.FastIK\&.FastIKFabric\&.Target"

.PP
Target the chain should bent to 
.PP
Definition at line 22 of file FastIKFabric\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
