.TH "DitzelGames.FastIK.FastIKLook" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DitzelGames.FastIK.FastIKLook
.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBTarget\fP"
.br
.RI "Look at target "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBStartDirection\fP"
.br
.RI "Initial direction "
.ti -1c
.RI "Quaternion \fBStartRotation\fP"
.br
.RI "Initial Rotation "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file FastIKLook\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 DitzelGames\&.FastIK\&.FastIKLook\&.StartDirection\fC [protected]\fP"

.PP
Initial direction 
.PP
Definition at line 18 of file FastIKLook\&.cs\&.
.SS "Quaternion DitzelGames\&.FastIK\&.FastIKLook\&.StartRotation\fC [protected]\fP"

.PP
Initial Rotation 
.PP
Definition at line 23 of file FastIKLook\&.cs\&.
.SS "Transform DitzelGames\&.FastIK\&.FastIKLook\&.Target"

.PP
Look at target 
.PP
Definition at line 13 of file FastIKLook\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
