.TH "DitzelGames.FastIK.SampleSinMover" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DitzelGames.FastIK.SampleSinMover
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBDir\fP"
.br
.ti -1c
.RI "Vector3 \fBStart\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file SampleSinMover\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 DitzelGames\&.FastIK\&.SampleSinMover\&.Dir"

.PP
Definition at line 8 of file SampleSinMover\&.cs\&.
.SS "Vector3 DitzelGames\&.FastIK\&.SampleSinMover\&.Start"

.PP
Definition at line 9 of file SampleSinMover\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
