.TH "DitzelGames.FastIK.SampleProcedualAnimation" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DitzelGames.FastIK.SampleProcedualAnimation
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLateUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform [] \fBFootTarget\fP"
.br
.ti -1c
.RI "Transform \fBLookTarget\fP"
.br
.ti -1c
.RI "Transform \fBHandTarget\fP"
.br
.ti -1c
.RI "Transform \fBHandPole\fP"
.br
.ti -1c
.RI "Transform \fBStep\fP"
.br
.ti -1c
.RI "Transform \fBAttraction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file SampleProcedualAnimation\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void DitzelGames\&.FastIK\&.SampleProcedualAnimation\&.LateUpdate ()"

.PP
Definition at line 19 of file SampleProcedualAnimation\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform DitzelGames\&.FastIK\&.SampleProcedualAnimation\&.Attraction"

.PP
Definition at line 17 of file SampleProcedualAnimation\&.cs\&.
.SS "Transform [] DitzelGames\&.FastIK\&.SampleProcedualAnimation\&.FootTarget"

.PP
Definition at line 12 of file SampleProcedualAnimation\&.cs\&.
.SS "Transform DitzelGames\&.FastIK\&.SampleProcedualAnimation\&.HandPole"

.PP
Definition at line 15 of file SampleProcedualAnimation\&.cs\&.
.SS "Transform DitzelGames\&.FastIK\&.SampleProcedualAnimation\&.HandTarget"

.PP
Definition at line 14 of file SampleProcedualAnimation\&.cs\&.
.SS "Transform DitzelGames\&.FastIK\&.SampleProcedualAnimation\&.LookTarget"

.PP
Definition at line 13 of file SampleProcedualAnimation\&.cs\&.
.SS "Transform DitzelGames\&.FastIK\&.SampleProcedualAnimation\&.Step"

.PP
Definition at line 16 of file SampleProcedualAnimation\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
