.TH "O:/GitHUBMINIPRoject/Assets/LeapMotion/Modules/InteractionEngine/Scripts/Utility/GraspedMovementEvent.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/LeapMotion/Modules/InteractionEngine/Scripts/Utility/GraspedMovementEvent.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLeap\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\&.Interaction\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\&.Interaction\&.Internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBLeap\&.Unity\&.Interaction\&.Internal\&.GraspedMovementEvent\fP (Vector3 oldPosition, Quaternion oldRotation, Vector3 newPosition, Quaternion newRotation, List< InteractionController > graspingControllers)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
