.TH "health" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
health \- This health class is resposible for making sure that the health is reduced , when the hits are registered in the \fBbulletcollider\&.cs\fP Also this script takes care of the exit function  

.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTakeDamage\fP (int amount)"
.br
.RI "Calculates the damage on the player and exits as per functionality "
.ti -1c
.RI "void \fBOnChangeHealth\fP (int \fBhealth\fP)"
.br
.RI "Changing the UI for the health bar\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "NetworkInstanceId \fBPlayerId\fP"
.br
.ti -1c
.RI "const int \fBmaxHealth\fP = 100"
.br
.ti -1c
.RI "int \fBcurrentHealth\fP = \fBmaxHealth\fP"
.br
.ti -1c
.RI "RectTransform \fBhealthbar\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This health class is resposible for making sure that the health is reduced , when the hits are registered in the \fBbulletcollider\&.cs\fP Also this script takes care of the exit function 


.PP
Definition at line 12 of file health\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void health\&.OnChangeHealth (int health)"

.PP
Changing the UI for the health bar\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhealth\fP 
.RE
.PP

.PP
Definition at line 85 of file health\&.cs\&.
.SS "void health\&.TakeDamage (int amount)"

.PP
Calculates the damage on the player and exits as per functionality This is for the UI update 
.PP
\fBParameters:\fP
.RS 4
\fIamount\fP The amount is taken when there is a bullet colliding the shootable layer of the player
.RE
.PP
Used to find number of players
.PP
This code checks for the health when it is less than or equal to zero Íf the server dies , it does nothing and keeps the connection open and deactivates the server\&. When the client does it disables the client\&. 
.PP
Definition at line 26 of file health\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int health\&.currentHealth = \fBmaxHealth\fP"
This is used to count the number of player in the network 
.PP
Definition at line 18 of file health\&.cs\&.
.SS "RectTransform health\&.healthbar"
SyncVar is used to to sync the current health , whenever the current health value changes on server, it will updated to the clients, such that clients know there is change in value once the method is called and this method will provide updated value to the health bar 
.PP
Definition at line 19 of file health\&.cs\&.
.SS "const int health\&.maxHealth = 100"
This game object stores the player id to identify whose health is getting reduced 
.PP
Definition at line 16 of file health\&.cs\&.
.SS "NetworkInstanceId health\&.PlayerId"

.PP
Definition at line 15 of file health\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
