.TH "O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.package-manager-ui@2.0.7/Editor/Sources/Services/Interfaces/IOperationFactory.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.package-manager-ui@2.0.7/Editor/Sources/Services/Interfaces/IOperationFactory.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBUnityEditor\&.PackageManager\&.UI\&.IOperationFactory\fP"
.br
.RI "This is the Interface we will use to create the facade we need for testing\&. In the case of the Fake factory, we can create fake operations with doctored data we use for our tests\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUnityEditor\fP"
.br
.ti -1c
.RI "namespace \fBUnityEditor\&.PackageManager\fP"
.br
.ti -1c
.RI "namespace \fBUnityEditor\&.PackageManager\&.UI\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
