.TH "LeapInternal.LEAP_IMAGE_PROPERTIES" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_IMAGE_PROPERTIES
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBeLeapImageType\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBeLeapImageFormat\fP \fBformat\fP"
.br
.ti -1c
.RI "UInt32 \fBbpp\fP"
.br
.ti -1c
.RI "UInt32 \fBwidth\fP"
.br
.ti -1c
.RI "UInt32 \fBheight\fP"
.br
.ti -1c
.RI "float \fBx_scale\fP"
.br
.ti -1c
.RI "float \fBy_scale\fP"
.br
.ti -1c
.RI "float \fBx_offset\fP"
.br
.ti -1c
.RI "float \fBy_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 585 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "UInt32 LeapInternal\&.LEAP_IMAGE_PROPERTIES\&.bpp"

.PP
Definition at line 588 of file LeapC\&.cs\&.
.SS "\fBeLeapImageFormat\fP LeapInternal\&.LEAP_IMAGE_PROPERTIES\&.format"

.PP
Definition at line 587 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_IMAGE_PROPERTIES\&.height"

.PP
Definition at line 590 of file LeapC\&.cs\&.
.SS "\fBeLeapImageType\fP LeapInternal\&.LEAP_IMAGE_PROPERTIES\&.type"

.PP
Definition at line 586 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_IMAGE_PROPERTIES\&.width"

.PP
Definition at line 589 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_IMAGE_PROPERTIES\&.x_offset"

.PP
Definition at line 593 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_IMAGE_PROPERTIES\&.x_scale"

.PP
Definition at line 591 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_IMAGE_PROPERTIES\&.y_offset"

.PP
Definition at line 594 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_IMAGE_PROPERTIES\&.y_scale"

.PP
Definition at line 592 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
