.TH "Leap.Unity.Space.IRadialTransformer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Space.IRadialTransformer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Space\&.ITransformer\fP\&.
.PP
Inherited by \fBLeap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\fP, and \fBLeap\&.Unity\&.Space\&.LeapSphericalSpace\&.Transformer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Vector4 \fBGetVectorRepresentation\fP (Transform element)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file LeapRadialSpace\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Vector4 Leap\&.Unity\&.Space\&.IRadialTransformer\&.GetVectorRepresentation (Transform element)"

.PP
Implemented in \fBLeap\&.Unity\&.Space\&.LeapSphericalSpace\&.Transformer\fP, and \fBLeap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
