.TH "Leap.Unity.Examples.SimpleTransformUtil" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples.SimpleTransformUtil
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetParentTo\fP (Transform t)"
.br
.ti -1c
.RI "void \fBClearParentTransform\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file SimpleTransformUtil\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Examples\&.SimpleTransformUtil\&.ClearParentTransform ()"

.PP
Definition at line 23 of file SimpleTransformUtil\&.cs\&.
.SS "void Leap\&.Unity\&.Examples\&.SimpleTransformUtil\&.SetParentTo (Transform t)"

.PP
Definition at line 19 of file SimpleTransformUtil\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
