.TH "Leap.Unity.Attributes.DisableIfBase" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.DisableIfBase \- Conditionally disables a property based on the value of another property\&. The only condition types that are currently supported are bool types, and enum types\&. The property has two arguments names 'equalTo' and 'notEqualTo'\&. Exactly one of them must be specified, like so:  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Attributes\&.CombinablePropertyAttribute\fP, and \fBLeap\&.Unity\&.Attributes\&.IPropertyDisabler\fP\&.
.PP
Inherited by \fBLeap\&.Unity\&.Attributes\&.DisableIf\fP, \fBLeap\&.Unity\&.Attributes\&.DisableIfAll\fP, and \fBLeap\&.Unity\&.Attributes\&.DisableIfAny\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisableIfBase\fP (object isEqualTo, object isNotEqualTo, bool \fBisAndOperation\fP, params string[] \fBpropertyNames\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string [] \fBpropertyNames\fP"
.br
.ti -1c
.RI "readonly object \fBtestValue\fP"
.br
.ti -1c
.RI "readonly bool \fBdisableResult\fP"
.br
.ti -1c
.RI "readonly bool \fBisAndOperation\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Conditionally disables a property based on the value of another property\&. The only condition types that are currently supported are bool types, and enum types\&. The property has two arguments names 'equalTo' and 'notEqualTo'\&. Exactly one of them must be specified, like so: 

[\fBDisableIf\fP('myBoolProperty', isEqualTo: true)] [\fBDisableIf\fP('myEnumProperty', isNotEqualTo: MyEnum\&.Value)] [\fBDisableIfAny\fP('bool1', 'bool2', isEqualTo: false)] [\fBDisableIfAll\fP('cond1', 'cond2', 'cond3', isNotEqualTo: true)] 
.PP
Definition at line 28 of file DisableIf\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Attributes\&.DisableIfBase\&.DisableIfBase (object isEqualTo, object isNotEqualTo, bool isAndOperation, params string [] propertyNames)"

.PP
Definition at line 34 of file DisableIf\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly bool Leap\&.Unity\&.Attributes\&.DisableIfBase\&.disableResult"

.PP
Definition at line 31 of file DisableIf\&.cs\&.
.SS "readonly bool Leap\&.Unity\&.Attributes\&.DisableIfBase\&.isAndOperation"

.PP
Definition at line 32 of file DisableIf\&.cs\&.
.SS "readonly string [] Leap\&.Unity\&.Attributes\&.DisableIfBase\&.propertyNames"

.PP
Definition at line 29 of file DisableIf\&.cs\&.
.SS "readonly object Leap\&.Unity\&.Attributes\&.DisableIfBase\&.testValue"

.PP
Definition at line 30 of file DisableIf\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
