.TH "LeapInternal.LEAP_HAND" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_HAND
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UInt32 \fBid\fP"
.br
.ti -1c
.RI "UInt32 \fBflags\fP"
.br
.ti -1c
.RI "\fBeLeapHandType\fP \fBtype\fP"
.br
.ti -1c
.RI "float \fBconfidence\fP"
.br
.ti -1c
.RI "UInt64 \fBvisible_time\fP"
.br
.ti -1c
.RI "float \fBpinch_distance\fP"
.br
.ti -1c
.RI "float \fBgrab_angle\fP"
.br
.ti -1c
.RI "float \fBpinch_strength\fP"
.br
.ti -1c
.RI "float \fBgrab_strength\fP"
.br
.ti -1c
.RI "\fBLEAP_PALM\fP \fBpalm\fP"
.br
.ti -1c
.RI "\fBLEAP_DIGIT\fP \fBthumb\fP"
.br
.ti -1c
.RI "\fBLEAP_DIGIT\fP \fBindex\fP"
.br
.ti -1c
.RI "\fBLEAP_DIGIT\fP \fBmiddle\fP"
.br
.ti -1c
.RI "\fBLEAP_DIGIT\fP \fBring\fP"
.br
.ti -1c
.RI "\fBLEAP_DIGIT\fP \fBpinky\fP"
.br
.ti -1c
.RI "\fBLEAP_BONE\fP \fBarm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 693 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLEAP_BONE\fP LeapInternal\&.LEAP_HAND\&.arm"

.PP
Definition at line 709 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_HAND\&.confidence"

.PP
Definition at line 697 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_HAND\&.flags"

.PP
Definition at line 695 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_HAND\&.grab_angle"

.PP
Definition at line 700 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_HAND\&.grab_strength"

.PP
Definition at line 702 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_HAND\&.id"

.PP
Definition at line 694 of file LeapC\&.cs\&.
.SS "\fBLEAP_DIGIT\fP LeapInternal\&.LEAP_HAND\&.index"

.PP
Definition at line 705 of file LeapC\&.cs\&.
.SS "\fBLEAP_DIGIT\fP LeapInternal\&.LEAP_HAND\&.middle"

.PP
Definition at line 706 of file LeapC\&.cs\&.
.SS "\fBLEAP_PALM\fP LeapInternal\&.LEAP_HAND\&.palm"

.PP
Definition at line 703 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_HAND\&.pinch_distance"

.PP
Definition at line 699 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_HAND\&.pinch_strength"

.PP
Definition at line 701 of file LeapC\&.cs\&.
.SS "\fBLEAP_DIGIT\fP LeapInternal\&.LEAP_HAND\&.pinky"

.PP
Definition at line 708 of file LeapC\&.cs\&.
.SS "\fBLEAP_DIGIT\fP LeapInternal\&.LEAP_HAND\&.ring"

.PP
Definition at line 707 of file LeapC\&.cs\&.
.SS "\fBLEAP_DIGIT\fP LeapInternal\&.LEAP_HAND\&.thumb"

.PP
Definition at line 704 of file LeapC\&.cs\&.
.SS "\fBeLeapHandType\fP LeapInternal\&.LEAP_HAND\&.type"

.PP
Definition at line 696 of file LeapC\&.cs\&.
.SS "UInt64 LeapInternal\&.LEAP_HAND\&.visible_time"

.PP
Definition at line 698 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
