.TH "LeapInternal.LEAP_DEVICE_INFO" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_DEVICE_INFO
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UInt32 \fBsize\fP"
.br
.ti -1c
.RI "\fBeLeapDeviceStatus\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBeLeapDeviceCaps\fP \fBcaps\fP"
.br
.ti -1c
.RI "\fBeLeapDeviceType\fP \fBtype\fP"
.br
.ti -1c
.RI "UInt32 \fBbaseline\fP"
.br
.ti -1c
.RI "UInt32 \fBserial_length\fP"
.br
.ti -1c
.RI "IntPtr \fBserial\fP"
.br
.ti -1c
.RI "float \fBh_fov\fP"
.br
.ti -1c
.RI "float \fBv_fov\fP"
.br
.ti -1c
.RI "UInt32 \fBrange\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 564 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "UInt32 LeapInternal\&.LEAP_DEVICE_INFO\&.baseline"

.PP
Definition at line 569 of file LeapC\&.cs\&.
.SS "\fBeLeapDeviceCaps\fP LeapInternal\&.LEAP_DEVICE_INFO\&.caps"

.PP
Definition at line 567 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_DEVICE_INFO\&.h_fov"

.PP
Definition at line 572 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_DEVICE_INFO\&.range"

.PP
Definition at line 574 of file LeapC\&.cs\&.
.SS "IntPtr LeapInternal\&.LEAP_DEVICE_INFO\&.serial"

.PP
Definition at line 571 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_DEVICE_INFO\&.serial_length"

.PP
Definition at line 570 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_DEVICE_INFO\&.size"

.PP
Definition at line 565 of file LeapC\&.cs\&.
.SS "\fBeLeapDeviceStatus\fP LeapInternal\&.LEAP_DEVICE_INFO\&.status"

.PP
Definition at line 566 of file LeapC\&.cs\&.
.SS "\fBeLeapDeviceType\fP LeapInternal\&.LEAP_DEVICE_INFO\&.type"

.PP
Definition at line 568 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_DEVICE_INFO\&.v_fov"

.PP
Definition at line 573 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
