.TH "Leap.Unity.Attributes.MinMax" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.MinMax
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Attributes\&.CombinablePropertyAttribute\fP, and \fBLeap\&.Unity\&.Attributes\&.IFullPropertyDrawer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMinMax\fP (float \fBmin\fP, float max)"
.br
.ti -1c
.RI "\fBMinMax\fP (int \fBmin\fP, int max)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const float \fBPERCENT_NUM\fP = 0\&.2f"
.br
.ti -1c
.RI "const float \fBSPACING\fP = 3"
.br
.ti -1c
.RI "readonly float \fBmin\fP"
.br
.ti -1c
.RI "readonly bool \fBisInt\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file MinMax\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Attributes\&.MinMax\&.MinMax (float min, float max)"

.PP
Definition at line 25 of file MinMax\&.cs\&.
.SS "Leap\&.Unity\&.Attributes\&.MinMax\&.MinMax (int min, int max)"

.PP
Definition at line 31 of file MinMax\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly bool Leap\&.Unity\&.Attributes\&.MinMax\&.isInt"

.PP
Definition at line 23 of file MinMax\&.cs\&.
.SS "readonly float Leap\&.Unity\&.Attributes\&.MinMax\&.min"

.PP
Definition at line 22 of file MinMax\&.cs\&.
.SS "const float Leap\&.Unity\&.Attributes\&.MinMax\&.PERCENT_NUM = 0\&.2f"

.PP
Definition at line 19 of file MinMax\&.cs\&.
.SS "const float Leap\&.Unity\&.Attributes\&.MinMax\&.SPACING = 3"

.PP
Definition at line 20 of file MinMax\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
