.TH "Leap.Unity.Animation.Internal.Vector2InterpolatorBase< ObjType >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Animation.Internal.Vector2InterpolatorBase< ObjType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Animation\&.Internal\&.InterpolatorBase< Vector2, ObjType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "new \fBVector2InterpolatorBase\fP< ObjType > \fBInit\fP (Vector2 a, Vector2 b, ObjType target)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override float \fBlength\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 54 of file InterpolatorBases\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "new \fBVector2InterpolatorBase\fP<ObjType> \fBLeap\&.Unity\&.Animation\&.Internal\&.Vector2InterpolatorBase\fP< ObjType >\&.Init (Vector2 a, Vector2 b, ObjType target)"

.PP
Definition at line 61 of file InterpolatorBases\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override float \fBLeap\&.Unity\&.Animation\&.Internal\&.Vector2InterpolatorBase\fP< ObjType >\&.length\fC [get]\fP"

.PP
Definition at line 55 of file InterpolatorBases\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
