.TH "Leap.Unity.KeyEnableGameObjects" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.KeyEnableGameObjects
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< GameObject > \fBtargets\fP"
.br
.ti -1c
.RI "KeyCode \fBunlockHold\fP = KeyCode\&.RightShift"
.br
.ti -1c
.RI "KeyCode \fBtoggle\fP = KeyCode\&.T"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file KeyEnableGameObjects\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<GameObject> Leap\&.Unity\&.KeyEnableGameObjects\&.targets"

.PP
Definition at line 16 of file KeyEnableGameObjects\&.cs\&.
.SS "KeyCode Leap\&.Unity\&.KeyEnableGameObjects\&.toggle = KeyCode\&.T"

.PP
Definition at line 19 of file KeyEnableGameObjects\&.cs\&.
.SS "KeyCode Leap\&.Unity\&.KeyEnableGameObjects\&.unlockHold = KeyCode\&.RightShift"

.PP
Definition at line 18 of file KeyEnableGameObjects\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
