.TH "Leap.Unity.Detector" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Detector
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBLeap\&.Unity\&.AbstractHoldDetector\fP, \fBLeap\&.Unity\&.DetectorLogicGate\fP, \fBLeap\&.Unity\&.ExtendedFingerDetector\fP, \fBLeap\&.Unity\&.FingerDirectionDetector\fP, \fBLeap\&.Unity\&.PalmDirectionDetector\fP, and \fBLeap\&.Unity\&.ProximityDetector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBActivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBDeactivate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBOnActivate\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnDeactivate\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Color \fBOnColor\fP = Color\&.green"
.br
.ti -1c
.RI "Color \fBOffColor\fP = Color\&.red"
.br
.ti -1c
.RI "Color \fBLimitColor\fP = Color\&.blue"
.br
.ti -1c
.RI "Color \fBDirectionColor\fP = Color\&.white"
.br
.ti -1c
.RI "Color \fBNormalColor\fP = Color\&.gray"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsActive\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for detectors\&.
.PP
A \fBDetector\fP is an object that observes some aspect of a scene and reports true when the specified conditions are met\&. Typically these conditions involve hand information, but this is not required\&.
.PP
\fBDetector\fP implementations must call \fBActivate()\fP when their conditions are met and \fBDeactivate()\fP when those conditions are no longer met\&. Implementations should also call \fBDeactivate()\fP when they, or the object they are a component of become disabled\&. Implementations can call \fBActivate()\fP and \fBDeactivate()\fP more often than is strictly necessary\&. This \fBDetector\fP base class keeps track of the IsActive status and only dispatches events when the status changes\&.
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 33 of file Detector\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Leap\&.Unity\&.Detector\&.Activate ()\fC [virtual]\fP"
Invoked when this detector activates\&. Subclasses must call this function when the detector's conditions become true\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 55 of file Detector\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Detector\&.Deactivate ()\fC [virtual]\fP"
Invoked when this detector deactivates\&. Subclasses must call this function when the detector's conditions change from true to false\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 67 of file Detector\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Color Leap\&.Unity\&.Detector\&.DirectionColor = Color\&.white\fC [protected]\fP"

.PP
Definition at line 78 of file Detector\&.cs\&.
.SS "Color Leap\&.Unity\&.Detector\&.LimitColor = Color\&.blue\fC [protected]\fP"

.PP
Definition at line 77 of file Detector\&.cs\&.
.SS "Color Leap\&.Unity\&.Detector\&.NormalColor = Color\&.gray\fC [protected]\fP"

.PP
Definition at line 79 of file Detector\&.cs\&.
.SS "Color Leap\&.Unity\&.Detector\&.OffColor = Color\&.red\fC [protected]\fP"

.PP
Definition at line 76 of file Detector\&.cs\&.
.SS "UnityEvent Leap\&.Unity\&.Detector\&.OnActivate"
Dispatched when the detector activates (becomes true)\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 43 of file Detector\&.cs\&.
.SS "Color Leap\&.Unity\&.Detector\&.OnColor = Color\&.green\fC [protected]\fP"

.PP
Definition at line 75 of file Detector\&.cs\&.
.SS "UnityEvent Leap\&.Unity\&.Detector\&.OnDeactivate"
Dispatched when the detector deactivates (becomes false)\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 48 of file Detector\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Leap\&.Unity\&.Detector\&.IsActive\fC [get]\fP"
The current detector state\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 37 of file Detector\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
