.TH "Leap.Unity.OldRigHierarchy.UpgradeOptions" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.OldRigHierarchy.UpgradeOptions
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBcamera_removeEnableDepthBufferScript\fP = true"
.br
.ti -1c
.RI "bool \fBcamera_removeRightEyeCamera\fP = true"
.br
.ti -1c
.RI "bool \fBcamera_removeLeapEyeDislocator\fP = true"
.br
.ti -1c
.RI "bool \fBleapSpace_removeMissingScripts\fP = true"
.br
.ti -1c
.RI "bool \fBleapSpace_mergeExtraChildrenUpward\fP = true"
.br
.ti -1c
.RI "bool \fBlhc_removeMissingScripts\fP = true"
.br
.ti -1c
.RI "bool \fBlhc_mergeExtraChildrenUpward\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 963 of file LeapRigUpgrader\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Leap\&.Unity\&.OldRigHierarchy\&.UpgradeOptions\&.camera_removeEnableDepthBufferScript = true"

.PP
Definition at line 964 of file LeapRigUpgrader\&.cs\&.
.SS "bool Leap\&.Unity\&.OldRigHierarchy\&.UpgradeOptions\&.camera_removeLeapEyeDislocator = true"

.PP
Definition at line 966 of file LeapRigUpgrader\&.cs\&.
.SS "bool Leap\&.Unity\&.OldRigHierarchy\&.UpgradeOptions\&.camera_removeRightEyeCamera = true"

.PP
Definition at line 965 of file LeapRigUpgrader\&.cs\&.
.SS "bool Leap\&.Unity\&.OldRigHierarchy\&.UpgradeOptions\&.leapSpace_mergeExtraChildrenUpward = true"

.PP
Definition at line 968 of file LeapRigUpgrader\&.cs\&.
.SS "bool Leap\&.Unity\&.OldRigHierarchy\&.UpgradeOptions\&.leapSpace_removeMissingScripts = true"

.PP
Definition at line 967 of file LeapRigUpgrader\&.cs\&.
.SS "bool Leap\&.Unity\&.OldRigHierarchy\&.UpgradeOptions\&.lhc_mergeExtraChildrenUpward = true"

.PP
Definition at line 970 of file LeapRigUpgrader\&.cs\&.
.SS "bool Leap\&.Unity\&.OldRigHierarchy\&.UpgradeOptions\&.lhc_removeMissingScripts = true"

.PP
Definition at line 969 of file LeapRigUpgrader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
