.TH "Leap.Unity.Attributes.CombinablePropertyDrawer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.CombinablePropertyDrawer
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyDrawer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override float \fBGetPropertyHeight\fP (SerializedProperty property, GUIContent label)"
.br
.ti -1c
.RI "override void \fBOnGUI\fP (Rect position, SerializedProperty property, GUIContent label)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBGetAttributes\fP (SerializedProperty property, FieldInfo fieldInfo, out List< \fBCombinablePropertyAttribute\fP > outAttributes)"
.br
.ti -1c
.RI "static void \fBOnGUI\fP (List< \fBCombinablePropertyAttribute\fP > attributes, FieldInfo fieldInfo, Rect position, SerializedProperty property, GUIContent label)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file CombinablePropertyDrawer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Leap\&.Unity\&.Attributes\&.CombinablePropertyDrawer\&.GetAttributes (SerializedProperty property, FieldInfo fieldInfo, out List< \fBCombinablePropertyAttribute\fP > outAttributes)\fC [static]\fP"

.PP
Definition at line 29 of file CombinablePropertyDrawer\&.cs\&.
.SS "override float Leap\&.Unity\&.Attributes\&.CombinablePropertyDrawer\&.GetPropertyHeight (SerializedProperty property, GUIContent label)"

.PP
Definition at line 53 of file CombinablePropertyDrawer\&.cs\&.
.SS "override void Leap\&.Unity\&.Attributes\&.CombinablePropertyDrawer\&.OnGUI (Rect position, SerializedProperty property, GUIContent label)"

.PP
Definition at line 57 of file CombinablePropertyDrawer\&.cs\&.
.SS "static void Leap\&.Unity\&.Attributes\&.CombinablePropertyDrawer\&.OnGUI (List< \fBCombinablePropertyAttribute\fP > attributes, FieldInfo fieldInfo, Rect position, SerializedProperty property, GUIContent label)\fC [static]\fP"

.PP
Definition at line 64 of file CombinablePropertyDrawer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
