.TH "Leap.Unity.LeapImageRetriever" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.LeapImageRetriever \- Acquires images from a \fBLeapServiceProvider\fP and uploads image data as shader global data for use by any shaders that render those images\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEyeTextureData\fP"
.br
.ti -1c
.RI "class \fBLeapDistortionData\fP"
.br
.ti -1c
.RI "class \fBLeapTextureData\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApplyGammaCorrectionValues\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBGLOBAL_COLOR_SPACE_GAMMA_NAME\fP = '_LeapGlobalColorSpaceGamma'"
.br
.ti -1c
.RI "const string \fBGLOBAL_GAMMA_CORRECTION_EXPONENT_NAME\fP = '_LeapGlobalGammaCorrectionExponent'"
.br
.ti -1c
.RI "const string \fBGLOBAL_CAMERA_PROJECTION_NAME\fP = '_LeapGlobalProjection'"
.br
.ti -1c
.RI "const int \fBIMAGE_WARNING_WAIT\fP = 10"
.br
.ti -1c
.RI "const int \fBLEFT_IMAGE_INDEX\fP = 0"
.br
.ti -1c
.RI "const int \fBRIGHT_IMAGE_INDEX\fP = 1"
.br
.ti -1c
.RI "const float \fBIMAGE_SETTING_POLL_RATE\fP = 2\&.0f"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBProduceConsumeBuffer\fP< \fBImage\fP > \fB_imageQueue\fP = new \fBProduceConsumeBuffer\fP<\fBImage\fP>(32)"
.br
.ti -1c
.RI "\fBImage\fP \fB_currentImage\fP = null"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEyeTextureData\fP \fBTextureData\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Acquires images from a \fBLeapServiceProvider\fP and uploads image data as shader global data for use by any shaders that render those images\&. 

Note: To use the \fBLeapImageRetriever\fP, you must be on version 2\&.1 or newer and you must enable 'Allow Images' in your \fBLeap\fP Motion settings\&. 
.PP
Definition at line 27 of file LeapImageRetriever\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.LeapImageRetriever\&.ApplyGammaCorrectionValues ()"

.PP
Definition at line 346 of file LeapImageRetriever\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBImage\fP Leap\&.Unity\&.LeapImageRetriever\&._currentImage = null\fC [protected]\fP"

.PP
Definition at line 45 of file LeapImageRetriever\&.cs\&.
.SS "\fBProduceConsumeBuffer\fP<\fBImage\fP> Leap\&.Unity\&.LeapImageRetriever\&._imageQueue = new \fBProduceConsumeBuffer\fP<\fBImage\fP>(32)\fC [protected]\fP"

.PP
Definition at line 44 of file LeapImageRetriever\&.cs\&.
.SS "const string Leap\&.Unity\&.LeapImageRetriever\&.GLOBAL_CAMERA_PROJECTION_NAME = '_LeapGlobalProjection'"

.PP
Definition at line 30 of file LeapImageRetriever\&.cs\&.
.SS "const string Leap\&.Unity\&.LeapImageRetriever\&.GLOBAL_COLOR_SPACE_GAMMA_NAME = '_LeapGlobalColorSpaceGamma'"

.PP
Definition at line 28 of file LeapImageRetriever\&.cs\&.
.SS "const string Leap\&.Unity\&.LeapImageRetriever\&.GLOBAL_GAMMA_CORRECTION_EXPONENT_NAME = '_LeapGlobalGammaCorrectionExponent'"

.PP
Definition at line 29 of file LeapImageRetriever\&.cs\&.
.SS "const float Leap\&.Unity\&.LeapImageRetriever\&.IMAGE_SETTING_POLL_RATE = 2\&.0f"

.PP
Definition at line 34 of file LeapImageRetriever\&.cs\&.
.SS "const int Leap\&.Unity\&.LeapImageRetriever\&.IMAGE_WARNING_WAIT = 10"

.PP
Definition at line 31 of file LeapImageRetriever\&.cs\&.
.SS "const int Leap\&.Unity\&.LeapImageRetriever\&.LEFT_IMAGE_INDEX = 0"

.PP
Definition at line 32 of file LeapImageRetriever\&.cs\&.
.SS "const int Leap\&.Unity\&.LeapImageRetriever\&.RIGHT_IMAGE_INDEX = 1"

.PP
Definition at line 33 of file LeapImageRetriever\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBEyeTextureData\fP Leap\&.Unity\&.LeapImageRetriever\&.TextureData\fC [get]\fP"

.PP
Definition at line 47 of file LeapImageRetriever\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
