.TH "Leap.DroppedFrameEventArgs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.DroppedFrameEventArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.LeapEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDroppedFrameEventArgs\fP (Int64 frame_id, \fBeLeapDroppedFrameType\fP \fBtype\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Int64 \fBframeID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBeLeapDroppedFrameType\fP \fBreason\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 208 of file Events\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.DroppedFrameEventArgs\&.DroppedFrameEventArgs (Int64 frame_id, \fBeLeapDroppedFrameType\fP type)"

.PP
Definition at line 209 of file Events\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Int64 Leap\&.DroppedFrameEventArgs\&.frameID\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 214 of file Events\&.cs\&.
.SS "\fBeLeapDroppedFrameType\fP Leap\&.DroppedFrameEventArgs\&.reason\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 215 of file Events\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
