.TH "Leap.Unity.HandRepresentation" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.HandRepresentation
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHandRepresentation\fP (\fBHandModelManager\fP parent, \fBHand\fP hand, \fBChirality\fP repChirality, \fBModelType\fP repType)"
.br
.ti -1c
.RI "void \fBFinish\fP ()"
.br
.ti -1c
.RI "void \fBAddModel\fP (\fBHandModelBase\fP model)"
.br
.ti -1c
.RI "void \fBRemoveModel\fP (\fBHandModelBase\fP model)"
.br
.ti -1c
.RI "void \fBUpdateRepresentation\fP (\fBHand\fP hand)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBHandModelBase\fP > \fBhandModels\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBHandID\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBLastUpdatedTime\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsMarked\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBChirality\fP \fBRepChirality\fP\fC [get, protected set]\fP"
.br
.ti -1c
.RI "\fBModelType\fP \fBRepType\fP\fC [get, protected set]\fP"
.br
.ti -1c
.RI "\fBHand\fP \fBMostRecentHand\fP\fC [get, protected set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBHandRepresentation\fP is a container class that facillitates the \fBHandModelBase\fP lifecycle 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP The HandPool which creates HandRepresentations 
.br
\fIhandModel\fP the \fBHandModelBase\fP to be paired with \fBLeap\fP \fBHand\fP data\&. 
.br
\fIhand\fP The \fBLeap\fP \fBHand\fP data to paired with a \fBHandModelBase\fP 
.RE
.PP

.PP
Definition at line 19 of file HandRepresentation\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.HandRepresentation\&.HandRepresentation (\fBHandModelManager\fP parent, \fBHand\fP hand, \fBChirality\fP repChirality, \fBModelType\fP repType)"

.PP
Definition at line 29 of file HandRepresentation\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.HandRepresentation\&.AddModel (\fBHandModelBase\fP model)"

.PP
Definition at line 49 of file HandRepresentation\&.cs\&.
.SS "void Leap\&.Unity\&.HandRepresentation\&.Finish ()"
To be called if the \fBHandRepresentation\fP no longer has a \fBLeap\fP \fBHand\fP\&. 
.PP
Definition at line 38 of file HandRepresentation\&.cs\&.
.SS "void Leap\&.Unity\&.HandRepresentation\&.RemoveModel (\fBHandModelBase\fP model)"

.PP
Definition at line 66 of file HandRepresentation\&.cs\&.
.SS "void Leap\&.Unity\&.HandRepresentation\&.UpdateRepresentation (\fBHand\fP hand)"
Calls Updates in HandModelBases that are part of this \fBHandRepresentation\fP 
.PP
Definition at line 74 of file HandRepresentation\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBHandModelBase\fP> Leap\&.Unity\&.HandRepresentation\&.handModels"

.PP
Definition at line 27 of file HandRepresentation\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Leap\&.Unity\&.HandRepresentation\&.HandID\fC [get]\fP"

.PP
Definition at line 21 of file HandRepresentation\&.cs\&.
.SS "bool Leap\&.Unity\&.HandRepresentation\&.IsMarked\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 23 of file HandRepresentation\&.cs\&.
.SS "int Leap\&.Unity\&.HandRepresentation\&.LastUpdatedTime\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 22 of file HandRepresentation\&.cs\&.
.SS "\fBHand\fP Leap\&.Unity\&.HandRepresentation\&.MostRecentHand\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line 26 of file HandRepresentation\&.cs\&.
.SS "\fBChirality\fP Leap\&.Unity\&.HandRepresentation\&.RepChirality\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line 24 of file HandRepresentation\&.cs\&.
.SS "\fBModelType\fP Leap\&.Unity\&.HandRepresentation\&.RepType\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line 25 of file HandRepresentation\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
