.TH "LeapInternal.LEAP_FRAME_HEADER" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_FRAME_HEADER
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IntPtr \fBreserved\fP"
.br
.ti -1c
.RI "Int64 \fBframe_id\fP"
.br
.ti -1c
.RI "Int64 \fBtimestamp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 578 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Int64 LeapInternal\&.LEAP_FRAME_HEADER\&.frame_id"

.PP
Definition at line 580 of file LeapC\&.cs\&.
.SS "IntPtr LeapInternal\&.LEAP_FRAME_HEADER\&.reserved"

.PP
Definition at line 579 of file LeapC\&.cs\&.
.SS "Int64 LeapInternal\&.LEAP_FRAME_HEADER\&.timestamp"

.PP
Definition at line 581 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
