.TH "Leap.Unity.Space.LeapCylindricalSpace.Transformer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Space.LeapCylindricalSpace.Transformer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Space\&.IRadialTransformer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Vector3 \fBTransformPoint\fP (Vector3 localRectPos)"
.br
.RI "Transform a point from rect space to warped space\&. "
.ti -1c
.RI "Vector3 \fBInverseTransformPoint\fP (Vector3 localWarpedPos)"
.br
.RI "Transform a point from warped space to rect space\&. "
.ti -1c
.RI "Quaternion \fBTransformRotation\fP (Vector3 localRectPos, Quaternion localRectRot)"
.br
.RI "Transform a rotation from rect space to warped space\&. "
.ti -1c
.RI "Quaternion \fBInverseTransformRotation\fP (Vector3 localWarpedPos, Quaternion localWarpedRot)"
.br
.RI "Transform a rotation from warped space to rect space\&. "
.ti -1c
.RI "Vector3 \fBTransformDirection\fP (Vector3 localRectPos, Vector3 localRectDirection)"
.br
.RI "Transform a direction from rect space to warped space\&. "
.ti -1c
.RI "Vector3 \fBInverseTransformDirection\fP (Vector3 localWarpedPos, Vector3 localWarpedDirection)"
.br
.RI "Transform a direction from warped space to rect space\&. "
.ti -1c
.RI "Matrix4x4 \fBGetTransformationMatrix\fP (Vector3 localRectPos)"
.br
.RI "Get a transformation matrix that maps a position in rect space to a position in warped space\&. "
.ti -1c
.RI "Vector4 \fBGetVectorRepresentation\fP (Transform element)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBangleOffset\fP"
.br
.ti -1c
.RI "float \fBheightOffset\fP"
.br
.ti -1c
.RI "float \fBradiusOffset\fP"
.br
.ti -1c
.RI "float \fBradiansPerMeter\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLeapCylindricalSpace\fP \fBspace\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBLeapSpaceAnchor\fP \fBanchor\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file LeapCylindricalSpace\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Matrix4x4 Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.GetTransformationMatrix (Vector3 localRectPos)"

.PP
Get a transformation matrix that maps a position in rect space to a position in warped space\&. 
.PP
Implements \fBLeap\&.Unity\&.Space\&.ITransformer\fP\&.
.PP
Definition at line 130 of file LeapCylindricalSpace\&.cs\&.
.SS "Vector4 Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.GetVectorRepresentation (Transform element)"

.PP
Implements \fBLeap\&.Unity\&.Space\&.IRadialTransformer\fP\&.
.PP
Definition at line 150 of file LeapCylindricalSpace\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.InverseTransformDirection (Vector3 localWarpedSpace, Vector3 localWarpedDirection)"

.PP
Transform a direction from warped space to rect space\&. 
.PP
Implements \fBLeap\&.Unity\&.Space\&.ITransformer\fP\&.
.PP
Definition at line 122 of file LeapCylindricalSpace\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.InverseTransformPoint (Vector3 localWarpedSpace)"

.PP
Transform a point from warped space to rect space\&. 
.PP
Implements \fBLeap\&.Unity\&.Space\&.ITransformer\fP\&.
.PP
Definition at line 70 of file LeapCylindricalSpace\&.cs\&.
.SS "Quaternion Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.InverseTransformRotation (Vector3 localWarpedPos, Quaternion localWarpedRot)"

.PP
Transform a rotation from warped space to rect space\&. 
.PP
Implements \fBLeap\&.Unity\&.Space\&.ITransformer\fP\&.
.PP
Definition at line 101 of file LeapCylindricalSpace\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.TransformDirection (Vector3 localRectPos, Vector3 localRectDirection)"

.PP
Transform a direction from rect space to warped space\&. 
.PP
Implements \fBLeap\&.Unity\&.Space\&.ITransformer\fP\&.
.PP
Definition at line 109 of file LeapCylindricalSpace\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.TransformPoint (Vector3 localRectPos)"

.PP
Transform a point from rect space to warped space\&. 
.PP
Implements \fBLeap\&.Unity\&.Space\&.ITransformer\fP\&.
.PP
Definition at line 53 of file LeapCylindricalSpace\&.cs\&.
.SS "Quaternion Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.TransformRotation (Vector3 localRectPos, Quaternion localRectRot)"

.PP
Transform a rotation from rect space to warped space\&. 
.PP
Implements \fBLeap\&.Unity\&.Space\&.ITransformer\fP\&.
.PP
Definition at line 88 of file LeapCylindricalSpace\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.angleOffset"

.PP
Definition at line 48 of file LeapCylindricalSpace\&.cs\&.
.SS "float Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.heightOffset"

.PP
Definition at line 49 of file LeapCylindricalSpace\&.cs\&.
.SS "float Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.radiansPerMeter"

.PP
Definition at line 51 of file LeapCylindricalSpace\&.cs\&.
.SS "float Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.radiusOffset"

.PP
Definition at line 50 of file LeapCylindricalSpace\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBLeapSpaceAnchor\fP Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.anchor\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 46 of file LeapCylindricalSpace\&.cs\&.
.SS "\fBLeapCylindricalSpace\fP Leap\&.Unity\&.Space\&.LeapCylindricalSpace\&.Transformer\&.space\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 45 of file LeapCylindricalSpace\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
