.TH "LeapInternal.LEAP_CONFIG_RESPONSE_EVENT" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_CONFIG_RESPONSE_EVENT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UInt32 \fBrequestId\fP"
.br
.ti -1c
.RI "\fBLEAP_VARIANT_VALUE_TYPE\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 751 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "UInt32 LeapInternal\&.LEAP_CONFIG_RESPONSE_EVENT\&.requestId"

.PP
Definition at line 752 of file LeapC\&.cs\&.
.SS "\fBLEAP_VARIANT_VALUE_TYPE\fP LeapInternal\&.LEAP_CONFIG_RESPONSE_EVENT\&.value"

.PP
Definition at line 753 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
