.TH "Leap.Unity.Tests.TransformCopyIdentity" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Tests.TransformCopyIdentity
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Tests\&.FrameValidator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBIdsAreSame\fP ()"
.br
.ti -1c
.RI "void \fBAreBinaryEqual\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override \fBFrame\fP \fBcreateFrame\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBFrame\fP \fB_originalFrame\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file TransformCopyTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Tests\&.TransformCopyIdentity\&.AreBinaryEqual ()"

.PP
Definition at line 44 of file TransformCopyTest\&.cs\&.
.SS "override \fBFrame\fP Leap\&.Unity\&.Tests\&.TransformCopyIdentity\&.createFrame ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBLeap\&.Unity\&.Tests\&.FrameValidator\fP\&.
.PP
Definition at line 21 of file TransformCopyTest\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.TransformCopyIdentity\&.IdsAreSame ()"

.PP
Definition at line 27 of file TransformCopyTest\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFrame\fP Leap\&.Unity\&.Tests\&.TransformCopyIdentity\&._originalFrame\fC [protected]\fP"

.PP
Definition at line 19 of file TransformCopyTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
