.TH "Leap.Unity.Examples" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAngularSpeedTextBehaviour\fP"
.br
.ti -1c
.RI "class \fBAutopilotSystem\fP"
.br
.ti -1c
.RI "class \fBIgnoreCollisionsInChildren\fP"
.br
.RI "This utility script scans through its Transform's children and tells PhysX to ignore collisions between all pairs of Colliders it finds\&. This is particlarly useful, for example, for interfaces, where buttons shouldn't collide with other buttons\&. "
.ti -1c
.RI "class \fBInertiaPostProcessProvider\fP"
.br
.ti -1c
.RI "class \fBLinearReferenceSpawner\fP"
.br
.RI "This script keeps a GameObject in front of the ship, off to the side a bit\&. The skybox cannot provide a frame of reference for the linear motion of the ship, so the spawned object provides one instead\&. "
.ti -1c
.RI "class \fBLinearSpeedTextBehaviour\fP"
.br
.ti -1c
.RI "class \fBProjectionPostProcessProvider\fP"
.br
.ti -1c
.RI "class \fBRenderWireSphere\fP"
.br
.ti -1c
.RI "class \fBSimpleAnchorFeedback\fP"
.br
.ti -1c
.RI "class \fBSimpleFacingCameraCallbacks\fP"
.br
.ti -1c
.RI "class \fBSimpleInteractionEmission\fP"
.br
.ti -1c
.RI "class \fBSimpleMatchAnchorScaleAndState\fP"
.br
.ti -1c
.RI "class \fBSimpleRendererUtil\fP"
.br
.ti -1c
.RI "class \fBSimpleScaleUtil\fP"
.br
.ti -1c
.RI "class \fBSimpleTransformUtil\fP"
.br
.ti -1c
.RI "class \fBSpaceship\fP"
.br
.RI "The spaceship in this example is a kinematic rigidbody with a force API, but having a rigidbody on your \fBInteraction\fP Manager's reference frame is entirely optional\&. Any moving transform can provide a frame of reference for the \fBInteraction\fP Manager and encompassing interfaces\&. "
.ti -1c
.RI "class \fBSwapGraspExample\fP"
.br
.ti -1c
.RI "class \fBTransformHandle\fP"
.br
.ti -1c
.RI "class \fBTransformHandleEditor\fP"
.br
.ti -1c
.RI "class \fBTransformRotationHandle\fP"
.br
.ti -1c
.RI "class \fBTransformTool\fP"
.br
.ti -1c
.RI "class \fBTransformTranslationHandle\fP"
.br
.ti -1c
.RI "class \fBWorkstationBehaviourEditor\fP"
.br
.ti -1c
.RI "class \fBWorkstationBehaviourExample\fP"
.br
.RI "This example script constructs behavior for a very specific kind of UI object that can animate out a 'workstation' panel when thrown or placed outside of an anchor\&. "
.ti -1c
.RI "class \fBWorkstationPoseTest\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBIntObj\fP = \fBInteractionBehaviour\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTranslationAxis\fP { \fBTranslationAxis\&.X\fP, \fBTranslationAxis\&.Y\fP, \fBTranslationAxis\&.Z\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBLeap\&.Unity\&.Examples\&.IntObj\fP = typedef \fBInteractionBehaviour\fP"

.PP
Definition at line 15 of file SwapGraspExample\&.cs\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLeap\&.Unity\&.Examples\&.TranslationAxis\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIX \fP\fP
.TP
\fB\fIY \fP\fP
.TP
\fB\fIZ \fP\fP
.PP
Definition at line 17 of file TransformTranslationHandle\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
