.TH "LeapInternal.LeapC" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LeapC
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLEAP_RECORDING_PARAMETERS\fP"
.br
.ti -1c
.RI "struct \fBLEAP_RECORDING_STATUS\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "static long \fBGetNow\fP ()"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBCreateClockRebaser\fP (out IntPtr phClockRebaser)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBDestroyClockRebaser\fP (IntPtr hClockRebaser)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBUpdateRebase\fP (IntPtr hClockRebaser, Int64 userClock, Int64 leapClock)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBRebaseClock\fP (IntPtr hClockRebaser, Int64 userClock, out Int64 leapClock)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBCreateConnection\fP (ref \fBLEAP_CONNECTION_CONFIG\fP pConfig, out IntPtr pConnection)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBGetConnectionInfo\fP (IntPtr hConnection, ref \fBLEAP_CONNECTION_INFO\fP pInfo)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBOpenConnection\fP (IntPtr hConnection)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBSetAllocator\fP (IntPtr hConnection, ref \fBLEAP_ALLOCATOR\fP pAllocator)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBGetDeviceList\fP (IntPtr hConnection, [In, Out] \fBLEAP_DEVICE_REF\fP[] pArray, out UInt32 pnArray)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBOpenDevice\fP (\fBLEAP_DEVICE_REF\fP rDevice, out IntPtr pDevice)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBGetDeviceInfo\fP (IntPtr hDevice, ref \fBLEAP_DEVICE_INFO\fP info)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBSetPolicyFlags\fP (IntPtr hConnection, UInt64 set, UInt64 clear)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBSetDeviceFlags\fP (IntPtr hDevice, UInt64 set, UInt64 clear, out UInt64 prior)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBPollConnection\fP (IntPtr hConnection, UInt32 timeout, ref \fBLEAP_CONNECTION_MESSAGE\fP msg)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBGetFrameSize\fP (IntPtr hConnection, Int64 timestamp, out UInt64 pncbEvent)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBInterpolateFrame\fP (IntPtr hConnection, Int64 timestamp, IntPtr pEvent, UInt64 ncbEvent)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBInterpolateFrameFromTime\fP (IntPtr hConnection, Int64 timestamp, Int64 sourceTimestamp, IntPtr pEvent, UInt64 ncbEvent)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBInterpolateHeadPose\fP (IntPtr hConnection, Int64 timestamp, ref \fBLEAP_HEAD_POSE_EVENT\fP headPose)"
.br
.ti -1c
.RI "static \fBLEAP_VECTOR\fP \fBLeapPixelToRectilinear\fP (IntPtr hConnection, \fBeLeapPerspectiveType\fP camera, \fBLEAP_VECTOR\fP pixel)"
.br
.ti -1c
.RI "static \fBLEAP_VECTOR\fP \fBLeapRectilinearToPixel\fP (IntPtr hConnection, \fBeLeapPerspectiveType\fP camera, \fBLEAP_VECTOR\fP rectilinear)"
.br
.ti -1c
.RI "static void \fBCloseDevice\fP (IntPtr pDevice)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBCloseConnection\fP (IntPtr hConnection)"
.br
.ti -1c
.RI "static void \fBDestroyConnection\fP (IntPtr connection)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBRequestConfigValue\fP (IntPtr hConnection, string name, out UInt32 request_id)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBGetPointMappingSize\fP (IntPtr hConnection, ref ulong pSize)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBGetPointMapping\fP (IntPtr hConnection, IntPtr pointMapping, ref ulong pSize)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBRecordingOpen\fP (ref IntPtr ppRecording, string userPath, \fBLEAP_RECORDING_PARAMETERS\fP parameters)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBRecordingClose\fP (ref IntPtr ppRecording)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBLeapRecordingGetStatus\fP (IntPtr pRecording, ref \fBLEAP_RECORDING_STATUS\fP status)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBRecordingReadSize\fP (IntPtr pRecording, ref UInt64 pncbEvent)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBRecordingRead\fP (IntPtr pRecording, ref \fBLEAP_TRACKING_EVENT\fP pEvent, UInt64 ncbEvent)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBRecordingWrite\fP (IntPtr pRecording, ref \fBLEAP_TRACKING_EVENT\fP pEvent, ref UInt64 pnBytesWritten)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBLeapTelemetryProfiling\fP (IntPtr hConnection, ref \fBLEAP_TELEMETRY_DATA\fP telemetryData)"
.br
.ti -1c
.RI "static UInt64 \fBTelemetryGetNow\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBeLeapRS\fP \fBCreateConnection\fP (out IntPtr pConnection)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBGetDeviceCount\fP (IntPtr hConnection, out UInt32 deviceCount)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBSaveConfigValue\fP (IntPtr hConnection, string key, bool value, out UInt32 requestId)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBSaveConfigValue\fP (IntPtr hConnection, string key, Int32 value, out UInt32 requestId)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBSaveConfigValue\fP (IntPtr hConnection, string key, float value, out UInt32 requestId)"
.br
.ti -1c
.RI "static \fBeLeapRS\fP \fBSaveConfigValue\fP (IntPtr hConnection, string key, string value, out UInt32 requestId)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBDistortionSize\fP = 64"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 779 of file LeapC\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.CloseConnection (IntPtr hConnection)"

.SS "static void LeapInternal\&.LeapC\&.CloseDevice (IntPtr pDevice)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.CreateClockRebaser (out IntPtr phClockRebaser)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.CreateConnection (ref \fBLEAP_CONNECTION_CONFIG\fP pConfig, out IntPtr pConnection)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.CreateConnection (out IntPtr pConnection)\fC [static]\fP"

.PP
Definition at line 804 of file LeapC\&.cs\&.
.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.DestroyClockRebaser (IntPtr hClockRebaser)"

.SS "static void LeapInternal\&.LeapC\&.DestroyConnection (IntPtr connection)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.GetConnectionInfo (IntPtr hConnection, ref \fBLEAP_CONNECTION_INFO\fP pInfo)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.GetDeviceCount (IntPtr hConnection, out UInt32 deviceCount)\fC [static]\fP"

.PP
Definition at line 823 of file LeapC\&.cs\&.
.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.GetDeviceInfo (IntPtr hDevice, ref \fBLEAP_DEVICE_INFO\fP info)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.GetDeviceList (IntPtr hConnection, [In, Out] \fBLEAP_DEVICE_REF\fP [] pArray, out UInt32 pnArray)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.GetFrameSize (IntPtr hConnection, Int64 timestamp, out UInt64 pncbEvent)"

.SS "static long LeapInternal\&.LeapC\&.GetNow ()"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.GetPointMapping (IntPtr hConnection, IntPtr pointMapping, ref ulong pSize)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.GetPointMappingSize (IntPtr hConnection, ref ulong pSize)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.InterpolateFrame (IntPtr hConnection, Int64 timestamp, IntPtr pEvent, UInt64 ncbEvent)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.InterpolateFrameFromTime (IntPtr hConnection, Int64 timestamp, Int64 sourceTimestamp, IntPtr pEvent, UInt64 ncbEvent)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.InterpolateHeadPose (IntPtr hConnection, Int64 timestamp, ref \fBLEAP_HEAD_POSE_EVENT\fP headPose)"

.SS "static \fBLEAP_VECTOR\fP LeapInternal\&.LeapC\&.LeapPixelToRectilinear (IntPtr hConnection, \fBeLeapPerspectiveType\fP camera, \fBLEAP_VECTOR\fP pixel)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.LeapRecordingGetStatus (IntPtr pRecording, ref \fBLEAP_RECORDING_STATUS\fP status)"

.SS "static \fBLEAP_VECTOR\fP LeapInternal\&.LeapC\&.LeapRectilinearToPixel (IntPtr hConnection, \fBeLeapPerspectiveType\fP camera, \fBLEAP_VECTOR\fP rectilinear)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.LeapTelemetryProfiling (IntPtr hConnection, ref \fBLEAP_TELEMETRY_DATA\fP telemetryData)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.OpenConnection (IntPtr hConnection)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.OpenDevice (\fBLEAP_DEVICE_REF\fP rDevice, out IntPtr pDevice)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.PollConnection (IntPtr hConnection, UInt32 timeout, ref \fBLEAP_CONNECTION_MESSAGE\fP msg)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.RebaseClock (IntPtr hClockRebaser, Int64 userClock, out Int64 leapClock)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.RecordingClose (ref IntPtr ppRecording)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.RecordingOpen (ref IntPtr ppRecording, string userPath, \fBLEAP_RECORDING_PARAMETERS\fP parameters)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.RecordingRead (IntPtr pRecording, ref \fBLEAP_TRACKING_EVENT\fP pEvent, UInt64 ncbEvent)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.RecordingReadSize (IntPtr pRecording, ref UInt64 pncbEvent)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.RecordingWrite (IntPtr pRecording, ref \fBLEAP_TRACKING_EVENT\fP pEvent, ref UInt64 pnBytesWritten)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.RequestConfigValue (IntPtr hConnection, string name, out UInt32 request_id)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.SaveConfigValue (IntPtr hConnection, string key, bool value, out UInt32 requestId)\fC [static]\fP"

.PP
Definition at line 875 of file LeapC\&.cs\&.
.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.SaveConfigValue (IntPtr hConnection, string key, Int32 value, out UInt32 requestId)\fC [static]\fP"

.PP
Definition at line 881 of file LeapC\&.cs\&.
.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.SaveConfigValue (IntPtr hConnection, string key, float value, out UInt32 requestId)\fC [static]\fP"

.PP
Definition at line 887 of file LeapC\&.cs\&.
.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.SaveConfigValue (IntPtr hConnection, string key, string value, out UInt32 requestId)\fC [static]\fP"

.PP
Definition at line 893 of file LeapC\&.cs\&.
.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.SetAllocator (IntPtr hConnection, ref \fBLEAP_ALLOCATOR\fP pAllocator)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.SetDeviceFlags (IntPtr hDevice, UInt64 set, UInt64 clear, out UInt64 prior)"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.SetPolicyFlags (IntPtr hConnection, UInt64 set, UInt64 clear)"

.SS "static UInt64 LeapInternal\&.LeapC\&.TelemetryGetNow ()"

.SS "static \fBeLeapRS\fP LeapInternal\&.LeapC\&.UpdateRebase (IntPtr hClockRebaser, Int64 userClock, Int64 leapClock)"

.SH "Member Data Documentation"
.PP 
.SS "int LeapInternal\&.LeapC\&.DistortionSize = 64\fC [static]\fP"

.PP
Definition at line 781 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
