.TH "Leap.Unity.Tests.HandFactoryTwoHands" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Tests.HandFactoryTwoHands
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Tests\&.FrameValidator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCorrectHandCount\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override \fBFrame\fP \fBcreateFrame\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file HandFactoryTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Tests\&.HandFactoryTwoHands\&.CorrectHandCount ()"

.PP
Definition at line 22 of file HandFactoryTest\&.cs\&.
.SS "override \fBFrame\fP Leap\&.Unity\&.Tests\&.HandFactoryTwoHands\&.createFrame ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBLeap\&.Unity\&.Tests\&.FrameValidator\fP\&.
.PP
Definition at line 17 of file HandFactoryTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
