.TH "Leap.Unity.ExtendedFingerDetector" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.ExtendedFingerDetector
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Detector\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBPeriod\fP = \&.1f"
.br
.ti -1c
.RI "\fBHandModelBase\fP \fBHandModel\fP = null"
.br
.ti -1c
.RI "\fBPointingState\fP \fBThumb\fP = \fBPointingState\&.Either\fP"
.br
.ti -1c
.RI "\fBPointingState\fP \fBIndex\fP = \fBPointingState\&.Either\fP"
.br
.ti -1c
.RI "\fBPointingState\fP \fBMiddle\fP = \fBPointingState\&.Either\fP"
.br
.ti -1c
.RI "\fBPointingState\fP \fBRing\fP = \fBPointingState\&.Either\fP"
.br
.ti -1c
.RI "\fBPointingState\fP \fBPinky\fP = \fBPointingState\&.Either\fP"
.br
.ti -1c
.RI "int \fBMinimumExtendedCount\fP = 0"
.br
.ti -1c
.RI "int \fBMaximumExtendedCount\fP = 5"
.br
.ti -1c
.RI "bool \fBShowGizmos\fP = true"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Detects when specified fingers are in an extended or non-extended state\&.
.PP
You can specify whether each finger is extended, not extended, or in either state\&. This detector activates when every finger on the observed hand meets these conditions\&.
.PP
If added to a \fBHandModelBase\fP instance or one of its children, this detector checks the finger state at the interval specified by the Period variable\&. You can also specify which hand model to observe explicitly by setting handModel in the \fBUnity\fP editor or in code\&.
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 30 of file ExtendedFingerDetector\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHandModelBase\fP Leap\&.Unity\&.ExtendedFingerDetector\&.HandModel = null"
The \fBHandModelBase\fP instance to observe\&. Set automatically if not explicitly set in the editor\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 46 of file ExtendedFingerDetector\&.cs\&.
.SS "\fBPointingState\fP Leap\&.Unity\&.ExtendedFingerDetector\&.Index = \fBPointingState\&.Either\fP"
The required index finger state\&. 
.PP
Definition at line 54 of file ExtendedFingerDetector\&.cs\&.
.SS "int Leap\&.Unity\&.ExtendedFingerDetector\&.MaximumExtendedCount = 5"
The most fingers allowed to be extended for the detector to activate\&. 
.PP
Definition at line 73 of file ExtendedFingerDetector\&.cs\&.
.SS "\fBPointingState\fP Leap\&.Unity\&.ExtendedFingerDetector\&.Middle = \fBPointingState\&.Either\fP"
The required middle finger state\&. 
.PP
Definition at line 57 of file ExtendedFingerDetector\&.cs\&.
.SS "int Leap\&.Unity\&.ExtendedFingerDetector\&.MinimumExtendedCount = 0"
How many fingers must be extended for the detector to activate\&. 
.PP
Definition at line 69 of file ExtendedFingerDetector\&.cs\&.
.SS "float Leap\&.Unity\&.ExtendedFingerDetector\&.Period = \&.1f"
The interval at which to check finger state\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 38 of file ExtendedFingerDetector\&.cs\&.
.SS "\fBPointingState\fP Leap\&.Unity\&.ExtendedFingerDetector\&.Pinky = \fBPointingState\&.Either\fP"
The required pinky finger state\&. 
.PP
Definition at line 63 of file ExtendedFingerDetector\&.cs\&.
.SS "\fBPointingState\fP Leap\&.Unity\&.ExtendedFingerDetector\&.Ring = \fBPointingState\&.Either\fP"
The required ring finger state\&. 
.PP
Definition at line 60 of file ExtendedFingerDetector\&.cs\&.
.SS "bool Leap\&.Unity\&.ExtendedFingerDetector\&.ShowGizmos = true"
Whether to draw the detector's Gizmos for debugging\&. (Not every detector provides gizmos\&.) 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 79 of file ExtendedFingerDetector\&.cs\&.
.SS "\fBPointingState\fP Leap\&.Unity\&.ExtendedFingerDetector\&.Thumb = \fBPointingState\&.Either\fP"
The required thumb state\&. 
.PP
Definition at line 51 of file ExtendedFingerDetector\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
