.TH "Leap.Arm" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Arm \- The \fBArm\fP class represents the forearm\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Bone\fP, and IEquatable< Arm >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArm\fP ()"
.br
.RI "Constructs a default \fBArm\fP object\&. Get valid \fBArm\fP objects from a \fBHand\fP object\&. "
.ti -1c
.RI "\fBArm\fP (\fBVector\fP elbow, \fBVector\fP wrist, \fBVector\fP center, \fBVector\fP direction, float length, float width, \fBLeapQuaternion\fP rotation)"
.br
.RI "Constructs a new \fBArm\fP object\&. "
.ti -1c
.RI "bool \fBEquals\fP (\fBArm\fP other)"
.br
.RI "Compare \fBArm\fP object equality\&. Two \fBArm\fP objects are equal if and only if both \fBArm\fP objects represent the exact same physical arm in the same frame and both \fBArm\fP objects are valid\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "A string containing a brief, human readable description of the \fBArm\fP object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBVector\fP \fBElbowPosition\fP\fC [get]\fP"
.br
.RI "The position of the elbow\&. If not in view, the elbow position is estimated based on typical human anatomical proportions\&. "
.ti -1c
.RI "\fBVector\fP \fBWristPosition\fP\fC [get]\fP"
.br
.RI "The position of the wrist\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBArm\fP class represents the forearm\&. 


.PP
Definition at line 17 of file Arm\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Arm\&.Arm ()"

.PP
Constructs a default \fBArm\fP object\&. Get valid \fBArm\fP objects from a \fBHand\fP object\&. 
.PP
\fBSince:\fP
.RS 4
2\&.0\&.3 
.RE
.PP

.PP
Definition at line 25 of file Arm\&.cs\&.
.SS "Leap\&.Arm\&.Arm (\fBVector\fP elbow, \fBVector\fP wrist, \fBVector\fP center, \fBVector\fP direction, float length, float width, \fBLeapQuaternion\fP rotation)"

.PP
Constructs a new \fBArm\fP object\&. 
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 31 of file Arm\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Leap\&.Arm\&.Equals (\fBArm\fP other)"

.PP
Compare \fBArm\fP object equality\&. Two \fBArm\fP objects are equal if and only if both \fBArm\fP objects represent the exact same physical arm in the same frame and both \fBArm\fP objects are valid\&. 
.PP
\fBSince:\fP
.RS 4
2\&.0\&.3 
.RE
.PP

.PP
Definition at line 53 of file Arm\&.cs\&.
.SS "override string Leap\&.Arm\&.ToString ()"

.PP
A string containing a brief, human readable description of the \fBArm\fP object\&. 
.PP
\fBSince:\fP
.RS 4
2\&.0\&.3 
.RE
.PP

.PP
Definition at line 61 of file Arm\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBVector\fP Leap\&.Arm\&.ElbowPosition\fC [get]\fP"

.PP
The position of the elbow\&. If not in view, the elbow position is estimated based on typical human anatomical proportions\&. 
.PP
\fBSince:\fP
.RS 4
2\&.0\&.3 
.RE
.PP

.PP
Definition at line 72 of file Arm\&.cs\&.
.SS "\fBVector\fP Leap\&.Arm\&.WristPosition\fC [get]\fP"

.PP
The position of the wrist\&. Note that the wrist position is not collocated with the end of any bone in the hand\&. There is a gap of a few centimeters since the carpal bones are not included in the skeleton model\&.
.PP
\fBSince:\fP
.RS 4
2\&.0\&.3 
.RE
.PP

.PP
Definition at line 87 of file Arm\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
