.TH "LeapInternal.LEAP_VARIANT_REF_TYPE" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_VARIANT_REF_TYPE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBeLeapValueType\fP \fBtype\fP"
.br
.ti -1c
.RI "string \fBstringValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 745 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string LeapInternal\&.LEAP_VARIANT_REF_TYPE\&.stringValue"

.PP
Definition at line 747 of file LeapC\&.cs\&.
.SS "\fBeLeapValueType\fP LeapInternal\&.LEAP_VARIANT_REF_TYPE\&.type"

.PP
Definition at line 746 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
