.TH "Leap.Unity.Examples.IgnoreCollisionsInChildren" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples.IgnoreCollisionsInChildren \- This utility script scans through its Transform's children and tells PhysX to ignore collisions between all pairs of Colliders it finds\&. This is particlarly useful, for example, for interfaces, where buttons shouldn't collide with other buttons\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBIgnoreCollisionsInChildrenOf\fP (Transform t, bool ignore=true)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This utility script scans through its Transform's children and tells PhysX to ignore collisions between all pairs of Colliders it finds\&. This is particlarly useful, for example, for interfaces, where buttons shouldn't collide with other buttons\&. 

This is not the recommended strategy in general: It is much more optimal for your application to put interface objects on a layer and disable self-collision for that layer in your Physics settings (Edit / Project Settings / Physics)\&. 
.PP
Definition at line 26 of file IgnoreCollisionsInChildren\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Leap\&.Unity\&.Examples\&.IgnoreCollisionsInChildren\&.IgnoreCollisionsInChildrenOf (Transform t, bool ignore = \fCtrue\fP)\fC [static]\fP"

.PP
Definition at line 32 of file IgnoreCollisionsInChildren\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
