.TH "Leap.Unity.LeapImageRetriever.EyeTextureData" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.LeapImageRetriever.EyeTextureData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEyeTextureData\fP ()"
.br
.ti -1c
.RI "bool \fBCheckStale\fP (\fBImage\fP image)"
.br
.ti -1c
.RI "void \fBMarkStale\fP ()"
.br
.ti -1c
.RI "void \fBReconstruct\fP (\fBImage\fP image)"
.br
.ti -1c
.RI "void \fBUpdateTextures\fP (\fBImage\fP image)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBResetGlobalShaderValues\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBLeapTextureData\fP \fBTextureData\fP"
.br
.ti -1c
.RI "readonly \fBLeapDistortionData\fP \fBDistortion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 190 of file LeapImageRetriever\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.LeapImageRetriever\&.EyeTextureData\&.EyeTextureData ()"

.PP
Definition at line 209 of file LeapImageRetriever\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Leap\&.Unity\&.LeapImageRetriever\&.EyeTextureData\&.CheckStale (\fBImage\fP image)"

.PP
Definition at line 214 of file LeapImageRetriever\&.cs\&.
.SS "void Leap\&.Unity\&.LeapImageRetriever\&.EyeTextureData\&.MarkStale ()"

.PP
Definition at line 220 of file LeapImageRetriever\&.cs\&.
.SS "void Leap\&.Unity\&.LeapImageRetriever\&.EyeTextureData\&.Reconstruct (\fBImage\fP image)"

.PP
Definition at line 224 of file LeapImageRetriever\&.cs\&.
.SS "static void Leap\&.Unity\&.LeapImageRetriever\&.EyeTextureData\&.ResetGlobalShaderValues ()\fC [static]\fP"

.PP
Definition at line 199 of file LeapImageRetriever\&.cs\&.
.SS "void Leap\&.Unity\&.LeapImageRetriever\&.EyeTextureData\&.UpdateTextures (\fBImage\fP image)"

.PP
Definition at line 230 of file LeapImageRetriever\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBLeapDistortionData\fP Leap\&.Unity\&.LeapImageRetriever\&.EyeTextureData\&.Distortion"

.PP
Definition at line 196 of file LeapImageRetriever\&.cs\&.
.SS "readonly \fBLeapTextureData\fP Leap\&.Unity\&.LeapImageRetriever\&.EyeTextureData\&.TextureData"

.PP
Definition at line 195 of file LeapImageRetriever\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
