.TH "LeapInternal.LEAP_ALLOCATOR" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_ALLOCATOR
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAllocate\fP \fBallocate\fP"
.br
.ti -1c
.RI "\fBDeallocate\fP \fBdeallocate\fP"
.br
.ti -1c
.RI "IntPtr \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 492 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAllocate\fP LeapInternal\&.LEAP_ALLOCATOR\&.allocate"

.PP
Definition at line 494 of file LeapC\&.cs\&.
.SS "\fBDeallocate\fP LeapInternal\&.LEAP_ALLOCATOR\&.deallocate"

.PP
Definition at line 496 of file LeapC\&.cs\&.
.SS "IntPtr LeapInternal\&.LEAP_ALLOCATOR\&.state"

.PP
Definition at line 497 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
