.TH "Leap.LeapCSharp.Tests.DeviceTests" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.LeapCSharp.Tests.DeviceTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBDeviceIsConnected\fP ()"
.br
.ti -1c
.RI "void \fBDevice_operator_equals\fP ()"
.br
.ti -1c
.RI "void \fBDeviceList_operator_index\fP ()"
.br
.ti -1c
.RI "void \fBDeviceList_isEmpty\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file DeviceTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.LeapCSharp\&.Tests\&.DeviceTests\&.Device_operator_equals ()"

.PP
Definition at line 31 of file DeviceTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.DeviceTests\&.DeviceIsConnected ()"

.PP
Definition at line 25 of file DeviceTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.DeviceTests\&.DeviceList_isEmpty ()"

.PP
Definition at line 53 of file DeviceTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.DeviceTests\&.DeviceList_operator_index ()"

.PP
Definition at line 42 of file DeviceTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.DeviceTests\&.Init ()"

.PP
Definition at line 19 of file DeviceTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
