.TH "Leap.Unity.Examples.Spaceship" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples.Spaceship \- The spaceship in this example is a kinematic rigidbody with a force API, but having a rigidbody on your \fBInteraction\fP Manager's reference frame is entirely optional\&. Any moving transform can provide a frame of reference for the \fBInteraction\fP Manager and encompassing interfaces\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddForce\fP (Vector3 force)"
.br
.ti -1c
.RI "void \fBAddForceAtPosition\fP (Vector3 force, Vector3 position)"
.br
.ti -1c
.RI "void \fBAddShipAlignedTorque\fP (Vector3 shipAlignedTorque)"
.br
.ti -1c
.RI "void \fBAddShipAlignedForce\fP (Vector3 shipAlignedForce)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Rigidbody \fBrigidbody\fP\fC [get]\fP"
.br
.RI "The ship contains Colliders, so it is given a kinematic Rigidbody to prevent the overhead of moving Colliders every frame\&. "
.ti -1c
.RI "Vector3 \fBvelocity\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Vector3 \fBshipAlignedVelocity\fP\fC [get]\fP"
.br
.ti -1c
.RI "Vector3 \fBangularVelocity\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Vector3 \fBshipAlignedAngularVelocity\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The spaceship in this example is a kinematic rigidbody with a force API, but having a rigidbody on your \fBInteraction\fP Manager's reference frame is entirely optional\&. Any moving transform can provide a frame of reference for the \fBInteraction\fP Manager and encompassing interfaces\&. 

This script provides a 'velocity' and 'angular velocity' abstraction for the \fBAutopilotSystem\fP in the example, and moves the ship's transform appropriately\&.
.PP
The important thing when using a moving reference frame is that you move the \fBInteraction\fP Manager's transform before its FixedUpdate runs\&. This script uses the manager's OnPrePhysicalUpdate to ensure this, which it calls at the beginning of its FixedUpdate\&. 
.PP
Definition at line 34 of file Spaceship\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Examples\&.Spaceship\&.AddForce (Vector3 force)"

.PP
Definition at line 124 of file Spaceship\&.cs\&.
.SS "void Leap\&.Unity\&.Examples\&.Spaceship\&.AddForceAtPosition (Vector3 force, Vector3 position)"

.PP
Definition at line 128 of file Spaceship\&.cs\&.
.SS "void Leap\&.Unity\&.Examples\&.Spaceship\&.AddShipAlignedForce (Vector3 shipAlignedForce)"

.PP
Definition at line 147 of file Spaceship\&.cs\&.
.SS "void Leap\&.Unity\&.Examples\&.Spaceship\&.AddShipAlignedTorque (Vector3 shipAlignedTorque)"

.PP
Definition at line 143 of file Spaceship\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Vector3 Leap\&.Unity\&.Examples\&.Spaceship\&.angularVelocity\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 63 of file Spaceship\&.cs\&.
.SS "Rigidbody Leap\&.Unity\&.Examples\&.Spaceship\&.rigidbody\fC [get]\fP"

.PP
The ship contains Colliders, so it is given a kinematic Rigidbody to prevent the overhead of moving Colliders every frame\&. Setting the rigidbody's position is not important for the \fBInteraction\fP Manager; only the transform's positional movement establishes a moving reference frame! 
.PP
Definition at line 48 of file Spaceship\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.Examples\&.Spaceship\&.shipAlignedAngularVelocity\fC [get]\fP"

.PP
Definition at line 68 of file Spaceship\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.Examples\&.Spaceship\&.shipAlignedVelocity\fC [get]\fP"

.PP
Definition at line 58 of file Spaceship\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.Examples\&.Spaceship\&.velocity\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 53 of file Spaceship\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
