.TH "Leap.Unity.Animation.TransformTweenBehaviour" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Animation.TransformTweenBehaviour \- This is a wrapper MonoBehaviour that demonstrates and exposes some of the basic functionality of the \fBTween\fP library\&. Tweens can interpolate between more than just Transform properties, so don't be afraid to roll your own\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFloatEvent\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBEventType\fP { \fBEventType\&.OnLeaveStart\fP = 110, \fBEventType\&.OnReachEnd\fP = 120, \fBEventType\&.OnLeaveEnd\fP = 130, \fBEventType\&.OnReachStart\fP = 140 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPlayTween\fP ()"
.br
.RI "Tweens play forward by default, but at any time past the starting state they can also be played backwards to return to the starting state\&. See the tween property for more direct control of this behaviour's tween\&. "
.ti -1c
.RI "void \fBPlayTween\fP (\fBDirection\fP tweenDirection=\fBDirection\&.Forward\fP, float afterDelay=0F)"
.br
.ti -1c
.RI "void \fBPlayForward\fP ()"
.br
.ti -1c
.RI "void \fBPlayBackward\fP ()"
.br
.ti -1c
.RI "void \fBPlayForwardAfterDelay\fP (float delay=0F)"
.br
.ti -1c
.RI "void \fBPlayBackwardAfterDelay\fP (float delay=0F)"
.br
.ti -1c
.RI "void \fBStopTween\fP ()"
.br
.RI "Stops the underlying tween and resets it to the starting state\&. "
.ti -1c
.RI "void \fBSetTargetToStart\fP ()"
.br
.ti -1c
.RI "void \fBSetTargetToEnd\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBtargetTransform\fP"
.br
.ti -1c
.RI "Transform \fBstartTransform\fP"
.br
.ti -1c
.RI "Transform \fBendTransform\fP"
.br
.ti -1c
.RI "bool \fBstartAtEnd\fP = false"
.br
.ti -1c
.RI "bool \fBtweenLocalPosition\fP = true"
.br
.ti -1c
.RI "bool \fBtweenLocalRotation\fP = true"
.br
.ti -1c
.RI "bool \fBtweenLocalScale\fP = true"
.br
.ti -1c
.RI "float \fBtweenDuration\fP = 0\&.25F"
.br
.ti -1c
.RI "\fBSmoothType\fP \fBtweenSmoothType\fP = \fBSmoothType\&.Smooth\fP"
.br
.ti -1c
.RI "Action< float > \fBOnProgress\fP = (progress) => { }"
.br
.ti -1c
.RI "Action \fBOnLeaveStart\fP = () => { }"
.br
.ti -1c
.RI "Action \fBOnReachEnd\fP = () => { }"
.br
.ti -1c
.RI "Action \fBOnLeaveEnd\fP = () => { }"
.br
.ti -1c
.RI "Action \fBOnReachStart\fP = () => { }"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTween\fP \fBtween\fP\fC [get, set]\fP"
.br
.RI "Returns the \fBTween\fP object the TransformTween behaviour produces on Start()\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is a wrapper MonoBehaviour that demonstrates and exposes some of the basic functionality of the \fBTween\fP library\&. Tweens can interpolate between more than just Transform properties, so don't be afraid to roll your own\&. 


.PP
Definition at line 24 of file TransformTweenBehaviour\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBLeap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.EventType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOnLeaveStart \fP\fP
.TP
\fB\fIOnReachEnd \fP\fP
.TP
\fB\fIOnLeaveEnd \fP\fP
.TP
\fB\fIOnReachStart \fP\fP
.PP
Definition at line 200 of file TransformTweenBehaviour\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.PlayBackward ()"

.PP
Definition at line 157 of file TransformTweenBehaviour\&.cs\&.
.SS "void Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.PlayBackwardAfterDelay (float delay = \fC0F\fP)"

.PP
Definition at line 165 of file TransformTweenBehaviour\&.cs\&.
.SS "void Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.PlayForward ()"

.PP
Definition at line 153 of file TransformTweenBehaviour\&.cs\&.
.SS "void Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.PlayForwardAfterDelay (float delay = \fC0F\fP)"

.PP
Definition at line 161 of file TransformTweenBehaviour\&.cs\&.
.SS "void Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.PlayTween ()"

.PP
Tweens play forward by default, but at any time past the starting state they can also be played backwards to return to the starting state\&. See the tween property for more direct control of this behaviour's tween\&. 
.PP
Definition at line 134 of file TransformTweenBehaviour\&.cs\&.
.SS "void Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.PlayTween (\fBDirection\fP tweenDirection = \fC\fBDirection\&.Forward\fP\fP, float afterDelay = \fC0F\fP)"

.PP
Definition at line 138 of file TransformTweenBehaviour\&.cs\&.
.SS "void Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.SetTargetToEnd ()"

.PP
Definition at line 180 of file TransformTweenBehaviour\&.cs\&.
.SS "void Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.SetTargetToStart ()"

.PP
Definition at line 176 of file TransformTweenBehaviour\&.cs\&.
.SS "void Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.StopTween ()"

.PP
Stops the underlying tween and resets it to the starting state\&. 
.PP
Definition at line 172 of file TransformTweenBehaviour\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.endTransform"

.PP
Definition at line 32 of file TransformTweenBehaviour\&.cs\&.
.SS "Action Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.OnLeaveEnd = () => { }"

.PP
Definition at line 50 of file TransformTweenBehaviour\&.cs\&.
.SS "Action Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.OnLeaveStart = () => { }"

.PP
Definition at line 48 of file TransformTweenBehaviour\&.cs\&.
.SS "Action<float> Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.OnProgress = (progress) => { }"

.PP
Definition at line 46 of file TransformTweenBehaviour\&.cs\&.
.SS "Action Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.OnReachEnd = () => { }"

.PP
Definition at line 49 of file TransformTweenBehaviour\&.cs\&.
.SS "Action Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.OnReachStart = () => { }"

.PP
Definition at line 51 of file TransformTweenBehaviour\&.cs\&.
.SS "bool Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.startAtEnd = false"

.PP
Definition at line 34 of file TransformTweenBehaviour\&.cs\&.
.SS "Transform Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.startTransform"

.PP
Definition at line 30 of file TransformTweenBehaviour\&.cs\&.
.SS "Transform Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.targetTransform"

.PP
Definition at line 27 of file TransformTweenBehaviour\&.cs\&.
.SS "float Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.tweenDuration = 0\&.25F"

.PP
Definition at line 41 of file TransformTweenBehaviour\&.cs\&.
.SS "bool Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.tweenLocalPosition = true"

.PP
Definition at line 37 of file TransformTweenBehaviour\&.cs\&.
.SS "bool Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.tweenLocalRotation = true"

.PP
Definition at line 38 of file TransformTweenBehaviour\&.cs\&.
.SS "bool Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.tweenLocalScale = true"

.PP
Definition at line 39 of file TransformTweenBehaviour\&.cs\&.
.SS "\fBSmoothType\fP Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.tweenSmoothType = \fBSmoothType\&.Smooth\fP"

.PP
Definition at line 42 of file TransformTweenBehaviour\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBTween\fP Leap\&.Unity\&.Animation\&.TransformTweenBehaviour\&.tween\fC [get]\fP, \fC [set]\fP"

.PP
Returns the \fBTween\fP object the TransformTween behaviour produces on Start()\&. Use this to play or otherwise manipulate the animation\&. 
.PP
Definition at line 61 of file TransformTweenBehaviour\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
