.TH "Leap.Unity.Attributes.DisableIfAll" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.DisableIfAll
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Attributes\&.DisableIfBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisableIfAll\fP (string propertyName1, string propertyName2, object areEqualTo=null, object areNotEqualTo=null)"
.br
.ti -1c
.RI "\fBDisableIfAll\fP (string propertyName1, string propertyName2, string propertyName3, object areEqualTo=null, object areNotEqualTo=null)"
.br
.ti -1c
.RI "\fBDisableIfAll\fP (string propertyName1, string propertyName2, string propertyName3, string propertyName4, object areEqualTo=null, object areNotEqualTo=null)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 109 of file DisableIf\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Attributes\&.DisableIfAll\&.DisableIfAll (string propertyName1, string propertyName2, object areEqualTo = \fCnull\fP, object areNotEqualTo = \fCnull\fP)"

.PP
Definition at line 111 of file DisableIf\&.cs\&.
.SS "Leap\&.Unity\&.Attributes\&.DisableIfAll\&.DisableIfAll (string propertyName1, string propertyName2, string propertyName3, object areEqualTo = \fCnull\fP, object areNotEqualTo = \fCnull\fP)"

.PP
Definition at line 114 of file DisableIf\&.cs\&.
.SS "Leap\&.Unity\&.Attributes\&.DisableIfAll\&.DisableIfAll (string propertyName1, string propertyName2, string propertyName3, string propertyName4, object areEqualTo = \fCnull\fP, object areNotEqualTo = \fCnull\fP)"

.PP
Definition at line 117 of file DisableIf\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
