.TH "Leap.Unity.Utils.HorizontalLineRectEnumerator" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Utils.HorizontalLineRectEnumerator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHorizontalLineRectEnumerator\fP (Rect \fBrect\fP, int \fBnumLines\fP)"
.br
.ti -1c
.RI "bool \fBMoveNext\fP ()"
.br
.ti -1c
.RI "\fBHorizontalLineRectEnumerator\fP \fBGetEnumerator\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "\fBQuery\fP< Rect > \fBQuery\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Rect \fBrect\fP"
.br
.ti -1c
.RI "int \fBnumLines\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBeachHeight\fP\fC [get]\fP"
.br
.ti -1c
.RI "Rect \fBCurrent\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1624 of file Utils\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Utils\&.HorizontalLineRectEnumerator\&.HorizontalLineRectEnumerator (Rect rect, int numLines)"

.PP
Definition at line 1629 of file Utils\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBHorizontalLineRectEnumerator\fP Leap\&.Unity\&.Utils\&.HorizontalLineRectEnumerator\&.GetEnumerator ()"

.PP
Definition at line 1644 of file Utils\&.cs\&.
.SS "bool Leap\&.Unity\&.Utils\&.HorizontalLineRectEnumerator\&.MoveNext ()"

.PP
Definition at line 1640 of file Utils\&.cs\&.
.SS "\fBQuery\fP<Rect> Leap\&.Unity\&.Utils\&.HorizontalLineRectEnumerator\&.Query ()"

.PP
Definition at line 1650 of file Utils\&.cs\&.
.SS "void Leap\&.Unity\&.Utils\&.HorizontalLineRectEnumerator\&.Reset ()"

.PP
Definition at line 1646 of file Utils\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int Leap\&.Unity\&.Utils\&.HorizontalLineRectEnumerator\&.index"

.PP
Definition at line 1627 of file Utils\&.cs\&.
.SS "int Leap\&.Unity\&.Utils\&.HorizontalLineRectEnumerator\&.numLines"

.PP
Definition at line 1626 of file Utils\&.cs\&.
.SS "Rect Leap\&.Unity\&.Utils\&.HorizontalLineRectEnumerator\&.rect"

.PP
Definition at line 1625 of file Utils\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Rect Leap\&.Unity\&.Utils\&.HorizontalLineRectEnumerator\&.Current\fC [get]\fP"

.PP
Definition at line 1637 of file Utils\&.cs\&.
.SS "float Leap\&.Unity\&.Utils\&.HorizontalLineRectEnumerator\&.eachHeight\fC [get]\fP"

.PP
Definition at line 1635 of file Utils\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
