.TH "Leap.Unity.RuntimeGizmos.RuntimeGizmoManager" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.RuntimeGizmos.RuntimeGizmoManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBTryGetGizmoDrawer\fP (out \fBRuntimeGizmoDrawer\fP drawer)"
.br
.RI "Tries to get a gizmo drawer\&. Will fail if there is no Gizmo manager in the scene, or if it is disabled\&. "
.ti -1c
.RI "static bool \fBTryGetGizmoDrawer\fP (GameObject attatchedGameObject, out \fBRuntimeGizmoDrawer\fP drawer)"
.br
.RI "Tries to get a gizmo drawer for a given gameObject\&. Will fail if there is no gizmo manager in the scene, or if it is disabled\&. Will also fail if there is a disable \fBRuntimeGizmoToggle\fP as a parent of the gameObject\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBDEFAULT_SHADER_NAME\fP = 'Hidden/Runtime Gizmos'"
.br
.ti -1c
.RI "const int \fBCIRCLE_RESOLUTION\fP = 32"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnValidate\fP ()"
.br
.ti -1c
.RI "virtual void \fBReset\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBonPostRender\fP (Camera camera)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBareGizmosDisabled\fP (Transform transform)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fB_displayInGameView\fP = true"
.br
.ti -1c
.RI "bool \fB_enabledForBuild\fP = true"
.br
.ti -1c
.RI "Mesh \fB_sphereMesh\fP"
.br
.ti -1c
.RI "Shader \fB_gizmoShader\fP"
.br
.ti -1c
.RI "Mesh \fB_cubeMesh\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fBRuntimeGizmoDrawer\fP \fB_backDrawer\fP = null"
.br
.ti -1c
.RI "static \fBRuntimeGizmoDrawer\fP \fB_frontDrawer\fP = null"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static Action< \fBRuntimeGizmoDrawer\fP > \fBOnPostRenderGizmos\fP"
.br
.RI "Subscribe to this event if you want to draw gizmos after rendering is complete\&. Doing gizmo rendering inside of the normal Camera\&.onPostRender event will cause rendering artifacts\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file RuntimeGizmoManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.areGizmosDisabled (Transform transform)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 215 of file RuntimeGizmoManager\&.cs\&.
.SS "virtual void Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.OnDisable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 140 of file RuntimeGizmoManager\&.cs\&.
.SS "virtual void Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.OnEnable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 115 of file RuntimeGizmoManager\&.cs\&.
.SS "void Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.onPostRender (Camera camera)\fC [protected]\fP"

.PP
Definition at line 173 of file RuntimeGizmoManager\&.cs\&.
.SS "virtual void Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.OnValidate ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 94 of file RuntimeGizmoManager\&.cs\&.
.SS "virtual void Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.Reset ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 111 of file RuntimeGizmoManager\&.cs\&.
.SS "static bool Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.TryGetGizmoDrawer (out \fBRuntimeGizmoDrawer\fP drawer)\fC [static]\fP"

.PP
Tries to get a gizmo drawer\&. Will fail if there is no Gizmo manager in the scene, or if it is disabled\&. The gizmo matrix will be set to the identity matrix\&. The gizmo color will be set to white\&. 
.PP
Definition at line 66 of file RuntimeGizmoManager\&.cs\&.
.SS "static bool Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.TryGetGizmoDrawer (GameObject attatchedGameObject, out \fBRuntimeGizmoDrawer\fP drawer)\fC [static]\fP"

.PP
Tries to get a gizmo drawer for a given gameObject\&. Will fail if there is no gizmo manager in the scene, or if it is disabled\&. Will also fail if there is a disable \fBRuntimeGizmoToggle\fP as a parent of the gameObject\&. The gizmo matrix will be set to the identity matrix\&. The gizmo color will be set to white\&. 
.PP
Definition at line 84 of file RuntimeGizmoManager\&.cs\&.
.SS "virtual void Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.Update ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 149 of file RuntimeGizmoManager\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRuntimeGizmoDrawer\fP Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&._backDrawer = null\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 49 of file RuntimeGizmoManager\&.cs\&.
.SS "Mesh Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&._cubeMesh\fC [protected]\fP"

.PP
Definition at line 47 of file RuntimeGizmoManager\&.cs\&.
.SS "bool Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&._displayInGameView = true\fC [protected]\fP"

.PP
Definition at line 33 of file RuntimeGizmoManager\&.cs\&.
.SS "bool Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&._enabledForBuild = true\fC [protected]\fP"

.PP
Definition at line 37 of file RuntimeGizmoManager\&.cs\&.
.SS "\fBRuntimeGizmoDrawer\fP Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&._frontDrawer = null\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 50 of file RuntimeGizmoManager\&.cs\&.
.SS "Shader Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&._gizmoShader\fC [protected]\fP"

.PP
Definition at line 45 of file RuntimeGizmoManager\&.cs\&.
.SS "Mesh Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&._sphereMesh\fC [protected]\fP"

.PP
Definition at line 41 of file RuntimeGizmoManager\&.cs\&.
.SS "const int Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.CIRCLE_RESOLUTION = 32"

.PP
Definition at line 29 of file RuntimeGizmoManager\&.cs\&.
.SS "const string Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.DEFAULT_SHADER_NAME = 'Hidden/Runtime Gizmos'"

.PP
Definition at line 28 of file RuntimeGizmoManager\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "Action<\fBRuntimeGizmoDrawer\fP> Leap\&.Unity\&.RuntimeGizmos\&.RuntimeGizmoManager\&.OnPostRenderGizmos\fC [static]\fP"

.PP
Subscribe to this event if you want to draw gizmos after rendering is complete\&. Doing gizmo rendering inside of the normal Camera\&.onPostRender event will cause rendering artifacts\&. 
.PP
Definition at line 57 of file RuntimeGizmoManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
