.TH "Leap.Unity.DeltaQuaternionBuffer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.DeltaQuaternionBuffer \- A ring buffer of Quaternions with a \fBDelta()\fP function that computes the buffer's average change over time as an angle-axis vector\&. Returns Vector3\&.zero if the buffer contains one or fewer samples\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.DeltaBuffer< Quaternion, Vector3 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeltaQuaternionBuffer\fP (int bufferSize)"
.br
.ti -1c
.RI "override Vector3 \fBDelta\fP ()"
.br
.RI "Returns the average angular velocity of Quaternions in the buffer as an angle-axis vector, or zero if the buffer is empty\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A ring buffer of Quaternions with a \fBDelta()\fP function that computes the buffer's average change over time as an angle-axis vector\&. Returns Vector3\&.zero if the buffer contains one or fewer samples\&. 

The larger the buffer, the more stable but also delayed the resulting average change over time\&. A buffer size of 5 is a good start for 60-90 Hz updates\&. 
.PP
Definition at line 169 of file DeltaBuffer\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.DeltaQuaternionBuffer\&.DeltaQuaternionBuffer (int bufferSize)"

.PP
Definition at line 171 of file DeltaBuffer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override Vector3 Leap\&.Unity\&.DeltaQuaternionBuffer\&.Delta ()\fC [virtual]\fP"

.PP
Returns the average angular velocity of Quaternions in the buffer as an angle-axis vector, or zero if the buffer is empty\&. 
.PP
Implements \fBLeap\&.Unity\&.DeltaBuffer< Quaternion, Vector3 >\fP\&.
.PP
Definition at line 177 of file DeltaBuffer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
