.TH "LeapInternal.LEAP_PALM" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_PALM
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLEAP_VECTOR\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBLEAP_VECTOR\fP \fBstabilized_position\fP"
.br
.ti -1c
.RI "\fBLEAP_VECTOR\fP \fBvelocity\fP"
.br
.ti -1c
.RI "\fBLEAP_VECTOR\fP \fBnormal\fP"
.br
.ti -1c
.RI "float \fBwidth\fP"
.br
.ti -1c
.RI "\fBLEAP_VECTOR\fP \fBdirection\fP"
.br
.ti -1c
.RI "\fBLEAP_QUATERNION\fP \fBorientation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 682 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLEAP_VECTOR\fP LeapInternal\&.LEAP_PALM\&.direction"

.PP
Definition at line 688 of file LeapC\&.cs\&.
.SS "\fBLEAP_VECTOR\fP LeapInternal\&.LEAP_PALM\&.normal"

.PP
Definition at line 686 of file LeapC\&.cs\&.
.SS "\fBLEAP_QUATERNION\fP LeapInternal\&.LEAP_PALM\&.orientation"

.PP
Definition at line 689 of file LeapC\&.cs\&.
.SS "\fBLEAP_VECTOR\fP LeapInternal\&.LEAP_PALM\&.position"

.PP
Definition at line 683 of file LeapC\&.cs\&.
.SS "\fBLEAP_VECTOR\fP LeapInternal\&.LEAP_PALM\&.stabilized_position"

.PP
Definition at line 684 of file LeapC\&.cs\&.
.SS "\fBLEAP_VECTOR\fP LeapInternal\&.LEAP_PALM\&.velocity"

.PP
Definition at line 685 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_PALM\&.width"

.PP
Definition at line 687 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
