.TH "Leap.Unity.IndexableStructEnumerator< Element, IndexableStruct >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.IndexableStructEnumerator< Element, IndexableStruct > \- A two-generic-argument variant of an enumerator that allows an \fBIIndexableStruct\fP to quickly define an Enumerator that avoids allocation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexableStructEnumerator\fP (IndexableStruct indexable)"
.br
.ti -1c
.RI "\fBIndexableStructEnumerator\fP< Element, IndexableStruct > \fBGetEnumerator\fP ()"
.br
.ti -1c
.RI "bool \fBMoveNext\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IndexableStruct? \fBmaybeIndexable\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Element \fBCurrent\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A two-generic-argument variant of an enumerator that allows an \fBIIndexableStruct\fP to quickly define an Enumerator that avoids allocation\&. 


.PP
\fBType Constraints\fP
.TP
\fIIndexableStruct\fP : \fIstruct\fP
.TP
\fIIndexableStruct\fP : \fI\fBIIndexableStruct\fP\fP
.TP
\fIIndexableStruct\fP : \fIElement\fP
.TP
\fIIndexableStruct\fP : \fIIndexableStruct\fP
.PP
Definition at line 114 of file IIndexableStruct\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLeap\&.Unity\&.IndexableStructEnumerator\fP< Element, IndexableStruct >\&.\fBIndexableStructEnumerator\fP (IndexableStruct indexable)"

.PP
Definition at line 120 of file IIndexableStruct\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIndexableStructEnumerator\fP<Element, IndexableStruct> \fBLeap\&.Unity\&.IndexableStructEnumerator\fP< Element, IndexableStruct >\&.GetEnumerator ()"

.PP
Definition at line 125 of file IIndexableStruct\&.cs\&.
.SS "bool \fBLeap\&.Unity\&.IndexableStructEnumerator\fP< Element, IndexableStruct >\&.MoveNext ()"

.PP
Definition at line 129 of file IIndexableStruct\&.cs\&.
.SS "void \fBLeap\&.Unity\&.IndexableStructEnumerator\fP< Element, IndexableStruct >\&.Reset ()"

.PP
Definition at line 134 of file IIndexableStruct\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBLeap\&.Unity\&.IndexableStructEnumerator\fP< Element, IndexableStruct >\&.index"

.PP
Definition at line 118 of file IIndexableStruct\&.cs\&.
.SS "IndexableStruct? \fBLeap\&.Unity\&.IndexableStructEnumerator\fP< Element, IndexableStruct >\&.maybeIndexable"

.PP
Definition at line 117 of file IIndexableStruct\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Element \fBLeap\&.Unity\&.IndexableStructEnumerator\fP< Element, IndexableStruct >\&.Current\fC [get]\fP"

.PP
Definition at line 138 of file IIndexableStruct\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
