.TH "Leap.Unity.Attributes.ImplementsTypeNameDropdownAttribute" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.ImplementsTypeNameDropdownAttribute \- Place this attribute on a serialized string field to have it render as a dropdown menu that is automatically populated with implementing types of the type provided to the attribute\&. The string field will contain the type name selected by the user\&. This can be converted into a Type reference via reflection and used to construct objects by their type, for example, or to construct ScriptableObjects by their type\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Attributes\&.CombinablePropertyAttribute\fP, and \fBLeap\&.Unity\&.Attributes\&.IFullPropertyDrawer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImplementsTypeNameDropdownAttribute\fP (Type type)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Type \fB_baseType\fP"
.br
.ti -1c
.RI "List< Type > \fB_implementingTypes\fP = new List<Type>()"
.br
.ti -1c
.RI "GUIContent [] \fB_typeOptions\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Place this attribute on a serialized string field to have it render as a dropdown menu that is automatically populated with implementing types of the type provided to the attribute\&. The string field will contain the type name selected by the user\&. This can be converted into a Type reference via reflection and used to construct objects by their type, for example, or to construct ScriptableObjects by their type\&. 


.PP
Definition at line 27 of file ImplementsTypeNameDropdown\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Attributes\&.ImplementsTypeNameDropdownAttribute\&.ImplementsTypeNameDropdownAttribute (Type type)"

.PP
Definition at line 34 of file ImplementsTypeNameDropdown\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Type Leap\&.Unity\&.Attributes\&.ImplementsTypeNameDropdownAttribute\&._baseType\fC [protected]\fP"

.PP
Definition at line 30 of file ImplementsTypeNameDropdown\&.cs\&.
.SS "List<Type> Leap\&.Unity\&.Attributes\&.ImplementsTypeNameDropdownAttribute\&._implementingTypes = new List<Type>()\fC [protected]\fP"

.PP
Definition at line 31 of file ImplementsTypeNameDropdown\&.cs\&.
.SS "GUIContent [] Leap\&.Unity\&.Attributes\&.ImplementsTypeNameDropdownAttribute\&._typeOptions\fC [protected]\fP"

.PP
Definition at line 32 of file ImplementsTypeNameDropdown\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
