.TH "Leap.Unity.LeapImageRetriever.LeapTextureData" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.LeapImageRetriever.LeapTextureData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCheckStale\fP (\fBImage\fP image)"
.br
.ti -1c
.RI "void \fBReconstruct\fP (\fBImage\fP image, string globalShaderName, string pixelSizeName)"
.br
.ti -1c
.RI "void \fBUpdateTexture\fP (\fBImage\fP image)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Texture2D \fBCombinedTexture\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file LeapImageRetriever\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Leap\&.Unity\&.LeapImageRetriever\&.LeapTextureData\&.CheckStale (\fBImage\fP image)"

.PP
Definition at line 63 of file LeapImageRetriever\&.cs\&.
.SS "void Leap\&.Unity\&.LeapImageRetriever\&.LeapTextureData\&.Reconstruct (\fBImage\fP image, string globalShaderName, string pixelSizeName)"

.PP
Definition at line 79 of file LeapImageRetriever\&.cs\&.
.SS "void Leap\&.Unity\&.LeapImageRetriever\&.LeapTextureData\&.UpdateTexture (\fBImage\fP image)"

.PP
Definition at line 101 of file LeapImageRetriever\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Texture2D Leap\&.Unity\&.LeapImageRetriever\&.LeapTextureData\&.CombinedTexture\fC [get]\fP"

.PP
Definition at line 57 of file LeapImageRetriever\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
