.TH "Leap.Unity.Interaction.IGraspedMovementHandler" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Interaction.IGraspedMovementHandler \- An \fBIGraspedMovementHandler\fP takes in a target position and rotation (a 'pose', usually provided by an \fBIGraspedPoseHandler\fP) and is responsible for attempting to move an interaction object to that target pose\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLeap\&.Unity\&.Interaction\&.KinematicGraspedMovement\fP, and \fBLeap\&.Unity\&.Interaction\&.NonKinematicGraspedMovement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMoveTo\fP (Vector3 solvedPosition, Quaternion solvedRotation, \fBInteractionBehaviour\fP interactionObj, bool justGrasped)"
.br
.RI "Called by an interaction object when its grasped pose handler has determined a target pose; this method should attempt to move the interaction object to match that pose\&. "
.in -1c
.SH "Detailed Description"
.PP 
An \fBIGraspedMovementHandler\fP takes in a target position and rotation (a 'pose', usually provided by an \fBIGraspedPoseHandler\fP) and is responsible for attempting to move an interaction object to that target pose\&. 


.PP
Definition at line 21 of file IGraspedMovementHandler\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Interaction\&.IGraspedMovementHandler\&.MoveTo (Vector3 solvedPosition, Quaternion solvedRotation, \fBInteractionBehaviour\fP interactionObj, bool justGrasped)"

.PP
Called by an interaction object when its grasped pose handler has determined a target pose; this method should attempt to move the interaction object to match that pose\&. 
.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.NonKinematicGraspedMovement\fP, and \fBLeap\&.Unity\&.Interaction\&.KinematicGraspedMovement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
