.TH "Leap.Unity.Attributes.CurveBoundsAttribute" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.CurveBoundsAttribute \- You can use this attribute to mark that an AnimationCurve can only have values that fall within specific bounds\&. The user will be prevented from entering a curve that lies outside of these bounds\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Attributes\&.CombinablePropertyAttribute\fP, and \fBLeap\&.Unity\&.Attributes\&.IFullPropertyDrawer\fP\&.
.PP
Inherited by \fBLeap\&.Unity\&.Attributes\&.UnitCurveAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCurveBoundsAttribute\fP (Rect \fBbounds\fP)"
.br
.ti -1c
.RI "\fBCurveBoundsAttribute\fP (float width, float height)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly Rect \fBbounds\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
You can use this attribute to mark that an AnimationCurve can only have values that fall within specific bounds\&. The user will be prevented from entering a curve that lies outside of these bounds\&. 


.PP
Definition at line 23 of file CurveBounds\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Attributes\&.CurveBoundsAttribute\&.CurveBoundsAttribute (Rect bounds)"

.PP
Definition at line 26 of file CurveBounds\&.cs\&.
.SS "Leap\&.Unity\&.Attributes\&.CurveBoundsAttribute\&.CurveBoundsAttribute (float width, float height)"

.PP
Definition at line 30 of file CurveBounds\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Rect Leap\&.Unity\&.Attributes\&.CurveBoundsAttribute\&.bounds"

.PP
Definition at line 24 of file CurveBounds\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
