.TH "Leap.Unity.Examples.TransformTranslationHandle" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples.TransformTranslationHandle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Examples\&.TransformHandle\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTranslationAxis\fP \fBaxis\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBStart\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file TransformTranslationHandle\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Leap\&.Unity\&.Examples\&.TransformTranslationHandle\&.Start ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.Examples\&.TransformHandle\fP\&.
.PP
Definition at line 24 of file TransformTranslationHandle\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTranslationAxis\fP Leap\&.Unity\&.Examples\&.TransformTranslationHandle\&.axis"

.PP
Definition at line 22 of file TransformTranslationHandle\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
