.TH "Leap.Unity.Interaction.InteractionControllerEditor" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Interaction.InteractionControllerEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.CustomEditorBase< InteractionController >\fP\&.
.PP
Inherited by \fBLeap\&.Unity\&.Interaction\&.InteractionHandEditor\fP, and \fBLeap\&.Unity\&.Interaction\&.InteractionVRControllerEditor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file InteractionControllerEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Leap\&.Unity\&.Interaction\&.InteractionControllerEditor\&.OnInspectorGUI ()"

.PP
Definition at line 22 of file InteractionControllerEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
