.TH "Leap.Unity.Attachments.AttachmentPointBehaviour" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attachments.AttachmentPointBehaviour \- Simple container class for storing a reference to the attachment point this transform corresponds to within an \fBAttachmentHand\fP\&. Also contains mappings from a single AttachmentPointFlags flag constant to the relevant bone on a \fBLeap\&.Hand\fP; these mappings can be accessed statically via \fBGetLeapHandPointData()\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetTransformUsingHand\fP (\fBLeap\&.Hand\fP hand)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator AttachmentPointFlags\fP (\fBAttachmentPointBehaviour\fP p)"
.br
.ti -1c
.RI "static void \fBGetLeapHandPointData\fP (\fBLeap\&.Hand\fP hand, \fBAttachmentPointFlags\fP singlePoint, out Vector3 position, out Quaternion rotation)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAttachmentHand\fP \fBattachmentHand\fP"
.br
.ti -1c
.RI "\fBAttachmentPointFlags\fP \fBattachmentPoint\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple container class for storing a reference to the attachment point this transform corresponds to within an \fBAttachmentHand\fP\&. Also contains mappings from a single AttachmentPointFlags flag constant to the relevant bone on a \fBLeap\&.Hand\fP; these mappings can be accessed statically via \fBGetLeapHandPointData()\fP\&. 

Can also be used to refer to a single AttachmentPointFlags flag constant (implicit conversion)\&. 
.PP
Definition at line 28 of file AttachmentPointBehaviour\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Leap\&.Unity\&.Attachments\&.AttachmentPointBehaviour\&.GetLeapHandPointData (\fBLeap\&.Hand\fP hand, \fBAttachmentPointFlags\fP singlePoint, out Vector3 position, out Quaternion rotation)\fC [static]\fP"

.PP
Definition at line 73 of file AttachmentPointBehaviour\&.cs\&.
.SS "static implicit Leap\&.Unity\&.Attachments\&.AttachmentPointBehaviour\&.operator \fBAttachmentPointFlags\fP (\fBAttachmentPointBehaviour\fP p)\fC [static]\fP"

.PP
Definition at line 53 of file AttachmentPointBehaviour\&.cs\&.
.SS "void Leap\&.Unity\&.Attachments\&.AttachmentPointBehaviour\&.SetTransformUsingHand (\fBLeap\&.Hand\fP hand)"

.PP
Definition at line 58 of file AttachmentPointBehaviour\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAttachmentHand\fP Leap\&.Unity\&.Attachments\&.AttachmentPointBehaviour\&.attachmentHand"

.PP
Definition at line 33 of file AttachmentPointBehaviour\&.cs\&.
.SS "\fBAttachmentPointFlags\fP Leap\&.Unity\&.Attachments\&.AttachmentPointBehaviour\&.attachmentPoint"

.PP
Definition at line 38 of file AttachmentPointBehaviour\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
