.TH "O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/EditorTools/Editor/LeapRigUpgrader.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/EditorTools/Editor/LeapRigUpgrader.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLeap\&.Unity\&.LeapRigUpgrader\fP"
.br
.RI "Can scan the currently open scene and detect instances of an old \fBLeap\fP Rig hierarchy, render a GUI describing the old rig, and provides functionality for automatically upgrading the rig\&. "
.ti -1c
.RI "class \fBLeap\&.Unity\&.OldRigHierarchy\fP"
.br
.RI "Description of an old \fBLeap\fP VR rig from before Core version 4\&.4\&. "
.ti -1c
.RI "class \fBLeap\&.Unity\&.OldRigHierarchy\&.OldCameraData\fP"
.br
.RI "Old camera objects that weren't modified at all would have had a \fBLeapEyeDislocator\fP (formerly LeapVRCameraControl), a Camera component, and an \fBEnableDepthBuffer\fP component\&. "
.ti -1c
.RI "class \fBLeap\&.Unity\&.OldRigHierarchy\&.OldLeapSpaceData\fP"
.br
.ti -1c
.RI "class \fBLeap\&.Unity\&.OldRigHierarchy\&.OldLeapHandControllerData\fP"
.br
.ti -1c
.RI "class \fBLeap\&.Unity\&.OldRigHierarchy\&.ImageRigData\fP"
.br
.ti -1c
.RI "class \fBLeap\&.Unity\&.OldRigHierarchy\&.UpgradeOptions\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLeap\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBLeap\&.Unity\&.UnityObject\fP = UnityEngine\&.Object"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
