.TH "Leap.Unity.LeapServiceProviderEditor" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.LeapServiceProviderEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.CustomEditorBase< LeapServiceProvider >\fP\&.
.PP
Inherited by \fBLeap\&.Unity\&.LeapXRServiceProviderEditor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnSceneGUI\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Quaternion \fBdeviceRotation\fP = Quaternion\&.identity"
.br
.ti -1c
.RI "bool \fBisVRProvider\fP = false"
.br
.ti -1c
.RI "Vector3 \fBcontrollerOffset\fP = Vector3\&.zero"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file LeapServiceProviderEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Leap\&.Unity\&.LeapServiceProviderEditor\&.OnEnable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.CustomEditorBase< LeapServiceProvider >\fP\&.
.PP
Reimplemented in \fBLeap\&.Unity\&.LeapXRServiceProviderEditor\fP\&.
.PP
Definition at line 27 of file LeapServiceProviderEditor\&.cs\&.
.SS "override void Leap\&.Unity\&.LeapServiceProviderEditor\&.OnInspectorGUI ()"

.PP
Definition at line 64 of file LeapServiceProviderEditor\&.cs\&.
.SS "virtual void Leap\&.Unity\&.LeapServiceProviderEditor\&.OnSceneGUI ()\fC [virtual]\fP"

.PP
Reimplemented in \fBLeap\&.Unity\&.LeapXRServiceProviderEditor\fP\&.
.PP
Definition at line 76 of file LeapServiceProviderEditor\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 Leap\&.Unity\&.LeapServiceProviderEditor\&.controllerOffset = Vector3\&.zero\fC [protected]\fP"

.PP
Definition at line 21 of file LeapServiceProviderEditor\&.cs\&.
.SS "Quaternion Leap\&.Unity\&.LeapServiceProviderEditor\&.deviceRotation = Quaternion\&.identity\fC [protected]\fP"

.PP
Definition at line 18 of file LeapServiceProviderEditor\&.cs\&.
.SS "bool Leap\&.Unity\&.LeapServiceProviderEditor\&.isVRProvider = false\fC [protected]\fP"

.PP
Definition at line 19 of file LeapServiceProviderEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
