.TH "Leap.DeviceFailureEventArgs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.DeviceFailureEventArgs \- Dispatched when a device is plugged in, but fails to initialize or when a working device fails in use\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.LeapEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeviceFailureEventArgs\fP (uint code, string message, string serial)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "uint \fBErrorCode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBErrorMessage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDeviceSerialNumber\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dispatched when a device is plugged in, but fails to initialize or when a working device fails in use\&. 

Provides the failure reason and, if available, the serial number\&. 
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 196 of file Events\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.DeviceFailureEventArgs\&.DeviceFailureEventArgs (uint code, string message, string serial)"

.PP
Definition at line 197 of file Events\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Leap\&.DeviceFailureEventArgs\&.DeviceSerialNumber\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 205 of file Events\&.cs\&.
.SS "uint Leap\&.DeviceFailureEventArgs\&.ErrorCode\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 203 of file Events\&.cs\&.
.SS "string Leap\&.DeviceFailureEventArgs\&.ErrorMessage\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 204 of file Events\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
