.TH "Leap.Unity.Attributes.AutoFindAttribute" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.AutoFindAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutoFindAttribute\fP (\fBAutoFindLocations\fP \fBsearchLocations\fP=\fBAutoFindLocations\&.All\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBAutoFindLocations\fP \fBsearchLocations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file AutoFind\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Attributes\&.AutoFindAttribute\&.AutoFindAttribute (\fBAutoFindLocations\fP searchLocations = \fC\fBAutoFindLocations\&.All\fP\fP)"

.PP
Definition at line 27 of file AutoFind\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBAutoFindLocations\fP Leap\&.Unity\&.Attributes\&.AutoFindAttribute\&.searchLocations"

.PP
Definition at line 25 of file AutoFind\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
