.TH "Leap.Unity.Space.LeapSphericalSpace" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Space.LeapSphericalSpace
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Space\&.LeapRadialSpace\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransformer\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override \fBITransformer\fP \fBCosntructBaseTransformer\fP ()"
.br
.ti -1c
.RI "override \fBITransformer\fP \fBConstructTransformer\fP (\fBLeapSpaceAnchor\fP anchor)"
.br
.ti -1c
.RI "override void \fBUpdateRadialTransformer\fP (\fBITransformer\fP \fBtransformer\fP, \fBITransformer\fP \fBparent\fP, Vector3 rectSpaceDelta)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file LeapSphericalSpace\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBITransformer\fP Leap\&.Unity\&.Space\&.LeapSphericalSpace\&.ConstructTransformer (\fBLeapSpaceAnchor\fP anchor)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBLeap\&.Unity\&.Space\&.LeapSpace\fP\&.
.PP
Definition at line 28 of file LeapSphericalSpace\&.cs\&.
.SS "override \fBITransformer\fP Leap\&.Unity\&.Space\&.LeapSphericalSpace\&.CosntructBaseTransformer ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBLeap\&.Unity\&.Space\&.LeapSpace\fP\&.
.PP
Definition at line 17 of file LeapSphericalSpace\&.cs\&.
.SS "override void Leap\&.Unity\&.Space\&.LeapSphericalSpace\&.UpdateRadialTransformer (\fBITransformer\fP transformer, \fBITransformer\fP parent, Vector3 rectSpaceDelta)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBLeap\&.Unity\&.Space\&.LeapRadialSpace\fP\&.
.PP
Definition at line 35 of file LeapSphericalSpace\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
