.TH "Leap.Unity.Animation.IInterpolator" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Animation.IInterpolator \- Implement this interface to add your own interpolators to Tween!  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.IPoolable\fP, and IDisposable\&.
.PP
Inherited by \fBLeap\&.Unity\&.Animation\&.Internal\&.GradientInterpolatorBase\fP, and \fBLeap\&.Unity\&.Animation\&.Internal\&.InterpolatorBase< ValueType, ObjType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInterpolate\fP (float percent)"
.br
.RI "Called to trigger the interpolation of this interpolator\&. Use this callback to do whatever work your interpolator needs to do\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBlength\fP\fC [get]\fP"
.br
.RI "Returns the 'length' of this interpolator, in whatever units make sense for this interpolator\&. If you are interpolating from one point to another, you would return the distance between the points\&. "
.ti -1c
.RI "bool \fBisValid\fP\fC [get]\fP"
.br
.RI "Returns whether or not this interpolator is currently considered valid\&. Any invalid interpolators will be removed from a tween\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implement this interface to add your own interpolators to Tween! 


.PP
Definition at line 17 of file IInterpolator\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Animation\&.IInterpolator\&.Interpolate (float percent)"

.PP
Called to trigger the interpolation of this interpolator\&. Use this callback to do whatever work your interpolator needs to do\&. 
.PP
Implemented in \fBLeap\&.Unity\&.Animation\&.Internal\&.GradientInterpolatorBase\fP, and \fBLeap\&.Unity\&.Animation\&.Internal\&.InterpolatorBase< ValueType, ObjType >\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Leap\&.Unity\&.Animation\&.IInterpolator\&.isValid\fC [get]\fP"

.PP
Returns whether or not this interpolator is currently considered valid\&. Any invalid interpolators will be removed from a tween\&. 
.PP
Definition at line 40 of file IInterpolator\&.cs\&.
.SS "float Leap\&.Unity\&.Animation\&.IInterpolator\&.length\fC [get]\fP"

.PP
Returns the 'length' of this interpolator, in whatever units make sense for this interpolator\&. If you are interpolating from one point to another, you would return the distance between the points\&. The only current use of this function is to drive the \fBTween\&.AtRate\fP function\&. 
.PP
Definition at line 34 of file IInterpolator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
