.TH "Leap.Unity.CapsuleHand" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.CapsuleHand
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.HandModelBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBSupportsEditorPersistence\fP ()"
.br
.RI "Returns whether or not this hand model supports editor persistence\&. This is false by default and must be opt-in by a developer making their own hand model script if they want editor persistence\&. "
.ti -1c
.RI "override \fBHand\fP \fBGetLeapHand\fP ()"
.br
.ti -1c
.RI "override void \fBSetLeapHand\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "override void \fBInitHand\fP ()"
.br
.ti -1c
.RI "override void \fBBeginHand\fP ()"
.br
.ti -1c
.RI "override void \fBUpdateHand\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override \fBModelType\fP \fBHandModelType\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBChirality\fP \fBHandedness\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A basic \fBLeap\fP hand model constructed dynamically vs\&. using pre-existing geometry 
.PP
Definition at line 17 of file CapsuleHand\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Leap\&.Unity\&.CapsuleHand\&.BeginHand ()\fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.HandModelBase\fP\&.
.PP
Definition at line 99 of file CapsuleHand\&.cs\&.
.SS "override \fBHand\fP Leap\&.Unity\&.CapsuleHand\&.GetLeapHand ()\fC [virtual]\fP"

.PP
Implements \fBLeap\&.Unity\&.HandModelBase\fP\&.
.PP
Definition at line 80 of file CapsuleHand\&.cs\&.
.SS "override void Leap\&.Unity\&.CapsuleHand\&.InitHand ()\fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.HandModelBase\fP\&.
.PP
Definition at line 88 of file CapsuleHand\&.cs\&.
.SS "override void Leap\&.Unity\&.CapsuleHand\&.SetLeapHand (\fBHand\fP hand)\fC [virtual]\fP"

.PP
Implements \fBLeap\&.Unity\&.HandModelBase\fP\&.
.PP
Definition at line 84 of file CapsuleHand\&.cs\&.
.SS "override bool Leap\&.Unity\&.CapsuleHand\&.SupportsEditorPersistence ()\fC [virtual]\fP"

.PP
Returns whether or not this hand model supports editor persistence\&. This is false by default and must be opt-in by a developer making their own hand model script if they want editor persistence\&. 
.PP
Reimplemented from \fBLeap\&.Unity\&.HandModelBase\fP\&.
.PP
Definition at line 76 of file CapsuleHand\&.cs\&.
.SS "override void Leap\&.Unity\&.CapsuleHand\&.UpdateHand ()\fC [virtual]\fP"

.PP
Implements \fBLeap\&.Unity\&.HandModelBase\fP\&.
.PP
Definition at line 111 of file CapsuleHand\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override \fBChirality\fP Leap\&.Unity\&.CapsuleHand\&.Handedness\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 69 of file CapsuleHand\&.cs\&.
.SS "override \fBModelType\fP Leap\&.Unity\&.CapsuleHand\&.HandModelType\fC [get]\fP"

.PP
Definition at line 63 of file CapsuleHand\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
