.TH "Leap.Unity.EnumEventTable" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.EnumEventTable
.SH SYNOPSIS
.br
.PP
.PP
Inherits ISerializationCallbackReceiver\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBHasUnityEvent\fP (int enumValue)"
.br
.ti -1c
.RI "void \fBInvoke\fP (int enumValue)"
.br
.ti -1c
.RI "void \fBOnBeforeSerialize\fP ()"
.br
.ti -1c
.RI "void \fBOnAfterDeserialize\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file EnumEventTable\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Leap\&.Unity\&.EnumEventTable\&.HasUnityEvent (int enumValue)"

.PP
Definition at line 38 of file EnumEventTable\&.cs\&.
.SS "void Leap\&.Unity\&.EnumEventTable\&.Invoke (int enumValue)"

.PP
Definition at line 48 of file EnumEventTable\&.cs\&.
.SS "void Leap\&.Unity\&.EnumEventTable\&.OnAfterDeserialize ()"

.PP
Definition at line 57 of file EnumEventTable\&.cs\&.
.SS "void Leap\&.Unity\&.EnumEventTable\&.OnBeforeSerialize ()"

.PP
Definition at line 55 of file EnumEventTable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
