.TH "Leap.Unity.Attachments.AttachmentHand" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attachments.AttachmentHand \- This MonoBehaviour is managed by an \fBAttachmentHands\fP component on a parent MonoBehaviour\&. Instead of adding \fBAttachmentHand\fP directly to a GameObject, add an \fBAttachmentHands\fP component to a parent GameObject to manage the construction and updating of \fBAttachmentHand\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAttachmentPointsEnumerator\fP"
.br
.RI "An enumerator that traverses all of the existing AttachmentPointBehaviours beneath an \fBAttachmentHand\fP\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBGetBehaviourForPoint\fP (\fBAttachmentPointFlags\fP singlePoint)"
.br
.RI "Returns the \fBAttachmentPointBehaviour\fP child object of this \fBAttachmentHand\fP given a reference to a single AttachmentPointFlags flag, or null if there is no such child object\&. "
.ti -1c
.RI "void \fBrefreshAttachmentTransforms\fP (\fBAttachmentPointFlags\fP \fBpoints\fP)"
.br
.ti -1c
.RI "void \fBnotifyPointBehaviourDeleted\fP (\fBAttachmentPointBehaviour\fP point)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Action \fBOnAttachmentPointsModified\fP = () => { }"
.br
.RI "Called when the \fBAttachmentHand\fP refreshes its \fBAttachmentPointBehaviour\fP transforms\&. If the user unchecks an attachment point in the \fBAttachmentHands\fP inspector, those Transforms will be destroyed; otherwise, existing Transforms will persist, so be careful not to unnecessarily duplicate any objects or components you may want to attach via this callback\&. "
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBwrist\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBpalm\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBthumbProximalJoint\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBthumbDistalJoint\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBthumbTip\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBindexKnuckle\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBindexMiddleJoint\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBindexDistalJoint\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBindexTip\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBmiddleKnuckle\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBmiddleMiddleJoint\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBmiddleDistalJoint\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBmiddleTip\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBringKnuckle\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBringMiddleJoint\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBringDistalJoint\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBringTip\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBpinkyKnuckle\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBpinkyMiddleJoint\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBpinkyDistalJoint\fP"
.br
.ti -1c
.RI "\fBAttachmentPointBehaviour\fP \fBpinkyTip\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAttachmentPointsEnumerator\fP \fBpoints\fP\fC [get]\fP"
.br
.RI "Gets an enumerator that traverses all of the AttachmentPoints beneath this \fBAttachmentHand\fP\&. "
.ti -1c
.RI "\fBChirality\fP \fBchirality\fP\fC [get, set]\fP"
.br
.RI "Gets the chirality of this \fBAttachmentHand\fP\&. This is set automatically by the \fBAttachmentHands\fP parent object of this \fBAttachmentHand\fP\&. "
.ti -1c
.RI "bool \fBisTracked\fP\fC [get, set]\fP"
.br
.RI "Gets the chirality of this \fBAttachmentHand\fP\&. This is set automatically by the \fBAttachmentHands\fP parent object of this \fBAttachmentHand\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
This MonoBehaviour is managed by an \fBAttachmentHands\fP component on a parent MonoBehaviour\&. Instead of adding \fBAttachmentHand\fP directly to a GameObject, add an \fBAttachmentHands\fP component to a parent GameObject to manage the construction and updating of \fBAttachmentHand\fP objects\&. 


.PP
Definition at line 29 of file AttachmentHand\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.GetBehaviourForPoint (\fBAttachmentPointFlags\fP singlePoint)"

.PP
Returns the \fBAttachmentPointBehaviour\fP child object of this \fBAttachmentHand\fP given a reference to a single AttachmentPointFlags flag, or null if there is no such child object\&. 
.PP
Definition at line 150 of file AttachmentHand\&.cs\&.
.SS "void Leap\&.Unity\&.Attachments\&.AttachmentHand\&.notifyPointBehaviourDeleted (\fBAttachmentPointBehaviour\fP point)"

.PP
Definition at line 230 of file AttachmentHand\&.cs\&.
.SS "void Leap\&.Unity\&.Attachments\&.AttachmentHand\&.refreshAttachmentTransforms (\fBAttachmentPointFlags\fP points)"

.PP
Definition at line 187 of file AttachmentHand\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.indexDistalJoint"

.PP
Definition at line 61 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.indexKnuckle"

.PP
Definition at line 57 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.indexMiddleJoint"

.PP
Definition at line 59 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.indexTip"

.PP
Definition at line 63 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.middleDistalJoint"

.PP
Definition at line 70 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.middleKnuckle"

.PP
Definition at line 66 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.middleMiddleJoint"

.PP
Definition at line 68 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.middleTip"

.PP
Definition at line 72 of file AttachmentHand\&.cs\&.
.SS "Action Leap\&.Unity\&.Attachments\&.AttachmentHand\&.OnAttachmentPointsModified = () => { }"

.PP
Called when the \fBAttachmentHand\fP refreshes its \fBAttachmentPointBehaviour\fP transforms\&. If the user unchecks an attachment point in the \fBAttachmentHands\fP inspector, those Transforms will be destroyed; otherwise, existing Transforms will persist, so be careful not to unnecessarily duplicate any objects or components you may want to attach via this callback\&. Also, you can use \fBAttachmentHand\&.points\fP for an enumerator of all existing \fBAttachmentPointBehaviour\fP transforms on a given \fBAttachmentHand\fP object\&. 
.PP
Definition at line 40 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.palm"

.PP
Definition at line 47 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.pinkyDistalJoint"

.PP
Definition at line 88 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.pinkyKnuckle"

.PP
Definition at line 84 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.pinkyMiddleJoint"

.PP
Definition at line 86 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.pinkyTip"

.PP
Definition at line 90 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.ringDistalJoint"

.PP
Definition at line 79 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.ringKnuckle"

.PP
Definition at line 75 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.ringMiddleJoint"

.PP
Definition at line 77 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.ringTip"

.PP
Definition at line 81 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.thumbDistalJoint"

.PP
Definition at line 52 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.thumbProximalJoint"

.PP
Definition at line 50 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.thumbTip"

.PP
Definition at line 54 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointBehaviour\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.wrist"

.PP
Definition at line 45 of file AttachmentHand\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBChirality\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.chirality\fC [get]\fP, \fC [set]\fP"

.PP
Gets the chirality of this \fBAttachmentHand\fP\&. This is set automatically by the \fBAttachmentHands\fP parent object of this \fBAttachmentHand\fP\&. 
.PP
Definition at line 112 of file AttachmentHand\&.cs\&.
.SS "bool Leap\&.Unity\&.Attachments\&.AttachmentHand\&.isTracked\fC [get]\fP, \fC [set]\fP"

.PP
Gets the chirality of this \fBAttachmentHand\fP\&. This is set automatically by the \fBAttachmentHands\fP parent object of this \fBAttachmentHand\fP\&. 
.PP
Definition at line 125 of file AttachmentHand\&.cs\&.
.SS "\fBAttachmentPointsEnumerator\fP Leap\&.Unity\&.Attachments\&.AttachmentHand\&.points\fC [get]\fP"

.PP
Gets an enumerator that traverses all of the AttachmentPoints beneath this \fBAttachmentHand\fP\&. 
.PP
Definition at line 97 of file AttachmentHand\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
