.TH "Leap.Unity.Animation.Internal.ColorInterpolatorBase< ObjType >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Animation.Internal.ColorInterpolatorBase< ObjType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Animation\&.Internal\&.InterpolatorBase< Color, ObjType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "new \fBColorInterpolatorBase\fP< ObjType > \fBInit\fP (Color a, Color b, ObjType target)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override float \fBlength\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 114 of file InterpolatorBases\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "new \fBColorInterpolatorBase\fP<ObjType> \fBLeap\&.Unity\&.Animation\&.Internal\&.ColorInterpolatorBase\fP< ObjType >\&.Init (Color a, Color b, ObjType target)"

.PP
Definition at line 121 of file InterpolatorBases\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override float \fBLeap\&.Unity\&.Animation\&.Internal\&.ColorInterpolatorBase\fP< ObjType >\&.length\fC [get]\fP"

.PP
Definition at line 115 of file InterpolatorBases\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
