.TH "LeapInternal.LEAP_VARIANT_VALUE_TYPE" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_VARIANT_VALUE_TYPE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBeLeapValueType\fP \fBtype\fP"
.br
.ti -1c
.RI "Int32 \fBboolValue\fP"
.br
.ti -1c
.RI "Int32 \fBintValue\fP"
.br
.ti -1c
.RI "float \fBfloatValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 733 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Int32 LeapInternal\&.LEAP_VARIANT_VALUE_TYPE\&.boolValue"

.PP
Definition at line 737 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_VARIANT_VALUE_TYPE\&.floatValue"

.PP
Definition at line 741 of file LeapC\&.cs\&.
.SS "Int32 LeapInternal\&.LEAP_VARIANT_VALUE_TYPE\&.intValue"

.PP
Definition at line 739 of file LeapC\&.cs\&.
.SS "\fBeLeapValueType\fP LeapInternal\&.LEAP_VARIANT_VALUE_TYPE\&.type"

.PP
Definition at line 735 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
