.TH "Leap.Unity.Animation.HermiteSpline2" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Animation.HermiteSpline2 \- Represents a spline that travels from one point in space to another over a specified time frame\&. The two endpoints are specified, as well as the instantaneous velocity at these two endpoints\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHermiteSpline2\fP (Vector2 \fBpos0\fP, Vector2 \fBpos1\fP)"
.br
.RI "Constructs a spline by specifying the positions of the two endpoints\&. The velocity at each endpoint is zero, and the time range of the spline is 0 to 1\&. "
.ti -1c
.RI "\fBHermiteSpline2\fP (Vector2 \fBpos0\fP, Vector2 \fBpos1\fP, Vector2 \fBvel0\fP, Vector2 \fBvel1\fP)"
.br
.RI "Constructs a spline by specifying the positions and velocities of the two endpoints\&. The time range of the spline is 0 to 1\&. "
.ti -1c
.RI "\fBHermiteSpline2\fP (Vector2 \fBpos0\fP, Vector2 \fBpos1\fP, Vector2 \fBvel0\fP, Vector2 \fBvel1\fP, float length)"
.br
.RI "Constructs a spline by specifying the positions and velocities of the two endpoints\&. The time range of the spline is 0 to length\&. "
.ti -1c
.RI "\fBHermiteSpline2\fP (float \fBt0\fP, float \fBt1\fP, Vector2 \fBpos0\fP, Vector2 \fBpos1\fP, Vector2 \fBvel0\fP, Vector2 \fBvel1\fP)"
.br
.RI "Constructs a spline by specifying the positions, velocities, and times of the endpoints\&. "
.ti -1c
.RI "Vector2 \fBPositionAt\fP (float t)"
.br
.RI "Gets the position at time t along this spline\&. "
.ti -1c
.RI "Vector2 \fBVelocityAt\fP (float t)"
.br
.RI "Gets the first derivative of position at time t\&. The time is clamped within the t0 - t1 range\&. "
.ti -1c
.RI "void \fBPositionAndVelAt\fP (float t, out Vector2 position, out Vector2 velocity)"
.br
.RI "Gets both the position and the first derivative of position at time ti\&. The time is clamped within the t0 - t1 range\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBt0\fP"
.br
.ti -1c
.RI "float \fBt1\fP"
.br
.ti -1c
.RI "Vector2 \fBpos0\fP"
.br
.ti -1c
.RI "Vector2 \fBpos1\fP"
.br
.ti -1c
.RI "Vector2 \fBvel0\fP"
.br
.ti -1c
.RI "Vector2 \fBvel1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a spline that travels from one point in space to another over a specified time frame\&. The two endpoints are specified, as well as the instantaneous velocity at these two endpoints\&. 

You may ask for the position or the velocity at any time during the splines duration\&. 
.PP
Definition at line 25 of file HermiteSpline2\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Animation\&.HermiteSpline2\&.HermiteSpline2 (Vector2 pos0, Vector2 pos1)"

.PP
Constructs a spline by specifying the positions of the two endpoints\&. The velocity at each endpoint is zero, and the time range of the spline is 0 to 1\&. 
.PP
Definition at line 35 of file HermiteSpline2\&.cs\&.
.SS "Leap\&.Unity\&.Animation\&.HermiteSpline2\&.HermiteSpline2 (Vector2 pos0, Vector2 pos1, Vector2 vel0, Vector2 vel1)"

.PP
Constructs a spline by specifying the positions and velocities of the two endpoints\&. The time range of the spline is 0 to 1\&. 
.PP
Definition at line 51 of file HermiteSpline2\&.cs\&.
.SS "Leap\&.Unity\&.Animation\&.HermiteSpline2\&.HermiteSpline2 (Vector2 pos0, Vector2 pos1, Vector2 vel0, Vector2 vel1, float length)"

.PP
Constructs a spline by specifying the positions and velocities of the two endpoints\&. The time range of the spline is 0 to length\&. 
.PP
Definition at line 67 of file HermiteSpline2\&.cs\&.
.SS "Leap\&.Unity\&.Animation\&.HermiteSpline2\&.HermiteSpline2 (float t0, float t1, Vector2 pos0, Vector2 pos1, Vector2 vel0, Vector2 vel1)"

.PP
Constructs a spline by specifying the positions, velocities, and times of the endpoints\&. 
.PP
Definition at line 82 of file HermiteSpline2\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Animation\&.HermiteSpline2\&.PositionAndVelAt (float t, out Vector2 position, out Vector2 velocity)"

.PP
Gets both the position and the first derivative of position at time ti\&. The time is clamped within the t0 - t1 range\&. 
.PP
Definition at line 142 of file HermiteSpline2\&.cs\&.
.SS "Vector2 Leap\&.Unity\&.Animation\&.HermiteSpline2\&.PositionAt (float t)"

.PP
Gets the position at time t along this spline\&. The time is clamped within the t0 - t1 range\&. 
.PP
Definition at line 97 of file HermiteSpline2\&.cs\&.
.SS "Vector2 Leap\&.Unity\&.Animation\&.HermiteSpline2\&.VelocityAt (float t)"

.PP
Gets the first derivative of position at time t\&. The time is clamped within the t0 - t1 range\&. 
.PP
Definition at line 114 of file HermiteSpline2\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector2 Leap\&.Unity\&.Animation\&.HermiteSpline2\&.pos0"

.PP
Definition at line 27 of file HermiteSpline2\&.cs\&.
.SS "Vector2 Leap\&.Unity\&.Animation\&.HermiteSpline2\&.pos1"

.PP
Definition at line 27 of file HermiteSpline2\&.cs\&.
.SS "float Leap\&.Unity\&.Animation\&.HermiteSpline2\&.t0"

.PP
Definition at line 26 of file HermiteSpline2\&.cs\&.
.SS "float Leap\&.Unity\&.Animation\&.HermiteSpline2\&.t1"

.PP
Definition at line 26 of file HermiteSpline2\&.cs\&.
.SS "Vector2 Leap\&.Unity\&.Animation\&.HermiteSpline2\&.vel0"

.PP
Definition at line 28 of file HermiteSpline2\&.cs\&.
.SS "Vector2 Leap\&.Unity\&.Animation\&.HermiteSpline2\&.vel1"

.PP
Definition at line 28 of file HermiteSpline2\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
