.TH "Leap.Unity.Attachments.AttachmentHands" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attachments.AttachmentHands \- Add an GameObject with this script to your scene if you would like to have a Transform hierarchy that will follow various important points on a hand, whether for visuals or for logic\&. The \fBAttachmentHands\fP object will maintain two child objects, one for each of the player's hands\&. Use the Inspector to customize which points you'd like to see in the hierarchy beneath the individual \fBAttachmentHand\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAttachmentPointFlags\fP \fBattachmentPoints\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Func< \fBHand\fP > [] \fBhandAccessors\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the functions used to get the latest \fBLeap\&.Hand\fP data for the corresponding \fBAttachmentHand\fP objects in the attachmentHands array\&. Modify this if you'd like to customize how hand data is sent to \fBAttachmentHands\fP; e\&.g\&. a networked multiplayer game receiving serialized hand data for a networked player representation\&. "
.ti -1c
.RI "\fBAttachmentHand\fP [] \fBattachmentHands\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the array of \fBAttachmentHand\fP objects that this component manages\&. The length of this array should match the handAccessors array; corresponding-index slots in handAccessors will be used to assign transform data to the \fBAttachmentHand\fP objects in this component's Update()\&. "
.in -1c
.SH "Detailed Description"
.PP 
Add an GameObject with this script to your scene if you would like to have a Transform hierarchy that will follow various important points on a hand, whether for visuals or for logic\&. The \fBAttachmentHands\fP object will maintain two child objects, one for each of the player's hands\&. Use the Inspector to customize which points you'd like to see in the hierarchy beneath the individual \fBAttachmentHand\fP objects\&. 


.PP
Definition at line 30 of file AttachmentHands\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBAttachmentHand\fP [] Leap\&.Unity\&.Attachments\&.AttachmentHands\&.attachmentHands\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the array of \fBAttachmentHand\fP objects that this component manages\&. The length of this array should match the handAccessors array; corresponding-index slots in handAccessors will be used to assign transform data to the \fBAttachmentHand\fP objects in this component's Update()\&. This array is automatically populated if it is null or empty during OnValidate() in the editor, but can be modified freely afterwards\&. 
.PP
Definition at line 74 of file AttachmentHands\&.cs\&.
.SS "\fBAttachmentPointFlags\fP Leap\&.Unity\&.Attachments\&.AttachmentHands\&.attachmentPoints\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 34 of file AttachmentHands\&.cs\&.
.SS "Func<\fBHand\fP> [] Leap\&.Unity\&.Attachments\&.AttachmentHands\&.handAccessors\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the functions used to get the latest \fBLeap\&.Hand\fP data for the corresponding \fBAttachmentHand\fP objects in the attachmentHands array\&. Modify this if you'd like to customize how hand data is sent to \fBAttachmentHands\fP; e\&.g\&. a networked multiplayer game receiving serialized hand data for a networked player representation\&. This array is automatically populated if it is null or empty during OnValidate() in the editor, but it can be modified freely afterwards\&. 
.PP
Definition at line 63 of file AttachmentHands\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
