.TH "Leap.Unity.SerializableHashSetEditor" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.SerializableHashSetEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyDrawer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerializableHashSetEditor\fP ()"
.br
.ti -1c
.RI "override void \fBOnGUI\fP (Rect position, SerializedProperty property, GUIContent label)"
.br
.ti -1c
.RI "override float \fBGetPropertyHeight\fP (SerializedProperty property, GUIContent label)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file SerializableHashSetEditor\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.SerializableHashSetEditor\&.SerializableHashSetEditor ()"

.PP
Definition at line 37 of file SerializableHashSetEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override float Leap\&.Unity\&.SerializableHashSetEditor\&.GetPropertyHeight (SerializedProperty property, GUIContent label)"

.PP
Definition at line 67 of file SerializableHashSetEditor\&.cs\&.
.SS "override void Leap\&.Unity\&.SerializableHashSetEditor\&.OnGUI (Rect position, SerializedProperty property, GUIContent label)"

.PP
Definition at line 52 of file SerializableHashSetEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
