.TH "Leap.Unity.Either< A, B >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Either< A, B > \- A data structure that represents either a value of type A or a value of type B\&. The value can never be both A and B\&. Neither A nor B can ever be null\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IEquatable< Either< A, B >>, IComparable, and IComparable< Either< A, B >>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEither\fP (A \fBa\fP)"
.br
.RI "Constructs an \fBEither\fP with a value of A\&. "
.ti -1c
.RI "\fBEither\fP (B \fBb\fP)"
.br
.RI "Constructs an \fBEither\fP with a value of B\&. "
.ti -1c
.RI "void \fBMatch\fP (Action< A > ifA, Action< B > ifB)"
.br
.RI "Calls the first delegate with the value of A if it is present, else calls the second delegate with the value of B\&. "
.ti -1c
.RI "bool \fBTryGetA\fP (out A \fBa\fP)"
.br
.RI "If this either contains the value of A, the out argument is filled with that value and this method returns true, else it returns false\&. "
.ti -1c
.RI "bool \fBTryGetB\fP (out B \fBb\fP)"
.br
.RI "If this either contains the value of B, the out argument is filled with that value and this method returns true, else it returns false\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "bool \fBEquals\fP (\fBEither\fP< A, B > other)"
.br
.ti -1c
.RI "int \fBCompareTo\fP (object obj)"
.br
.ti -1c
.RI "int \fBCompareTo\fP (\fBEither\fP< A, B > other)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBoperator==\fP (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)"
.br
.ti -1c
.RI "static bool \fBoperator !=\fP (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)"
.br
.ti -1c
.RI "static bool \fBoperator >\fP (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)"
.br
.ti -1c
.RI "static bool \fBoperator >=\fP (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)"
.br
.ti -1c
.RI "static bool \fBoperator<\fP (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)"
.br
.ti -1c
.RI "static bool \fBoperator<=\fP (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)"
.br
.ti -1c
.RI "static implicit \fBoperator Either< A, B >\fP (A \fBa\fP)"
.br
.ti -1c
.RI "static implicit \fBoperator Either< A, B >\fP (B \fBb\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly bool \fBisA\fP"
.br
.RI "Returns whether or not this \fBEither\fP contains the first value\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBisB\fP\fC [get]\fP"
.br
.RI "Returns whether or not this \fBEither\fP contains the second value\&. "
.ti -1c
.RI "Maybe< A > \fBa\fP\fC [get]\fP"
.br
.RI "Returns a \fBMaybe\fP that contains the value of A if it exists, or no value if it doesn't\&. "
.ti -1c
.RI "Maybe< B > \fBb\fP\fC [get]\fP"
.br
.RI "Returns a \fBMaybe\fP that contains the value of B if it exists, or no value if it doesn't\&. "
.in -1c
.SH "Detailed Description"
.PP 
A data structure that represents either a value of type A or a value of type B\&. The value can never be both A and B\&. Neither A nor B can ever be null\&. 


.PP
Definition at line 19 of file Either\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLeap\&.Unity\&.Either\fP< A, B >\&.\fBEither\fP (A a)"

.PP
Constructs an \fBEither\fP with a value of A\&. 
.PP
Definition at line 69 of file Either\&.cs\&.
.SS "\fBLeap\&.Unity\&.Either\fP< A, B >\&.\fBEither\fP (B b)"

.PP
Constructs an \fBEither\fP with a value of B\&. 
.PP
Definition at line 82 of file Either\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "int \fBLeap\&.Unity\&.Either\fP< A, B >\&.CompareTo (object obj)"

.PP
Definition at line 148 of file Either\&.cs\&.
.SS "int \fBLeap\&.Unity\&.Either\fP< A, B >\&.CompareTo (\fBEither\fP< A, B > other)"

.PP
Definition at line 156 of file Either\&.cs\&.
.SS "override bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.Equals (object obj)"

.PP
Definition at line 130 of file Either\&.cs\&.
.SS "bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.Equals (\fBEither\fP< A, B > other)"

.PP
Definition at line 138 of file Either\&.cs\&.
.SS "override int \fBLeap\&.Unity\&.Either\fP< A, B >\&.GetHashCode ()"

.PP
Definition at line 122 of file Either\&.cs\&.
.SS "void \fBLeap\&.Unity\&.Either\fP< A, B >\&.Match (Action< A > ifA, Action< B > ifB)"

.PP
Calls the first delegate with the value of A if it is present, else calls the second delegate with the value of B\&. 
.PP
Definition at line 96 of file Either\&.cs\&.
.SS "static bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.operator != (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)\fC [static]\fP"

.PP
Definition at line 190 of file Either\&.cs\&.
.SS "static bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.operator > (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)\fC [static]\fP"

.PP
Definition at line 194 of file Either\&.cs\&.
.SS "static bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.operator >= (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)\fC [static]\fP"

.PP
Definition at line 198 of file Either\&.cs\&.
.SS "static implicit \fBLeap\&.Unity\&.Either\fP< A, B >\&.operator \fBEither\fP< A, B > (A a)\fC [static]\fP"

.PP
Definition at line 210 of file Either\&.cs\&.
.SS "static implicit \fBLeap\&.Unity\&.Either\fP< A, B >\&.operator \fBEither\fP< A, B > (B b)\fC [static]\fP"

.PP
Definition at line 214 of file Either\&.cs\&.
.SS "static bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.operator< (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)\fC [static]\fP"

.PP
Definition at line 202 of file Either\&.cs\&.
.SS "static bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.operator<= (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)\fC [static]\fP"

.PP
Definition at line 206 of file Either\&.cs\&.
.SS "static bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.operator== (\fBEither\fP< A, B > either0, \fBEither\fP< A, B > either1)\fC [static]\fP"

.PP
Definition at line 186 of file Either\&.cs\&.
.SS "bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.TryGetA (out A a)"

.PP
If this either contains the value of A, the out argument is filled with that value and this method returns true, else it returns false\&. 
.PP
Definition at line 108 of file Either\&.cs\&.
.SS "bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.TryGetB (out B b)"

.PP
If this either contains the value of B, the out argument is filled with that value and this method returns true, else it returns false\&. 
.PP
Definition at line 117 of file Either\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.isA"

.PP
Returns whether or not this \fBEither\fP contains the first value\&. 
.PP
Definition at line 24 of file Either\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Maybe<A> \fBLeap\&.Unity\&.Either\fP< A, B >\&.a\fC [get]\fP"

.PP
Returns a \fBMaybe\fP that contains the value of A if it exists, or no value if it doesn't\&. 
.PP
Definition at line 42 of file Either\&.cs\&.
.SS "Maybe<B> \fBLeap\&.Unity\&.Either\fP< A, B >\&.b\fC [get]\fP"

.PP
Returns a \fBMaybe\fP that contains the value of B if it exists, or no value if it doesn't\&. 
.PP
Definition at line 56 of file Either\&.cs\&.
.SS "bool \fBLeap\&.Unity\&.Either\fP< A, B >\&.isB\fC [get]\fP"

.PP
Returns whether or not this \fBEither\fP contains the second value\&. 
.PP
Definition at line 29 of file Either\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
