.TH "Leap.Unity.FrameRateControls" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.FrameRateControls \- Provides control of target frame rate\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBResetRender\fP ()"
.br
.ti -1c
.RI "void \fBResetPhysics\fP ()"
.br
.ti -1c
.RI "void \fBResetAll\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtargetRenderRate\fP = 60"
.br
.ti -1c
.RI "int \fBtargetRenderRateStep\fP = 1"
.br
.ti -1c
.RI "int \fBfixedPhysicsRate\fP = 50"
.br
.ti -1c
.RI "int \fBfixedPhysicsRateStep\fP = 1"
.br
.ti -1c
.RI "KeyCode \fBunlockRender\fP = KeyCode\&.RightShift"
.br
.ti -1c
.RI "KeyCode \fBunlockPhysics\fP = KeyCode\&.LeftShift"
.br
.ti -1c
.RI "KeyCode \fBdecrease\fP = KeyCode\&.DownArrow"
.br
.ti -1c
.RI "KeyCode \fBincrease\fP = KeyCode\&.UpArrow"
.br
.ti -1c
.RI "KeyCode \fBresetRate\fP = KeyCode\&.Backspace"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides control of target frame rate\&. 

This utility is useful for verifying frame-rate independence of behaviors\&. 
.PP
Definition at line 20 of file FrameRateControls\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.FrameRateControls\&.ResetAll ()"

.PP
Definition at line 85 of file FrameRateControls\&.cs\&.
.SS "void Leap\&.Unity\&.FrameRateControls\&.ResetPhysics ()"

.PP
Definition at line 80 of file FrameRateControls\&.cs\&.
.SS "void Leap\&.Unity\&.FrameRateControls\&.ResetRender ()"

.PP
Definition at line 75 of file FrameRateControls\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "KeyCode Leap\&.Unity\&.FrameRateControls\&.decrease = KeyCode\&.DownArrow"

.PP
Definition at line 27 of file FrameRateControls\&.cs\&.
.SS "int Leap\&.Unity\&.FrameRateControls\&.fixedPhysicsRate = 50"

.PP
Definition at line 23 of file FrameRateControls\&.cs\&.
.SS "int Leap\&.Unity\&.FrameRateControls\&.fixedPhysicsRateStep = 1"

.PP
Definition at line 24 of file FrameRateControls\&.cs\&.
.SS "KeyCode Leap\&.Unity\&.FrameRateControls\&.increase = KeyCode\&.UpArrow"

.PP
Definition at line 28 of file FrameRateControls\&.cs\&.
.SS "KeyCode Leap\&.Unity\&.FrameRateControls\&.resetRate = KeyCode\&.Backspace"

.PP
Definition at line 29 of file FrameRateControls\&.cs\&.
.SS "int Leap\&.Unity\&.FrameRateControls\&.targetRenderRate = 60"

.PP
Definition at line 21 of file FrameRateControls\&.cs\&.
.SS "int Leap\&.Unity\&.FrameRateControls\&.targetRenderRateStep = 1"

.PP
Definition at line 22 of file FrameRateControls\&.cs\&.
.SS "KeyCode Leap\&.Unity\&.FrameRateControls\&.unlockPhysics = KeyCode\&.LeftShift"

.PP
Definition at line 26 of file FrameRateControls\&.cs\&.
.SS "KeyCode Leap\&.Unity\&.FrameRateControls\&.unlockRender = KeyCode\&.RightShift"

.PP
Definition at line 25 of file FrameRateControls\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
