.TH "Leap.Unity.Examples.InertiaPostProcessProvider" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples.InertiaPostProcessProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.PostProcessProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBProcessFrame\fP (ref \fBFrame\fP inputFrame)"
.br
.RI "Post-processes the input frame in place to give hands bouncy-feeling physics\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBstiffness\fP = 2f"
.br
.ti -1c
.RI "float \fBdamping\fP = 2f"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file InertiaPostProcessProvider\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Leap\&.Unity\&.Examples\&.InertiaPostProcessProvider\&.ProcessFrame (ref \fBFrame\fP inputFrame)\fC [virtual]\fP"

.PP
Post-processes the input frame in place to give hands bouncy-feeling physics\&. 
.PP
Implements \fBLeap\&.Unity\&.PostProcessProvider\fP\&.
.PP
Definition at line 46 of file InertiaPostProcessProvider\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Leap\&.Unity\&.Examples\&.InertiaPostProcessProvider\&.damping = 2f"

.PP
Definition at line 25 of file InertiaPostProcessProvider\&.cs\&.
.SS "float Leap\&.Unity\&.Examples\&.InertiaPostProcessProvider\&.stiffness = 2f"

.PP
Definition at line 21 of file InertiaPostProcessProvider\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
