.TH "Leap.Unity.IIndexable< T >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.IIndexable< T > \- This easy-to-implement interface represents the ability to index into a collection of elements of type T\&. IIndexables inherit Query() via an extension method\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLeap\&.Unity\&.RingBuffer< T >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBthis[int idx]\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCount\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This easy-to-implement interface represents the ability to index into a collection of elements of type T\&. IIndexables inherit Query() via an extension method\&. 

\fBIIndexable\fP is fire-and-forget if your implementer is a reference type (class)\&. If the implementing type is a struct, be mindful of boxing, and consider using \fBIIndexableStruct\fP and pooling instead\&. 
.PP
Definition at line 22 of file IIndexable\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int \fBLeap\&.Unity\&.IIndexable\fP< T >\&.Count\fC [get]\fP"

.PP
Definition at line 26 of file IIndexable\&.cs\&.
.SS "T \fBLeap\&.Unity\&.IIndexable\fP< T >\&.this[int idx]\fC [get]\fP"

.PP
Definition at line 24 of file IIndexable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
