.TH "Leap.LeapCSharp.Tests.LeapCTests" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.LeapCSharp.Tests.LeapCTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestNow\fP ()"
.br
.ti -1c
.RI "void \fBTestRebaserLifeCycle\fP ()"
.br
.ti -1c
.RI "void \fBTestCreateConnection\fP ()"
.br
.ti -1c
.RI "void \fBTestOpenConnection\fP ()"
.br
.ti -1c
.RI "void \fBTestGetConnectionInfo\fP ()"
.br
.ti -1c
.RI "void \fBTestPollConnection\fP ()"
.br
.ti -1c
.RI "void \fBTestInterpolateFrames\fP ()"
.br
.ti -1c
.RI "void \fBTestGetDeviceList\fP ()"
.br
.ti -1c
.RI "void \fBTestOpenDevice\fP ()"
.br
.ti -1c
.RI "void \fBTestGetDeviceInfo\fP ()"
.br
.ti -1c
.RI "void \fBTestGetOneDeviceInfo\fP ()"
.br
.ti -1c
.RI "void \fBTestSetPolicyFlags\fP ()"
.br
.ti -1c
.RI "void \fBTestSetDeviceFlags\fP ()"
.br
.ti -1c
.RI "void \fBTestCloseDevice\fP ()"
.br
.ti -1c
.RI "void \fBTestDestroyConnection\fP ()"
.br
.ti -1c
.RI "void \fBTestBoolConfigReadWrite\fP ()"
.br
.ti -1c
.RI "void \fBTestReadFloatConfig\fP ()"
.br
.ti -1c
.RI "void \fBTestFloatConfigReadWrite\fP ()"
.br
.ti -1c
.RI "void \fBTestInt32ConfigReadWrite\fP ()"
.br
.ti -1c
.RI "void \fBTestGetStringConfigValue\fP ()"
.br
.ti -1c
.RI "void \fBTestStringConfigReadWrite\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file LeapCTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestBoolConfigReadWrite ()"

.PP
Definition at line 516 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestCloseDevice ()"

.PP
Definition at line 465 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestCreateConnection ()"

.PP
Definition at line 55 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestDestroyConnection ()"

.PP
Definition at line 506 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestFloatConfigReadWrite ()"

.PP
Definition at line 652 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestGetConnectionInfo ()"

.PP
Definition at line 93 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestGetDeviceInfo ()"

.PP
Definition at line 289 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestGetDeviceList ()"

.PP
Definition at line 214 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestGetOneDeviceInfo ()"

.PP
Definition at line 346 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestGetStringConfigValue ()"

.PP
Definition at line 856 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestInt32ConfigReadWrite ()"

.PP
Definition at line 756 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestInterpolateFrames ()"

.PP
Definition at line 150 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestNow ()"

.PP
Definition at line 23 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestOpenConnection ()"

.PP
Definition at line 76 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestOpenDevice ()"

.PP
Definition at line 249 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestPollConnection ()"

.PP
Definition at line 127 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestReadFloatConfig ()"

.PP
Definition at line 610 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestRebaserLifeCycle ()"

.PP
Definition at line 35 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestSetDeviceFlags ()"

.PP
Definition at line 420 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestSetPolicyFlags ()"

.PP
Definition at line 393 of file LeapCTests\&.cs\&.
.SS "void Leap\&.LeapCSharp\&.Tests\&.LeapCTests\&.TestStringConfigReadWrite ()"

.PP
Definition at line 899 of file LeapCTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
