.TH "Leap.Unity.AutoValueProxy" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.AutoValueProxy \- A helpful implementation of \fBIValueProxy\fP\&. The class is a monobehaviour and so can be attached to game objects\&. Auto-pushing can also be turned on and off\&. When Auto-pushing is enabled, the behaviour will push the value on every LateUpdate\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and \fBLeap\&.Unity\&.IValueProxy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBOnPullValue\fP ()"
.br
.RI "Called when this proxy should pull from the target object into its serialized representation\&. "
.ti -1c
.RI "abstract void \fBOnPushValue\fP ()"
.br
.RI "Called when this proxy should push its serialized representation out to the target object\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBautoPushingEnabled\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A helpful implementation of \fBIValueProxy\fP\&. The class is a monobehaviour and so can be attached to game objects\&. Auto-pushing can also be turned on and off\&. When Auto-pushing is enabled, the behaviour will push the value on every LateUpdate\&. 


.PP
Definition at line 47 of file IValueProxy\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract void Leap\&.Unity\&.AutoValueProxy\&.OnPullValue ()\fC [pure virtual]\fP"

.PP
Called when this proxy should pull from the target object into its serialized representation\&. 
.PP
Implements \fBLeap\&.Unity\&.IValueProxy\fP\&.
.SS "abstract void Leap\&.Unity\&.AutoValueProxy\&.OnPushValue ()\fC [pure virtual]\fP"

.PP
Called when this proxy should push its serialized representation out to the target object\&. 
.PP
Implements \fBLeap\&.Unity\&.IValueProxy\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Leap\&.Unity\&.AutoValueProxy\&.autoPushingEnabled\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 51 of file IValueProxy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
