.TH "Leap.Unity.Tests.FrameValidator" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Tests.FrameValidator
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLeap\&.Unity\&.Tests\&.HandFactoryLeft\fP, \fBLeap\&.Unity\&.Tests\&.HandFactoryRight\fP, \fBLeap\&.Unity\&.Tests\&.HandFactoryTwoHands\fP, \fBLeap\&.Unity\&.Tests\&.TransformCopyIdentity\fP, and \fBLeap\&.Unity\&.Tests\&.TransformCopyTranslation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetup\fP ()"
.br
.ti -1c
.RI "virtual void \fBTeardown\fP ()"
.br
.ti -1c
.RI "void \fBHandsAreUnique\fP ()"
.br
.ti -1c
.RI "void \fBHandsHaveFiveFingers\fP ()"
.br
.ti -1c
.RI "void \fBFingersHaveFourBones\fP ([ValueSource(typeof(\fBFrameValidator\fP), '_fingers')] Finger\&.FingerType fingerType, [ValueSource(typeof(\fBFrameValidator\fP), '_bones')] Bone\&.BoneType boneType)"
.br
.ti -1c
.RI "void \fBBoneLength\fP ([ValueSource(typeof(\fBFrameValidator\fP), '_fingers')] Finger\&.FingerType fingerType, [ValueSource(typeof(\fBFrameValidator\fP), '_bones')] Bone\&.BoneType boneType)"
.br
.ti -1c
.RI "void \fBJointsMatch\fP ([ValueSource(typeof(\fBFrameValidator\fP), '_fingers')] Finger\&.FingerType fingerType, [ValueSource(typeof(\fBFrameValidator\fP), '_bones')] Bone\&.BoneType boneType)"
.br
.ti -1c
.RI "void \fBCenterIsBetweenJoints\fP ([ValueSource(typeof(\fBFrameValidator\fP), '_fingers')] Finger\&.FingerType fingerType, [ValueSource(typeof(\fBFrameValidator\fP), '_bones')] Bone\&.BoneType boneType)"
.br
.ti -1c
.RI "void \fBDirectionMatchesJoints\fP ([ValueSource(typeof(\fBFrameValidator\fP), '_fingers')] Finger\&.FingerType fingerType, [ValueSource(typeof(\fBFrameValidator\fP), '_bones')] Bone\&.BoneType boneType)"
.br
.ti -1c
.RI "void \fBRotationIsValid\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "abstract \fBFrame\fP \fBcreateFrame\fP ()"
.br
.ti -1c
.RI "\fBBone\fP \fBgetBone\fP (\fBHand\fP hand, \fBFinger\&.FingerType\fP fingerType, \fBBone\&.BoneType\fP boneType)"
.br
.ti -1c
.RI "void \fBassertVectorsEqual\fP (\fBVector\fP a, \fBVector\fP b, string vectorName='Vector')"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const float \fBTOLERANCE\fP = 0\&.0001f"
.br
.ti -1c
.RI "\fBFrame\fP \fB_frame\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fBFinger\&.FingerType\fP [] \fB_fingers\fP"
.br
.ti -1c
.RI "static \fBBone\&.BoneType\fP [] \fB_bones\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file FrameValidator\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Tests\&.FrameValidator\&.assertVectorsEqual (\fBVector\fP a, \fBVector\fP b, string vectorName = \fC'Vector'\fP)\fC [protected]\fP"

.PP
Definition at line 146 of file FrameValidator\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.FrameValidator\&.BoneLength ([ValueSource(typeof(FrameValidator), '_fingers')] \fBFinger\&.FingerType\fP fingerType, [ValueSource(typeof(FrameValidator), '_bones')] \fBBone\&.BoneType\fP boneType)"

.PP
Definition at line 69 of file FrameValidator\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.FrameValidator\&.CenterIsBetweenJoints ([ValueSource(typeof(FrameValidator), '_fingers')] \fBFinger\&.FingerType\fP fingerType, [ValueSource(typeof(FrameValidator), '_bones')] \fBBone\&.BoneType\fP boneType)"

.PP
Definition at line 98 of file FrameValidator\&.cs\&.
.SS "abstract \fBFrame\fP Leap\&.Unity\&.Tests\&.FrameValidator\&.createFrame ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBLeap\&.Unity\&.Tests\&.TransformCopyTranslation\fP, \fBLeap\&.Unity\&.Tests\&.HandFactoryRight\fP, \fBLeap\&.Unity\&.Tests\&.HandFactoryLeft\fP, \fBLeap\&.Unity\&.Tests\&.TransformCopyIdentity\fP, and \fBLeap\&.Unity\&.Tests\&.HandFactoryTwoHands\fP\&.
.SS "void Leap\&.Unity\&.Tests\&.FrameValidator\&.DirectionMatchesJoints ([ValueSource(typeof(FrameValidator), '_fingers')] \fBFinger\&.FingerType\fP fingerType, [ValueSource(typeof(FrameValidator), '_bones')] \fBBone\&.BoneType\fP boneType)"

.PP
Definition at line 109 of file FrameValidator\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.FrameValidator\&.FingersHaveFourBones ([ValueSource(typeof(FrameValidator), '_fingers')] \fBFinger\&.FingerType\fP fingerType, [ValueSource(typeof(FrameValidator), '_bones')] \fBBone\&.BoneType\fP boneType)"

.PP
Definition at line 60 of file FrameValidator\&.cs\&.
.SS "\fBBone\fP Leap\&.Unity\&.Tests\&.FrameValidator\&.getBone (\fBHand\fP hand, \fBFinger\&.FingerType\fP fingerType, \fBBone\&.BoneType\fP boneType)\fC [protected]\fP"

.PP
Definition at line 131 of file FrameValidator\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.FrameValidator\&.HandsAreUnique ()"

.PP
Definition at line 47 of file FrameValidator\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.FrameValidator\&.HandsHaveFiveFingers ()"

.PP
Definition at line 53 of file FrameValidator\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.FrameValidator\&.JointsMatch ([ValueSource(typeof(FrameValidator), '_fingers')] \fBFinger\&.FingerType\fP fingerType, [ValueSource(typeof(FrameValidator), '_bones')] \fBBone\&.BoneType\fP boneType)"

.PP
Definition at line 80 of file FrameValidator\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.FrameValidator\&.RotationIsValid ()"

.PP
Definition at line 125 of file FrameValidator\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Tests\&.FrameValidator\&.Setup ()\fC [virtual]\fP"

.PP
Definition at line 35 of file FrameValidator\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Tests\&.FrameValidator\&.Teardown ()\fC [virtual]\fP"

.PP
Definition at line 40 of file FrameValidator\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBone\&.BoneType\fP [] Leap\&.Unity\&.Tests\&.FrameValidator\&._bones\fC [static]\fP, \fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
= {
      Bone\&.BoneType\&.TYPE_DISTAL,
      Bone\&.BoneType\&.TYPE_INTERMEDIATE,
      Bone\&.BoneType\&.TYPE_METACARPAL,
      Bone\&.BoneType\&.TYPE_PROXIMAL
    }
.fi
.PP
Definition at line 25 of file FrameValidator\&.cs\&.
.SS "\fBFinger\&.FingerType\fP [] Leap\&.Unity\&.Tests\&.FrameValidator\&._fingers\fC [static]\fP, \fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
= {
      Finger\&.FingerType\&.TYPE_INDEX,
      Finger\&.FingerType\&.TYPE_MIDDLE,
      Finger\&.FingerType\&.TYPE_PINKY,
      Finger\&.FingerType\&.TYPE_RING,
      Finger\&.FingerType\&.TYPE_THUMB
    }
.fi
.PP
Definition at line 17 of file FrameValidator\&.cs\&.
.SS "\fBFrame\fP Leap\&.Unity\&.Tests\&.FrameValidator\&._frame\fC [protected]\fP"

.PP
Definition at line 32 of file FrameValidator\&.cs\&.
.SS "const float Leap\&.Unity\&.Tests\&.FrameValidator\&.TOLERANCE = 0\&.0001f\fC [protected]\fP"

.PP
Definition at line 16 of file FrameValidator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
