.TH "Leap.Unity.DetectorLogicGate" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.DetectorLogicGate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Detector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddDetector\fP (\fBDetector\fP detector)"
.br
.ti -1c
.RI "void \fBRemoveDetector\fP (\fBDetector\fP detector)"
.br
.ti -1c
.RI "void \fBAddAllSiblingDetectors\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBAddAllSiblingDetectorsOnAwake\fP = true"
.br
.ti -1c
.RI "\fBLogicType\fP \fBGateType\fP = \fBLogicType\&.AndGate\fP"
.br
.ti -1c
.RI "bool \fBNegate\fP = false"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBCheckDetectors\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBDetectorLogicGate\fP detector observes other detectors and activates when these other detectors match the specified logic\&.
.PP
A \fBDetectorLogicGate\fP can be configured as an AND gate or an OR gate\&. You can also negate the output (creating a NAND or NOR gate)\&.
.PP
Since a \fBDetectorLogicGate\fP is a \fBDetector\fP, it can observe other \fBDetectorLogicGate\fP instances\&. However, before constructing complex logic chains, you should consider whether it is better to put such logic into a normal script\&.
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 29 of file DetectorLogicGate\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.DetectorLogicGate\&.AddAllSiblingDetectors ()"
Adds all the other detectors on the same GameObject to the list of observed detectors\&.
.PP
Note: If you have more than one \fBDetectorLogicGate\fP instance on a game object, make sure that both objects don't observe each other\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 92 of file DetectorLogicGate\&.cs\&.
.SS "void Leap\&.Unity\&.DetectorLogicGate\&.AddDetector (\fBDetector\fP detector)"
Adds the specified detector to the list of observed detectors\&.
.PP
The same detector cannot be added more than once\&. 
.PP
\fBParameters:\fP
.RS 4
\fI\fBDetector\fP\fP the detector to watch\&. 
.RE
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 66 of file DetectorLogicGate\&.cs\&.
.SS "void Leap\&.Unity\&.DetectorLogicGate\&.CheckDetectors ()\fC [protected]\fP"
Checks all the observed detectors, combines them with the specified type of logic and calls the \fBActivate()\fP or \fBDeactivate()\fP function as appropriate\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 130 of file DetectorLogicGate\&.cs\&.
.SS "void Leap\&.Unity\&.DetectorLogicGate\&.RemoveDetector (\fBDetector\fP detector)"
Removes the specified detector from the list of observed detectors;
.PP
\fBParameters:\fP
.RS 4
\fI\fBDetector\fP\fP the detector to remove\&. 
.RE
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 79 of file DetectorLogicGate\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Leap\&.Unity\&.DetectorLogicGate\&.AddAllSiblingDetectorsOnAwake = true"
When true, all \fBDetector\fP components of the same game object are added to the list of watched detectors on Awake\&. When false, you must manually add the desired detectors\&.
.PP
If you have more than one \fBDetectorLogicGate\fP component on a game object, do not enable this option on both\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 43 of file DetectorLogicGate\&.cs\&.
.SS "\fBLogicType\fP Leap\&.Unity\&.DetectorLogicGate\&.GateType = \fBLogicType\&.AndGate\fP"
The type of logic for this gate: AND or OR\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 50 of file DetectorLogicGate\&.cs\&.
.SS "bool Leap\&.Unity\&.DetectorLogicGate\&.Negate = false"
Whether to negate the output of the gate\&. AND becomes NAND; OR becomes NOR\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 57 of file DetectorLogicGate\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
