.TH "LeapInternal.LEAP_DROPPED_FRAME_EVENT" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_DROPPED_FRAME_EVENT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Int64 \fBframe_id\fP"
.br
.ti -1c
.RI "\fBeLeapDroppedFrameType\fP \fBreason\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 523 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Int64 LeapInternal\&.LEAP_DROPPED_FRAME_EVENT\&.frame_id"

.PP
Definition at line 524 of file LeapC\&.cs\&.
.SS "\fBeLeapDroppedFrameType\fP LeapInternal\&.LEAP_DROPPED_FRAME_EVENT\&.reason"

.PP
Definition at line 525 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
