.TH "Leap.Unity.Attributes.ImplementsInterfaceAttribute" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.ImplementsInterfaceAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Attributes\&.CombinablePropertyAttribute\fP, \fBLeap\&.Unity\&.Attributes\&.IPropertyConstrainer\fP, \fBLeap\&.Unity\&.Attributes\&.IFullPropertyDrawer\fP, and \fBLeap\&.Unity\&.Attributes\&.ISupportDragAndDrop\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImplementsInterfaceAttribute\fP (Type type)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file ImplementsInterface\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Attributes\&.ImplementsInterfaceAttribute\&.ImplementsInterfaceAttribute (Type type)"

.PP
Definition at line 33 of file ImplementsInterface\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
