.TH "Leap.Unity.PostProcessProvider" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.PostProcessProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.LeapProvider\fP\&.
.PP
Inherited by \fBLeap\&.Unity\&.Examples\&.InertiaPostProcessProvider\fP, and \fBLeap\&.Unity\&.Examples\&.ProjectionPostProcessProvider\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDataUpdateMode\fP { \fBDataUpdateMode\&.UpdateOnly\fP, \fBDataUpdateMode\&.FixedUpdateOnly\fP, \fBDataUpdateMode\&.UpdateAndFixedUpdate\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBProcessFrame\fP (ref \fBFrame\fP inputFrame)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDataUpdateMode\fP \fBdataUpdateMode\fP = \fBDataUpdateMode\&.UpdateOnly\fP"
.br
.ti -1c
.RI "bool \fBpassthroughOnly\fP = false"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnValidate\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBLeapProvider\fP \fB_inputLeapProvider\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLeapProvider\fP \fBinputLeapProvider\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "override \fBFrame\fP \fBCurrentFrame\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBFrame\fP \fBCurrentFixedFrame\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file PostProcessProvider\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBLeap\&.Unity\&.PostProcessProvider\&.DataUpdateMode\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUpdateOnly \fP\fP
.TP
\fB\fIFixedUpdateOnly \fP\fP
.TP
\fB\fIUpdateAndFixedUpdate \fP\fP
.PP
Definition at line 42 of file PostProcessProvider\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Leap\&.Unity\&.PostProcessProvider\&.OnEnable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 77 of file PostProcessProvider\&.cs\&.
.SS "virtual void Leap\&.Unity\&.PostProcessProvider\&.OnValidate ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 82 of file PostProcessProvider\&.cs\&.
.SS "abstract void Leap\&.Unity\&.PostProcessProvider\&.ProcessFrame (ref \fBFrame\fP inputFrame)\fC [pure virtual]\fP"

.PP
Implemented in \fBLeap\&.Unity\&.Examples\&.InertiaPostProcessProvider\fP, and \fBLeap\&.Unity\&.Examples\&.ProjectionPostProcessProvider\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLeapProvider\fP Leap\&.Unity\&.PostProcessProvider\&._inputLeapProvider\fC [protected]\fP"

.PP
Definition at line 21 of file PostProcessProvider\&.cs\&.
.SS "\fBDataUpdateMode\fP Leap\&.Unity\&.PostProcessProvider\&.dataUpdateMode = \fBDataUpdateMode\&.UpdateOnly\fP"

.PP
Definition at line 46 of file PostProcessProvider\&.cs\&.
.SS "bool Leap\&.Unity\&.PostProcessProvider\&.passthroughOnly = false"

.PP
Definition at line 50 of file PostProcessProvider\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override \fBFrame\fP Leap\&.Unity\&.PostProcessProvider\&.CurrentFixedFrame\fC [get]\fP"

.PP
Definition at line 66 of file PostProcessProvider\&.cs\&.
.SS "override \fBFrame\fP Leap\&.Unity\&.PostProcessProvider\&.CurrentFrame\fC [get]\fP"

.PP
Definition at line 55 of file PostProcessProvider\&.cs\&.
.SS "\fBLeapProvider\fP Leap\&.Unity\&.PostProcessProvider\&.inputLeapProvider\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 22 of file PostProcessProvider\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
