.TH "Leap.Unity.Examples.SwapGraspExample" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples.SwapGraspExample
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIntObj\fP \fBobjA\fP"
.br
.ti -1c
.RI "\fBInteractionButton\fP \fBswapButton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file SwapGraspExample\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBIntObj\fP Leap\&.Unity\&.Examples\&.SwapGraspExample\&.objA"

.PP
Definition at line 20 of file SwapGraspExample\&.cs\&.
.SS "\fBInteractionButton\fP Leap\&.Unity\&.Examples\&.SwapGraspExample\&.swapButton"

.PP
Definition at line 22 of file SwapGraspExample\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
