.TH "LeapInternal.LEAP_TELEMETRY_DATA" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_TELEMETRY_DATA
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UInt32 \fBthreadId\fP"
.br
.ti -1c
.RI "UInt64 \fBstartTime\fP"
.br
.ti -1c
.RI "UInt64 \fBendTime\fP"
.br
.ti -1c
.RI "UInt32 \fBzoneDepth\fP"
.br
.ti -1c
.RI "string \fBfileName\fP"
.br
.ti -1c
.RI "UInt32 \fBlineNumber\fP"
.br
.ti -1c
.RI "string \fBzoneName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 769 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "UInt64 LeapInternal\&.LEAP_TELEMETRY_DATA\&.endTime"

.PP
Definition at line 772 of file LeapC\&.cs\&.
.SS "string LeapInternal\&.LEAP_TELEMETRY_DATA\&.fileName"

.PP
Definition at line 774 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_TELEMETRY_DATA\&.lineNumber"

.PP
Definition at line 775 of file LeapC\&.cs\&.
.SS "UInt64 LeapInternal\&.LEAP_TELEMETRY_DATA\&.startTime"

.PP
Definition at line 771 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_TELEMETRY_DATA\&.threadId"

.PP
Definition at line 770 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_TELEMETRY_DATA\&.zoneDepth"

.PP
Definition at line 773 of file LeapC\&.cs\&.
.SS "string LeapInternal\&.LEAP_TELEMETRY_DATA\&.zoneName"

.PP
Definition at line 776 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
