.TH "LeapInternal.Connection" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.Connection
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.ti -1c
.RI "UInt64 \fBGetInterpolatedFrameSize\fP (Int64 time)"
.br
.ti -1c
.RI "void \fBGetInterpolatedFrame\fP (\fBFrame\fP toFill, Int64 time)"
.br
.ti -1c
.RI "void \fBGetInterpolatedFrameFromTime\fP (\fBFrame\fP toFill, Int64 time, Int64 sourceTime)"
.br
.ti -1c
.RI "\fBFrame\fP \fBGetInterpolatedFrame\fP (Int64 time)"
.br
.ti -1c
.RI "void \fBGetInterpolatedHeadPose\fP (ref \fBLEAP_HEAD_POSE_EVENT\fP toFill, Int64 time)"
.br
.ti -1c
.RI "\fBLEAP_HEAD_POSE_EVENT\fP \fBGetInterpolatedHeadPose\fP (Int64 time)"
.br
.ti -1c
.RI "void \fBGetInterpolatedLeftRightTransform\fP (Int64 time, Int64 sourceTime, Int64 leftId, Int64 rightId, out \fBLeapTransform\fP leftTransform, out \fBLeapTransform\fP rightTransform)"
.br
.ti -1c
.RI "void \fBSetPolicy\fP (\fBController\&.PolicyFlag\fP policy)"
.br
.ti -1c
.RI "void \fBClearPolicy\fP (\fBController\&.PolicyFlag\fP policy)"
.br
.ti -1c
.RI "bool \fBIsPolicySet\fP (\fBController\&.PolicyFlag\fP policy)"
.br
.RI "Gets the active setting for a specific policy\&. "
.ti -1c
.RI "uint \fBGetConfigValue\fP (string config_key)"
.br
.ti -1c
.RI "uint \fBSetConfigValue< T >\fP (string config_key, T value)"
.br
.ti -1c
.RI "\fBVector\fP \fBPixelToRectilinear\fP (\fBImage\&.CameraType\fP camera, \fBVector\fP pixel)"
.br
.ti -1c
.RI "\fBVector\fP \fBRectilinearToPixel\fP (\fBImage\&.CameraType\fP camera, \fBVector\fP ray)"
.br
.ti -1c
.RI "void \fBTelemetryProfiling\fP (ref \fBLEAP_TELEMETRY_DATA\fP telemetryData)"
.br
.ti -1c
.RI "void \fBGetPointMapping\fP (ref \fBPointMapping\fP pm)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBConnection\fP \fBGetConnection\fP (int connectionKey=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "EventHandler< \fBConnectionLostEventArgs\fP > \fBLeapConnectionLost\fP"
.br
.ti -1c
.RI "EventHandler< \fBDeviceEventArgs\fP > \fBLeapDevice\fP"
.br
.ti -1c
.RI "EventHandler< \fBDeviceEventArgs\fP > \fBLeapDeviceLost\fP"
.br
.ti -1c
.RI "EventHandler< \fBDeviceFailureEventArgs\fP > \fBLeapDeviceFailure\fP"
.br
.ti -1c
.RI "EventHandler< \fBPolicyEventArgs\fP > \fBLeapPolicyChange\fP"
.br
.ti -1c
.RI "EventHandler< \fBFrameEventArgs\fP > \fBLeapFrame\fP"
.br
.ti -1c
.RI "EventHandler< \fBInternalFrameEventArgs\fP > \fBLeapInternalFrame\fP"
.br
.ti -1c
.RI "EventHandler< \fBLogEventArgs\fP > \fBLeapLogEvent\fP"
.br
.ti -1c
.RI "EventHandler< \fBSetConfigResponseEventArgs\fP > \fBLeapConfigResponse\fP"
.br
.ti -1c
.RI "EventHandler< \fBConfigChangeEventArgs\fP > \fBLeapConfigChange\fP"
.br
.ti -1c
.RI "EventHandler< \fBDistortionEventArgs\fP > \fBLeapDistortionChange\fP"
.br
.ti -1c
.RI "EventHandler< \fBDroppedFrameEventArgs\fP > \fBLeapDroppedFrame\fP"
.br
.ti -1c
.RI "EventHandler< \fBImageEventArgs\fP > \fBLeapImage\fP"
.br
.ti -1c
.RI "EventHandler< \fBPointMappingChangeEventArgs\fP > \fBLeapPointMappingChange\fP"
.br
.ti -1c
.RI "EventHandler< \fBHeadPoseEventArgs\fP > \fBLeapHeadPoseChange\fP"
.br
.ti -1c
.RI "Action< \fBBeginProfilingForThreadArgs\fP > \fBLeapBeginProfilingForThread\fP"
.br
.ti -1c
.RI "Action< \fBEndProfilingForThreadArgs\fP > \fBLeapEndProfilingForThread\fP"
.br
.ti -1c
.RI "Action< \fBBeginProfilingBlockArgs\fP > \fBLeapBeginProfilingBlock\fP"
.br
.ti -1c
.RI "Action< \fBEndProfilingBlockArgs\fP > \fBLeapEndProfilingBlock\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBConnectionKey\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBCircularObjectBuffer\fP< \fBLEAP_TRACKING_EVENT\fP > \fBFrames\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "SynchronizationContext \fBEventContext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "EventHandler< \fBLeapEventArgs\fP > \fBLeapInit\fP"
.br
.ti -1c
.RI "EventHandler< \fBConnectionEventArgs\fP > \fBLeapConnection\fP"
.br
.ti -1c
.RI "bool \fBIsServiceConnected\fP\fC [get]\fP"
.br
.RI "Reports whether your application has a connection to the \fBLeap\fP Motion daemon/service\&. Can be true even if the \fBLeap\fP Motion hardware is not available\&. "
.ti -1c
.RI "\fBDeviceList\fP \fBDevices\fP\fC [get]\fP"
.br
.RI "The list of currently attached and recognized \fBLeap\fP Motion controller devices\&. "
.ti -1c
.RI "\fBFailedDeviceList\fP \fBFailedDevices\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Connection\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void LeapInternal\&.Connection\&.ClearPolicy (\fBController\&.PolicyFlag\fP policy)"

.PP
Definition at line 666 of file Connection\&.cs\&.
.SS "void LeapInternal\&.Connection\&.Dispose ()"

.PP
Definition at line 109 of file Connection\&.cs\&.
.SS "virtual void LeapInternal\&.Connection\&.Dispose (bool disposing)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 115 of file Connection\&.cs\&.
.SS "uint LeapInternal\&.Connection\&.GetConfigValue (string config_key)"

.PP
Definition at line 712 of file Connection\&.cs\&.
.SS "static \fBConnection\fP LeapInternal\&.Connection\&.GetConnection (int connectionKey = \fC0\fP)\fC [static]\fP"

.PP
Definition at line 34 of file Connection\&.cs\&.
.SS "void LeapInternal\&.Connection\&.GetInterpolatedFrame (\fBFrame\fP toFill, Int64 time)"

.PP
Definition at line 334 of file Connection\&.cs\&.
.SS "\fBFrame\fP LeapInternal\&.Connection\&.GetInterpolatedFrame (Int64 time)"

.PP
Definition at line 360 of file Connection\&.cs\&.
.SS "void LeapInternal\&.Connection\&.GetInterpolatedFrameFromTime (\fBFrame\fP toFill, Int64 time, Int64 sourceTime)"

.PP
Definition at line 347 of file Connection\&.cs\&.
.SS "UInt64 LeapInternal\&.Connection\&.GetInterpolatedFrameSize (Int64 time)"

.PP
Definition at line 327 of file Connection\&.cs\&.
.SS "void LeapInternal\&.Connection\&.GetInterpolatedHeadPose (ref \fBLEAP_HEAD_POSE_EVENT\fP toFill, Int64 time)"

.PP
Definition at line 366 of file Connection\&.cs\&.
.SS "\fBLEAP_HEAD_POSE_EVENT\fP LeapInternal\&.Connection\&.GetInterpolatedHeadPose (Int64 time)"

.PP
Definition at line 371 of file Connection\&.cs\&.
.SS "void LeapInternal\&.Connection\&.GetInterpolatedLeftRightTransform (Int64 time, Int64 sourceTime, Int64 leftId, Int64 rightId, out \fBLeapTransform\fP leftTransform, out \fBLeapTransform\fP rightTransform)"

.PP
Definition at line 377 of file Connection\&.cs\&.
.SS "void LeapInternal\&.Connection\&.GetPointMapping (ref \fBPointMapping\fP pm)"

.PP
Definition at line 820 of file Connection\&.cs\&.
.SS "bool LeapInternal\&.Connection\&.IsPolicySet (\fBController\&.PolicyFlag\fP policy)"

.PP
Gets the active setting for a specific policy\&. Keep in mind that setting a policy flag is asynchronous, so changes are not effective immediately after calling setPolicyFlag()\&. In addition, a policy request can be declined by the user\&. You should always set the policy flags required by your application at startup and check that the policy change request was successful after an appropriate interval\&.
.PP
If the controller object is not connected to the \fBLeap\fP Motion software, then the default state for the selected policy is returned\&.
.PP
\fBSince:\fP
.RS 4
2\&.1\&.6 
.RE
.PP

.PP
Definition at line 707 of file Connection\&.cs\&.
.SS "\fBVector\fP LeapInternal\&.Connection\&.PixelToRectilinear (\fBImage\&.CameraType\fP camera, \fBVector\fP pixel)"

.PP
Definition at line 795 of file Connection\&.cs\&.
.SS "\fBVector\fP LeapInternal\&.Connection\&.RectilinearToPixel (\fBImage\&.CameraType\fP camera, \fBVector\fP ray)"

.PP
Definition at line 805 of file Connection\&.cs\&.
.SS "uint LeapInternal\&.Connection\&.SetConfigValue< T > (string config_key, T value)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIIConvertible\fP
.PP
Definition at line 720 of file Connection\&.cs\&.
.SS "void LeapInternal\&.Connection\&.SetPolicy (\fBController\&.PolicyFlag\fP policy)"

.PP
Definition at line 656 of file Connection\&.cs\&.
.SS "void LeapInternal\&.Connection\&.Start ()"

.PP
Definition at line 142 of file Connection\&.cs\&.
.SS "void LeapInternal\&.Connection\&.Stop ()"

.PP
Definition at line 177 of file Connection\&.cs\&.
.SS "void LeapInternal\&.Connection\&.TelemetryProfiling (ref \fBLEAP_TELEMETRY_DATA\fP telemetryData)"

.PP
Definition at line 815 of file Connection\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Action<\fBBeginProfilingBlockArgs\fP> LeapInternal\&.Connection\&.LeapBeginProfilingBlock"

.PP
Definition at line 104 of file Connection\&.cs\&.
.SS "Action<\fBBeginProfilingForThreadArgs\fP> LeapInternal\&.Connection\&.LeapBeginProfilingForThread"

.PP
Definition at line 102 of file Connection\&.cs\&.
.SS "EventHandler<\fBConfigChangeEventArgs\fP> LeapInternal\&.Connection\&.LeapConfigChange"

.PP
Definition at line 95 of file Connection\&.cs\&.
.SS "EventHandler<\fBSetConfigResponseEventArgs\fP> LeapInternal\&.Connection\&.LeapConfigResponse"

.PP
Definition at line 94 of file Connection\&.cs\&.
.SS "EventHandler<\fBConnectionLostEventArgs\fP> LeapInternal\&.Connection\&.LeapConnectionLost"

.PP
Definition at line 86 of file Connection\&.cs\&.
.SS "EventHandler<\fBDeviceEventArgs\fP> LeapInternal\&.Connection\&.LeapDevice"

.PP
Definition at line 87 of file Connection\&.cs\&.
.SS "EventHandler<\fBDeviceFailureEventArgs\fP> LeapInternal\&.Connection\&.LeapDeviceFailure"

.PP
Definition at line 89 of file Connection\&.cs\&.
.SS "EventHandler<\fBDeviceEventArgs\fP> LeapInternal\&.Connection\&.LeapDeviceLost"

.PP
Definition at line 88 of file Connection\&.cs\&.
.SS "EventHandler<\fBDistortionEventArgs\fP> LeapInternal\&.Connection\&.LeapDistortionChange"

.PP
Definition at line 96 of file Connection\&.cs\&.
.SS "EventHandler<\fBDroppedFrameEventArgs\fP> LeapInternal\&.Connection\&.LeapDroppedFrame"

.PP
Definition at line 97 of file Connection\&.cs\&.
.SS "Action<\fBEndProfilingBlockArgs\fP> LeapInternal\&.Connection\&.LeapEndProfilingBlock"

.PP
Definition at line 105 of file Connection\&.cs\&.
.SS "Action<\fBEndProfilingForThreadArgs\fP> LeapInternal\&.Connection\&.LeapEndProfilingForThread"

.PP
Definition at line 103 of file Connection\&.cs\&.
.SS "EventHandler<\fBFrameEventArgs\fP> LeapInternal\&.Connection\&.LeapFrame"

.PP
Definition at line 91 of file Connection\&.cs\&.
.SS "EventHandler<\fBHeadPoseEventArgs\fP> LeapInternal\&.Connection\&.LeapHeadPoseChange"

.PP
Definition at line 100 of file Connection\&.cs\&.
.SS "EventHandler<\fBImageEventArgs\fP> LeapInternal\&.Connection\&.LeapImage"

.PP
Definition at line 98 of file Connection\&.cs\&.
.SS "EventHandler<\fBInternalFrameEventArgs\fP> LeapInternal\&.Connection\&.LeapInternalFrame"

.PP
Definition at line 92 of file Connection\&.cs\&.
.SS "EventHandler<\fBLogEventArgs\fP> LeapInternal\&.Connection\&.LeapLogEvent"

.PP
Definition at line 93 of file Connection\&.cs\&.
.SS "EventHandler<\fBPointMappingChangeEventArgs\fP> LeapInternal\&.Connection\&.LeapPointMappingChange"

.PP
Definition at line 99 of file Connection\&.cs\&.
.SS "EventHandler<\fBPolicyEventArgs\fP> LeapInternal\&.Connection\&.LeapPolicyChange"

.PP
Definition at line 90 of file Connection\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int LeapInternal\&.Connection\&.ConnectionKey\fC [get]\fP"

.PP
Definition at line 43 of file Connection\&.cs\&.
.SS "\fBDeviceList\fP LeapInternal\&.Connection\&.Devices\fC [get]\fP"

.PP
The list of currently attached and recognized \fBLeap\fP Motion controller devices\&. The Device objects in the list describe information such as the range and tracking volume\&.
.PP
Currently, the \fBLeap\fP Motion Controller only allows a single active device at a time, however there may be multiple devices physically attached and listed here\&. Any active device(s) are guaranteed to be listed first, however order is not determined beyond that\&.
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 775 of file Connection\&.cs\&.
.SS "SynchronizationContext LeapInternal\&.Connection\&.EventContext\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 65 of file Connection\&.cs\&.
.SS "\fBFailedDeviceList\fP LeapInternal\&.Connection\&.FailedDevices\fC [get]\fP"

.PP
Definition at line 785 of file Connection\&.cs\&.
.SS "\fBCircularObjectBuffer\fP<\fBLEAP_TRACKING_EVENT\fP> LeapInternal\&.Connection\&.Frames\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 44 of file Connection\&.cs\&.
.SS "bool LeapInternal\&.Connection\&.IsServiceConnected\fC [get]\fP"

.PP
Reports whether your application has a connection to the \fBLeap\fP Motion daemon/service\&. Can be true even if the \fBLeap\fP Motion hardware is not available\&. 
.PP
\fBSince:\fP
.RS 4
1\&.2 
.RE
.PP

.PP
Definition at line 745 of file Connection\&.cs\&.
.SS "EventHandler<\fBConnectionEventArgs\fP> LeapInternal\&.Connection\&.LeapConnection\fC [add]\fP, \fC [remove]\fP"

.PP
Definition at line 78 of file Connection\&.cs\&.
.SS "EventHandler<\fBLeapEventArgs\fP> LeapInternal\&.Connection\&.LeapInit\fC [add]\fP, \fC [remove]\fP"

.PP
Definition at line 68 of file Connection\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
