.TH "Leap.Unity.Interaction.InteractionSlider" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Interaction.InteractionSlider \- A physics-enabled slider\&. Sliding is triggered by physically pushing the slider to its compressed position\&. Increasing the horizontal and vertical slide limits allows it to act as either a 1D or 2D slider\&. /summary>  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Interaction\&.InteractionButton\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFloatEvent\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSliderType\fP { \fBSliderType\&.Vertical\fP, \fBSliderType\&.Horizontal\fP, \fBSliderType\&.TwoDimensional\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRecalculateSliderLimits\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSliderType\fP \fBsliderType\fP = \fBSliderType\&.Horizontal\fP"
.br
.ti -1c
.RI "bool \fBdispatchSlideValueOnStart\fP = true"
.br
.ti -1c
.RI "bool \fBoverrideRectLimits\fP = false"
.br
.ti -1c
.RI "float \fBdefaultHorizontalValue\fP"
.br
.ti -1c
.RI "Vector2 \fBhorizontalSlideLimits\fP = new Vector2(\-0\&.05f, 0\&.05f)"
.br
.ti -1c
.RI "int \fBhorizontalSteps\fP = 0"
.br
.ti -1c
.RI "float \fBdefaultVerticalValue\fP"
.br
.ti -1c
.RI "Vector2 \fBverticalSlideLimits\fP = new Vector2(0f, 0f)"
.br
.ti -1c
.RI "int \fBverticalSteps\fP = 0"
.br
.RI "summary> Triggered while this slider is depressed\&. "
.ti -1c
.RI "Action< float > \fBHorizontalSlideEvent\fP = (f) => { }"
.br
.ti -1c
.RI "Action< float > \fBVerticalSlideEvent\fP = (f) => { }"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnValidate\fP ()"
.br
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "override void \fBStart\fP ()"
.br
.ti -1c
.RI "override void \fBUpdate\fP ()"
.br
.ti -1c
.RI "override Vector3 \fBconstrainDepressedLocalPosition\fP (Vector3 desiredOffset)"
.br
.RI "Clamps the input local-space position to the bounds allowed by this UI element, without clamping along the button depression axis\&. For buttons, this is locks the element in local-XY space, but not along the pressing axis (Z axis)\&. "
.ti -1c
.RI "override void \fBOnDrawGizmosSelected\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fB_horizontalSliderPercent\fP"
.br
.ti -1c
.RI "float \fB_verticalSliderPercent\fP"
.br
.ti -1c
.RI "RectTransform \fBparent\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBminHorizontalValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBmaxHorizontalValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBminVerticalValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBmaxVerticalValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBHorizontalSliderPercent\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBVerticalSliderPercent\fP\fC [get, set]\fP"
.br
.RI "summary> This slider's horizontal slider value, mapped between the values in the HorizontalValueRange\&. "
.ti -1c
.RI "float \fBHorizontalSliderValue\fP\fC [get, set]\fP"
.br
.RI "summary> This slider's current vertical slider value, mapped between the values in the VerticalValueRange\&. "
.ti -1c
.RI "float \fBVerticalSliderValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBnormalizedHorizontalValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBnormalizedVerticalValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBhorizontalStepValue\fP\fC [get]\fP"
.br
.RI "Returns the number of horizontal steps past the minimum value of the slider, for sliders with a non-zero number of horizontal steps\&. This value is independent of the horizontal value range of the slider\&. For example a slider with a horizontalSteps value of 9 could have horizontalStepValues of 0-9\&. "
.ti -1c
.RI "bool \fBwasSlid\fP\fC [get]\fP"
.br
.RI "Gets whether the slider was slide in the latest \fBUpdate()\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
A physics-enabled slider\&. Sliding is triggered by physically pushing the slider to its compressed position\&. Increasing the horizontal and vertical slide limits allows it to act as either a 1D or 2D slider\&. /summary> 
.PP
Definition at line 22 of file InteractionSlider\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBLeap\&.Unity\&.Interaction\&.InteractionSlider\&.SliderType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIVertical \fP\fP
.TP
\fB\fIHorizontal \fP\fP
.TP
\fB\fITwoDimensional \fP\fP
.PP
Definition at line 26 of file InteractionSlider\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override Vector3 Leap\&.Unity\&.Interaction\&.InteractionSlider\&.constrainDepressedLocalPosition (Vector3 localPosition)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Clamps the input local-space position to the bounds allowed by this UI element, without clamping along the button depression axis\&. For buttons, this is locks the element in local-XY space, but not along the pressing axis (Z axis)\&. 
.PP
Reimplemented from \fBLeap\&.Unity\&.Interaction\&.InteractionButton\fP\&.
.PP
Definition at line 408 of file InteractionSlider\&.cs\&.
.SS "override void Leap\&.Unity\&.Interaction\&.InteractionSlider\&.OnDisable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.Interaction\&.InteractionButton\fP\&.
.PP
Definition at line 292 of file InteractionSlider\&.cs\&.
.SS "override void Leap\&.Unity\&.Interaction\&.InteractionSlider\&.OnDrawGizmosSelected ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.Interaction\&.InteractionButton\fP\&.
.PP
Definition at line 433 of file InteractionSlider\&.cs\&.
.SS "override void Leap\&.Unity\&.Interaction\&.InteractionSlider\&.OnEnable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.PP
Definition at line 286 of file InteractionSlider\&.cs\&.
.SS "override void Leap\&.Unity\&.Interaction\&.InteractionSlider\&.OnValidate ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.PP
Definition at line 275 of file InteractionSlider\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.InteractionSlider\&.RecalculateSliderLimits ()"

.PP
Definition at line 357 of file InteractionSlider\&.cs\&.
.SS "override void Leap\&.Unity\&.Interaction\&.InteractionSlider\&.Start ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.Interaction\&.InteractionButton\fP\&.
.PP
Definition at line 298 of file InteractionSlider\&.cs\&.
.SS "override void Leap\&.Unity\&.Interaction\&.InteractionSlider\&.Update ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.Interaction\&.InteractionButton\fP\&.
.PP
Definition at line 331 of file InteractionSlider\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&._horizontalSliderPercent\fC [protected]\fP"

.PP
Definition at line 262 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&._verticalSliderPercent\fC [protected]\fP"

.PP
Definition at line 263 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.defaultHorizontalValue"

.PP
Definition at line 46 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.defaultVerticalValue"

.PP
Definition at line 94 of file InteractionSlider\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionSlider\&.dispatchSlideValueOnStart = true"

.PP
Definition at line 35 of file InteractionSlider\&.cs\&.
.SS "Action<float> Leap\&.Unity\&.Interaction\&.InteractionSlider\&.HorizontalSlideEvent = (f) => { }"

.PP
Definition at line 139 of file InteractionSlider\&.cs\&.
.SS "Vector2 Leap\&.Unity\&.Interaction\&.InteractionSlider\&.horizontalSlideLimits = new Vector2(\-0\&.05f, 0\&.05f)"

.PP
Definition at line 78 of file InteractionSlider\&.cs\&.
.SS "int Leap\&.Unity\&.Interaction\&.InteractionSlider\&.horizontalSteps = 0"

.PP
Definition at line 84 of file InteractionSlider\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionSlider\&.overrideRectLimits = false"

.PP
Definition at line 39 of file InteractionSlider\&.cs\&.
.SS "RectTransform Leap\&.Unity\&.Interaction\&.InteractionSlider\&.parent\fC [protected]\fP"

.PP
Definition at line 264 of file InteractionSlider\&.cs\&.
.SS "\fBSliderType\fP Leap\&.Unity\&.Interaction\&.InteractionSlider\&.sliderType = \fBSliderType\&.Horizontal\fP"

.PP
Definition at line 33 of file InteractionSlider\&.cs\&.
.SS "Action<float> Leap\&.Unity\&.Interaction\&.InteractionSlider\&.VerticalSlideEvent = (f) => { }"

.PP
Definition at line 140 of file InteractionSlider\&.cs\&.
.SS "Vector2 Leap\&.Unity\&.Interaction\&.InteractionSlider\&.verticalSlideLimits = new Vector2(0f, 0f)"

.PP
Definition at line 126 of file InteractionSlider\&.cs\&.
.SS "int Leap\&.Unity\&.Interaction\&.InteractionSlider\&.verticalSteps = 0"

.PP
summary> Triggered while this slider is depressed\&. 
.PP
Definition at line 132 of file InteractionSlider\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.HorizontalSliderPercent\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 142 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.HorizontalSliderValue\fC [get]\fP, \fC [set]\fP"

.PP
summary> This slider's current vertical slider value, mapped between the values in the VerticalValueRange\&. 
.PP
Definition at line 177 of file InteractionSlider\&.cs\&.
.SS "int Leap\&.Unity\&.Interaction\&.InteractionSlider\&.horizontalStepValue\fC [get]\fP"

.PP
Returns the number of horizontal steps past the minimum value of the slider, for sliders with a non-zero number of horizontal steps\&. This value is independent of the horizontal value range of the slider\&. For example a slider with a horizontalSteps value of 9 could have horizontalStepValues of 0-9\&. 
.PP
Definition at line 241 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.maxHorizontalValue\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 64 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.maxVerticalValue\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 112 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.minHorizontalValue\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 52 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.minVerticalValue\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 100 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.normalizedHorizontalValue\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 209 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.normalizedVerticalValue\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 222 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.VerticalSliderPercent\fC [get]\fP, \fC [set]\fP"

.PP
summary> This slider's horizontal slider value, mapped between the values in the HorizontalValueRange\&. 
.PP
Definition at line 159 of file InteractionSlider\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionSlider\&.VerticalSliderValue\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 187 of file InteractionSlider\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionSlider\&.wasSlid\fC [get]\fP"

.PP
Gets whether the slider was slide in the latest \fBUpdate()\fP\&. 
.PP
Definition at line 254 of file InteractionSlider\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
