.TH "LeapInternal.LEAP_POINT_MAPPING" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_POINT_MAPPING
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Int64 \fBframe_id\fP"
.br
.ti -1c
.RI "Int64 \fBtimestamp\fP"
.br
.ti -1c
.RI "UInt32 \fBnPoints\fP"
.br
.ti -1c
.RI "IntPtr \fBpoints\fP"
.br
.ti -1c
.RI "IntPtr \fBids\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 536 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Int64 LeapInternal\&.LEAP_POINT_MAPPING\&.frame_id"

.PP
Definition at line 537 of file LeapC\&.cs\&.
.SS "IntPtr LeapInternal\&.LEAP_POINT_MAPPING\&.ids"

.PP
Definition at line 541 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_POINT_MAPPING\&.nPoints"

.PP
Definition at line 539 of file LeapC\&.cs\&.
.SS "IntPtr LeapInternal\&.LEAP_POINT_MAPPING\&.points"

.PP
Definition at line 540 of file LeapC\&.cs\&.
.SS "Int64 LeapInternal\&.LEAP_POINT_MAPPING\&.timestamp"

.PP
Definition at line 538 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
