.TH "Leap.Unity.SmoothedFloat" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.SmoothedFloat \- Time-step independent exponential smoothing\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetBlend\fP (float blend, float deltaTime=1f)"
.br
.ti -1c
.RI "float \fBUpdate\fP (float input, float deltaTime=1f)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBvalue\fP = 0f"
.br
.ti -1c
.RI "float \fBdelay\fP = 0f"
.br
.ti -1c
.RI "bool \fBreset\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Time-step independent exponential smoothing\&. 

When moving at a constant speed: speed * delay = Value - \fBSmoothedFloat\&.value\fP\&. 
.PP
Definition at line 20 of file SmoothedFloat\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.SmoothedFloat\&.SetBlend (float blend, float deltaTime = \fC1f\fP)"

.PP
Definition at line 25 of file SmoothedFloat\&.cs\&.
.SS "float Leap\&.Unity\&.SmoothedFloat\&.Update (float input, float deltaTime = \fC1f\fP)"

.PP
Definition at line 29 of file SmoothedFloat\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Leap\&.Unity\&.SmoothedFloat\&.delay = 0f"

.PP
Definition at line 22 of file SmoothedFloat\&.cs\&.
.SS "bool Leap\&.Unity\&.SmoothedFloat\&.reset = true"

.PP
Definition at line 23 of file SmoothedFloat\&.cs\&.
.SS "float Leap\&.Unity\&.SmoothedFloat\&.value = 0f"

.PP
Definition at line 21 of file SmoothedFloat\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
