.TH "LeapInternal.LEAP_IMAGE_EVENT" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_IMAGE_EVENT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLEAP_FRAME_HEADER\fP \fBinfo\fP"
.br
.ti -1c
.RI "\fBLEAP_IMAGE\fP \fBleftImage\fP"
.br
.ti -1c
.RI "\fBLEAP_IMAGE\fP \fBrightImage\fP"
.br
.ti -1c
.RI "IntPtr \fBcalib\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 613 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "IntPtr LeapInternal\&.LEAP_IMAGE_EVENT\&.calib"

.PP
Definition at line 617 of file LeapC\&.cs\&.
.SS "\fBLEAP_FRAME_HEADER\fP LeapInternal\&.LEAP_IMAGE_EVENT\&.info"

.PP
Definition at line 614 of file LeapC\&.cs\&.
.SS "\fBLEAP_IMAGE\fP LeapInternal\&.LEAP_IMAGE_EVENT\&.leftImage"

.PP
Definition at line 615 of file LeapC\&.cs\&.
.SS "\fBLEAP_IMAGE\fP LeapInternal\&.LEAP_IMAGE_EVENT\&.rightImage"

.PP
Definition at line 616 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
