.TH "Leap.Unity.Space" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Space
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIdentityTransformer\fP"
.br
.ti -1c
.RI "interface \fBIRadialTransformer\fP"
.br
.ti -1c
.RI "interface \fBISpaceComponent\fP"
.br
.ti -1c
.RI "interface \fBITransformer\fP"
.br
.ti -1c
.RI "class \fBITransformerExtensions\fP"
.br
.ti -1c
.RI "class \fBLeapCylindricalSpace\fP"
.br
.ti -1c
.RI "class \fBLeapRadialSpace\fP"
.br
.ti -1c
.RI "class \fBLeapSpace\fP"
.br
.ti -1c
.RI "class \fBLeapSpaceAnchor\fP"
.br
.ti -1c
.RI "class \fBLeapSphericalSpace\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
