.TH "Leap.Unity.Attributes.UnitCurveAttribute" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.UnitCurveAttribute \- You can use this attribute to mark that an AnimationCurve can only have values that range from 0 to 1\&. The user will be prevented from entering a curve that lies outside of these bounds\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Attributes\&.CurveBoundsAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnitCurveAttribute\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
You can use this attribute to mark that an AnimationCurve can only have values that range from 0 to 1\&. The user will be prevented from entering a curve that lies outside of these bounds\&. 


.PP
Definition at line 52 of file CurveBounds\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Attributes\&.UnitCurveAttribute\&.UnitCurveAttribute ()"

.PP
Definition at line 53 of file CurveBounds\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
