.TH "Leap.Unity.SkeletalHand" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.SkeletalHand
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.HandModel\fP\&.
.PP
Inherited by \fBLeap\&.Unity\&.RigidHand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBUpdateHand\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Vector3 \fBGetPalmCenter\fP ()"
.br
.ti -1c
.RI "void \fBSetPositions\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const float \fBPALM_CENTER_OFFSET\fP = 0\&.015f"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override \fBModelType\fP \fBHandModelType\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A hand object consisting of discrete, component parts\&.
.PP
The hand can have game objects for the palm, wrist and forearm, as well as fingers\&. 
.PP
Definition at line 20 of file SkeletalHand\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Vector3 Leap\&.Unity\&.SkeletalHand\&.GetPalmCenter ()\fC [protected]\fP"

.PP
Definition at line 44 of file SkeletalHand\&.cs\&.
.SS "void Leap\&.Unity\&.SkeletalHand\&.SetPositions ()\fC [protected]\fP"

.PP
Definition at line 49 of file SkeletalHand\&.cs\&.
.SS "override void Leap\&.Unity\&.SkeletalHand\&.UpdateHand ()\fC [virtual]\fP"
Updates the hand and its component parts by setting their positions and rotations\&. 
.PP
Implements \fBLeap\&.Unity\&.HandModel\fP\&.
.PP
Definition at line 40 of file SkeletalHand\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const float Leap\&.Unity\&.SkeletalHand\&.PALM_CENTER_OFFSET = 0\&.015f\fC [protected]\fP"

.PP
Definition at line 26 of file SkeletalHand\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override \fBModelType\fP Leap\&.Unity\&.SkeletalHand\&.HandModelType\fC [get]\fP"

.PP
Definition at line 21 of file SkeletalHand\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
