.TH "Leap.Unity.Attributes" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAutoFindAttribute\fP"
.br
.ti -1c
.RI "class \fBCombinablePropertyAttribute\fP"
.br
.ti -1c
.RI "class \fBCombinablePropertyDrawer\fP"
.br
.ti -1c
.RI "class \fBCurveBoundsAttribute\fP"
.br
.RI "You can use this attribute to mark that an AnimationCurve can only have values that fall within specific bounds\&. The user will be prevented from entering a curve that lies outside of these bounds\&. "
.ti -1c
.RI "class \fBDisableAttribute\fP"
.br
.ti -1c
.RI "class \fBDisableIf\fP"
.br
.ti -1c
.RI "class \fBDisableIfAll\fP"
.br
.ti -1c
.RI "class \fBDisableIfAny\fP"
.br
.ti -1c
.RI "class \fBDisableIfBase\fP"
.br
.RI "Conditionally disables a property based on the value of another property\&. The only condition types that are currently supported are bool types, and enum types\&. The property has two arguments names 'equalTo' and 'notEqualTo'\&. Exactly one of them must be specified, like so: "
.ti -1c
.RI "class \fBEditTimeOnly\fP"
.br
.ti -1c
.RI "class \fBEnumFlags\fP"
.br
.ti -1c
.RI "interface \fBIAdditiveDrawer\fP"
.br
.ti -1c
.RI "interface \fBIAfterFieldAdditiveDrawer\fP"
.br
.ti -1c
.RI "interface \fBIAfterLabelAdditiveDrawer\fP"
.br
.ti -1c
.RI "interface \fBIBeforeFieldAdditiveDrawer\fP"
.br
.ti -1c
.RI "interface \fBIBeforeLabelAdditiveDrawer\fP"
.br
.ti -1c
.RI "interface \fBIFullPropertyDrawer\fP"
.br
.ti -1c
.RI "class \fBImplementsInterfaceAttribute\fP"
.br
.ti -1c
.RI "class \fBImplementsTypeNameDropdownAttribute\fP"
.br
.RI "Place this attribute on a serialized string field to have it render as a dropdown menu that is automatically populated with implementing types of the type provided to the attribute\&. The string field will contain the type name selected by the user\&. This can be converted into a Type reference via reflection and used to construct objects by their type, for example, or to construct ScriptableObjects by their type\&. "
.ti -1c
.RI "class \fBIncrementable\fP"
.br
.ti -1c
.RI "class \fBInspectorNameAttribute\fP"
.br
.ti -1c
.RI "interface \fBIPropertyConstrainer\fP"
.br
.ti -1c
.RI "interface \fBIPropertyDisabler\fP"
.br
.ti -1c
.RI "interface \fBISupportDragAndDrop\fP"
.br
.ti -1c
.RI "class \fBMaxValue\fP"
.br
.ti -1c
.RI "class \fBMinMax\fP"
.br
.ti -1c
.RI "class \fBMinValue\fP"
.br
.ti -1c
.RI "class \fBOnEditorChangeAttribute\fP"
.br
.RI "Use the OnChange attribute to recieve a callback whenever a field is changed\&. The callback can be in the form of: "
.ti -1c
.RI "class \fBQuickButtonAttribute\fP"
.br
.ti -1c
.RI "class \fBRunTimeOnlyAttribute\fP"
.br
.ti -1c
.RI "class \fBUnitCurveAttribute\fP"
.br
.RI "You can use this attribute to mark that an AnimationCurve can only have values that range from 0 to 1\&. The user will be prevented from entering a curve that lies outside of these bounds\&. "
.ti -1c
.RI "class \fBUnitsAttribute\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBUnityObject\fP = \fBUnityEngine\&.Object\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAutoFindLocations\fP { \fBAutoFindLocations\&.Object\fP = 0x01, \fBAutoFindLocations\&.Children\fP = 0x02, \fBAutoFindLocations\&.Parents\fP = 0x04, \fBAutoFindLocations\&.Scene\fP = 0x08, \fBAutoFindLocations\&.All\fP = 0xFFFF }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBLeap\&.Unity\&.Attributes\&.UnityObject\fP = typedef \fBUnityEngine\&.Object\fP"

.PP
Definition at line 20 of file CombinablePropertyAttribute\&.cs\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLeap\&.Unity\&.Attributes\&.AutoFindLocations\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIObject \fP\fP
.TP
\fB\fIChildren \fP\fP
.TP
\fB\fIParents \fP\fP
.TP
\fB\fIScene \fP\fP
.TP
\fB\fIAll \fP\fP
.PP
Definition at line 15 of file AutoFind\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
