.TH "Leap.Unity.EnableDepthBuffer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.EnableDepthBuffer
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBDEPTH_TEXTURE_VARIANT_NAME\fP = 'USE_DEPTH_TEXTURE'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file EnableDepthBuffer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Leap\&.Unity\&.EnableDepthBuffer\&.DEPTH_TEXTURE_VARIANT_NAME = 'USE_DEPTH_TEXTURE'"

.PP
Definition at line 16 of file EnableDepthBuffer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
