.TH "Leap.Unity.Interaction.AnchorGroup" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Interaction.AnchorGroup
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBContains\fP (\fBAnchor\fP anchor)"
.br
.ti -1c
.RI "bool \fBAdd\fP (\fBAnchor\fP anchor)"
.br
.ti -1c
.RI "bool \fBRemove\fP (\fBAnchor\fP anchor)"
.br
.ti -1c
.RI "void \fBNotifyAnchorableObjectAdded\fP (\fBAnchorableBehaviour\fP anchObj)"
.br
.ti -1c
.RI "void \fBNotifyAnchorableObjectRemoved\fP (\fBAnchorableBehaviour\fP anchObj)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAnchorSet\fP \fBanchors\fP\fC [get]\fP"
.br
.ti -1c
.RI "HashSet< \fBAnchorableBehaviour\fP > \fBanchorableObjects\fP\fC [get]\fP"
.br
.RI "Gets the AnchorableBehaviours that are set to this \fBAnchorGroup\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file AnchorGroup\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Leap\&.Unity\&.Interaction\&.AnchorGroup\&.Add (\fBAnchor\fP anchor)"

.PP
Definition at line 50 of file AnchorGroup\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.AnchorGroup\&.Contains (\fBAnchor\fP anchor)"

.PP
Definition at line 46 of file AnchorGroup\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.AnchorGroup\&.NotifyAnchorableObjectAdded (\fBAnchorableBehaviour\fP anchObj)"

.PP
Definition at line 70 of file AnchorGroup\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.AnchorGroup\&.NotifyAnchorableObjectRemoved (\fBAnchorableBehaviour\fP anchObj)"

.PP
Definition at line 74 of file AnchorGroup\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.AnchorGroup\&.Remove (\fBAnchor\fP anchor)"

.PP
Definition at line 60 of file AnchorGroup\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "HashSet<\fBAnchorableBehaviour\fP> Leap\&.Unity\&.Interaction\&.AnchorGroup\&.anchorableObjects\fC [get]\fP"

.PP
Gets the AnchorableBehaviours that are set to this \fBAnchorGroup\fP\&. 
.PP
Definition at line 32 of file AnchorGroup\&.cs\&.
.SS "\fBAnchorSet\fP Leap\&.Unity\&.Interaction\&.AnchorGroup\&.anchors\fC [get]\fP"

.PP
Definition at line 26 of file AnchorGroup\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
