.TH "Leap.DistortionEventArgs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.DistortionEventArgs \- Dispatched when the image distortion map changes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.LeapEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDistortionEventArgs\fP (\fBDistortionData\fP \fBdistortion\fP, \fBImage\&.CameraType\fP \fBcamera\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDistortionData\fP \fBdistortion\fP\fC [get, protected set]\fP"
.br
.ti -1c
.RI "\fBImage\&.CameraType\fP \fBcamera\fP\fC [get, protected set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dispatched when the image distortion map changes\&. 

Provides the new distortion map as an argument\&. 
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 114 of file Events\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.DistortionEventArgs\&.DistortionEventArgs (\fBDistortionData\fP distortion, \fBImage\&.CameraType\fP camera)"

.PP
Definition at line 115 of file Events\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBImage\&.CameraType\fP Leap\&.DistortionEventArgs\&.camera\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line 120 of file Events\&.cs\&.
.SS "\fBDistortionData\fP Leap\&.DistortionEventArgs\&.distortion\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line 119 of file Events\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
