.TH "Leap.Unity.HandTransitionBehavior" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.HandTransitionBehavior \- A component to be attached to a \fBHandModelBase\fP to handle starting and ending of tracking\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBLeap\&.Unity\&.HandDrop\fP, and \fBLeap\&.Unity\&.HandEnableDisable\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBHandReset\fP ()"
.br
.ti -1c
.RI "abstract void \fBHandFinish\fP ()"
.br
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDestroy\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBHandModelBase\fP \fBhandModelBase\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A component to be attached to a \fBHandModelBase\fP to handle starting and ending of tracking\&. 


.PP
Definition at line 19 of file HandTransitionBehavior\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Leap\&.Unity\&.HandTransitionBehavior\&.Awake ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBLeap\&.Unity\&.HandDrop\fP, and \fBLeap\&.Unity\&.HandEnableDisable\fP\&.
.PP
Definition at line 26 of file HandTransitionBehavior\&.cs\&.
.SS "abstract void Leap\&.Unity\&.HandTransitionBehavior\&.HandFinish ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBLeap\&.Unity\&.HandDrop\fP, and \fBLeap\&.Unity\&.HandEnableDisable\fP\&.
.SS "abstract void Leap\&.Unity\&.HandTransitionBehavior\&.HandReset ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBLeap\&.Unity\&.HandDrop\fP, and \fBLeap\&.Unity\&.HandEnableDisable\fP\&.
.SS "virtual void Leap\&.Unity\&.HandTransitionBehavior\&.OnDestroy ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 41 of file HandTransitionBehavior\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHandModelBase\fP Leap\&.Unity\&.HandTransitionBehavior\&.handModelBase\fC [protected]\fP"

.PP
Definition at line 21 of file HandTransitionBehavior\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
