.TH "Leap.Unity.Space.LeapSpace" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Space.LeapSpace
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Space\&.LeapSpaceAnchor\fP\&.
.PP
Inherited by \fBLeap\&.Unity\&.Space\&.LeapRadialSpace\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRebuildHierarchy\fP ()"
.br
.RI "Call to traverse the entire hierarchy and rebuild the relationship between anchors\&. Call this whenever any of the following happens: "
.ti -1c
.RI "void \fBRecalculateTransformers\fP ()"
.br
.RI "Call to update all transformers in the space\&. Call this whenever any anchor or parent of an anchor changes it's transform\&. "
.ti -1c
.RI "abstract \fBHash\fP \fBGetSettingHash\fP ()"
.br
.RI "Get a hash of all features in this space\&. This is useful if you want to know if anything has changed about the settings of this space\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "abstract \fBITransformer\fP \fBCosntructBaseTransformer\fP ()"
.br
.ti -1c
.RI "abstract \fBITransformer\fP \fBConstructTransformer\fP (\fBLeapSpaceAnchor\fP anchor)"
.br
.ti -1c
.RI "abstract void \fBUpdateTransformer\fP (\fBITransformer\fP \fBtransformer\fP, \fBITransformer\fP \fBparent\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static List< \fBLeapSpace\fP > \fBallEnabled\fP\fC [get]\fP"
.br
.ti -1c
.RI "List< \fBLeapSpaceAnchor\fP > \fBanchors\fP\fC [get]\fP"
.br
.RI "Returns all active anchors in depth-first pre-order "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file LeapSpace\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract \fBITransformer\fP Leap\&.Unity\&.Space\&.LeapSpace\&.ConstructTransformer (\fBLeapSpaceAnchor\fP anchor)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBLeap\&.Unity\&.Space\&.LeapSphericalSpace\fP, and \fBLeap\&.Unity\&.Space\&.LeapCylindricalSpace\fP\&.
.SS "abstract \fBITransformer\fP Leap\&.Unity\&.Space\&.LeapSpace\&.CosntructBaseTransformer ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBLeap\&.Unity\&.Space\&.LeapSphericalSpace\fP, and \fBLeap\&.Unity\&.Space\&.LeapCylindricalSpace\fP\&.
.SS "abstract \fBHash\fP Leap\&.Unity\&.Space\&.LeapSpace\&.GetSettingHash ()\fC [pure virtual]\fP"

.PP
Get a hash of all features in this space\&. This is useful if you want to know if anything has changed about the settings of this space\&. 
.PP
Implemented in \fBLeap\&.Unity\&.Space\&.LeapRadialSpace\fP\&.
.SS "override void Leap\&.Unity\&.Space\&.LeapSpace\&.OnDisable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.Space\&.LeapSpaceAnchor\fP\&.
.PP
Definition at line 43 of file LeapSpace\&.cs\&.
.SS "override void Leap\&.Unity\&.Space\&.LeapSpace\&.OnEnable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.Space\&.LeapSpaceAnchor\fP\&.
.PP
Definition at line 34 of file LeapSpace\&.cs\&.
.SS "void Leap\&.Unity\&.Space\&.LeapSpace\&.RebuildHierarchy ()"

.PP
Call to traverse the entire hierarchy and rebuild the relationship between anchors\&. Call this whenever any of the following happens: 
.IP "\(bu" 2
An anchor is created
.IP "\(bu" 2
An anchor is enabled / disabled
.IP "\(bu" 2
An enabled anchor is destroyed
.IP "\(bu" 2
The relative position in the hierarchy of any two anchors changes\&. 
.PP

.PP
Definition at line 71 of file LeapSpace\&.cs\&.
.SS "void Leap\&.Unity\&.Space\&.LeapSpace\&.RecalculateTransformers ()"

.PP
Call to update all transformers in the space\&. Call this whenever any anchor or parent of an anchor changes it's transform\&. 
.PP
Definition at line 85 of file LeapSpace\&.cs\&.
.SS "abstract void Leap\&.Unity\&.Space\&.LeapSpace\&.UpdateTransformer (\fBITransformer\fP transformer, \fBITransformer\fP parent)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBLeap\&.Unity\&.Space\&.LeapRadialSpace\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBLeapSpace\fP> Leap\&.Unity\&.Space\&.LeapSpace\&.allEnabled\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 19 of file LeapSpace\&.cs\&.
.SS "List<\fBLeapSpaceAnchor\fP> Leap\&.Unity\&.Space\&.LeapSpace\&.anchors\fC [get]\fP"

.PP
Returns all active anchors in depth-first pre-order 
.PP
Definition at line 57 of file LeapSpace\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
