.TH "Leap.Unity.Attributes.QuickButtonAttribute" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.QuickButtonAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Attributes\&.CombinablePropertyAttribute\fP, and \fBLeap\&.Unity\&.Attributes\&.IAfterFieldAdditiveDrawer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuickButtonAttribute\fP (string buttonLabel, string \fBmethodOnPress\fP, string \fBtooltip\fP='')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const float \fBPADDING_RIGHT\fP = 12f"
.br
.ti -1c
.RI "readonly string \fBlabel\fP = 'Quick Button'"
.br
.ti -1c
.RI "readonly string \fBmethodOnPress\fP = null"
.br
.ti -1c
.RI "readonly string \fBtooltip\fP = ''"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file QuickButton\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Attributes\&.QuickButtonAttribute\&.QuickButtonAttribute (string buttonLabel, string methodOnPress, string tooltip = \fC''\fP)"

.PP
Definition at line 29 of file QuickButton\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly string Leap\&.Unity\&.Attributes\&.QuickButtonAttribute\&.label = 'Quick Button'"

.PP
Definition at line 25 of file QuickButton\&.cs\&.
.SS "readonly string Leap\&.Unity\&.Attributes\&.QuickButtonAttribute\&.methodOnPress = null"

.PP
Definition at line 26 of file QuickButton\&.cs\&.
.SS "const float Leap\&.Unity\&.Attributes\&.QuickButtonAttribute\&.PADDING_RIGHT = 12f"

.PP
Definition at line 23 of file QuickButton\&.cs\&.
.SS "readonly string Leap\&.Unity\&.Attributes\&.QuickButtonAttribute\&.tooltip = ''"

.PP
Definition at line 27 of file QuickButton\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
