.TH "Leap.Unity.Leap.Unity.Animation.Internal.TransformSelector" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Leap.Unity.Animation.Internal.TransformSelector
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransformSelector\fP (Transform target, Tween tween)"
.br
.ti -1c
.RI "Tween \fBPosition\fP (Vector3 a, Vector3 b)"
.br
.ti -1c
.RI "Tween \fBToPosition\fP (Vector3 b)"
.br
.ti -1c
.RI "Tween \fBByPosition\fP (Vector3 delta)"
.br
.ti -1c
.RI "Tween \fBPosition\fP (Transform a, Transform b)"
.br
.ti -1c
.RI "Tween \fBLocalPosition\fP (Vector3 a, Vector3 b)"
.br
.ti -1c
.RI "Tween \fBToLocalPosition\fP (Vector3 b)"
.br
.ti -1c
.RI "Tween \fBByLocalPosition\fP (Vector3 delta)"
.br
.ti -1c
.RI "Tween \fBLocalPosition\fP (Transform a, Transform b)"
.br
.ti -1c
.RI "Tween \fBRotation\fP (Quaternion a, Quaternion b)"
.br
.ti -1c
.RI "Tween \fBToRotation\fP (Quaternion b)"
.br
.ti -1c
.RI "Tween \fBByRotation\fP (Quaternion delta)"
.br
.ti -1c
.RI "Tween \fBRotation\fP (Transform a, Transform b)"
.br
.ti -1c
.RI "Tween \fBLocalRotation\fP (Quaternion a, Quaternion b)"
.br
.ti -1c
.RI "Tween \fBToLocalRotation\fP (Quaternion b)"
.br
.ti -1c
.RI "Tween \fBByLocalRotation\fP (Quaternion delta)"
.br
.ti -1c
.RI "Tween \fBLocalRotation\fP (Transform a, Transform b)"
.br
.ti -1c
.RI "Tween \fBLocalScale\fP (Vector3 a, Vector3 b)"
.br
.ti -1c
.RI "Tween \fBLocalScale\fP (float a, float b)"
.br
.ti -1c
.RI "Tween \fBToLocalScale\fP (Vector3 b)"
.br
.ti -1c
.RI "Tween \fBToLocalScale\fP (float b)"
.br
.ti -1c
.RI "Tween \fBByLocalScale\fP (float b)"
.br
.ti -1c
.RI "Tween \fBLocalScale\fP (Transform a, Transform b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file TransformInterpolators\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.TransformSelector (Transform target, Tween tween)"

.PP
Definition at line 29 of file TransformInterpolators\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.ByLocalPosition (Vector3 delta)"

.PP
Definition at line 59 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.ByLocalRotation (Quaternion delta)"

.PP
Definition at line 157 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.ByLocalScale (float b)"

.PP
Definition at line 247 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.ByPosition (Vector3 delta)"

.PP
Definition at line 43 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.ByRotation (Quaternion delta)"

.PP
Definition at line 141 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.LocalPosition (Vector3 a, Vector3 b)"

.PP
Definition at line 51 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.LocalPosition (Transform a, Transform b)"

.PP
Definition at line 63 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.LocalRotation (Quaternion a, Quaternion b)"

.PP
Definition at line 149 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.LocalRotation (Transform a, Transform b)"

.PP
Definition at line 161 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.LocalScale (Vector3 a, Vector3 b)"

.PP
Definition at line 231 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.LocalScale (float a, float b)"

.PP
Definition at line 235 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.LocalScale (Transform a, Transform b)"

.PP
Definition at line 251 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.Position (Vector3 a, Vector3 b)"

.PP
Definition at line 35 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.Position (Transform a, Transform b)"

.PP
Definition at line 47 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.Rotation (Quaternion a, Quaternion b)"

.PP
Definition at line 133 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.Rotation (Transform a, Transform b)"

.PP
Definition at line 145 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.ToLocalPosition (Vector3 b)"

.PP
Definition at line 55 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.ToLocalRotation (Quaternion b)"

.PP
Definition at line 153 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.ToLocalScale (Vector3 b)"

.PP
Definition at line 239 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.ToLocalScale (float b)"

.PP
Definition at line 243 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.ToPosition (Vector3 b)"

.PP
Definition at line 39 of file TransformInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.TransformSelector\&.ToRotation (Quaternion b)"

.PP
Definition at line 137 of file TransformInterpolators\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
