.TH "Leap.Unity.Examples.WorkstationPoseTest" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples.WorkstationPoseTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBuserCamera\fP"
.br
.ti -1c
.RI "Transform \fBstationObj\fP"
.br
.ti -1c
.RI "Transform \fBstationObjOneSecLater\fP"
.br
.ti -1c
.RI "float \fBmyRadius\fP"
.br
.ti -1c
.RI "Transform \fBotherOpenStationsParent\fP"
.br
.ti -1c
.RI "List< Vector3 > \fBotherOpenStationPositions\fP = new List<Vector3>()"
.br
.ti -1c
.RI "List< float > \fBotherOpenStationRadii\fP = new List<float>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file WorkstationPoseTest\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Leap\&.Unity\&.Examples\&.WorkstationPoseTest\&.myRadius"

.PP
Definition at line 27 of file WorkstationPoseTest\&.cs\&.
.SS "List<Vector3> Leap\&.Unity\&.Examples\&.WorkstationPoseTest\&.otherOpenStationPositions = new List<Vector3>()"

.PP
Definition at line 32 of file WorkstationPoseTest\&.cs\&.
.SS "List<float> Leap\&.Unity\&.Examples\&.WorkstationPoseTest\&.otherOpenStationRadii = new List<float>()"

.PP
Definition at line 34 of file WorkstationPoseTest\&.cs\&.
.SS "Transform Leap\&.Unity\&.Examples\&.WorkstationPoseTest\&.otherOpenStationsParent"

.PP
Definition at line 29 of file WorkstationPoseTest\&.cs\&.
.SS "Transform Leap\&.Unity\&.Examples\&.WorkstationPoseTest\&.stationObj"

.PP
Definition at line 24 of file WorkstationPoseTest\&.cs\&.
.SS "Transform Leap\&.Unity\&.Examples\&.WorkstationPoseTest\&.stationObjOneSecLater"

.PP
Definition at line 25 of file WorkstationPoseTest\&.cs\&.
.SS "Transform Leap\&.Unity\&.Examples\&.WorkstationPoseTest\&.userCamera"

.PP
Definition at line 23 of file WorkstationPoseTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
