.TH "Leap.Frame" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Frame \- The \fBFrame\fP class represents a set of hand and finger tracking data detected in a single frame\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IEquatable< Frame >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrame\fP ()"
.br
.RI "Constructs a \fBFrame\fP object\&. "
.ti -1c
.RI "\fBFrame\fP (long id, long timestamp, float fps, List< \fBHand\fP > hands)"
.br
.RI "Constructs a new \fBFrame\fP\&. "
.ti -1c
.RI "void \fBDeserialize\fP (byte[] arg)"
.br
.ti -1c
.RI "\fBHand\fP \fBHand\fP (int id)"
.br
.RI "The \fBHand\fP object with the specified ID in this frame, or null if none exists\&. "
.ti -1c
.RI "bool \fBEquals\fP (\fBFrame\fP other)"
.br
.RI "Compare \fBFrame\fP object equality\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "A string containing a brief, human readable description of the \fBFrame\fP object\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBId\fP"
.br
.RI "A unique ID for this \fBFrame\fP\&. "
.ti -1c
.RI "long \fBTimestamp\fP"
.br
.RI "The frame capture time in microseconds elapsed since an arbitrary point in time in the past\&. "
.ti -1c
.RI "float \fBCurrentFramesPerSecond\fP"
.br
.RI "The instantaneous framerate\&. "
.ti -1c
.RI "List< \fBHand\fP > \fBHands\fP"
.br
.RI "The list of \fBHand\fP objects detected in this frame, given in arbitrary order\&. The list can be empty if no hands are detected\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBSerializeLength\fP\fC [get]\fP"
.br
.ti -1c
.RI "byte [] \fBSerialize\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBFrame\fP class represents a set of hand and finger tracking data detected in a single frame\&. 

The \fBLeap\fP Motion software detects hands, fingers and tools within the tracking area, reporting their positions, orientations, gestures, and motions in frames at the \fBLeap\fP Motion frame rate\&.
.PP
Access \fBFrame\fP objects through an instance of the \fBController\fP class\&. 
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 25 of file Frame\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Frame\&.Frame ()"

.PP
Constructs a \fBFrame\fP object\&. \fBFrame\fP instances created with this constructor are invalid\&. Get valid \fBFrame\fP objects by calling the \fBController\&.Frame()\fP function\&.
.PP
The only time you should use this constructor is before deserializing serialized frame data, or if you are going to be passing this \fBFrame\fP to a method that fills it with valid data\&.
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 41 of file Frame\&.cs\&.
.SS "Leap\&.Frame\&.Frame (long id, long timestamp, float fps, List< \fBHand\fP > hands)"

.PP
Constructs a new \fBFrame\fP\&. 
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 49 of file Frame\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Frame\&.Deserialize (byte [] arg)"

.PP
Definition at line 71 of file Frame\&.cs\&.
.SS "bool Leap\&.Frame\&.Equals (\fBFrame\fP other)"

.PP
Compare \fBFrame\fP object equality\&. Two \fBFrame\fP objects are equal if and only if both \fBFrame\fP objects represent the exact same frame of tracking data and both \fBFrame\fP objects are valid\&. 
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 105 of file Frame\&.cs\&.
.SS "\fBHand\fP Leap\&.Frame\&.Hand (int id)"

.PP
The \fBHand\fP object with the specified ID in this frame, or null if none exists\&. Use the \fBFrame\&.Hand()\fP function to retrieve the \fBHand\fP object from this frame using an ID value obtained from a previous frame\&. This function always returns a \fBHand\fP object, but if no hand with the specified ID is present, an invalid \fBHand\fP object is returned\&.
.PP
Note that ID values persist across frames, but only until tracking of a particular object is lost\&. If tracking of a hand is lost and subsequently regained, the new \fBHand\fP object representing that physical hand may have a different ID than that representing the physical hand in an earlier frame\&. 
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 89 of file Frame\&.cs\&.
.SS "override string Leap\&.Frame\&.ToString ()"

.PP
A string containing a brief, human readable description of the \fBFrame\fP object\&. 
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 113 of file Frame\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Leap\&.Frame\&.CurrentFramesPerSecond"

.PP
The instantaneous framerate\&. The rate at which the \fBLeap\fP Motion software is providing frames of data (in frames per second)\&. The framerate can fluctuate depending on available computing resources, activity within the device field of view, software tracking settings, and other factors\&.
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 149 of file Frame\&.cs\&.
.SS "List<\fBHand\fP> Leap\&.Frame\&.Hands"

.PP
The list of \fBHand\fP objects detected in this frame, given in arbitrary order\&. The list can be empty if no hands are detected\&. 
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 157 of file Frame\&.cs\&.
.SS "long Leap\&.Frame\&.Id"

.PP
A unique ID for this \fBFrame\fP\&. Consecutive frames processed by the \fBLeap\fP Motion software have consecutive increasing values\&. You can use the frame ID to avoid processing the same \fBFrame\fP object twice, as well as to make sure that your application processes every frame\&.
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 127 of file Frame\&.cs\&.
.SS "long Leap\&.Frame\&.Timestamp"

.PP
The frame capture time in microseconds elapsed since an arbitrary point in time in the past\&. You can use \fBController\&.Now()\fP to calculate the age of the frame\&.
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 137 of file Frame\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "byte [] Leap\&.Frame\&.Serialize\fC [get]\fP"

.PP
Definition at line 64 of file Frame\&.cs\&.
.SS "int Leap\&.Frame\&.SerializeLength\fC [get]\fP"

.PP
Definition at line 57 of file Frame\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
