.TH "Leap.Unity.Attributes.DisableAttribute" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.DisableAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Attributes\&.CombinablePropertyAttribute\fP, and \fBLeap\&.Unity\&.Attributes\&.IPropertyDisabler\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file Disable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
