.TH "Leap.Unity.RiggedFinger" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.RiggedFinger \- Manages the position and orientation of the bones in a model rigged for skeletal animation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.FingerModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Quaternion \fBReorientation\fP ()"
.br
.ti -1c
.RI "override void \fBUpdateFinger\fP ()"
.br
.RI "Updates model bone positions and rotations based on tracked hand data\&. "
.ti -1c
.RI "void \fBSetupRiggedFinger\fP (bool useMetaCarpals)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBdeformPosition\fP = false"
.br
.RI "Allows the mesh to be stretched to align with finger joint positions\&. Only set to true when mesh is not visible\&. "
.ti -1c
.RI "bool \fBscaleLastFingerBone\fP = false"
.br
.ti -1c
.RI "Vector3 \fBmodelFingerPointing\fP = Vector3\&.forward"
.br
.ti -1c
.RI "Vector3 \fBmodelPalmFacing\fP = \-Vector3\&.up"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Manages the position and orientation of the bones in a model rigged for skeletal animation\&. 

The class expects that the graphics model's bones that correspond to the bones in the \fBLeap\fP Motion hand model are in the same order in the bones array\&. 
.PP
Definition at line 23 of file RiggedFinger\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Quaternion Leap\&.Unity\&.RiggedFinger\&.Reorientation ()"

.PP
Definition at line 38 of file RiggedFinger\&.cs\&.
.SS "void Leap\&.Unity\&.RiggedFinger\&.SetupRiggedFinger (bool useMetaCarpals)"

.PP
Definition at line 100 of file RiggedFinger\&.cs\&.
.SS "override void Leap\&.Unity\&.RiggedFinger\&.UpdateFinger ()\fC [virtual]\fP"

.PP
Updates model bone positions and rotations based on tracked hand data\&. 
.PP
Implements \fBLeap\&.Unity\&.FingerModel\fP\&.
.PP
Definition at line 61 of file RiggedFinger\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Leap\&.Unity\&.RiggedFinger\&.deformPosition = false"

.PP
Allows the mesh to be stretched to align with finger joint positions\&. Only set to true when mesh is not visible\&. 
.PP
Definition at line 30 of file RiggedFinger\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.RiggedFinger\&.modelFingerPointing = Vector3\&.forward"

.PP
Definition at line 35 of file RiggedFinger\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.RiggedFinger\&.modelPalmFacing = \-Vector3\&.up"

.PP
Definition at line 36 of file RiggedFinger\&.cs\&.
.SS "bool Leap\&.Unity\&.RiggedFinger\&.scaleLastFingerBone = false"

.PP
Definition at line 33 of file RiggedFinger\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
