.TH "Leap.Unity.SkeletalFinger" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.SkeletalFinger
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.FingerModel\fP\&.
.PP
Inherited by \fBLeap\&.Unity\&.RigidFinger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitFinger\fP ()"
.br
.ti -1c
.RI "override void \fBUpdateFinger\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetPositions\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A finger object consisting of discrete, component parts for each bone\&.
.PP
The graphic objects can include both bones and joints, but both are optional\&. 
.PP
Definition at line 20 of file SkeletalFinger\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Leap\&.Unity\&.SkeletalFinger\&.InitFinger ()\fC [virtual]\fP"
Initializes the finger bones and joints by setting their positions and rotations\&. 
.PP
Reimplemented from \fBLeap\&.Unity\&.FingerModel\fP\&.
.PP
Definition at line 23 of file SkeletalFinger\&.cs\&.
.SS "void Leap\&.Unity\&.SkeletalFinger\&.SetPositions ()\fC [protected]\fP"

.PP
Definition at line 32 of file SkeletalFinger\&.cs\&.
.SS "override void Leap\&.Unity\&.SkeletalFinger\&.UpdateFinger ()\fC [virtual]\fP"
Updates the finger bones and joints by setting their positions and rotations\&. 
.PP
Implements \fBLeap\&.Unity\&.FingerModel\fP\&.
.PP
Definition at line 28 of file SkeletalFinger\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
