.TH "Leap.Unity.Tests.SlidingMaxTest" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Tests.SlidingMaxTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.ti -1c
.RI "void \fBTeardown\fP ()"
.br
.ti -1c
.RI "void \fBIsFunctional\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBMAX_HISTORY\fP = 64"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file SlidingMaxTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Tests\&.SlidingMaxTest\&.IsFunctional ()"

.PP
Definition at line 32 of file SlidingMaxTest\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.SlidingMaxTest\&.Setup ()"

.PP
Definition at line 22 of file SlidingMaxTest\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.SlidingMaxTest\&.Teardown ()"

.PP
Definition at line 27 of file SlidingMaxTest\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Leap\&.Unity\&.Tests\&.SlidingMaxTest\&.MAX_HISTORY = 64"

.PP
Definition at line 17 of file SlidingMaxTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
