.TH "Leap.Unity.Tests.TransformCopyTranslation" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Tests.TransformCopyTranslation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Tests\&.FrameValidator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBIsTranslated\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override \fBFrame\fP \fBcreateFrame\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBFrame\fP \fB_originalFrame\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fBVector\fP \fBtranslation\fP = \fBVector\&.Forward\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file TransformCopyTest\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBFrame\fP Leap\&.Unity\&.Tests\&.TransformCopyTranslation\&.createFrame ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBLeap\&.Unity\&.Tests\&.FrameValidator\fP\&.
.PP
Definition at line 111 of file TransformCopyTest\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.TransformCopyTranslation\&.IsTranslated ()"

.PP
Definition at line 118 of file TransformCopyTest\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFrame\fP Leap\&.Unity\&.Tests\&.TransformCopyTranslation\&._originalFrame\fC [protected]\fP"

.PP
Definition at line 109 of file TransformCopyTest\&.cs\&.
.SS "\fBVector\fP Leap\&.Unity\&.Tests\&.TransformCopyTranslation\&.translation = \fBVector\&.Forward\fP\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 108 of file TransformCopyTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
