.TH "Leap.Unity.LeapPreferences" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.LeapPreferences \- This attribute is used to add items to the \fBLeap\fP Motion preferences window\&. This allows each module to define their own preferences and still have them all show up under the same window\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLeapPreferences\fP (string \fBheader\fP, int \fBorder\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBheader\fP"
.br
.ti -1c
.RI "readonly int \fBorder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This attribute is used to add items to the \fBLeap\fP Motion preferences window\&. This allows each module to define their own preferences and still have them all show up under the same window\&. 

The usage is very similar to the built-in PreferenceItem attribute\&. You add the attribute onto a static method that should be run whenever the preference window is visited\&. This method is a gui method and should use GuiLayout and EditorGuiLayout in order to draw the preferences\&. You can specify the name of the preferences as well as an order value to specify how the preferences are ordered relative to other preferences\&. 
.PP
Definition at line 33 of file LeapPreferences\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.LeapPreferences\&.LeapPreferences (string header, int order)"

.PP
Definition at line 37 of file LeapPreferences\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly string Leap\&.Unity\&.LeapPreferences\&.header"

.PP
Definition at line 34 of file LeapPreferences\&.cs\&.
.SS "readonly int Leap\&.Unity\&.LeapPreferences\&.order"

.PP
Definition at line 35 of file LeapPreferences\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
