.TH "Leap.Unity.Interaction.IGraspedPoseHandler" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Interaction.IGraspedPoseHandler \- An \fBIGraspedPoseHandler\fP specifies where an object grasped by a \fBLeap\fP hand or controller (or multiple hands/controllers) should move as the grasping controllers(s) move\&. The default implementation provided by the \fBInteraction\fP Engine is the \fBKabschGraspedPose\fP, which produces a physically-intuitive following motion for the object no matter how a grasping hand moves\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLeap\&.Unity\&.Interaction\&.KabschGraspedPose\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddController\fP (\fBInteractionController\fP controller)"
.br
.RI "Called when a new \fBInteractionController\fP begins grasping a certain object\&. The controller or \fBLeap\fP hand should be included in the held pose calculation\&. "
.ti -1c
.RI "void \fBRemoveController\fP (\fBInteractionController\fP controller)"
.br
.RI "Called when an \fBInteractionController\fP stops grasping a certain object; the controller should no longer be included in the held pose calculation\&. "
.ti -1c
.RI "void \fBClearControllers\fP ()"
.br
.RI "Called e\&.g\&. if the \fBInteractionBehaviour\fP is set not to move while being grasped; this should clear any hands to be included in the grasping position calculation\&. "
.ti -1c
.RI "void \fBGetGraspedPosition\fP (out Vector3 position, out Quaternion rotation)"
.br
.RI "Calculate the best holding position and orientation given the current state of all InteractionControllers (added via \fBAddController()\fP)\&. "
.in -1c
.SH "Detailed Description"
.PP 
An \fBIGraspedPoseHandler\fP specifies where an object grasped by a \fBLeap\fP hand or controller (or multiple hands/controllers) should move as the grasping controllers(s) move\&. The default implementation provided by the \fBInteraction\fP Engine is the \fBKabschGraspedPose\fP, which produces a physically-intuitive following motion for the object no matter how a grasping hand moves\&. 

IGraspedPoseHandlers do not actually move an object; they only calculate where an object should be moved\&. Actually moving the object is the concern of an \fBIGraspedMovementHandler\fP\&. 
.PP
Definition at line 27 of file IGraspedPoseHandler\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Interaction\&.IGraspedPoseHandler\&.AddController (\fBInteractionController\fP controller)"

.PP
Called when a new \fBInteractionController\fP begins grasping a certain object\&. The controller or \fBLeap\fP hand should be included in the held pose calculation\&. 
.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.KabschGraspedPose\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IGraspedPoseHandler\&.ClearControllers ()"

.PP
Called e\&.g\&. if the \fBInteractionBehaviour\fP is set not to move while being grasped; this should clear any hands to be included in the grasping position calculation\&. 
.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.KabschGraspedPose\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IGraspedPoseHandler\&.GetGraspedPosition (out Vector3 position, out Quaternion rotation)"

.PP
Calculate the best holding position and orientation given the current state of all InteractionControllers (added via \fBAddController()\fP)\&. 
.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.KabschGraspedPose\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IGraspedPoseHandler\&.RemoveController (\fBInteractionController\fP controller)"

.PP
Called when an \fBInteractionController\fP stops grasping a certain object; the controller should no longer be included in the held pose calculation\&. 
.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.KabschGraspedPose\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
