.TH "Leap.Unity.FpsLabel" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.FpsLabel
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
Definition at line 13 of file FpsLabel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
