.TH "LeapInternal.LEAP_CONFIG_RESPONSE_EVENT_WITH_REF_TYPE" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_CONFIG_RESPONSE_EVENT_WITH_REF_TYPE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UInt32 \fBrequestId\fP"
.br
.ti -1c
.RI "\fBLEAP_VARIANT_REF_TYPE\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 757 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "UInt32 LeapInternal\&.LEAP_CONFIG_RESPONSE_EVENT_WITH_REF_TYPE\&.requestId"

.PP
Definition at line 758 of file LeapC\&.cs\&.
.SS "\fBLEAP_VARIANT_REF_TYPE\fP LeapInternal\&.LEAP_CONFIG_RESPONSE_EVENT_WITH_REF_TYPE\&.value"

.PP
Definition at line 759 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
