.TH "Leap.Unity.Examples.TransformHandle" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples.TransformHandle
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBLeap\&.Unity\&.Examples\&.TransformRotationHandle\fP, and \fBLeap\&.Unity\&.Examples\&.TransformTranslationHandle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsyncRigidbodyWithTransform\fP ()"
.br
.ti -1c
.RI "void \fBEnsureVisible\fP ()"
.br
.RI "Called by the Transform Tool when this handle should be visible\&. "
.ti -1c
.RI "void \fBEnsureHidden\fP ()"
.br
.RI "Called by the Transform Tool when this handle should not be visible\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBOnShouldShowHandle\fP = new UnityEvent()"
.br
.ti -1c
.RI "UnityEvent \fBOnShouldHideHandle\fP = new UnityEvent()"
.br
.ti -1c
.RI "UnityEvent \fBOnHandleActivated\fP = new UnityEvent()"
.br
.ti -1c
.RI "UnityEvent \fBOnHandleDeactivated\fP = new UnityEvent()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBStart\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBInteractionBehaviour\fP \fB_intObj\fP"
.br
.ti -1c
.RI "\fBTransformTool\fP \fB_tool\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file TransformHandle\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Examples\&.TransformHandle\&.EnsureHidden ()"

.PP
Called by the Transform Tool when this handle should not be visible\&. 
.PP
Definition at line 70 of file TransformHandle\&.cs\&.
.SS "void Leap\&.Unity\&.Examples\&.TransformHandle\&.EnsureVisible ()"

.PP
Called by the Transform Tool when this handle should be visible\&. 
.PP
Definition at line 61 of file TransformHandle\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Examples\&.TransformHandle\&.Start ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBLeap\&.Unity\&.Examples\&.TransformTranslationHandle\fP, and \fBLeap\&.Unity\&.Examples\&.TransformRotationHandle\fP\&.
.PP
Definition at line 30 of file TransformHandle\&.cs\&.
.SS "void Leap\&.Unity\&.Examples\&.TransformHandle\&.syncRigidbodyWithTransform ()"

.PP
Definition at line 39 of file TransformHandle\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBInteractionBehaviour\fP Leap\&.Unity\&.Examples\&.TransformHandle\&._intObj\fC [protected]\fP"

.PP
Definition at line 22 of file TransformHandle\&.cs\&.
.SS "\fBTransformTool\fP Leap\&.Unity\&.Examples\&.TransformHandle\&._tool\fC [protected]\fP"

.PP
Definition at line 23 of file TransformHandle\&.cs\&.
.SS "UnityEvent Leap\&.Unity\&.Examples\&.TransformHandle\&.OnHandleActivated = new UnityEvent()"

.PP
Definition at line 27 of file TransformHandle\&.cs\&.
.SS "UnityEvent Leap\&.Unity\&.Examples\&.TransformHandle\&.OnHandleDeactivated = new UnityEvent()"

.PP
Definition at line 28 of file TransformHandle\&.cs\&.
.SS "UnityEvent Leap\&.Unity\&.Examples\&.TransformHandle\&.OnShouldHideHandle = new UnityEvent()"

.PP
Definition at line 26 of file TransformHandle\&.cs\&.
.SS "UnityEvent Leap\&.Unity\&.Examples\&.TransformHandle\&.OnShouldShowHandle = new UnityEvent()"

.PP
Definition at line 25 of file TransformHandle\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
