.TH "Leap.Unity.Attributes.ISupportDragAndDrop" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.ISupportDragAndDrop
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLeap\&.Unity\&.Attributes\&.ImplementsInterfaceAttribute\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 47 of file CombinablePropertyAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
