.TH "O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/EditorTools/LeapProjectChecks.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/EditorTools/LeapProjectChecks.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLeap\&.Unity\&.LeapProjectCheckAttribute\fP"
.br
.RI "Add this attribute to a settings check\&. This method will be called often while the \fBLeap\fP Motion \fBUnity\fP Window is open, so it should be as light-weight as possible! If you need to do a heavy check that involves scanning the current scene for example, you should gate the check behind a button\&. "
.ti -1c
.RI "class \fBLeap\&.Unity\&.LeapProjectChecks\fP"
.br
.RI "Utility class for working with project checks\&. Note, most features are only available in the Editor\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLeap\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
