.TH "Leap.Unity.Leap.Unity.Animation.Internal.MaterialSelector" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Leap.Unity.Animation.Internal.MaterialSelector
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterialSelector\fP (\fBMaterial\fP target, Tween tween)"
.br
.ti -1c
.RI "Tween \fBColor\fP (Color a, Color b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBColor\fP (Color a, Color b, string propertyName='_Color')"
.br
.ti -1c
.RI "Tween \fBColor\fP (Gradient gradient, int propertyId)"
.br
.ti -1c
.RI "Tween \fBColor\fP (Gradient gradient, string propertyName='_Color')"
.br
.ti -1c
.RI "Tween \fBToColor\fP (\fBColor\fP b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBToColor\fP (\fBColor\fP b, string propertyName='_Color')"
.br
.ti -1c
.RI "Tween \fBRGB\fP (\fBColor\fP a, \fBColor\fP b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBRGB\fP (\fBColor\fP a, \fBColor\fP b, string propertyName='_Color')"
.br
.ti -1c
.RI "Tween \fBToRGB\fP (\fBColor\fP b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBToRGB\fP (\fBColor\fP b, string propertyName='_Color')"
.br
.ti -1c
.RI "Tween \fBAlpha\fP (float a, float b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBAlpha\fP (float a, float b, string propertyName='_Color')"
.br
.ti -1c
.RI "Tween \fBToAlpha\fP (float b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBToAlpha\fP (float b, string propertyName='_Color')"
.br
.ti -1c
.RI "Tween \fBFloat\fP (float a, float b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBFloat\fP (float a, float b, string propertyName)"
.br
.ti -1c
.RI "Tween \fBToFloat\fP (float b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBToFloat\fP (float b, string propertyName)"
.br
.ti -1c
.RI "Tween \fBVector\fP (Vector4 a, Vector4 b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBVector\fP (Vector4 a, Vector4 b, string propertyName)"
.br
.ti -1c
.RI "Tween \fBVector\fP (Vector3 a, Vector3 b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBVector\fP (Vector3 a, Vector3 b, string propertyName)"
.br
.ti -1c
.RI "Tween \fBToVector\fP (Vector4 b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBToVector\fP (Vector4 b, string propertyName)"
.br
.ti -1c
.RI "Tween \fBToVector\fP (Vector3 b, int propertyId)"
.br
.ti -1c
.RI "Tween \fBToVector\fP (Vector3 b, string propertyName)"
.br
.ti -1c
.RI "Tween \fBMaterial\fP (Material a, Material b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file MaterialInterpolators\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.MaterialSelector (\fBMaterial\fP target, Tween tween)"

.PP
Definition at line 28 of file MaterialInterpolators\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Alpha (float a, float b, int propertyId)"

.PP
Definition at line 74 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Alpha (float a, float b, string propertyName = \fC'_Color'\fP)"

.PP
Definition at line 78 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Color (Color a, Color b, int propertyId)"

.PP
Definition at line 34 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Color (Color a, Color b, string propertyName = \fC'_Color'\fP)"

.PP
Definition at line 38 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Color (Gradient gradient, int propertyId)"

.PP
Definition at line 42 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Color (Gradient gradient, string propertyName = \fC'_Color'\fP)"

.PP
Definition at line 46 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Float (float a, float b, int propertyId)"

.PP
Definition at line 156 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Float (float a, float b, string propertyName)"

.PP
Definition at line 160 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Material (Material a, Material b)"

.PP
Definition at line 234 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.RGB (\fBColor\fP a, \fBColor\fP b, int propertyId)"

.PP
Definition at line 58 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.RGB (\fBColor\fP a, \fBColor\fP b, string propertyName = \fC'_Color'\fP)"

.PP
Definition at line 62 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToAlpha (float b, int propertyId)"

.PP
Definition at line 82 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToAlpha (float b, string propertyName = \fC'_Color'\fP)"

.PP
Definition at line 86 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToColor (\fBColor\fP b, int propertyId)"

.PP
Definition at line 50 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToColor (\fBColor\fP b, string propertyName = \fC'_Color'\fP)"

.PP
Definition at line 54 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToFloat (float b, int propertyId)"

.PP
Definition at line 164 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToFloat (float b, string propertyName)"

.PP
Definition at line 168 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToRGB (\fBColor\fP b, int propertyId)"

.PP
Definition at line 66 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToRGB (\fBColor\fP b, string propertyName = \fC'_Color'\fP)"

.PP
Definition at line 70 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToVector (Vector4 b, int propertyId)"

.PP
Definition at line 203 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToVector (Vector4 b, string propertyName)"

.PP
Definition at line 207 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToVector (Vector3 b, int propertyId)"

.PP
Definition at line 211 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.ToVector (Vector3 b, string propertyName)"

.PP
Definition at line 215 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Vector (Vector4 a, Vector4 b, int propertyId)"

.PP
Definition at line 187 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Vector (Vector4 a, Vector4 b, string propertyName)"

.PP
Definition at line 191 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Vector (Vector3 a, Vector3 b, int propertyId)"

.PP
Definition at line 195 of file MaterialInterpolators\&.cs\&.
.SS "Tween Leap\&.Unity\&.Leap\&.Unity\&.Animation\&.Internal\&.MaterialSelector\&.Vector (Vector3 a, Vector3 b, string propertyName)"

.PP
Definition at line 199 of file MaterialInterpolators\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
