.TH "LeapInternal.LEAP_DEVICE_REF" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_DEVICE_REF
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IntPtr \fBhandle\fP"
.br
.ti -1c
.RI "UInt32 \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 481 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "IntPtr LeapInternal\&.LEAP_DEVICE_REF\&.handle"

.PP
Definition at line 482 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_DEVICE_REF\&.id"

.PP
Definition at line 483 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
