.TH "Leap.Unity.ConnectionMonitor" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.ConnectionMonitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLeapServiceProvider\fP \fBprovider\fP"
.br
.ti -1c
.RI "float \fBfadeInTime\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBfadeOutTime\fP = 1\&.0f"
.br
.ti -1c
.RI "AnimationCurve \fBfadeCurve\fP = AnimationCurve\&.EaseInOut(0\&.0f, 0\&.0f, 1\&.0f, 1\&.0f)"
.br
.ti -1c
.RI "int \fBmonitorInterval\fP = 2"
.br
.ti -1c
.RI "Color \fBonColor\fP = Color\&.white"
.br
.ti -1c
.RI "float \fBdistanceToCamera\fP = 12\&.0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBConnectionMonitor\fP class monitors the connection to the \fBLeap\fP Motion service and displays a sprite in front of the camera when a connection is not available\&. You can use the PluginLeapNotice sprites in the LeapMotion/Textures folder or create your own\&. 
.PP
Definition at line 22 of file ConnectionMonitor\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Leap\&.Unity\&.ConnectionMonitor\&.distanceToCamera = 12\&.0f"
The distance of the notification sprite from the camera in world units\&. 
.PP
Definition at line 45 of file ConnectionMonitor\&.cs\&.
.SS "AnimationCurve Leap\&.Unity\&.ConnectionMonitor\&.fadeCurve = AnimationCurve\&.EaseInOut(0\&.0f, 0\&.0f, 1\&.0f, 1\&.0f)"
The easing curve\&. 
.PP
Definition at line 36 of file ConnectionMonitor\&.cs\&.
.SS "float Leap\&.Unity\&.ConnectionMonitor\&.fadeInTime = 1\&.0f"
The speed to fade the sprite alpha from 0 to 1\&. 
.PP
Definition at line 29 of file ConnectionMonitor\&.cs\&.
.SS "float Leap\&.Unity\&.ConnectionMonitor\&.fadeOutTime = 1\&.0f"
The speed to fade the sprite alpha from 1 to 0\&. 
.PP
Definition at line 33 of file ConnectionMonitor\&.cs\&.
.SS "int Leap\&.Unity\&.ConnectionMonitor\&.monitorInterval = 2"
How often to check the connection\&. 
.PP
Definition at line 39 of file ConnectionMonitor\&.cs\&.
.SS "Color Leap\&.Unity\&.ConnectionMonitor\&.onColor = Color\&.white"
The fully on texture tint color\&. 
.PP
Definition at line 42 of file ConnectionMonitor\&.cs\&.
.SS "\fBLeapServiceProvider\fP Leap\&.Unity\&.ConnectionMonitor\&.provider"
The \fBLeapServiceProvider\fP in the scene\&. 
.PP
Definition at line 25 of file ConnectionMonitor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
