.TH "Leap.Unity.ProgressBar" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.ProgressBar \- This class allows you to easily give feedback of an action as it completes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgressBar\fP (\fBIProgressView\fP view)"
.br
.RI "Constructs a new progress bar given a progress view object that will display the progress information for this progress bar\&. "
.ti -1c
.RI "void \fBBegin\fP (int sections, string title, string info, Action action)"
.br
.RI "Begins a new chunk\&. If this call is made from within a chunk it will generate a sub-chunk that represents a single step in the parent chunk\&. "
.ti -1c
.RI "void \fBStep\fP (string infoString='')"
.br
.RI "Steps through one section of the current chunk\&. You can provide an optional info string that will be concatenated to the current info string before progress is displayed\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class allows you to easily give feedback of an action as it completes\&. 

The progress bar is represented as a single 'Chunk' that is made of a certain number of sections\&. The progress bar is hierarchical, and so each section can itself be another chunk\&. 
.PP
Definition at line 67 of file ProgressBar\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.ProgressBar\&.ProgressBar (\fBIProgressView\fP view)"

.PP
Constructs a new progress bar given a progress view object that will display the progress information for this progress bar\&. 
.PP
Definition at line 93 of file ProgressBar\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.ProgressBar\&.Begin (int sections, string title, string info, Action action)"

.PP
Begins a new chunk\&. If this call is made from within a chunk it will generate a sub-chunk that represents a single step in the parent chunk\&. You must specify the number of sections this chunk contains\&. All title and info strings will be concatenated together when the progress bar is displayed\&.
.PP
You must specify a delegate that represents the action performed by this chunk\&. This delegate is allowed to call both Begin and StepProgress to progress through its work\&. 
.PP
Definition at line 110 of file ProgressBar\&.cs\&.
.SS "void Leap\&.Unity\&.ProgressBar\&.Step (string infoString = \fC''\fP)"

.PP
Steps through one section of the current chunk\&. You can provide an optional info string that will be concatenated to the current info string before progress is displayed\&. 
.PP
Definition at line 148 of file ProgressBar\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
