.TH "LeapInternal.LEAP_DIGIT" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_DIGIT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Int32 \fBfinger_id\fP"
.br
.ti -1c
.RI "\fBLEAP_BONE\fP \fBmetacarpal\fP"
.br
.ti -1c
.RI "\fBLEAP_BONE\fP \fBproximal\fP"
.br
.ti -1c
.RI "\fBLEAP_BONE\fP \fBintermediate\fP"
.br
.ti -1c
.RI "\fBLEAP_BONE\fP \fBdistal\fP"
.br
.ti -1c
.RI "Int32 \fBis_extended\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 672 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLEAP_BONE\fP LeapInternal\&.LEAP_DIGIT\&.distal"

.PP
Definition at line 677 of file LeapC\&.cs\&.
.SS "Int32 LeapInternal\&.LEAP_DIGIT\&.finger_id"

.PP
Definition at line 673 of file LeapC\&.cs\&.
.SS "\fBLEAP_BONE\fP LeapInternal\&.LEAP_DIGIT\&.intermediate"

.PP
Definition at line 676 of file LeapC\&.cs\&.
.SS "Int32 LeapInternal\&.LEAP_DIGIT\&.is_extended"

.PP
Definition at line 678 of file LeapC\&.cs\&.
.SS "\fBLEAP_BONE\fP LeapInternal\&.LEAP_DIGIT\&.metacarpal"

.PP
Definition at line 674 of file LeapC\&.cs\&.
.SS "\fBLEAP_BONE\fP LeapInternal\&.LEAP_DIGIT\&.proximal"

.PP
Definition at line 675 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
