.TH "Leap.LeapCSharp.Tests.TestMarshaledStruct" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.LeapCSharp.Tests.TestMarshaledStruct
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestMarshaledStruct\fP (int t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file StructMarshalTests\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.LeapCSharp\&.Tests\&.TestMarshaledStruct\&.TestMarshaledStruct (int t)"

.PP
Definition at line 20 of file StructMarshalTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int Leap\&.LeapCSharp\&.Tests\&.TestMarshaledStruct\&.id"

.PP
Definition at line 19 of file StructMarshalTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
