.TH "Leap.Unity.Query" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Query
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBQuery\fP"
.br
.RI "A \fBQuery\fP object is a type of immutable ordered collection of elements that can be used to perform useful queries\&. These queries are very similar to LINQ style queries, providing useful methods such as Where, Select, Concat, etc\&.\&.\&.\&. "
.ti -1c
.RI "class \fBQueryCollapseExtensions\fP"
.br
.ti -1c
.RI "class \fBQueryConversionExtensions\fP"
.br
.ti -1c
.RI "class \fBQueryOperatorExtensions\fP"
.br
.RI "A collection of extension methods that operate on a \fBQuery\fP structure\&. All of these methods destroy the original query and return a new \fBQuery\fP based on the original\&. "
.ti -1c
.RI "class \fBValues\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
