.TH "Leap.BeginProfilingForThreadArgs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.BeginProfilingForThreadArgs
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBeginProfilingForThreadArgs\fP (string \fBthreadName\fP, params string[] \fBblockNames\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBthreadName\fP"
.br
.ti -1c
.RI "string [] \fBblockNames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 259 of file Events\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.BeginProfilingForThreadArgs\&.BeginProfilingForThreadArgs (string threadName, params string [] blockNames)"

.PP
Definition at line 263 of file Events\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string [] Leap\&.BeginProfilingForThreadArgs\&.blockNames"

.PP
Definition at line 261 of file Events\&.cs\&.
.SS "string Leap\&.BeginProfilingForThreadArgs\&.threadName"

.PP
Definition at line 260 of file Events\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
