.TH "Leap.Unity.Interaction.Internal.HeuristicGrabClassifier" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Interaction.Internal.HeuristicGrabClassifier
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHeuristicGrabClassifier\fP (\fBInteractionHand\fP intHand, float fingerStickiness=0F, float thumbStickiness=0\&.04F, float maxCurl=0\&.65F, float minCurl=\-0\&.1F, float fingerRadius=0\&.012F, float thumbRadius=0\&.017F, float grabCooldown=0\&.2F, float maxCurlVel=0\&.0F, float grabbedMaxCurlVel=\-0\&.025F, float maxGrabDistance=0\&.05F, int layerMask=0, QueryTriggerInteraction queryTriggers=QueryTriggerInteraction\&.UseGlobal)"
.br
.ti -1c
.RI "void \fBFixedUpdateClassifierHandState\fP ()"
.br
.ti -1c
.RI "bool \fBFixedUpdateClassifierGrasp\fP (out \fBIInteractionBehaviour\fP graspedObject)"
.br
.ti -1c
.RI "bool \fBFixedUpdateClassifierRelease\fP (out \fBIInteractionBehaviour\fP releasedObject)"
.br
.ti -1c
.RI "void \fBUnregisterInteractionBehaviour\fP (\fBIInteractionBehaviour\fP behaviour)"
.br
.ti -1c
.RI "void \fBNotifyGraspForciblyReleased\fP (\fBIInteractionBehaviour\fP behaviour)"
.br
.ti -1c
.RI "void \fBGetGraspingFingertipPositions\fP (\fBIInteractionBehaviour\fP behaviour, Vector3[] fingertipPositionsBuffer, out int numGraspingFingertips)"
.br
.ti -1c
.RI "bool \fBTryGrasp\fP (\fBIInteractionBehaviour\fP intObj, \fBHand\fP hand)"
.br
.ti -1c
.RI "void \fBSwapClassifierState\fP (\fBIInteractionBehaviour\fP original, \fBIInteractionBehaviour\fP replacement)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInteractionHand\fP \fBinteractionHand\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBFillClassifier\fP (\fBIInteractionBehaviour\fP behaviour, \fBHand\fP hand, ref GrabClassifierHeuristics\&.GrabClassifier classifier)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file HeuristicGrabClassifier\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Interaction\&.Internal\&.HeuristicGrabClassifier\&.HeuristicGrabClassifier (\fBInteractionHand\fP intHand, float fingerStickiness = \fC0F\fP, float thumbStickiness = \fC0\&.04F\fP, float maxCurl = \fC0\&.65F\fP, float minCurl = \fC\-0\&.1F\fP, float fingerRadius = \fC0\&.012F\fP, float thumbRadius = \fC0\&.017F\fP, float grabCooldown = \fC0\&.2F\fP, float maxCurlVel = \fC0\&.0F\fP, float grabbedMaxCurlVel = \fC\-0\&.025F\fP, float maxGrabDistance = \fC0\&.05F\fP, int layerMask = \fC0\fP, QueryTriggerInteraction queryTriggers = \fCQueryTriggerInteraction\&.UseGlobal\fP)"

.PP
Definition at line 33 of file HeuristicGrabClassifier\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Interaction\&.Internal\&.HeuristicGrabClassifier\&.FillClassifier (\fBIInteractionBehaviour\fP behaviour, \fBHand\fP hand, ref GrabClassifierHeuristics\&.GrabClassifier classifier)\fC [protected]\fP"

.PP
Definition at line 232 of file HeuristicGrabClassifier\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.Internal\&.HeuristicGrabClassifier\&.FixedUpdateClassifierGrasp (out \fBIInteractionBehaviour\fP graspedObject)"

.PP
Definition at line 90 of file HeuristicGrabClassifier\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.Internal\&.HeuristicGrabClassifier\&.FixedUpdateClassifierHandState ()"

.PP
Definition at line 64 of file HeuristicGrabClassifier\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.Internal\&.HeuristicGrabClassifier\&.FixedUpdateClassifierRelease (out \fBIInteractionBehaviour\fP releasedObject)"

.PP
Definition at line 110 of file HeuristicGrabClassifier\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.Internal\&.HeuristicGrabClassifier\&.GetGraspingFingertipPositions (\fBIInteractionBehaviour\fP behaviour, Vector3 [] fingertipPositionsBuffer, out int numGraspingFingertips)"

.PP
Definition at line 188 of file HeuristicGrabClassifier\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.Internal\&.HeuristicGrabClassifier\&.NotifyGraspForciblyReleased (\fBIInteractionBehaviour\fP behaviour)"

.PP
Definition at line 176 of file HeuristicGrabClassifier\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.Internal\&.HeuristicGrabClassifier\&.SwapClassifierState (\fBIInteractionBehaviour\fP original, \fBIInteractionBehaviour\fP replacement)"

.PP
Definition at line 211 of file HeuristicGrabClassifier\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.Internal\&.HeuristicGrabClassifier\&.TryGrasp (\fBIInteractionBehaviour\fP intObj, \fBHand\fP hand)"

.PP
Definition at line 204 of file HeuristicGrabClassifier\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.Internal\&.HeuristicGrabClassifier\&.UnregisterInteractionBehaviour (\fBIInteractionBehaviour\fP behaviour)"

.PP
Definition at line 172 of file HeuristicGrabClassifier\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBInteractionHand\fP Leap\&.Unity\&.Interaction\&.Internal\&.HeuristicGrabClassifier\&.interactionHand"

.PP
Definition at line 23 of file HeuristicGrabClassifier\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
