.TH "LeapInternal.LEAP_QUATERNION" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_QUATERNION
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLeap\&.LeapQuaternion\fP \fBToLeapQuaternion\fP ()"
.br
.ti -1c
.RI "\fBLEAP_QUATERNION\fP (\fBLeap\&.LeapQuaternion\fP q)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 638 of file LeapC\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LeapInternal\&.LEAP_QUATERNION\&.LEAP_QUATERNION (\fBLeap\&.LeapQuaternion\fP q)"

.PP
Definition at line 648 of file LeapC\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBLeap\&.LeapQuaternion\fP LeapInternal\&.LEAP_QUATERNION\&.ToLeapQuaternion ()"

.PP
Definition at line 644 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float LeapInternal\&.LEAP_QUATERNION\&.w"

.PP
Definition at line 642 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_QUATERNION\&.x"

.PP
Definition at line 639 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_QUATERNION\&.y"

.PP
Definition at line 640 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_QUATERNION\&.z"

.PP
Definition at line 641 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
