.TH "LeapInternal.LEAP_CONNECTION_EVENT" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_CONNECTION_EVENT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBeLeapServiceDisposition\fP \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 476 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBeLeapServiceDisposition\fP LeapInternal\&.LEAP_CONNECTION_EVENT\&.flags"

.PP
Definition at line 477 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
