.TH "LeapInternal.LEAP_DEVICE_EVENT" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_DEVICE_EVENT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UInt32 \fBflags\fP"
.br
.ti -1c
.RI "\fBLEAP_DEVICE_REF\fP \fBdevice\fP"
.br
.ti -1c
.RI "\fBeLeapDeviceStatus\fP \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 501 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLEAP_DEVICE_REF\fP LeapInternal\&.LEAP_DEVICE_EVENT\&.device"

.PP
Definition at line 503 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_DEVICE_EVENT\&.flags"

.PP
Definition at line 502 of file LeapC\&.cs\&.
.SS "\fBeLeapDeviceStatus\fP LeapInternal\&.LEAP_DEVICE_EVENT\&.status"

.PP
Definition at line 504 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
