.TH "Leap.ConfigChangeEventArgs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.ConfigChangeEventArgs \- Dispatched when a configuration change is completed\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.LeapEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigChangeEventArgs\fP (string config_key, bool succeeded, uint requestId)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBConfigKey\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBSucceeded\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "uint \fBRequestId\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dispatched when a configuration change is completed\&. 

Provides the configuration key, whether the change was successful, and the id of the original change request\&. 
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 129 of file Events\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.ConfigChangeEventArgs\&.ConfigChangeEventArgs (string config_key, bool succeeded, uint requestId)"

.PP
Definition at line 130 of file Events\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Leap\&.ConfigChangeEventArgs\&.ConfigKey\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 135 of file Events\&.cs\&.
.SS "uint Leap\&.ConfigChangeEventArgs\&.RequestId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 137 of file Events\&.cs\&.
.SS "bool Leap\&.ConfigChangeEventArgs\&.Succeeded\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 136 of file Events\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
