.TH "Leap.Unity.LeapImageRetrieverEditor" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.LeapImageRetrieverEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.CustomEditorBase< LeapImageRetriever >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file LeapImageRetrieverEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Leap\&.Unity\&.LeapImageRetrieverEditor\&.OnEnable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.CustomEditorBase< LeapImageRetriever >\fP\&.
.PP
Definition at line 20 of file LeapImageRetrieverEditor\&.cs\&.
.SS "override void Leap\&.Unity\&.LeapImageRetrieverEditor\&.OnInspectorGUI ()"

.PP
Definition at line 27 of file LeapImageRetrieverEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
