.TH "Leap.Unity.Tests.MultiTypedReferenceTests.BaseClass" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Tests.MultiTypedReferenceTests.BaseClass
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLeap\&.Unity\&.Tests\&.MultiTypedReferenceTests\&.A\fP, \fBLeap\&.Unity\&.Tests\&.MultiTypedReferenceTests\&.B\fP, \fBLeap\&.Unity\&.Tests\&.MultiTypedReferenceTests\&.C\fP, \fBLeap\&.Unity\&.Tests\&.MultiTypedReferenceTests\&.D\fP, and \fBLeap\&.Unity\&.Tests\&.MultiTypedReferenceTests\&.InvalidClass\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 16 of file MultiTypedReferenceTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
