.TH "Leap.Unity.Interaction.IInteractionBehaviour" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Interaction.IInteractionBehaviour \- \fBIInteractionBehaviour\fP is the interface that defines all \fBInteraction\fP objects, specifying the minimum set of functionality required to make objects interactable\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFixedUpdateObject\fP ()"
.br
.ti -1c
.RI "float \fBGetHoverDistance\fP (Vector3 worldPosition)"
.br
.ti -1c
.RI "void \fBBeginHover\fP (List< \fBInteractionController\fP > beganHovering)"
.br
.ti -1c
.RI "void \fBEndHover\fP (List< \fBInteractionController\fP > endedHovering)"
.br
.ti -1c
.RI "void \fBStayHovered\fP (List< \fBInteractionController\fP > currentlyHovering)"
.br
.ti -1c
.RI "void \fBBeginPrimaryHover\fP (List< \fBInteractionController\fP > beganPrimaryHovering)"
.br
.ti -1c
.RI "void \fBEndPrimaryHover\fP (List< \fBInteractionController\fP > endedPrimaryHovering)"
.br
.ti -1c
.RI "void \fBStayPrimaryHovered\fP (List< \fBInteractionController\fP > currentlyPrimaryHovering)"
.br
.ti -1c
.RI "void \fBBeginContact\fP (List< \fBInteractionController\fP > beganContact)"
.br
.ti -1c
.RI "void \fBEndContact\fP (List< \fBInteractionController\fP > endedContact)"
.br
.ti -1c
.RI "void \fBStayContacted\fP (List< \fBInteractionController\fP > currentlyContacting)"
.br
.ti -1c
.RI "void \fBBeginGrasp\fP (List< \fBInteractionController\fP > beganGrasping)"
.br
.ti -1c
.RI "void \fBEndGrasp\fP (List< \fBInteractionController\fP > endedGrasping)"
.br
.ti -1c
.RI "void \fBStayGrasped\fP (List< \fBInteractionController\fP > currentlyGrasping)"
.br
.ti -1c
.RI "void \fBBeginSuspension\fP (\fBInteractionController\fP beganSuspending)"
.br
.ti -1c
.RI "void \fBEndSuspension\fP (\fBInteractionController\fP endedSuspending)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBname\fP\fC [get]\fP"
.br
.ti -1c
.RI "GameObject \fBgameObject\fP\fC [get]\fP"
.br
.ti -1c
.RI "Transform \fBtransform\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBInteractionManager\fP \fBmanager\fP\fC [get]\fP"
.br
.ti -1c
.RI "Rigidbody \fBrigidbody\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBISpaceComponent\fP \fBspace\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIgnoreHoverMode\fP \fBignoreHoverMode\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBignorePrimaryHover\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBignoreContact\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBignoreGrasping\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBallowMultiGrasp\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBSingleLayer\fP \fBinteractionLayer\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBSingleLayer\fP \fBnoContactLayer\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBisGrasped\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBisSuspended\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBIInteractionBehaviour\fP is the interface that defines all \fBInteraction\fP objects, specifying the minimum set of functionality required to make objects interactable\&. 


.PP
Definition at line 23 of file IInteractionBehaviour\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.BeginContact (List< \fBInteractionController\fP > beganContact)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.BeginGrasp (List< \fBInteractionController\fP > beganGrasping)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.BeginHover (List< \fBInteractionController\fP > beganHovering)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.BeginPrimaryHover (List< \fBInteractionController\fP > beganPrimaryHovering)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.BeginSuspension (\fBInteractionController\fP beganSuspending)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.EndContact (List< \fBInteractionController\fP > endedContact)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.EndGrasp (List< \fBInteractionController\fP > endedGrasping)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.EndHover (List< \fBInteractionController\fP > endedHovering)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.EndPrimaryHover (List< \fBInteractionController\fP > endedPrimaryHovering)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.EndSuspension (\fBInteractionController\fP endedSuspending)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.FixedUpdateObject ()"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "float Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.GetHoverDistance (Vector3 worldPosition)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.StayContacted (List< \fBInteractionController\fP > currentlyContacting)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.StayGrasped (List< \fBInteractionController\fP > currentlyGrasping)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.StayHovered (List< \fBInteractionController\fP > currentlyHovering)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SS "void Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.StayPrimaryHovered (List< \fBInteractionController\fP > currentlyPrimaryHovering)"

.PP
Implemented in \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.allowMultiGrasp\fC [get]\fP"

.PP
Definition at line 43 of file IInteractionBehaviour\&.cs\&.
.SS "GameObject Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.gameObject\fC [get]\fP"

.PP
Definition at line 27 of file IInteractionBehaviour\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.ignoreContact\fC [get]\fP"

.PP
Definition at line 39 of file IInteractionBehaviour\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.ignoreGrasping\fC [get]\fP"

.PP
Definition at line 40 of file IInteractionBehaviour\&.cs\&.
.SS "\fBIgnoreHoverMode\fP Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.ignoreHoverMode\fC [get]\fP"

.PP
Definition at line 37 of file IInteractionBehaviour\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.ignorePrimaryHover\fC [get]\fP"

.PP
Definition at line 38 of file IInteractionBehaviour\&.cs\&.
.SS "\fBSingleLayer\fP Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.interactionLayer\fC [get]\fP"

.PP
Definition at line 46 of file IInteractionBehaviour\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.isGrasped\fC [get]\fP"

.PP
Definition at line 77 of file IInteractionBehaviour\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.isSuspended\fC [get]\fP"

.PP
Definition at line 83 of file IInteractionBehaviour\&.cs\&.
.SS "\fBInteractionManager\fP Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.manager\fC [get]\fP"

.PP
Definition at line 31 of file IInteractionBehaviour\&.cs\&.
.SS "string Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.name\fC [get]\fP"

.PP
Definition at line 26 of file IInteractionBehaviour\&.cs\&.
.SS "\fBSingleLayer\fP Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.noContactLayer\fC [get]\fP"

.PP
Definition at line 47 of file IInteractionBehaviour\&.cs\&.
.SS "Rigidbody Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.rigidbody\fC [get]\fP"

.PP
Definition at line 32 of file IInteractionBehaviour\&.cs\&.
.SS "\fBISpaceComponent\fP Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.space\fC [get]\fP"

.PP
Definition at line 33 of file IInteractionBehaviour\&.cs\&.
.SS "Transform Leap\&.Unity\&.Interaction\&.IInteractionBehaviour\&.transform\fC [get]\fP"

.PP
Definition at line 28 of file IInteractionBehaviour\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
