.TH "Leap.Unity.Tests.DequeTests" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Tests.DequeTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.ti -1c
.RI "void \fBTeardown\fP ()"
.br
.ti -1c
.RI "void \fBInvalidCapacity\fP ([Values(int\&.MinValue, \-1, 0)] int minCapacity)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBAccessEmptyBack\fP ()"
.br
.ti -1c
.RI "void \fBAccessEmptyFront\fP ()"
.br
.ti -1c
.RI "void \fBInvalidIndex\fP ([Values(int\&.MinValue, \-1, 5, int\&.MaxValue)] int index)"
.br
.ti -1c
.RI "void \fBPushFront\fP ()"
.br
.ti -1c
.RI "void \fBPushBack\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file DequeTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Tests\&.DequeTests\&.AccessEmptyBack ()"

.PP
Definition at line 47 of file DequeTests\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.DequeTests\&.AccessEmptyFront ()"

.PP
Definition at line 56 of file DequeTests\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.DequeTests\&.Clear ()"

.PP
Definition at line 38 of file DequeTests\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.DequeTests\&.InvalidCapacity ([Values(int\&.MinValue, \-1, 0)] int minCapacity)"

.PP
Definition at line 31 of file DequeTests\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.DequeTests\&.InvalidIndex ([Values(int\&.MinValue, \-1, 5, int\&.MaxValue)] int index)"

.PP
Definition at line 64 of file DequeTests\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.DequeTests\&.PushBack ()"

.PP
Definition at line 95 of file DequeTests\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.DequeTests\&.PushFront ()"

.PP
Definition at line 76 of file DequeTests\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.DequeTests\&.Setup ()"

.PP
Definition at line 20 of file DequeTests\&.cs\&.
.SS "void Leap\&.Unity\&.Tests\&.DequeTests\&.Teardown ()"

.PP
Definition at line 25 of file DequeTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
