.TH "Leap.FailedDeviceList" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.FailedDeviceList \- The list of \fBFailedDevice\fP objects contains an entry for every failed \fBLeap\fP Motion hardware device connected to the client computer\&. \fBFailedDevice\fP objects report the device pnpID string and reason for failure\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits List< FailedDevice >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFailedDeviceList\fP ()"
.br
.RI "Constructs an empty list\&. "
.ti -1c
.RI "\fBFailedDeviceList\fP \fBAppend\fP (\fBFailedDeviceList\fP other)"
.br
.RI "Appends the contents of another \fBFailedDeviceList\fP to this one\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsEmpty\fP\fC [get]\fP"
.br
.RI "Reports whether the list is empty\&. "
.in -1c
.SH "Detailed Description"
.PP 
The list of \fBFailedDevice\fP objects contains an entry for every failed \fBLeap\fP Motion hardware device connected to the client computer\&. \fBFailedDevice\fP objects report the device pnpID string and reason for failure\&. 

Get the list of \fBFailedDevice\fP objects from \fBController\&.FailedDevices()\fP\&.
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 22 of file FailedDeviceList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.FailedDeviceList\&.FailedDeviceList ()"

.PP
Constructs an empty list\&. 
.PP
Definition at line 27 of file FailedDeviceList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBFailedDeviceList\fP Leap\&.FailedDeviceList\&.Append (\fBFailedDeviceList\fP other)"

.PP
Appends the contents of another \fBFailedDeviceList\fP to this one\&. 
.PP
Definition at line 32 of file FailedDeviceList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Leap\&.FailedDeviceList\&.IsEmpty\fC [get]\fP"

.PP
Reports whether the list is empty\&. 
.PP
Definition at line 40 of file FailedDeviceList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
