.TH "Leap.PolicyEventArgs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.PolicyEventArgs \- Dispatched when a policy change is complete\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.LeapEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolicyEventArgs\fP (UInt64 \fBcurrentPolicies\fP, UInt64 \fBoldPolicies\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "UInt64 \fBcurrentPolicies\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "UInt64 \fBoldPolicies\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dispatched when a policy change is complete\&. 

Provides the current and previous policies as arguments\&.
.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 98 of file Events\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.PolicyEventArgs\&.PolicyEventArgs (UInt64 currentPolicies, UInt64 oldPolicies)"

.PP
Definition at line 99 of file Events\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "UInt64 Leap\&.PolicyEventArgs\&.currentPolicies\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 104 of file Events\&.cs\&.
.SS "UInt64 Leap\&.PolicyEventArgs\&.oldPolicies\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 105 of file Events\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
