.TH "Leap.Unity.PinchDetector" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.PinchDetector \- A basic utility class to aid in creating pinch based actions\&. Once linked with a \fBHandModelBase\fP, it can be used to detect pinch gestures that the hand makes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.AbstractHoldDetector\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBActivateDistance\fP = \&.03f"
.br
.ti -1c
.RI "float \fBDeactivateDistance\fP = \&.04f"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnValidate\fP ()"
.br
.ti -1c
.RI "override void \fBensureUpToDate\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const float \fBMM_TO_M\fP = 0\&.001f"
.br
.ti -1c
.RI "bool \fB_isPinching\fP = false"
.br
.ti -1c
.RI "float \fB_lastPinchTime\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fB_lastUnpinchTime\fP = 0\&.0f"
.br
.ti -1c
.RI "Vector3 \fB_pinchPos\fP"
.br
.ti -1c
.RI "Quaternion \fB_pinchRotation\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsPinching\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBDidStartPinch\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBDidEndPinch\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A basic utility class to aid in creating pinch based actions\&. Once linked with a \fBHandModelBase\fP, it can be used to detect pinch gestures that the hand makes\&. 


.PP
Definition at line 20 of file PinchDetector\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Leap\&.Unity\&.PinchDetector\&.ensureUpToDate ()\fC [protected]\fP, \fC [virtual]\fP"
Implementations must implement this method\&. 
.PP
Implements \fBLeap\&.Unity\&.AbstractHoldDetector\fP\&.
.PP
Definition at line 63 of file PinchDetector\&.cs\&.
.SS "virtual void Leap\&.Unity\&.PinchDetector\&.OnValidate ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 47 of file PinchDetector\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Leap\&.Unity\&.PinchDetector\&._isPinching = false\fC [protected]\fP"

.PP
Definition at line 39 of file PinchDetector\&.cs\&.
.SS "float Leap\&.Unity\&.PinchDetector\&._lastPinchTime = 0\&.0f\fC [protected]\fP"

.PP
Definition at line 41 of file PinchDetector\&.cs\&.
.SS "float Leap\&.Unity\&.PinchDetector\&._lastUnpinchTime = 0\&.0f\fC [protected]\fP"

.PP
Definition at line 42 of file PinchDetector\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.PinchDetector\&._pinchPos\fC [protected]\fP"

.PP
Definition at line 44 of file PinchDetector\&.cs\&.
.SS "Quaternion Leap\&.Unity\&.PinchDetector\&._pinchRotation\fC [protected]\fP"

.PP
Definition at line 45 of file PinchDetector\&.cs\&.
.SS "float Leap\&.Unity\&.PinchDetector\&.ActivateDistance = \&.03f"

.PP
Definition at line 28 of file PinchDetector\&.cs\&.
.SS "float Leap\&.Unity\&.PinchDetector\&.DeactivateDistance = \&.04f"

.PP
Definition at line 33 of file PinchDetector\&.cs\&.
.SS "const float Leap\&.Unity\&.PinchDetector\&.MM_TO_M = 0\&.001f\fC [protected]\fP"

.PP
Definition at line 21 of file PinchDetector\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Leap\&.Unity\&.PinchDetector\&.DidEndPinch\fC [get]\fP"

.PP
Definition at line 37 of file PinchDetector\&.cs\&.
.SS "bool Leap\&.Unity\&.PinchDetector\&.DidStartPinch\fC [get]\fP"

.PP
Definition at line 36 of file PinchDetector\&.cs\&.
.SS "bool Leap\&.Unity\&.PinchDetector\&.IsPinching\fC [get]\fP"

.PP
Definition at line 35 of file PinchDetector\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
