.TH "LeapInternal.CircularObjectBuffer< T >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.CircularObjectBuffer< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCircularObjectBuffer\fP (int capacity)"
.br
.ti -1c
.RI "virtual void \fBPut\fP (ref T item)"
.br
.ti -1c
.RI "void \fBGet\fP (out T t, int index=0)"
.br
.ti -1c
.RI "void \fBResize\fP (int newCapacity)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCount\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCapacity\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsEmpty\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Limited capacity, circular LIFO buffer that wraps around when full\&. Supports indexing to get older items\&. Array-backed\&.
.IP "\(bu" 2
Unlike many collections, objects are never removed, just overwritten when the buffer cycles back to their array location\&.
.PP
.PP
Object types used must have default parameterless constructor\&. It should be obvious that such default objects are invalid\&. I\&.e\&. for \fBLeap\fP API objects, the IsValid property should be false\&. 
.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fInew()\fP
.PP
Definition at line 23 of file CircularObjectBuffer\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLeapInternal\&.CircularObjectBuffer\fP< T >\&.\fBCircularObjectBuffer\fP (int capacity)"

.PP
Definition at line 31 of file CircularObjectBuffer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBLeapInternal\&.CircularObjectBuffer\fP< T >\&.Get (out T t, int index = \fC0\fP)"
Get the item indexed backward from the head of the list 
.PP
Definition at line 59 of file CircularObjectBuffer\&.cs\&.
.SS "virtual void \fBLeapInternal\&.CircularObjectBuffer\fP< T >\&.Put (ref T item)\fC [virtual]\fP"
Put an item at the head of the list\&. Once full, this will overwrite the oldest item\&. 
.PP
Definition at line 40 of file CircularObjectBuffer\&.cs\&.
.SS "void \fBLeapInternal\&.CircularObjectBuffer\fP< T >\&.Resize (int newCapacity)"
Increase 
.PP
Definition at line 75 of file CircularObjectBuffer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int \fBLeapInternal\&.CircularObjectBuffer\fP< T >\&.Capacity\fC [get]\fP"

.PP
Definition at line 28 of file CircularObjectBuffer\&.cs\&.
.SS "int \fBLeapInternal\&.CircularObjectBuffer\fP< T >\&.Count\fC [get]\fP"

.PP
Definition at line 27 of file CircularObjectBuffer\&.cs\&.
.SS "bool \fBLeapInternal\&.CircularObjectBuffer\fP< T >\&.IsEmpty\fC [get]\fP"

.PP
Definition at line 29 of file CircularObjectBuffer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
