.TH "Leap.Unity.Interaction.KabschGraspedPose.PosePointCollection" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Interaction.KabschGraspedPose.PosePointCollection
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetWorldPosition\fP (int index, Vector3 worldPosition)"
.br
.ti -1c
.RI "Vector3 \fBGetLocalPosition\fP (int index)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPosePointCollection\fP \fBCreate\fP (Vector3 position, Quaternion rotation)"
.br
.ti -1c
.RI "static void \fBReturn\fP (\fBPosePointCollection\fP posePointCollection)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 141 of file KabschGraspedPose\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBPosePointCollection\fP Leap\&.Unity\&.Interaction\&.KabschGraspedPose\&.PosePointCollection\&.Create (Vector3 position, Quaternion rotation)\fC [static]\fP"

.PP
Definition at line 149 of file KabschGraspedPose\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.Interaction\&.KabschGraspedPose\&.PosePointCollection\&.GetLocalPosition (int index)"

.PP
Definition at line 189 of file KabschGraspedPose\&.cs\&.
.SS "static void Leap\&.Unity\&.Interaction\&.KabschGraspedPose\&.PosePointCollection\&.Return (\fBPosePointCollection\fP posePointCollection)\fC [static]\fP"

.PP
Definition at line 162 of file KabschGraspedPose\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.KabschGraspedPose\&.PosePointCollection\&.SetWorldPosition (int index, Vector3 worldPosition)"

.PP
Definition at line 174 of file KabschGraspedPose\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
