.TH "Leap.Unity.Examples.RenderWireSphere" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples.RenderWireSphere
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and \fBLeap\&.Unity\&.RuntimeGizmos\&.IRuntimeGizmoComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnDrawRuntimeGizmos\fP (\fBRuntimeGizmoDrawer\fP drawer)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBradius\fP = 0\&.30F"
.br
.ti -1c
.RI "Color \fBcolor\fP = Color\&.red"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file RenderWireSphere\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Examples\&.RenderWireSphere\&.OnDrawRuntimeGizmos (\fBRuntimeGizmoDrawer\fP drawer)"

.PP
Implements \fBLeap\&.Unity\&.RuntimeGizmos\&.IRuntimeGizmoComponent\fP\&.
.PP
Definition at line 23 of file RenderWireSphere\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Color Leap\&.Unity\&.Examples\&.RenderWireSphere\&.color = Color\&.red"

.PP
Definition at line 21 of file RenderWireSphere\&.cs\&.
.SS "float Leap\&.Unity\&.Examples\&.RenderWireSphere\&.radius = 0\&.30F"

.PP
Definition at line 20 of file RenderWireSphere\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
