.TH "O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/LeapServiceProvider.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/LeapServiceProvider.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLeap\&.Unity\&.LeapServiceProvider\fP"
.br
.RI "The \fBLeapServiceProvider\fP provides tracked \fBLeap\fP \fBHand\fP data and images from the device via the \fBLeap\fP service running on the client machine\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLeap\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
