.TH "Leap.Unity.SerializableType" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.SerializableType
.SH SYNOPSIS
.br
.PP
.PP
Inherits ISerializationCallbackReceiver\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnAfterDeserialize\fP ()"
.br
.ti -1c
.RI "void \fBOnBeforeSerialize\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator Type\fP (\fBSerializableType\fP serializableType)"
.br
.ti -1c
.RI "static implicit \fBoperator SerializableType\fP (Type type)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file SerializableType\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.SerializableType\&.OnAfterDeserialize ()"

.PP
Definition at line 35 of file SerializableType\&.cs\&.
.SS "void Leap\&.Unity\&.SerializableType\&.OnBeforeSerialize ()"

.PP
Definition at line 48 of file SerializableType\&.cs\&.
.SS "static implicit Leap\&.Unity\&.SerializableType\&.operator \fBSerializableType\fP (Type type)\fC [static]\fP"

.PP
Definition at line 58 of file SerializableType\&.cs\&.
.SS "static implicit Leap\&.Unity\&.SerializableType\&.operator Type (\fBSerializableType\fP serializableType)\fC [static]\fP"

.PP
Definition at line 54 of file SerializableType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
