.TH "Leap.Unity.AssetFolder" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.AssetFolder \- A convenient serializable representation of an asset folder\&. Only useful for editor scripts since asset folder structure is not preserved for builds\&. The asset folder struct itself is still available at runtime for serialization ease, but the Path property will not be available\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLeap\&.Unity\&.StreamingFolder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssetFolder\fP ()"
.br
.ti -1c
.RI "\fBAssetFolder\fP (string path)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBUnityObject\fP \fB_assetFolder\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBPath\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the folder path\&. This path will always be a path relative to the asset folder, and matches the format expected and returned by AssetDatabase\&. This operation cannot be performed from inside of a build due to Assets no longer existing\&. "
.in -1c
.SH "Detailed Description"
.PP 
A convenient serializable representation of an asset folder\&. Only useful for editor scripts since asset folder structure is not preserved for builds\&. The asset folder struct itself is still available at runtime for serialization ease, but the Path property will not be available\&. 


.PP
Definition at line 27 of file AssetFolder\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.AssetFolder\&.AssetFolder ()"

.PP
Definition at line 32 of file AssetFolder\&.cs\&.
.SS "Leap\&.Unity\&.AssetFolder\&.AssetFolder (string path)"

.PP
Definition at line 34 of file AssetFolder\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBUnityObject\fP Leap\&.Unity\&.AssetFolder\&._assetFolder\fC [protected]\fP"

.PP
Definition at line 30 of file AssetFolder\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual string Leap\&.Unity\&.AssetFolder\&.Path\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the folder path\&. This path will always be a path relative to the asset folder, and matches the format expected and returned by AssetDatabase\&. This operation cannot be performed from inside of a build due to Assets no longer existing\&. 
.PP
Definition at line 44 of file AssetFolder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
