.TH "Leap.Unity.Interaction.InteractionButton" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Interaction.InteractionButton \- A physics-enabled button\&. Activated by physically pressing the button, with events for press and unpress\&. /summary>  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.PP
Inherited by \fBLeap\&.Unity\&.Interaction\&.InteractionSlider\fP, and \fBLeap\&.Unity\&.Interaction\&.InteractionToggle\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBStartingPositionMode\fP { \fBStartingPositionMode\&.Depressed\fP, \fBStartingPositionMode\&.Relaxed\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetMinHeight\fP (float minHeight)"
.br
.RI "Sets the minimum height (x component) of the minMaxHeight property\&. The minimum height can't be set larger than the maximum height with this method (it will be clamped if necessary)\&. "
.ti -1c
.RI "void \fBsetMinHeight\fP (float minHeight)"
.br
.ti -1c
.RI "void \fBSetMaxHeight\fP (float maxHeight)"
.br
.RI "Sets the maximum height (y component) of the minMaxHeight property\&. The maximum height can't be set smaller than the minimum height with this method (it will be clamped if necessary)\&. "
.ti -1c
.RI "void \fBsetMaxHeight\fP (float maxHeight)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStartingPositionMode\fP \fBstartingPositionMode\fP = \fBStartingPositionMode\&.Depressed\fP"
.br
.ti -1c
.RI "Vector2 \fBminMaxHeight\fP = new Vector2(0f, 0\&.02f)"
.br
.RI "The minimum and maximum heights the button can exist at\&. "
.ti -1c
.RI "float \fBrestingHeight\fP = 0\&.5f"
.br
.RI "The height that this button rests at; this value is a lerp in between the min and max height\&. "
.ti -1c
.RI "Action \fBOnPress\fP = () => { }"
.br
.ti -1c
.RI "Action \fBOnUnpress\fP = () => { }"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "override void \fBStart\fP ()"
.br
.ti -1c
.RI "virtual void \fBFixedUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.ti -1c
.RI "virtual Vector3 \fBconstrainDepressedLocalPosition\fP (Vector3 localPosition)"
.br
.RI "Clamps the input local-space position to the bounds allowed by this UI element, without clamping along the button depression axis\&. For buttons, this is locks the element in local-XY space, but not along the pressing axis (Z axis)\&. "
.ti -1c
.RI "virtual void \fBonGraspBegin\fP ()"
.br
.ti -1c
.RI "virtual void \fBonGraspEnd\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnCollisionEnter\fP (Collision collision)"
.br
.ti -1c
.RI "virtual void \fBOnCollisionStay\fP (Collision collision)"
.br
.ti -1c
.RI "virtual void \fBOnTriggerEnter\fP (Collider collider)"
.br
.ti -1c
.RI "virtual void \fBOnTriggerStay\fP (Collider collider)"
.br
.ti -1c
.RI "virtual void \fBOnDrawGizmosSelected\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fB_isPressed\fP = false"
.br
.ti -1c
.RI "bool \fB_pressedThisFrame\fP = false"
.br
.ti -1c
.RI "bool \fB_unpressedThisFrame\fP = false"
.br
.ti -1c
.RI "Vector3 \fBinitialLocalPosition\fP"
.br
.RI "The initial position of this element in local space, stored on \fBStart()\fP\&. "
.ti -1c
.RI "Vector3 \fBlocalPhysicsPosition\fP"
.br
.RI "The physical position of this element in local space; may diverge from the graphical position\&. "
.ti -1c
.RI "Vector3 \fBphysicsPosition\fP = Vector3\&.zero"
.br
.RI "The physical position of this element in world space; may diverge from the graphical position\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBcontrolEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBspringForce\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisPressed\fP\fC [get]\fP"
.br
.RI "Gets whether the button is currently held down\&. "
.ti -1c
.RI "bool \fBisDepressed\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBpressedThisFrame\fP\fC [get]\fP"
.br
.RI "Gets whether the button was pressed during this Update frame\&. "
.ti -1c
.RI "bool \fBdepressedThisFrame\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBunpressedThisFrame\fP\fC [get]\fP"
.br
.RI "Gets whether the button was unpressed this frame\&. "
.ti -1c
.RI "bool \fBunDepressedThisFrame\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBpressedAmount\fP\fC [get]\fP"
.br
.RI "Gets a normalized value between 0 and 1 based on how depressed the button currently is relative to its maximum depression\&. 0 represents a button fully at rest or pulled out beyond its resting position; 1 represents a fully-pressed button\&. "
.ti -1c
.RI "float \fBdepressedAmount\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual Vector3 \fBRelaxedLocalPosition\fP\fC [get]\fP"
.br
.RI "Returns the local position of this button when it is able to relax into its target position\&. "
.in -1c
.SH "Detailed Description"
.PP 
A physics-enabled button\&. Activated by physically pressing the button, with events for press and unpress\&. /summary> 
.PP
Definition at line 22 of file InteractionButton\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBLeap\&.Unity\&.Interaction\&.InteractionButton\&.StartingPositionMode\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDepressed \fP\fP
.TP
\fB\fIRelaxed \fP\fP
.PP
Definition at line 43 of file InteractionButton\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual Vector3 Leap\&.Unity\&.Interaction\&.InteractionButton\&.constrainDepressedLocalPosition (Vector3 localPosition)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Clamps the input local-space position to the bounds allowed by this UI element, without clamping along the button depression axis\&. For buttons, this is locks the element in local-XY space, but not along the pressing axis (Z axis)\&. 
.PP
Reimplemented in \fBLeap\&.Unity\&.Interaction\&.InteractionSlider\fP\&.
.PP
Definition at line 408 of file InteractionButton\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Interaction\&.InteractionButton\&.FixedUpdate ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 223 of file InteractionButton\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Interaction\&.InteractionButton\&.OnCollisionEnter (Collision collision)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 433 of file InteractionButton\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Interaction\&.InteractionButton\&.OnCollisionStay (Collision collision)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 434 of file InteractionButton\&.cs\&.
.SS "override void Leap\&.Unity\&.Interaction\&.InteractionButton\&.OnDisable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.PP
Reimplemented in \fBLeap\&.Unity\&.Interaction\&.InteractionSlider\fP, and \fBLeap\&.Unity\&.Interaction\&.InteractionToggle\fP\&.
.PP
Definition at line 179 of file InteractionButton\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Interaction\&.InteractionButton\&.OnDrawGizmosSelected ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBLeap\&.Unity\&.Interaction\&.InteractionSlider\fP\&.
.PP
Definition at line 454 of file InteractionButton\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Interaction\&.InteractionButton\&.onGraspBegin ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 416 of file InteractionButton\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Interaction\&.InteractionButton\&.onGraspEnd ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 421 of file InteractionButton\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Interaction\&.InteractionButton\&.OnTriggerEnter (Collider collider)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 437 of file InteractionButton\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Interaction\&.InteractionButton\&.OnTriggerStay (Collider collider)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 438 of file InteractionButton\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.InteractionButton\&.SetMaxHeight (float maxHeight)"

.PP
Sets the maximum height (y component) of the minMaxHeight property\&. The maximum height can't be set smaller than the minimum height with this method (it will be clamped if necessary)\&. 
.PP
Definition at line 492 of file InteractionButton\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.InteractionButton\&.setMaxHeight (float maxHeight)"

.PP
Definition at line 496 of file InteractionButton\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.InteractionButton\&.SetMinHeight (float minHeight)"

.PP
Sets the minimum height (x component) of the minMaxHeight property\&. The minimum height can't be set larger than the maximum height with this method (it will be clamped if necessary)\&. 
.PP
Definition at line 479 of file InteractionButton\&.cs\&.
.SS "void Leap\&.Unity\&.Interaction\&.InteractionButton\&.setMinHeight (float minHeight)"

.PP
Definition at line 483 of file InteractionButton\&.cs\&.
.SS "override void Leap\&.Unity\&.Interaction\&.InteractionButton\&.Start ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBLeap\&.Unity\&.Interaction\&.InteractionBehaviour\fP\&.
.PP
Reimplemented in \fBLeap\&.Unity\&.Interaction\&.InteractionSlider\fP, and \fBLeap\&.Unity\&.Interaction\&.InteractionToggle\fP\&.
.PP
Definition at line 192 of file InteractionButton\&.cs\&.
.SS "virtual void Leap\&.Unity\&.Interaction\&.InteractionButton\&.Update ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBLeap\&.Unity\&.Interaction\&.InteractionSlider\fP\&.
.PP
Definition at line 254 of file InteractionButton\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionButton\&._isPressed = false\fC [protected]\fP"

.PP
Definition at line 93 of file InteractionButton\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionButton\&._pressedThisFrame = false\fC [protected]\fP"

.PP
Definition at line 99 of file InteractionButton\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionButton\&._unpressedThisFrame = false\fC [protected]\fP"

.PP
Definition at line 107 of file InteractionButton\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.Interaction\&.InteractionButton\&.initialLocalPosition\fC [protected]\fP"

.PP
The initial position of this element in local space, stored on \fBStart()\fP\&. 
.PP
Definition at line 130 of file InteractionButton\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.Interaction\&.InteractionButton\&.localPhysicsPosition\fC [protected]\fP"

.PP
The physical position of this element in local space; may diverge from the graphical position\&. 
.PP
Definition at line 136 of file InteractionButton\&.cs\&.
.SS "Vector2 Leap\&.Unity\&.Interaction\&.InteractionButton\&.minMaxHeight = new Vector2(0f, 0\&.02f)"

.PP
The minimum and maximum heights the button can exist at\&. 
.PP
Definition at line 49 of file InteractionButton\&.cs\&.
.SS "Action Leap\&.Unity\&.Interaction\&.InteractionButton\&.OnPress = () => { }"

.PP
Definition at line 86 of file InteractionButton\&.cs\&.
.SS "Action Leap\&.Unity\&.Interaction\&.InteractionButton\&.OnUnpress = () => { }"

.PP
Definition at line 87 of file InteractionButton\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.Interaction\&.InteractionButton\&.physicsPosition = Vector3\&.zero\fC [protected]\fP"

.PP
The physical position of this element in world space; may diverge from the graphical position\&. 
.PP
Definition at line 142 of file InteractionButton\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionButton\&.restingHeight = 0\&.5f"

.PP
The height that this button rests at; this value is a lerp in between the min and max height\&. 
.PP
Definition at line 57 of file InteractionButton\&.cs\&.
.SS "\fBStartingPositionMode\fP Leap\&.Unity\&.Interaction\&.InteractionButton\&.startingPositionMode = \fBStartingPositionMode\&.Depressed\fP"

.PP
Definition at line 42 of file InteractionButton\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionButton\&.controlEnabled\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 34 of file InteractionButton\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionButton\&.depressedAmount\fC [get]\fP"

.PP
Definition at line 124 of file InteractionButton\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionButton\&.depressedThisFrame\fC [get]\fP"

.PP
Definition at line 105 of file InteractionButton\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionButton\&.isDepressed\fC [get]\fP"

.PP
Definition at line 97 of file InteractionButton\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionButton\&.isPressed\fC [get]\fP"

.PP
Gets whether the button is currently held down\&. 
.PP
Definition at line 95 of file InteractionButton\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionButton\&.pressedAmount\fC [get]\fP"

.PP
Gets a normalized value between 0 and 1 based on how depressed the button currently is relative to its maximum depression\&. 0 represents a button fully at rest or pulled out beyond its resting position; 1 represents a fully-pressed button\&. 
.PP
Definition at line 122 of file InteractionButton\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionButton\&.pressedThisFrame\fC [get]\fP"

.PP
Gets whether the button was pressed during this Update frame\&. 
.PP
Definition at line 103 of file InteractionButton\&.cs\&.
.SS "virtual Vector3 Leap\&.Unity\&.Interaction\&.InteractionButton\&.RelaxedLocalPosition\fC [get]\fP"

.PP
Returns the local position of this button when it is able to relax into its target position\&. 
.PP
Definition at line 148 of file InteractionButton\&.cs\&.
.SS "float Leap\&.Unity\&.Interaction\&.InteractionButton\&.springForce\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 65 of file InteractionButton\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionButton\&.unDepressedThisFrame\fC [get]\fP"

.PP
Definition at line 113 of file InteractionButton\&.cs\&.
.SS "bool Leap\&.Unity\&.Interaction\&.InteractionButton\&.unpressedThisFrame\fC [get]\fP"

.PP
Gets whether the button was unpressed this frame\&. 
.PP
Definition at line 111 of file InteractionButton\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
