.TH "Leap.Unity.LeapImageRetriever.LeapDistortionData" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.LeapImageRetriever.LeapDistortionData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCheckStale\fP ()"
.br
.ti -1c
.RI "void \fBReconstruct\fP (\fBImage\fP image, string shaderName)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Texture2D \fBCombinedTexture\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 125 of file LeapImageRetriever\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Leap\&.Unity\&.LeapImageRetriever\&.LeapDistortionData\&.CheckStale ()"

.PP
Definition at line 134 of file LeapImageRetriever\&.cs\&.
.SS "void Leap\&.Unity\&.LeapImageRetriever\&.LeapDistortionData\&.Reconstruct (\fBImage\fP image, string shaderName)"

.PP
Definition at line 138 of file LeapImageRetriever\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Texture2D Leap\&.Unity\&.LeapImageRetriever\&.LeapDistortionData\&.CombinedTexture\fC [get]\fP"

.PP
Definition at line 128 of file LeapImageRetriever\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
