.TH "Leap.Unity.OldRigHierarchy.OldLeapHandControllerData" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.OldRigHierarchy.OldLeapHandControllerData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBlhcTransform\fP"
.br
.ti -1c
.RI "\fBLeapServiceProvider\fP \fBleapServiceProvider\fP"
.br
.ti -1c
.RI "\fBHandModelManager\fP \fBhandModelManager\fP"
.br
.ti -1c
.RI "List< Transform > \fBextraChildTransforms\fP"
.br
.ti -1c
.RI "List< Component > \fBextraComponents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 665 of file LeapRigUpgrader\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<Transform> Leap\&.Unity\&.OldRigHierarchy\&.OldLeapHandControllerData\&.extraChildTransforms"

.PP
Definition at line 669 of file LeapRigUpgrader\&.cs\&.
.SS "List<Component> Leap\&.Unity\&.OldRigHierarchy\&.OldLeapHandControllerData\&.extraComponents"

.PP
Definition at line 670 of file LeapRigUpgrader\&.cs\&.
.SS "\fBHandModelManager\fP Leap\&.Unity\&.OldRigHierarchy\&.OldLeapHandControllerData\&.handModelManager"

.PP
Definition at line 668 of file LeapRigUpgrader\&.cs\&.
.SS "\fBLeapServiceProvider\fP Leap\&.Unity\&.OldRigHierarchy\&.OldLeapHandControllerData\&.leapServiceProvider"

.PP
Definition at line 667 of file LeapRigUpgrader\&.cs\&.
.SS "Transform Leap\&.Unity\&.OldRigHierarchy\&.OldLeapHandControllerData\&.lhcTransform"

.PP
Definition at line 666 of file LeapRigUpgrader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
