.TH "Leap.Unity.RuntimeGizmos.RuntimeColliderGizmos" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.RuntimeGizmos.RuntimeColliderGizmos
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and \fBLeap\&.Unity\&.RuntimeGizmos\&.IRuntimeGizmoComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnDrawRuntimeGizmos\fP (\fBRuntimeGizmoDrawer\fP drawer)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBcolor\fP = Color\&.white"
.br
.ti -1c
.RI "bool \fBuseWireframe\fP = true"
.br
.ti -1c
.RI "bool \fBtraverseHierarchy\fP = true"
.br
.ti -1c
.RI "bool \fBdrawTriggers\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file RuntimeColliderGizmos\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.RuntimeGizmos\&.RuntimeColliderGizmos\&.OnDrawRuntimeGizmos (\fBRuntimeGizmoDrawer\fP drawer)"

.PP
Implements \fBLeap\&.Unity\&.RuntimeGizmos\&.IRuntimeGizmoComponent\fP\&.
.PP
Definition at line 26 of file RuntimeColliderGizmos\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Color Leap\&.Unity\&.RuntimeGizmos\&.RuntimeColliderGizmos\&.color = Color\&.white"

.PP
Definition at line 16 of file RuntimeColliderGizmos\&.cs\&.
.SS "bool Leap\&.Unity\&.RuntimeGizmos\&.RuntimeColliderGizmos\&.drawTriggers = false"

.PP
Definition at line 19 of file RuntimeColliderGizmos\&.cs\&.
.SS "bool Leap\&.Unity\&.RuntimeGizmos\&.RuntimeColliderGizmos\&.traverseHierarchy = true"

.PP
Definition at line 18 of file RuntimeColliderGizmos\&.cs\&.
.SS "bool Leap\&.Unity\&.RuntimeGizmos\&.RuntimeColliderGizmos\&.useWireframe = true"

.PP
Definition at line 17 of file RuntimeColliderGizmos\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
