.TH "Leap.Unity.MultiTypedList.Key" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.MultiTypedList.Key
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file MultiTypedList\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int Leap\&.Unity\&.MultiTypedList\&.Key\&.id"

.PP
Definition at line 23 of file MultiTypedList\&.cs\&.
.SS "int Leap\&.Unity\&.MultiTypedList\&.Key\&.index"

.PP
Definition at line 24 of file MultiTypedList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
