.TH "Leap.DeviceList" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.DeviceList \- The \fBDeviceList\fP class represents a list of \fBDevice\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits List< Device >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeviceList\fP ()"
.br
.RI "Constructs an empty list of devices\&. "
.ti -1c
.RI "\fBDevice\fP \fBFindDeviceByHandle\fP (IntPtr deviceHandle)"
.br
.RI "For internal use only\&. "
.ti -1c
.RI "void \fBAddOrUpdate\fP (\fBDevice\fP device)"
.br
.RI "For internal use only\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDevice\fP \fBActiveDevice\fP\fC [get]\fP"
.br
.RI "The device that is currently streaming tracking data\&. If no streaming devices are found, returns null "
.ti -1c
.RI "bool \fBIsEmpty\fP\fC [get]\fP"
.br
.RI "Reports whether the list is empty\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBDeviceList\fP class represents a list of \fBDevice\fP objects\&. 

Get a \fBDeviceList\fP object by calling \fBController\&.Devices()\fP\&. 
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 20 of file DeviceList\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.DeviceList\&.DeviceList ()"

.PP
Constructs an empty list of devices\&. 
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 27 of file DeviceList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.DeviceList\&.AddOrUpdate (\fBDevice\fP device)"

.PP
For internal use only\&. 
.PP
Definition at line 63 of file DeviceList\&.cs\&.
.SS "\fBDevice\fP Leap\&.DeviceList\&.FindDeviceByHandle (IntPtr deviceHandle)"

.PP
For internal use only\&. 
.PP
Definition at line 32 of file DeviceList\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBDevice\fP Leap\&.DeviceList\&.ActiveDevice\fC [get]\fP"

.PP
The device that is currently streaming tracking data\&. If no streaming devices are found, returns null 
.PP
Definition at line 44 of file DeviceList\&.cs\&.
.SS "bool Leap\&.DeviceList\&.IsEmpty\fC [get]\fP"

.PP
Reports whether the list is empty\&. 
.PP
\fBSince:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition at line 76 of file DeviceList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
