.TH "Leap.Unity.LeapEyeDislocator" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.LeapEyeDislocator \- Moves the camera to each eye position on pre-render\&. Only necessary for image pass-through (IR viewer) scenarios\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
Moves the camera to each eye position on pre-render\&. Only necessary for image pass-through (IR viewer) scenarios\&. 


.PP
Definition at line 20 of file LeapEyeDislocator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
