.TH "Leap.Unity.OldRigHierarchy.OldLeapSpaceData" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.OldRigHierarchy.OldLeapSpaceData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBleapSpaceTransform\fP"
.br
.ti -1c
.RI "List< Transform > \fBnonLHCChildTransforms\fP"
.br
.RI "Some rigs, like the old image rig or modifications to the old standard rig, may have non-LeapHandController transforms as children of the LeapSpace object\&. These objects should be moved to be children of the Camera directly\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 653 of file LeapRigUpgrader\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform Leap\&.Unity\&.OldRigHierarchy\&.OldLeapSpaceData\&.leapSpaceTransform"

.PP
Definition at line 654 of file LeapRigUpgrader\&.cs\&.
.SS "List<Transform> Leap\&.Unity\&.OldRigHierarchy\&.OldLeapSpaceData\&.nonLHCChildTransforms"

.PP
Some rigs, like the old image rig or modifications to the old standard rig, may have non-LeapHandController transforms as children of the LeapSpace object\&. These objects should be moved to be children of the Camera directly\&. 
.PP
Definition at line 661 of file LeapRigUpgrader\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
