.TH "Leap.Unity.DeltaFloatBuffer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.DeltaFloatBuffer \- A ring buffer of floats with a \fBDelta()\fP function that computes the buffer's average change over time\&. \fBDelta()\fP will return zero if the buffer contains one or fewer samples\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.DeltaBuffer< float, float >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeltaFloatBuffer\fP (int bufferSize)"
.br
.ti -1c
.RI "override float \fBDelta\fP ()"
.br
.RI "Returns the average change between each sample per unit time, or zero if the buffer is empty\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A ring buffer of floats with a \fBDelta()\fP function that computes the buffer's average change over time\&. \fBDelta()\fP will return zero if the buffer contains one or fewer samples\&. 

The larger the buffer, the more stable but also delayed the resulting average change over time\&. A buffer size of 5 is a good start for 60-90 Hz updates\&. 
.PP
Definition at line 141 of file DeltaBuffer\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.DeltaFloatBuffer\&.DeltaFloatBuffer (int bufferSize)"

.PP
Definition at line 143 of file DeltaBuffer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override float Leap\&.Unity\&.DeltaFloatBuffer\&.Delta ()\fC [virtual]\fP"

.PP
Returns the average change between each sample per unit time, or zero if the buffer is empty\&. 
.PP
Implements \fBLeap\&.Unity\&.DeltaBuffer< float, float >\fP\&.
.PP
Definition at line 149 of file DeltaBuffer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
