.TH "Leap.Unity.RigidFinger" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.RigidFinger
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.SkeletalFinger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBUpdateFinger\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfiltering\fP = 0\&.5f"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A physics finger model for our rigid hand made out of various cube \fBUnity\fP Colliders\&. 
.PP
Definition at line 16 of file RigidFinger\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Leap\&.Unity\&.RigidFinger\&.UpdateFinger ()\fC [virtual]\fP"
Implement this function to update this finger once per game loop\&. Typically, this function is called by the parent \fBHandModel\fP object's UpdateHand() function, which is called in the \fBUnity\fP Update() phase for graphics hand models and in the FixedUpdate() phase for physics hand models\&. 
.PP
Implements \fBLeap\&.Unity\&.FingerModel\fP\&.
.PP
Definition at line 28 of file RigidFinger\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Leap\&.Unity\&.RigidFinger\&.filtering = 0\&.5f"

.PP
Definition at line 18 of file RigidFinger\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
