.TH "Leap.Unity.Examples.SimpleInteractionEmission" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples.SimpleInteractionEmission
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBnonPrimaryHoverEmission\fP = Color\&.black"
.br
.ti -1c
.RI "Color \fBprimaryHoverEmission\fP = Color\&.white"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file SimpleInteractionEmission\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Color Leap\&.Unity\&.Examples\&.SimpleInteractionEmission\&.nonPrimaryHoverEmission = Color\&.black"

.PP
Definition at line 21 of file SimpleInteractionEmission\&.cs\&.
.SS "Color Leap\&.Unity\&.Examples\&.SimpleInteractionEmission\&.primaryHoverEmission = Color\&.white"

.PP
Definition at line 22 of file SimpleInteractionEmission\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
