.TH "Leap.Unity.PalmDirectionDetector" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.PalmDirectionDetector
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Detector\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBPeriod\fP = \&.1f"
.br
.ti -1c
.RI "\fBHandModelBase\fP \fBHandModel\fP = null"
.br
.ti -1c
.RI "\fBPointingType\fP \fBPointingType\fP = \fBPointingType\&.RelativeToHorizon\fP"
.br
.ti -1c
.RI "Vector3 \fBPointingDirection\fP = Vector3\&.forward"
.br
.ti -1c
.RI "Transform \fBTargetObject\fP = null"
.br
.ti -1c
.RI "float \fBOnAngle\fP = 45"
.br
.ti -1c
.RI "float \fBOffAngle\fP = 65"
.br
.ti -1c
.RI "bool \fBShowGizmos\fP = true"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Detects whether the palm of the hand is pointing toward the specified direction\&. The detector activates when the palm direction is within OnAngle degrees of the desired direction and deactivates when it becomes more than OffAngle degrees\&.
.PP
Directions can be specified relative to the global frame of reference, relative to the camera frame of reference, or using a combination of the two -- relative to the camera direction in the x-z plane, but not changing relative to the horizon\&.
.PP
You can alternatively specify a target game object\&.
.PP
If added to a \fBHandModelBase\fP instance or one of its children, this detector checks the palm direction at the interval specified by the Period variable\&. You can also specify which hand model to observe explicitly by setting handModel in the \fBUnity\fP editor or in code\&.
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 34 of file PalmDirectionDetector\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHandModelBase\fP Leap\&.Unity\&.PalmDirectionDetector\&.HandModel = null"
The \fBHandModelBase\fP instance to observe\&. Set automatically if not explicitly set in the editor\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 49 of file PalmDirectionDetector\&.cs\&.
.SS "float Leap\&.Unity\&.PalmDirectionDetector\&.OffAngle = 65"
The turn-off angle\&. The detector deactivates when the palm points more than this many degrees away from the target direction\&. The off angle must be larger than the on angle\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 102 of file PalmDirectionDetector\&.cs\&.
.SS "float Leap\&.Unity\&.PalmDirectionDetector\&.OnAngle = 45"
The turn-on angle\&. The detector activates when the palm points within this many degrees of the target direction\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 93 of file PalmDirectionDetector\&.cs\&.
.SS "float Leap\&.Unity\&.PalmDirectionDetector\&.Period = \&.1f"
The interval at which to check palm direction\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 42 of file PalmDirectionDetector\&.cs\&.
.SS "Vector3 Leap\&.Unity\&.PalmDirectionDetector\&.PointingDirection = Vector3\&.forward"
The target direction as interpreted by the PointingType setting\&. Ignored when Pointingtype is 'AtTarget\&.' 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 77 of file PalmDirectionDetector\&.cs\&.
.SS "\fBPointingType\fP Leap\&.Unity\&.PalmDirectionDetector\&.PointingType = \fBPointingType\&.RelativeToHorizon\fP"
Specifies how to interprete the direction specified by PointingDirection\&.
.PP
.IP "\(bu" 2
RelativeToCamera -- the target direction is defined relative to the camera's forward vector, i\&.e\&. (0, 0, 1) is the cmaera's local forward direction\&.
.IP "\(bu" 2
RelativeToHorizon -- the target direction is defined relative to the camera's forward vector, except that it does not change with pitch\&.
.IP "\(bu" 2
RelativeToWorld -- the target direction is defined as a global direction that does not change with camera movement\&. For example, (0, 1, 0) is always world up, no matter which way the camera is pointing\&.
.IP "\(bu" 2
AtTarget -- a target object is used as the pointing direction (The specified PointingDirection is ignored)\&.
.PP
.PP
In VR scenes, RelativeToHorizon with a direction of (0, 0, 1) for camera forward and RelativeToWorld with a direction of (0, 1, 0) for absolute up, are often the most useful settings\&. 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 68 of file PalmDirectionDetector\&.cs\&.
.SS "bool Leap\&.Unity\&.PalmDirectionDetector\&.ShowGizmos = true"
Whether to draw the detector's Gizmos for debugging\&. (Not every detector provides gizmos\&.) 
.PP
\fBSince:\fP
.RS 4
4\&.1\&.2 
.RE
.PP

.PP
Definition at line 109 of file PalmDirectionDetector\&.cs\&.
.SS "Transform Leap\&.Unity\&.PalmDirectionDetector\&.TargetObject = null"
The object to point at when the PointingType is 'AtTarget\&.' Ignored otherwise\&. 
.PP
Definition at line 84 of file PalmDirectionDetector\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
