.TH "Leap.Unity.Examples.AngularSpeedTextBehaviour" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Examples.AngularSpeedTextBehaviour
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TextMesh \fBtextMesh\fP"
.br
.ti -1c
.RI "\fBSpaceship\fP \fBship\fP"
.br
.ti -1c
.RI "string \fBangularSpeedPrefixText\fP"
.br
.ti -1c
.RI "string \fBangularSpeedPostfixText\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file AngularSpeedTextBehaviour\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Leap\&.Unity\&.Examples\&.AngularSpeedTextBehaviour\&.angularSpeedPostfixText"

.PP
Definition at line 22 of file AngularSpeedTextBehaviour\&.cs\&.
.SS "string Leap\&.Unity\&.Examples\&.AngularSpeedTextBehaviour\&.angularSpeedPrefixText"

.PP
Definition at line 21 of file AngularSpeedTextBehaviour\&.cs\&.
.SS "\fBSpaceship\fP Leap\&.Unity\&.Examples\&.AngularSpeedTextBehaviour\&.ship"

.PP
Definition at line 20 of file AngularSpeedTextBehaviour\&.cs\&.
.SS "TextMesh Leap\&.Unity\&.Examples\&.AngularSpeedTextBehaviour\&.textMesh"

.PP
Definition at line 19 of file AngularSpeedTextBehaviour\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
