.TH "Leap.Unity.Animation.Internal.TweenRunner" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Animation.Internal.TweenRunner
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBScheduleForRecycle\fP (\fBTweenInstance\fP \fBinstance\fP)"
.br
.ti -1c
.RI "void \fBAddTween\fP (\fBTweenInstance\fP \fBinstance\fP)"
.br
.ti -1c
.RI "void \fBRemoveTween\fP (\fBTweenInstance\fP \fBinstance\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBTweenRunner\fP \fBinstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file TweenRunner\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.Animation\&.Internal\&.TweenRunner\&.AddTween (\fBTweenInstance\fP instance)"

.PP
Definition at line 69 of file TweenRunner\&.cs\&.
.SS "void Leap\&.Unity\&.Animation\&.Internal\&.TweenRunner\&.RemoveTween (\fBTweenInstance\fP instance)"

.PP
Definition at line 89 of file TweenRunner\&.cs\&.
.SS "void Leap\&.Unity\&.Animation\&.Internal\&.TweenRunner\&.ScheduleForRecycle (\fBTweenInstance\fP instance)"

.PP
Definition at line 62 of file TweenRunner\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBTweenRunner\fP Leap\&.Unity\&.Animation\&.Internal\&.TweenRunner\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 24 of file TweenRunner\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
