.TH "Leap.Unity.IPoolable" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.IPoolable \- Implement this interface to recieve a callback whenever your object is spawned from a pool\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLeap\&.Unity\&.Animation\&.IInterpolator\fP, \fBLeap\&.Unity\&.Animation\&.Internal\&.TweenInstance\fP, and \fBLeap\&.Unity\&.BoxedIndexableStruct< Element, IndexableStruct >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnSpawn\fP ()"
.br
.ti -1c
.RI "void \fBOnRecycle\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implement this interface to recieve a callback whenever your object is spawned from a pool\&. 


.PP
Definition at line 20 of file Pool\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.IPoolable\&.OnRecycle ()"

.PP
Implemented in \fBLeap\&.Unity\&.Animation\&.Internal\&.GradientInterpolatorBase\fP, \fBLeap\&.Unity\&.BoxedIndexableStruct< Element, IndexableStruct >\fP, \fBLeap\&.Unity\&.Animation\&.Internal\&.TweenInstance\fP, and \fBLeap\&.Unity\&.Animation\&.Internal\&.InterpolatorBase< ValueType, ObjType >\fP\&.
.SS "void Leap\&.Unity\&.IPoolable\&.OnSpawn ()"

.PP
Implemented in \fBLeap\&.Unity\&.Animation\&.Internal\&.GradientInterpolatorBase\fP, \fBLeap\&.Unity\&.BoxedIndexableStruct< Element, IndexableStruct >\fP, \fBLeap\&.Unity\&.Animation\&.Internal\&.TweenInstance\fP, and \fBLeap\&.Unity\&.Animation\&.Internal\&.InterpolatorBase< ValueType, ObjType >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
