.TH "Leap.Unity.SerializableDictionary< TKey, TValue >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.SerializableDictionary< TKey, TValue > \- In order to have this class be serialized, you will always need to create your own non-generic version specific to your needs\&. This is the same workflow that exists for using the UnityEvent class as well\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.SerializableDictionaryBase\fP, IEnumerable< KeyValuePair< TKey, TValue >>, \fBLeap\&.Unity\&.ICanReportDuplicateInformation\fP, ISerializationCallbackReceiver, and \fBLeap\&.Unity\&.ISerializableDictionary\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (TKey key, TValue value)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "bool \fBContainsKey\fP (TKey key)"
.br
.ti -1c
.RI "bool \fBContainsValue\fP (TValue value)"
.br
.ti -1c
.RI "bool \fBRemove\fP (TKey key)"
.br
.ti -1c
.RI "bool \fBTryGetValue\fP (TKey key, out TValue value)"
.br
.ti -1c
.RI "IEnumerator< KeyValuePair< TKey, TValue > > \fBGetEnumerator\fP ()"
.br
.ti -1c
.RI "virtual float \fBKeyDisplayRatio\fP ()"
.br
.RI "Returns how much of the display space should be allocated to the key\&. Should be a value in the range 0-1\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "void \fBOnAfterDeserialize\fP ()"
.br
.ti -1c
.RI "void \fBOnBeforeSerialize\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator Dictionary< TKey, TValue >\fP (\fBSerializableDictionary\fP< TKey, TValue > serializableDictionary)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TValue \fBthis[TKey key]\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< TKey, TValue >\&.KeyCollection \fBKeys\fP\fC [get]\fP"
.br
.ti -1c
.RI "Dictionary< TKey, TValue >\&.ValueCollection \fBValues\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCount\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
In order to have this class be serialized, you will always need to create your own non-generic version specific to your needs\&. This is the same workflow that exists for using the UnityEvent class as well\&. 


.PP
Definition at line 40 of file SerializableDictionary\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.Add (TKey key, TValue value)"

.PP
Definition at line 74 of file SerializableDictionary\&.cs\&.
.SS "void \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.Clear ()"

.PP
Definition at line 78 of file SerializableDictionary\&.cs\&.
.SS "bool \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.ContainsKey (TKey key)"

.PP
Definition at line 82 of file SerializableDictionary\&.cs\&.
.SS "bool \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.ContainsValue (TValue value)"

.PP
Definition at line 86 of file SerializableDictionary\&.cs\&.
.SS "IEnumerator<KeyValuePair<TKey, TValue> > \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.GetEnumerator ()"

.PP
Definition at line 98 of file SerializableDictionary\&.cs\&.
.SS "virtual float \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.KeyDisplayRatio ()\fC [virtual]\fP"

.PP
Returns how much of the display space should be allocated to the key\&. Should be a value in the range 0-1\&. 
.PP
Implements \fBLeap\&.Unity\&.ISerializableDictionary\fP\&.
.PP
Definition at line 116 of file SerializableDictionary\&.cs\&.
.SS "void \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.OnAfterDeserialize ()"

.PP
Definition at line 137 of file SerializableDictionary\&.cs\&.
.SS "void \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.OnBeforeSerialize ()"

.PP
Definition at line 205 of file SerializableDictionary\&.cs\&.
.SS "static implicit \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.operator Dictionary< TKey, TValue > (\fBSerializableDictionary\fP< TKey, TValue > serializableDictionary)\fC [static]\fP"

.PP
Definition at line 106 of file SerializableDictionary\&.cs\&.
.SS "bool \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.Remove (TKey key)"

.PP
Definition at line 90 of file SerializableDictionary\&.cs\&.
.SS "override string \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.ToString ()"

.PP
Definition at line 120 of file SerializableDictionary\&.cs\&.
.SS "bool \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.TryGetValue (TKey key, out TValue value)"

.PP
Definition at line 94 of file SerializableDictionary\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.Count\fC [get]\fP"

.PP
Definition at line 70 of file SerializableDictionary\&.cs\&.
.SS "Dictionary<TKey, TValue>\&.KeyCollection \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.Keys\fC [get]\fP"

.PP
Definition at line 62 of file SerializableDictionary\&.cs\&.
.SS "TValue \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.this[TKey key]\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 57 of file SerializableDictionary\&.cs\&.
.SS "Dictionary<TKey, TValue>\&.ValueCollection \fBLeap\&.Unity\&.SerializableDictionary\fP< TKey, TValue >\&.Values\fC [get]\fP"

.PP
Definition at line 66 of file SerializableDictionary\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
