.TH "LeapInternal.LEAP_BONE" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_BONE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLEAP_VECTOR\fP \fBprev_joint\fP"
.br
.ti -1c
.RI "\fBLEAP_VECTOR\fP \fBnext_joint\fP"
.br
.ti -1c
.RI "float \fBwidth\fP"
.br
.ti -1c
.RI "\fBLEAP_QUATERNION\fP \fBrotation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 664 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLEAP_VECTOR\fP LeapInternal\&.LEAP_BONE\&.next_joint"

.PP
Definition at line 666 of file LeapC\&.cs\&.
.SS "\fBLEAP_VECTOR\fP LeapInternal\&.LEAP_BONE\&.prev_joint"

.PP
Definition at line 665 of file LeapC\&.cs\&.
.SS "\fBLEAP_QUATERNION\fP LeapInternal\&.LEAP_BONE\&.rotation"

.PP
Definition at line 668 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_BONE\&.width"

.PP
Definition at line 667 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
