.TH "LeapInternal.LEAP_VECTOR" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_VECTOR
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLeap\&.Vector\fP \fBToLeapVector\fP ()"
.br
.ti -1c
.RI "\fBLEAP_VECTOR\fP (\fBLeap\&.Vector\fP leap)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 621 of file LeapC\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LeapInternal\&.LEAP_VECTOR\&.LEAP_VECTOR (\fBLeap\&.Vector\fP leap)"

.PP
Definition at line 630 of file LeapC\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBLeap\&.Vector\fP LeapInternal\&.LEAP_VECTOR\&.ToLeapVector ()"

.PP
Definition at line 626 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float LeapInternal\&.LEAP_VECTOR\&.x"

.PP
Definition at line 622 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_VECTOR\&.y"

.PP
Definition at line 623 of file LeapC\&.cs\&.
.SS "float LeapInternal\&.LEAP_VECTOR\&.z"

.PP
Definition at line 624 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
