.TH "Leap.Unity.RingBuffer< T >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.RingBuffer< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.IIndexable< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRingBuffer\fP (int bufferSize)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (T t)"
.br
.ti -1c
.RI "T \fBGet\fP (int idx)"
.br
.RI "Oldest element is at index 0, youngest is at Count - 1\&. "
.ti -1c
.RI "T \fBGetLatest\fP ()"
.br
.ti -1c
.RI "T \fBGetOldest\fP ()"
.br
.ti -1c
.RI "void \fBSet\fP (int idx, T t)"
.br
.ti -1c
.RI "void \fBSetLatest\fP (T t)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCount\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCapacity\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFull\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsEmpty\fP\fC [get]\fP"
.br
.ti -1c
.RI "T \fBthis[int idx]\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file RingBuffer\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLeap\&.Unity\&.RingBuffer\fP< T >\&.\fBRingBuffer\fP (int bufferSize)"

.PP
Definition at line 20 of file RingBuffer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.Add (T t)"

.PP
Definition at line 59 of file RingBuffer\&.cs\&.
.SS "void \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.Clear ()"

.PP
Definition at line 54 of file RingBuffer\&.cs\&.
.SS "T \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.Get (int idx)"

.PP
Oldest element is at index 0, youngest is at Count - 1\&. 
.PP
Definition at line 73 of file RingBuffer\&.cs\&.
.SS "T \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.GetLatest ()"

.PP
Definition at line 79 of file RingBuffer\&.cs\&.
.SS "T \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.GetOldest ()"

.PP
Definition at line 87 of file RingBuffer\&.cs\&.
.SS "void \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.Set (int idx, T t)"

.PP
Definition at line 95 of file RingBuffer\&.cs\&.
.SS "void \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.SetLatest (T t)"

.PP
Definition at line 102 of file RingBuffer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.Capacity\fC [get]\fP"

.PP
Definition at line 36 of file RingBuffer\&.cs\&.
.SS "int \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.Count\fC [get]\fP"

.PP
Definition at line 25 of file RingBuffer\&.cs\&.
.SS "bool \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.IsEmpty\fC [get]\fP"

.PP
Definition at line 45 of file RingBuffer\&.cs\&.
.SS "bool \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.IsFull\fC [get]\fP"

.PP
Definition at line 40 of file RingBuffer\&.cs\&.
.SS "T \fBLeap\&.Unity\&.RingBuffer\fP< T >\&.this[int idx]\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 49 of file RingBuffer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
