.TH "Leap.Unity.Attributes.OnEditorChangeAttribute" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Attributes.OnEditorChangeAttribute \- Use the OnChange attribute to recieve a callback whenever a field is changed\&. The callback can be in the form of:  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLeap\&.Unity\&.Attributes\&.CombinablePropertyAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOnEditorChangeAttribute\fP (string \fBmethodName\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBmethodName\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Use the OnChange attribute to recieve a callback whenever a field is changed\&. The callback can be in the form of: 


.IP "\(bu" 2
A method accepting zero arguments
.IP "\(bu" 2
A method accepting a single argument matching the field type (new value is passed in as the argument)
.IP "\(bu" 2
A property matching the type of the field (the setter is called with the new value) 
.PP

.PP
Definition at line 29 of file OnEditorChange\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.Attributes\&.OnEditorChangeAttribute\&.OnEditorChangeAttribute (string methodName)"

.PP
Definition at line 32 of file OnEditorChange\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly string Leap\&.Unity\&.Attributes\&.OnEditorChangeAttribute\&.methodName"

.PP
Definition at line 30 of file OnEditorChange\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
