.TH "Leap.Unity.ReadonlySlice< T >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.ReadonlySlice< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits IIndexableStruct< T, ReadonlySlice< T >>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReadonlySlice\fP (\fBReadonlyList\fP< T > list, int beginIdx, int endIdx)"
.br
.RI "Creates a readonlySlice into the \fBReadonlyList\fP with an inclusive beginIdx and an \fIexclusive\fP endIdx\&. A readonlySlice with identical begin and end indices would be an empty readonlySlice\&. "
.ti -1c
.RI "\fBIndexableStructEnumerator\fP< T, \fBReadonlySlice\fP< T > > \fBGetEnumerator\fP ()"
.br
.ti -1c
.RI "\fBQuery\fP< T > \fBQuery\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBthis[int index]\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCount\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file ReadonlySlice\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLeap\&.Unity\&.ReadonlySlice\fP< T >\&.\fBReadonlySlice\fP (\fBReadonlyList\fP< T > list, int beginIdx, int endIdx)"

.PP
Creates a readonlySlice into the \fBReadonlyList\fP with an inclusive beginIdx and an \fIexclusive\fP endIdx\&. A readonlySlice with identical begin and end indices would be an empty readonlySlice\&. A readonlySlice whose endIdx is smaller than its beginIdx will index backwards along the underlying \fBReadonlyList\fP\&. 
.PP
Definition at line 70 of file ReadonlySlice\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIndexableStructEnumerator\fP<T, \fBReadonlySlice\fP<T> > \fBLeap\&.Unity\&.ReadonlySlice\fP< T >\&.GetEnumerator ()"

.PP
Definition at line 92 of file ReadonlySlice\&.cs\&.
.SS "\fBQuery\fP<T> \fBLeap\&.Unity\&.ReadonlySlice\fP< T >\&.\fBQuery\fP ()"

.PP
Definition at line 96 of file ReadonlySlice\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int \fBLeap\&.Unity\&.ReadonlySlice\fP< T >\&.Count\fC [get]\fP"

.PP
Definition at line 84 of file ReadonlySlice\&.cs\&.
.SS "T \fBLeap\&.Unity\&.ReadonlySlice\fP< T >\&.this[int index]\fC [get]\fP"

.PP
Definition at line 77 of file ReadonlySlice\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
