.TH "Leap.Unity.Interaction.PhysicsCallbacks" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Interaction.PhysicsCallbacks
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPhysicsCallbacks\fP \fB_instance\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static Action \fBOnPrePhysics\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "static Action \fBOnPostPhysics\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "static \fBPhysicsCallbacks\fP \fBProvider\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file PhysicsCallbacks\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPhysicsCallbacks\fP Leap\&.Unity\&.Interaction\&.PhysicsCallbacks\&._instance\fC [static]\fP"

.PP
Definition at line 29 of file PhysicsCallbacks\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Action Leap\&.Unity\&.Interaction\&.PhysicsCallbacks\&.OnPostPhysics\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 24 of file PhysicsCallbacks\&.cs\&.
.SS "Action Leap\&.Unity\&.Interaction\&.PhysicsCallbacks\&.OnPrePhysics\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 19 of file PhysicsCallbacks\&.cs\&.
.SS "\fBPhysicsCallbacks\fP Leap\&.Unity\&.Interaction\&.PhysicsCallbacks\&.Provider\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 30 of file PhysicsCallbacks\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
