.TH "Leap.Unity.SerializableDictionaryEditor" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.SerializableDictionaryEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyDrawer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerializableDictionaryEditor\fP ()"
.br
.ti -1c
.RI "override void \fBOnGUI\fP (Rect position, SerializedProperty property, GUIContent label)"
.br
.ti -1c
.RI "override float \fBGetPropertyHeight\fP (SerializedProperty property, GUIContent label)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file SerializableDictionaryEditor\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.SerializableDictionaryEditor\&.SerializableDictionaryEditor ()"

.PP
Definition at line 38 of file SerializableDictionaryEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override float Leap\&.Unity\&.SerializableDictionaryEditor\&.GetPropertyHeight (SerializedProperty property, GUIContent label)"

.PP
Definition at line 69 of file SerializableDictionaryEditor\&.cs\&.
.SS "override void Leap\&.Unity\&.SerializableDictionaryEditor\&.OnGUI (Rect position, SerializedProperty property, GUIContent label)"

.PP
Definition at line 54 of file SerializableDictionaryEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
