.TH "LeapInternal.LEAP_TRACKING_EVENT" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LeapInternal.LEAP_TRACKING_EVENT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLEAP_FRAME_HEADER\fP \fBinfo\fP"
.br
.ti -1c
.RI "Int64 \fBtracking_id\fP"
.br
.ti -1c
.RI "UInt32 \fBnHands\fP"
.br
.ti -1c
.RI "IntPtr \fBpHands\fP"
.br
.ti -1c
.RI "float \fBframerate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 514 of file LeapC\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float LeapInternal\&.LEAP_TRACKING_EVENT\&.framerate"

.PP
Definition at line 519 of file LeapC\&.cs\&.
.SS "\fBLEAP_FRAME_HEADER\fP LeapInternal\&.LEAP_TRACKING_EVENT\&.info"

.PP
Definition at line 515 of file LeapC\&.cs\&.
.SS "UInt32 LeapInternal\&.LEAP_TRACKING_EVENT\&.nHands"

.PP
Definition at line 517 of file LeapC\&.cs\&.
.SS "IntPtr LeapInternal\&.LEAP_TRACKING_EVENT\&.pHands"

.PP
Definition at line 518 of file LeapC\&.cs\&.
.SS "Int64 LeapInternal\&.LEAP_TRACKING_EVENT\&.tracking_id"

.PP
Definition at line 516 of file LeapC\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
