.TH "Leap.Unity.EnumEventTableEditor" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.EnumEventTableEditor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnumEventTableEditor\fP (SerializedProperty tableProperty, Type enumType)"
.br
.RI "The enum event table is unable to properly display itself in the inspector, it instead must be constructed and used from within a custom editor\&. Pass in a serialized property pointing to the \fBEnumEventTable\fP, and the enum type used by the table\&. "
.ti -1c
.RI "void \fBDoGuiLayout\fP ()"
.br
.ti -1c
.RI "bool \fBHasAnyCallbacks\fP (int enumValue)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file EnumEventTableEditor\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.Unity\&.EnumEventTableEditor\&.EnumEventTableEditor (SerializedProperty tableProperty, Type enumType)"

.PP
The enum event table is unable to properly display itself in the inspector, it instead must be constructed and used from within a custom editor\&. Pass in a serialized property pointing to the \fBEnumEventTable\fP, and the enum type used by the table\&. 
.PP
Definition at line 34 of file EnumEventTableEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Leap\&.Unity\&.EnumEventTableEditor\&.DoGuiLayout ()"

.PP
Definition at line 47 of file EnumEventTableEditor\&.cs\&.
.SS "bool Leap\&.Unity\&.EnumEventTableEditor\&.HasAnyCallbacks (int enumValue)"

.PP
Definition at line 96 of file EnumEventTableEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
