.TH "Leap.LeapEventArgs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.LeapEventArgs \- A generic object with no arguments beyond the event type\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.PP
Inherited by \fBLeap\&.ConfigChangeEventArgs\fP, \fBLeap\&.ConnectionEventArgs\fP, \fBLeap\&.ConnectionLostEventArgs\fP, \fBLeap\&.DeviceEventArgs\fP, \fBLeap\&.DeviceFailureEventArgs\fP, \fBLeap\&.DistortionEventArgs\fP, \fBLeap\&.DroppedFrameEventArgs\fP, \fBLeap\&.FrameEventArgs\fP, \fBLeap\&.HeadPoseEventArgs\fP, \fBLeap\&.ImageEventArgs\fP, \fBLeap\&.InternalFrameEventArgs\fP, \fBLeap\&.LogEventArgs\fP, \fBLeap\&.PointMappingChangeEventArgs\fP, \fBLeap\&.PolicyEventArgs\fP, and \fBLeap\&.SetConfigResponseEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLeapEventArgs\fP (\fBLeapEvent\fP \fBtype\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLeapEvent\fP \fBtype\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A generic object with no arguments beyond the event type\&. 


.PP
\fBSince:\fP
.RS 4
3\&.0 
.RE
.PP

.PP
Definition at line 43 of file Events\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Leap\&.LeapEventArgs\&.LeapEventArgs (\fBLeapEvent\fP type)"

.PP
Definition at line 44 of file Events\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBLeapEvent\fP Leap\&.LeapEventArgs\&.type\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 47 of file Events\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
