.TH "Leap.Unity.Interaction.Examples" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Leap.Unity.Interaction.Examples
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHideInteractionHandWhenControllerMoving\fP"
.br
.RI "This simple example script disables the \fBInteractionHand\fP script and has event outputs to drive hiding \fBLeap\fP hand renderers when it detects that an \fBInteractionXRController\fP is tracked and moving (e\&.g\&. it has been picked up)\&. "
.ti -1c
.RI "class \fBMovePoseExample\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
