.TH "md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.ads_0D2.0.8__c_h_a_n_g_e_l_o_g" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.ads_0D2.0.8__c_h_a_n_g_e_l_o_g \- CHANGELOG 
[1\&.0\&.1]
.PP
Adding Readme file Adding local plugin importer callbacks\&. Removing Bintray references in package\&.json
.PP
[2\&.0\&.3]
.PP
Fix bug where importing the asset store ads package would cause duiplicate symbols, and removing the asset store ads package would cause missing symbols\&.
.PP
[2\&.0\&.4]
.PP
Added new description string to package\&.json Fixed art assets to use no compression (fixes issue switching between iOS and PC builds)
.PP
[2\&.0\&.5] - 2018-03-29
.PP
Fix for https://fogbugz.unity3d.com/f/cases/1011363 Fixes an incorrect guid that the importer used to include/exclude the runtime assembly from the build\&.
.PP
[2\&.0\&.6] - 2018-03-29
.PP
Update changelog for this and 2\&.0\&.5
.PP
[2\&.0\&.7] - 2018-04-06
.PP
Fix editor assembly project file to include the importer script\&.
.PP
[2\&.0\&.8] - 2018-05-01
.PP
Add call to SetShouldOverridePredicate to exclude package dll when asset store dlls are present\&. Update unity version attribute to support 2017\&.4 LTS
.PP
Fix an issue with the editor assembly to add back in some iOS platform specific code that was removed via conditionals (which is fine for source packages, but doesn't work with precompiled assemblies) 
