.TH "md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.package-manager-ui_0D2.0.7__c_h_a_n_g_e_l_o_g" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.package-manager-ui_0D2.0.7__c_h_a_n_g_e_l_o_g \- Changelog 
All notable changes to this package will be documented in this file\&.
.PP
The format is based on \fCKeep a Changelog\fP and this project adheres to \fCSemantic Versioning\fP\&.
.PP
.SS "[2\&.0\&.7] - 2019-03-06"
.PP
.IP "\(bu" 2
Fix version parse for \&.NET 3\&.5
.PP
.PP
.SS "[2\&.0\&.4] - 2018-12-02"
.PP
.IP "\(bu" 2
Fix version conversion to support different CultureInfos
.PP
.PP
.SS "[2\&.0\&.3] - 2018-10-10"
.PP
.IP "\(bu" 2
When a preview package is installed, keep showing updates even if 'Show Preview Packages' is not checked
.IP "\(bu" 2
When user as not already choose to show or hide Preview Packages:
.IP "  \(bu" 4
If a preview package is already installed, 'Show Preview Packages' is checked
.IP "  \(bu" 4
If no preview packages are installed, 'Show Preview Packages' is not checked
.PP

.PP
.PP
.SS "[2\&.0\&.2] - 2018-10-04"
.PP
.IP "\(bu" 2
Documentation Update
.IP "\(bu" 2
Update dialog title to 'Unity Package Manager'
.PP
.PP
.SS "[2\&.0\&.1] - 2018-09-14"
.PP
.IP "\(bu" 2
Move undesired public classes to internal
.IP "\(bu" 2
Minor fix to the documentation
.PP
.PP
.SS "[2\&.0\&.0] - 2018-09-10"
.PP
.IP "\(bu" 2
Always mark a package as up to date when it's not installed
.IP "\(bu" 2
Add 'Advanced' menu
.IP "\(bu" 2
Hide preview packages by default
.IP "\(bu" 2
Labelled packages with major version '0' as preview
.IP "\(bu" 2
Fixed cropped error message
.IP "\(bu" 2
Disabled downgrading Package Manager UI to incompatible versions
.IP "\(bu" 2
Updated docs to reflect the new UI
.IP "\(bu" 2
Fix incorrect verified tag on preview packages
.IP "\(bu" 2
UI Fixes:
.IP "  \(bu" 4
Change mouse cursor when hovering over links
.IP "  \(bu" 4
Tweak UI layout for better alignment
.PP

.IP "\(bu" 2
Fixed dropdown to work with 2018\&.3 editor
.IP "\(bu" 2
Updated style to reflect changes in VisualElements
.IP "\(bu" 2
Added packages serialization to avoid unnecessary refreshes
.IP "\(bu" 2
Enable 'View Documentation' Button on built-in packages, and make it point to the url contained in the description string
.IP "\(bu" 2
Added persistent error icon when there are package add or remove errors
.IP "\(bu" 2
Filter by name, category, version and release tag
.IP "\(bu" 2
Show All Package by default
.IP "\(bu" 2
MenuDropdown for All packages/In project/Built-in
.IP "\(bu" 2
UI redesign
.IP "\(bu" 2
Remove sentence 'This package is installed for\&.\&.\&.' and all other sentence regarding status of the package
.IP "\(bu" 2
Hide buttons for embedded, git and local packages
.IP "\(bu" 2
Display 'No results for '"
.PP
.PP
.SS "[1\&.9\&.9] - 2018-05-09"
.PP
.IP "\(bu" 2
Only show user visible versions in the UI
.PP
.PP
.SS "[1\&.9\&.8] - 2018-05-01"
.PP
.IP "\(bu" 2
Fixed package to work with 2018\&.3
.IP "\(bu" 2
Deprecated 2018\&.1 because of its inability to update without error
.PP
.PP
.SS "[1\&.9\&.6] - 2018-04-10"
.PP
.IP "\(bu" 2
Added ability to choose a package version
.IP "\(bu" 2
Added loading indicator when retrieving package lists
.PP
.PP
.SS "[1\&.9\&.5] - 2018-03-28"
.PP
.IP "\(bu" 2
Optimize packages list loading
.IP "\(bu" 2
Fixes for UXML factories changes in Unity
.IP "\(bu" 2
UI Fixes:
.IP "  \(bu" 4
'View changes' update position and label should say 'View Changelog'
.IP "  \(bu" 4
Packages list should not have padding
.IP "  \(bu" 4
preview and verified tags should be lower case everywhere
.IP "  \(bu" 4
the package displayed name should stay on 1 line
.PP

.PP
.PP
.SS "[1\&.9\&.3] - 2018-03-11"
.PP
.IP "\(bu" 2
Added caching for faster UI response time
.IP "\(bu" 2
Exposed APIs for the Package Manager UI extension mechanism
.PP
.PP
.SS "[1\&.8\&.2] - 2018-03-02"
.PP
.IP "\(bu" 2
Modified Tags to reflect new package workflow (Preview -> Released(no tag) -> Verified)
.PP
.PP
.SS "[1\&.8\&.1] - 2018-02-23"
.PP
.IP "\(bu" 2
Removed Recommended tag if package version is alpha, beta or experimental
.PP
.PP
.SS "[1\&.8\&.0] - 2018-02-16"
.PP
.IP "\(bu" 2
Removed support built-in packages
.IP "\(bu" 2
Fixed packages sorting in All tab
.IP "\(bu" 2
Fixed error reporting with an invalid manifest
.PP
.PP
.SS "[1\&.7\&.2] - 2018-02-08"
.PP
.IP "\(bu" 2
Fixed errors when an exception is thrown during an operation
.IP "\(bu" 2
Changed to only show 'View Changes' when there is an update button
.IP "\(bu" 2
Fixed typos in dialog when updating package manager ui
.PP
.PP
.SS "[1\&.7\&.0] - 2018-02-05"
.PP
.IP "\(bu" 2
Added 'View Documentation' link to package details
.IP "\(bu" 2
Added 'View changes' link to package details
.PP
.PP
.SS "[1\&.6\&.1] - 2018-01-30"
.PP
.SS "Fixes"
.PP
.IP "\(bu" 2
When updating from 1\&.5\&.1, ask user to confirm close of window prior to update
.IP "\(bu" 2
Made window dockable
.IP "\(bu" 2
Reworked UI styles
.IP "\(bu" 2
Enhanced keyboard navigation
.PP
.PP
.SS "[1\&.5\&.1] - 2018-01-18"
.PP
.SS "Fixes"
.PP
.IP "\(bu" 2
Replaced VisualContainer by VisualElement in code and templates
.IP "\(bu" 2
Moved 'Project->Packages->Manage' menu item to 'Window->Package Manager'
.IP "\(bu" 2
Showed the latest version and description in tab 'Install' instead of the current version
.IP "\(bu" 2
Added 'Recommended' tag properly
.IP "\(bu" 2
Added 'Go back to' when latest version is less than current one
.IP "\(bu" 2
Removed 'Update to' when current version is greater than latest one\&. (case for embedded or local packages)
.IP "\(bu" 2
Replaced packages action button label:
.IP "  \(bu" 4
'Install' instead of 'Add' for packages
.IP "  \(bu" 4
'Enable/Disable' instead of 'Add/Remove' for built-in packages
.PP

.IP "\(bu" 2
Added 'alpha', 'beta', 'experimental' and 'recommended' tags support
.IP "\(bu" 2
Added loading progress while opening window
.IP "\(bu" 2
Added package description and display name update
.IP "\(bu" 2
Added extra messaging on package state
.IP "\(bu" 2
Performed Documentation update
.PP
.PP
.SS "[1\&.3\&.0] - 2017-12-12"
.PP
.SS "Changes"
.PP
.IP "\(bu" 2
Added assembly definition files
.IP "\(bu" 2
Forced SemVer to use \&.NetStandard
.IP "\(bu" 2
Fixed ValidationSuiteTests tests
.IP "\(bu" 2
Handled compatible versions returned in PackageInfo
.PP
.PP
.SS "[1\&.2\&.0] - 2017-11-16"
.PP
.SS "Fixes"
.PP
.IP "\(bu" 2
Fixed flickering test When_Default_FirstPackageUIElement_HasSelectedClass, use package only
.IP "\(bu" 2
Fixed documentation
.IP "\(bu" 2
Added Doxygen configuration file
.IP "\(bu" 2
Removed unused fields in package\&.json
.IP "\(bu" 2
Changed 'Modules' for 'Built In Packages'
.IP "\(bu" 2
Removed version display for Built In Packages
.PP
.PP
.SS "[1\&.0\&.0] - 2017-11-10"
.PP
.SS "This is the first release of \fIUnity Package Manager UI\fP\&."

