.TH "md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.analytics_0D3.2.2__documentation" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.analytics_0D3.2.2__documentation \- ~_analytics About the Analytics Package 
This Analytics package supports the following Unity Analytics features:
.PP
.IP "\(bu" 2
\fCStandard Events\fP
.IP "\(bu" 2
\fCAnalytics Event Tracker\fP
.IP "\(bu" 2
\fCUnity Analytics Data Privacy Plug-in\fP
.PP
.PP
For instructions on using the features in the Analytics package, refer to the \fCAnalytics section of the Unity Manual\fP\&.
.PP
The package is supported by Unity 2018\&.3+ and includes functionality previously included in earlier Unity Asset Store and Package Manager packages\&. When upgrading existing projects to 2018\&.3 or later, older, redundant packages should be removed from the project\&.
.PP
.SS "Installing the Analytics Package"
.PP
The Analytics package is built into the Unity Editor and enabled automatically\&. Use the Unity Package Manager (menu: \fBWindow\fP > \fBPackage Manager\fP) to disable or enable the package\&. The Analytics package is listed under the built-in packages\&.
.PP
 
.SS "Using the Analytics Package"
.PP
For instructions on using the features in the Analytics package, refer to the Unity Manual:
.PP
.IP "\(bu" 2
\fCStandard Events\fP
.IP "\(bu" 2
\fCAnalytics Event Tracker\fP
.IP "\(bu" 2
\fCUnity Analytics Data Privacy Plug-in\fP
.PP
.PP
.SS "Package contents"
.PP
The following table indicates the major classes, components, and files included in the Analytics package:
.PP
Item  Description   \fC\fCAnalyticsEvent\fP class\fP  The primary class for sending Standard and Custom analytics events to the Unity Analytics service\&.   \fCAnalytics Event Tracker component\fP  A Unity component that you can use to send Standard and Custom analytics events (without writing code)\&.   \fCDataPrivacy class\fP  A utility class that helps applications using Unity Analytics comply with the EU General Data Protection Regulation (GDPR)\&.   \fCPackages/Analytics Library/DataPrivacy/DataPrivacyButton\fP  A Prefab GameObject you can use when building a user interface to allow players to opt out of Analytics data collection\&.   \fCPackages/Analytics Library/DataPrivacy/DataPrivacyIcon\fP  An icon graphic you can use when creating your own opt-out button or control\&.   
.PP
.SS "Document revision history"
.PP
Date  Reason   October 5, 2018  Document created\&. Matches package version 3\&.2\&.0\&.   
