.TH "md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.collab-proxy_0D1.2.15__c_h_a_n_g_e_l_o_g" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.collab-proxy_0D1.2.15__c_h_a_n_g_e_l_o_g \- Changelog 
All notable changes to this package will be documented in this file\&.
.PP
The format is based on \fCKeep a Changelog\fP and this project adheres to \fCSemantic Versioning\fP\&.
.PP
.SS "[1\&.2\&.15] - 2018-11-16"
.PP
Added support for non-experimental UIElements\&.
.PP
.SS "[1\&.2\&.11] - 2018-09-04"
.PP
Made some performance improvements to reduce impact on ReloadAssemblies\&.
.PP
.SS "[1\&.2\&.9] - 2018-08-13"
.PP
Test issues for the Collab History Window are now fixed\&.
.PP
.SS "[1\&.2\&.7] - 2018-08-07"
.PP
Toolbar drop-down will no longer show up when package is uninstalled\&.
.PP
.SS "[1\&.2\&.6] - 2018-06-15"
.PP
Fixed an issue where Collab's History window wouldn't load properly\&.
.PP
.SS "[1\&.2\&.5] - 2018-05-21"
.PP
This is the first release of \fIUnity Package \fBCollabProxy\fP\fP\&.
.PP
.SS "Added"
.PP
.IP "\(bu" 2
Collab history and toolbar windows
.IP "\(bu" 2
Collab view and presenter classes
.IP "\(bu" 2
Collab Editor tests for view and presenter 
.PP

