.TH "md__o_1__git_h_u_b_m_i_n_i_p_roject__r_e_a_d_m_e" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__o_1__git_h_u_b_m_i_n_i_p_roject__r_e_a_d_m_e \- Multi User VR Viewer Mini Project 
Multi user VR Viewer with voice chat and Hand IK
.PP
#How to play :
.PP
Drag the Main scene and place it under Environment Hierarchy\&.
.PP
Set up your unity account and make sure that your multiplayer networking is enabled\&.
.PP
Now you can play\&.
.PP
Look at the Multi USER VR Viewer Presentation for more information on networking
.PP
#More about the code:
.PP
Doxygen Documentation- To be uploaded soon
.PP
#Developed by :
.PP
Saurabh Bagh
.PP
Prakash Verma
.PP
Sri Hari
.PP
#12-07-2019 
