.TH "md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.purchasing_0D2.0.3__documentation__i_a_p" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.purchasing_0D2.0.3__documentation__i_a_p \- Unity In-App Purchasing (IAP) 
Unity IAP makes it easy to implement in-app purchases in your application across the most popular App stores\&.
.PP
Supported platforms include:
.PP
.IP "\(bu" 2
iOS App Store
.IP "\(bu" 2
Mac App Store
.IP "\(bu" 2
Google Play
.IP "\(bu" 2
Universal Windows Platform
.IP "\(bu" 2
Amazon Appstore
.IP "\(bu" 2
Samsung Galaxy Apps
.IP "\(bu" 2
Tizen Store
.IP "\(bu" 2
CloudMoolah Store
.IP "\(bu" 2
Facebook Gameroom
.IP "\(bu" 2
Xiaomi Mi Game Pay 
.PP

