.TH "md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.xr.openvr.standalone_0D1.0.0__r_e_a_d_m_e" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__o_1__git_h_u_b_m_i_n_i_p_roject__library__package_cache_com.unity.xr.openvr.standalone_0D1.0.0__r_e_a_d_m_e \- Oculus XR SDK Package 
The purpose of this package is to provide OpenVR XR Support\&. This package provides the necessary sdk libraries for users to build Applications that work with the SteamVR runtime\&.
.PP
.SS "Package structure"
.PP
.PP
.nf
<root>
    com\&.unity\&.openvr
        README
        Licenses
        CHANGELOG
        Documentation
        package\&.json
.fi
.PP
 
