.TH "O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.analytics@3.2.2/Tests/Editor/Unity.Analytics.StandardEvents Directory Reference" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.analytics@3.2.2/Tests/Editor/Unity.Analytics.StandardEvents Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAchievementStepTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBAchievementUnlockedTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBAdCompleteTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBAdOfferTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBAdSkipTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBAdStartTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBAnalyticsEventTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBChatMessageSentTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBCutsceneSkipTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBCutsceneStartTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBFirstInteractionTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBGameOverTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBGameStartTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBIAPTransactionTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBItemAcquiredTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBItemSpentTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBLevelCompleteTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBLevelFailTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBLevelQuitTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBLevelSkipTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBLevelStartTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBLevelUpTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBPostAdActionTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBPushNotificationClickTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBPushNotificationEnableTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBScreenVisitTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBSocialShareAcceptTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBSocialShareTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBStoreItemClickTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBStoreOpenedTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTutorialCompleteTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTutorialSkipTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTutorialStartTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTutorialStepTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBUserSignupTests\&.cs\fP"
.br
.in -1c
