.TH "O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.package-manager-ui@2.0.7/Editor/Sources/Services/Packages Directory Reference" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.package-manager-ui@2.0.7/Editor/Sources/Services/Packages Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPackage\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageAssetPostprocessor\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageCollection\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageError\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageFilter\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageGroupOrigins\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageInfoListExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageJsonHelper\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageListExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageOrigin\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageSearchFilter\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageState\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackageTag\&.cs\fP"
.br
.in -1c
