.TH "O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.package-manager-ui@2.0.7/Editor/Sources/Services/Interfaces Directory Reference" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.package-manager-ui@2.0.7/Editor/Sources/Services/Interfaces Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIAddOperation\&.cs\fP"
.br
.ti -1c
.RI "file \fBIBaseOperation\&.cs\fP"
.br
.ti -1c
.RI "file \fBIListOperation\&.cs\fP"
.br
.ti -1c
.RI "file \fBIOperationFactory\&.cs\fP"
.br
.ti -1c
.RI "file \fBIRemoveOperation\&.cs\fP"
.br
.ti -1c
.RI "file \fBISearchOperation\&.cs\fP"
.br
.in -1c
