.TH "O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.ads@2.0.8/Editor/Resources/iOS/builds/UnityAds.framework/Headers Directory Reference" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.ads@2.0.8/Editor/Resources/iOS/builds/UnityAds.framework/Headers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBUADSInAppPurchaseMetaData\&.h\fP"
.br
.ti -1c
.RI "file \fBUADSJsonStorage\&.h\fP"
.br
.ti -1c
.RI "file \fBUADSMediationMetaData\&.h\fP"
.br
.ti -1c
.RI "file \fBUADSMetaData\&.h\fP"
.br
.ti -1c
.RI "file \fBUADSPlayerMetaData\&.h\fP"
.br
.ti -1c
.RI "file \fBUnityAds\&.h\fP"
.br
.ti -1c
.RI "file \fBUnityAdsExtended\&.h\fP"
.br
.ti -1c
.RI "file \fBUnityAdsUnityDelegate\&.h\fP"
.br
.in -1c
