.TH "O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/Attributes/OnEditorChange.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/Attributes/OnEditorChange.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLeap\&.Unity\&.Attributes\&.OnEditorChangeAttribute\fP"
.br
.RI "Use the OnChange attribute to recieve a callback whenever a field is changed\&. The callback can be in the form of: "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLeap\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\&.Attributes\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBUnityObject\fP = UnityEngine\&.Object"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBUnityObject\fP =  UnityEngine\&.Object"

.PP
Definition at line 16 of file OnEditorChange\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
