.TH "PlayerController" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerController \- This class takes care of the player movement and shooting of bullets  

.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCmdFireLeft\fP (Vector3 x, Quaternion y)"
.br
.RI "Command :This [Command] code is called on the Client ,but it is run on the Server! This is invoke when Left trigger is pressed with parameter x is being position of controller and parameter y is rotation of the controller\&. "
.ti -1c
.RI "void \fBCmdFireRight\fP (Vector3 x, Quaternion y)"
.br
.RI "This is invoke when Right trigger is pressed with parameter x is being position of controller and parameter y is rotation of the controller\&. "
.ti -1c
.RI "override void \fBOnStartLocalPlayer\fP ()"
.br
.RI "Setting offset of the player and initializing the player position with offset\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBbulletPrefab\fP"
.br
.ti -1c
.RI "Transform \fBbulletSpawn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class takes care of the player movement and shooting of bullets 


.PP
Definition at line 12 of file PlayerController\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void PlayerController\&.CmdFireLeft (Vector3 x, Quaternion y)"

.PP
Command :This [Command] code is called on the Client ,but it is run on the Server! This is invoke when Left trigger is pressed with parameter x is being position of controller and parameter y is rotation of the controller\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP position of the left controller
.br
\fIy\fP rotation of the left controller
.RE
.PP
Create the Bullet from the Bullet Prefab
.PP
Add velocity to the bullet
.PP
Spawn the bullet on the Clients
.PP
Destroy the bullet after 8 seconds 
.PP
Definition at line 106 of file PlayerController\&.cs\&.
.SS "void PlayerController\&.CmdFireRight (Vector3 x, Quaternion y)"

.PP
This is invoke when Right trigger is pressed with parameter x is being position of controller and parameter y is rotation of the controller\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP position of the right controller
.br
\fIy\fP rotation of the right controller
.RE
.PP

.PP
Definition at line 129 of file PlayerController\&.cs\&.
.SS "override void PlayerController\&.OnStartLocalPlayer ()"

.PP
Setting offset of the player and initializing the player position with offset\&. 
.PP
Definition at line 149 of file PlayerController\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject PlayerController\&.bulletPrefab"

.PP
Definition at line 14 of file PlayerController\&.cs\&.
.SS "Transform PlayerController\&.bulletSpawn"

.PP
Definition at line 15 of file PlayerController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
