.TH "O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/DataStructures/SerializableDictionary.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/LeapMotion/Core/Scripts/DataStructures/SerializableDictionary.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLeap\&.Unity\&.SDictionaryAttribute\fP"
.br
.ti -1c
.RI "class \fBLeap\&.Unity\&.SerializableDictionaryBase\fP"
.br
.ti -1c
.RI "interface \fBLeap\&.Unity\&.ICanReportDuplicateInformation\fP"
.br
.ti -1c
.RI "interface \fBLeap\&.Unity\&.ISerializableDictionary\fP"
.br
.ti -1c
.RI "class \fBLeap\&.Unity\&.SerializableDictionary< TKey, TValue >\fP"
.br
.RI "In order to have this class be serialized, you will always need to create your own non-generic version specific to your needs\&. This is the same workflow that exists for using the UnityEvent class as well\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLeap\fP"
.br
.ti -1c
.RI "namespace \fBLeap\&.Unity\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
