.TH "SimpleShoot" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleShoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBbulletPrefab\fP"
.br
.ti -1c
.RI "GameObject \fBcasingPrefab\fP"
.br
.ti -1c
.RI "GameObject \fBmuzzleFlashPrefab\fP"
.br
.ti -1c
.RI "Transform \fBbarrelLocation\fP"
.br
.ti -1c
.RI "Transform \fBcasingExitLocation\fP"
.br
.ti -1c
.RI "float \fBshotPower\fP = 100f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file SimpleShoot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform SimpleShoot\&.barrelLocation"

.PP
Definition at line 11 of file SimpleShoot\&.cs\&.
.SS "GameObject SimpleShoot\&.bulletPrefab"

.PP
Definition at line 8 of file SimpleShoot\&.cs\&.
.SS "Transform SimpleShoot\&.casingExitLocation"

.PP
Definition at line 12 of file SimpleShoot\&.cs\&.
.SS "GameObject SimpleShoot\&.casingPrefab"

.PP
Definition at line 9 of file SimpleShoot\&.cs\&.
.SS "GameObject SimpleShoot\&.muzzleFlashPrefab"

.PP
Definition at line 10 of file SimpleShoot\&.cs\&.
.SS "float SimpleShoot\&.shotPower = 100f"

.PP
Definition at line 15 of file SimpleShoot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
