.TH "O:/GitHUBMINIPRoject/Assets/SteamVR/Input/SteamVR_Input_ActionScopes.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/SteamVR/Input/SteamVR_Input_ActionScopes.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBValve\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.VR\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBValve\&.VR\&.SteamVR_Input_ActionScopes\fP { \fBValve\&.VR\&.SteamVR_Input_ActionScopes\&.ActionSet\fP, \fBValve\&.VR\&.SteamVR_Input_ActionScopes\&.Application\fP, \fBValve\&.VR\&.SteamVR_Input_ActionScopes\&.Global\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
