.TH "O:/GitHUBMINIPRoject/Assets/SteamVR/Input/SteamVR_Action_Boolean.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/SteamVR/Input/SteamVR_Action_Boolean.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Action_Boolean\fP"
.br
.RI "Boolean actions are either true or false\&. There are a variety of helper events included that will fire for the given input source\&. They're prefixed with 'on'\&. "
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Action_Boolean_Source_Map\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Action_Boolean_Source\fP"
.br
.ti -1c
.RI "interface \fBValve\&.VR\&.ISteamVR_Action_Boolean\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBValve\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.VR\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
