.TH "O:/GitHUBMINIPRoject/Assets/SteamVR/Extras/SteamVR_GazeTracker.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/SteamVR/Extras/SteamVR_GazeTracker.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBValve\&.VR\&.Extras\&.SteamVR_GazeTracker\fP"
.br
.ti -1c
.RI "struct \fBValve\&.VR\&.Extras\&.GazeEventArgs\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBValve\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.VR\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.VR\&.Extras\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBValve\&.VR\&.Extras\&.GazeEventHandler\fP (object sender, GazeEventArgs gazeEventArgs)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
