.TH "O:/GitHUBMINIPRoject/Assets/SteamVR/Input/SteamVR_Input_ActionFile.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/SteamVR/Input/SteamVR_Input_ActionFile.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ActionFile\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ActionFile_ActionSet\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ActionFile_Action\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ActionFile_LocalizationItem\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ManifestFile\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ManifestFile_Application\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_Unity_AssemblyFile_Definition\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ManifestFile_ApplicationString\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ManifestFile_Application_Binding\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ManifestFile_Application_Binding_ControllerTypes\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ActionFile_ActionTypes\fP"
.br
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Input_ActionFile_ActionSet_Usages\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBValve\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.VR\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBValve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding_ControllerTypes\fP { \fBValve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding_ControllerTypes\&.vive\fP, \fBValve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding_ControllerTypes\&.vive_pro\fP, \fBValve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding_ControllerTypes\&.vive_controller\fP, \fBValve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding_ControllerTypes\&.generic\fP, \fBValve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding_ControllerTypes\&.holographic_controller\fP, \fBValve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding_ControllerTypes\&.oculus_touch\fP, \fBValve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding_ControllerTypes\&.gamepad\fP, \fBValve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding_ControllerTypes\&.knuckles\fP }"
.br
.ti -1c
.RI "enum \fBValve\&.VR\&.SteamVR_Input_ActionFile_Action_Requirements\fP { \fBValve\&.VR\&.SteamVR_Input_ActionFile_Action_Requirements\&.optional\fP, \fBValve\&.VR\&.SteamVR_Input_ActionFile_Action_Requirements\&.suggested\fP, \fBValve\&.VR\&.SteamVR_Input_ActionFile_Action_Requirements\&.mandatory\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
