.TH "O:/GitHUBMINIPRoject/Assets/SteamVR/Extras/SteamVR_ForceSteamVRMode.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/SteamVR/Extras/SteamVR_ForceSteamVRMode.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBValve\&.VR\&.Extras\&.SteamVR_ForceSteamVRMode\fP"
.br
.RI "This is an example class of how to force steamvr initialization\&. You still need to have vr mode enabled but you can have the top sdk set to None, then this script will force it to \fBOpenVR\fP after a second "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBValve\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.VR\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.VR\&.Extras\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
