.TH "O:/GitHUBMINIPRoject/Assets/SteamVR/Input/SteamVR_Action_Vector2.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/SteamVR/Input/SteamVR_Action_Vector2.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Action_Vector2\fP"
.br
.RI "An analog action with two values generally from -1 to 1\&. Also provides a delta since the last update\&. "
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Action_Vector2_Source_Map\fP"
.br
.RI "Boolean actions are either true or false\&. There is an onStateUp and onStateDown event for the rising and falling edge\&. "
.ti -1c
.RI "class \fBValve\&.VR\&.SteamVR_Action_Vector2_Source\fP"
.br
.ti -1c
.RI "interface \fBValve\&.VR\&.ISteamVR_Action_Vector2\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBValve\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.VR\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
