.TH "SteamVR_Editor" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SteamVR_Editor
.SH SYNOPSIS
.br
.PP
.PP
Inherits Editor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBExportPackage\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file SteamVR_Editor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void SteamVR_Editor\&.ExportPackage ()\fC [static]\fP"

.PP
Definition at line 111 of file SteamVR_Editor\&.cs\&.
.SS "override void SteamVR_Editor\&.OnInspectorGUI ()"

.PP
Definition at line 42 of file SteamVR_Editor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
