.TH "O:/GitHUBMINIPRoject/Assets/SteamVR/Input/SteamVR_Input_Sources.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Assets/SteamVR/Input/SteamVR_Input_Sources.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBValve\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.VR\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.Valve\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.Valve\&.VR\fP"
.br
.ti -1c
.RI "namespace \fBValve\&.Valve\&.VR\&.InputSources\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBValve\&.Valve\&.VR\&.InputSources\&.Sources\fP = SteamVR_Input_Sources"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBValve\&.VR\&.SteamVR_Input_Sources\fP { \fBValve\&.VR\&.SteamVR_Input_Sources\&.Any\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.LeftHand\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.RightHand\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.LeftFoot\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.RightFoot\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.LeftShoulder\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.RightShoulder\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.Waist\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.Chest\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.Head\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.Gamepad\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.Camera\fP, \fBValve\&.VR\&.SteamVR_Input_Sources\&.Keyboard\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
