.TH "textlookout" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textlookout \- This class take care of the player name to be represented over the player By default it will show the network Id set by the network identity manager , but you have an option to change the name from GUI interface and that will be displayed over the network  

.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCmdChange\fP (string tempname)"
.br
.RI "When the player changes his/her name in GUI , and clicks on the change button , this command will be called and the name will be updated over the network\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "NetworkInstanceId \fBPlayerId\fP"
.br
.ti -1c
.RI "string \fBusername\fP"
.br
.ti -1c
.RI "GameObject \fBShowID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class take care of the player name to be represented over the player By default it will show the network Id set by the network identity manager , but you have an option to change the name from GUI interface and that will be displayed over the network 


.PP
Definition at line 10 of file textlookout\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void textlookout\&.CmdChange (string tempname)"

.PP
When the player changes his/her name in GUI , and clicks on the change button , this command will be called and the name will be updated over the network\&. 
.PP
\fBParameters:\fP
.RS 4
\fItempname\fP 
.RE
.PP

.PP
Definition at line 39 of file textlookout\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "NetworkInstanceId textlookout\&.PlayerId"

.PP
Definition at line 12 of file textlookout\&.cs\&.
.SS "GameObject textlookout\&.ShowID"
Stores the player ID in the toString() type 
.PP
Definition at line 15 of file textlookout\&.cs\&.
.SS "string textlookout\&.username"
Stores the played ID , which is set be the network identity manager 
.PP
Definition at line 14 of file textlookout\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
