.TH "O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.textmeshpro@1.3.0/Scripts/Runtime/TextContainer.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.textmeshpro@1.3.0/Scripts/Runtime/TextContainer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTMPro\&.TextContainer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTMPro\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTMPro\&.TextContainerAnchors\fP { \fBTMPro\&.TextContainerAnchors\&.TopLeft\fP = 0, \fBTMPro\&.TextContainerAnchors\&.Top\fP = 1, \fBTMPro\&.TextContainerAnchors\&.TopRight\fP = 2, \fBTMPro\&.TextContainerAnchors\&.Left\fP = 3, \fBTMPro\&.TextContainerAnchors\&.Middle\fP = 4, \fBTMPro\&.TextContainerAnchors\&.Right\fP = 5, \fBTMPro\&.TextContainerAnchors\&.BottomLeft\fP = 6, \fBTMPro\&.TextContainerAnchors\&.Bottom\fP = 7, \fBTMPro\&.TextContainerAnchors\&.BottomRight\fP = 8, \fBTMPro\&.TextContainerAnchors\&.Custom\fP = 9 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
