.TH "O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.textmeshpro@1.3.0/Scripts/Runtime/TMP_SpriteAssetImportFormats.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.textmeshpro@1.3.0/Scripts/Runtime/TMP_SpriteAssetImportFormats.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTMPro\&.SpriteAssetUtilities\&.TexturePacker\fP"
.br
.ti -1c
.RI "struct \fBTMPro\&.SpriteAssetUtilities\&.TexturePacker\&.SpriteFrame\fP"
.br
.ti -1c
.RI "struct \fBTMPro\&.SpriteAssetUtilities\&.TexturePacker\&.SpriteSize\fP"
.br
.ti -1c
.RI "struct \fBTMPro\&.SpriteAssetUtilities\&.TexturePacker\&.SpriteData\fP"
.br
.ti -1c
.RI "class \fBTMPro\&.SpriteAssetUtilities\&.TexturePacker\&.SpriteDataObject\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTMPro\fP"
.br
.ti -1c
.RI "namespace \fBTMPro\&.SpriteAssetUtilities\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTMPro\&.SpriteAssetUtilities\&.SpriteAssetImportFormats\fP { \fBTMPro\&.SpriteAssetUtilities\&.SpriteAssetImportFormats\&.None\fP = 0, \fBTMPro\&.SpriteAssetUtilities\&.SpriteAssetImportFormats\&.TexturePacker\fP = 0x1 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
