.TH "TMPro.TMP_ObjectPool< T >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_ObjectPool< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMP_ObjectPool\fP (UnityAction< T > actionOnGet, UnityAction< T > actionOnRelease)"
.br
.ti -1c
.RI "T \fBGet\fP ()"
.br
.ti -1c
.RI "void \fBRelease\fP (T element)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBcountAll\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBcountActive\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBcountInactive\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fInew()\fP
.PP
Definition at line 9 of file TMP_ObjectPool\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTMPro\&.TMP_ObjectPool\fP< T >\&.\fBTMP_ObjectPool\fP (UnityAction< T > actionOnGet, UnityAction< T > actionOnRelease)"

.PP
Definition at line 19 of file TMP_ObjectPool\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "T \fBTMPro\&.TMP_ObjectPool\fP< T >\&.Get ()"

.PP
Definition at line 25 of file TMP_ObjectPool\&.cs\&.
.SS "void \fBTMPro\&.TMP_ObjectPool\fP< T >\&.Release (T element)"

.PP
Definition at line 42 of file TMP_ObjectPool\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int \fBTMPro\&.TMP_ObjectPool\fP< T >\&.countActive\fC [get]\fP"

.PP
Definition at line 16 of file TMP_ObjectPool\&.cs\&.
.SS "int \fBTMPro\&.TMP_ObjectPool\fP< T >\&.countAll\fC [get]\fP"

.PP
Definition at line 15 of file TMP_ObjectPool\&.cs\&.
.SS "int \fBTMPro\&.TMP_ObjectPool\fP< T >\&.countInactive\fC [get]\fP"

.PP
Definition at line 17 of file TMP_ObjectPool\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
