.TH "TMPro.TextContainer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TextContainer
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIBehaviour\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "override void \fBOnRectTransformDimensionsChange\fP ()"
.br
.RI "Callback from Unity to handle RectTransform changes\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBhasChanged\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Vector2 \fBpivot\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBTextContainerAnchors\fP \fBanchorPosition\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Rect \fBrect\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Vector2 \fBsize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBwidth\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBheight\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisDefaultWidth\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBisDefaultHeight\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBisAutoFitting\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Vector3 [] \fBcorners\fP\fC [get]\fP"
.br
.ti -1c
.RI "Vector3 [] \fBworldCorners\fP\fC [get]\fP"
.br
.ti -1c
.RI "Vector4 \fBmargins\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "RectTransform \fBrectTransform\fP\fC [get]\fP"
.br
.RI "The RectTransform used by the object "
.ti -1c
.RI "\fBTextMeshPro\fP \fBtextMeshPro\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file TextContainer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TMPro\&.TextContainer\&.Awake ()\fC [protected]\fP"

.PP
Definition at line 168 of file TextContainer\&.cs\&.
.SS "override void TMPro\&.TextContainer\&.OnDisable ()\fC [protected]\fP"

.PP

.PP
Definition at line 190 of file TextContainer\&.cs\&.
.SS "override void TMPro\&.TextContainer\&.OnEnable ()\fC [protected]\fP"

.PP

.PP
Definition at line 179 of file TextContainer\&.cs\&.
.SS "override void TMPro\&.TextContainer\&.OnRectTransformDimensionsChange ()\fC [protected]\fP"

.PP
Callback from Unity to handle RectTransform changes\&. 
.PP
Definition at line 247 of file TextContainer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBTextContainerAnchors\fP TMPro\&.TextContainer\&.anchorPosition\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 38 of file TextContainer\&.cs\&.
.SS "Vector3 [] TMPro\&.TextContainer\&.corners\fC [get]\fP"

.PP
Definition at line 104 of file TextContainer\&.cs\&.
.SS "bool TMPro\&.TextContainer\&.hasChanged\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 20 of file TextContainer\&.cs\&.
.SS "float TMPro\&.TextContainer\&.height\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 73 of file TextContainer\&.cs\&.
.SS "bool TMPro\&.TextContainer\&.isAutoFitting\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 95 of file TextContainer\&.cs\&.
.SS "bool TMPro\&.TextContainer\&.isDefaultHeight\fC [get]\fP"

.PP
Definition at line 88 of file TextContainer\&.cs\&.
.SS "bool TMPro\&.TextContainer\&.isDefaultWidth\fC [get]\fP"

.PP
Definition at line 81 of file TextContainer\&.cs\&.
.SS "Vector4 TMPro\&.TextContainer\&.margins\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 126 of file TextContainer\&.cs\&.
.SS "Vector2 TMPro\&.TextContainer\&.pivot\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 29 of file TextContainer\&.cs\&.
.SS "Rect TMPro\&.TextContainer\&.rect\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 48 of file TextContainer\&.cs\&.
.SS "RectTransform TMPro\&.TextContainer\&.rectTransform\fC [get]\fP"

.PP
The RectTransform used by the object 
.PP
Definition at line 138 of file TextContainer\&.cs\&.
.SS "Vector2 TMPro\&.TextContainer\&.size\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 57 of file TextContainer\&.cs\&.
.SS "\fBTextMeshPro\fP TMPro\&.TextContainer\&.textMeshPro\fC [get]\fP"

.PP

.PP
Definition at line 158 of file TextContainer\&.cs\&.
.SS "float TMPro\&.TextContainer\&.width\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 65 of file TextContainer\&.cs\&.
.SS "Vector3 [] TMPro\&.TextContainer\&.worldCorners\fC [get]\fP"

.PP
Definition at line 111 of file TextContainer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
