.TH "TMPro.TMP_DefaultControls.Resources" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_DefaultControls.Resources
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSprite\fP \fBstandard\fP"
.br
.ti -1c
.RI "\fBSprite\fP \fBbackground\fP"
.br
.ti -1c
.RI "\fBSprite\fP \fBinputField\fP"
.br
.ti -1c
.RI "\fBSprite\fP \fBknob\fP"
.br
.ti -1c
.RI "\fBSprite\fP \fBcheckmark\fP"
.br
.ti -1c
.RI "\fBSprite\fP \fBdropdown\fP"
.br
.ti -1c
.RI "\fBSprite\fP \fBmask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file TMP_DefaultControls\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSprite\fP TMPro\&.TMP_DefaultControls\&.Resources\&.background"

.PP
Definition at line 14 of file TMP_DefaultControls\&.cs\&.
.SS "\fBSprite\fP TMPro\&.TMP_DefaultControls\&.Resources\&.checkmark"

.PP
Definition at line 17 of file TMP_DefaultControls\&.cs\&.
.SS "\fBSprite\fP TMPro\&.TMP_DefaultControls\&.Resources\&.dropdown"

.PP
Definition at line 18 of file TMP_DefaultControls\&.cs\&.
.SS "\fBSprite\fP TMPro\&.TMP_DefaultControls\&.Resources\&.inputField"

.PP
Definition at line 15 of file TMP_DefaultControls\&.cs\&.
.SS "\fBSprite\fP TMPro\&.TMP_DefaultControls\&.Resources\&.knob"

.PP
Definition at line 16 of file TMP_DefaultControls\&.cs\&.
.SS "\fBSprite\fP TMPro\&.TMP_DefaultControls\&.Resources\&.mask"

.PP
Definition at line 19 of file TMP_DefaultControls\&.cs\&.
.SS "\fBSprite\fP TMPro\&.TMP_DefaultControls\&.Resources\&.standard"

.PP
Definition at line 13 of file TMP_DefaultControls\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
