.TH "TMPro.TMP_MeshInfo" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_MeshInfo \- Structure which contains the vertex attributes (geometry) of the text object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMP_MeshInfo\fP (Mesh \fBmesh\fP, int size)"
.br
.RI "Function to pre-allocate vertex attributes for a mesh of size X\&. "
.ti -1c
.RI "\fBTMP_MeshInfo\fP (Mesh \fBmesh\fP, int size, bool isVolumetric)"
.br
.RI "Function to pre-allocate vertex attributes for a mesh of size X\&. "
.ti -1c
.RI "void \fBResizeMeshInfo\fP (int size)"
.br
.RI "Function to resized the content of MeshData and re-assign normals, tangents and triangles\&. "
.ti -1c
.RI "void \fBResizeMeshInfo\fP (int size, bool isVolumetric)"
.br
.RI "Function to resized the content of MeshData and re-assign normals, tangents and triangles\&. "
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "Function to clear the vertices while preserving the Triangles, Normals and Tangents\&. "
.ti -1c
.RI "void \fBClear\fP (bool uploadChanges)"
.br
.RI "Function to clear the vertices while preserving the Triangles, Normals and Tangents\&. "
.ti -1c
.RI "void \fBClearUnusedVertices\fP ()"
.br
.RI "Function to clear the vertices while preserving the Triangles, Normals and Tangents\&. "
.ti -1c
.RI "void \fBClearUnusedVertices\fP (int startIndex)"
.br
.RI "Function used to mark unused vertices as degenerate\&. "
.ti -1c
.RI "void \fBClearUnusedVertices\fP (int startIndex, bool updateMesh)"
.br
.RI "Function used to mark unused vertices as degenerate an upload resulting data to the mesh\&. "
.ti -1c
.RI "void \fBSortGeometry\fP (\fBVertexSortingOrder\fP order)"
.br
.ti -1c
.RI "void \fBSortGeometry\fP (IList< int > sortingOrder)"
.br
.RI "Function to rearrange the quads of the text object to change their rendering order\&. "
.ti -1c
.RI "void \fBSwapVertexData\fP (int src, int dst)"
.br
.RI "Method to swap the vertex attributes between src and dst quads\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Mesh \fBmesh\fP"
.br
.ti -1c
.RI "int \fBvertexCount\fP"
.br
.ti -1c
.RI "Vector3 [] \fBvertices\fP"
.br
.ti -1c
.RI "Vector3 [] \fBnormals\fP"
.br
.ti -1c
.RI "Vector4 [] \fBtangents\fP"
.br
.ti -1c
.RI "Vector2 [] \fBuvs0\fP"
.br
.ti -1c
.RI "Vector2 [] \fBuvs2\fP"
.br
.ti -1c
.RI "Color32 [] \fBcolors32\fP"
.br
.ti -1c
.RI "int [] \fBtriangles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure which contains the vertex attributes (geometry) of the text object\&. 


.PP
Definition at line 15 of file TMP_MeshInfo\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMPro\&.TMP_MeshInfo\&.TMP_MeshInfo (Mesh mesh, int size)"

.PP
Function to pre-allocate vertex attributes for a mesh of size X\&. 
.PP
\fBParameters:\fP
.RS 4
\fImesh\fP 
.br
\fIsize\fP 
.RE
.PP

.PP
Definition at line 40 of file TMP_MeshInfo\&.cs\&.
.SS "TMPro\&.TMP_MeshInfo\&.TMP_MeshInfo (Mesh mesh, int size, bool isVolumetric)"

.PP
Function to pre-allocate vertex attributes for a mesh of size X\&. 
.PP
\fBParameters:\fP
.RS 4
\fImesh\fP 
.br
\fIsize\fP 
.br
\fIisVolumetric\fP 
.RE
.PP

.PP
Definition at line 113 of file TMP_MeshInfo\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMPro\&.TMP_MeshInfo\&.Clear ()"

.PP
Function to clear the vertices while preserving the Triangles, Normals and Tangents\&. 
.PP
Definition at line 429 of file TMP_MeshInfo\&.cs\&.
.SS "void TMPro\&.TMP_MeshInfo\&.Clear (bool uploadChanges)"

.PP
Function to clear the vertices while preserving the Triangles, Normals and Tangents\&. 
.PP
Definition at line 444 of file TMP_MeshInfo\&.cs\&.
.SS "void TMPro\&.TMP_MeshInfo\&.ClearUnusedVertices ()"

.PP
Function to clear the vertices while preserving the Triangles, Normals and Tangents\&. 
.PP
Definition at line 459 of file TMP_MeshInfo\&.cs\&.
.SS "void TMPro\&.TMP_MeshInfo\&.ClearUnusedVertices (int startIndex)"

.PP
Function used to mark unused vertices as degenerate\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstartIndex\fP 
.RE
.PP

.PP
Definition at line 472 of file TMP_MeshInfo\&.cs\&.
.SS "void TMPro\&.TMP_MeshInfo\&.ClearUnusedVertices (int startIndex, bool updateMesh)"

.PP
Function used to mark unused vertices as degenerate an upload resulting data to the mesh\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstartIndex\fP 
.RE
.PP

.PP
Definition at line 485 of file TMP_MeshInfo\&.cs\&.
.SS "void TMPro\&.TMP_MeshInfo\&.ResizeMeshInfo (int size)"

.PP
Function to resized the content of MeshData and re-assign normals, tangents and triangles\&. 
.PP
\fBParameters:\fP
.RS 4
\fImeshData\fP 
.br
\fIsize\fP 
.RE
.PP

.PP
Definition at line 232 of file TMP_MeshInfo\&.cs\&.
.SS "void TMPro\&.TMP_MeshInfo\&.ResizeMeshInfo (int size, bool isVolumetric)"

.PP
Function to resized the content of MeshData and re-assign normals, tangents and triangles\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP 
.br
\fIisVolumetric\fP 
.RE
.PP

.PP
Definition at line 302 of file TMP_MeshInfo\&.cs\&.
.SS "void TMPro\&.TMP_MeshInfo\&.SortGeometry (\fBVertexSortingOrder\fP order)"

.PP
Definition at line 497 of file TMP_MeshInfo\&.cs\&.
.SS "void TMPro\&.TMP_MeshInfo\&.SortGeometry (IList< int > sortingOrder)"

.PP
Function to rearrange the quads of the text object to change their rendering order\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsortingOrder\fP 
.RE
.PP

.PP
Definition at line 527 of file TMP_MeshInfo\&.cs\&.
.SS "void TMPro\&.TMP_MeshInfo\&.SwapVertexData (int src, int dst)"

.PP
Method to swap the vertex attributes between src and dst quads\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsrc\fP Index of the first vertex attribute of the source character / quad\&.
.br
\fIdst\fP Index of the first vertex attribute of the destination character / quad\&.
.RE
.PP

.PP
Definition at line 559 of file TMP_MeshInfo\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Color32 [] TMPro\&.TMP_MeshInfo\&.colors32"

.PP
Definition at line 31 of file TMP_MeshInfo\&.cs\&.
.SS "Mesh TMPro\&.TMP_MeshInfo\&.mesh"

.PP
Definition at line 21 of file TMP_MeshInfo\&.cs\&.
.SS "Vector3 [] TMPro\&.TMP_MeshInfo\&.normals"

.PP
Definition at line 25 of file TMP_MeshInfo\&.cs\&.
.SS "Vector4 [] TMPro\&.TMP_MeshInfo\&.tangents"

.PP
Definition at line 26 of file TMP_MeshInfo\&.cs\&.
.SS "int [] TMPro\&.TMP_MeshInfo\&.triangles"

.PP
Definition at line 32 of file TMP_MeshInfo\&.cs\&.
.SS "Vector2 [] TMPro\&.TMP_MeshInfo\&.uvs0"

.PP
Definition at line 28 of file TMP_MeshInfo\&.cs\&.
.SS "Vector2 [] TMPro\&.TMP_MeshInfo\&.uvs2"

.PP
Definition at line 29 of file TMP_MeshInfo\&.cs\&.
.SS "int TMPro\&.TMP_MeshInfo\&.vertexCount"

.PP
Definition at line 22 of file TMP_MeshInfo\&.cs\&.
.SS "Vector3 [] TMPro\&.TMP_MeshInfo\&.vertices"

.PP
Definition at line 24 of file TMP_MeshInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
