.TH "TMPro.TMP_Asset" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_Asset
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.PP
Inherited by \fBTMPro\&.TMP_FontAsset\fP, and \fBTMPro\&.TMP_SpriteAsset\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBhashCode\fP"
.br
.RI "HashCode based on the name of the asset\&. "
.ti -1c
.RI "Material \fBmaterial\fP"
.br
.RI "The material used by this asset\&. "
.ti -1c
.RI "int \fBmaterialHashCode\fP"
.br
.RI "HashCode based on the name of the material assigned to this asset\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file TMP_Asset\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int TMPro\&.TMP_Asset\&.hashCode"

.PP
HashCode based on the name of the asset\&. 
.PP
Definition at line 13 of file TMP_Asset\&.cs\&.
.SS "Material TMPro\&.TMP_Asset\&.material"

.PP
The material used by this asset\&. 
.PP
Definition at line 18 of file TMP_Asset\&.cs\&.
.SS "int TMPro\&.TMP_Asset\&.materialHashCode"

.PP
HashCode based on the name of the material assigned to this asset\&. 
.PP
Definition at line 23 of file TMP_Asset\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
