.TH "TMPro.TMP_PageInfo" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_PageInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfirstCharacterIndex\fP"
.br
.ti -1c
.RI "int \fBlastCharacterIndex\fP"
.br
.ti -1c
.RI "float \fBascender\fP"
.br
.ti -1c
.RI "float \fBbaseLine\fP"
.br
.ti -1c
.RI "float \fBdescender\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 174 of file TMPro_MeshUtilities\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float TMPro\&.TMP_PageInfo\&.ascender"

.PP
Definition at line 178 of file TMPro_MeshUtilities\&.cs\&.
.SS "float TMPro\&.TMP_PageInfo\&.baseLine"

.PP
Definition at line 179 of file TMPro_MeshUtilities\&.cs\&.
.SS "float TMPro\&.TMP_PageInfo\&.descender"

.PP
Definition at line 180 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_PageInfo\&.firstCharacterIndex"

.PP
Definition at line 176 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_PageInfo\&.lastCharacterIndex"

.PP
Definition at line 177 of file TMPro_MeshUtilities\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
