.TH "TMPro.AssetConversionData" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.AssetConversionData \- Data structure containing a list of target and replacement fileID and GUID requiring remapping from previous versions of TextMesh Pro to the new TextMesh Pro UPM package\&. This data structure is populated with the data contained in the PackageConversionData\&.json file included in the package\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBAssetConversionRecord\fP > \fBassetRecords\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data structure containing a list of target and replacement fileID and GUID requiring remapping from previous versions of TextMesh Pro to the new TextMesh Pro UPM package\&. This data structure is populated with the data contained in the PackageConversionData\&.json file included in the package\&. 


.PP
Definition at line 28 of file TMP_PackageUtilities\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBAssetConversionRecord\fP> TMPro\&.AssetConversionData\&.assetRecords"

.PP
Definition at line 30 of file TMP_PackageUtilities\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
