.TH "TMPro.GlyphValueRecord" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.GlyphValueRecord \- Positional adjustments of a glyph  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGlyphValueRecord\fP \fBoperator+\fP (\fBGlyphValueRecord\fP a, \fBGlyphValueRecord\fP b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBxPlacement\fP"
.br
.ti -1c
.RI "float \fByPlacement\fP"
.br
.ti -1c
.RI "float \fBxAdvance\fP"
.br
.ti -1c
.RI "float \fByAdvance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Positional adjustments of a glyph 


.PP
Definition at line 117 of file TMPro_FontUtilities\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBGlyphValueRecord\fP TMPro\&.GlyphValueRecord\&.operator+ (\fBGlyphValueRecord\fP a, \fBGlyphValueRecord\fP b)\fC [static]\fP"

.PP
Definition at line 124 of file TMPro_FontUtilities\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float TMPro\&.GlyphValueRecord\&.xAdvance"

.PP
Definition at line 121 of file TMPro_FontUtilities\&.cs\&.
.SS "float TMPro\&.GlyphValueRecord\&.xPlacement"

.PP
Definition at line 119 of file TMPro_FontUtilities\&.cs\&.
.SS "float TMPro\&.GlyphValueRecord\&.yAdvance"

.PP
Definition at line 122 of file TMPro_FontUtilities\&.cs\&.
.SS "float TMPro\&.GlyphValueRecord\&.yPlacement"

.PP
Definition at line 120 of file TMPro_FontUtilities\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
