.TH "TMPro.EditorUtilities.TMP_BitmapShaderGUI" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.EditorUtilities.TMP_BitmapShaderGUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMPro\&.EditorUtilities\&.TMP_BaseShaderGUI\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDoGUI\fP ()"
.br
.RI "Override this method to create the specific shader GUI\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file TMP_BitmapShaderGUI\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TMPro\&.EditorUtilities\&.TMP_BitmapShaderGUI\&.DoGUI ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this method to create the specific shader GUI\&. 
.PP
Implements \fBTMPro\&.EditorUtilities\&.TMP_BaseShaderGUI\fP\&.
.PP
Definition at line 10 of file TMP_BitmapShaderGUI\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
