.TH "TMPro.TMP_UpdateManager" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_UpdateManager
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRegisterTextElementForLayoutRebuild\fP (\fBTMP_Text\fP element)"
.br
.RI "Function to register elements which require a layout rebuild\&. "
.ti -1c
.RI "static void \fBRegisterTextElementForGraphicRebuild\fP (\fBTMP_Text\fP element)"
.br
.RI "Function to register elements which require a layout rebuild\&. "
.ti -1c
.RI "static void \fBUnRegisterTextElementForRebuild\fP (\fBTMP_Text\fP element)"
.br
.RI "Function to unregister elements which no longer require a rebuild\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTMP_UpdateManager\fP ()"
.br
.RI "Register to receive rendering callbacks\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBTMP_UpdateManager\fP \fBinstance\fP\fC [get]\fP"
.br
.RI "Get a singleton instance of the registry "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file TMP_UpdateManager\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMPro\&.TMP_UpdateManager\&.TMP_UpdateManager ()\fC [protected]\fP"

.PP
Register to receive rendering callbacks\&. 
.PP
Definition at line 43 of file TMP_UpdateManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void TMPro\&.TMP_UpdateManager\&.RegisterTextElementForGraphicRebuild (\fBTMP_Text\fP element)\fC [static]\fP"

.PP
Function to register elements which require a layout rebuild\&. 
.PP
\fBParameters:\fP
.RS 4
\fIelement\fP 
.RE
.PP

.PP
Definition at line 80 of file TMP_UpdateManager\&.cs\&.
.SS "static void TMPro\&.TMP_UpdateManager\&.RegisterTextElementForLayoutRebuild (\fBTMP_Text\fP element)\fC [static]\fP"

.PP
Function to register elements which require a layout rebuild\&. 
.PP
\fBParameters:\fP
.RS 4
\fIelement\fP 
.RE
.PP

.PP
Definition at line 57 of file TMP_UpdateManager\&.cs\&.
.SS "static void TMPro\&.TMP_UpdateManager\&.UnRegisterTextElementForRebuild (\fBTMP_Text\fP element)\fC [static]\fP"

.PP
Function to unregister elements which no longer require a rebuild\&. 
.PP
\fBParameters:\fP
.RS 4
\fIelement\fP 
.RE
.PP

.PP
Definition at line 162 of file TMP_UpdateManager\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBTMP_UpdateManager\fP TMPro\&.TMP_UpdateManager\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Get a singleton instance of the registry 
.PP
Definition at line 30 of file TMP_UpdateManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
