.TH "TMPro.TMP_FontWeights" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_FontWeights \- Contains the font asset for the specified font weight styles\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTMP_FontAsset\fP \fBregularTypeface\fP"
.br
.ti -1c
.RI "\fBTMP_FontAsset\fP \fBitalicTypeface\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the font asset for the specified font weight styles\&. 


.PP
Definition at line 15 of file TMP_FontAsset\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTMP_FontAsset\fP TMPro\&.TMP_FontWeights\&.italicTypeface"

.PP
Definition at line 18 of file TMP_FontAsset\&.cs\&.
.SS "\fBTMP_FontAsset\fP TMPro\&.TMP_FontWeights\&.regularTypeface"

.PP
Definition at line 17 of file TMP_FontAsset\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
