.TH "TMPro.TMP_ScrollbarEventHandler" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_ScrollbarEventHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerClickHandler, ISelectHandler, and IDeselectHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerClick\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnSelect\fP (BaseEventData eventData)"
.br
.ti -1c
.RI "void \fBOnDeselect\fP (BaseEventData eventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisSelected\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file TMP_ScrollbarEventHandler\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMPro\&.TMP_ScrollbarEventHandler\&.OnDeselect (BaseEventData eventData)"

.PP
Definition at line 25 of file TMP_ScrollbarEventHandler\&.cs\&.
.SS "void TMPro\&.TMP_ScrollbarEventHandler\&.OnPointerClick (PointerEventData eventData)"

.PP
Definition at line 14 of file TMP_ScrollbarEventHandler\&.cs\&.
.SS "void TMPro\&.TMP_ScrollbarEventHandler\&.OnSelect (BaseEventData eventData)"

.PP
Definition at line 19 of file TMP_ScrollbarEventHandler\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool TMPro\&.TMP_ScrollbarEventHandler\&.isSelected"

.PP
Definition at line 12 of file TMP_ScrollbarEventHandler\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
