.TH "TMPro.TMP_Style" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_Style
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefreshStyle\fP ()"
.br
.RI "Function to update the content of the int[] resulting from changes to OpeningDefinition & ClosingDefinition\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBname\fP\fC [get, set]\fP"
.br
.RI "The name identifying this style\&. ex\&. <style='name'>\&. "
.ti -1c
.RI "int \fBhashCode\fP\fC [get, set]\fP"
.br
.RI "The hash code corresponding to the name of this style\&. "
.ti -1c
.RI "string \fBstyleOpeningDefinition\fP\fC [get]\fP"
.br
.RI "The initial definition of the style\&. ex\&. \fB \fI\&. \fP\fP"
.ti -1c
.RI "string \fBstyleClosingDefinition\fP\fC [get]\fP"
.br
.RI "The closing definition of the style\&. ex\&.  \&. "
.ti -1c
.RI "int [] \fBstyleOpeningTagArray\fP\fC [get]\fP"
.br
.ti -1c
.RI "int [] \fBstyleClosingTagArray\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file TMP_Style\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMPro\&.TMP_Style\&.RefreshStyle ()"

.PP
Function to update the content of the int[] resulting from changes to OpeningDefinition & ClosingDefinition\&. 
.PP
Definition at line 76 of file TMP_Style\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int TMPro\&.TMP_Style\&.hashCode\fC [get]\fP, \fC [set]\fP"

.PP
The hash code corresponding to the name of this style\&. 
.PP
Definition at line 24 of file TMP_Style\&.cs\&.
.SS "string TMPro\&.TMP_Style\&.name\fC [get]\fP, \fC [set]\fP"

.PP
The name identifying this style\&. ex\&. <style='name'>\&. 
.PP
Definition at line 18 of file TMP_Style\&.cs\&.
.SS "string TMPro\&.TMP_Style\&.styleClosingDefinition\fC [get]\fP"

.PP
The closing definition of the style\&. ex\&.  \&. 
.PP
Definition at line 36 of file TMP_Style\&.cs\&.
.SS "int [] TMPro\&.TMP_Style\&.styleClosingTagArray\fC [get]\fP"

.PP
Definition at line 44 of file TMP_Style\&.cs\&.
.SS "string TMPro\&.TMP_Style\&.styleOpeningDefinition\fC [get]\fP"

.PP
The initial definition of the style\&. ex\&. \fB \fI\&. \fP\fP
.PP
Definition at line 30 of file TMP_Style\&.cs\&.
.SS "int [] TMPro\&.TMP_Style\&.styleOpeningTagArray\fC [get]\fP"

.PP
Definition at line 40 of file TMP_Style\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
