.TH "TMPro.TMP_TextElement" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_TextElement \- Base class for all text elements like characters (glyphs) and sprites\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTMPro\&.TMP_Glyph\fP, and \fBTMPro\&.TMP_Sprite\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBwidth\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.ti -1c
.RI "float \fBxOffset\fP"
.br
.ti -1c
.RI "float \fByOffset\fP"
.br
.ti -1c
.RI "float \fBxAdvance\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for all text elements like characters (glyphs) and sprites\&. 


.PP
Definition at line 13 of file TMP_TextElement\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float TMPro\&.TMP_TextElement\&.height"

.PP
Definition at line 19 of file TMP_TextElement\&.cs\&.
.SS "int TMPro\&.TMP_TextElement\&.id"

.PP
Definition at line 15 of file TMP_TextElement\&.cs\&.
.SS "float TMPro\&.TMP_TextElement\&.scale"

.PP
Definition at line 23 of file TMP_TextElement\&.cs\&.
.SS "float TMPro\&.TMP_TextElement\&.width"

.PP
Definition at line 18 of file TMP_TextElement\&.cs\&.
.SS "float TMPro\&.TMP_TextElement\&.x"

.PP
Definition at line 16 of file TMP_TextElement\&.cs\&.
.SS "float TMPro\&.TMP_TextElement\&.xAdvance"

.PP
Definition at line 22 of file TMP_TextElement\&.cs\&.
.SS "float TMPro\&.TMP_TextElement\&.xOffset"

.PP
Definition at line 20 of file TMP_TextElement\&.cs\&.
.SS "float TMPro\&.TMP_TextElement\&.y"

.PP
Definition at line 17 of file TMP_TextElement\&.cs\&.
.SS "float TMPro\&.TMP_TextElement\&.yOffset"

.PP
Definition at line 21 of file TMP_TextElement\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
