.TH "TMPro.TMP_UpdateRegistry" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_UpdateRegistry \- Class for handling and scheduling text object updates\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRegisterCanvasElementForLayoutRebuild\fP (ICanvasElement element)"
.br
.RI "Function to register elements which require a layout rebuild\&. "
.ti -1c
.RI "static void \fBRegisterCanvasElementForGraphicRebuild\fP (ICanvasElement element)"
.br
.RI "Function to register elements which require a graphic rebuild\&. "
.ti -1c
.RI "static void \fBUnRegisterCanvasElementForRebuild\fP (ICanvasElement element)"
.br
.RI "Function to unregister elements which no longer require a rebuild\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTMP_UpdateRegistry\fP ()"
.br
.RI "Register to receive callback from the Canvas System\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBTMP_UpdateRegistry\fP \fBinstance\fP\fC [get]\fP"
.br
.RI "Get a singleton instance of the registry "
.in -1c
.SH "Detailed Description"
.PP 
Class for handling and scheduling text object updates\&. 


.PP
Definition at line 13 of file TMP_UpdateRegistery\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMPro\&.TMP_UpdateRegistry\&.TMP_UpdateRegistry ()\fC [protected]\fP"

.PP
Register to receive callback from the Canvas System\&. 
.PP
Definition at line 43 of file TMP_UpdateRegistery\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void TMPro\&.TMP_UpdateRegistry\&.RegisterCanvasElementForGraphicRebuild (ICanvasElement element)\fC [static]\fP"

.PP
Function to register elements which require a graphic rebuild\&. 
.PP
\fBParameters:\fP
.RS 4
\fIelement\fP 
.RE
.PP

.PP
Definition at line 77 of file TMP_UpdateRegistery\&.cs\&.
.SS "static void TMPro\&.TMP_UpdateRegistry\&.RegisterCanvasElementForLayoutRebuild (ICanvasElement element)\fC [static]\fP"

.PP
Function to register elements which require a layout rebuild\&. 
.PP
\fBParameters:\fP
.RS 4
\fIelement\fP 
.RE
.PP

.PP
Definition at line 54 of file TMP_UpdateRegistery\&.cs\&.
.SS "static void TMPro\&.TMP_UpdateRegistry\&.UnRegisterCanvasElementForRebuild (ICanvasElement element)\fC [static]\fP"

.PP
Function to unregister elements which no longer require a rebuild\&. 
.PP
\fBParameters:\fP
.RS 4
\fIelement\fP 
.RE
.PP

.PP
Definition at line 152 of file TMP_UpdateRegistery\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBTMP_UpdateRegistry\fP TMPro\&.TMP_UpdateRegistry\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Get a singleton instance of the registry 
.PP
Definition at line 30 of file TMP_UpdateRegistery\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
