.TH "TMPro.SpriteAssetUtilities.TexturePacker.SpriteDataObject" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.SpriteAssetUtilities.TexturePacker.SpriteDataObject
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBSpriteData\fP > \fBframes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file TMP_SpriteAssetImportFormats\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBSpriteData\fP> TMPro\&.SpriteAssetUtilities\&.TexturePacker\&.SpriteDataObject\&.frames"

.PP
Definition at line 56 of file TMP_SpriteAssetImportFormats\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
