.TH "TMPro.TMP_XmlTagStack< T >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_XmlTagStack< T > \- Structure used to track XML tags of various types\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMP_XmlTagStack\fP (T[] tagStack)"
.br
.RI "Constructor to create a new item stack\&. "
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "Function to clear and reset stack to first item\&. "
.ti -1c
.RI "void \fBSetDefault\fP (T item)"
.br
.RI "Function to set the first item on the stack and reset index\&. "
.ti -1c
.RI "void \fBAdd\fP (T item)"
.br
.RI "Function to add a new item to the stack\&. "
.ti -1c
.RI "T \fBRemove\fP ()"
.br
.RI "Function to retrieve an item from the stack\&. "
.ti -1c
.RI "void \fBPush\fP (T item)"
.br
.ti -1c
.RI "T \fBPop\fP ()"
.br
.ti -1c
.RI "T \fBCurrentItem\fP ()"
.br
.RI "Function to retrieve the current item from the stack\&. "
.ti -1c
.RI "T \fBPreviousItem\fP ()"
.br
.RI "Function to retrieve the previous item without affecting the stack\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T [] \fBitemStack\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to track XML tags of various types\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP 
.RE
.PP

.PP
Definition at line 123 of file TMP_XmlTagStack\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTMPro\&.TMP_XmlTagStack\fP< T >\&.\fBTMP_XmlTagStack\fP (T [] tagStack)"

.PP
Constructor to create a new item stack\&. 
.PP
\fBParameters:\fP
.RS 4
\fItagStack\fP 
.RE
.PP

.PP
Definition at line 138 of file TMP_XmlTagStack\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBTMPro\&.TMP_XmlTagStack\fP< T >\&.Add (T item)"

.PP
Function to add a new item to the stack\&. 
.PP
\fBParameters:\fP
.RS 4
\fIitem\fP 
.RE
.PP

.PP
Definition at line 172 of file TMP_XmlTagStack\&.cs\&.
.SS "void \fBTMPro\&.TMP_XmlTagStack\fP< T >\&.Clear ()"

.PP
Function to clear and reset stack to first item\&. 
.PP
Definition at line 151 of file TMP_XmlTagStack\&.cs\&.
.SS "T \fBTMPro\&.TMP_XmlTagStack\fP< T >\&.CurrentItem ()"

.PP
Function to retrieve the current item from the stack\&. 
.PP
\fBReturns:\fP
.RS 4
itemStack <T>
.RE
.PP

.PP
Definition at line 232 of file TMP_XmlTagStack\&.cs\&.
.SS "T \fBTMPro\&.TMP_XmlTagStack\fP< T >\&.Pop ()"

.PP
Definition at line 215 of file TMP_XmlTagStack\&.cs\&.
.SS "T \fBTMPro\&.TMP_XmlTagStack\fP< T >\&.PreviousItem ()"

.PP
Function to retrieve the previous item without affecting the stack\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 245 of file TMP_XmlTagStack\&.cs\&.
.SS "void \fBTMPro\&.TMP_XmlTagStack\fP< T >\&.Push (T item)"

.PP
Definition at line 200 of file TMP_XmlTagStack\&.cs\&.
.SS "T \fBTMPro\&.TMP_XmlTagStack\fP< T >\&.Remove ()"

.PP
Function to retrieve an item from the stack\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 186 of file TMP_XmlTagStack\&.cs\&.
.SS "void \fBTMPro\&.TMP_XmlTagStack\fP< T >\&.SetDefault (T item)"

.PP
Function to set the first item on the stack and reset index\&. 
.PP
\fBParameters:\fP
.RS 4
\fIitem\fP 
.RE
.PP

.PP
Definition at line 161 of file TMP_XmlTagStack\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBTMPro\&.TMP_XmlTagStack\fP< T >\&.index"

.PP
Definition at line 126 of file TMP_XmlTagStack\&.cs\&.
.SS "T [] \fBTMPro\&.TMP_XmlTagStack\fP< T >\&.itemStack"

.PP
Definition at line 125 of file TMP_XmlTagStack\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
