.TH "TMPro.EditorUtilities.TMP_BaseShaderGUI.ShaderFeature" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.EditorUtilities.TMP_BaseShaderGUI.ShaderFeature \- Representation of a #pragma shader_feature\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReadState\fP (Material material)"
.br
.ti -1c
.RI "void \fBSetActive\fP (bool active, Material material)"
.br
.ti -1c
.RI "void \fBDoPopup\fP (MaterialEditor editor, Material material)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBundoLabel\fP"
.br
.ti -1c
.RI "GUIContent \fBlabel\fP"
.br
.ti -1c
.RI "GUIContent [] \fBkeywordLabels\fP"
.br
.RI "The keyword labels, for display\&. Include the no-keyword as the first option\&. "
.ti -1c
.RI "string [] \fBkeywords\fP"
.br
.RI "The shader keywords\&. Exclude the no-keyword option\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBActive\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBState\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Representation of a #pragma shader_feature\&. 

It is assumed that the first feature option is for no keyword (underscores)\&. 
.PP
Definition at line 11 of file TMP_BaseShaderGUI\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMPro\&.EditorUtilities\&.TMP_BaseShaderGUI\&.ShaderFeature\&.DoPopup (MaterialEditor editor, Material material)"

.PP
Definition at line 55 of file TMP_BaseShaderGUI\&.cs\&.
.SS "void TMPro\&.EditorUtilities\&.TMP_BaseShaderGUI\&.ShaderFeature\&.ReadState (Material material)"

.PP
Definition at line 35 of file TMP_BaseShaderGUI\&.cs\&.
.SS "void TMPro\&.EditorUtilities\&.TMP_BaseShaderGUI\&.ShaderFeature\&.SetActive (bool active, Material material)"

.PP
Definition at line 49 of file TMP_BaseShaderGUI\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "GUIContent [] TMPro\&.EditorUtilities\&.TMP_BaseShaderGUI\&.ShaderFeature\&.keywordLabels"

.PP
The keyword labels, for display\&. Include the no-keyword as the first option\&. 
.PP
Definition at line 18 of file TMP_BaseShaderGUI\&.cs\&.
.SS "string [] TMPro\&.EditorUtilities\&.TMP_BaseShaderGUI\&.ShaderFeature\&.keywords"

.PP
The shader keywords\&. Exclude the no-keyword option\&. 
.PP
Definition at line 21 of file TMP_BaseShaderGUI\&.cs\&.
.SS "GUIContent TMPro\&.EditorUtilities\&.TMP_BaseShaderGUI\&.ShaderFeature\&.label"

.PP
Definition at line 15 of file TMP_BaseShaderGUI\&.cs\&.
.SS "string TMPro\&.EditorUtilities\&.TMP_BaseShaderGUI\&.ShaderFeature\&.undoLabel"

.PP
Definition at line 13 of file TMP_BaseShaderGUI\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool TMPro\&.EditorUtilities\&.TMP_BaseShaderGUI\&.ShaderFeature\&.Active\fC [get]\fP"

.PP
Definition at line 26 of file TMP_BaseShaderGUI\&.cs\&.
.SS "int TMPro\&.EditorUtilities\&.TMP_BaseShaderGUI\&.ShaderFeature\&.State\fC [get]\fP"

.PP
Definition at line 31 of file TMP_BaseShaderGUI\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
