.TH "TMPro.TweenRunner< T >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TweenRunner< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (MonoBehaviour coroutineContainer)"
.br
.ti -1c
.RI "void \fBStartTween\fP (T info)"
.br
.ti -1c
.RI "void \fBStopTween\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "MonoBehaviour \fBm_CoroutineContainer\fP"
.br
.ti -1c
.RI "IEnumerator \fBm_Tween\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fIstruct\fP
.TP
\fIT\fP : \fI\fBITweenValue\fP\fP
.PP
Definition at line 190 of file TMP_CoroutineTween\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBTMPro\&.TweenRunner\fP< T >\&.Init (MonoBehaviour coroutineContainer)"

.PP
Definition at line 212 of file TMP_CoroutineTween\&.cs\&.
.SS "void \fBTMPro\&.TweenRunner\fP< T >\&.StartTween (T info)"

.PP
Definition at line 217 of file TMP_CoroutineTween\&.cs\&.
.SS "void \fBTMPro\&.TweenRunner\fP< T >\&.StopTween ()"

.PP
Definition at line 237 of file TMP_CoroutineTween\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "MonoBehaviour \fBTMPro\&.TweenRunner\fP< T >\&.m_CoroutineContainer\fC [protected]\fP"

.PP
Definition at line 192 of file TMP_CoroutineTween\&.cs\&.
.SS "IEnumerator \fBTMPro\&.TweenRunner\fP< T >\&.m_Tween\fC [protected]\fP"

.PP
Definition at line 193 of file TMP_CoroutineTween\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
