.TH "TMPro.TMP_Settings.LineBreakingTable" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_Settings.LineBreakingTable
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< int, char > \fBleadingCharacters\fP"
.br
.ti -1c
.RI "Dictionary< int, char > \fBfollowingCharacters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 414 of file TMP_Settings\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<int, char> TMPro\&.TMP_Settings\&.LineBreakingTable\&.followingCharacters"

.PP
Definition at line 417 of file TMP_Settings\&.cs\&.
.SS "Dictionary<int, char> TMPro\&.TMP_Settings\&.LineBreakingTable\&.leadingCharacters"

.PP
Definition at line 416 of file TMP_Settings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
