.TH "TMPro.EditorUtilities.StyleDrawer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.EditorUtilities.StyleDrawer
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyDrawer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override float \fBGetPropertyHeight\fP (SerializedProperty property, GUIContent label)"
.br
.ti -1c
.RI "override void \fBOnGUI\fP (Rect position, SerializedProperty property, GUIContent label)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly float \fBheight\fP = 95f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file TMP_StyleSheetEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override float TMPro\&.EditorUtilities\&.StyleDrawer\&.GetPropertyHeight (SerializedProperty property, GUIContent label)"

.PP
Definition at line 13 of file TMP_StyleSheetEditor\&.cs\&.
.SS "override void TMPro\&.EditorUtilities\&.StyleDrawer\&.OnGUI (Rect position, SerializedProperty property, GUIContent label)"

.PP
Definition at line 18 of file TMP_StyleSheetEditor\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly float TMPro\&.EditorUtilities\&.StyleDrawer\&.height = 95f\fC [static]\fP"

.PP
Definition at line 11 of file TMP_StyleSheetEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
