.TH "TMPro.TMP_CharacterInfo" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_CharacterInfo \- TMP custom data type to represent 32 bit characters\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBcharacter\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.RI "Index of the character in the raw string\&. "
.ti -1c
.RI "\fBTMP_TextElementType\fP \fBelementType\fP"
.br
.ti -1c
.RI "\fBTMP_TextElement\fP \fBtextElement\fP"
.br
.ti -1c
.RI "\fBTMP_FontAsset\fP \fBfontAsset\fP"
.br
.ti -1c
.RI "\fBTMP_SpriteAsset\fP \fBspriteAsset\fP"
.br
.ti -1c
.RI "int \fBspriteIndex\fP"
.br
.ti -1c
.RI "Material \fBmaterial\fP"
.br
.ti -1c
.RI "int \fBmaterialReferenceIndex\fP"
.br
.ti -1c
.RI "bool \fBisUsingAlternateTypeface\fP"
.br
.ti -1c
.RI "float \fBpointSize\fP"
.br
.ti -1c
.RI "int \fBlineNumber\fP"
.br
.ti -1c
.RI "int \fBpageNumber\fP"
.br
.ti -1c
.RI "int \fBvertexIndex\fP"
.br
.ti -1c
.RI "\fBTMP_Vertex\fP \fBvertex_TL\fP"
.br
.ti -1c
.RI "\fBTMP_Vertex\fP \fBvertex_BL\fP"
.br
.ti -1c
.RI "\fBTMP_Vertex\fP \fBvertex_TR\fP"
.br
.ti -1c
.RI "\fBTMP_Vertex\fP \fBvertex_BR\fP"
.br
.ti -1c
.RI "Vector3 \fBtopLeft\fP"
.br
.ti -1c
.RI "Vector3 \fBbottomLeft\fP"
.br
.ti -1c
.RI "Vector3 \fBtopRight\fP"
.br
.ti -1c
.RI "Vector3 \fBbottomRight\fP"
.br
.ti -1c
.RI "float \fBorigin\fP"
.br
.ti -1c
.RI "float \fBascender\fP"
.br
.ti -1c
.RI "float \fBbaseLine\fP"
.br
.ti -1c
.RI "float \fBdescender\fP"
.br
.ti -1c
.RI "float \fBxAdvance\fP"
.br
.ti -1c
.RI "float \fBaspectRatio\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "Color32 \fBcolor\fP"
.br
.ti -1c
.RI "Color32 \fBunderlineColor\fP"
.br
.ti -1c
.RI "Color32 \fBstrikethroughColor\fP"
.br
.ti -1c
.RI "Color32 \fBhighlightColor\fP"
.br
.ti -1c
.RI "\fBFontStyles\fP \fBstyle\fP"
.br
.ti -1c
.RI "bool \fBisVisible\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TMP custom data type to represent 32 bit characters\&. 

Structure containing information about individual text elements (character or sprites)\&. 
.PP
Definition at line 66 of file TMPro_MeshUtilities\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float TMPro\&.TMP_CharacterInfo\&.ascender"

.PP
Definition at line 102 of file TMPro_MeshUtilities\&.cs\&.
.SS "float TMPro\&.TMP_CharacterInfo\&.aspectRatio"

.PP
Definition at line 107 of file TMPro_MeshUtilities\&.cs\&.
.SS "float TMPro\&.TMP_CharacterInfo\&.baseLine"

.PP
Definition at line 103 of file TMPro_MeshUtilities\&.cs\&.
.SS "Vector3 TMPro\&.TMP_CharacterInfo\&.bottomLeft"

.PP
Definition at line 98 of file TMPro_MeshUtilities\&.cs\&.
.SS "Vector3 TMPro\&.TMP_CharacterInfo\&.bottomRight"

.PP
Definition at line 100 of file TMPro_MeshUtilities\&.cs\&.
.SS "char TMPro\&.TMP_CharacterInfo\&.character"

.PP
Definition at line 68 of file TMPro_MeshUtilities\&.cs\&.
.SS "Color32 TMPro\&.TMP_CharacterInfo\&.color"

.PP
Definition at line 109 of file TMPro_MeshUtilities\&.cs\&.
.SS "float TMPro\&.TMP_CharacterInfo\&.descender"

.PP
Definition at line 104 of file TMPro_MeshUtilities\&.cs\&.
.SS "\fBTMP_TextElementType\fP TMPro\&.TMP_CharacterInfo\&.elementType"

.PP
Definition at line 73 of file TMPro_MeshUtilities\&.cs\&.
.SS "\fBTMP_FontAsset\fP TMPro\&.TMP_CharacterInfo\&.fontAsset"

.PP
Definition at line 76 of file TMPro_MeshUtilities\&.cs\&.
.SS "Color32 TMPro\&.TMP_CharacterInfo\&.highlightColor"

.PP
Definition at line 112 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_CharacterInfo\&.index"

.PP
Index of the character in the raw string\&. 
.PP
Definition at line 72 of file TMPro_MeshUtilities\&.cs\&.
.SS "bool TMPro\&.TMP_CharacterInfo\&.isUsingAlternateTypeface"

.PP
Definition at line 81 of file TMPro_MeshUtilities\&.cs\&.
.SS "bool TMPro\&.TMP_CharacterInfo\&.isVisible"

.PP
Definition at line 114 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_CharacterInfo\&.lineNumber"

.PP
Definition at line 86 of file TMPro_MeshUtilities\&.cs\&.
.SS "Material TMPro\&.TMP_CharacterInfo\&.material"

.PP
Definition at line 79 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_CharacterInfo\&.materialReferenceIndex"

.PP
Definition at line 80 of file TMPro_MeshUtilities\&.cs\&.
.SS "float TMPro\&.TMP_CharacterInfo\&.origin"

.PP
Definition at line 101 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_CharacterInfo\&.pageNumber"

.PP
Definition at line 88 of file TMPro_MeshUtilities\&.cs\&.
.SS "float TMPro\&.TMP_CharacterInfo\&.pointSize"

.PP
Definition at line 83 of file TMPro_MeshUtilities\&.cs\&.
.SS "float TMPro\&.TMP_CharacterInfo\&.scale"

.PP
Definition at line 108 of file TMPro_MeshUtilities\&.cs\&.
.SS "\fBTMP_SpriteAsset\fP TMPro\&.TMP_CharacterInfo\&.spriteAsset"

.PP
Definition at line 77 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_CharacterInfo\&.spriteIndex"

.PP
Definition at line 78 of file TMPro_MeshUtilities\&.cs\&.
.SS "Color32 TMPro\&.TMP_CharacterInfo\&.strikethroughColor"

.PP
Definition at line 111 of file TMPro_MeshUtilities\&.cs\&.
.SS "\fBFontStyles\fP TMPro\&.TMP_CharacterInfo\&.style"

.PP
Definition at line 113 of file TMPro_MeshUtilities\&.cs\&.
.SS "\fBTMP_TextElement\fP TMPro\&.TMP_CharacterInfo\&.textElement"

.PP
Definition at line 75 of file TMPro_MeshUtilities\&.cs\&.
.SS "Vector3 TMPro\&.TMP_CharacterInfo\&.topLeft"

.PP
Definition at line 97 of file TMPro_MeshUtilities\&.cs\&.
.SS "Vector3 TMPro\&.TMP_CharacterInfo\&.topRight"

.PP
Definition at line 99 of file TMPro_MeshUtilities\&.cs\&.
.SS "Color32 TMPro\&.TMP_CharacterInfo\&.underlineColor"

.PP
Definition at line 110 of file TMPro_MeshUtilities\&.cs\&.
.SS "\fBTMP_Vertex\fP TMPro\&.TMP_CharacterInfo\&.vertex_BL"

.PP
Definition at line 93 of file TMPro_MeshUtilities\&.cs\&.
.SS "\fBTMP_Vertex\fP TMPro\&.TMP_CharacterInfo\&.vertex_BR"

.PP
Definition at line 95 of file TMPro_MeshUtilities\&.cs\&.
.SS "\fBTMP_Vertex\fP TMPro\&.TMP_CharacterInfo\&.vertex_TL"

.PP
Definition at line 92 of file TMPro_MeshUtilities\&.cs\&.
.SS "\fBTMP_Vertex\fP TMPro\&.TMP_CharacterInfo\&.vertex_TR"

.PP
Definition at line 94 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_CharacterInfo\&.vertexIndex"

.PP
Definition at line 91 of file TMPro_MeshUtilities\&.cs\&.
.SS "float TMPro\&.TMP_CharacterInfo\&.xAdvance"

.PP
Definition at line 106 of file TMPro_MeshUtilities\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
