.TH "TMPro.TMP_BasicXmlTagStack" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_BasicXmlTagStack \- Structure used to track basic XML tags which are binary (on / off)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "Clear the basic XML tag stack\&. "
.ti -1c
.RI "byte \fBAdd\fP (\fBFontStyles\fP style)"
.br
.ti -1c
.RI "byte \fBRemove\fP (\fBFontStyles\fP style)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBbold\fP"
.br
.ti -1c
.RI "byte \fBitalic\fP"
.br
.ti -1c
.RI "byte \fBunderline\fP"
.br
.ti -1c
.RI "byte \fBstrikethrough\fP"
.br
.ti -1c
.RI "byte \fBhighlight\fP"
.br
.ti -1c
.RI "byte \fBsuperscript\fP"
.br
.ti -1c
.RI "byte \fBsubscript\fP"
.br
.ti -1c
.RI "byte \fBuppercase\fP"
.br
.ti -1c
.RI "byte \fBlowercase\fP"
.br
.ti -1c
.RI "byte \fBsmallcaps\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to track basic XML tags which are binary (on / off) 


.PP
Definition at line 6 of file TMP_XmlTagStack\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.Add (\fBFontStyles\fP style)"

.PP
Definition at line 36 of file TMP_XmlTagStack\&.cs\&.
.SS "void TMPro\&.TMP_BasicXmlTagStack\&.Clear ()"

.PP
Clear the basic XML tag stack\&. 
.PP
Definition at line 22 of file TMP_XmlTagStack\&.cs\&.
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.Remove (\fBFontStyles\fP style)"

.PP
Definition at line 66 of file TMP_XmlTagStack\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.bold"

.PP
Definition at line 8 of file TMP_XmlTagStack\&.cs\&.
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.highlight"

.PP
Definition at line 12 of file TMP_XmlTagStack\&.cs\&.
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.italic"

.PP
Definition at line 9 of file TMP_XmlTagStack\&.cs\&.
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.lowercase"

.PP
Definition at line 16 of file TMP_XmlTagStack\&.cs\&.
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.smallcaps"

.PP
Definition at line 17 of file TMP_XmlTagStack\&.cs\&.
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.strikethrough"

.PP
Definition at line 11 of file TMP_XmlTagStack\&.cs\&.
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.subscript"

.PP
Definition at line 14 of file TMP_XmlTagStack\&.cs\&.
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.superscript"

.PP
Definition at line 13 of file TMP_XmlTagStack\&.cs\&.
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.underline"

.PP
Definition at line 10 of file TMP_XmlTagStack\&.cs\&.
.SS "byte TMPro\&.TMP_BasicXmlTagStack\&.uppercase"

.PP
Definition at line 15 of file TMP_XmlTagStack\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
