.TH "TMPro.MaterialReferenceManager" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.MaterialReferenceManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBContains\fP (\fBTMP_FontAsset\fP font)"
.br
.RI "Add new material reference and return the index of this new reference in the materialReferences array\&. "
.ti -1c
.RI "bool \fBContains\fP (\fBTMP_SpriteAsset\fP sprite)"
.br
.RI "Function to check if the sprite asset is already referenced\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAddFontAsset\fP (\fBTMP_FontAsset\fP fontAsset)"
.br
.RI "Add new font asset reference to dictionary\&. "
.ti -1c
.RI "static void \fBAddSpriteAsset\fP (\fBTMP_SpriteAsset\fP spriteAsset)"
.br
.RI "Add new Sprite Asset to dictionary\&. "
.ti -1c
.RI "static void \fBAddSpriteAsset\fP (int hashCode, \fBTMP_SpriteAsset\fP spriteAsset)"
.br
.RI "Add new Sprite Asset to dictionary\&. "
.ti -1c
.RI "static void \fBAddFontMaterial\fP (int hashCode, Material material)"
.br
.RI "Add new Material reference to dictionary\&. "
.ti -1c
.RI "static void \fBAddColorGradientPreset\fP (int hashCode, \fBTMP_ColorGradient\fP spriteAsset)"
.br
.RI "Add new Color Gradient Preset to dictionary\&. "
.ti -1c
.RI "static bool \fBTryGetFontAsset\fP (int hashCode, out \fBTMP_FontAsset\fP fontAsset)"
.br
.RI "Function returning the Font Asset corresponding to the provided hash code\&. "
.ti -1c
.RI "static bool \fBTryGetSpriteAsset\fP (int hashCode, out \fBTMP_SpriteAsset\fP spriteAsset)"
.br
.RI "Function returning the Sprite Asset corresponding to the provided hash code\&. "
.ti -1c
.RI "static bool \fBTryGetColorGradientPreset\fP (int hashCode, out \fBTMP_ColorGradient\fP gradientPreset)"
.br
.RI "Function returning the Color Gradient Preset corresponding to the provided hash code\&. "
.ti -1c
.RI "static bool \fBTryGetMaterial\fP (int hashCode, out Material material)"
.br
.RI "Function returning the Font Material corresponding to the provided hash code\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBMaterialReferenceManager\fP \fBinstance\fP\fC [get]\fP"
.br
.RI "Get a singleton instance of the registry "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file MaterialReferenceManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void TMPro\&.MaterialReferenceManager\&.AddColorGradientPreset (int hashCode, \fBTMP_ColorGradient\fP spriteAsset)\fC [static]\fP"

.PP
Add new Color Gradient Preset to dictionary\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhashCode\fP 
.br
\fIspriteAsset\fP 
.RE
.PP

.PP
Definition at line 145 of file MaterialReferenceManager\&.cs\&.
.SS "static void TMPro\&.MaterialReferenceManager\&.AddFontAsset (\fBTMP_FontAsset\fP fontAsset)\fC [static]\fP"

.PP
Add new font asset reference to dictionary\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfontAsset\fP 
.RE
.PP

.PP
Definition at line 39 of file MaterialReferenceManager\&.cs\&.
.SS "static void TMPro\&.MaterialReferenceManager\&.AddFontMaterial (int hashCode, Material material)\fC [static]\fP"

.PP
Add new Material reference to dictionary\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhashCode\fP 
.br
\fImaterial\fP 
.RE
.PP

.PP
Definition at line 122 of file MaterialReferenceManager\&.cs\&.
.SS "static void TMPro\&.MaterialReferenceManager\&.AddSpriteAsset (\fBTMP_SpriteAsset\fP spriteAsset)\fC [static]\fP"

.PP
Add new Sprite Asset to dictionary\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhashCode\fP 
.br
\fIspriteAsset\fP 
.RE
.PP

.PP
Definition at line 66 of file MaterialReferenceManager\&.cs\&.
.SS "static void TMPro\&.MaterialReferenceManager\&.AddSpriteAsset (int hashCode, \fBTMP_SpriteAsset\fP spriteAsset)\fC [static]\fP"

.PP
Add new Sprite Asset to dictionary\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhashCode\fP 
.br
\fIspriteAsset\fP 
.RE
.PP

.PP
Definition at line 92 of file MaterialReferenceManager\&.cs\&.
.SS "bool TMPro\&.MaterialReferenceManager\&.Contains (\fBTMP_FontAsset\fP font)"

.PP
Add new material reference and return the index of this new reference in the materialReferences array\&. 
.PP
\fBParameters:\fP
.RS 4
\fImaterial\fP 
.br
\fImaterialHashCode\fP 
.br
\fIfontAsset\fP 
.RE
.PP
.PP
Add new material reference and return the index of this new reference in the materialReferences array\&. 
.PP
\fBParameters:\fP
.RS 4
\fImaterial\fP 
.br
\fImaterialHashCode\fP 
.br
\fIspriteAsset\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
.PP
Function to check if the font asset is already referenced\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfont\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 247 of file MaterialReferenceManager\&.cs\&.
.SS "bool TMPro\&.MaterialReferenceManager\&.Contains (\fBTMP_SpriteAsset\fP sprite)"

.PP
Function to check if the sprite asset is already referenced\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfont\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 261 of file MaterialReferenceManager\&.cs\&.
.SS "static bool TMPro\&.MaterialReferenceManager\&.TryGetColorGradientPreset (int hashCode, out \fBTMP_ColorGradient\fP gradientPreset)\fC [static]\fP"

.PP
Function returning the Color Gradient Preset corresponding to the provided hash code\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhashCode\fP 
.br
\fIgradientPreset\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 338 of file MaterialReferenceManager\&.cs\&.
.SS "static bool TMPro\&.MaterialReferenceManager\&.TryGetFontAsset (int hashCode, out \fBTMP_FontAsset\fP fontAsset)\fC [static]\fP"

.PP
Function returning the Font Asset corresponding to the provided hash code\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhashCode\fP 
.br
\fIfontAsset\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 277 of file MaterialReferenceManager\&.cs\&.
.SS "static bool TMPro\&.MaterialReferenceManager\&.TryGetMaterial (int hashCode, out Material material)\fC [static]\fP"

.PP
Function returning the Font Material corresponding to the provided hash code\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhashCode\fP 
.br
\fImaterial\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 368 of file MaterialReferenceManager\&.cs\&.
.SS "static bool TMPro\&.MaterialReferenceManager\&.TryGetSpriteAsset (int hashCode, out \fBTMP_SpriteAsset\fP spriteAsset)\fC [static]\fP"

.PP
Function returning the Sprite Asset corresponding to the provided hash code\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhashCode\fP 
.br
\fIspriteAsset\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 308 of file MaterialReferenceManager\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBMaterialReferenceManager\fP TMPro\&.MaterialReferenceManager\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Get a singleton instance of the registry 
.PP
Definition at line 24 of file MaterialReferenceManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
