.TH "TMPro.TMP_LinkInfo" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_LinkInfo \- Structure containing information about individual links contained in the text object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal void \fBSetLinkID\fP (char[] text, int startIndex, int length)"
.br
.ti -1c
.RI "string \fBGetLinkText\fP ()"
.br
.RI "Function which returns the text contained in a link\&. "
.ti -1c
.RI "string \fBGetLinkID\fP ()"
.br
.RI "Function which returns the link ID as a string\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTMP_Text\fP \fBtextComponent\fP"
.br
.ti -1c
.RI "int \fBhashCode\fP"
.br
.ti -1c
.RI "int \fBlinkIdFirstCharacterIndex\fP"
.br
.ti -1c
.RI "int \fBlinkIdLength\fP"
.br
.ti -1c
.RI "int \fBlinkTextfirstCharacterIndex\fP"
.br
.ti -1c
.RI "int \fBlinkTextLength\fP"
.br
.ti -1c
.RI "internal char [] \fBlinkID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure containing information about individual links contained in the text object\&. 


.PP
Definition at line 188 of file TMPro_MeshUtilities\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string TMPro\&.TMP_LinkInfo\&.GetLinkID ()"

.PP
Function which returns the link ID as a string\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP The source input text\&.
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 232 of file TMPro_MeshUtilities\&.cs\&.
.SS "string TMPro\&.TMP_LinkInfo\&.GetLinkText ()"

.PP
Function which returns the text contained in a link\&. 
.PP
\fBParameters:\fP
.RS 4
\fItextInfo\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 215 of file TMPro_MeshUtilities\&.cs\&.
.SS "internal void TMPro\&.TMP_LinkInfo\&.SetLinkID (char [] text, int startIndex, int length)"

.PP
Definition at line 202 of file TMPro_MeshUtilities\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int TMPro\&.TMP_LinkInfo\&.hashCode"

.PP
Definition at line 192 of file TMPro_MeshUtilities\&.cs\&.
.SS "internal char [] TMPro\&.TMP_LinkInfo\&.linkID"

.PP
Definition at line 199 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_LinkInfo\&.linkIdFirstCharacterIndex"

.PP
Definition at line 194 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_LinkInfo\&.linkIdLength"

.PP
Definition at line 195 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_LinkInfo\&.linkTextfirstCharacterIndex"

.PP
Definition at line 196 of file TMPro_MeshUtilities\&.cs\&.
.SS "int TMPro\&.TMP_LinkInfo\&.linkTextLength"

.PP
Definition at line 197 of file TMPro_MeshUtilities\&.cs\&.
.SS "\fBTMP_Text\fP TMPro\&.TMP_LinkInfo\&.textComponent"

.PP
Definition at line 190 of file TMPro_MeshUtilities\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
