.TH "TMPro.TMP_Dropdown" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_Dropdown
.SH SYNOPSIS
.br
.PP
.PP
Inherits Selectable, IPointerClickHandler, ISubmitHandler, and ICancelHandler\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDropdownEvent\fP"
.br
.ti -1c
.RI "class \fBDropdownItem\fP"
.br
.ti -1c
.RI "class \fBOptionData\fP"
.br
.ti -1c
.RI "class \fBOptionDataList\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefreshShownValue\fP ()"
.br
.ti -1c
.RI "void \fBAddOptions\fP (List< \fBOptionData\fP > \fBoptions\fP)"
.br
.ti -1c
.RI "void \fBAddOptions\fP (List< string > \fBoptions\fP)"
.br
.ti -1c
.RI "void \fBAddOptions\fP (List< \fBSprite\fP > \fBoptions\fP)"
.br
.ti -1c
.RI "void \fBClearOptions\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnPointerClick\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "virtual void \fBOnSubmit\fP (BaseEventData eventData)"
.br
.ti -1c
.RI "virtual void \fBOnCancel\fP (BaseEventData eventData)"
.br
.ti -1c
.RI "void \fBShow\fP ()"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTMP_Dropdown\fP ()"
.br
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.ti -1c
.RI "virtual GameObject \fBCreateBlocker\fP (Canvas rootCanvas)"
.br
.ti -1c
.RI "virtual void \fBDestroyBlocker\fP (GameObject blocker)"
.br
.ti -1c
.RI "virtual GameObject \fBCreateDropdownList\fP (GameObject \fBtemplate\fP)"
.br
.ti -1c
.RI "virtual void \fBDestroyDropdownList\fP (GameObject dropdownList)"
.br
.ti -1c
.RI "virtual \fBDropdownItem\fP \fBCreateItem\fP (\fBDropdownItem\fP itemTemplate)"
.br
.ti -1c
.RI "virtual void \fBDestroyItem\fP (\fBDropdownItem\fP item)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "RectTransform \fBtemplate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBTMP_Text\fP \fBcaptionText\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Image \fBcaptionImage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBTMP_Text\fP \fBitemText\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Image \fBitemImage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "List< \fBOptionData\fP > \fBoptions\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBDropdownEvent\fP \fBonValueChanged\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBvalue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsExpanded\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file TMP_Dropdown\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMPro\&.TMP_Dropdown\&.TMP_Dropdown ()\fC [protected]\fP"

.PP
Definition at line 173 of file TMP_Dropdown\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMPro\&.TMP_Dropdown\&.AddOptions (List< \fBOptionData\fP > options)"

.PP
Definition at line 230 of file TMP_Dropdown\&.cs\&.
.SS "void TMPro\&.TMP_Dropdown\&.AddOptions (List< string > options)"

.PP
Definition at line 236 of file TMP_Dropdown\&.cs\&.
.SS "void TMPro\&.TMP_Dropdown\&.AddOptions (List< \fBSprite\fP > options)"

.PP
Definition at line 243 of file TMP_Dropdown\&.cs\&.
.SS "override void TMPro\&.TMP_Dropdown\&.Awake ()\fC [protected]\fP"

.PP
Definition at line 176 of file TMP_Dropdown\&.cs\&.
.SS "void TMPro\&.TMP_Dropdown\&.ClearOptions ()"

.PP
Definition at line 250 of file TMP_Dropdown\&.cs\&.
.SS "virtual GameObject TMPro\&.TMP_Dropdown\&.CreateBlocker (Canvas rootCanvas)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 484 of file TMP_Dropdown\&.cs\&.
.SS "virtual GameObject TMPro\&.TMP_Dropdown\&.CreateDropdownList (GameObject template)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 522 of file TMP_Dropdown\&.cs\&.
.SS "virtual \fBDropdownItem\fP TMPro\&.TMP_Dropdown\&.CreateItem (\fBDropdownItem\fP itemTemplate)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 532 of file TMP_Dropdown\&.cs\&.
.SS "virtual void TMPro\&.TMP_Dropdown\&.DestroyBlocker (GameObject blocker)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 517 of file TMP_Dropdown\&.cs\&.
.SS "virtual void TMPro\&.TMP_Dropdown\&.DestroyDropdownList (GameObject dropdownList)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 527 of file TMP_Dropdown\&.cs\&.
.SS "virtual void TMPro\&.TMP_Dropdown\&.DestroyItem (\fBDropdownItem\fP item)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 537 of file TMP_Dropdown\&.cs\&.
.SS "void TMPro\&.TMP_Dropdown\&.Hide ()"

.PP
Definition at line 596 of file TMP_Dropdown\&.cs\&.
.SS "virtual void TMPro\&.TMP_Dropdown\&.OnCancel (BaseEventData eventData)\fC [virtual]\fP"

.PP
Definition at line 333 of file TMP_Dropdown\&.cs\&.
.SS "virtual void TMPro\&.TMP_Dropdown\&.OnPointerClick (PointerEventData eventData)\fC [virtual]\fP"

.PP
Definition at line 323 of file TMP_Dropdown\&.cs\&.
.SS "virtual void TMPro\&.TMP_Dropdown\&.OnSubmit (BaseEventData eventData)\fC [virtual]\fP"

.PP
Definition at line 328 of file TMP_Dropdown\&.cs\&.
.SS "void TMPro\&.TMP_Dropdown\&.RefreshShownValue ()"

.PP
Definition at line 205 of file TMP_Dropdown\&.cs\&.
.SS "void TMPro\&.TMP_Dropdown\&.Show ()"

.PP
Definition at line 346 of file TMP_Dropdown\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Image TMPro\&.TMP_Dropdown\&.captionImage\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 106 of file TMP_Dropdown\&.cs\&.
.SS "\fBTMP_Text\fP TMPro\&.TMP_Dropdown\&.captionText\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 102 of file TMP_Dropdown\&.cs\&.
.SS "bool TMPro\&.TMP_Dropdown\&.IsExpanded\fC [get]\fP"

.PP
Definition at line 171 of file TMP_Dropdown\&.cs\&.
.SS "Image TMPro\&.TMP_Dropdown\&.itemImage\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 116 of file TMP_Dropdown\&.cs\&.
.SS "\fBTMP_Text\fP TMPro\&.TMP_Dropdown\&.itemText\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 112 of file TMP_Dropdown\&.cs\&.
.SS "\fBDropdownEvent\fP TMPro\&.TMP_Dropdown\&.onValueChanged\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 140 of file TMP_Dropdown\&.cs\&.
.SS "List<\fBOptionData\fP> TMPro\&.TMP_Dropdown\&.options\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 130 of file TMP_Dropdown\&.cs\&.
.SS "RectTransform TMPro\&.TMP_Dropdown\&.template\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 97 of file TMP_Dropdown\&.cs\&.
.SS "int TMPro\&.TMP_Dropdown\&.value\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 152 of file TMP_Dropdown\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
