.TH "TMPro.SpriteAssetUtilities" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.SpriteAssetUtilities
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTexturePacker\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSpriteAssetImportFormats\fP { \fBSpriteAssetImportFormats\&.None\fP = 0, \fBSpriteAssetImportFormats\&.TexturePacker\fP = 0x1 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBTMPro\&.SpriteAssetUtilities\&.SpriteAssetImportFormats\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fITexturePacker \fP\fP
.PP
Definition at line 8 of file TMP_SpriteAssetImportFormats\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
