.TH "TMPro.MaterialReference" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.MaterialReference
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterialReference\fP (int \fBindex\fP, \fBTMP_FontAsset\fP \fBfontAsset\fP, \fBTMP_SpriteAsset\fP \fBspriteAsset\fP, Material \fBmaterial\fP, float \fBpadding\fP)"
.br
.RI "Constructor for new Material Reference\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBContains\fP (\fBMaterialReference\fP[] materialReferences, \fBTMP_FontAsset\fP \fBfontAsset\fP)"
.br
.RI "Function to check if a certain font asset is contained in the material reference array\&. "
.ti -1c
.RI "static int \fBAddMaterialReference\fP (Material \fBmaterial\fP, \fBTMP_FontAsset\fP \fBfontAsset\fP, \fBMaterialReference\fP[] materialReferences, Dictionary< int, int > materialReferenceIndexLookup)"
.br
.RI "Function to add a new material reference and returning its index in the material reference array\&. "
.ti -1c
.RI "static int \fBAddMaterialReference\fP (Material \fBmaterial\fP, \fBTMP_SpriteAsset\fP \fBspriteAsset\fP, \fBMaterialReference\fP[] materialReferences, Dictionary< int, int > materialReferenceIndexLookup)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "\fBTMP_FontAsset\fP \fBfontAsset\fP"
.br
.ti -1c
.RI "\fBTMP_SpriteAsset\fP \fBspriteAsset\fP"
.br
.ti -1c
.RI "Material \fBmaterial\fP"
.br
.ti -1c
.RI "bool \fBisDefaultMaterial\fP"
.br
.ti -1c
.RI "bool \fBisFallbackMaterial\fP"
.br
.ti -1c
.RI "Material \fBfallbackMaterial\fP"
.br
.ti -1c
.RI "float \fBpadding\fP"
.br
.ti -1c
.RI "int \fBreferenceCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 517 of file MaterialReferenceManager\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMPro\&.MaterialReference\&.MaterialReference (int index, \fBTMP_FontAsset\fP fontAsset, \fBTMP_SpriteAsset\fP spriteAsset, Material material, float padding)"

.PP
Constructor for new Material Reference\&. 
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP 
.br
\fIfontAsset\fP 
.br
\fIspriteAsset\fP 
.br
\fImaterial\fP 
.br
\fIpadding\fP 
.RE
.PP

.PP
Definition at line 539 of file MaterialReferenceManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static int TMPro\&.MaterialReference\&.AddMaterialReference (Material material, \fBTMP_FontAsset\fP fontAsset, \fBMaterialReference\fP [] materialReferences, Dictionary< int, int > materialReferenceIndexLookup)\fC [static]\fP"

.PP
Function to add a new material reference and returning its index in the material reference array\&. 
.PP
\fBParameters:\fP
.RS 4
\fImaterial\fP 
.br
\fIfontAsset\fP 
.br
\fImaterialReferences\fP 
.br
\fImaterialReferenceIndexLookup\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 581 of file MaterialReferenceManager\&.cs\&.
.SS "static int TMPro\&.MaterialReference\&.AddMaterialReference (Material material, \fBTMP_SpriteAsset\fP spriteAsset, \fBMaterialReference\fP [] materialReferences, Dictionary< int, int > materialReferenceIndexLookup)\fC [static]\fP"

.PP

.PP
\fBParameters:\fP
.RS 4
\fImaterial\fP 
.br
\fIspriteAsset\fP 
.br
\fImaterialReferences\fP 
.br
\fImaterialReferenceIndexLookup\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 618 of file MaterialReferenceManager\&.cs\&.
.SS "static bool TMPro\&.MaterialReference\&.Contains (\fBMaterialReference\fP [] materialReferences, \fBTMP_FontAsset\fP fontAsset)\fC [static]\fP"

.PP
Function to check if a certain font asset is contained in the material reference array\&. 
.PP
\fBParameters:\fP
.RS 4
\fImaterialReferences\fP 
.br
\fIfontAsset\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 559 of file MaterialReferenceManager\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Material TMPro\&.MaterialReference\&.fallbackMaterial"

.PP
Definition at line 526 of file MaterialReferenceManager\&.cs\&.
.SS "\fBTMP_FontAsset\fP TMPro\&.MaterialReference\&.fontAsset"

.PP
Definition at line 521 of file MaterialReferenceManager\&.cs\&.
.SS "int TMPro\&.MaterialReference\&.index"

.PP
Definition at line 520 of file MaterialReferenceManager\&.cs\&.
.SS "bool TMPro\&.MaterialReference\&.isDefaultMaterial"

.PP
Definition at line 524 of file MaterialReferenceManager\&.cs\&.
.SS "bool TMPro\&.MaterialReference\&.isFallbackMaterial"

.PP
Definition at line 525 of file MaterialReferenceManager\&.cs\&.
.SS "Material TMPro\&.MaterialReference\&.material"

.PP
Definition at line 523 of file MaterialReferenceManager\&.cs\&.
.SS "float TMPro\&.MaterialReference\&.padding"

.PP
Definition at line 527 of file MaterialReferenceManager\&.cs\&.
.SS "int TMPro\&.MaterialReference\&.referenceCount"

.PP
Definition at line 528 of file MaterialReferenceManager\&.cs\&.
.SS "\fBTMP_SpriteAsset\fP TMPro\&.MaterialReference\&.spriteAsset"

.PP
Definition at line 522 of file MaterialReferenceManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
