.TH "TMPro.TMP_SubMesh" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_SubMesh
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDestroySelf\fP ()"
.br
.ti -1c
.RI "float \fBGetPaddingForMaterial\fP ()"
.br
.RI "Function called when the padding value for the material needs to be re-calculated\&. "
.ti -1c
.RI "void \fBUpdateMeshPadding\fP (bool isExtraPadding, bool isUsingBold)"
.br
.RI "Function to update the padding values of the object\&. "
.ti -1c
.RI "void \fBSetVerticesDirty\fP ()"
.br
.ti -1c
.RI "void \fBSetMaterialDirty\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTMP_SubMesh\fP \fBAddSubTextObject\fP (\fBTextMeshPro\fP textComponent, \fBMaterialReference\fP materialReference)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateMaterial\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTMP_FontAsset\fP \fBfontAsset\fP\fC [get, set]\fP"
.br
.RI "The TMP Font Asset assigned to this sub text object\&. "
.ti -1c
.RI "\fBTMP_SpriteAsset\fP \fBspriteAsset\fP\fC [get, set]\fP"
.br
.RI "The TMP Sprite Asset assigned to this sub text object\&. "
.ti -1c
.RI "Material \fBmaterial\fP\fC [get, set]\fP"
.br
.RI "The material to be assigned to this object\&. Returns an instance of the material\&. "
.ti -1c
.RI "Material \fBsharedMaterial\fP\fC [get, set]\fP"
.br
.RI "The material to be assigned to this text object\&. "
.ti -1c
.RI "Material \fBfallbackMaterial\fP\fC [get, set]\fP"
.br
.RI "The fallback material created from the properties of the fallback source material\&. "
.ti -1c
.RI "Material \fBfallbackSourceMaterial\fP\fC [get, set]\fP"
.br
.RI "The source material used by the fallback font "
.ti -1c
.RI "bool \fBisDefaultMaterial\fP\fC [get, set]\fP"
.br
.RI "Is the text object using the default font asset material\&. "
.ti -1c
.RI "float \fBpadding\fP\fC [get, set]\fP"
.br
.RI "Padding value resulting for the property settings on the material\&. "
.ti -1c
.RI "new Renderer \fBrenderer\fP\fC [get]\fP"
.br
.RI "The Mesh Renderer of this text sub object\&. "
.ti -1c
.RI "MeshFilter \fBmeshFilter\fP\fC [get]\fP"
.br
.RI "The MeshFilter of this text sub object\&. "
.ti -1c
.RI "Mesh \fBmesh\fP\fC [get, set]\fP"
.br
.RI "The Mesh of this text sub object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file TMP_SubMesh\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBTMP_SubMesh\fP TMPro\&.TMP_SubMesh\&.AddSubTextObject (\fBTextMeshPro\fP textComponent, \fBMaterialReference\fP materialReference)\fC [static]\fP"

.PP
Definition at line 373 of file TMP_SubMesh\&.cs\&.
.SS "void TMPro\&.TMP_SubMesh\&.DestroySelf ()"

.PP
Definition at line 400 of file TMP_SubMesh\&.cs\&.
.SS "float TMPro\&.TMP_SubMesh\&.GetPaddingForMaterial ()"

.PP
Function called when the padding value for the material needs to be re-calculated\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 484 of file TMP_SubMesh\&.cs\&.
.SS "void TMPro\&.TMP_SubMesh\&.SetMaterialDirty ()"

.PP

.PP
Definition at line 523 of file TMP_SubMesh\&.cs\&.
.SS "void TMPro\&.TMP_SubMesh\&.SetVerticesDirty ()"

.PP

.PP
Definition at line 506 of file TMP_SubMesh\&.cs\&.
.SS "void TMPro\&.TMP_SubMesh\&.UpdateMaterial ()\fC [protected]\fP"

.PP

.PP
Definition at line 538 of file TMP_SubMesh\&.cs\&.
.SS "void TMPro\&.TMP_SubMesh\&.UpdateMeshPadding (bool isExtraPadding, bool isUsingBold)"

.PP
Function to update the padding values of the object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIisExtraPadding\fP 
.br
\fIisBold\fP 
.RE
.PP

.PP
Definition at line 497 of file TMP_SubMesh\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Material TMPro\&.TMP_SubMesh\&.fallbackMaterial\fC [get]\fP, \fC [set]\fP"

.PP
The fallback material created from the properties of the fallback source material\&. 
.PP
Definition at line 81 of file TMP_SubMesh\&.cs\&.
.SS "Material TMPro\&.TMP_SubMesh\&.fallbackSourceMaterial\fC [get]\fP, \fC [set]\fP"

.PP
The source material used by the fallback font 
.PP
Definition at line 103 of file TMP_SubMesh\&.cs\&.
.SS "\fBTMP_FontAsset\fP TMPro\&.TMP_SubMesh\&.fontAsset\fC [get]\fP, \fC [set]\fP"

.PP
The TMP Font Asset assigned to this sub text object\&. 
.PP
Definition at line 19 of file TMP_SubMesh\&.cs\&.
.SS "bool TMPro\&.TMP_SubMesh\&.isDefaultMaterial\fC [get]\fP, \fC [set]\fP"

.PP
Is the text object using the default font asset material\&. 
.PP
Definition at line 114 of file TMP_SubMesh\&.cs\&.
.SS "Material TMPro\&.TMP_SubMesh\&.material\fC [get]\fP, \fC [set]\fP"

.PP
The material to be assigned to this object\&. Returns an instance of the material\&. 
.PP
Definition at line 43 of file TMP_SubMesh\&.cs\&.
.SS "Mesh TMPro\&.TMP_SubMesh\&.mesh\fC [get]\fP, \fC [set]\fP"

.PP
The Mesh of this text sub object\&. 
.PP
Definition at line 165 of file TMP_SubMesh\&.cs\&.
.SS "MeshFilter TMPro\&.TMP_SubMesh\&.meshFilter\fC [get]\fP"

.PP
The MeshFilter of this text sub object\&. 
.PP
Definition at line 152 of file TMP_SubMesh\&.cs\&.
.SS "float TMPro\&.TMP_SubMesh\&.padding\fC [get]\fP, \fC [set]\fP"

.PP
Padding value resulting for the property settings on the material\&. 
.PP
Definition at line 126 of file TMP_SubMesh\&.cs\&.
.SS "new Renderer TMPro\&.TMP_SubMesh\&.renderer\fC [get]\fP"

.PP
The Mesh Renderer of this text sub object\&. 
.PP
Definition at line 138 of file TMP_SubMesh\&.cs\&.
.SS "Material TMPro\&.TMP_SubMesh\&.sharedMaterial\fC [get]\fP, \fC [set]\fP"

.PP
The material to be assigned to this text object\&. 
.PP
Definition at line 69 of file TMP_SubMesh\&.cs\&.
.SS "\fBTMP_SpriteAsset\fP TMPro\&.TMP_SubMesh\&.spriteAsset\fC [get]\fP, \fC [set]\fP"

.PP
The TMP Sprite Asset assigned to this sub text object\&. 
.PP
Definition at line 31 of file TMP_SubMesh\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
