.TH "TMPro.EditorUtilities.TMPro_FontPlugin" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.EditorUtilities.TMPro_FontPlugin
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBInitialize_FontEngine\fP ()"
.br
.ti -1c
.RI "static int \fBDestroy_FontEngine\fP ()"
.br
.ti -1c
.RI "static int \fBLoad_TrueType_Font\fP (string fontPath)"
.br
.ti -1c
.RI "static int \fBFT_Size_Font\fP (int fontSize)"
.br
.ti -1c
.RI "static int \fBRender_Character\fP (byte[] buffer_fill, byte[] buffer_edge, int buffer_width, int buffer_height, int offset, int asc, \fBFaceStyles\fP style, float thickness, \fBRenderModes\fP rasterMode, ref \fBFT_GlyphInfo\fP glyphInfo)"
.br
.ti -1c
.RI "static int \fBRender_Characters\fP (byte[] buffer, int buffer_width, int buffer_height, int character_padding, int[] asc_set, int char_count, \fBFaceStyles\fP style, float style_mod, bool autoSize, \fBRenderModes\fP renderMode, int method, ref \fBFT_FaceInfo\fP fontData, \fBFT_GlyphInfo\fP[] Output)"
.br
.ti -1c
.RI "static int \fBFT_GetKerningPairs\fP (string fontPath, int[] characterSet, int setCount, \fBFT_KerningPair\fP[] kerningPairs)"
.br
.ti -1c
.RI "static float \fBCheck_RenderProgress\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBLinkDebugLog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file TMPro_FontPlugin\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static float TMPro\&.EditorUtilities\&.TMPro_FontPlugin\&.Check_RenderProgress ()"

.SS "static int TMPro\&.EditorUtilities\&.TMPro_FontPlugin\&.Destroy_FontEngine ()"

.SS "static int TMPro\&.EditorUtilities\&.TMPro_FontPlugin\&.FT_GetKerningPairs (string fontPath, int [] characterSet, int setCount, \fBFT_KerningPair\fP [] kerningPairs)"

.SS "static int TMPro\&.EditorUtilities\&.TMPro_FontPlugin\&.FT_Size_Font (int fontSize)"

.SS "static int TMPro\&.EditorUtilities\&.TMPro_FontPlugin\&.Initialize_FontEngine ()"

.SS "static void TMPro\&.EditorUtilities\&.TMPro_FontPlugin\&.LinkDebugLog ()\fC [static]\fP"

.PP
Definition at line 22 of file TMPro_FontPlugin\&.cs\&.
.SS "static int TMPro\&.EditorUtilities\&.TMPro_FontPlugin\&.Load_TrueType_Font (string fontPath)"

.SS "static int TMPro\&.EditorUtilities\&.TMPro_FontPlugin\&.Render_Character (byte [] buffer_fill, byte [] buffer_edge, int buffer_width, int buffer_height, int offset, int asc, \fBFaceStyles\fP style, float thickness, \fBRenderModes\fP rasterMode, ref \fBFT_GlyphInfo\fP glyphInfo)"

.SS "static int TMPro\&.EditorUtilities\&.TMPro_FontPlugin\&.Render_Characters (byte [] buffer, int buffer_width, int buffer_height, int character_padding, int [] asc_set, int char_count, \fBFaceStyles\fP style, float style_mod, bool autoSize, \fBRenderModes\fP renderMode, int method, ref \fBFT_FaceInfo\fP fontData, \fBFT_GlyphInfo\fP [] Output)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
