.TH "TMPro.EditorUtilities.DropdownOptionListDrawer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.EditorUtilities.DropdownOptionListDrawer
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyDrawer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnGUI\fP (Rect position, SerializedProperty property, GUIContent label)"
.br
.ti -1c
.RI "override float \fBGetPropertyHeight\fP (SerializedProperty property, GUIContent label)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file DropdownOptionListDrawer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override float TMPro\&.EditorUtilities\&.DropdownOptionListDrawer\&.GetPropertyHeight (SerializedProperty property, GUIContent label)"

.PP
Definition at line 53 of file DropdownOptionListDrawer\&.cs\&.
.SS "override void TMPro\&.EditorUtilities\&.DropdownOptionListDrawer\&.OnGUI (Rect position, SerializedProperty property, GUIContent label)"

.PP
Definition at line 26 of file DropdownOptionListDrawer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
