.TH "TMPro.TMP_SpriteAnimator" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_SpriteAnimator
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStopAllAnimations\fP ()"
.br
.ti -1c
.RI "void \fBDoSpriteAnimation\fP (int currentCharacter, \fBTMP_SpriteAsset\fP spriteAsset, int start, int end, int framerate)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file TMP_SpriteAnimator\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMPro\&.TMP_SpriteAnimator\&.DoSpriteAnimation (int currentCharacter, \fBTMP_SpriteAsset\fP spriteAsset, int start, int end, int framerate)"

.PP
Definition at line 44 of file TMP_SpriteAnimator\&.cs\&.
.SS "void TMPro\&.TMP_SpriteAnimator\&.StopAllAnimations ()"

.PP
Definition at line 36 of file TMP_SpriteAnimator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
