.TH "TMPro.TMP_Dropdown.OptionDataList" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_Dropdown.OptionDataList
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionDataList\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBOptionData\fP > \fBoptions\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file TMP_Dropdown\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMPro\&.TMP_Dropdown\&.OptionDataList\&.OptionDataList ()"

.PP
Definition at line 85 of file TMP_Dropdown\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBOptionData\fP> TMPro\&.TMP_Dropdown\&.OptionDataList\&.options\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 82 of file TMP_Dropdown\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
