.TH "TMPro.AssetConversionRecord" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.AssetConversionRecord \- Data structure containing the target and replacement fileIDs and GUIDs which will require remapping from previous version of TextMesh Pro to the new TextMesh Pro UPM package\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBreferencedResource\fP"
.br
.ti -1c
.RI "string \fBtarget\fP"
.br
.ti -1c
.RI "string \fBreplacement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data structure containing the target and replacement fileIDs and GUIDs which will require remapping from previous version of TextMesh Pro to the new TextMesh Pro UPM package\&. 


.PP
Definition at line 15 of file TMP_PackageUtilities\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string TMPro\&.AssetConversionRecord\&.referencedResource"

.PP
Definition at line 17 of file TMP_PackageUtilities\&.cs\&.
.SS "string TMPro\&.AssetConversionRecord\&.replacement"

.PP
Definition at line 19 of file TMP_PackageUtilities\&.cs\&.
.SS "string TMPro\&.AssetConversionRecord\&.target"

.PP
Definition at line 18 of file TMP_PackageUtilities\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
