.TH "TMPro.EditorUtilities.TMPro_TextContainerEditor" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.EditorUtilities.TMPro_TextContainerEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits Editor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file TMPro_TextContainerEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TMPro\&.EditorUtilities\&.TMPro_TextContainerEditor\&.OnInspectorGUI ()"

.PP
Definition at line 66 of file TMPro_TextContainerEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
