.TH "TMPro.ColorTween" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.ColorTween
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMPro\&.ITweenValue\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColorTweenCallback\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBColorTweenMode\fP { \fBColorTweenMode\&.All\fP, \fBColorTweenMode\&.RGB\fP, \fBColorTweenMode\&.Alpha\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTweenValue\fP (float floatPercentage)"
.br
.ti -1c
.RI "void \fBAddOnChangedCallback\fP (UnityAction< Color > callback)"
.br
.ti -1c
.RI "bool \fBGetIgnoreTimescale\fP ()"
.br
.ti -1c
.RI "float \fBGetDuration\fP ()"
.br
.ti -1c
.RI "bool \fBValidTarget\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Color \fBstartColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Color \fBtargetColor\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBColorTweenMode\fP \fBtweenMode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBduration\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBignoreTimeScale\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file TMP_CoroutineTween\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBTMPro\&.ColorTween\&.ColorTweenMode\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAll \fP\fP
.TP
\fB\fIRGB \fP\fP
.TP
\fB\fIAlpha \fP\fP
.PP
Definition at line 25 of file TMP_CoroutineTween\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMPro\&.ColorTween\&.AddOnChangedCallback (UnityAction< Color > callback)"

.PP
Definition at line 92 of file TMP_CoroutineTween\&.cs\&.
.SS "float TMPro\&.ColorTween\&.GetDuration ()"

.PP
Definition at line 105 of file TMP_CoroutineTween\&.cs\&.
.SS "bool TMPro\&.ColorTween\&.GetIgnoreTimescale ()"

.PP
Definition at line 100 of file TMP_CoroutineTween\&.cs\&.
.SS "void TMPro\&.ColorTween\&.TweenValue (float floatPercentage)"

.PP
Implements \fBTMPro\&.ITweenValue\fP\&.
.PP
Definition at line 72 of file TMP_CoroutineTween\&.cs\&.
.SS "bool TMPro\&.ColorTween\&.ValidTarget ()"

.PP
Implements \fBTMPro\&.ITweenValue\fP\&.
.PP
Definition at line 110 of file TMP_CoroutineTween\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "float TMPro\&.ColorTween\&.duration\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 61 of file TMP_CoroutineTween\&.cs\&.
.SS "bool TMPro\&.ColorTween\&.ignoreTimeScale\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 67 of file TMP_CoroutineTween\&.cs\&.
.SS "Color TMPro\&.ColorTween\&.startColor\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 43 of file TMP_CoroutineTween\&.cs\&.
.SS "Color TMPro\&.ColorTween\&.targetColor\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 49 of file TMP_CoroutineTween\&.cs\&.
.SS "\fBColorTweenMode\fP TMPro\&.ColorTween\&.tweenMode\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 55 of file TMP_CoroutineTween\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
