.TH "TMPro.TMP_ColorGradient" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_ColorGradient
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMP_ColorGradient\fP ()"
.br
.RI "Default Constructor which sets each of the colors as white\&. "
.ti -1c
.RI "\fBTMP_ColorGradient\fP (Color color)"
.br
.RI "Constructor allowing to set the default color of the Color Gradient\&. "
.ti -1c
.RI "\fBTMP_ColorGradient\fP (Color color0, Color color1, Color color2, Color color3)"
.br
.RI "The vertex colors at the corners of the characters\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBColorMode\fP \fBcolorMode\fP = \fBColorMode\&.FourCornersGradient\fP"
.br
.ti -1c
.RI "Color \fBtopLeft\fP"
.br
.ti -1c
.RI "Color \fBtopRight\fP"
.br
.ti -1c
.RI "Color \fBbottomLeft\fP"
.br
.ti -1c
.RI "Color \fBbottomRight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file TMP_ColorGradient\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMPro\&.TMP_ColorGradient\&.TMP_ColorGradient ()"

.PP
Default Constructor which sets each of the colors as white\&. 
.PP
Definition at line 30 of file TMP_ColorGradient\&.cs\&.
.SS "TMPro\&.TMP_ColorGradient\&.TMP_ColorGradient (Color color)"

.PP
Constructor allowing to set the default color of the Color Gradient\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcolor\fP 
.RE
.PP

.PP
Definition at line 43 of file TMP_ColorGradient\&.cs\&.
.SS "TMPro\&.TMP_ColorGradient\&.TMP_ColorGradient (Color color0, Color color1, Color color2, Color color3)"

.PP
The vertex colors at the corners of the characters\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcolor0\fP Top left color\&.
.br
\fIcolor1\fP Top right color\&.
.br
\fIcolor2\fP Bottom left color\&.
.br
\fIcolor3\fP Bottom right color\&.
.RE
.PP

.PP
Definition at line 59 of file TMP_ColorGradient\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Color TMPro\&.TMP_ColorGradient\&.bottomLeft"

.PP
Definition at line 21 of file TMP_ColorGradient\&.cs\&.
.SS "Color TMPro\&.TMP_ColorGradient\&.bottomRight"

.PP
Definition at line 22 of file TMP_ColorGradient\&.cs\&.
.SS "\fBColorMode\fP TMPro\&.TMP_ColorGradient\&.colorMode = \fBColorMode\&.FourCornersGradient\fP"

.PP
Definition at line 17 of file TMP_ColorGradient\&.cs\&.
.SS "Color TMPro\&.TMP_ColorGradient\&.topLeft"

.PP
Definition at line 19 of file TMP_ColorGradient\&.cs\&.
.SS "Color TMPro\&.TMP_ColorGradient\&.topRight"

.PP
Definition at line 20 of file TMP_ColorGradient\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
