.TH "TMPro.EditorUtilities.FT_FaceInfo" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.EditorUtilities.FT_FaceInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBpointSize\fP"
.br
.ti -1c
.RI "int \fBpadding\fP"
.br
.ti -1c
.RI "float \fBlineHeight\fP"
.br
.ti -1c
.RI "float \fBbaseline\fP"
.br
.ti -1c
.RI "float \fBascender\fP"
.br
.ti -1c
.RI "float \fBdescender\fP"
.br
.ti -1c
.RI "float \fBcenterLine\fP"
.br
.ti -1c
.RI "float \fBunderline\fP"
.br
.ti -1c
.RI "float \fBunderlineThickness\fP"
.br
.ti -1c
.RI "int \fBcharacterCount\fP"
.br
.ti -1c
.RI "int \fBatlasWidth\fP"
.br
.ti -1c
.RI "int \fBatlasHeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 96 of file TMPro_FontPlugin\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float TMPro\&.EditorUtilities\&.FT_FaceInfo\&.ascender"

.PP
Definition at line 104 of file TMPro_FontPlugin\&.cs\&.
.SS "int TMPro\&.EditorUtilities\&.FT_FaceInfo\&.atlasHeight"

.PP
Definition at line 111 of file TMPro_FontPlugin\&.cs\&.
.SS "int TMPro\&.EditorUtilities\&.FT_FaceInfo\&.atlasWidth"

.PP
Definition at line 110 of file TMPro_FontPlugin\&.cs\&.
.SS "float TMPro\&.EditorUtilities\&.FT_FaceInfo\&.baseline"

.PP
Definition at line 103 of file TMPro_FontPlugin\&.cs\&.
.SS "float TMPro\&.EditorUtilities\&.FT_FaceInfo\&.centerLine"

.PP
Definition at line 106 of file TMPro_FontPlugin\&.cs\&.
.SS "int TMPro\&.EditorUtilities\&.FT_FaceInfo\&.characterCount"

.PP
Definition at line 109 of file TMPro_FontPlugin\&.cs\&.
.SS "float TMPro\&.EditorUtilities\&.FT_FaceInfo\&.descender"

.PP
Definition at line 105 of file TMPro_FontPlugin\&.cs\&.
.SS "float TMPro\&.EditorUtilities\&.FT_FaceInfo\&.lineHeight"

.PP
Definition at line 102 of file TMPro_FontPlugin\&.cs\&.
.SS "string TMPro\&.EditorUtilities\&.FT_FaceInfo\&.name"

.PP
Definition at line 99 of file TMPro_FontPlugin\&.cs\&.
.SS "int TMPro\&.EditorUtilities\&.FT_FaceInfo\&.padding"

.PP
Definition at line 101 of file TMPro_FontPlugin\&.cs\&.
.SS "int TMPro\&.EditorUtilities\&.FT_FaceInfo\&.pointSize"

.PP
Definition at line 100 of file TMPro_FontPlugin\&.cs\&.
.SS "float TMPro\&.EditorUtilities\&.FT_FaceInfo\&.underline"

.PP
Definition at line 107 of file TMPro_FontPlugin\&.cs\&.
.SS "float TMPro\&.EditorUtilities\&.FT_FaceInfo\&.underlineThickness"

.PP
Definition at line 108 of file TMPro_FontPlugin\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
