.TH "TMPro.TMP_SelectionCaret" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_SelectionCaret \- A simple component that can be added to a newly created object where inheriting from MaskableGraphic is needed\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MaskableGraphic\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBCull\fP (Rect clipRect, bool validRect)"
.br
.RI "Override to Cull function of MaskableGraphic to prevent Culling\&. "
.in -1c
.SH "Detailed Description"
.PP 
A simple component that can be added to a newly created object where inheriting from MaskableGraphic is needed\&. 


.PP
Definition at line 10 of file TMP_SelectionCaret\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TMPro\&.TMP_SelectionCaret\&.Cull (Rect clipRect, bool validRect)"

.PP
Override to Cull function of MaskableGraphic to prevent Culling\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclipRect\fP 
.br
\fIvalidRect\fP 
.RE
.PP

.PP
Definition at line 18 of file TMP_SelectionCaret\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
