.TH "TMPro.TMP_StyleSheet" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_StyleSheet
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateStyleDictionaryKey\fP (int old_key, int new_key)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTMP_StyleSheet\fP \fBLoadDefaultStyleSheet\fP ()"
.br
.RI "Static Function to load the Default Style Sheet\&. "
.ti -1c
.RI "static \fBTMP_Style\fP \fBGetStyle\fP (int hashCode)"
.br
.RI "Function to retrieve the Style matching the HashCode\&. "
.ti -1c
.RI "static void \fBUpdateStyleSheet\fP ()"
.br
.RI "Function to update the internal reference to a newly assigned style sheet in the TMP Settings\&. "
.ti -1c
.RI "static void \fBRefreshStyles\fP ()"
.br
.RI "Function to refresh the Style Dictionary\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBTMP_StyleSheet\fP \fBinstance\fP\fC [get]\fP"
.br
.RI "Get a singleton instance of the \fBTMP_StyleSheet\fP "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file TMP_StyleSheet\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBTMP_Style\fP TMPro\&.TMP_StyleSheet\&.GetStyle (int hashCode)\fC [static]\fP"

.PP
Function to retrieve the Style matching the HashCode\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhashCode\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 59 of file TMP_StyleSheet\&.cs\&.
.SS "static \fBTMP_StyleSheet\fP TMPro\&.TMP_StyleSheet\&.LoadDefaultStyleSheet ()\fC [static]\fP"

.PP
Static Function to load the Default Style Sheet\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 48 of file TMP_StyleSheet\&.cs\&.
.SS "static void TMPro\&.TMP_StyleSheet\&.RefreshStyles ()\fC [static]\fP"

.PP
Function to refresh the Style Dictionary\&. 
.PP
Definition at line 108 of file TMP_StyleSheet\&.cs\&.
.SS "void TMPro\&.TMP_StyleSheet\&.UpdateStyleDictionaryKey (int old_key, int new_key)"

.PP
Definition at line 82 of file TMP_StyleSheet\&.cs\&.
.SS "static void TMPro\&.TMP_StyleSheet\&.UpdateStyleSheet ()\fC [static]\fP"

.PP
Function to update the internal reference to a newly assigned style sheet in the TMP Settings\&. 
.PP
Definition at line 96 of file TMP_StyleSheet\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBTMP_StyleSheet\fP TMPro\&.TMP_StyleSheet\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Get a singleton instance of the \fBTMP_StyleSheet\fP 
.PP
Definition at line 23 of file TMP_StyleSheet\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
