.TH "TMPro.TextMeshProUGUI" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TextMeshProUGUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMPro\&.TMP_Text\fP, and ILayoutElement\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCalculateLayoutInputHorizontal\fP ()"
.br
.RI "Function called by Unity when the horizontal layout needs to be recalculated\&. "
.ti -1c
.RI "void \fBCalculateLayoutInputVertical\fP ()"
.br
.RI "Function called by Unity when the vertical layout needs to be recalculated\&. "
.ti -1c
.RI "override void \fBSetVerticesDirty\fP ()"
.br
.ti -1c
.RI "override void \fBSetLayoutDirty\fP ()"
.br
.ti -1c
.RI "override void \fBSetMaterialDirty\fP ()"
.br
.ti -1c
.RI "override void \fBSetAllDirty\fP ()"
.br
.ti -1c
.RI "override void \fBRebuild\fP (CanvasUpdate update)"
.br
.ti -1c
.RI "override Material \fBGetModifiedMaterial\fP (Material baseMaterial)"
.br
.ti -1c
.RI "override void \fBRecalculateClipping\fP ()"
.br
.RI "Method called when the state of a parent changes\&. "
.ti -1c
.RI "override void \fBRecalculateMasking\fP ()"
.br
.RI "Method called when Stencil Mask needs to be updated on this element and parents\&. "
.ti -1c
.RI "override void \fBCull\fP (Rect clipRect, bool validRect)"
.br
.RI "Override of the Cull function to provide for the ability to override the culling of the text object\&. "
.ti -1c
.RI "override void \fBUpdateMeshPadding\fP ()"
.br
.RI "Function to be used to force recomputing of character padding when Shader / Material properties have been changed via script\&. "
.ti -1c
.RI "override void \fBForceMeshUpdate\fP ()"
.br
.RI "Function to force regeneration of the mesh before its normal process time\&. This is useful when changes to the text object properties need to be applied immediately\&. "
.ti -1c
.RI "override void \fBForceMeshUpdate\fP (bool ignoreInactive)"
.br
.RI "Function to force regeneration of the mesh before its normal process time\&. This is useful when changes to the text object properties need to be applied immediately\&. "
.ti -1c
.RI "override \fBTMP_TextInfo\fP \fBGetTextInfo\fP (string \fBtext\fP)"
.br
.RI "Function used to evaluate the length of a text string\&. "
.ti -1c
.RI "override void \fBClearMesh\fP ()"
.br
.RI "Function to clear the geometry of the Primary and Sub Text objects\&. "
.ti -1c
.RI "override void \fBUpdateGeometry\fP (Mesh \fBmesh\fP, int index)"
.br
.RI "Function to force the regeneration of the text object\&. "
.ti -1c
.RI "override void \fBUpdateVertexData\fP (\fBTMP_VertexDataUpdateFlags\fP flags)"
.br
.RI "Function to upload the updated vertex data and renderer\&. "
.ti -1c
.RI "override void \fBUpdateVertexData\fP ()"
.br
.RI "Function to upload the updated vertex data and renderer\&. "
.ti -1c
.RI "void \fBUpdateFontAsset\fP ()"
.br
.ti -1c
.RI "override void \fBComputeMarginSize\fP ()"
.br
.RI "Update the margin width and height "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBUpdateMaterial\fP ()"
.br
.ti -1c
.RI "override void \fBInternalCrossFadeColor\fP (Color targetColor, float duration, bool ignoreTimeScale, bool useAlpha)"
.br
.RI "Tweens the CanvasRenderer color associated with this Graphic\&. "
.ti -1c
.RI "override void \fBInternalCrossFadeAlpha\fP (float \fBalpha\fP, float duration, bool ignoreTimeScale)"
.br
.RI "Tweens the alpha of the CanvasRenderer color associated with this Graphic\&. "
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "override void \fBLoadFontAsset\fP ()"
.br
.RI "Method which derived classes need to override to load Font Assets\&. "
.ti -1c
.RI "override Material \fBGetMaterial\fP (Material mat)"
.br
.RI "Function called internally when a new material is assigned via the fontMaterial property\&. "
.ti -1c
.RI "override Material [] \fBGetMaterials\fP (Material[] mats)"
.br
.RI "Method returning instances of the materials used by the text object\&. "
.ti -1c
.RI "override void \fBSetSharedMaterial\fP (Material mat)"
.br
.RI "Function called internally when a new shared material is assigned via the fontSharedMaterial property\&. "
.ti -1c
.RI "override Material [] \fBGetSharedMaterials\fP ()"
.br
.RI "Method returning an array containing the materials used by the text object\&. "
.ti -1c
.RI "override void \fBSetSharedMaterials\fP (Material[] materials)"
.br
.RI "Method used to assign new materials to the text and sub text objects\&. "
.ti -1c
.RI "override void \fBSetOutlineThickness\fP (float thickness)"
.br
.RI "Function called internally to set the outline thickness property of the material\&. This will results in an instance of the material\&. "
.ti -1c
.RI "override void \fBSetFaceColor\fP (Color32 \fBcolor\fP)"
.br
.RI "Function called internally to set the face color of the material\&. This will results in an instance of the material\&. "
.ti -1c
.RI "override void \fBSetOutlineColor\fP (Color32 \fBcolor\fP)"
.br
.RI "Function called internally to set the outline color of the material\&. This will results in an instance of the material\&. "
.ti -1c
.RI "override void \fBSetShaderDepth\fP ()"
.br
.RI "Set the Render Queue and ZTest mode on the current material "
.ti -1c
.RI "override void \fBSetCulling\fP ()"
.br
.RI "Set the culling mode on the material\&. "
.ti -1c
.RI "override float \fBGetPaddingForMaterial\fP (Material mat)"
.br
.RI "Get the padding value for the currently assigned material\&. "
.ti -1c
.RI "override float \fBGetPaddingForMaterial\fP ()"
.br
.RI "Get the padding value for the currently assigned material\&. "
.ti -1c
.RI "override int \fBSetArraySizes\fP (int[] chars)"
.br
.RI "Method used to determine the number of visible characters and required buffer allocations\&. "
.ti -1c
.RI "override void \fBOnDidApplyAnimationProperties\fP ()"
.br
.ti -1c
.RI "override void \fBOnCanvasHierarchyChanged\fP ()"
.br
.ti -1c
.RI "override void \fBOnTransformParentChanged\fP ()"
.br
.ti -1c
.RI "override void \fBOnRectTransformDimensionsChange\fP ()"
.br
.ti -1c
.RI "override void \fBGenerateTextMesh\fP ()"
.br
.RI "This is the main function that is responsible for creating / displaying the text\&. "
.ti -1c
.RI "override Vector3 [] \fBGetTextContainerLocalCorners\fP ()"
.br
.RI "Method to return the local corners of the Text Container or RectTransform\&. "
.ti -1c
.RI "override void \fBSetActiveSubMeshes\fP (bool state)"
.br
.RI "Method to Enable or Disable child SubMesh objects\&. "
.ti -1c
.RI "override Bounds \fBGetCompoundBounds\fP ()"
.br
.RI "Method returning the compound bounds of the text object and child sub objects\&. "
.ti -1c
.RI "override void \fBAdjustLineOffset\fP (int startIndex, int endIndex, float offset)"
.br
.RI "Method to adjust line spacing as a result of using different fonts or font point size\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBTMP_SubMeshUI\fP [] \fBm_subTextObjects\fP = new \fBTMP_SubMeshUI\fP[8]"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override Material \fBmaterialForRendering\fP\fC [get]\fP"
.br
.RI "Get the material that will be used for rendering\&. "
.ti -1c
.RI "override bool \fBautoSizeTextContainer\fP\fC [get, set]\fP"
.br
.RI "Determines if the size of the text container will be adjusted to fit the text object when it is first created\&. "
.ti -1c
.RI "override Mesh \fBmesh\fP\fC [get]\fP"
.br
.RI "Reference to the Mesh used by the text object\&. "
.ti -1c
.RI "new CanvasRenderer \fBcanvasRenderer\fP\fC [get]\fP"
.br
.RI "Reference to the CanvasRenderer used by the text object\&. "
.ti -1c
.RI "Vector4 \fBmaskOffset\fP\fC [get, set]\fP"
.br
.RI "Sets the masking offset from the bounds of the object "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file TextMeshProUGUI\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TMPro\&.TextMeshProUGUI\&.AdjustLineOffset (int startIndex, int endIndex, float offset)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method to adjust line spacing as a result of using different fonts or font point size\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstartIndex\fP 
.br
\fIendIndex\fP 
.br
\fIoffset\fP 
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 4222 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.Awake ()\fC [protected]\fP"

.PP
Definition at line 71 of file TMPro_UGUI_Private\&.cs\&.
.SS "void TMPro\&.TextMeshProUGUI\&.CalculateLayoutInputHorizontal ()"

.PP
Function called by Unity when the horizontal layout needs to be recalculated\&. 
.PP
Definition at line 83 of file TextMeshProUGUI\&.cs\&.
.SS "void TMPro\&.TextMeshProUGUI\&.CalculateLayoutInputVertical ()"

.PP
Function called by Unity when the vertical layout needs to be recalculated\&. 
.PP
Definition at line 105 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.ClearMesh ()\fC [virtual]\fP"

.PP
Function to clear the geometry of the Primary and Sub Text objects\&. 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 526 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.ComputeMarginSize ()\fC [virtual]\fP"

.PP
Update the margin width and height 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 1492 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.Cull (Rect clipRect, bool validRect)"

.PP
Override of the Cull function to provide for the ability to override the culling of the text object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclipRect\fP 
.br
\fIvalidRect\fP 
.RE
.PP

.PP
Definition at line 356 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.ForceMeshUpdate ()\fC [virtual]\fP"

.PP
Function to force regeneration of the mesh before its normal process time\&. This is useful when changes to the text object properties need to be applied immediately\&. 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 478 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.ForceMeshUpdate (bool ignoreInactive)\fC [virtual]\fP"

.PP
Function to force regeneration of the mesh before its normal process time\&. This is useful when changes to the text object properties need to be applied immediately\&. 
.PP
\fBParameters:\fP
.RS 4
\fIignoreInactive\fP If set to true, the text object will be regenerated regardless of is active state\&.
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 491 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.GenerateTextMesh ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
This is the main function that is responsible for creating / displaying the text\&. 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 1651 of file TMPro_UGUI_Private\&.cs\&.
.SS "override Bounds TMPro\&.TextMeshProUGUI\&.GetCompoundBounds ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method returning the compound bounds of the text object and child sub objects\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 4131 of file TMPro_UGUI_Private\&.cs\&.
.SS "override Material TMPro\&.TextMeshProUGUI\&.GetMaterial (Material mat)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Function called internally when a new material is assigned via the fontMaterial property\&. 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 736 of file TMPro_UGUI_Private\&.cs\&.
.SS "override Material [] TMPro\&.TextMeshProUGUI\&.GetMaterials (Material [] mats)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method returning instances of the materials used by the text object\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 766 of file TMPro_UGUI_Private\&.cs\&.
.SS "override Material TMPro\&.TextMeshProUGUI\&.GetModifiedMaterial (Material baseMaterial)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIbaseMaterial\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 242 of file TextMeshProUGUI\&.cs\&.
.SS "override float TMPro\&.TextMeshProUGUI\&.GetPaddingForMaterial (Material mat)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Get the padding value for the currently assigned material\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 992 of file TMPro_UGUI_Private\&.cs\&.
.SS "override float TMPro\&.TextMeshProUGUI\&.GetPaddingForMaterial ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Get the padding value for the currently assigned material\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 1006 of file TMPro_UGUI_Private\&.cs\&.
.SS "override Material [] TMPro\&.TextMeshProUGUI\&.GetSharedMaterials ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method returning an array containing the materials used by the text object\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 810 of file TMPro_UGUI_Private\&.cs\&.
.SS "override Vector3 [] TMPro\&.TextMeshProUGUI\&.GetTextContainerLocalCorners ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method to return the local corners of the Text Container or RectTransform\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 4103 of file TMPro_UGUI_Private\&.cs\&.
.SS "override \fBTMP_TextInfo\fP TMPro\&.TextMeshProUGUI\&.GetTextInfo (string text)\fC [virtual]\fP"

.PP
Function used to evaluate the length of a text string\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 504 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.InternalCrossFadeAlpha (float alpha, float duration, bool ignoreTimeScale)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Tweens the alpha of the CanvasRenderer color associated with this Graphic\&. 
.PP
\fBParameters:\fP
.RS 4
\fIalpha\fP Target alpha\&.
.br
\fIduration\fP Duration of the tween in seconds\&.
.br
\fIignoreTimeScale\fP Should ignore Time\&.scale?
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 464 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.InternalCrossFadeColor (Color targetColor, float duration, bool ignoreTimeScale, bool useAlpha)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Tweens the CanvasRenderer color associated with this Graphic\&. 
.PP
\fBParameters:\fP
.RS 4
\fItargetColor\fP Target color\&.
.br
\fIduration\fP Tween duration\&.
.br
\fIignoreTimeScale\fP Should ignore Time\&.scale?
.br
\fIuseAlpha\fP Should also Tween the alpha channel?
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 447 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.LoadFontAsset ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method which derived classes need to override to load Font Assets\&. 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 501 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.OnCanvasHierarchyChanged ()\fC [protected]\fP"

.PP
Definition at line 1519 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.OnDestroy ()\fC [protected]\fP"

.PP
Definition at line 228 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.OnDidApplyAnimationProperties ()\fC [protected]\fP"

.PP

.PP
Definition at line 1510 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.OnDisable ()\fC [protected]\fP"

.PP
Definition at line 199 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.OnEnable ()\fC [protected]\fP"

.PP
Definition at line 154 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.OnRectTransformDimensionsChange ()\fC [protected]\fP"

.PP
Definition at line 1539 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.OnTransformParentChanged ()\fC [protected]\fP"

.PP
Definition at line 1526 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.Rebuild (CanvasUpdate update)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIupdate\fP 
.RE
.PP

.PP
Definition at line 196 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.RecalculateClipping ()"

.PP
Method called when the state of a parent changes\&. 
.PP
Definition at line 332 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.RecalculateMasking ()"

.PP
Method called when Stencil Mask needs to be updated on this element and parents\&. 
.PP
Definition at line 343 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetActiveSubMeshes (bool state)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method to Enable or Disable child SubMesh objects\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstate\fP 
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 4117 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetAllDirty ()"

.PP

.PP
Definition at line 181 of file TextMeshProUGUI\&.cs\&.
.SS "override int TMPro\&.TextMeshProUGUI\&.SetArraySizes (int [] chars)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method used to determine the number of visible characters and required buffer allocations\&. 
.PP
\fBParameters:\fP
.RS 4
\fIchars\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 1027 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetCulling ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Set the culling mode on the material\&. 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 939 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetFaceColor (Color32 color)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Function called internally to set the face color of the material\&. This will results in an instance of the material\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcolor\fP 
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 893 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetLayoutDirty ()"

.PP

.PP
Definition at line 142 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetMaterialDirty ()"

.PP

.PP
Definition at line 163 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetOutlineColor (Color32 color)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Function called internally to set the outline color of the material\&. This will results in an instance of the material\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcolor\fP 
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 907 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetOutlineThickness (float thickness)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Function called internally to set the outline thickness property of the material\&. This will results in an instance of the material\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthickness\fP 
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 871 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetShaderDepth ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Set the Render Queue and ZTest mode on the current material 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 921 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetSharedMaterial (Material mat)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Function called internally when a new shared material is assigned via the fontSharedMaterial property\&. 
.PP
\fBParameters:\fP
.RS 4
\fImat\fP 
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 791 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetSharedMaterials (Material [] materials)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Method used to assign new materials to the text and sub text objects\&. 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 834 of file TMPro_UGUI_Private\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.SetVerticesDirty ()"

.PP
Definition at line 126 of file TextMeshProUGUI\&.cs\&.
.SS "void TMPro\&.TextMeshProUGUI\&.UpdateFontAsset ()"

.PP
Definition at line 650 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.UpdateGeometry (Mesh mesh, int index)\fC [virtual]\fP"

.PP
Function to force the regeneration of the text object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIflags\fP Flags to control which portions of the geometry gets uploaded\&.
.RE
.PP
.PP
Function to update the geometry of the main and sub text objects\&. 
.PP
\fBParameters:\fP
.RS 4
\fImesh\fP 
.br
\fIindex\fP 
.RE
.PP

.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 550 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.UpdateMaterial ()\fC [protected]\fP"

.PP

.PP
Definition at line 272 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.UpdateMeshPadding ()\fC [virtual]\fP"

.PP
Function to be used to force recomputing of character padding when Shader / Material properties have been changed via script\&. 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 424 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.UpdateVertexData (\fBTMP_VertexDataUpdateFlags\fP flags)\fC [virtual]\fP"

.PP
Function to upload the updated vertex data and renderer\&. 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 568 of file TextMeshProUGUI\&.cs\&.
.SS "override void TMPro\&.TextMeshProUGUI\&.UpdateVertexData ()\fC [virtual]\fP"

.PP
Function to upload the updated vertex data and renderer\&. 
.PP
Reimplemented from \fBTMPro\&.TMP_Text\fP\&.
.PP
Definition at line 615 of file TextMeshProUGUI\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTMP_SubMeshUI\fP [] TMPro\&.TextMeshProUGUI\&.m_subTextObjects = new \fBTMP_SubMeshUI\fP[8]\fC [protected]\fP"

.PP
Definition at line 21 of file TMPro_UGUI_Private\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override bool TMPro\&.TextMeshProUGUI\&.autoSizeTextContainer\fC [get]\fP, \fC [set]\fP"

.PP
Determines if the size of the text container will be adjusted to fit the text object when it is first created\&. 
.PP
Definition at line 35 of file TextMeshProUGUI\&.cs\&.
.SS "new CanvasRenderer TMPro\&.TextMeshProUGUI\&.canvasRenderer\fC [get]\fP"

.PP
Reference to the CanvasRenderer used by the text object\&. 
.PP
Definition at line 56 of file TextMeshProUGUI\&.cs\&.
.SS "Vector4 TMPro\&.TextMeshProUGUI\&.maskOffset\fC [get]\fP, \fC [set]\fP"

.PP
Sets the masking offset from the bounds of the object 
.PP
Definition at line 309 of file TextMeshProUGUI\&.cs\&.
.SS "override Material TMPro\&.TextMeshProUGUI\&.materialForRendering\fC [get]\fP"

.PP
Get the material that will be used for rendering\&. 
.PP
Definition at line 27 of file TextMeshProUGUI\&.cs\&.
.SS "override Mesh TMPro\&.TextMeshProUGUI\&.mesh\fC [get]\fP"

.PP
Reference to the Mesh used by the text object\&. 
.PP
Definition at line 47 of file TextMeshProUGUI\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
