.TH "TMPro.TMP_Dropdown.DropdownItem" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_Dropdown.DropdownItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerEnterHandler, and ICancelHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "virtual void \fBOnCancel\fP (BaseEventData eventData)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTMP_Text\fP \fBtext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Image \fBimage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "RectTransform \fBrectTransform\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Toggle \fBtoggle\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file TMP_Dropdown\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void TMPro\&.TMP_Dropdown\&.DropdownItem\&.OnCancel (BaseEventData eventData)\fC [virtual]\fP"

.PP
Definition at line 37 of file TMP_Dropdown\&.cs\&.
.SS "virtual void TMPro\&.TMP_Dropdown\&.DropdownItem\&.OnPointerEnter (PointerEventData eventData)\fC [virtual]\fP"

.PP
Definition at line 32 of file TMP_Dropdown\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Image TMPro\&.TMP_Dropdown\&.DropdownItem\&.image\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 28 of file TMP_Dropdown\&.cs\&.
.SS "RectTransform TMPro\&.TMP_Dropdown\&.DropdownItem\&.rectTransform\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 29 of file TMP_Dropdown\&.cs\&.
.SS "\fBTMP_Text\fP TMPro\&.TMP_Dropdown\&.DropdownItem\&.text\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 27 of file TMP_Dropdown\&.cs\&.
.SS "Toggle TMPro\&.TMP_Dropdown\&.DropdownItem\&.toggle\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 30 of file TMP_Dropdown\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
