.TH "O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.textmeshpro@1.3.0/Scripts/Editor/TMPro_FontPlugin.cs" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.textmeshpro@1.3.0/Scripts/Editor/TMPro_FontPlugin.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTMPro\&.EditorUtilities\&.TMPro_FontPlugin\fP"
.br
.ti -1c
.RI "struct \fBTMPro\&.EditorUtilities\&.FT_KerningPair\fP"
.br
.ti -1c
.RI "struct \fBTMPro\&.EditorUtilities\&.FT_GlyphInfo\fP"
.br
.ti -1c
.RI "struct \fBTMPro\&.EditorUtilities\&.FT_FaceInfo\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTMPro\fP"
.br
.ti -1c
.RI "namespace \fBTMPro\&.EditorUtilities\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTMPro\&.EditorUtilities\&.FaceStyles\fP { \fBTMPro\&.EditorUtilities\&.FaceStyles\&.Normal\fP, \fBTMPro\&.EditorUtilities\&.FaceStyles\&.Bold\fP, \fBTMPro\&.EditorUtilities\&.FaceStyles\&.Italic\fP, \fBTMPro\&.EditorUtilities\&.FaceStyles\&.Bold_Italic\fP, \fBTMPro\&.EditorUtilities\&.FaceStyles\&.Outline\fP, \fBTMPro\&.EditorUtilities\&.FaceStyles\&.Bold_Sim\fP }"
.br
.ti -1c
.RI "enum \fBTMPro\&.EditorUtilities\&.RenderModes\fP { \fBTMPro\&.EditorUtilities\&.RenderModes\&.HintedSmooth\fP = 0, \fBTMPro\&.EditorUtilities\&.RenderModes\&.Smooth\fP = 1, \fBTMPro\&.EditorUtilities\&.RenderModes\&.RasterHinted\fP = 2, \fBTMPro\&.EditorUtilities\&.RenderModes\&.Raster\fP = 3, \fBTMPro\&.EditorUtilities\&.RenderModes\&.DistanceField16\fP = 6, \fBTMPro\&.EditorUtilities\&.RenderModes\&.DistanceField32\fP = 7 }"
.br
.ti -1c
.RI "enum \fBTMPro\&.EditorUtilities\&.CancellationRequestType\fP : byte { \fBTMPro\&.EditorUtilities\&.CancellationRequestType\&.None\fP = 0x0, \fBTMPro\&.EditorUtilities\&.CancellationRequestType\&.CancelInProgess\fP = 0x1, \fBTMPro\&.EditorUtilities\&.CancellationRequestType\&.WindowClosed\fP = 0x2 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
