.TH "TMPro.FloatTween" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.FloatTween
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTMPro\&.ITweenValue\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFloatTweenCallback\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTweenValue\fP (float floatPercentage)"
.br
.ti -1c
.RI "void \fBAddOnChangedCallback\fP (UnityAction< float > callback)"
.br
.ti -1c
.RI "bool \fBGetIgnoreTimescale\fP ()"
.br
.ti -1c
.RI "float \fBGetDuration\fP ()"
.br
.ti -1c
.RI "bool \fBValidTarget\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBstartValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBtargetValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBduration\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBignoreTimeScale\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 119 of file TMP_CoroutineTween\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMPro\&.FloatTween\&.AddOnChangedCallback (UnityAction< float > callback)"

.PP
Definition at line 163 of file TMP_CoroutineTween\&.cs\&.
.SS "float TMPro\&.FloatTween\&.GetDuration ()"

.PP
Definition at line 176 of file TMP_CoroutineTween\&.cs\&.
.SS "bool TMPro\&.FloatTween\&.GetIgnoreTimescale ()"

.PP
Definition at line 171 of file TMP_CoroutineTween\&.cs\&.
.SS "void TMPro\&.FloatTween\&.TweenValue (float floatPercentage)"

.PP
Implements \fBTMPro\&.ITweenValue\fP\&.
.PP
Definition at line 154 of file TMP_CoroutineTween\&.cs\&.
.SS "bool TMPro\&.FloatTween\&.ValidTarget ()"

.PP
Implements \fBTMPro\&.ITweenValue\fP\&.
.PP
Definition at line 181 of file TMP_CoroutineTween\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "float TMPro\&.FloatTween\&.duration\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 143 of file TMP_CoroutineTween\&.cs\&.
.SS "bool TMPro\&.FloatTween\&.ignoreTimeScale\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 149 of file TMP_CoroutineTween\&.cs\&.
.SS "float TMPro\&.FloatTween\&.startValue\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 131 of file TMP_CoroutineTween\&.cs\&.
.SS "float TMPro\&.FloatTween\&.targetValue\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 137 of file TMP_CoroutineTween\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
