.TH "TMPro.TMP_TextInfo" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_TextInfo \- Class which contains information about every element contained within the text object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTMP_TextInfo\fP ()"
.br
.ti -1c
.RI "\fBTMP_TextInfo\fP (\fBTMP_Text\fP \fBtextComponent\fP)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "Function to clear the counters of the text object\&. "
.ti -1c
.RI "void \fBClearMeshInfo\fP (bool updateMesh)"
.br
.RI "Function to clear the content of the MeshInfo array while preserving the Triangles, Normals and Tangents\&. "
.ti -1c
.RI "void \fBClearAllMeshInfo\fP ()"
.br
.RI "Function to clear the content of all the MeshInfo arrays while preserving their Triangles, Normals and Tangents\&. "
.ti -1c
.RI "void \fBResetVertexLayout\fP (bool isVolumetric)"
.br
.ti -1c
.RI "void \fBClearUnusedVertices\fP (\fBMaterialReference\fP[] materials)"
.br
.RI "Function used to mark unused vertices as degenerate\&. "
.ti -1c
.RI "void \fBClearLineInfo\fP ()"
.br
.RI "Function to clear and initialize the lineInfo array\&. "
.ti -1c
.RI "\fBTMP_MeshInfo\fP [] \fBCopyMeshInfoVertexData\fP ()"
.br
.RI "Function to copy the MeshInfo Arrays and their primary vertex data content\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBResize< T >\fP (ref T[] array, int size)"
.br
.RI "Function to resize any of the structure contained in the \fBTMP_TextInfo\fP class\&. "
.ti -1c
.RI "static void \fBResize< T >\fP (ref T[] array, int size, bool isBlockAllocated)"
.br
.RI "Function to resize any of the structure contained in the \fBTMP_TextInfo\fP class\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTMP_Text\fP \fBtextComponent\fP"
.br
.ti -1c
.RI "int \fBcharacterCount\fP"
.br
.ti -1c
.RI "int \fBspriteCount\fP"
.br
.ti -1c
.RI "int \fBspaceCount\fP"
.br
.ti -1c
.RI "int \fBwordCount\fP"
.br
.ti -1c
.RI "int \fBlinkCount\fP"
.br
.ti -1c
.RI "int \fBlineCount\fP"
.br
.ti -1c
.RI "int \fBpageCount\fP"
.br
.ti -1c
.RI "int \fBmaterialCount\fP"
.br
.ti -1c
.RI "\fBTMP_CharacterInfo\fP [] \fBcharacterInfo\fP"
.br
.ti -1c
.RI "\fBTMP_WordInfo\fP [] \fBwordInfo\fP"
.br
.ti -1c
.RI "\fBTMP_LinkInfo\fP [] \fBlinkInfo\fP"
.br
.ti -1c
.RI "\fBTMP_LineInfo\fP [] \fBlineInfo\fP"
.br
.ti -1c
.RI "\fBTMP_PageInfo\fP [] \fBpageInfo\fP"
.br
.ti -1c
.RI "\fBTMP_MeshInfo\fP [] \fBmeshInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class which contains information about every element contained within the text object\&. 


.PP
Definition at line 13 of file TMP_TextInfo\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMPro\&.TMP_TextInfo\&.TMP_TextInfo ()"

.PP
Definition at line 40 of file TMP_TextInfo\&.cs\&.
.SS "TMPro\&.TMP_TextInfo\&.TMP_TextInfo (\fBTMP_Text\fP textComponent)"

.PP
Definition at line 52 of file TMP_TextInfo\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void TMPro\&.TMP_TextInfo\&.Clear ()"

.PP
Function to clear the counters of the text object\&. 
.PP
Definition at line 73 of file TMP_TextInfo\&.cs\&.
.SS "void TMPro\&.TMP_TextInfo\&.ClearAllMeshInfo ()"

.PP
Function to clear the content of all the MeshInfo arrays while preserving their Triangles, Normals and Tangents\&. 
.PP
Definition at line 103 of file TMP_TextInfo\&.cs\&.
.SS "void TMPro\&.TMP_TextInfo\&.ClearLineInfo ()"

.PP
Function to clear and initialize the lineInfo array\&. 
.PP
Definition at line 137 of file TMP_TextInfo\&.cs\&.
.SS "void TMPro\&.TMP_TextInfo\&.ClearMeshInfo (bool updateMesh)"

.PP
Function to clear the content of the MeshInfo array while preserving the Triangles, Normals and Tangents\&. 
.PP
Definition at line 93 of file TMP_TextInfo\&.cs\&.
.SS "void TMPro\&.TMP_TextInfo\&.ClearUnusedVertices (\fBMaterialReference\fP [] materials)"

.PP
Function used to mark unused vertices as degenerate\&. 
.PP
\fBParameters:\fP
.RS 4
\fImaterials\fP 
.RE
.PP

.PP
Definition at line 124 of file TMP_TextInfo\&.cs\&.
.SS "\fBTMP_MeshInfo\fP [] TMPro\&.TMP_TextInfo\&.CopyMeshInfoVertexData ()"

.PP
Function to copy the MeshInfo Arrays and their primary vertex data content\&. 
.PP
\fBReturns:\fP
.RS 4
A copy of the MeshInfo[]
.RE
.PP

.PP
Definition at line 167 of file TMP_TextInfo\&.cs\&.
.SS "void TMPro\&.TMP_TextInfo\&.ResetVertexLayout (bool isVolumetric)"

.PP

.PP
Definition at line 113 of file TMP_TextInfo\&.cs\&.
.SS "static void TMPro\&.TMP_TextInfo\&.Resize< T > (ref T [] array, int size)\fC [static]\fP"

.PP
Function to resize any of the structure contained in the \fBTMP_TextInfo\fP class\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIarray\fP 
.br
\fIsize\fP 
.RE
.PP

.PP
Definition at line 228 of file TMP_TextInfo\&.cs\&.
.SS "static void TMPro\&.TMP_TextInfo\&.Resize< T > (ref T [] array, int size, bool isBlockAllocated)\fC [static]\fP"

.PP
Function to resize any of the structure contained in the \fBTMP_TextInfo\fP class\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIarray\fP 
.br
\fIsize\fP 
.br
\fIisFixedSize\fP 
.RE
.PP

.PP
Definition at line 244 of file TMP_TextInfo\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int TMPro\&.TMP_TextInfo\&.characterCount"

.PP
Definition at line 20 of file TMP_TextInfo\&.cs\&.
.SS "\fBTMP_CharacterInfo\fP [] TMPro\&.TMP_TextInfo\&.characterInfo"

.PP
Definition at line 30 of file TMP_TextInfo\&.cs\&.
.SS "int TMPro\&.TMP_TextInfo\&.lineCount"

.PP
Definition at line 25 of file TMP_TextInfo\&.cs\&.
.SS "\fBTMP_LineInfo\fP [] TMPro\&.TMP_TextInfo\&.lineInfo"

.PP
Definition at line 33 of file TMP_TextInfo\&.cs\&.
.SS "int TMPro\&.TMP_TextInfo\&.linkCount"

.PP
Definition at line 24 of file TMP_TextInfo\&.cs\&.
.SS "\fBTMP_LinkInfo\fP [] TMPro\&.TMP_TextInfo\&.linkInfo"

.PP
Definition at line 32 of file TMP_TextInfo\&.cs\&.
.SS "int TMPro\&.TMP_TextInfo\&.materialCount"

.PP
Definition at line 28 of file TMP_TextInfo\&.cs\&.
.SS "\fBTMP_MeshInfo\fP [] TMPro\&.TMP_TextInfo\&.meshInfo"

.PP
Definition at line 35 of file TMP_TextInfo\&.cs\&.
.SS "int TMPro\&.TMP_TextInfo\&.pageCount"

.PP
Definition at line 26 of file TMP_TextInfo\&.cs\&.
.SS "\fBTMP_PageInfo\fP [] TMPro\&.TMP_TextInfo\&.pageInfo"

.PP
Definition at line 34 of file TMP_TextInfo\&.cs\&.
.SS "int TMPro\&.TMP_TextInfo\&.spaceCount"

.PP
Definition at line 22 of file TMP_TextInfo\&.cs\&.
.SS "int TMPro\&.TMP_TextInfo\&.spriteCount"

.PP
Definition at line 21 of file TMP_TextInfo\&.cs\&.
.SS "\fBTMP_Text\fP TMPro\&.TMP_TextInfo\&.textComponent"

.PP
Definition at line 18 of file TMP_TextInfo\&.cs\&.
.SS "int TMPro\&.TMP_TextInfo\&.wordCount"

.PP
Definition at line 23 of file TMP_TextInfo\&.cs\&.
.SS "\fBTMP_WordInfo\fP [] TMPro\&.TMP_TextInfo\&.wordInfo"

.PP
Definition at line 31 of file TMP_TextInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
