.TH "UADSInAppPurchaseMetaData" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UADSInAppPurchaseMetaData
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <UADSInAppPurchaseMetaData\&.h>\fP
.PP
Inherits \fBUADSMetaData\fP\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(void) \- \fBsetProductId:\fP"
.br
.ti -1c
.RI "(void) \- \fBsetPrice:\fP"
.br
.ti -1c
.RI "(void) \- \fBsetCurrency:\fP"
.br
.ti -1c
.RI "(void) \- \fBsetReceiptPurchaseData:\fP"
.br
.ti -1c
.RI "(void) \- \fBsetSignature:\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file UADSInAppPurchaseMetaData\&.h\&.
.SH "Method Documentation"
.PP 
.SS "\- (void) setCurrency: (NSString *) currency"

.SS "\- (void) setPrice: (NSNumber *) price"

.SS "\- (void) setProductId: (NSString *) productId"

.SS "\- (void) setReceiptPurchaseData: (NSString *) receiptPurchaseData"

.SS "\- (void) setSignature: (NSString *) signature"


.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
