.TH "UnityEditor.CollabHistoryWindow" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.CollabHistoryWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow, and ICollabHistoryWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollabHistoryWindow\fP ()"
.br
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBSetupGUI\fP ()"
.br
.ti -1c
.RI "void \fBUpdateState\fP (HistoryState state, bool force)"
.br
.ti -1c
.RI "void \fBUpdateRevisions\fP (IEnumerable< RevisionData > datas, string tip, int totalRevisions, int currentPage)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShowHistoryWindow\fP ()"
.br
.ti -1c
.RI "static bool \fBValidateShowHistoryWindow\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBrevisionActionsEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBinProgressRevision\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBitemsPerPage\fP\fC [set]\fP"
.br
.ti -1c
.RI "PageChangeAction \fBOnPageChangeAction\fP\fC [set]\fP"
.br
.ti -1c
.RI "RevisionAction \fBOnGoBackAction\fP\fC [set]\fP"
.br
.ti -1c
.RI "RevisionAction \fBOnUpdateAction\fP\fC [set]\fP"
.br
.ti -1c
.RI "RevisionAction \fBOnRestoreAction\fP\fC [set]\fP"
.br
.ti -1c
.RI "ShowBuildAction \fBOnShowBuildAction\fP\fC [set]\fP"
.br
.ti -1c
.RI "Action \fBOnShowServicesAction\fP\fC [set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file CollabHistoryWindow\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEditor\&.CollabHistoryWindow\&.CollabHistoryWindow ()"

.PP
Definition at line 55 of file CollabHistoryWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.CollabHistoryWindow\&.OnDisable ()"

.PP
Definition at line 72 of file CollabHistoryWindow\&.cs\&.
.SS "void UnityEditor\&.CollabHistoryWindow\&.OnEnable ()"

.PP
Definition at line 60 of file CollabHistoryWindow\&.cs\&.
.SS "void UnityEditor\&.CollabHistoryWindow\&.SetupGUI ()"

.PP
Definition at line 103 of file CollabHistoryWindow\&.cs\&.
.SS "static void UnityEditor\&.CollabHistoryWindow\&.ShowHistoryWindow ()\fC [static]\fP"

.PP
Definition at line 33 of file CollabHistoryWindow\&.cs\&.
.SS "void UnityEditor\&.CollabHistoryWindow\&.UpdateRevisions (IEnumerable< RevisionData > datas, string tip, int totalRevisions, int currentPage)"

.PP
Definition at line 202 of file CollabHistoryWindow\&.cs\&.
.SS "void UnityEditor\&.CollabHistoryWindow\&.UpdateState (HistoryState state, bool force)"

.PP
Definition at line 182 of file CollabHistoryWindow\&.cs\&.
.SS "static bool UnityEditor\&.CollabHistoryWindow\&.ValidateShowHistoryWindow ()\fC [static]\fP"

.PP
Definition at line 39 of file CollabHistoryWindow\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string UnityEditor\&.CollabHistoryWindow\&.inProgressRevision\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 252 of file CollabHistoryWindow\&.cs\&.
.SS "int UnityEditor\&.CollabHistoryWindow\&.itemsPerPage\fC [set]\fP"

.PP
Definition at line 265 of file CollabHistoryWindow\&.cs\&.
.SS "RevisionAction UnityEditor\&.CollabHistoryWindow\&.OnGoBackAction\fC [set]\fP"

.PP
Definition at line 280 of file CollabHistoryWindow\&.cs\&.
.SS "PageChangeAction UnityEditor\&.CollabHistoryWindow\&.OnPageChangeAction\fC [set]\fP"

.PP
Definition at line 275 of file CollabHistoryWindow\&.cs\&.
.SS "RevisionAction UnityEditor\&.CollabHistoryWindow\&.OnRestoreAction\fC [set]\fP"

.PP
Definition at line 290 of file CollabHistoryWindow\&.cs\&.
.SS "ShowBuildAction UnityEditor\&.CollabHistoryWindow\&.OnShowBuildAction\fC [set]\fP"

.PP
Definition at line 295 of file CollabHistoryWindow\&.cs\&.
.SS "Action UnityEditor\&.CollabHistoryWindow\&.OnShowServicesAction\fC [set]\fP"

.PP
Definition at line 300 of file CollabHistoryWindow\&.cs\&.
.SS "RevisionAction UnityEditor\&.CollabHistoryWindow\&.OnUpdateAction\fC [set]\fP"

.PP
Definition at line 285 of file CollabHistoryWindow\&.cs\&.
.SS "bool UnityEditor\&.CollabHistoryWindow\&.revisionActionsEnabled\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 78 of file CollabHistoryWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
