.TH "O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.ads@2.0.8/Editor/Resources/iOS/builds/UnityAds.framework/Headers/UnityAds.h" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O:/GitHUBMINIPRoject/Library/PackageCache/com.unity.ads@2.0.8/Editor/Resources/iOS/builds/UnityAds.framework/Headers/UnityAds.h
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br
\fC#import <UnityAds/UADSMediationMetaData\&.h>\fP
.br
\fC#import <UnityAds/UADSPlayerMetaData\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "protocol \fB<UnityAdsDelegate>\fP"
.br
.ti -1c
.RI "class \fBUnityAds\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "typedef \fBNS_ENUM\fP (NSInteger, UnityAdsPlacementState)"
.br
.ti -1c
.RI "typedef \fBNS_ENUM\fP (NSInteger, UnityAdsFinishState)"
.br
.ti -1c
.RI "typedef \fBNS_ENUM\fP (NSInteger, UnityAdsError)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "typedef NS_ENUM (NSInteger, UnityAdsPlacementState)"
An enumerate that describes the state of \fC\fBUnityAds\fP\fP placements\&. 
.PP
\fBNote:\fP
.RS 4
All placement states, other than \fCkUnityAdsPlacementStateReady\fP, indicate that the placement is not currently ready to show ads\&. 
.RE
.PP
A state that indicates that the placement is ready to show an ad\&. The \fCshow:\fP selector can be called\&.
.PP
A state that indicates that no state is information is available\&. 
.PP
\fBWarning:\fP
.RS 4
This state can that \fBUnityAds\fP is not initialized or that the placement is not correctly configured in the Unity Ads admin tool\&.
.RE
.PP
A state that indicates that the placement is currently disabled\&. The placement can be enabled in the Unity Ads admin tools\&.
.PP
A state that indicates that the placement is not currently ready, but will be in the future\&. 
.PP
\fBNote:\fP
.RS 4
This state most likely indicates that the ad content is currently caching\&.
.RE
.PP
A state that indicates that the placement is properly configured, but there are currently no ads available for the placement\&.
.PP
Definition at line 10 of file UnityAds\&.h\&.
.SS "typedef NS_ENUM (NSInteger, UnityAdsFinishState)"
An enumeration for the completion state of an ad\&. A state that indicates that the ad did not successfully display\&.
.PP
A state that indicates that the user skipped the ad\&.
.PP
A state that indicates that the ad was played entirely\&.
.PP
Definition at line 38 of file UnityAds\&.h\&.
.SS "typedef NS_ENUM (NSInteger, UnityAdsError)"
An enumeration for the various errors that can be emitted through the \fC\fBUnityAdsDelegate\fP\fP \fCunityAdsDidError:withMessage:\fP method\&. An error that indicates failure due to \fC\fBUnityAds\fP\fP currently being uninitialized\&.
.PP
An error that indicates failure due to a failure in the initialization process\&.
.PP
An error that indicates failure due to attempting to initialize \fC\fBUnityAds\fP\fP with invalid parameters\&.
.PP
An error that indicates failure of the video player\&.
.PP
An error that indicates failure due to having attempted to initialize the \fC\fBUnityAds\fP\fP class in an invalid environment\&.
.PP
An error that indicates failure due to the presence of an ad blocker\&.
.PP
An error that indicates failure due to inability to read or write a file\&.
.PP
An error that indicates failure due to a bad device identifier\&.
.PP
An error that indicates a failure when attempting to show an ad\&.
.PP
An error that indicates an internal failure in \fC\fBUnityAds\fP\fP\&.
.PP
Definition at line 56 of file UnityAds\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
