.TH "UnityEditor.Collaboration.PagedListView" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.Collaboration.PagedListView
.SH SYNOPSIS
.br
.PP
.PP
Inherits VisualElement, and \fBUnityEditor\&.Collaboration\&.IPagerData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPagedListView\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBDefaultItemsPerPage\fP = 10"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBpageSize\fP\fC [set]\fP"
.br
.ti -1c
.RI "IEnumerable< VisualElement > \fBitems\fP\fC [set]\fP"
.br
.ti -1c
.RI "int \fBtotalItems\fP\fC [set]\fP"
.br
.ti -1c
.RI "PageChangeAction \fBOnPageChanged\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBcurPage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBtotalPages\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file PagedListView\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEditor\&.Collaboration\&.PagedListView\&.PagedListView ()"

.PP
Definition at line 120 of file PagedListView\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const int UnityEditor\&.Collaboration\&.PagedListView\&.DefaultItemsPerPage = 10"

.PP
Definition at line 83 of file PagedListView\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int UnityEditor\&.Collaboration\&.PagedListView\&.curPage\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 172 of file PagedListView\&.cs\&.
.SS "IEnumerable<VisualElement> UnityEditor\&.Collaboration\&.PagedListView\&.items\fC [set]\fP"

.PP
Definition at line 98 of file PagedListView\&.cs\&.
.SS "PageChangeAction UnityEditor\&.Collaboration\&.PagedListView\&.OnPageChanged\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 118 of file PagedListView\&.cs\&.
.SS "int UnityEditor\&.Collaboration\&.PagedListView\&.pageSize\fC [set]\fP"

.PP
Definition at line 93 of file PagedListView\&.cs\&.
.SS "int UnityEditor\&.Collaboration\&.PagedListView\&.totalItems\fC [set]\fP"

.PP
Definition at line 107 of file PagedListView\&.cs\&.
.SS "int UnityEditor\&.Collaboration\&.PagedListView\&.totalPages\fC [get]\fP"

.PP
Definition at line 182 of file PagedListView\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
