.TH "UnityEditor.PackageManager.UI.PackageManagerWindow" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.PackageManagerWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBPackagePath\fP = 'Packages/com\&.unity\&.package\-manager\-ui/'"
.br
.ti -1c
.RI "const string \fBResourcesPath\fP = \fBPackagePath\fP + 'Editor/Resources/'"
.br
.ti -1c
.RI "\fBPackageCollection\fP \fBCollection\fP"
.br
.ti -1c
.RI "\fBPackageSearchFilter\fP \fBSearchFilter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file PackageManagerWindow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPackageCollection\fP UnityEditor\&.PackageManager\&.UI\&.PackageManagerWindow\&.Collection"

.PP
Definition at line 18 of file PackageManagerWindow\&.cs\&.
.SS "const string UnityEditor\&.PackageManager\&.UI\&.PackageManagerWindow\&.PackagePath = 'Packages/com\&.unity\&.package\-manager\-ui/'"

.PP
Definition at line 10 of file PackageManagerWindow\&.cs\&.
.SS "const string UnityEditor\&.PackageManager\&.UI\&.PackageManagerWindow\&.ResourcesPath = \fBPackagePath\fP + 'Editor/Resources/'"

.PP
Definition at line 11 of file PackageManagerWindow\&.cs\&.
.SS "\fBPackageSearchFilter\fP UnityEditor\&.PackageManager\&.UI\&.PackageManagerWindow\&.SearchFilter"

.PP
Definition at line 19 of file PackageManagerWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
