.TH "UnityEditor.PackageManager.UI.PackageSearchToolbar" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.PackageSearchToolbar
.SH SYNOPSIS
.br
.PP
.PP
Inherits VisualElement\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPackageSearchToolbar\fP ()"
.br
.ti -1c
.RI "void \fBGrabFocus\fP ()"
.br
.ti -1c
.RI "new void \fBSetEnabled\fP (bool enable)"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action \fBOnFocusChange\fP = delegate { }"
.br
.ti -1c
.RI "Action< string > \fBOnSearchChange\fP = delegate { }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file PackageSearchToolbar\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEditor\&.PackageManager\&.UI\&.PackageSearchToolbar\&.PackageSearchToolbar ()"

.PP
Definition at line 32 of file PackageSearchToolbar\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.PackageManager\&.UI\&.PackageSearchToolbar\&.GrabFocus ()"

.PP
Definition at line 61 of file PackageSearchToolbar\&.cs\&.
.SS "new void UnityEditor\&.PackageManager\&.UI\&.PackageSearchToolbar\&.SetEnabled (bool enable)"

.PP
Definition at line 66 of file PackageSearchToolbar\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "Action UnityEditor\&.PackageManager\&.UI\&.PackageSearchToolbar\&.OnFocusChange = delegate { }"

.PP
Definition at line 24 of file PackageSearchToolbar\&.cs\&.
.SS "Action<string> UnityEditor\&.PackageManager\&.UI\&.PackageSearchToolbar\&.OnSearchChange = delegate { }"

.PP
Definition at line 25 of file PackageSearchToolbar\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
