.TH "UnityEditor.PackageManager.UI.Tests.MockAddOperation" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.Tests.MockAddOperation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.PackageManager\&.UI\&.Tests\&.MockOperation\fP, and \fBUnityEditor\&.PackageManager\&.UI\&.IAddOperation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMockAddOperation\fP (\fBMockOperationFactory\fP factory, \fBPackageInfo\fP packageInfo=null)"
.br
.ti -1c
.RI "void \fBAddPackageAsync\fP (\fBPackageInfo\fP packageInfo, Action< \fBPackageInfo\fP > doneCallbackAction=null, Action< Error > errorCallbackAction=null)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBPackageInfo\fP \fBPackageInfo\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "new Action< Error > \fBOnOperationError\fP = delegate { }"
.br
.ti -1c
.RI "new Action \fBOnOperationFinalized\fP = delegate { }"
.br
.ti -1c
.RI "Action< \fBPackageInfo\fP > \fBOnOperationSuccess\fP = delegate { }"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file MockAddOperation\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockAddOperation\&.MockAddOperation (\fBMockOperationFactory\fP factory, \fBPackageInfo\fP packageInfo = \fCnull\fP)"

.PP
Definition at line 14 of file MockAddOperation\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockAddOperation\&.AddPackageAsync (\fBPackageInfo\fP packageInfo, Action< \fBPackageInfo\fP > doneCallbackAction = \fCnull\fP, Action< Error > errorCallbackAction = \fCnull\fP)"

.PP
Implements \fBUnityEditor\&.PackageManager\&.UI\&.IAddOperation\fP\&.
.PP
Definition at line 19 of file MockAddOperation\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBPackageInfo\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockAddOperation\&.PackageInfo\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 12 of file MockAddOperation\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "new Action<Error> UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockAddOperation\&.OnOperationError = delegate { }"

.PP
Definition at line 8 of file MockAddOperation\&.cs\&.
.SS "new Action UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockAddOperation\&.OnOperationFinalized = delegate { }"

.PP
Definition at line 9 of file MockAddOperation\&.cs\&.
.SS "Action<\fBPackageInfo\fP> UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockAddOperation\&.OnOperationSuccess = delegate { }"

.PP
Definition at line 10 of file MockAddOperation\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
