.TH "UnityEditor.CollabToolbarButton" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.CollabToolbarButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits SubToolbar, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollabToolbarButton\fP ()"
.br
.ti -1c
.RI "override void \fBOnGUI\fP (Rect rect)"
.br
.ti -1c
.RI "void \fBOnCollabStateChanged\fP (CollabInfo info)"
.br
.ti -1c
.RI "void \fBUpdateCollabToolbarState\fP ()"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file CollabToolbarButton\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEditor\&.CollabToolbarButton\&.CollabToolbarButton ()"

.PP
Definition at line 98 of file CollabToolbarButton\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.CollabToolbarButton\&.Dispose ()"

.PP
Definition at line 287 of file CollabToolbarButton\&.cs\&.
.SS "void UnityEditor\&.CollabToolbarButton\&.OnCollabStateChanged (CollabInfo info)"

.PP
Definition at line 186 of file CollabToolbarButton\&.cs\&.
.SS "override void UnityEditor\&.CollabToolbarButton\&.OnGUI (Rect rect)"

.PP
Definition at line 128 of file CollabToolbarButton\&.cs\&.
.SS "void UnityEditor\&.CollabToolbarButton\&.UpdateCollabToolbarState ()"

.PP
Definition at line 191 of file CollabToolbarButton\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
