.TH "UnityEditor.WebViewStatic" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.WebViewStatic
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableSingleton< WebViewStatic >\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static WebView \fBGetWebView\fP ()"
.br
.ti -1c
.RI "static void \fBSetWebView\fP (WebView webView)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file CollabToolbarWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static WebView UnityEditor\&.WebViewStatic\&.GetWebView ()\fC [static]\fP"

.PP
Definition at line 14 of file CollabToolbarWindow\&.cs\&.
.SS "static void UnityEditor\&.WebViewStatic\&.SetWebView (WebView webView)\fC [static]\fP"

.PP
Definition at line 19 of file CollabToolbarWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
