.TH "UnityEditor.PackageManager.UI.Tests.PackageSets" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.Tests.PackageSets
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPackageInfo\fP \fBSingle\fP (string name=null, string version=null)"
.br
.ti -1c
.RI "\fBPackageInfo\fP \fBSingle\fP (PackageSource type, string name=null, string version=null, bool isCurrent=true, bool isVerified=false)"
.br
.ti -1c
.RI "List< \fBPackageInfo\fP > \fBMany\fP (int count, bool onlyPackageGroup=false)"
.br
.ti -1c
.RI "List< \fBPackageInfo\fP > \fBMany\fP (string name, int count, bool onlyPackageGroup=false)"
.br
.ti -1c
.RI "List< \fBPackageInfo\fP > \fBTestData\fP ()"
.br
.ti -1c
.RI "List< \fBPackageInfo\fP > \fBRealPackages\fP ()"
.br
.ti -1c
.RI "List< \fBPackageInfo\fP > \fBOutdated\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBPackageSets\fP \fBInstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file PackageSets\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "List<\fBPackageInfo\fP> UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSets\&.Many (int count, bool onlyPackageGroup = \fCfalse\fP)"

.PP
Definition at line 106 of file PackageSets\&.cs\&.
.SS "List<\fBPackageInfo\fP> UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSets\&.Many (string name, int count, bool onlyPackageGroup = \fCfalse\fP)"

.PP
Definition at line 111 of file PackageSets\&.cs\&.
.SS "List<\fBPackageInfo\fP> UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSets\&.Outdated ()"

.PP
Definition at line 262 of file PackageSets\&.cs\&.
.SS "List<\fBPackageInfo\fP> UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSets\&.RealPackages ()"

.PP
Definition at line 164 of file PackageSets\&.cs\&.
.SS "\fBPackageInfo\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSets\&.Single (string name = \fCnull\fP, string version = \fCnull\fP)"

.PP
Definition at line 66 of file PackageSets\&.cs\&.
.SS "\fBPackageInfo\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSets\&.Single (PackageSource type, string name = \fCnull\fP, string version = \fCnull\fP, bool isCurrent = \fCtrue\fP, bool isVerified = \fCfalse\fP)"

.PP
Definition at line 72 of file PackageSets\&.cs\&.
.SS "List<\fBPackageInfo\fP> UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSets\&.TestData ()"

.PP
Definition at line 152 of file PackageSets\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBPackageSets\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSets\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 10 of file PackageSets\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
