.TH "UnityEditor.PackageManager.UI.PackageInfo" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.PackageInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits IEquatable< PackageInfo >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBRedirectsToManual\fP (\fBPackageInfo\fP packageInfo)"
.br
.ti -1c
.RI "bool \fBHasChangelog\fP (\fBPackageInfo\fP packageInfo)"
.br
.ti -1c
.RI "string \fBGetDocumentationUrl\fP ()"
.br
.ti -1c
.RI "string \fBGetChangelogUrl\fP ()"
.br
.ti -1c
.RI "string \fBGetLicensesUrl\fP ()"
.br
.ti -1c
.RI "bool \fBEquals\fP (\fBPackageInfo\fP other)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.ti -1c
.RI "bool \fBHasVersionTag\fP (string tag)"
.br
.ti -1c
.RI "bool \fBHasVersionTag\fP (\fBPackageTag\fP tag)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetPackageUrlRedirect\fP (string packageName, string shortVersionId)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBName\fP"
.br
.ti -1c
.RI "string \fBDisplayName\fP"
.br
.ti -1c
.RI "\fBSemVersion\fP \fBVersion\fP"
.br
.ti -1c
.RI "string \fBDescription\fP"
.br
.ti -1c
.RI "string \fBCategory\fP"
.br
.ti -1c
.RI "\fBPackageState\fP \fBState\fP"
.br
.ti -1c
.RI "bool \fBIsCurrent\fP"
.br
.ti -1c
.RI "bool \fBIsLatest\fP"
.br
.ti -1c
.RI "string \fBGroup\fP"
.br
.ti -1c
.RI "PackageSource \fBOrigin\fP"
.br
.ti -1c
.RI "List< \fBError\fP > \fBErrors\fP"
.br
.ti -1c
.RI "bool \fBIsVerified\fP"
.br
.ti -1c
.RI "string \fBAuthor\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "PackageManager\&.PackageInfo \fBInfo\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBPackageId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBVersionId\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBShortVersionId\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBBuiltInDescription\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsPreRelease\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsPreview\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsUserVisible\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsInDevelopment\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsLocal\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsBuiltIn\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBVersionWithoutTag\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsVersionLocked\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBCanBeRemoved\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file PackageInfo\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.Equals (\fBPackageInfo\fP other)"

.PP
Definition at line 136 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.GetChangelogUrl ()"

.PP
Definition at line 122 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.GetDocumentationUrl ()"

.PP
Definition at line 108 of file PackageInfo\&.cs\&.
.SS "override int UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.GetHashCode ()"

.PP
Definition at line 146 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.GetLicensesUrl ()"

.PP
Definition at line 127 of file PackageInfo\&.cs\&.
.SS "static string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.GetPackageUrlRedirect (string packageName, string shortVersionId)\fC [static]\fP"

.PP
Definition at line 72 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.HasChangelog (\fBPackageInfo\fP packageInfo)"

.PP
Definition at line 102 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.HasVersionTag (string tag)"

.PP
Definition at line 151 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.HasVersionTag (\fBPackageTag\fP tag)"

.PP
Definition at line 159 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.RedirectsToManual (\fBPackageInfo\fP packageInfo)"

.PP
Definition at line 97 of file PackageInfo\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.Author"

.PP
Definition at line 29 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.Category"

.PP
Definition at line 21 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.Description"

.PP
Definition at line 20 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.DisplayName"

.PP
Definition at line 17 of file PackageInfo\&.cs\&.
.SS "List<\fBError\fP> UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.Errors"

.PP
Definition at line 27 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.Group"

.PP
Definition at line 25 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.IsCurrent"

.PP
Definition at line 23 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.IsLatest"

.PP
Definition at line 24 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.IsVerified"

.PP
Definition at line 28 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.Name"

.PP
Definition at line 16 of file PackageInfo\&.cs\&.
.SS "PackageSource UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.Origin"

.PP
Definition at line 26 of file PackageInfo\&.cs\&.
.SS "\fBPackageState\fP UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.State"

.PP
Definition at line 22 of file PackageInfo\&.cs\&.
.SS "\fBSemVersion\fP UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.Version"

.PP
Definition at line 19 of file PackageInfo\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.BuiltInDescription\fC [get]\fP"

.PP
Definition at line 50 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.CanBeRemoved\fC [get]\fP"

.PP
Definition at line 194 of file PackageInfo\&.cs\&.
.SS "PackageManager\&.PackageInfo UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.Info\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 31 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.IsBuiltIn\fC [get]\fP"

.PP
Definition at line 184 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.IsInDevelopment\fC [get]\fP"

.PP
Definition at line 182 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.IsLocal\fC [get]\fP"

.PP
Definition at line 183 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.IsPreRelease\fC [get]\fP"

.PP
Definition at line 167 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.IsPreview\fC [get]\fP"

.PP
Definition at line 172 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.IsUserVisible\fC [get]\fP"

.PP
Definition at line 178 of file PackageInfo\&.cs\&.
.SS "bool UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.IsVersionLocked\fC [get]\fP"

.PP
Definition at line 189 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.PackageId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 33 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.ShortVersionId\fC [get]\fP"

.PP
Definition at line 48 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.VersionId\fC [get]\fP"

.PP
Definition at line 47 of file PackageInfo\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageInfo\&.VersionWithoutTag\fC [get]\fP"

.PP
Definition at line 186 of file PackageInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
