.TH "UnityEditor.PackageManager.UI.Tests.PackageManagerWindowTests" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.Tests.PackageManagerWindowTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.PackageManager\&.UI\&.Tests\&.UITests< PackageManagerWindow >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP ()"
.br
.ti -1c
.RI "void \fBWhen_Default_FirstPackageUIElement_HasSelectedClass\fP ()"
.br
.ti -1c
.RI "void \fBWhen_PackageCollection_Updates_PackageList_Updates\fP ()"
.br
.ti -1c
.RI "void \fBWhen_PackageCollection_Update_Fails_Package_Stay_Current\fP ()"
.br
.ti -1c
.RI "void \fBWhen_PackageCollection_Remove_PackageLists_Updated\fP ()"
.br
.ti -1c
.RI "void \fBWhen_PackageCollection_Remove_Fails_PackageLists_NotUpdated\fP ()"
.br
.ti -1c
.RI "void \fBWhen_Filter_Changes_Shows_Correct_List\fP ()"
.br
.ti -1c
.RI "void \fBListPackages_UsesCache\fP ()"
.br
.ti -1c
.RI "void \fBSearchPackages_UsesCache\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file PackageManagerWindowTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageManagerWindowTests\&.ListPackages_UsesCache ()"

.PP
Definition at line 194 of file PackageManagerWindowTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageManagerWindowTests\&.SearchPackages_UsesCache ()"

.PP
Definition at line 203 of file PackageManagerWindowTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageManagerWindowTests\&.Setup ()"

.PP
Definition at line 16 of file PackageManagerWindowTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageManagerWindowTests\&.TearDown ()"

.PP
Definition at line 27 of file PackageManagerWindowTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageManagerWindowTests\&.When_Default_FirstPackageUIElement_HasSelectedClass ()"

.PP
Definition at line 34 of file PackageManagerWindowTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageManagerWindowTests\&.When_Filter_Changes_Shows_Correct_List ()"

.PP
Definition at line 172 of file PackageManagerWindowTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageManagerWindowTests\&.When_PackageCollection_Remove_Fails_PackageLists_NotUpdated ()"

.PP
Definition at line 147 of file PackageManagerWindowTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageManagerWindowTests\&.When_PackageCollection_Remove_PackageLists_Updated ()"

.PP
Definition at line 125 of file PackageManagerWindowTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageManagerWindowTests\&.When_PackageCollection_Update_Fails_Package_Stay_Current ()"

.PP
Definition at line 88 of file PackageManagerWindowTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageManagerWindowTests\&.When_PackageCollection_Updates_PackageList_Updates ()"

.PP
Definition at line 49 of file PackageManagerWindowTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
