.TH "UnityEditor.PackageManager.UI.PackageDetailsFactory" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.PackageDetailsFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits UxmlFactory< PackageDetails >\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override \fBPackageDetails\fP \fBDoCreate\fP (IUxmlAttributes bag, CreationContext cc)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file PackageDetails\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBPackageDetails\fP UnityEditor\&.PackageManager\&.UI\&.PackageDetailsFactory\&.DoCreate (IUxmlAttributes bag, CreationContext cc)\fC [protected]\fP"

.PP
Definition at line 12 of file PackageDetails\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
