.TH "UnityEditor.PackageManager.UI.OperationSignal< T >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.OperationSignal< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetOperation\fP (T operation)"
.br
.ti -1c
.RI "void \fBWhenOperation\fP (Action< T > callback)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBOperation\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< T > \fBOnOperation\fP = delegate { }"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBIBaseOperation\fP\fP
.PP
Definition at line 6 of file OperationSignal\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBUnityEditor\&.PackageManager\&.UI\&.OperationSignal\fP< T >\&.SetOperation (T operation)"

.PP
Definition at line 12 of file OperationSignal\&.cs\&.
.SS "void \fBUnityEditor\&.PackageManager\&.UI\&.OperationSignal\fP< T >\&.WhenOperation (Action< T > callback)"

.PP
Definition at line 18 of file OperationSignal\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "T \fBUnityEditor\&.PackageManager\&.UI\&.OperationSignal\fP< T >\&.Operation\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 10 of file OperationSignal\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "Action<T> \fBUnityEditor\&.PackageManager\&.UI\&.OperationSignal\fP< T >\&.OnOperation = delegate { }"

.PP
Definition at line 8 of file OperationSignal\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
