.TH "UnityEditor.Collaboration.Tests.TestRevisionsService" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.Collaboration.Tests.TestRevisionsService
.SH SYNOPSIS
.br
.PP
.PP
Inherits IRevisionsService\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetRevisions\fP (int offset, int count)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RevisionsResult \fBresult\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBtipRevision\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBcurrentUser\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "RevisionsDelegate \fBFetchRevisionsCallback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 542 of file HistoryTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.Collaboration\&.Tests\&.TestRevisionsService\&.GetRevisions (int offset, int count)"

.PP
Definition at line 550 of file HistoryTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "RevisionsResult UnityEditor\&.Collaboration\&.Tests\&.TestRevisionsService\&.result"

.PP
Definition at line 544 of file HistoryTests\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string UnityEditor\&.Collaboration\&.Tests\&.TestRevisionsService\&.currentUser\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 548 of file HistoryTests\&.cs\&.
.SS "string UnityEditor\&.Collaboration\&.Tests\&.TestRevisionsService\&.tipRevision\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 547 of file HistoryTests\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "RevisionsDelegate UnityEditor\&.Collaboration\&.Tests\&.TestRevisionsService\&.FetchRevisionsCallback"

.PP
Definition at line 545 of file HistoryTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
