.TH "UnityEditor.PackageManager.UI.Tests.PackageSearchTests" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.Tests.PackageSearchTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageBaseTests\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.ti -1c
.RI "void \fBMatchCriteria_NullOrEmptyCriteria_ReturnsTrue\fP (string criteria)"
.br
.ti -1c
.RI "void \fBMatchCriteria_CriteriaMatchDisplayNamePartially_ReturnsTrue\fP (string criteria)"
.br
.ti -1c
.RI "void \fBMatchCriteria_CriteriaMatchCurrentVersion_ReturnsTrue\fP (string criteria)"
.br
.ti -1c
.RI "void \fBMatchCriteria_CriteriaMatchCurrentVersionPreRelease_ReturnsTrue\fP (string criteria)"
.br
.ti -1c
.RI "void \fBMatchCriteria_CriteriaPartialMatchCurrentVersionPreRelease_ReturnsTrue\fP (string criteria)"
.br
.ti -1c
.RI "void \fBMatchCriteria_CriteriaPartialMatchCurrentVersionPreReleaseLeadingDash_ReturnsTrue\fP (string criteria)"
.br
.ti -1c
.RI "void \fBMatchCriteria_CriteriaPartialMatchVerified_ReturnsTrue\fP (string criteria)"
.br
.ti -1c
.RI "void \fBMatchCriteria_CriteriaDoesntMatch_ReturnsFalse\fP (string criteria)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file PackageSearchTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSearchTests\&.MatchCriteria_CriteriaDoesntMatch_ReturnsFalse (string criteria)"

.PP
Definition at line 103 of file PackageSearchTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSearchTests\&.MatchCriteria_CriteriaMatchCurrentVersion_ReturnsTrue (string criteria)"

.PP
Definition at line 43 of file PackageSearchTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSearchTests\&.MatchCriteria_CriteriaMatchCurrentVersionPreRelease_ReturnsTrue (string criteria)"

.PP
Definition at line 51 of file PackageSearchTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSearchTests\&.MatchCriteria_CriteriaMatchDisplayNamePartially_ReturnsTrue (string criteria)"

.PP
Definition at line 37 of file PackageSearchTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSearchTests\&.MatchCriteria_CriteriaPartialMatchCurrentVersionPreRelease_ReturnsTrue (string criteria)"

.PP
Definition at line 63 of file PackageSearchTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSearchTests\&.MatchCriteria_CriteriaPartialMatchCurrentVersionPreReleaseLeadingDash_ReturnsTrue (string criteria)"

.PP
Definition at line 75 of file PackageSearchTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSearchTests\&.MatchCriteria_CriteriaPartialMatchVerified_ReturnsTrue (string criteria)"

.PP
Definition at line 87 of file PackageSearchTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSearchTests\&.MatchCriteria_NullOrEmptyCriteria_ReturnsTrue (string criteria)"

.PP
Definition at line 31 of file PackageSearchTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSearchTests\&.Setup ()"

.PP
Definition at line 18 of file PackageSearchTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
