.TH "UnityEditor.PackageManager.UI" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTests\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlert\fP"
.br
.ti -1c
.RI "class \fBAlertFactory\fP"
.br
.ti -1c
.RI "class \fBApplicationUtil\fP"
.br
.ti -1c
.RI "interface \fBIAddOperation\fP"
.br
.ti -1c
.RI "interface \fBIBaseOperation\fP"
.br
.ti -1c
.RI "interface \fBIListOperation\fP"
.br
.ti -1c
.RI "interface \fBIOperationFactory\fP"
.br
.RI "This is the Interface we will use to create the facade we need for testing\&. In the case of the Fake factory, we can create fake operations with doctored data we use for our tests\&. "
.ti -1c
.RI "interface \fBIPackageManagerExtension\fP"
.br
.RI "Interface for \fBPackage\fP Manager \fBUI\fP Extension "
.ti -1c
.RI "interface \fBIRemoveOperation\fP"
.br
.ti -1c
.RI "interface \fBISearchOperation\fP"
.br
.ti -1c
.RI "class \fBLoadingSpinner\fP"
.br
.ti -1c
.RI "class \fBLoadingSpinnerFactory\fP"
.br
.ti -1c
.RI "class \fBOperationFactory\fP"
.br
.ti -1c
.RI "class \fBOperationSignal\fP"
.br
.ti -1c
.RI "class \fBPackage\fP"
.br
.ti -1c
.RI "class \fBPackageAddFromUrlField\fP"
.br
.ti -1c
.RI "class \fBPackageAddFromUrlFieldFactory\fP"
.br
.ti -1c
.RI "class \fBPackageAssetPostprocessor\fP"
.br
.ti -1c
.RI "class \fBPackageCollection\fP"
.br
.ti -1c
.RI "class \fBPackageDetails\fP"
.br
.ti -1c
.RI "class \fBPackageDetailsFactory\fP"
.br
.ti -1c
.RI "class \fBPackageError\fP"
.br
.ti -1c
.RI "class \fBPackageFiltering\fP"
.br
.ti -1c
.RI "class \fBPackageGroup\fP"
.br
.ti -1c
.RI "class \fBPackageGroupFactory\fP"
.br
.ti -1c
.RI "class \fBPackageInfo\fP"
.br
.ti -1c
.RI "class \fBPackageInfoListExtensions\fP"
.br
.ti -1c
.RI "class \fBPackageItem\fP"
.br
.ti -1c
.RI "class \fBPackageItemFactory\fP"
.br
.ti -1c
.RI "class \fBPackageJsonHelper\fP"
.br
.ti -1c
.RI "class \fBPackageList\fP"
.br
.ti -1c
.RI "class \fBPackageListExtensions\fP"
.br
.ti -1c
.RI "class \fBPackageListFactory\fP"
.br
.ti -1c
.RI "class \fBPackageManagerExtensions\fP"
.br
.RI "\fBPackage\fP Manager \fBUI\fP Extensions "
.ti -1c
.RI "class \fBPackageManagerPrefs\fP"
.br
.ti -1c
.RI "class \fBPackageManagerToolbar\fP"
.br
.ti -1c
.RI "class \fBPackageManagerWindow\fP"
.br
.ti -1c
.RI "class \fBPackageManangerToolbarFactory\fP"
.br
.ti -1c
.RI "class \fBPackageSearchFilter\fP"
.br
.ti -1c
.RI "class \fBPackageSearchToolbar\fP"
.br
.ti -1c
.RI "class \fBPackageSearchToolbarFactory\fP"
.br
.ti -1c
.RI "class \fBPackageStatusBar\fP"
.br
.ti -1c
.RI "class \fBPackageStatusBarFactory\fP"
.br
.ti -1c
.RI "class \fBPopupField\fP"
.br
.ti -1c
.RI "class \fBResources\fP"
.br
.ti -1c
.RI "class \fBThreadedDelay\fP"
.br
.ti -1c
.RI "class \fBUIUtils\fP"
.br
.ti -1c
.RI "class \fBUpmAddOperation\fP"
.br
.ti -1c
.RI "class \fBUpmBaseOperation\fP"
.br
.ti -1c
.RI "class \fBUpmListOperation\fP"
.br
.ti -1c
.RI "class \fBUpmOperationFactory\fP"
.br
.ti -1c
.RI "class \fBUpmRemoveOperation\fP"
.br
.ti -1c
.RI "class \fBUpmSearchOperation\fP"
.br
.ti -1c
.RI "class \fBVersionItem\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPackageFilter\fP { \fBPackageFilter\&.None\fP, \fBPackageFilter\&.All\fP, \fBPackageFilter\&.Local\fP, \fBPackageFilter\&.Modules\fP }"
.br
.ti -1c
.RI "enum \fBPackageGroupOrigins\fP { \fBPackageGroupOrigins\&.Packages\fP, \fBPackageGroupOrigins\&.BuiltInPackages\fP }"
.br
.ti -1c
.RI "enum \fBPackageOrigin\fP { \fBPackageOrigin\&.Unknown\fP, \fBPackageOrigin\&.Builtin\fP, \fBPackageOrigin\&.Registry\fP }"
.br
.ti -1c
.RI "enum \fBPackageState\fP { \fBPackageState\&.UpToDate\fP, \fBPackageState\&.Outdated\fP, \fBPackageState\&.InProgress\fP, \fBPackageState\&.Error\fP }"
.br
.ti -1c
.RI "enum \fBPackageTag\fP { \fBPackageTag\&.preview\fP, \fBPackageTag\&.verified\fP, \fBPackageTag\&.inDevelopment\fP, \fBPackageTag\&.local\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBUnityEditor\&.PackageManager\&.UI\&.PackageFilter\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIAll \fP\fP
.TP
\fB\fILocal \fP\fP
.TP
\fB\fIModules \fP\fP
.PP
Definition at line 6 of file PackageFilter\&.cs\&.
.SS "enum \fBUnityEditor\&.PackageManager\&.UI\&.PackageGroupOrigins\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPackages \fP\fP
.TP
\fB\fIBuiltInPackages \fP\fP
.PP
Definition at line 3 of file PackageGroupOrigins\&.cs\&.
.SS "enum \fBUnityEditor\&.PackageManager\&.UI\&.PackageOrigin\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUnknown \fP\fP
.TP
\fB\fIBuiltin \fP\fP
.TP
\fB\fIRegistry \fP\fP
.PP
Definition at line 3 of file PackageOrigin\&.cs\&.
.SS "enum \fBUnityEditor\&.PackageManager\&.UI\&.PackageState\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUpToDate \fP\fP
.TP
\fB\fIOutdated \fP\fP
.TP
\fB\fIInProgress \fP\fP
.TP
\fB\fIError \fP\fP
.PP
Definition at line 3 of file PackageState\&.cs\&.
.SS "enum \fBUnityEditor\&.PackageManager\&.UI\&.PackageTag\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIpreview \fP\fP
.TP
\fB\fIverified \fP\fP
.TP
\fB\fIinDevelopment \fP\fP
.TP
\fB\fIlocal \fP\fP
.PP
Definition at line 3 of file PackageTag\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
