.TH "UnityEditor.PackageManager.UI.Tests.MockOperationFactory" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.Tests.MockOperationFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.PackageManager\&.UI\&.IOperationFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMockOperationFactory\fP ()"
.br
.ti -1c
.RI "void \fBResetOperations\fP ()"
.br
.ti -1c
.RI "\fBIListOperation\fP \fBCreateListOperation\fP (bool offlineMode=false)"
.br
.ti -1c
.RI "\fBISearchOperation\fP \fBCreateSearchOperation\fP ()"
.br
.ti -1c
.RI "\fBIAddOperation\fP \fBCreateAddOperation\fP ()"
.br
.ti -1c
.RI "\fBIRemoveOperation\fP \fBCreateRemoveOperation\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IEnumerable< \fBPackageInfo\fP > \fBPackages\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMockAddOperation\fP \fBAddOperation\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMockSearchOperation\fP \fBSearchOperation\fP\fC [set]\fP"
.br
.ti -1c
.RI "\fBMockRemoveOperation\fP \fBRemoveOperation\fP\fC [set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file MockOperationFactory\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockOperationFactory\&.MockOperationFactory ()"

.PP
Definition at line 13 of file MockOperationFactory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIAddOperation\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockOperationFactory\&.CreateAddOperation ()"

.PP
Implements \fBUnityEditor\&.PackageManager\&.UI\&.IOperationFactory\fP\&.
.PP
Definition at line 41 of file MockOperationFactory\&.cs\&.
.SS "\fBIListOperation\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockOperationFactory\&.CreateListOperation (bool offlineMode = \fCfalse\fP)"

.PP
Implements \fBUnityEditor\&.PackageManager\&.UI\&.IOperationFactory\fP\&.
.PP
Definition at line 31 of file MockOperationFactory\&.cs\&.
.SS "\fBIRemoveOperation\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockOperationFactory\&.CreateRemoveOperation ()"

.PP
Implements \fBUnityEditor\&.PackageManager\&.UI\&.IOperationFactory\fP\&.
.PP
Definition at line 46 of file MockOperationFactory\&.cs\&.
.SS "\fBISearchOperation\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockOperationFactory\&.CreateSearchOperation ()"

.PP
Implements \fBUnityEditor\&.PackageManager\&.UI\&.IOperationFactory\fP\&.
.PP
Definition at line 36 of file MockOperationFactory\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockOperationFactory\&.ResetOperations ()"

.PP
Definition at line 18 of file MockOperationFactory\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBMockAddOperation\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockOperationFactory\&.AddOperation\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 9 of file MockOperationFactory\&.cs\&.
.SS "IEnumerable<\fBPackageInfo\fP> UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockOperationFactory\&.Packages\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 8 of file MockOperationFactory\&.cs\&.
.SS "\fBMockRemoveOperation\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockOperationFactory\&.RemoveOperation\fC [set]\fP"

.PP
Definition at line 11 of file MockOperationFactory\&.cs\&.
.SS "\fBMockSearchOperation\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.MockOperationFactory\&.SearchOperation\fC [set]\fP"

.PP
Definition at line 10 of file MockOperationFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
