.TH "UnityEditor.PackageManager.UI.Tests.PackageTests" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.Tests.PackageTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageBaseTests\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPackageInfo\fP \fBDisplay\fP (\fBPackage\fP package)"
.br
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithNullPackageName_ThrowsException\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithEmptyPackageName_ThrowsException\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithNullPackageInfos_ThrowsException\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithEmptyPackageInfos_ThrowsException\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithOnePackageInfo_CurrentIsFirstVersion\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithOnePackageInfo_LatestIsLastVersion\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithOnePackageInfo_LatestAndCurrentAreEqual\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithTwoPackageInfos_CurrentIsFirstVersion\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithTwoPackageInfos_LatestIsLastVersion\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithTwoPackagesInfo_LatestAndCurrentAreNotEqual\fP ()"
.br
.ti -1c
.RI "void \fBConstructor_WithMultiplePackagesInfo_VersionsCorrespond\fP ()"
.br
.ti -1c
.RI "void \fBAdd_WhenPackageInfoIsCurrent_AddOperationIsNotCalled\fP ()"
.br
.ti -1c
.RI "void \fBAdd_WhenPackageInfoIsNotCurrent_AddOperationIsCalled\fP ()"
.br
.ti -1c
.RI "void \fBUpdate_WhenCurrentIsLatest_AddOperationIsNotCalled\fP ()"
.br
.ti -1c
.RI "void \fBUpdate_WhenCurrentIsNotLatest_AddOperationIsCalled\fP ()"
.br
.ti -1c
.RI "void \fBRemove_RemoveOperationIsCalled\fP ()"
.br
.ti -1c
.RI "void \fBIsPackageManagerUI_WhenPackageManagerUIPackage_ReturnsTrue\fP ()"
.br
.ti -1c
.RI "void \fBIsPackageManagerUI_WhenNotPackageManagerUIPackage_ReturnsFalse\fP ()"
.br
.ti -1c
.RI "void \fBName_ReturnsExpectedValue\fP ()"
.br
.ti -1c
.RI "void \fBDisplay_WhenCurrentIsNotNull_ReturnsCurrent\fP ()"
.br
.ti -1c
.RI "void \fBDisplay_WhenCurrentIsNull_ReturnsLatest\fP ()"
.br
.ti -1c
.RI "void \fBDisplay_WhenCurrentAndLatest_ReturnsLatest\fP ()"
.br
.ti -1c
.RI "void \fBVersions_WhenOrderedPackageInfo_ReturnsOrderedValues\fP ()"
.br
.ti -1c
.RI "void \fBVersions_WhenUnorderedPackageInfo_ReturnsOrderedValues\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_Current_lessthen_Verified\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_Current_equalto_Verified\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_Current_greaterthen_Verified\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_Current_greaterthen_Verified_WithLatest\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_NoVerified_Current_lessthen_Latest\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_NoVerified_Current_equalto_Latest\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_NoCurrent_WithVerified\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_NoCurrent_Latest\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_NoCurrent_Latest_WithPreview\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_NoCurrent_Verified_WithPreview\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_NoCurrent_OnlyPreviews\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_CurrentPreview_WithVerified\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_CurrentPreview_WithLatestPreview\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_CurrentPreview_WithLatestPreviewNoVerified\fP ()"
.br
.ti -1c
.RI "void \fBVersionUpdate_CurrentEmbedded\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file PackageTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Add_WhenPackageInfoIsCurrent_AddOperationIsNotCalled ()"

.PP
Definition at line 140 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Add_WhenPackageInfoIsNotCurrent_AddOperationIsCalled ()"

.PP
Definition at line 160 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Constructor_WithEmptyPackageInfos_ThrowsException ()"

.PP
Definition at line 63 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Constructor_WithEmptyPackageName_ThrowsException ()"

.PP
Definition at line 44 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Constructor_WithMultiplePackagesInfo_VersionsCorrespond ()"

.PP
Definition at line 131 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Constructor_WithNullPackageInfos_ThrowsException ()"

.PP
Definition at line 54 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Constructor_WithNullPackageName_ThrowsException ()"

.PP
Definition at line 34 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Constructor_WithOnePackageInfo_CurrentIsFirstVersion ()"

.PP
Definition at line 73 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Constructor_WithOnePackageInfo_LatestAndCurrentAreEqual ()"

.PP
Definition at line 93 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Constructor_WithOnePackageInfo_LatestIsLastVersion ()"

.PP
Definition at line 83 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Constructor_WithTwoPackageInfos_CurrentIsFirstVersion ()"

.PP
Definition at line 102 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Constructor_WithTwoPackageInfos_LatestIsLastVersion ()"

.PP
Definition at line 112 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Constructor_WithTwoPackagesInfo_LatestAndCurrentAreNotEqual ()"

.PP
Definition at line 122 of file PackageTests\&.cs\&.
.SS "\fBPackageInfo\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Display (\fBPackage\fP package)"

.PP
Definition at line 15 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Display_WhenCurrentAndLatest_ReturnsLatest ()"

.PP
Definition at line 290 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Display_WhenCurrentIsNotNull_ReturnsCurrent ()"

.PP
Definition at line 271 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Display_WhenCurrentIsNull_ReturnsLatest ()"

.PP
Definition at line 280 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.IsPackageManagerUI_WhenNotPackageManagerUIPackage_ReturnsFalse ()"

.PP
Definition at line 253 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.IsPackageManagerUI_WhenPackageManagerUIPackage_ReturnsTrue ()"

.PP
Definition at line 241 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Name_ReturnsExpectedValue ()"

.PP
Definition at line 262 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Remove_RemoveOperationIsCalled ()"

.PP
Definition at line 221 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Setup ()"

.PP
Definition at line 21 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.TearDown ()"

.PP
Definition at line 27 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Update_WhenCurrentIsLatest_AddOperationIsNotCalled ()"

.PP
Definition at line 180 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Update_WhenCurrentIsNotLatest_AddOperationIsCalled ()"

.PP
Definition at line 200 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Versions_WhenOrderedPackageInfo_ReturnsOrderedValues ()"

.PP
Definition at line 301 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.Versions_WhenUnorderedPackageInfo_ReturnsOrderedValues ()"

.PP
Definition at line 310 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_Current_equalto_Verified ()"

.PP
Definition at line 345 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_Current_greaterthen_Verified ()"

.PP
Definition at line 357 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_Current_greaterthen_Verified_WithLatest ()"

.PP
Definition at line 369 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_Current_lessthen_Verified ()"

.PP
Definition at line 332 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_CurrentEmbedded ()"

.PP
Definition at line 510 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_CurrentPreview_WithLatestPreview ()"

.PP
Definition at line 482 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_CurrentPreview_WithLatestPreviewNoVerified ()"

.PP
Definition at line 496 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_CurrentPreview_WithVerified ()"

.PP
Definition at line 469 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_NoCurrent_Latest ()"

.PP
Definition at line 419 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_NoCurrent_Latest_WithPreview ()"

.PP
Definition at line 431 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_NoCurrent_OnlyPreviews ()"

.PP
Definition at line 457 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_NoCurrent_Verified_WithPreview ()"

.PP
Definition at line 444 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_NoCurrent_WithVerified ()"

.PP
Definition at line 407 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_NoVerified_Current_equalto_Latest ()"

.PP
Definition at line 395 of file PackageTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\&.VersionUpdate_NoVerified_Current_lessthen_Latest ()"

.PP
Definition at line 382 of file PackageTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
