.TH "UnityEditor.PackageManager.UI.Tests.PackageBaseTests" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.Tests.PackageBaseTests
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageCollectionTests\fP, \fBUnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageInfoTests\fP, \fBUnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageSearchTests\fP, and \fBUnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageTests\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOneTimeSetup\fP ()"
.br
.ti -1c
.RI "void \fBOneTimeTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBMockOperationFactory\fP \fBFactory\fP"
.br
.ti -1c
.RI "const string \fBkPackageTestName\fP = 'com\&.unity\&.test'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file PackageBaseTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageBaseTests\&.OneTimeSetup ()"

.PP
Definition at line 12 of file PackageBaseTests\&.cs\&.
.SS "void UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageBaseTests\&.OneTimeTearDown ()"

.PP
Definition at line 19 of file PackageBaseTests\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMockOperationFactory\fP UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageBaseTests\&.Factory\fC [protected]\fP"

.PP
Definition at line 7 of file PackageBaseTests\&.cs\&.
.SS "const string UnityEditor\&.PackageManager\&.UI\&.Tests\&.PackageBaseTests\&.kPackageTestName = 'com\&.unity\&.test'\fC [protected]\fP"

.PP
Definition at line 8 of file PackageBaseTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
