.TH "UnityEditor.Collaboration.Tests.HistoryTests" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.Collaboration.Tests.HistoryTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__PropagatesRevisionResult\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__RevisionNumberingIsInOrder\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__RevisionNumberingChangesForMorePages\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__ObtainedIsCalculated\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__CurrentIsCalculated\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__InProgressIsCalculated\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__EnabledIsCalculated\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__DisabledIsCalculated\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__BuildStateHasNoneWhenNotTip\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__BuildStateTipHasNoneWhenEnabled\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__BuildStateHasConfigureWhenTip\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__BuildStateHasConfigureWhenZeroBuildStatus\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__BuildStateHasNoneWhenZeroBuildStatuses\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__BuildStateHasSuccessWhenCompleteAndSucceeded\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__BuildStateHasInProgress\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__BuildStateHasFailure\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__BuildStateHasFailureWhenAnyBuildsFail\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__ChangesPropagateThrough\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__ChangesTotalIsCalculated\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__ChangesTruncatedIsCalculated\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__OnlyKeeps10ChangeActions\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__DeduplicatesMetaFiles\fP ()"
.br
.ti -1c
.RI "void \fBCollabHistoryPresenter_OnUpdatePage__FolderMetaFilesAreCounted\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file HistoryTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__BuildStateHasConfigureWhenTip ()"

.PP
Definition at line 239 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__BuildStateHasConfigureWhenZeroBuildStatus ()"

.PP
Definition at line 258 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__BuildStateHasFailure ()"

.PP
Definition at line 348 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__BuildStateHasFailureWhenAnyBuildsFail ()"

.PP
Definition at line 374 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__BuildStateHasInProgress ()"

.PP
Definition at line 322 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__BuildStateHasNoneWhenNotTip ()"

.PP
Definition at line 201 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__BuildStateHasNoneWhenZeroBuildStatuses ()"

.PP
Definition at line 277 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__BuildStateHasSuccessWhenCompleteAndSucceeded ()"

.PP
Definition at line 296 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__BuildStateTipHasNoneWhenEnabled ()"

.PP
Definition at line 220 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__ChangesPropagateThrough ()"

.PP
Definition at line 402 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__ChangesTotalIsCalculated ()"

.PP
Definition at line 422 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__ChangesTruncatedIsCalculated ()"

.PP
Definition at line 439 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__CurrentIsCalculated ()"

.PP
Definition at line 121 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__DeduplicatesMetaFiles ()"

.PP
Definition at line 478 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__DisabledIsCalculated ()"

.PP
Definition at line 183 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__EnabledIsCalculated ()"

.PP
Definition at line 165 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__FolderMetaFilesAreCounted ()"

.PP
Definition at line 507 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__InProgressIsCalculated ()"

.PP
Definition at line 143 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__ObtainedIsCalculated ()"

.PP
Definition at line 102 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__OnlyKeeps10ChangeActions ()"

.PP
Definition at line 459 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__PropagatesRevisionResult ()"

.PP
Definition at line 33 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__RevisionNumberingChangesForMorePages ()"

.PP
Definition at line 76 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.CollabHistoryPresenter_OnUpdatePage__RevisionNumberingIsInOrder ()"

.PP
Definition at line 52 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.SetUp ()"

.PP
Definition at line 20 of file HistoryTests\&.cs\&.
.SS "void UnityEditor\&.Collaboration\&.Tests\&.HistoryTests\&.TearDown ()"

.PP
Definition at line 28 of file HistoryTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
