.TH "UnityEditor.PackageManager.UI.PackageError" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.PackageError
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPackageError\fP (string packageName, \fBError\fP error)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBPackageName\fP"
.br
.ti -1c
.RI "Error \fBError\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file PackageError\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEditor\&.PackageManager\&.UI\&.PackageError\&.PackageError (string packageName, \fBError\fP error)"

.PP
Definition at line 11 of file PackageError\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Error UnityEditor\&.PackageManager\&.UI\&.PackageError\&.Error"

.PP
Definition at line 9 of file PackageError\&.cs\&.
.SS "string UnityEditor\&.PackageManager\&.UI\&.PackageError\&.PackageName"

.PP
Definition at line 8 of file PackageError\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
