.TH "UnityEditor.Collaboration.ICollabHistoryItemFactory" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.Collaboration.ICollabHistoryItemFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUnityEditor\&.Collaboration\&.CollabHistoryItemFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "IEnumerable< RevisionData > \fBGenerateElements\fP (IEnumerable< Revision > revsRevisions, int mTotalRevisions, int startIndex, string tipRev, string inProgressRevision, bool revisionActionsEnabled, bool buildServiceEnabled, string currentUser)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file ICollabHistoryItemFactory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "IEnumerable<RevisionData> UnityEditor\&.Collaboration\&.ICollabHistoryItemFactory\&.GenerateElements (IEnumerable< Revision > revsRevisions, int mTotalRevisions, int startIndex, string tipRev, string inProgressRevision, bool revisionActionsEnabled, bool buildServiceEnabled, string currentUser)"

.PP
Implemented in \fBUnityEditor\&.Collaboration\&.CollabHistoryItemFactory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
