.TH "UnityEditor.PackageManager.UI.PackageGroup" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.PackageGroup
.SH SYNOPSIS
.br
.PP
.PP
Inherits VisualElement\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPackageGroup\fP ()"
.br
.ti -1c
.RI "\fBPackageGroup\fP (string groupName)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPackageGroup\fP \fBpreviousGroup\fP"
.br
.ti -1c
.RI "\fBPackageGroup\fP \fBnextGroup\fP"
.br
.ti -1c
.RI "\fBPackageItem\fP \fBfirstPackage\fP"
.br
.ti -1c
.RI "\fBPackageItem\fP \fBlastPackage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file PackageGroup\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnityEditor\&.PackageManager\&.UI\&.PackageGroup\&.PackageGroup ()"

.PP
Definition at line 31 of file PackageGroup\&.cs\&.
.SS "UnityEditor\&.PackageManager\&.UI\&.PackageGroup\&.PackageGroup (string groupName)"

.PP
Definition at line 35 of file PackageGroup\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPackageItem\fP UnityEditor\&.PackageManager\&.UI\&.PackageGroup\&.firstPackage"

.PP
Definition at line 28 of file PackageGroup\&.cs\&.
.SS "\fBPackageItem\fP UnityEditor\&.PackageManager\&.UI\&.PackageGroup\&.lastPackage"

.PP
Definition at line 29 of file PackageGroup\&.cs\&.
.SS "\fBPackageGroup\fP UnityEditor\&.PackageManager\&.UI\&.PackageGroup\&.nextGroup"

.PP
Definition at line 26 of file PackageGroup\&.cs\&.
.SS "\fBPackageGroup\fP UnityEditor\&.PackageManager\&.UI\&.PackageGroup\&.previousGroup"

.PP
Definition at line 25 of file PackageGroup\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
