.TH "UnityEditor.PackageManager.UI.IPackageManagerExtension" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.PackageManager.UI.IPackageManagerExtension \- Interface for \fBPackage\fP Manager \fBUI\fP Extension  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "VisualElement \fBCreateExtensionUI\fP ()"
.br
.RI "Creates the extension \fBUI\fP visual element\&. "
.ti -1c
.RI "void \fBOnPackageSelectionChange\fP (PackageManager\&.PackageInfo packageInfo)"
.br
.RI "Called by the \fBPackage\fP Manager \fBUI\fP when the package selection changed\&. "
.ti -1c
.RI "void \fBOnPackageAddedOrUpdated\fP (PackageManager\&.PackageInfo packageInfo)"
.br
.RI "Called by the \fBPackage\fP Manager \fBUI\fP when a package is added or updated\&. "
.ti -1c
.RI "void \fBOnPackageRemoved\fP (PackageManager\&.PackageInfo packageInfo)"
.br
.RI "Called by the \fBPackage\fP Manager \fBUI\fP when a package is removed\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface for \fBPackage\fP Manager \fBUI\fP Extension 


.PP
Definition at line 8 of file IPackageManagerExtension\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "VisualElement UnityEditor\&.PackageManager\&.UI\&.IPackageManagerExtension\&.CreateExtensionUI ()"

.PP
Creates the extension \fBUI\fP visual element\&. 
.PP
\fBReturns:\fP
.RS 4
A visual element that represents the \fBUI\fP or null if none
.RE
.PP

.SS "void UnityEditor\&.PackageManager\&.UI\&.IPackageManagerExtension\&.OnPackageAddedOrUpdated (PackageManager\&.PackageInfo packageInfo)"

.PP
Called by the \fBPackage\fP Manager \fBUI\fP when a package is added or updated\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpackageInfo\fP The package information
.RE
.PP

.SS "void UnityEditor\&.PackageManager\&.UI\&.IPackageManagerExtension\&.OnPackageRemoved (PackageManager\&.PackageInfo packageInfo)"

.PP
Called by the \fBPackage\fP Manager \fBUI\fP when a package is removed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpackageInfo\fP The package information
.RE
.PP

.SS "void UnityEditor\&.PackageManager\&.UI\&.IPackageManagerExtension\&.OnPackageSelectionChange (PackageManager\&.PackageInfo packageInfo)"

.PP
Called by the \fBPackage\fP Manager \fBUI\fP when the package selection changed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpackageInfo\fP The newly selected package information (can be null)
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
