.TH "UnityEditor.CollabToolbarWindow" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityEditor.CollabToolbarWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits WebViewEditorStaticWindow, and IHasCustomMenu\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnReceiveTitle\fP (string title)"
.br
.ti -1c
.RI "new void \fBOnInitScripting\fP ()"
.br
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "new void \fBOnDestroy\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCloseToolbar\fP ()"
.br
.ti -1c
.RI "static \fBCollabToolbarWindow\fP \fBShowToolbarWindow\fP ()"
.br
.ti -1c
.RI "static bool \fBValidateShowToolbarWindow\fP ()"
.br
.ti -1c
.RI "static bool \fBIsVisible\fP ()"
.br
.ti -1c
.RI "static bool \fBShowCenteredAtPosition\fP (Rect buttonRect)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBs_ToolbarIsVisible\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file CollabToolbarWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void UnityEditor\&.CollabToolbarWindow\&.CloseToolbar ()\fC [static]\fP"

.PP
Definition at line 44 of file CollabToolbarWindow\&.cs\&.
.SS "static bool UnityEditor\&.CollabToolbarWindow\&.IsVisible ()\fC [static]\fP"

.PP
Definition at line 68 of file CollabToolbarWindow\&.cs\&.
.SS "new void UnityEditor\&.CollabToolbarWindow\&.OnDestroy ()"

.PP
Definition at line 131 of file CollabToolbarWindow\&.cs\&.
.SS "override void UnityEditor\&.CollabToolbarWindow\&.OnEnable ()"

.PP
Definition at line 109 of file CollabToolbarWindow\&.cs\&.
.SS "new void UnityEditor\&.CollabToolbarWindow\&.OnInitScripting ()"

.PP
Definition at line 104 of file CollabToolbarWindow\&.cs\&.
.SS "void UnityEditor\&.CollabToolbarWindow\&.OnReceiveTitle (string title)"

.PP
Definition at line 99 of file CollabToolbarWindow\&.cs\&.
.SS "static bool UnityEditor\&.CollabToolbarWindow\&.ShowCenteredAtPosition (Rect buttonRect)\fC [static]\fP"

.PP
Definition at line 73 of file CollabToolbarWindow\&.cs\&.
.SS "static \fBCollabToolbarWindow\fP UnityEditor\&.CollabToolbarWindow\&.ShowToolbarWindow ()\fC [static]\fP"

.PP
Definition at line 51 of file CollabToolbarWindow\&.cs\&.
.SS "static bool UnityEditor\&.CollabToolbarWindow\&.ValidateShowToolbarWindow ()\fC [static]\fP"

.PP
Definition at line 63 of file CollabToolbarWindow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UnityEditor\&.CollabToolbarWindow\&.s_ToolbarIsVisible = false\fC [static]\fP"

.PP
Definition at line 39 of file CollabToolbarWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
