.TH "Valve.VR.SteamVR_ActionSet" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_ActionSet \- Action sets are logical groupings of actions\&. Multiple sets can be active at one time\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IEquatable< SteamVR_ActionSet >, \fBValve\&.VR\&.ISteamVR_ActionSet\fP, and ISerializationCallbackReceiver\&.
.PP
Inherited by \fBValve\&.VR\&.SteamVR_Input_ActionSet_buggy\fP, \fBValve\&.VR\&.SteamVR_Input_ActionSet_default\fP, \fBValve\&.VR\&.SteamVR_Input_ActionSet_mixedreality\fP, and \fBValve\&.VR\&.SteamVR_Input_ActionSet_platformer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSteamVR_ActionSet\fP ()"
.br
.ti -1c
.RI "void \fBPreInitialize\fP (string newActionPath)"
.br
.ti -1c
.RI "virtual void \fBFinishPreInitialize\fP ()"
.br
.ti -1c
.RI "virtual void \fBInitialize\fP (bool createNew=false, bool throwErrors=true)"
.br
.RI "Initializes the handle for the action "
.ti -1c
.RI "string \fBGetPath\fP ()"
.br
.ti -1c
.RI "bool \fBIsActive\fP (\fBSteamVR_Input_Sources\fP source=\fBSteamVR_Input_Sources\&.Any\fP)"
.br
.RI "Returns whether the set is currently active or not\&. "
.ti -1c
.RI "float \fBGetTimeLastChanged\fP (\fBSteamVR_Input_Sources\fP source=\fBSteamVR_Input_Sources\&.Any\fP)"
.br
.RI "Returns the last time this action set was changed (set to active or inactive) "
.ti -1c
.RI "void \fBActivate\fP (\fBSteamVR_Input_Sources\fP activateForSource=\fBSteamVR_Input_Sources\&.Any\fP, int priority=0, bool disableAllOtherActionSets=false)"
.br
.RI "Activate this set so its actions can be called "
.ti -1c
.RI "void \fBDeactivate\fP (\fBSteamVR_Input_Sources\fP forSource=\fBSteamVR_Input_Sources\&.Any\fP)"
.br
.RI "Deactivate the action set so its actions can no longer be called "
.ti -1c
.RI "string \fBGetShortName\fP ()"
.br
.RI "Gets the last part of the path for this action\&. Removes 'actions' and direction\&. "
.ti -1c
.RI "bool \fBReadRawSetActive\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.ti -1c
.RI "float \fBReadRawSetLastChanged\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.ti -1c
.RI "int \fBReadRawSetPriority\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.ti -1c
.RI "\fBSteamVR_ActionSet_Data\fP \fBGetActionSetData\fP ()"
.br
.ti -1c
.RI "CreateType \fBGetCopy< CreateType >\fP ()"
.br
.ti -1c
.RI "bool \fBEquals\fP (\fBSteamVR_ActionSet\fP other)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object other)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static CreateType \fBCreate< CreateType >\fP (string newSetPath)"
.br
.ti -1c
.RI "static CreateType \fBCreateFromName< CreateType >\fP (string newSetName)"
.br
.ti -1c
.RI "static bool \fBoperator !=\fP (\fBSteamVR_ActionSet\fP set1, \fBSteamVR_ActionSet\fP set2)"
.br
.ti -1c
.RI "static bool \fBoperator==\fP (\fBSteamVR_ActionSet\fP set1, \fBSteamVR_ActionSet\fP set2)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_ActionSet_Data\fP \fBsetData\fP"
.br
.ti -1c
.RI "bool \fBinitialized\fP = false"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSteamVR_Action\fP [] \fBallActions\fP\fC [get]\fP"
.br
.RI "All actions within this set (including out actions) "
.ti -1c
.RI "\fBISteamVR_Action_In\fP [] \fBnonVisualInActions\fP\fC [get]\fP"
.br
.RI "All IN actions within this set that are NOT pose or skeleton actions "
.ti -1c
.RI "\fBISteamVR_Action_In\fP [] \fBvisualActions\fP\fC [get]\fP"
.br
.RI "All pose and skeleton actions within this set "
.ti -1c
.RI "\fBSteamVR_Action_Pose\fP [] \fBposeActions\fP\fC [get]\fP"
.br
.RI "All pose actions within this set "
.ti -1c
.RI "\fBSteamVR_Action_Skeleton\fP [] \fBskeletonActions\fP\fC [get]\fP"
.br
.RI "All skeleton actions within this set "
.ti -1c
.RI "\fBISteamVR_Action_Out\fP [] \fBoutActionArray\fP\fC [get]\fP"
.br
.RI "All out actions within this set "
.ti -1c
.RI "string \fBfullPath\fP\fC [get]\fP"
.br
.RI "The full path to this action set (ex: /actions/in/default) "
.ti -1c
.RI "string \fBusage\fP\fC [get]\fP"
.br
.ti -1c
.RI "ulong \fBhandle\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Action sets are logical groupings of actions\&. Multiple sets can be active at one time\&. 


.PP
Definition at line 17 of file SteamVR_ActionSet\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.SteamVR_ActionSet\&.SteamVR_ActionSet ()"

.PP
Definition at line 19 of file SteamVR_ActionSet\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_ActionSet\&.Activate (\fBSteamVR_Input_Sources\fP activateForSource = \fC\fBSteamVR_Input_Sources\&.Any\fP\fP, int priority = \fC0\fP, bool disableAllOtherActionSets = \fCfalse\fP)"

.PP
Activate this set so its actions can be called 
.PP
\fBParameters:\fP
.RS 4
\fIdisableAllOtherActionSets\fP Disable all other action sets at the same time
.br
\fIpriority\fP The priority of this action set\&. If you have two actions bound to the same input (button) the higher priority set will override the lower priority\&. If they are the same priority both will execute\&.
.br
\fIactivateForSource\fP Will activate this action set only for the specified source\&. Any if you want to activate for everything
.RE
.PP

.PP
Implements \fBValve\&.VR\&.ISteamVR_ActionSet\fP\&.
.PP
Definition at line 230 of file SteamVR_ActionSet\&.cs\&.
.SS "static CreateType \fBValve\&.VR\&.SteamVR_ActionSet\&.Create\fP< CreateType > (string newSetPath)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fICreateType\fP : \fISteamVR_ActionSet\fP
.TP
\fICreateType\fP : \fInew()\fP
.PP
Definition at line 138 of file SteamVR_ActionSet\&.cs\&.
.SS "static CreateType Valve\&.VR\&.SteamVR_ActionSet\&.CreateFromName< CreateType > (string newSetName)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fICreateType\fP : \fISteamVR_ActionSet\fP
.TP
\fICreateType\fP : \fInew()\fP
.PP
Definition at line 144 of file SteamVR_ActionSet\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_ActionSet\&.Deactivate (\fBSteamVR_Input_Sources\fP forSource = \fC\fBSteamVR_Input_Sources\&.Any\fP\fP)"

.PP
Deactivate the action set so its actions can no longer be called 
.PP
Implements \fBValve\&.VR\&.ISteamVR_ActionSet\fP\&.
.PP
Definition at line 238 of file SteamVR_ActionSet\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_ActionSet\&.Equals (\fBSteamVR_ActionSet\fP other)"

.PP
Definition at line 280 of file SteamVR_ActionSet\&.cs\&.
.SS "override bool Valve\&.VR\&.SteamVR_ActionSet\&.Equals (object other)"

.PP
Definition at line 288 of file SteamVR_ActionSet\&.cs\&.
.SS "virtual void Valve\&.VR\&.SteamVR_ActionSet\&.FinishPreInitialize ()\fC [virtual]\fP"

.PP
Definition at line 162 of file SteamVR_ActionSet\&.cs\&.
.SS "\fBSteamVR_ActionSet_Data\fP Valve\&.VR\&.SteamVR_ActionSet\&.GetActionSetData ()"

.PP
Definition at line 264 of file SteamVR_ActionSet\&.cs\&.
.SS "CreateType Valve\&.VR\&.SteamVR_ActionSet\&.GetCopy< CreateType > ()"

.PP
\fBType Constraints\fP
.TP
\fICreateType\fP : \fISteamVR_ActionSet\fP
.TP
\fICreateType\fP : \fInew()\fP
.PP
Definition at line 269 of file SteamVR_ActionSet\&.cs\&.
.SS "override int Valve\&.VR\&.SteamVR_ActionSet\&.GetHashCode ()"

.PP
Definition at line 306 of file SteamVR_ActionSet\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_ActionSet\&.GetPath ()"

.PP
Definition at line 201 of file SteamVR_ActionSet\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_ActionSet\&.GetShortName ()"

.PP
Gets the last part of the path for this action\&. Removes 'actions' and direction\&. 
.PP
Implements \fBValve\&.VR\&.ISteamVR_ActionSet\fP\&.
.PP
Definition at line 244 of file SteamVR_ActionSet\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_ActionSet\&.GetTimeLastChanged (\fBSteamVR_Input_Sources\fP source = \fC\fBSteamVR_Input_Sources\&.Any\fP\fP)"

.PP
Returns the last time this action set was changed (set to active or inactive) 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The device to check\&. Any means all devices here (not left or right, but all)
.RE
.PP

.PP
Implements \fBValve\&.VR\&.ISteamVR_ActionSet\fP\&.
.PP
Definition at line 219 of file SteamVR_ActionSet\&.cs\&.
.SS "virtual void Valve\&.VR\&.SteamVR_ActionSet\&.Initialize (bool createNew = \fCfalse\fP, bool throwErrors = \fCtrue\fP)\fC [virtual]\fP"

.PP
Initializes the handle for the action 
.PP
Definition at line 170 of file SteamVR_ActionSet\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_ActionSet\&.IsActive (\fBSteamVR_Input_Sources\fP source = \fC\fBSteamVR_Input_Sources\&.Any\fP\fP)"

.PP
Returns whether the set is currently active or not\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The device to check\&. Any means all devices here (not left or right, but all)
.RE
.PP

.PP
Implements \fBValve\&.VR\&.ISteamVR_ActionSet\fP\&.
.PP
Definition at line 210 of file SteamVR_ActionSet\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_ActionSet\&.operator != (\fBSteamVR_ActionSet\fP set1, \fBSteamVR_ActionSet\fP set2)\fC [static]\fP"

.PP
Definition at line 314 of file SteamVR_ActionSet\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_ActionSet\&.operator== (\fBSteamVR_ActionSet\fP set1, \fBSteamVR_ActionSet\fP set2)\fC [static]\fP"

.PP
Definition at line 319 of file SteamVR_ActionSet\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_ActionSet\&.PreInitialize (string newActionPath)"

.PP
Definition at line 151 of file SteamVR_ActionSet\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_ActionSet\&.ReadRawSetActive (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
Implements \fBValve\&.VR\&.ISteamVR_ActionSet\fP\&.
.PP
Definition at line 249 of file SteamVR_ActionSet\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_ActionSet\&.ReadRawSetLastChanged (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
Implements \fBValve\&.VR\&.ISteamVR_ActionSet\fP\&.
.PP
Definition at line 254 of file SteamVR_ActionSet\&.cs\&.
.SS "int Valve\&.VR\&.SteamVR_ActionSet\&.ReadRawSetPriority (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
Implements \fBValve\&.VR\&.ISteamVR_ActionSet\fP\&.
.PP
Definition at line 259 of file SteamVR_ActionSet\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_ActionSet\&.initialized = false\fC [protected]\fP"

.PP
Definition at line 135 of file SteamVR_ActionSet\&.cs\&.
.SS "\fBSteamVR_ActionSet_Data\fP Valve\&.VR\&.SteamVR_ActionSet\&.setData\fC [protected]\fP"

.PP
Definition at line 25 of file SteamVR_ActionSet\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBSteamVR_Action\fP [] Valve\&.VR\&.SteamVR_ActionSet\&.allActions\fC [get]\fP"

.PP
All actions within this set (including out actions) 
.PP
Definition at line 30 of file SteamVR_ActionSet\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_ActionSet\&.fullPath\fC [get]\fP"

.PP
The full path to this action set (ex: /actions/in/default) 
.PP
Definition at line 103 of file SteamVR_ActionSet\&.cs\&.
.SS "ulong Valve\&.VR\&.SteamVR_ActionSet\&.handle\fC [get]\fP"

.PP
Definition at line 124 of file SteamVR_ActionSet\&.cs\&.
.SS "\fBISteamVR_Action_In\fP [] Valve\&.VR\&.SteamVR_ActionSet\&.nonVisualInActions\fC [get]\fP"

.PP
All IN actions within this set that are NOT pose or skeleton actions 
.PP
Definition at line 42 of file SteamVR_ActionSet\&.cs\&.
.SS "\fBISteamVR_Action_Out\fP [] Valve\&.VR\&.SteamVR_ActionSet\&.outActionArray\fC [get]\fP"

.PP
All out actions within this set 
.PP
Definition at line 90 of file SteamVR_ActionSet\&.cs\&.
.SS "\fBSteamVR_Action_Pose\fP [] Valve\&.VR\&.SteamVR_ActionSet\&.poseActions\fC [get]\fP"

.PP
All pose actions within this set 
.PP
Definition at line 66 of file SteamVR_ActionSet\&.cs\&.
.SS "\fBSteamVR_Action_Skeleton\fP [] Valve\&.VR\&.SteamVR_ActionSet\&.skeletonActions\fC [get]\fP"

.PP
All skeleton actions within this set 
.PP
Definition at line 78 of file SteamVR_ActionSet\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_ActionSet\&.usage\fC [get]\fP"

.PP
Definition at line 113 of file SteamVR_ActionSet\&.cs\&.
.SS "\fBISteamVR_Action_In\fP [] Valve\&.VR\&.SteamVR_ActionSet\&.visualActions\fC [get]\fP"

.PP
All pose and skeleton actions within this set 
.PP
Definition at line 54 of file SteamVR_ActionSet\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
