.TH "Valve.VR.Extras.SteamVR_GazeTracker" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.Extras.SteamVR_GazeTracker
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnGazeOn\fP (\fBGazeEventArgs\fP gazeEventArgs)"
.br
.ti -1c
.RI "virtual void \fBOnGazeOff\fP (\fBGazeEventArgs\fP gazeEventArgs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisInGaze\fP = false"
.br
.ti -1c
.RI "float \fBgazeInCutoff\fP = 0\&.15f"
.br
.ti -1c
.RI "float \fBgazeOutCutoff\fP = 0\&.4f"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Transform \fBhmdTrackedObject\fP = null"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "\fBGazeEventHandler\fP \fBGazeOn\fP"
.br
.ti -1c
.RI "\fBGazeEventHandler\fP \fBGazeOff\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file SteamVR_GazeTracker\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Valve\&.VR\&.Extras\&.SteamVR_GazeTracker\&.OnGazeOff (\fBGazeEventArgs\fP gazeEventArgs)\fC [virtual]\fP"

.PP
Definition at line 24 of file SteamVR_GazeTracker\&.cs\&.
.SS "virtual void Valve\&.VR\&.Extras\&.SteamVR_GazeTracker\&.OnGazeOn (\fBGazeEventArgs\fP gazeEventArgs)\fC [virtual]\fP"

.PP
Definition at line 18 of file SteamVR_GazeTracker\&.cs\&.
.SS "virtual void Valve\&.VR\&.Extras\&.SteamVR_GazeTracker\&.Update ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 30 of file SteamVR_GazeTracker\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.Extras\&.SteamVR_GazeTracker\&.gazeInCutoff = 0\&.15f"

.PP
Definition at line 12 of file SteamVR_GazeTracker\&.cs\&.
.SS "float Valve\&.VR\&.Extras\&.SteamVR_GazeTracker\&.gazeOutCutoff = 0\&.4f"

.PP
Definition at line 13 of file SteamVR_GazeTracker\&.cs\&.
.SS "Transform Valve\&.VR\&.Extras\&.SteamVR_GazeTracker\&.hmdTrackedObject = null\fC [protected]\fP"

.PP
Definition at line 16 of file SteamVR_GazeTracker\&.cs\&.
.SS "bool Valve\&.VR\&.Extras\&.SteamVR_GazeTracker\&.isInGaze = false"

.PP
Definition at line 9 of file SteamVR_GazeTracker\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "\fBGazeEventHandler\fP Valve\&.VR\&.Extras\&.SteamVR_GazeTracker\&.GazeOff"

.PP
Definition at line 11 of file SteamVR_GazeTracker\&.cs\&.
.SS "\fBGazeEventHandler\fP Valve\&.VR\&.Extras\&.SteamVR_GazeTracker\&.GazeOn"

.PP
Definition at line 10 of file SteamVR_GazeTracker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
