.TH "Valve.VR.CameraVideoStreamFrameHeader_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.CameraVideoStreamFrameHeader_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEVRTrackedCameraFrameType\fP \fBeFrameType\fP"
.br
.ti -1c
.RI "uint \fBnWidth\fP"
.br
.ti -1c
.RI "uint \fBnHeight\fP"
.br
.ti -1c
.RI "uint \fBnBytesPerPixel\fP"
.br
.ti -1c
.RI "uint \fBnFrameSequence\fP"
.br
.ti -1c
.RI "\fBTrackedDevicePose_t\fP \fBstandingTrackedDevicePose\fP"
.br
.ti -1c
.RI "ulong \fBulFrameExposureTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5327 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEVRTrackedCameraFrameType\fP Valve\&.VR\&.CameraVideoStreamFrameHeader_t\&.eFrameType"

.PP
Definition at line 5329 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CameraVideoStreamFrameHeader_t\&.nBytesPerPixel"

.PP
Definition at line 5332 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CameraVideoStreamFrameHeader_t\&.nFrameSequence"

.PP
Definition at line 5333 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CameraVideoStreamFrameHeader_t\&.nHeight"

.PP
Definition at line 5331 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CameraVideoStreamFrameHeader_t\&.nWidth"

.PP
Definition at line 5330 of file openvr_api\&.cs\&.
.SS "\fBTrackedDevicePose_t\fP Valve\&.VR\&.CameraVideoStreamFrameHeader_t\&.standingTrackedDevicePose"

.PP
Definition at line 5334 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.CameraVideoStreamFrameHeader_t\&.ulFrameExposureTime"

.PP
Definition at line 5335 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
