.TH "Valve.VR.InteractionSystem.Player" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Player
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHand\fP \fBGetHand\fP (int i)"
.br
.ti -1c
.RI "void \fBDraw2DDebug\fP ()"
.br
.ti -1c
.RI "void \fBPlayerShotSelf\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBtrackingOriginTransform\fP"
.br
.ti -1c
.RI "Transform [] \fBhmdTransforms\fP"
.br
.ti -1c
.RI "\fBHand\fP [] \fBhands\fP"
.br
.ti -1c
.RI "Collider \fBheadCollider\fP"
.br
.ti -1c
.RI "GameObject \fBrigSteamVR\fP"
.br
.ti -1c
.RI "GameObject \fBrig2DFallback\fP"
.br
.ti -1c
.RI "Transform \fBaudioListener\fP"
.br
.ti -1c
.RI "\fBSteamVR_Action_Boolean\fP \fBheadsetOnHead\fP = \fBSteamVR_Input\&.GetBooleanAction\fP('HeadsetOnHead')"
.br
.ti -1c
.RI "bool \fBallowToggleTo2D\fP = true"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBPlayer\fP \fBinstance\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBhandCount\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHand\fP \fBleftHand\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHand\fP \fBrightHand\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBscale\fP\fC [get]\fP"
.br
.ti -1c
.RI "Transform \fBhmdTransform\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBeyeHeight\fP\fC [get]\fP"
.br
.ti -1c
.RI "Vector3 \fBfeetPositionGuess\fP\fC [get]\fP"
.br
.ti -1c
.RI "Vector3 \fBbodyDirectionGuess\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file Player\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.Player\&.Draw2DDebug ()"

.PP
Definition at line 366 of file Player\&.cs\&.
.SS "\fBHand\fP Valve\&.VR\&.InteractionSystem\&.Player\&.GetHand (int i)"

.PP
Definition at line 88 of file Player\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Player\&.PlayerShotSelf ()"

.PP
Definition at line 411 of file Player\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Player\&.Update ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 282 of file Player\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.Player\&.allowToggleTo2D = true"

.PP
Definition at line 43 of file Player\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Player\&.audioListener"

.PP
Definition at line 38 of file Player\&.cs\&.
.SS "\fBHand\fP [] Valve\&.VR\&.InteractionSystem\&.Player\&.hands"

.PP
Definition at line 26 of file Player\&.cs\&.
.SS "Collider Valve\&.VR\&.InteractionSystem\&.Player\&.headCollider"

.PP
Definition at line 29 of file Player\&.cs\&.
.SS "\fBSteamVR_Action_Boolean\fP Valve\&.VR\&.InteractionSystem\&.Player\&.headsetOnHead = \fBSteamVR_Input\&.GetBooleanAction\fP('HeadsetOnHead')"

.PP
Definition at line 41 of file Player\&.cs\&.
.SS "Transform [] Valve\&.VR\&.InteractionSystem\&.Player\&.hmdTransforms"

.PP
Definition at line 23 of file Player\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.Player\&.rig2DFallback"

.PP
Definition at line 35 of file Player\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.Player\&.rigSteamVR"

.PP
Definition at line 32 of file Player\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Player\&.trackingOriginTransform"

.PP
Definition at line 20 of file Player\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.Player\&.bodyDirectionGuess\fC [get]\fP"

.PP
Definition at line 231 of file Player\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Player\&.eyeHeight\fC [get]\fP"

.PP
Definition at line 196 of file Player\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.Player\&.feetPositionGuess\fC [get]\fP"

.PP
Definition at line 214 of file Player\&.cs\&.
.SS "int Valve\&.VR\&.InteractionSystem\&.Player\&.handCount\fC [get]\fP"

.PP
Definition at line 67 of file Player\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Player\&.hmdTransform\fC [get]\fP"

.PP
Definition at line 176 of file Player\&.cs\&.
.SS "\fBPlayer\fP Valve\&.VR\&.InteractionSystem\&.Player\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 51 of file Player\&.cs\&.
.SS "\fBHand\fP Valve\&.VR\&.InteractionSystem\&.Player\&.leftHand\fC [get]\fP"

.PP
Definition at line 112 of file Player\&.cs\&.
.SS "\fBHand\fP Valve\&.VR\&.InteractionSystem\&.Player\&.rightHand\fC [get]\fP"

.PP
Definition at line 137 of file Player\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Player\&.scale\fC [get]\fP"

.PP
Definition at line 164 of file Player\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
