.TH "Valve.VR.VREvent_ApplicationLaunch_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VREvent_ApplicationLaunch_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint \fBpid\fP"
.br
.ti -1c
.RI "uint \fBunArgsHandle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5149 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "uint Valve\&.VR\&.VREvent_ApplicationLaunch_t\&.pid"

.PP
Definition at line 5151 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.VREvent_ApplicationLaunch_t\&.unArgsHandle"

.PP
Definition at line 5152 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
