.TH "Valve.VR.SteamVR_PlayArea" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_PlayArea
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSize\fP { \fBSize\&.Calibrated\fP, \fBSize\&._400x300\fP, \fBSize\&._300x225\fP, \fBSize\&._200x150\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBuildMesh\fP ()"
.br
.ti -1c
.RI "void \fBDrawWireframe\fP ()"
.br
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBGetBounds\fP (\fBSize\fP \fBsize\fP, ref \fBHmdQuad_t\fP pRect)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBborderThickness\fP = 0\&.15f"
.br
.ti -1c
.RI "float \fBwireframeHeight\fP = 2\&.0f"
.br
.ti -1c
.RI "bool \fBdrawWireframeWhenSelectedOnly\fP = false"
.br
.ti -1c
.RI "bool \fBdrawInGame\fP = true"
.br
.ti -1c
.RI "\fBSize\fP \fBsize\fP"
.br
.ti -1c
.RI "Color \fBcolor\fP = Color\&.cyan"
.br
.ti -1c
.RI "Vector3 [] \fBvertices\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file SteamVR_PlayArea\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.SteamVR_PlayArea\&.Size\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICalibrated \fP\fP
.TP
\fB\fI_400x300 \fP\fP
.TP
\fB\fI_300x225 \fP\fP
.TP
\fB\fI_200x150 \fP\fP
.PP
Definition at line 22 of file SteamVR_PlayArea\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_PlayArea\&.BuildMesh ()"

.PP
Definition at line 89 of file SteamVR_PlayArea\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_PlayArea\&.DrawWireframe ()"

.PP
Definition at line 226 of file SteamVR_PlayArea\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_PlayArea\&.GetBounds (\fBSize\fP size, ref \fBHmdQuad_t\fP pRect)\fC [static]\fP"

.PP
Definition at line 36 of file SteamVR_PlayArea\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_PlayArea\&.OnEnable ()"

.PP
Definition at line 246 of file SteamVR_PlayArea\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.SteamVR_PlayArea\&.borderThickness = 0\&.15f"

.PP
Definition at line 17 of file SteamVR_PlayArea\&.cs\&.
.SS "Color Valve\&.VR\&.SteamVR_PlayArea\&.color = Color\&.cyan"

.PP
Definition at line 31 of file SteamVR_PlayArea\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_PlayArea\&.drawInGame = true"

.PP
Definition at line 20 of file SteamVR_PlayArea\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_PlayArea\&.drawWireframeWhenSelectedOnly = false"

.PP
Definition at line 19 of file SteamVR_PlayArea\&.cs\&.
.SS "\fBSize\fP Valve\&.VR\&.SteamVR_PlayArea\&.size"

.PP
Definition at line 30 of file SteamVR_PlayArea\&.cs\&.
.SS "Vector3 [] Valve\&.VR\&.SteamVR_PlayArea\&.vertices"

.PP
Definition at line 34 of file SteamVR_PlayArea\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_PlayArea\&.wireframeHeight = 2\&.0f"

.PP
Definition at line 18 of file SteamVR_PlayArea\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
