.TH "Valve.VR.SteamVR_Input_ActionFile_DefaultBinding" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_ActionFile_DefaultBinding
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSteamVR_Input_ActionFile_DefaultBinding\fP \fBGetCopy\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBcontroller_type\fP"
.br
.ti -1c
.RI "string \fBbinding_url\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 249 of file SteamVR_Input_ActionFile\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSteamVR_Input_ActionFile_DefaultBinding\fP Valve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding\&.GetCopy ()"

.PP
Definition at line 254 of file SteamVR_Input_ActionFile\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Valve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding\&.binding_url"

.PP
Definition at line 252 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input_ActionFile_DefaultBinding\&.controller_type"

.PP
Definition at line 251 of file SteamVR_Input_ActionFile\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
