.TH "Valve.VR.SteamVR_Input_ActionSet_platformer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_ActionSet_platformer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_ActionSet\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBSteamVR_Action_Vector2\fP \fBMove\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBSteamVR_Action_Boolean\fP \fBJump\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file SteamVR_Input_ActionSet_platformer\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual \fBSteamVR_Action_Boolean\fP Valve\&.VR\&.SteamVR_Input_ActionSet_platformer\&.Jump\fC [get]\fP"

.PP
Definition at line 29 of file SteamVR_Input_ActionSet_platformer\&.cs\&.
.SS "virtual \fBSteamVR_Action_Vector2\fP Valve\&.VR\&.SteamVR_Input_ActionSet_platformer\&.Move\fC [get]\fP"

.PP
Definition at line 21 of file SteamVR_Input_ActionSet_platformer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
