.TH "Valve.VR.SteamVR_Fade" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Fade
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnStartFade\fP (Color newColor, float duration, bool fadeOverlay)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBStart\fP (Color newColor, float duration, bool fadeOverlay=false)"
.br
.ti -1c
.RI "static void \fBView\fP (Color newColor, float duration)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file SteamVR_Fade\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Fade\&.OnStartFade (Color newColor, float duration, bool fadeOverlay)"

.PP
Definition at line 57 of file SteamVR_Fade\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Fade\&.Start (Color newColor, float duration, bool fadeOverlay = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 34 of file SteamVR_Fade\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Fade\&.View (Color newColor, float duration)\fC [static]\fP"

.PP
Definition at line 39 of file SteamVR_Fade\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
