.TH "Valve.VR.VREvent_Keyboard_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VREvent_Keyboard_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBcNewInput0\fP"
.br
.ti -1c
.RI "byte \fBcNewInput1\fP"
.br
.ti -1c
.RI "byte \fBcNewInput2\fP"
.br
.ti -1c
.RI "byte \fBcNewInput3\fP"
.br
.ti -1c
.RI "byte \fBcNewInput4\fP"
.br
.ti -1c
.RI "byte \fBcNewInput5\fP"
.br
.ti -1c
.RI "byte \fBcNewInput6\fP"
.br
.ti -1c
.RI "byte \fBcNewInput7\fP"
.br
.ti -1c
.RI "ulong \fBuUserValue\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBcNewInput\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5092 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "byte Valve\&.VR\&.VREvent_Keyboard_t\&.cNewInput0"

.PP
Definition at line 5094 of file openvr_api\&.cs\&.
.SS "byte Valve\&.VR\&.VREvent_Keyboard_t\&.cNewInput1"

.PP
Definition at line 5094 of file openvr_api\&.cs\&.
.SS "byte Valve\&.VR\&.VREvent_Keyboard_t\&.cNewInput2"

.PP
Definition at line 5094 of file openvr_api\&.cs\&.
.SS "byte Valve\&.VR\&.VREvent_Keyboard_t\&.cNewInput3"

.PP
Definition at line 5094 of file openvr_api\&.cs\&.
.SS "byte Valve\&.VR\&.VREvent_Keyboard_t\&.cNewInput4"

.PP
Definition at line 5094 of file openvr_api\&.cs\&.
.SS "byte Valve\&.VR\&.VREvent_Keyboard_t\&.cNewInput5"

.PP
Definition at line 5094 of file openvr_api\&.cs\&.
.SS "byte Valve\&.VR\&.VREvent_Keyboard_t\&.cNewInput6"

.PP
Definition at line 5094 of file openvr_api\&.cs\&.
.SS "byte Valve\&.VR\&.VREvent_Keyboard_t\&.cNewInput7"

.PP
Definition at line 5094 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VREvent_Keyboard_t\&.uUserValue"

.PP
Definition at line 5111 of file openvr_api\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Valve\&.VR\&.VREvent_Keyboard_t\&.cNewInput\fC [get]\fP"

.PP
Definition at line 5096 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
