.TH "Valve.VR.IVRChaperone" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.IVRChaperone
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal delegate \fBChaperoneCalibrationState\fP \fB_GetCalibrationState\fP ()"
.br
.ti -1c
.RI "internal delegate bool \fB_GetPlayAreaSize\fP (ref float pSizeX, ref float pSizeZ)"
.br
.ti -1c
.RI "internal delegate bool \fB_GetPlayAreaRect\fP (ref \fBHmdQuad_t\fP rect)"
.br
.ti -1c
.RI "internal delegate void \fB_ReloadInfo\fP ()"
.br
.ti -1c
.RI "internal delegate void \fB_SetSceneColor\fP (\fBHmdColor_t\fP color)"
.br
.ti -1c
.RI "internal delegate void \fB_GetBoundsColor\fP (ref \fBHmdColor_t\fP pOutputColorArray, int nNumOutputColors, float flCollisionBoundsFadeDistance, ref \fBHmdColor_t\fP pOutputCameraColor)"
.br
.ti -1c
.RI "internal delegate bool \fB_AreBoundsVisible\fP ()"
.br
.ti -1c
.RI "internal delegate void \fB_ForceBoundsVisible\fP (bool bForce)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internal \fB_GetCalibrationState\fP \fBGetCalibrationState\fP"
.br
.ti -1c
.RI "internal \fB_GetPlayAreaSize\fP \fBGetPlayAreaSize\fP"
.br
.ti -1c
.RI "internal \fB_GetPlayAreaRect\fP \fBGetPlayAreaRect\fP"
.br
.ti -1c
.RI "internal \fB_ReloadInfo\fP \fBReloadInfo\fP"
.br
.ti -1c
.RI "internal \fB_SetSceneColor\fP \fBSetSceneColor\fP"
.br
.ti -1c
.RI "internal \fB_GetBoundsColor\fP \fBGetBoundsColor\fP"
.br
.ti -1c
.RI "internal \fB_AreBoundsVisible\fP \fBAreBoundsVisible\fP"
.br
.ti -1c
.RI "internal \fB_ForceBoundsVisible\fP \fBForceBoundsVisible\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 501 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "internal delegate bool Valve\&.VR\&.IVRChaperone\&._AreBoundsVisible ()"

.SS "internal delegate void Valve\&.VR\&.IVRChaperone\&._ForceBoundsVisible (bool bForce)"

.SS "internal delegate void Valve\&.VR\&.IVRChaperone\&._GetBoundsColor (ref \fBHmdColor_t\fP pOutputColorArray, int nNumOutputColors, float flCollisionBoundsFadeDistance, ref \fBHmdColor_t\fP pOutputCameraColor)"

.SS "internal delegate \fBChaperoneCalibrationState\fP Valve\&.VR\&.IVRChaperone\&._GetCalibrationState ()"

.SS "internal delegate bool Valve\&.VR\&.IVRChaperone\&._GetPlayAreaRect (ref \fBHmdQuad_t\fP rect)"

.SS "internal delegate bool Valve\&.VR\&.IVRChaperone\&._GetPlayAreaSize (ref float pSizeX, ref float pSizeZ)"

.SS "internal delegate void Valve\&.VR\&.IVRChaperone\&._ReloadInfo ()"

.SS "internal delegate void Valve\&.VR\&.IVRChaperone\&._SetSceneColor (\fBHmdColor_t\fP color)"

.SH "Member Data Documentation"
.PP 
.SS "internal \fB_AreBoundsVisible\fP Valve\&.VR\&.IVRChaperone\&.AreBoundsVisible"

.PP
Definition at line 536 of file openvr_api\&.cs\&.
.SS "internal \fB_ForceBoundsVisible\fP Valve\&.VR\&.IVRChaperone\&.ForceBoundsVisible"

.PP
Definition at line 541 of file openvr_api\&.cs\&.
.SS "internal \fB_GetBoundsColor\fP Valve\&.VR\&.IVRChaperone\&.GetBoundsColor"

.PP
Definition at line 531 of file openvr_api\&.cs\&.
.SS "internal \fB_GetCalibrationState\fP Valve\&.VR\&.IVRChaperone\&.GetCalibrationState"

.PP
Definition at line 506 of file openvr_api\&.cs\&.
.SS "internal \fB_GetPlayAreaRect\fP Valve\&.VR\&.IVRChaperone\&.GetPlayAreaRect"

.PP
Definition at line 516 of file openvr_api\&.cs\&.
.SS "internal \fB_GetPlayAreaSize\fP Valve\&.VR\&.IVRChaperone\&.GetPlayAreaSize"

.PP
Definition at line 511 of file openvr_api\&.cs\&.
.SS "internal \fB_ReloadInfo\fP Valve\&.VR\&.IVRChaperone\&.ReloadInfo"

.PP
Definition at line 521 of file openvr_api\&.cs\&.
.SS "internal \fB_SetSceneColor\fP Valve\&.VR\&.IVRChaperone\&.SetSceneColor"

.PP
Definition at line 526 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
