.TH "Valve.VR.SteamVR_Action_Vibration_Source" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Action_Vibration_Source
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_Action_Out_Source\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP ()"
.br
.RI "\fB[Should not be called by user code]\fP Initializes the handle for the inputSource, and any other related \fBSteamVR\fP data\&. "
.ti -1c
.RI "override void \fBPreinitialize\fP (\fBSteamVR_Action\fP wrappingAction, \fBSteamVR_Input_Sources\fP forInputSource)"
.br
.RI "\fB[Should not be called by user code]\fP Sets up the internals of the action source before \fBSteamVR\fP has been initialized\&. "
.ti -1c
.RI "void \fBExecute\fP (float secondsFromNow, float durationSeconds, float frequency, float amplitude)"
.br
.RI "Trigger the haptics at a certain time for a certain length "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_Action_Vibration\fP \fBvibrationAction\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBactive\fP\fC [get]\fP"
.br
.RI "Returns true if this action is bound and the ActionSet is active "
.ti -1c
.RI "override bool \fBactiveBinding\fP\fC [get]\fP"
.br
.RI "Returns true if the action is bound "
.ti -1c
.RI "override bool \fBlastActive\fP\fC [get, protected set]\fP"
.br
.RI "Returns true if the action was bound and the ActionSet was active during the previous update "
.ti -1c
.RI "override bool \fBlastActiveBinding\fP\fC [get]\fP"
.br
.RI "Returns true if the action was bound during the previous update "
.ti -1c
.RI "float \fBtimeLastExecuted\fP\fC [get, protected set]\fP"
.br
.RI "The last time the execute method was called on this action "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "\fBSteamVR_Action_Vibration\&.ActiveChangeHandler\fP \fBonActiveChange\fP"
.br
.RI "Event fires when the active state (ActionSet active and binding active) changes "
.ti -1c
.RI "\fBSteamVR_Action_Vibration\&.ActiveChangeHandler\fP \fBonActiveBindingChange\fP"
.br
.RI "Event fires when the active state of the binding changes "
.ti -1c
.RI "\fBSteamVR_Action_Vibration\&.ExecuteHandler\fP \fBonExecute\fP"
.br
.RI "Event fires whenever this action is executed "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 135 of file SteamVR_Action_Vibration\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.Execute (float secondsFromNow, float durationSeconds, float frequency, float amplitude)"

.PP
Trigger the haptics at a certain time for a certain length 
.PP
\fBParameters:\fP
.RS 4
\fIsecondsFromNow\fP How long from the current time to execute the action (in seconds - can be 0)
.br
\fIdurationSeconds\fP How long the haptic action should last (in seconds)
.br
\fIfrequency\fP How often the haptic motor should bounce (0 - 320 in hz\&. The lower end being more useful)
.br
\fIamplitude\fP How intense the haptic action should be (0 - 1)
.br
\fIinputSource\fP The device you would like to execute the haptic action\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 193 of file SteamVR_Action_Vibration\&.cs\&.
.SS "override void Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.Initialize ()\fC [virtual]\fP"

.PP
\fB[Should not be called by user code]\fP Initializes the handle for the inputSource, and any other related \fBSteamVR\fP data\&. 
.PP
Reimplemented from \fBValve\&.VR\&.SteamVR_Action_Source\fP\&.
.PP
Definition at line 170 of file SteamVR_Action_Vibration\&.cs\&.
.SS "override void Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.Preinitialize (\fBSteamVR_Action\fP wrappingAction, \fBSteamVR_Input_Sources\fP forInputSource)\fC [virtual]\fP"

.PP
\fB[Should not be called by user code]\fP Sets up the internals of the action source before \fBSteamVR\fP has been initialized\&. 
.PP
Reimplemented from \fBValve\&.VR\&.SteamVR_Action_Source\fP\&.
.PP
Definition at line 177 of file SteamVR_Action_Vibration\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSteamVR_Action_Vibration\fP Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.vibrationAction\fC [protected]\fP"

.PP
Definition at line 163 of file SteamVR_Action_Vibration\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override bool Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.active\fC [get]\fP"

.PP
Returns true if this action is bound and the ActionSet is active 
.PP
Definition at line 148 of file SteamVR_Action_Vibration\&.cs\&.
.SS "override bool Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.activeBinding\fC [get]\fP"

.PP
Returns true if the action is bound 
.PP
Definition at line 151 of file SteamVR_Action_Vibration\&.cs\&.
.SS "override bool Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.lastActive\fC [get]\fP, \fC [protected set]\fP"

.PP
Returns true if the action was bound and the ActionSet was active during the previous update 
.PP
Definition at line 155 of file SteamVR_Action_Vibration\&.cs\&.
.SS "override bool Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.lastActiveBinding\fC [get]\fP"

.PP
Returns true if the action was bound during the previous update 
.PP
Definition at line 158 of file SteamVR_Action_Vibration\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.timeLastExecuted\fC [get]\fP, \fC [protected set]\fP"

.PP
The last time the execute method was called on this action 
.PP
Definition at line 161 of file SteamVR_Action_Vibration\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "\fBSteamVR_Action_Vibration\&.ActiveChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.onActiveBindingChange"

.PP
Event fires when the active state of the binding changes 
.PP
Definition at line 141 of file SteamVR_Action_Vibration\&.cs\&.
.SS "\fBSteamVR_Action_Vibration\&.ActiveChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.onActiveChange"

.PP
Event fires when the active state (ActionSet active and binding active) changes 
.PP
Definition at line 138 of file SteamVR_Action_Vibration\&.cs\&.
.SS "\fBSteamVR_Action_Vibration\&.ExecuteHandler\fP Valve\&.VR\&.SteamVR_Action_Vibration_Source\&.onExecute"

.PP
Event fires whenever this action is executed 
.PP
Definition at line 144 of file SteamVR_Action_Vibration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
