.TH "Valve.VR.SteamVR_Input_EditorWindow" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_EditorWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBForceClose\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShowWindow\fP ()"
.br
.ti -1c
.RI "static void \fBReopenWindow\fP ()"
.br
.ti -1c
.RI "static void \fBRefresh\fP ()"
.br
.ti -1c
.RI "static void \fBSetProgressBarText\fP (string newText, float newAmount)"
.br
.ti -1c
.RI "static void \fBClearProgressBar\fP ()"
.br
.ti -1c
.RI "static bool \fBIsOpen\fP ()"
.br
.ti -1c
.RI "static \fBSteamVR_Input_EditorWindow\fP \fBGetOpenWindow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file SteamVR_Input_EditorWindow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Valve\&.VR\&.SteamVR_Input_EditorWindow\&.ClearProgressBar ()\fC [static]\fP"

.PP
Definition at line 251 of file SteamVR_Input_EditorWindow\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Input_EditorWindow\&.ForceClose ()"

.PP
Definition at line 60 of file SteamVR_Input_EditorWindow\&.cs\&.
.SS "static \fBSteamVR_Input_EditorWindow\fP Valve\&.VR\&.SteamVR_Input_EditorWindow\&.GetOpenWindow ()\fC [static]\fP"

.PP
Definition at line 367 of file SteamVR_Input_EditorWindow\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input_EditorWindow\&.IsOpen ()\fC [static]\fP"

.PP
Definition at line 357 of file SteamVR_Input_EditorWindow\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_EditorWindow\&.Refresh ()\fC [static]\fP"

.PP
Definition at line 42 of file SteamVR_Input_EditorWindow\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_EditorWindow\&.ReopenWindow ()\fC [static]\fP"

.PP
Definition at line 30 of file SteamVR_Input_EditorWindow\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_EditorWindow\&.SetProgressBarText (string newText, float newAmount)\fC [static]\fP"

.PP
Definition at line 244 of file SteamVR_Input_EditorWindow\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_EditorWindow\&.ShowWindow ()\fC [static]\fP"

.PP
Definition at line 25 of file SteamVR_Input_EditorWindow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
