.TH "Valve.VR.ISteamVR_Action_In_Source" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.ISteamVR_Action_In_Source
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.ISteamVR_Action_Source\fP\&.
.PP
Inherited by \fBValve\&.VR\&.ISteamVR_Action_Boolean\fP, \fBValve\&.VR\&.ISteamVR_Action_In\fP, \fBValve\&.VR\&.ISteamVR_Action_Pose\fP, \fBValve\&.VR\&.ISteamVR_Action_Single\fP, \fBValve\&.VR\&.ISteamVR_Action_Vector2\fP, \fBValve\&.VR\&.ISteamVR_Action_Vector3\fP, and \fBValve\&.VR\&.SteamVR_Action_In_Source\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBchanged\fP\fC [get]\fP"
.br
.RI "Returns true if the action has been changed in the most recent update "
.ti -1c
.RI "bool \fBlastChanged\fP\fC [get]\fP"
.br
.RI "Returns true if the action was changed for the previous update cycle "
.ti -1c
.RI "float \fBchangedTime\fP\fC [get]\fP"
.br
.RI "The Time\&.realtimeSinceStartup that this action was last changed\&. "
.ti -1c
.RI "float \fBupdateTime\fP\fC [get]\fP"
.br
.RI "The time the action was updated (Time\&.realtimeSinceStartup) "
.ti -1c
.RI "ulong \fBactiveOrigin\fP\fC [get]\fP"
.br
.RI "The handle to the component that triggered the action to be changed "
.ti -1c
.RI "ulong \fBlastActiveOrigin\fP\fC [get]\fP"
.br
.RI "The handle to the component that triggered the action to be changed in the previous update "
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBactiveDevice\fP\fC [get]\fP"
.br
.RI "The input source that triggered the action to be updated "
.ti -1c
.RI "uint \fBtrackedDeviceIndex\fP\fC [get]\fP"
.br
.RI "The device index (used by Render Models) used by the device that triggered the action to be updated "
.ti -1c
.RI "string \fBrenderModelComponentName\fP\fC [get]\fP"
.br
.RI "The name of the component on the render model that caused the action to be updated (not localized) "
.ti -1c
.RI "string \fBlocalizedOriginName\fP\fC [get]\fP"
.br
.RI "Gets the localized full name of the device that the action was updated by\&. ex: 'Left Hand Vive Controller Trackpad' "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 390 of file SteamVR_Action_In\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.ISteamVR_Action_In_Source\&.activeDevice\fC [get]\fP"

.PP
The input source that triggered the action to be updated 
.PP
Definition at line 412 of file SteamVR_Action_In\&.cs\&.
.SS "ulong Valve\&.VR\&.ISteamVR_Action_In_Source\&.activeOrigin\fC [get]\fP"

.PP
The handle to the component that triggered the action to be changed 
.PP
Definition at line 406 of file SteamVR_Action_In\&.cs\&.
.SS "bool Valve\&.VR\&.ISteamVR_Action_In_Source\&.changed\fC [get]\fP"

.PP
Returns true if the action has been changed in the most recent update 
.PP
Definition at line 394 of file SteamVR_Action_In\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_In_Source\&.changedTime\fC [get]\fP"

.PP
The Time\&.realtimeSinceStartup that this action was last changed\&. 
.PP
Definition at line 400 of file SteamVR_Action_In\&.cs\&.
.SS "ulong Valve\&.VR\&.ISteamVR_Action_In_Source\&.lastActiveOrigin\fC [get]\fP"

.PP
The handle to the component that triggered the action to be changed in the previous update 
.PP
Definition at line 409 of file SteamVR_Action_In\&.cs\&.
.SS "bool Valve\&.VR\&.ISteamVR_Action_In_Source\&.lastChanged\fC [get]\fP"

.PP
Returns true if the action was changed for the previous update cycle 
.PP
Definition at line 397 of file SteamVR_Action_In\&.cs\&.
.SS "string Valve\&.VR\&.ISteamVR_Action_In_Source\&.localizedOriginName\fC [get]\fP"

.PP
Gets the localized full name of the device that the action was updated by\&. ex: 'Left Hand Vive Controller Trackpad' 
.PP
Definition at line 421 of file SteamVR_Action_In\&.cs\&.
.SS "string Valve\&.VR\&.ISteamVR_Action_In_Source\&.renderModelComponentName\fC [get]\fP"

.PP
The name of the component on the render model that caused the action to be updated (not localized) 
.PP
Definition at line 418 of file SteamVR_Action_In\&.cs\&.
.SS "uint Valve\&.VR\&.ISteamVR_Action_In_Source\&.trackedDeviceIndex\fC [get]\fP"

.PP
The device index (used by Render Models) used by the device that triggered the action to be updated 
.PP
Definition at line 415 of file SteamVR_Action_In\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_In_Source\&.updateTime\fC [get]\fP"

.PP
The time the action was updated (Time\&.realtimeSinceStartup) 
.PP
Definition at line 403 of file SteamVR_Action_In\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
