.TH "Valve.VR.InteractionSystem.Sample.FloppyHand.Finger" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Sample.FloppyHand.Finger
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBeulerAxis\fP { \fBeulerAxis\&.X\fP, \fBeulerAxis\&.Y\fP, \fBeulerAxis\&.Z\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApplyForce\fP (Vector3 worldForce)"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBUpdateFinger\fP (float deltaTime)"
.br
.ti -1c
.RI "void \fBApplyTransforms\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBmass\fP"
.br
.ti -1c
.RI "float \fBpos\fP"
.br
.ti -1c
.RI "Vector3 \fBforwardAxis\fP"
.br
.ti -1c
.RI "SkinnedMeshRenderer \fBrenderer\fP"
.br
.ti -1c
.RI "\fBSteamVR_Action_Single\fP \fBsqueezyAction\fP"
.br
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBinputSource\fP"
.br
.ti -1c
.RI "Transform [] \fBbones\fP"
.br
.ti -1c
.RI "Transform \fBreferenceBone\fP"
.br
.ti -1c
.RI "Vector2 \fBreferenceAngles\fP"
.br
.ti -1c
.RI "\fBeulerAxis\fP \fBreferenceAxis\fP"
.br
.ti -1c
.RI "float \fBflexAngle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file FloppyHand\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.eulerAxis\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIX \fP\fP
.TP
\fB\fIY \fP\fP
.TP
\fB\fIZ \fP\fP
.PP
Definition at line 34 of file FloppyHand\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.ApplyForce (Vector3 worldForce)"

.PP
Definition at line 58 of file FloppyHand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.ApplyTransforms ()"

.PP
Definition at line 177 of file FloppyHand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.Init ()"

.PP
Definition at line 68 of file FloppyHand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.UpdateFinger (float deltaTime)"

.PP
Definition at line 87 of file FloppyHand\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform [] Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.bones"

.PP
Definition at line 30 of file FloppyHand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.flexAngle"

.PP
Definition at line 42 of file FloppyHand\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.forwardAxis"

.PP
Definition at line 23 of file FloppyHand\&.cs\&.
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.inputSource"

.PP
Definition at line 28 of file FloppyHand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.mass"

.PP
Definition at line 18 of file FloppyHand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.pos"

.PP
Definition at line 21 of file FloppyHand\&.cs\&.
.SS "Vector2 Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.referenceAngles"

.PP
Definition at line 32 of file FloppyHand\&.cs\&.
.SS "\fBeulerAxis\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.referenceAxis"

.PP
Definition at line 38 of file FloppyHand\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.referenceBone"

.PP
Definition at line 31 of file FloppyHand\&.cs\&.
.SS "SkinnedMeshRenderer Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.renderer"

.PP
Definition at line 25 of file FloppyHand\&.cs\&.
.SS "\fBSteamVR_Action_Single\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.Finger\&.squeezyAction"

.PP
Definition at line 27 of file FloppyHand\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
