.TH "Valve.VR.HmdColor_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.HmdColor_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBr\fP"
.br
.ti -1c
.RI "float \fBg\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4954 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.HmdColor_t\&.a"

.PP
Definition at line 4959 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.HmdColor_t\&.b"

.PP
Definition at line 4958 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.HmdColor_t\&.g"

.PP
Definition at line 4957 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.HmdColor_t\&.r"

.PP
Definition at line 4956 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
