.TH "Valve.VR.SteamVR_Action_In_Source_Map< SourceElement >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Action_In_Source_Map< SourceElement >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_Action_Source_Map< SourceElement >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsUpdating\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "\fB[Should not be called by user code]\fP Returns whether the system has determined this source should be updated (based on code calls) Should only be used if you've set \fBSteamVR_Action\&.startUpdatingSourceOnAccess\fP to false\&. "
.ti -1c
.RI "void \fBForceAddSourceToUpdateList\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "\fB[Should not be called by user code]\fP Forces the system to start updating the data for this action and the specified input source\&. Should only be used if you've set \fBSteamVR_Action\&.startUpdatingSourceOnAccess\fP to false\&. "
.ti -1c
.RI "void \fBUpdateValues\fP ()"
.br
.RI "\fB[Should not be called by user code]\fP Updates the data for all the input sources the system has detected need to be updated\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAccessSource\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "List< \fBSteamVR_Input_Sources\fP > \fBupdatingSources\fP = new List<\fBSteamVR_Input_Sources\fP>()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fISourceElement\fP : \fI\fBSteamVR_Action_In_Source\fP\fP
.TP
\fISourceElement\fP : \fInew()\fP
.PP
Definition at line 154 of file SteamVR_Action_In\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBValve\&.VR\&.SteamVR_Action_In_Source_Map\fP< SourceElement >\&.ForceAddSourceToUpdateList (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
\fB[Should not be called by user code]\fP Forces the system to start updating the data for this action and the specified input source\&. Should only be used if you've set \fBSteamVR_Action\&.startUpdatingSourceOnAccess\fP to false\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 190 of file SteamVR_Action_In\&.cs\&.
.SS "bool \fBValve\&.VR\&.SteamVR_Action_In_Source_Map\fP< SourceElement >\&.IsUpdating (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
\fB[Should not be called by user code]\fP Returns whether the system has determined this source should be updated (based on code calls) Should only be used if you've set \fBSteamVR_Action\&.startUpdatingSourceOnAccess\fP to false\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 165 of file SteamVR_Action_In\&.cs\&.
.SS "override void \fBValve\&.VR\&.SteamVR_Action_In_Source_Map\fP< SourceElement >\&.OnAccessSource (\fBSteamVR_Input_Sources\fP inputSource)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBValve\&.VR\&.SteamVR_Action_Source_Map< SourceElement >\fP\&.
.PP
Definition at line 176 of file SteamVR_Action_In\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Action_In_Source_Map\fP< SourceElement >\&.UpdateValues ()"

.PP
\fB[Should not be called by user code]\fP Updates the data for all the input sources the system has detected need to be updated\&. 
.PP
Definition at line 206 of file SteamVR_Action_In\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBSteamVR_Input_Sources\fP> \fBValve\&.VR\&.SteamVR_Action_In_Source_Map\fP< SourceElement >\&.updatingSources = new List<\fBSteamVR_Input_Sources\fP>()\fC [protected]\fP"

.PP
Definition at line 157 of file SteamVR_Action_In\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
