.TH "Valve.VR.SteamVR_Menu" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Menu
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShowMenu\fP ()"
.br
.ti -1c
.RI "void \fBHideMenu\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Texture \fBcursor\fP"
.br
.ti -1c
.RI "float \fBlogoHeight\fP"
.br
.ti -1c
.RI "Vector2 \fBscaleLimits\fP = new Vector2(0\&.1f, 5\&.0f)"
.br
.ti -1c
.RI "float \fBscaleRate\fP = 0\&.5f"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "RenderTexture? \fBtexture\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBscale\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file SteamVR_Menu\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Menu\&.HideMenu ()"

.PP
Definition at line 270 of file SteamVR_Menu\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Menu\&.ShowMenu ()"

.PP
Definition at line 230 of file SteamVR_Menu\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Texture Valve\&.VR\&.SteamVR_Menu\&.cursor"

.PP
Definition at line 14 of file SteamVR_Menu\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Menu\&.logoHeight"

.PP
Definition at line 15 of file SteamVR_Menu\&.cs\&.
.SS "Vector2 Valve\&.VR\&.SteamVR_Menu\&.scaleLimits = new Vector2(0\&.1f, 5\&.0f)"

.PP
Definition at line 17 of file SteamVR_Menu\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Menu\&.scaleRate = 0\&.5f"

.PP
Definition at line 18 of file SteamVR_Menu\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "float Valve\&.VR\&.SteamVR_Menu\&.scale\fC [get]\fP"

.PP
Definition at line 26 of file SteamVR_Menu\&.cs\&.
.SS "RenderTexture? Valve\&.VR\&.SteamVR_Menu\&.texture\fC [get]\fP"

.PP
Definition at line 25 of file SteamVR_Menu\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
