.TH "Valve.VR.InteractionSystem.Sample.Planting" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Sample.Planting
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPlant\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_Action_Boolean\fP \fBplantAction\fP"
.br
.ti -1c
.RI "\fBHand\fP \fBhand\fP"
.br
.ti -1c
.RI "GameObject \fBprefabToPlant\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file Planting\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.Sample\&.Planting\&.Plant ()"

.PP
Definition at line 47 of file Planting\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHand\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.Planting\&.hand"

.PP
Definition at line 14 of file Planting\&.cs\&.
.SS "\fBSteamVR_Action_Boolean\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.Planting\&.plantAction"

.PP
Definition at line 12 of file Planting\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.Sample\&.Planting\&.prefabToPlant"

.PP
Definition at line 16 of file Planting\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
