.TH "Valve.VR.SteamVR_Action_Pose_Base< SourceMap, SourceElement >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Action_Pose_Base< SourceMap, SourceElement > \- The base pose action (pose and skeleton inherit from this)  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_Action_In< SourceMap, SourceElement >\fP, and \fBValve\&.VR\&.ISteamVR_Action_Pose\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSteamVR_Action_Pose_Base\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdateValues\fP (bool skipStateAndEventUpdates)"
.br
.RI "\fB[Should not be called by user code]\fP Updates the data for all the input sources the system has detected need to be updated\&. "
.ti -1c
.RI "bool \fBGetVelocitiesAtTimeOffset\fP (\fBSteamVR_Input_Sources\fP inputSource, float secondsFromNow, out Vector3 \fBvelocity\fP, out Vector3 \fBangularVelocity\fP)"
.br
.RI "\fBSteamVR\fP keeps a log of past poses so you can retrieve old poses or estimated poses in the future by passing in a secondsFromNow value that is negative or positive\&. "
.ti -1c
.RI "bool \fBGetPoseAtTimeOffset\fP (\fBSteamVR_Input_Sources\fP inputSource, float secondsFromNow, out Vector3 \fBlocalPosition\fP, out Quaternion \fBlocalRotation\fP, out Vector3 \fBvelocity\fP, out Vector3 \fBangularVelocity\fP)"
.br
.RI "\fBSteamVR\fP keeps a log of past poses so you can retrieve old poses or estimated poses in the future by passing in a secondsFromNow value that is negative or positive\&. "
.ti -1c
.RI "virtual void \fBUpdateTransform\fP (\fBSteamVR_Input_Sources\fP inputSource, Transform transformToUpdate)"
.br
.RI "Update a transform's local position and local roation to match the pose from the most recent update "
.ti -1c
.RI "Vector3 \fBGetLocalPosition\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "The local position of this action relative to the universe origin "
.ti -1c
.RI "Quaternion \fBGetLocalRotation\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "The local rotation of this action relative to the universe origin "
.ti -1c
.RI "Vector3 \fBGetVelocity\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "The local velocity of this pose relative to the universe origin "
.ti -1c
.RI "Vector3 \fBGetAngularVelocity\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "The local angular velocity of this pose relative to the universe origin "
.ti -1c
.RI "bool \fBGetDeviceIsConnected\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "True if the device bound to this action and input source is connected "
.ti -1c
.RI "bool \fBGetPoseIsValid\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "True if the pose retrieved for this action and input source is valid (good data from the tracking source) "
.ti -1c
.RI "\fBETrackingResult\fP \fBGetTrackingResult\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "The state of the tracking system that is used to create pose data (position, rotation, etc) "
.ti -1c
.RI "Vector3 \fBGetLastLocalPosition\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "The local position for this pose during the previous update "
.ti -1c
.RI "Quaternion \fBGetLastLocalRotation\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "The local rotation for this pose during the previous update "
.ti -1c
.RI "Vector3 \fBGetLastVelocity\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "The velocity for this pose during the previous update "
.ti -1c
.RI "Vector3 \fBGetLastAngularVelocity\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "The angular velocity for this pose during the previous update "
.ti -1c
.RI "bool \fBGetLastDeviceIsConnected\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "True if the device bound to this action was connected during the previous update "
.ti -1c
.RI "bool \fBGetLastPoseIsValid\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "True if the pose was valid during the previous update "
.ti -1c
.RI "\fBETrackingResult\fP \fBGetLastTrackingResult\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "The tracking state for this pose during the previous update "
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetUniverseOrigin\fP (\fBETrackingUniverseOrigin\fP newOrigin)"
.br
.RI "Sets all pose (and skeleton) actions to use the specified universe origin\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Vector3 \fBlocalPosition\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local position of this action relative to the universe origin "
.ti -1c
.RI "Quaternion \fBlocalRotation\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local rotation of this action relative to the universe origin "
.ti -1c
.RI "\fBETrackingResult\fP \fBtrackingState\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The state of the tracking system that is used to create pose data (position, rotation, etc) "
.ti -1c
.RI "Vector3 \fBvelocity\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local velocity of this pose relative to the universe origin "
.ti -1c
.RI "Vector3 \fBangularVelocity\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local angular velocity of this pose relative to the universe origin "
.ti -1c
.RI "bool \fBposeIsValid\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True if the pose retrieved for this action and input source is valid (good data from the tracking source) "
.ti -1c
.RI "bool \fBdeviceIsConnected\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True if the device bound to this action and input source is connected "
.ti -1c
.RI "Vector3 \fBlastLocalPosition\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local position for this pose during the previous update "
.ti -1c
.RI "Quaternion \fBlastLocalRotation\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local rotation for this pose during the previous update "
.ti -1c
.RI "\fBETrackingResult\fP \fBlastTrackingState\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The tracking state for this pose during the previous update "
.ti -1c
.RI "Vector3 \fBlastVelocity\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The velocity for this pose during the previous update "
.ti -1c
.RI "Vector3 \fBlastAngularVelocity\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The angular velocity for this pose during the previous update "
.ti -1c
.RI "bool \fBlastPoseIsValid\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True if the pose was valid during the previous update "
.ti -1c
.RI "bool \fBlastDeviceIsConnected\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True if the device bound to this action was connected during the previous update "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The base pose action (pose and skeleton inherit from this) 


.PP
\fBType Constraints\fP
.TP
\fISourceMap\fP : \fI\fBSteamVR_Action_Pose_Source_Map\fP<SourceElement>\fP
.TP
\fISourceMap\fP : \fInew()\fP
.TP
\fISourceElement\fP : \fI\fBSteamVR_Action_Pose_Source\fP\fP
.TP
\fISourceElement\fP : \fInew()\fP
.PP
Definition at line 173 of file SteamVR_Action_Pose\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.\fBSteamVR_Action_Pose_Base\fP ()"

.PP
Definition at line 236 of file SteamVR_Action_Pose\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetAngularVelocity (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
The local angular velocity of this pose relative to the universe origin 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 302 of file SteamVR_Action_Pose\&.cs\&.
.SS "bool \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetDeviceIsConnected (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
True if the device bound to this action and input source is connected 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 309 of file SteamVR_Action_Pose\&.cs\&.
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetLastAngularVelocity (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
The angular velocity for this pose during the previous update 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 353 of file SteamVR_Action_Pose\&.cs\&.
.SS "bool \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetLastDeviceIsConnected (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
True if the device bound to this action was connected during the previous update 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 360 of file SteamVR_Action_Pose\&.cs\&.
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetLastLocalPosition (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
The local position for this pose during the previous update 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 332 of file SteamVR_Action_Pose\&.cs\&.
.SS "Quaternion \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetLastLocalRotation (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
The local rotation for this pose during the previous update 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 339 of file SteamVR_Action_Pose\&.cs\&.
.SS "bool \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetLastPoseIsValid (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
True if the pose was valid during the previous update 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 367 of file SteamVR_Action_Pose\&.cs\&.
.SS "\fBETrackingResult\fP \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetLastTrackingResult (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
The tracking state for this pose during the previous update 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 374 of file SteamVR_Action_Pose\&.cs\&.
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetLastVelocity (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
The velocity for this pose during the previous update 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 346 of file SteamVR_Action_Pose\&.cs\&.
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetLocalPosition (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
The local position of this action relative to the universe origin 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 281 of file SteamVR_Action_Pose\&.cs\&.
.SS "Quaternion \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetLocalRotation (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
The local rotation of this action relative to the universe origin 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 288 of file SteamVR_Action_Pose\&.cs\&.
.SS "bool \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetPoseAtTimeOffset (\fBSteamVR_Input_Sources\fP inputSource, float secondsFromNow, out Vector3 localPosition, out Quaternion localRotation, out Vector3 velocity, out Vector3 angularVelocity)"

.PP
\fBSteamVR\fP keeps a log of past poses so you can retrieve old poses or estimated poses in the future by passing in a secondsFromNow value that is negative or positive\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.br
\fIsecondsFromNow\fP The time offset in the future (estimated) or in the past (previously recorded) you want to get data from
.RE
.PP
\fBReturns:\fP
.RS 4
true if the call succeeded
.RE
.PP

.PP
Definition at line 264 of file SteamVR_Action_Pose\&.cs\&.
.SS "bool \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetPoseIsValid (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
True if the pose retrieved for this action and input source is valid (good data from the tracking source) 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 316 of file SteamVR_Action_Pose\&.cs\&.
.SS "\fBETrackingResult\fP \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetTrackingResult (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
The state of the tracking system that is used to create pose data (position, rotation, etc) 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 323 of file SteamVR_Action_Pose\&.cs\&.
.SS "bool \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetVelocitiesAtTimeOffset (\fBSteamVR_Input_Sources\fP inputSource, float secondsFromNow, out Vector3 velocity, out Vector3 angularVelocity)"

.PP
\fBSteamVR\fP keeps a log of past poses so you can retrieve old poses or estimated poses in the future by passing in a secondsFromNow value that is negative or positive\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.br
\fIsecondsFromNow\fP The time offset in the future (estimated) or in the past (previously recorded) you want to get data from
.RE
.PP
\fBReturns:\fP
.RS 4
true if the call succeeded
.RE
.PP

.PP
Definition at line 253 of file SteamVR_Action_Pose\&.cs\&.
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.GetVelocity (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
The local velocity of this pose relative to the universe origin 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 295 of file SteamVR_Action_Pose\&.cs\&.
.SS "static void \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.SetUniverseOrigin (\fBETrackingUniverseOrigin\fP newOrigin)\fC [static]\fP, \fC [protected]\fP"

.PP
Sets all pose (and skeleton) actions to use the specified universe origin\&. 
.PP
Definition at line 180 of file SteamVR_Action_Pose\&.cs\&.
.SS "virtual void \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.UpdateTransform (\fBSteamVR_Input_Sources\fP inputSource, Transform transformToUpdate)\fC [virtual]\fP"

.PP
Update a transform's local position and local roation to match the pose from the most recent update 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.br
\fItransformToUpdate\fP The transform of the object to be updated
.RE
.PP

.PP
Definition at line 274 of file SteamVR_Action_Pose\&.cs\&.
.SS "virtual void \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.UpdateValues (bool skipStateAndEventUpdates)\fC [virtual]\fP"

.PP
\fB[Should not be called by user code]\fP Updates the data for all the input sources the system has detected need to be updated\&. 
.PP
Definition at line 242 of file SteamVR_Action_Pose\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.angularVelocity\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local angular velocity of this pose relative to the universe origin 
.PP
Definition at line 206 of file SteamVR_Action_Pose\&.cs\&.
.SS "bool \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.deviceIsConnected\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True if the device bound to this action and input source is connected 
.PP
Definition at line 212 of file SteamVR_Action_Pose\&.cs\&.
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.lastAngularVelocity\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The angular velocity for this pose during the previous update 
.PP
Definition at line 227 of file SteamVR_Action_Pose\&.cs\&.
.SS "bool \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.lastDeviceIsConnected\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True if the device bound to this action was connected during the previous update 
.PP
Definition at line 233 of file SteamVR_Action_Pose\&.cs\&.
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.lastLocalPosition\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local position for this pose during the previous update 
.PP
Definition at line 215 of file SteamVR_Action_Pose\&.cs\&.
.SS "Quaternion \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.lastLocalRotation\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local rotation for this pose during the previous update 
.PP
Definition at line 218 of file SteamVR_Action_Pose\&.cs\&.
.SS "bool \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.lastPoseIsValid\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True if the pose was valid during the previous update 
.PP
Definition at line 230 of file SteamVR_Action_Pose\&.cs\&.
.SS "\fBETrackingResult\fP \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.lastTrackingState\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The tracking state for this pose during the previous update 
.PP
Definition at line 221 of file SteamVR_Action_Pose\&.cs\&.
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.lastVelocity\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The velocity for this pose during the previous update 
.PP
Definition at line 224 of file SteamVR_Action_Pose\&.cs\&.
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.localPosition\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local position of this action relative to the universe origin 
.PP
Definition at line 194 of file SteamVR_Action_Pose\&.cs\&.
.SS "Quaternion \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.localRotation\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local rotation of this action relative to the universe origin 
.PP
Definition at line 197 of file SteamVR_Action_Pose\&.cs\&.
.SS "bool \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.poseIsValid\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True if the pose retrieved for this action and input source is valid (good data from the tracking source) 
.PP
Definition at line 209 of file SteamVR_Action_Pose\&.cs\&.
.SS "\fBETrackingResult\fP \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.trackingState\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The state of the tracking system that is used to create pose data (position, rotation, etc) 
.PP
Definition at line 200 of file SteamVR_Action_Pose\&.cs\&.
.SS "Vector3 \fBValve\&.VR\&.SteamVR_Action_Pose_Base\fP< SourceMap, SourceElement >\&.velocity\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP The local velocity of this pose relative to the universe origin 
.PP
Definition at line 203 of file SteamVR_Action_Pose\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
