.TH "Valve.VR.VRControllerAxis_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VRControllerAxis_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5253 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.VRControllerAxis_t\&.x"

.PP
Definition at line 5255 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.VRControllerAxis_t\&.y"

.PP
Definition at line 5256 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
