.TH "Valve.VR.SteamVR_Camera" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Camera
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Ray \fBGetRay\fP ()"
.br
.ti -1c
.RI "void \fBForceLast\fP ()"
.br
.ti -1c
.RI "void \fBExpand\fP ()"
.br
.ti -1c
.RI "void \fBCollapse\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBwireframe\fP = false"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Transform \fBhead\fP\fC [get]\fP"
.br
.ti -1c
.RI "Transform \fBoffset\fP\fC [get]\fP"
.br
.ti -1c
.RI "Transform \fBorigin\fP\fC [get]\fP"
.br
.ti -1c
.RI "new \fBCamera\fP \fBcamera\fP\fC [get]\fP"
.br
.ti -1c
.RI "Transform \fBears\fP\fC [get]\fP"
.br
.ti -1c
.RI "static float \fBsceneResolutionScale\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string? \fBbaseName\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file SteamVR_Camera\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Camera\&.Collapse ()"

.PP
Definition at line 241 of file SteamVR_Camera\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Camera\&.Expand ()"

.PP
Definition at line 187 of file SteamVR_Camera\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Camera\&.ForceLast ()"

.PP
Definition at line 126 of file SteamVR_Camera\&.cs\&.
.SS "Ray Valve\&.VR\&.SteamVR_Camera\&.GetRay ()"

.PP
Definition at line 36 of file SteamVR_Camera\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_Camera\&.wireframe = false"

.PP
Definition at line 41 of file SteamVR_Camera\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string? Valve\&.VR\&.SteamVR_Camera\&.baseName\fC [get]\fP"

.PP
Definition at line 182 of file SteamVR_Camera\&.cs\&.
.SS "new \fBCamera\fP Valve\&.VR\&.SteamVR_Camera\&.camera\fC [get]\fP"

.PP
Definition at line 30 of file SteamVR_Camera\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Camera\&.ears\fC [get]\fP"

.PP
Definition at line 34 of file SteamVR_Camera\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Camera\&.head\fC [get]\fP"

.PP
Definition at line 26 of file SteamVR_Camera\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Camera\&.offset\fC [get]\fP"

.PP
Definition at line 27 of file SteamVR_Camera\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Camera\&.origin\fC [get]\fP"

.PP
Definition at line 28 of file SteamVR_Camera\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Camera\&.sceneResolutionScale\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 51 of file SteamVR_Camera\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
