.TH "Valve.VR.CVRChaperoneSetup" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.CVRChaperoneSetup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCommitWorkingCopy\fP (\fBEChaperoneConfigFile\fP configFile)"
.br
.ti -1c
.RI "void \fBRevertWorkingCopy\fP ()"
.br
.ti -1c
.RI "bool \fBGetWorkingPlayAreaSize\fP (ref float pSizeX, ref float pSizeZ)"
.br
.ti -1c
.RI "bool \fBGetWorkingPlayAreaRect\fP (ref \fBHmdQuad_t\fP rect)"
.br
.ti -1c
.RI "bool \fBGetWorkingCollisionBoundsInfo\fP (out \fBHmdQuad_t\fP [] pQuadsBuffer)"
.br
.ti -1c
.RI "bool \fBGetLiveCollisionBoundsInfo\fP (out \fBHmdQuad_t\fP [] pQuadsBuffer)"
.br
.ti -1c
.RI "bool \fBGetWorkingSeatedZeroPoseToRawTrackingPose\fP (ref \fBHmdMatrix34_t\fP pmatSeatedZeroPoseToRawTrackingPose)"
.br
.ti -1c
.RI "bool \fBGetWorkingStandingZeroPoseToRawTrackingPose\fP (ref \fBHmdMatrix34_t\fP pmatStandingZeroPoseToRawTrackingPose)"
.br
.ti -1c
.RI "void \fBSetWorkingPlayAreaSize\fP (float sizeX, float sizeZ)"
.br
.ti -1c
.RI "void \fBSetWorkingCollisionBoundsInfo\fP (\fBHmdQuad_t\fP [] pQuadsBuffer)"
.br
.ti -1c
.RI "void \fBSetWorkingPerimeter\fP (\fBHmdVector2_t\fP [] pPointBuffer)"
.br
.ti -1c
.RI "void \fBSetWorkingSeatedZeroPoseToRawTrackingPose\fP (ref \fBHmdMatrix34_t\fP pMatSeatedZeroPoseToRawTrackingPose)"
.br
.ti -1c
.RI "void \fBSetWorkingStandingZeroPoseToRawTrackingPose\fP (ref \fBHmdMatrix34_t\fP pMatStandingZeroPoseToRawTrackingPose)"
.br
.ti -1c
.RI "void \fBReloadFromDisk\fP (\fBEChaperoneConfigFile\fP configFile)"
.br
.ti -1c
.RI "bool \fBGetLiveSeatedZeroPoseToRawTrackingPose\fP (ref \fBHmdMatrix34_t\fP pmatSeatedZeroPoseToRawTrackingPose)"
.br
.ti -1c
.RI "bool \fBExportLiveToBuffer\fP (System\&.Text\&.StringBuilder pBuffer, ref uint pnBufferLength)"
.br
.ti -1c
.RI "bool \fBImportFromBufferToWorking\fP (string pBuffer, uint nImportFlags)"
.br
.ti -1c
.RI "void \fBShowWorkingSetPreview\fP ()"
.br
.ti -1c
.RI "void \fBHideWorkingSetPreview\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2372 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Valve\&.VR\&.CVRChaperoneSetup\&.CommitWorkingCopy (\fBEChaperoneConfigFile\fP configFile)"

.PP
Definition at line 2379 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRChaperoneSetup\&.ExportLiveToBuffer (System\&.Text\&.StringBuilder pBuffer, ref uint pnBufferLength)"

.PP
Definition at line 2455 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRChaperoneSetup\&.GetLiveCollisionBoundsInfo (out \fBHmdQuad_t\fP [] pQuadsBuffer)"

.PP
Definition at line 2408 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRChaperoneSetup\&.GetLiveSeatedZeroPoseToRawTrackingPose (ref \fBHmdMatrix34_t\fP pmatSeatedZeroPoseToRawTrackingPose)"

.PP
Definition at line 2450 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRChaperoneSetup\&.GetWorkingCollisionBoundsInfo (out \fBHmdQuad_t\fP [] pQuadsBuffer)"

.PP
Definition at line 2400 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRChaperoneSetup\&.GetWorkingPlayAreaRect (ref \fBHmdQuad_t\fP rect)"

.PP
Definition at line 2395 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRChaperoneSetup\&.GetWorkingPlayAreaSize (ref float pSizeX, ref float pSizeZ)"

.PP
Definition at line 2388 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRChaperoneSetup\&.GetWorkingSeatedZeroPoseToRawTrackingPose (ref \fBHmdMatrix34_t\fP pmatSeatedZeroPoseToRawTrackingPose)"

.PP
Definition at line 2416 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRChaperoneSetup\&.GetWorkingStandingZeroPoseToRawTrackingPose (ref \fBHmdMatrix34_t\fP pmatStandingZeroPoseToRawTrackingPose)"

.PP
Definition at line 2421 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperoneSetup\&.HideWorkingSetPreview ()"

.PP
Definition at line 2470 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRChaperoneSetup\&.ImportFromBufferToWorking (string pBuffer, uint nImportFlags)"

.PP
Definition at line 2461 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperoneSetup\&.ReloadFromDisk (\fBEChaperoneConfigFile\fP configFile)"

.PP
Definition at line 2446 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperoneSetup\&.RevertWorkingCopy ()"

.PP
Definition at line 2384 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperoneSetup\&.SetWorkingCollisionBoundsInfo (\fBHmdQuad_t\fP [] pQuadsBuffer)"

.PP
Definition at line 2430 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperoneSetup\&.SetWorkingPerimeter (\fBHmdVector2_t\fP [] pPointBuffer)"

.PP
Definition at line 2434 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperoneSetup\&.SetWorkingPlayAreaSize (float sizeX, float sizeZ)"

.PP
Definition at line 2426 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperoneSetup\&.SetWorkingSeatedZeroPoseToRawTrackingPose (ref \fBHmdMatrix34_t\fP pMatSeatedZeroPoseToRawTrackingPose)"

.PP
Definition at line 2438 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperoneSetup\&.SetWorkingStandingZeroPoseToRawTrackingPose (ref \fBHmdMatrix34_t\fP pMatStandingZeroPoseToRawTrackingPose)"

.PP
Definition at line 2442 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperoneSetup\&.ShowWorkingSetPreview ()"

.PP
Definition at line 2466 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
