.TH "Valve.VR.HmdVector4_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.HmdVector4_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBv0\fP"
.br
.ti -1c
.RI "float \fBv1\fP"
.br
.ti -1c
.RI "float \fBv2\fP"
.br
.ti -1c
.RI "float \fBv3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4922 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.HmdVector4_t\&.v0"

.PP
Definition at line 4924 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.HmdVector4_t\&.v1"

.PP
Definition at line 4925 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.HmdVector4_t\&.v2"

.PP
Definition at line 4926 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.HmdVector4_t\&.v3"

.PP
Definition at line 4927 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
