.TH "Valve.VR.VRVulkanTextureData_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VRVulkanTextureData_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ulong \fBm_nImage\fP"
.br
.ti -1c
.RI "IntPtr \fBm_pDevice\fP"
.br
.ti -1c
.RI "IntPtr \fBm_pPhysicalDevice\fP"
.br
.ti -1c
.RI "IntPtr \fBm_pInstance\fP"
.br
.ti -1c
.RI "IntPtr \fBm_pQueue\fP"
.br
.ti -1c
.RI "uint \fBm_nQueueFamilyIndex\fP"
.br
.ti -1c
.RI "uint \fBm_nWidth\fP"
.br
.ti -1c
.RI "uint \fBm_nHeight\fP"
.br
.ti -1c
.RI "uint \fBm_nFormat\fP"
.br
.ti -1c
.RI "uint \fBm_nSampleCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5024 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "uint Valve\&.VR\&.VRVulkanTextureData_t\&.m_nFormat"

.PP
Definition at line 5034 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.VRVulkanTextureData_t\&.m_nHeight"

.PP
Definition at line 5033 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VRVulkanTextureData_t\&.m_nImage"

.PP
Definition at line 5026 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.VRVulkanTextureData_t\&.m_nQueueFamilyIndex"

.PP
Definition at line 5031 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.VRVulkanTextureData_t\&.m_nSampleCount"

.PP
Definition at line 5035 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.VRVulkanTextureData_t\&.m_nWidth"

.PP
Definition at line 5032 of file openvr_api\&.cs\&.
.SS "IntPtr Valve\&.VR\&.VRVulkanTextureData_t\&.m_pDevice"

.PP
Definition at line 5027 of file openvr_api\&.cs\&.
.SS "IntPtr Valve\&.VR\&.VRVulkanTextureData_t\&.m_pInstance"

.PP
Definition at line 5029 of file openvr_api\&.cs\&.
.SS "IntPtr Valve\&.VR\&.VRVulkanTextureData_t\&.m_pPhysicalDevice"

.PP
Definition at line 5028 of file openvr_api\&.cs\&.
.SS "IntPtr Valve\&.VR\&.VRVulkanTextureData_t\&.m_pQueue"

.PP
Definition at line 5030 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
