.TH "Valve.VR.ISteamVR_Action_Skeleton_Source" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.ISteamVR_Action_Skeleton_Source
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBValve\&.VR\&.SteamVR_Action_Skeleton\fP, and \fBValve\&.VR\&.SteamVR_Action_Skeleton_Source\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEVRSkeletalTrackingLevel\fP \fBskeletalTrackingLevel\fP\fC [get]\fP"
.br
.RI "Get the accuracy level of the skeletal tracking data\&. 
.PP
* Estimated: Body part location can’t be directly determined by the device\&. Any skeletal pose provided by the device is estimated based on the active buttons, triggers, joysticks, or other input sensors\&. Examples include the Vive Controller and gamepads\&. 
.PP
* Partial: Body part location can be measured directly but with fewer degrees of freedom than the actual body part\&.Certain body part positions may be unmeasured by the device and estimated from other input data\&.Examples include Knuckles or gloves that only measure finger curl 
.PP
* Full: Body part location can be measured directly throughout the entire range of motion of the body part\&.Examples include hi-end mocap systems, or gloves that measure the rotation of each finger segment\&. "
.ti -1c
.RI "Vector3 [] \fBbonePositions\fP\fC [get]\fP"
.br
.RI "An array of the positions of the bones from the most recent update\&. Relative to skeletalTransformSpace\&. See SteamVR_Skeleton_JointIndexes for bone indexes\&. "
.ti -1c
.RI "Quaternion [] \fBboneRotations\fP\fC [get]\fP"
.br
.RI "An array of the rotations of the bones from the most recent update\&. Relative to skeletalTransformSpace\&. See SteamVR_Skeleton_JointIndexes for bone indexes\&. "
.ti -1c
.RI "Vector3 [] \fBlastBonePositions\fP\fC [get]\fP"
.br
.RI "From the previous update: An array of the positions of the bones from the most recent update\&. Relative to skeletalTransformSpace\&. See SteamVR_Skeleton_JointIndexes for bone indexes\&. "
.ti -1c
.RI "Quaternion [] \fBlastBoneRotations\fP\fC [get]\fP"
.br
.RI "From the previous update: An array of the rotations of the bones from the most recent update\&. Relative to skeletalTransformSpace\&. See SteamVR_Skeleton_JointIndexes for bone indexes\&. "
.ti -1c
.RI "\fBEVRSkeletalMotionRange\fP \fBrangeOfMotion\fP\fC [get, set]\fP"
.br
.RI "The range of motion the we're using to get bone data from\&. With Controller being your hand while holding the controller\&. "
.ti -1c
.RI "\fBEVRSkeletalTransformSpace\fP \fBskeletalTransformSpace\fP\fC [get, set]\fP"
.br
.RI "The space to get bone data in\&. Parent space by default "
.ti -1c
.RI "float \fBthumbCurl\fP\fC [get]\fP"
.br
.RI "A 0-1 value representing how curled the thumb is\&. 0 being straight, 1 being fully curled\&. "
.ti -1c
.RI "float \fBindexCurl\fP\fC [get]\fP"
.br
.RI "A 0-1 value representing how curled the index finger is\&. 0 being straight, 1 being fully curled\&. "
.ti -1c
.RI "float \fBmiddleCurl\fP\fC [get]\fP"
.br
.RI "A 0-1 value representing how curled the middle finger is\&. 0 being straight, 1 being fully curled\&. "
.ti -1c
.RI "float \fBringCurl\fP\fC [get]\fP"
.br
.RI "A 0-1 value representing how curled the ring finger is\&. 0 being straight, 1 being fully curled\&. "
.ti -1c
.RI "float \fBpinkyCurl\fP\fC [get]\fP"
.br
.RI "A 0-1 value representing how curled the pinky finger is\&. 0 being straight, 1 being fully curled\&. "
.ti -1c
.RI "float \fBthumbIndexSplay\fP\fC [get]\fP"
.br
.RI "A 0-1 value representing the size of the gap between the thumb and index fingers "
.ti -1c
.RI "float \fBindexMiddleSplay\fP\fC [get]\fP"
.br
.RI "A 0-1 value representing the size of the gap between the index and middle fingers "
.ti -1c
.RI "float \fBmiddleRingSplay\fP\fC [get]\fP"
.br
.RI "A 0-1 value representing the size of the gap between the middle and ring fingers "
.ti -1c
.RI "float \fBringPinkySplay\fP\fC [get]\fP"
.br
.RI "A 0-1 value representing the size of the gap between the ring and pinky fingers "
.ti -1c
.RI "float \fBlastThumbCurl\fP\fC [get]\fP"
.br
.RI "[Previous Update] A 0-1 value representing how curled the thumb is\&. 0 being straight, 1 being fully curled\&. "
.ti -1c
.RI "float \fBlastIndexCurl\fP\fC [get]\fP"
.br
.RI "[Previous Update] A 0-1 value representing how curled the index finger is\&. 0 being straight, 1 being fully curled\&. "
.ti -1c
.RI "float \fBlastMiddleCurl\fP\fC [get]\fP"
.br
.RI "[Previous Update] A 0-1 value representing how curled the middle finger is\&. 0 being straight, 1 being fully curled\&. "
.ti -1c
.RI "float \fBlastRingCurl\fP\fC [get]\fP"
.br
.RI "[Previous Update] A 0-1 value representing how curled the ring finger is\&. 0 being straight, 1 being fully curled\&. "
.ti -1c
.RI "float \fBlastPinkyCurl\fP\fC [get]\fP"
.br
.RI "[Previous Update] A 0-1 value representing how curled the pinky finger is\&. 0 being straight, 1 being fully curled\&. "
.ti -1c
.RI "float \fBlastThumbIndexSplay\fP\fC [get]\fP"
.br
.RI "[Previous Update] A 0-1 value representing the size of the gap between the thumb and index fingers "
.ti -1c
.RI "float \fBlastIndexMiddleSplay\fP\fC [get]\fP"
.br
.RI "[Previous Update] A 0-1 value representing the size of the gap between the index and middle fingers "
.ti -1c
.RI "float \fBlastMiddleRingSplay\fP\fC [get]\fP"
.br
.RI "[Previous Update] A 0-1 value representing the size of the gap between the middle and ring fingers "
.ti -1c
.RI "float \fBlastRingPinkySplay\fP\fC [get]\fP"
.br
.RI "[Previous Update] A 0-1 value representing the size of the gap between the ring and pinky fingers "
.ti -1c
.RI "float [] \fBfingerCurls\fP\fC [get]\fP"
.br
.RI "0-1 values representing how curled the specified finger is\&. 0 being straight, 1 being fully curled\&. For indexes see: \fBSteamVR_Skeleton_FingerIndexes\fP "
.ti -1c
.RI "float [] \fBfingerSplays\fP\fC [get]\fP"
.br
.RI "0-1 values representing how splayed the specified finger and it's next index'd finger is\&. For indexes see: \fBSteamVR_Skeleton_FingerIndexes\fP "
.ti -1c
.RI "float [] \fBlastFingerCurls\fP\fC [get]\fP"
.br
.RI "[Previous Update] 0-1 values representing how curled the specified finger is\&. 0 being straight, 1 being fully curled\&. For indexes see: \fBSteamVR_Skeleton_FingerIndexes\fP "
.ti -1c
.RI "float [] \fBlastFingerSplays\fP\fC [get]\fP"
.br
.RI "[Previous Update] 0-1 values representing how splayed the specified finger and it's next index'd finger is\&. For indexes see: \fBSteamVR_Skeleton_FingerIndexes\fP "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1132 of file SteamVR_Action_Skeleton\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Vector3 [] Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.bonePositions\fC [get]\fP"

.PP
An array of the positions of the bones from the most recent update\&. Relative to skeletalTransformSpace\&. See SteamVR_Skeleton_JointIndexes for bone indexes\&. 
.PP
Definition at line 1143 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "Quaternion [] Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.boneRotations\fC [get]\fP"

.PP
An array of the rotations of the bones from the most recent update\&. Relative to skeletalTransformSpace\&. See SteamVR_Skeleton_JointIndexes for bone indexes\&. 
.PP
Definition at line 1146 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float [] Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.fingerCurls\fC [get]\fP"

.PP
0-1 values representing how curled the specified finger is\&. 0 being straight, 1 being fully curled\&. For indexes see: \fBSteamVR_Skeleton_FingerIndexes\fP 
.PP
Definition at line 1218 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float [] Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.fingerSplays\fC [get]\fP"

.PP
0-1 values representing how splayed the specified finger and it's next index'd finger is\&. For indexes see: \fBSteamVR_Skeleton_FingerIndexes\fP 
.PP
Definition at line 1221 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.indexCurl\fC [get]\fP"

.PP
A 0-1 value representing how curled the index finger is\&. 0 being straight, 1 being fully curled\&. 
.PP
Definition at line 1164 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.indexMiddleSplay\fC [get]\fP"

.PP
A 0-1 value representing the size of the gap between the index and middle fingers 
.PP
Definition at line 1179 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "Vector3 [] Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastBonePositions\fC [get]\fP"

.PP
From the previous update: An array of the positions of the bones from the most recent update\&. Relative to skeletalTransformSpace\&. See SteamVR_Skeleton_JointIndexes for bone indexes\&. 
.PP
Definition at line 1149 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "Quaternion [] Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastBoneRotations\fC [get]\fP"

.PP
From the previous update: An array of the rotations of the bones from the most recent update\&. Relative to skeletalTransformSpace\&. See SteamVR_Skeleton_JointIndexes for bone indexes\&. 
.PP
Definition at line 1152 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float [] Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastFingerCurls\fC [get]\fP"

.PP
[Previous Update] 0-1 values representing how curled the specified finger is\&. 0 being straight, 1 being fully curled\&. For indexes see: \fBSteamVR_Skeleton_FingerIndexes\fP 
.PP
Definition at line 1224 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float [] Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastFingerSplays\fC [get]\fP"

.PP
[Previous Update] 0-1 values representing how splayed the specified finger and it's next index'd finger is\&. For indexes see: \fBSteamVR_Skeleton_FingerIndexes\fP 
.PP
Definition at line 1227 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastIndexCurl\fC [get]\fP"

.PP
[Previous Update] A 0-1 value representing how curled the index finger is\&. 0 being straight, 1 being fully curled\&. 
.PP
Definition at line 1192 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastIndexMiddleSplay\fC [get]\fP"

.PP
[Previous Update] A 0-1 value representing the size of the gap between the index and middle fingers 
.PP
Definition at line 1207 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastMiddleCurl\fC [get]\fP"

.PP
[Previous Update] A 0-1 value representing how curled the middle finger is\&. 0 being straight, 1 being fully curled\&. 
.PP
Definition at line 1195 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastMiddleRingSplay\fC [get]\fP"

.PP
[Previous Update] A 0-1 value representing the size of the gap between the middle and ring fingers 
.PP
Definition at line 1210 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastPinkyCurl\fC [get]\fP"

.PP
[Previous Update] A 0-1 value representing how curled the pinky finger is\&. 0 being straight, 1 being fully curled\&. 
.PP
Definition at line 1201 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastRingCurl\fC [get]\fP"

.PP
[Previous Update] A 0-1 value representing how curled the ring finger is\&. 0 being straight, 1 being fully curled\&. 
.PP
Definition at line 1198 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastRingPinkySplay\fC [get]\fP"

.PP
[Previous Update] A 0-1 value representing the size of the gap between the ring and pinky fingers 
.PP
Definition at line 1213 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastThumbCurl\fC [get]\fP"

.PP
[Previous Update] A 0-1 value representing how curled the thumb is\&. 0 being straight, 1 being fully curled\&. 
.PP
Definition at line 1189 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.lastThumbIndexSplay\fC [get]\fP"

.PP
[Previous Update] A 0-1 value representing the size of the gap between the thumb and index fingers 
.PP
Definition at line 1204 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.middleCurl\fC [get]\fP"

.PP
A 0-1 value representing how curled the middle finger is\&. 0 being straight, 1 being fully curled\&. 
.PP
Definition at line 1167 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.middleRingSplay\fC [get]\fP"

.PP
A 0-1 value representing the size of the gap between the middle and ring fingers 
.PP
Definition at line 1182 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.pinkyCurl\fC [get]\fP"

.PP
A 0-1 value representing how curled the pinky finger is\&. 0 being straight, 1 being fully curled\&. 
.PP
Definition at line 1173 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "\fBEVRSkeletalMotionRange\fP Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.rangeOfMotion\fC [get]\fP, \fC [set]\fP"

.PP
The range of motion the we're using to get bone data from\&. With Controller being your hand while holding the controller\&. 
.PP
Definition at line 1155 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.ringCurl\fC [get]\fP"

.PP
A 0-1 value representing how curled the ring finger is\&. 0 being straight, 1 being fully curled\&. 
.PP
Definition at line 1170 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.ringPinkySplay\fC [get]\fP"

.PP
A 0-1 value representing the size of the gap between the ring and pinky fingers 
.PP
Definition at line 1185 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "\fBEVRSkeletalTrackingLevel\fP Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.skeletalTrackingLevel\fC [get]\fP"

.PP
Get the accuracy level of the skeletal tracking data\&. 
.PP
* Estimated: Body part location can’t be directly determined by the device\&. Any skeletal pose provided by the device is estimated based on the active buttons, triggers, joysticks, or other input sensors\&. Examples include the Vive Controller and gamepads\&. 
.PP
* Partial: Body part location can be measured directly but with fewer degrees of freedom than the actual body part\&.Certain body part positions may be unmeasured by the device and estimated from other input data\&.Examples include Knuckles or gloves that only measure finger curl 
.PP
* Full: Body part location can be measured directly throughout the entire range of motion of the body part\&.Examples include hi-end mocap systems, or gloves that measure the rotation of each finger segment\&. 
.PP
Definition at line 1140 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "\fBEVRSkeletalTransformSpace\fP Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.skeletalTransformSpace\fC [get]\fP, \fC [set]\fP"

.PP
The space to get bone data in\&. Parent space by default 
.PP
Definition at line 1158 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.thumbCurl\fC [get]\fP"

.PP
A 0-1 value representing how curled the thumb is\&. 0 being straight, 1 being fully curled\&. 
.PP
Definition at line 1161 of file SteamVR_Action_Skeleton\&.cs\&.
.SS "float Valve\&.VR\&.ISteamVR_Action_Skeleton_Source\&.thumbIndexSplay\fC [get]\fP"

.PP
A 0-1 value representing the size of the gap between the thumb and index fingers 
.PP
Definition at line 1176 of file SteamVR_Action_Skeleton\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
