.TH "Valve.VR.InteractionSystem.Sample.BuggyController" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Sample.BuggyController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBmodelJoystick\fP"
.br
.ti -1c
.RI "float \fBjoystickRot\fP = 20"
.br
.ti -1c
.RI "Transform \fBmodelTrigger\fP"
.br
.ti -1c
.RI "float \fBtriggerRot\fP = 20"
.br
.ti -1c
.RI "\fBBuggyBuddy\fP \fBbuggy\fP"
.br
.ti -1c
.RI "Transform \fBbuttonBrake\fP"
.br
.ti -1c
.RI "Transform \fBbuttonReset\fP"
.br
.ti -1c
.RI "Canvas \fBui_Canvas\fP"
.br
.ti -1c
.RI "Image \fBui_rpm\fP"
.br
.ti -1c
.RI "Image \fBui_speed\fP"
.br
.ti -1c
.RI "RectTransform \fBui_steer\fP"
.br
.ti -1c
.RI "float \fBui_steerangle\fP"
.br
.ti -1c
.RI "Vector2 \fBui_fillAngles\fP"
.br
.ti -1c
.RI "Transform \fBresetToPoint\fP"
.br
.ti -1c
.RI "\fBSteamVR_Action_Vector2\fP \fBactionSteering\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Vector2\fP>('buggy', 'Steering')"
.br
.ti -1c
.RI "\fBSteamVR_Action_Single\fP \fBactionThrottle\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Single\fP>('buggy', 'Throttle')"
.br
.ti -1c
.RI "\fBSteamVR_Action_Boolean\fP \fBactionBrake\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('buggy', 'Brake')"
.br
.ti -1c
.RI "\fBSteamVR_Action_Boolean\fP \fBactionReset\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('buggy', 'Reset')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file BuggyController\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSteamVR_Action_Boolean\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.actionBrake = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('buggy', 'Brake')"

.PP
Definition at line 40 of file BuggyController\&.cs\&.
.SS "\fBSteamVR_Action_Boolean\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.actionReset = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('buggy', 'Reset')"

.PP
Definition at line 42 of file BuggyController\&.cs\&.
.SS "\fBSteamVR_Action_Vector2\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.actionSteering = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Vector2\fP>('buggy', 'Steering')"

.PP
Definition at line 36 of file BuggyController\&.cs\&.
.SS "\fBSteamVR_Action_Single\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.actionThrottle = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Single\fP>('buggy', 'Throttle')"

.PP
Definition at line 38 of file BuggyController\&.cs\&.
.SS "\fBBuggyBuddy\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.buggy"

.PP
Definition at line 18 of file BuggyController\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.buttonBrake"

.PP
Definition at line 20 of file BuggyController\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.buttonReset"

.PP
Definition at line 21 of file BuggyController\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.joystickRot = 20"

.PP
Definition at line 13 of file BuggyController\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.modelJoystick"

.PP
Definition at line 12 of file BuggyController\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.modelTrigger"

.PP
Definition at line 15 of file BuggyController\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.resetToPoint"

.PP
Definition at line 34 of file BuggyController\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.triggerRot = 20"

.PP
Definition at line 16 of file BuggyController\&.cs\&.
.SS "Canvas Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.ui_Canvas"

.PP
Definition at line 25 of file BuggyController\&.cs\&.
.SS "Vector2 Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.ui_fillAngles"

.PP
Definition at line 32 of file BuggyController\&.cs\&.
.SS "Image Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.ui_rpm"

.PP
Definition at line 26 of file BuggyController\&.cs\&.
.SS "Image Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.ui_speed"

.PP
Definition at line 27 of file BuggyController\&.cs\&.
.SS "RectTransform Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.ui_steer"

.PP
Definition at line 28 of file BuggyController\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Sample\&.BuggyController\&.ui_steerangle"

.PP
Definition at line 30 of file BuggyController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
