.TH "Valve.VR.InteractionSystem.SeeThru" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.SeeThru
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Material \fBseeThruMaterial\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file SeeThru\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Material Valve\&.VR\&.InteractionSystem\&.SeeThru\&.seeThruMaterial"

.PP
Definition at line 16 of file SeeThru\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
