.TH "Valve.VR.VROverlayIntersectionParams_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VROverlayIntersectionParams_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHmdVector3_t\fP \fBvSource\fP"
.br
.ti -1c
.RI "\fBHmdVector3_t\fP \fBvDirection\fP"
.br
.ti -1c
.RI "\fBETrackingUniverseOrigin\fP \fBeOrigin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5404 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBETrackingUniverseOrigin\fP Valve\&.VR\&.VROverlayIntersectionParams_t\&.eOrigin"

.PP
Definition at line 5408 of file openvr_api\&.cs\&.
.SS "\fBHmdVector3_t\fP Valve\&.VR\&.VROverlayIntersectionParams_t\&.vDirection"

.PP
Definition at line 5407 of file openvr_api\&.cs\&.
.SS "\fBHmdVector3_t\fP Valve\&.VR\&.VROverlayIntersectionParams_t\&.vSource"

.PP
Definition at line 5406 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
