.TH "Valve.VR.IVRTrackedCamera" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.IVRTrackedCamera
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal delegate IntPtr \fB_GetCameraErrorNameFromEnum\fP (\fBEVRTrackedCameraError\fP eCameraError)"
.br
.ti -1c
.RI "internal delegate \fBEVRTrackedCameraError\fP \fB_HasCamera\fP (uint nDeviceIndex, ref bool pHasCamera)"
.br
.ti -1c
.RI "internal delegate \fBEVRTrackedCameraError\fP \fB_GetCameraFrameSize\fP (uint nDeviceIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref uint pnWidth, ref uint pnHeight, ref uint pnFrameBufferSize)"
.br
.ti -1c
.RI "internal delegate \fBEVRTrackedCameraError\fP \fB_GetCameraIntrinsics\fP (uint nDeviceIndex, uint nCameraIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref \fBHmdVector2_t\fP pFocalLength, ref \fBHmdVector2_t\fP pCenter)"
.br
.ti -1c
.RI "internal delegate \fBEVRTrackedCameraError\fP \fB_GetCameraProjection\fP (uint nDeviceIndex, uint nCameraIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, float flZNear, float flZFar, ref \fBHmdMatrix44_t\fP pProjection)"
.br
.ti -1c
.RI "internal delegate \fBEVRTrackedCameraError\fP \fB_AcquireVideoStreamingService\fP (uint nDeviceIndex, ref ulong pHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVRTrackedCameraError\fP \fB_ReleaseVideoStreamingService\fP (ulong hTrackedCamera)"
.br
.ti -1c
.RI "internal delegate \fBEVRTrackedCameraError\fP \fB_GetVideoStreamFrameBuffer\fP (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, IntPtr pFrameBuffer, uint nFrameBufferSize, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"
.br
.ti -1c
.RI "internal delegate \fBEVRTrackedCameraError\fP \fB_GetVideoStreamTextureSize\fP (uint nDeviceIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref \fBVRTextureBounds_t\fP pTextureBounds, ref uint pnWidth, ref uint pnHeight)"
.br
.ti -1c
.RI "internal delegate \fBEVRTrackedCameraError\fP \fB_GetVideoStreamTextureD3D11\fP (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, IntPtr pD3D11DeviceOrResource, ref IntPtr ppD3D11ShaderResourceView, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"
.br
.ti -1c
.RI "internal delegate \fBEVRTrackedCameraError\fP \fB_GetVideoStreamTextureGL\fP (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, ref uint pglTextureId, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"
.br
.ti -1c
.RI "internal delegate \fBEVRTrackedCameraError\fP \fB_ReleaseVideoStreamTextureGL\fP (ulong hTrackedCamera, uint glTextureId)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internal \fB_GetCameraErrorNameFromEnum\fP \fBGetCameraErrorNameFromEnum\fP"
.br
.ti -1c
.RI "internal \fB_HasCamera\fP \fBHasCamera\fP"
.br
.ti -1c
.RI "internal \fB_GetCameraFrameSize\fP \fBGetCameraFrameSize\fP"
.br
.ti -1c
.RI "internal \fB_GetCameraIntrinsics\fP \fBGetCameraIntrinsics\fP"
.br
.ti -1c
.RI "internal \fB_GetCameraProjection\fP \fBGetCameraProjection\fP"
.br
.ti -1c
.RI "internal \fB_AcquireVideoStreamingService\fP \fBAcquireVideoStreamingService\fP"
.br
.ti -1c
.RI "internal \fB_ReleaseVideoStreamingService\fP \fBReleaseVideoStreamingService\fP"
.br
.ti -1c
.RI "internal \fB_GetVideoStreamFrameBuffer\fP \fBGetVideoStreamFrameBuffer\fP"
.br
.ti -1c
.RI "internal \fB_GetVideoStreamTextureSize\fP \fBGetVideoStreamTextureSize\fP"
.br
.ti -1c
.RI "internal \fB_GetVideoStreamTextureD3D11\fP \fBGetVideoStreamTextureD3D11\fP"
.br
.ti -1c
.RI "internal \fB_GetVideoStreamTextureGL\fP \fBGetVideoStreamTextureGL\fP"
.br
.ti -1c
.RI "internal \fB_ReleaseVideoStreamTextureGL\fP \fBReleaseVideoStreamTextureGL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 276 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "internal delegate \fBEVRTrackedCameraError\fP Valve\&.VR\&.IVRTrackedCamera\&._AcquireVideoStreamingService (uint nDeviceIndex, ref ulong pHandle)"

.SS "internal delegate IntPtr Valve\&.VR\&.IVRTrackedCamera\&._GetCameraErrorNameFromEnum (\fBEVRTrackedCameraError\fP eCameraError)"

.SS "internal delegate \fBEVRTrackedCameraError\fP Valve\&.VR\&.IVRTrackedCamera\&._GetCameraFrameSize (uint nDeviceIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref uint pnWidth, ref uint pnHeight, ref uint pnFrameBufferSize)"

.SS "internal delegate \fBEVRTrackedCameraError\fP Valve\&.VR\&.IVRTrackedCamera\&._GetCameraIntrinsics (uint nDeviceIndex, uint nCameraIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref \fBHmdVector2_t\fP pFocalLength, ref \fBHmdVector2_t\fP pCenter)"

.SS "internal delegate \fBEVRTrackedCameraError\fP Valve\&.VR\&.IVRTrackedCamera\&._GetCameraProjection (uint nDeviceIndex, uint nCameraIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, float flZNear, float flZFar, ref \fBHmdMatrix44_t\fP pProjection)"

.SS "internal delegate \fBEVRTrackedCameraError\fP Valve\&.VR\&.IVRTrackedCamera\&._GetVideoStreamFrameBuffer (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, IntPtr pFrameBuffer, uint nFrameBufferSize, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"

.SS "internal delegate \fBEVRTrackedCameraError\fP Valve\&.VR\&.IVRTrackedCamera\&._GetVideoStreamTextureD3D11 (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, IntPtr pD3D11DeviceOrResource, ref IntPtr ppD3D11ShaderResourceView, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"

.SS "internal delegate \fBEVRTrackedCameraError\fP Valve\&.VR\&.IVRTrackedCamera\&._GetVideoStreamTextureGL (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, ref uint pglTextureId, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"

.SS "internal delegate \fBEVRTrackedCameraError\fP Valve\&.VR\&.IVRTrackedCamera\&._GetVideoStreamTextureSize (uint nDeviceIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref \fBVRTextureBounds_t\fP pTextureBounds, ref uint pnWidth, ref uint pnHeight)"

.SS "internal delegate \fBEVRTrackedCameraError\fP Valve\&.VR\&.IVRTrackedCamera\&._HasCamera (uint nDeviceIndex, ref bool pHasCamera)"

.SS "internal delegate \fBEVRTrackedCameraError\fP Valve\&.VR\&.IVRTrackedCamera\&._ReleaseVideoStreamingService (ulong hTrackedCamera)"

.SS "internal delegate \fBEVRTrackedCameraError\fP Valve\&.VR\&.IVRTrackedCamera\&._ReleaseVideoStreamTextureGL (ulong hTrackedCamera, uint glTextureId)"

.SH "Member Data Documentation"
.PP 
.SS "internal \fB_AcquireVideoStreamingService\fP Valve\&.VR\&.IVRTrackedCamera\&.AcquireVideoStreamingService"

.PP
Definition at line 306 of file openvr_api\&.cs\&.
.SS "internal \fB_GetCameraErrorNameFromEnum\fP Valve\&.VR\&.IVRTrackedCamera\&.GetCameraErrorNameFromEnum"

.PP
Definition at line 281 of file openvr_api\&.cs\&.
.SS "internal \fB_GetCameraFrameSize\fP Valve\&.VR\&.IVRTrackedCamera\&.GetCameraFrameSize"

.PP
Definition at line 291 of file openvr_api\&.cs\&.
.SS "internal \fB_GetCameraIntrinsics\fP Valve\&.VR\&.IVRTrackedCamera\&.GetCameraIntrinsics"

.PP
Definition at line 296 of file openvr_api\&.cs\&.
.SS "internal \fB_GetCameraProjection\fP Valve\&.VR\&.IVRTrackedCamera\&.GetCameraProjection"

.PP
Definition at line 301 of file openvr_api\&.cs\&.
.SS "internal \fB_GetVideoStreamFrameBuffer\fP Valve\&.VR\&.IVRTrackedCamera\&.GetVideoStreamFrameBuffer"

.PP
Definition at line 316 of file openvr_api\&.cs\&.
.SS "internal \fB_GetVideoStreamTextureD3D11\fP Valve\&.VR\&.IVRTrackedCamera\&.GetVideoStreamTextureD3D11"

.PP
Definition at line 326 of file openvr_api\&.cs\&.
.SS "internal \fB_GetVideoStreamTextureGL\fP Valve\&.VR\&.IVRTrackedCamera\&.GetVideoStreamTextureGL"

.PP
Definition at line 331 of file openvr_api\&.cs\&.
.SS "internal \fB_GetVideoStreamTextureSize\fP Valve\&.VR\&.IVRTrackedCamera\&.GetVideoStreamTextureSize"

.PP
Definition at line 321 of file openvr_api\&.cs\&.
.SS "internal \fB_HasCamera\fP Valve\&.VR\&.IVRTrackedCamera\&.HasCamera"

.PP
Definition at line 286 of file openvr_api\&.cs\&.
.SS "internal \fB_ReleaseVideoStreamingService\fP Valve\&.VR\&.IVRTrackedCamera\&.ReleaseVideoStreamingService"

.PP
Definition at line 311 of file openvr_api\&.cs\&.
.SS "internal \fB_ReleaseVideoStreamTextureGL\fP Valve\&.VR\&.IVRTrackedCamera\&.ReleaseVideoStreamTextureGL"

.PP
Definition at line 336 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
