.TH "Valve.VR.Compositor_CumulativeStats" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.Compositor_CumulativeStats
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint \fBm_nPid\fP"
.br
.ti -1c
.RI "uint \fBm_nNumFramePresents\fP"
.br
.ti -1c
.RI "uint \fBm_nNumDroppedFrames\fP"
.br
.ti -1c
.RI "uint \fBm_nNumReprojectedFrames\fP"
.br
.ti -1c
.RI "uint \fBm_nNumFramePresentsOnStartup\fP"
.br
.ti -1c
.RI "uint \fBm_nNumDroppedFramesOnStartup\fP"
.br
.ti -1c
.RI "uint \fBm_nNumReprojectedFramesOnStartup\fP"
.br
.ti -1c
.RI "uint \fBm_nNumLoading\fP"
.br
.ti -1c
.RI "uint \fBm_nNumFramePresentsLoading\fP"
.br
.ti -1c
.RI "uint \fBm_nNumDroppedFramesLoading\fP"
.br
.ti -1c
.RI "uint \fBm_nNumReprojectedFramesLoading\fP"
.br
.ti -1c
.RI "uint \fBm_nNumTimedOut\fP"
.br
.ti -1c
.RI "uint \fBm_nNumFramePresentsTimedOut\fP"
.br
.ti -1c
.RI "uint \fBm_nNumDroppedFramesTimedOut\fP"
.br
.ti -1c
.RI "uint \fBm_nNumReprojectedFramesTimedOut\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5386 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumDroppedFrames"

.PP
Definition at line 5390 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumDroppedFramesLoading"

.PP
Definition at line 5397 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumDroppedFramesOnStartup"

.PP
Definition at line 5393 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumDroppedFramesTimedOut"

.PP
Definition at line 5401 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumFramePresents"

.PP
Definition at line 5389 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumFramePresentsLoading"

.PP
Definition at line 5396 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumFramePresentsOnStartup"

.PP
Definition at line 5392 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumFramePresentsTimedOut"

.PP
Definition at line 5400 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumLoading"

.PP
Definition at line 5395 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumReprojectedFrames"

.PP
Definition at line 5391 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumReprojectedFramesLoading"

.PP
Definition at line 5398 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumReprojectedFramesOnStartup"

.PP
Definition at line 5394 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumReprojectedFramesTimedOut"

.PP
Definition at line 5402 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nNumTimedOut"

.PP
Definition at line 5399 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_CumulativeStats\&.m_nPid"

.PP
Definition at line 5388 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
