.TH "Valve.VR.InteractionSystem.BalloonSpawner" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.BalloonSpawner
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GameObject \fBSpawnBalloon\fP (\fBBalloon\&.BalloonColor\fP \fBcolor\fP=\fBBalloon\&.BalloonColor\&.Red\fP)"
.br
.ti -1c
.RI "void \fBSpawnBalloonFromEvent\fP (int \fBcolor\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBminSpawnTime\fP = 5f"
.br
.ti -1c
.RI "float \fBmaxSpawnTime\fP = 15f"
.br
.ti -1c
.RI "GameObject \fBballoonPrefab\fP"
.br
.ti -1c
.RI "bool \fBautoSpawn\fP = true"
.br
.ti -1c
.RI "bool \fBspawnAtStartup\fP = true"
.br
.ti -1c
.RI "bool \fBplaySounds\fP = true"
.br
.ti -1c
.RI "\fBSoundPlayOneshot\fP \fBinflateSound\fP"
.br
.ti -1c
.RI "\fBSoundPlayOneshot\fP \fBstretchSound\fP"
.br
.ti -1c
.RI "bool \fBsendSpawnMessageToParent\fP = false"
.br
.ti -1c
.RI "float \fBscale\fP = 1f"
.br
.ti -1c
.RI "Transform \fBspawnDirectionTransform\fP"
.br
.ti -1c
.RI "float \fBspawnForce\fP"
.br
.ti -1c
.RI "bool \fBattachBalloon\fP = false"
.br
.ti -1c
.RI "\fBBalloon\&.BalloonColor\fP \fBcolor\fP = \fBBalloon\&.BalloonColor\&.Random\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file BalloonSpawner\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.SpawnBalloon (\fBBalloon\&.BalloonColor\fP color = \fC\fBBalloon\&.BalloonColor\&.Red\fP\fP)"

.PP
Definition at line 72 of file BalloonSpawner\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.SpawnBalloonFromEvent (int color)"

.PP
Definition at line 115 of file BalloonSpawner\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.attachBalloon = false"

.PP
Definition at line 34 of file BalloonSpawner\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.autoSpawn = true"

.PP
Definition at line 20 of file BalloonSpawner\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.balloonPrefab"

.PP
Definition at line 18 of file BalloonSpawner\&.cs\&.
.SS "\fBBalloon\&.BalloonColor\fP Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.color = \fBBalloon\&.BalloonColor\&.Random\fP"

.PP
Definition at line 36 of file BalloonSpawner\&.cs\&.
.SS "\fBSoundPlayOneshot\fP Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.inflateSound"

.PP
Definition at line 24 of file BalloonSpawner\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.maxSpawnTime = 15f"

.PP
Definition at line 16 of file BalloonSpawner\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.minSpawnTime = 5f"

.PP
Definition at line 15 of file BalloonSpawner\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.playSounds = true"

.PP
Definition at line 23 of file BalloonSpawner\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.scale = 1f"

.PP
Definition at line 29 of file BalloonSpawner\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.sendSpawnMessageToParent = false"

.PP
Definition at line 27 of file BalloonSpawner\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.spawnAtStartup = true"

.PP
Definition at line 21 of file BalloonSpawner\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.spawnDirectionTransform"

.PP
Definition at line 31 of file BalloonSpawner\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.spawnForce"

.PP
Definition at line 32 of file BalloonSpawner\&.cs\&.
.SS "\fBSoundPlayOneshot\fP Valve\&.VR\&.InteractionSystem\&.BalloonSpawner\&.stretchSound"

.PP
Definition at line 25 of file BalloonSpawner\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
