.TH "Valve.VR.InteractionSystem.ArrowHand" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.ArrowHand
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBarrowPrefab\fP"
.br
.ti -1c
.RI "Transform \fBarrowNockTransform\fP"
.br
.ti -1c
.RI "float \fBnockDistance\fP = 0\&.1f"
.br
.ti -1c
.RI "float \fBlerpCompleteDistance\fP = 0\&.08f"
.br
.ti -1c
.RI "float \fBrotationLerpThreshold\fP = 0\&.15f"
.br
.ti -1c
.RI "float \fBpositionLerpThreshold\fP = 0\&.15f"
.br
.ti -1c
.RI "\fBSoundPlayOneshot\fP \fBarrowSpawnSound\fP"
.br
.ti -1c
.RI "int \fBmaxArrowCount\fP = 10"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file ArrowHand\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform Valve\&.VR\&.InteractionSystem\&.ArrowHand\&.arrowNockTransform"

.PP
Definition at line 23 of file ArrowHand\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.ArrowHand\&.arrowPrefab"

.PP
Definition at line 21 of file ArrowHand\&.cs\&.
.SS "\fBSoundPlayOneshot\fP Valve\&.VR\&.InteractionSystem\&.ArrowHand\&.arrowSpawnSound"

.PP
Definition at line 37 of file ArrowHand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.ArrowHand\&.lerpCompleteDistance = 0\&.08f"

.PP
Definition at line 26 of file ArrowHand\&.cs\&.
.SS "int Valve\&.VR\&.InteractionSystem\&.ArrowHand\&.maxArrowCount = 10"

.PP
Definition at line 41 of file ArrowHand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.ArrowHand\&.nockDistance = 0\&.1f"

.PP
Definition at line 25 of file ArrowHand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.ArrowHand\&.positionLerpThreshold = 0\&.15f"

.PP
Definition at line 28 of file ArrowHand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.ArrowHand\&.rotationLerpThreshold = 0\&.15f"

.PP
Definition at line 27 of file ArrowHand\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
