.TH "Valve.VR.VREvent_ProgressUpdate_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VREvent_ProgressUpdate_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ulong \fBulApplicationPropertyContainer\fP"
.br
.ti -1c
.RI "ulong \fBpathDevice\fP"
.br
.ti -1c
.RI "ulong \fBpathInputSource\fP"
.br
.ti -1c
.RI "ulong \fBpathProgressAction\fP"
.br
.ti -1c
.RI "ulong \fBpathIcon\fP"
.br
.ti -1c
.RI "float \fBfProgress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5206 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.VREvent_ProgressUpdate_t\&.fProgress"

.PP
Definition at line 5213 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VREvent_ProgressUpdate_t\&.pathDevice"

.PP
Definition at line 5209 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VREvent_ProgressUpdate_t\&.pathIcon"

.PP
Definition at line 5212 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VREvent_ProgressUpdate_t\&.pathInputSource"

.PP
Definition at line 5210 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VREvent_ProgressUpdate_t\&.pathProgressAction"

.PP
Definition at line 5211 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VREvent_ProgressUpdate_t\&.ulApplicationPropertyContainer"

.PP
Definition at line 5208 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
