.TH "Valve.VR.InteractionSystem.RenderModel" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.RenderModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSteamVR_Behaviour_Skeleton\fP \fBGetSkeleton\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetInputSource\fP (\fBSteamVR_Input_Sources\fP newInputSource)"
.br
.ti -1c
.RI "virtual void \fBOnHandInitialized\fP (int deviceIndex)"
.br
.ti -1c
.RI "void \fBMatchHandToTransform\fP (Transform match)"
.br
.ti -1c
.RI "void \fBSetHandPosition\fP (Vector3 newPosition)"
.br
.ti -1c
.RI "void \fBSetHandRotation\fP (Quaternion newRotation)"
.br
.ti -1c
.RI "Vector3 \fBGetHandPosition\fP ()"
.br
.ti -1c
.RI "Quaternion \fBGetHandRotation\fP ()"
.br
.ti -1c
.RI "void \fBSetVisibility\fP (bool state, bool overrideDefault=false)"
.br
.ti -1c
.RI "void \fBShow\fP (bool overrideDefault=false)"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetMaterial\fP (Material material)"
.br
.ti -1c
.RI "void \fBSetControllerMaterial\fP (Material material)"
.br
.ti -1c
.RI "void \fBSetHandMaterial\fP (Material material)"
.br
.ti -1c
.RI "void \fBSetControllerVisibility\fP (bool state, bool permanent=false)"
.br
.ti -1c
.RI "void \fBSetHandVisibility\fP (bool state, bool permanent=false)"
.br
.ti -1c
.RI "bool \fBIsHandVisibile\fP ()"
.br
.ti -1c
.RI "bool \fBIsControllerVisibile\fP ()"
.br
.ti -1c
.RI "Transform \fBGetBone\fP (int boneIndex)"
.br
.ti -1c
.RI "Vector3 \fBGetBonePosition\fP (int boneIndex, bool local=false)"
.br
.ti -1c
.RI "Vector3 \fBGetControllerPosition\fP (string componentName=null)"
.br
.ti -1c
.RI "Quaternion \fBGetBoneRotation\fP (int boneIndex, bool local=false)"
.br
.ti -1c
.RI "void \fBSetSkeletonRangeOfMotion\fP (\fBEVRSkeletalMotionRange\fP newRangeOfMotion, float blendOverSeconds=0\&.1f)"
.br
.ti -1c
.RI "void \fBSetTemporarySkeletonRangeOfMotion\fP (\fBSkeletalMotionRangeChange\fP temporaryRangeOfMotionChange, float blendOverSeconds=0\&.1f)"
.br
.ti -1c
.RI "void \fBResetTemporarySkeletonRangeOfMotion\fP (float blendOverSeconds=0\&.1f)"
.br
.ti -1c
.RI "void \fBSetAnimationState\fP (int stateValue)"
.br
.ti -1c
.RI "void \fBStopAnimation\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBhandPrefab\fP"
.br
.ti -1c
.RI "bool \fBdisplayHandByDefault\fP = true"
.br
.ti -1c
.RI "GameObject \fBcontrollerPrefab\fP"
.br
.ti -1c
.RI "bool \fBdisplayControllerByDefault\fP = true"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBInitializeHand\fP ()"
.br
.ti -1c
.RI "void \fBInitializeController\fP ()"
.br
.ti -1c
.RI "virtual void \fBDestroyHand\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnSkeletonActiveChange\fP (\fBSteamVR_Action_Skeleton\fP changedAction, bool newState)"
.br
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBOnDestroy\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBhandInstance\fP"
.br
.ti -1c
.RI "Renderer [] \fBhandRenderers\fP"
.br
.ti -1c
.RI "\fBSteamVR_Behaviour_Skeleton\fP \fBhandSkeleton\fP"
.br
.ti -1c
.RI "Animator \fBhandAnimator\fP"
.br
.ti -1c
.RI "string \fBanimatorParameterStateName\fP = 'AnimationState'"
.br
.ti -1c
.RI "int \fBhandAnimatorStateId\fP = \-1"
.br
.ti -1c
.RI "GameObject \fBcontrollerInstance\fP"
.br
.ti -1c
.RI "Renderer [] \fBcontrollerRenderers\fP"
.br
.ti -1c
.RI "\fBSteamVR_RenderModel\fP \fBcontrollerRenderModel\fP"
.br
.ti -1c
.RI "Material \fBdelayedSetMaterial\fP"
.br
.ti -1c
.RI "\fBSteamVR_Events\&.Action\fP \fBrenderModelLoadedAction\fP"
.br
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBinputSource\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEVRSkeletalMotionRange\fP \fBGetSkeletonRangeOfMotion\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action \fBonControllerLoaded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file RenderModel\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.Awake ()\fC [protected]\fP"

.PP
Definition at line 36 of file RenderModel\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.DestroyHand ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 86 of file RenderModel\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.RenderModel\&.GetBone (int boneIndex)"

.PP
Definition at line 310 of file RenderModel\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.RenderModel\&.GetBonePosition (int boneIndex, bool local = \fCfalse\fP)"

.PP
Definition at line 320 of file RenderModel\&.cs\&.
.SS "Quaternion Valve\&.VR\&.InteractionSystem\&.RenderModel\&.GetBoneRotation (int boneIndex, bool local = \fCfalse\fP)"

.PP
Definition at line 338 of file RenderModel\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.RenderModel\&.GetControllerPosition (string componentName = \fCnull\fP)"

.PP
Definition at line 330 of file RenderModel\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.RenderModel\&.GetHandPosition ()"

.PP
Definition at line 171 of file RenderModel\&.cs\&.
.SS "Quaternion Valve\&.VR\&.InteractionSystem\&.RenderModel\&.GetHandRotation ()"

.PP
Definition at line 181 of file RenderModel\&.cs\&.
.SS "\fBSteamVR_Behaviour_Skeleton\fP Valve\&.VR\&.InteractionSystem\&.RenderModel\&.GetSkeleton ()"

.PP
Definition at line 128 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.Hide ()"

.PP
Definition at line 221 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.InitializeController ()\fC [protected]\fP"

.PP
Definition at line 73 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.InitializeHand ()\fC [protected]\fP"

.PP
Definition at line 45 of file RenderModel\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.RenderModel\&.IsControllerVisibile ()"

.PP
Definition at line 296 of file RenderModel\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.RenderModel\&.IsHandVisibile ()"

.PP
Definition at line 282 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.MatchHandToTransform (Transform match)"

.PP
Definition at line 146 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.OnDestroy ()\fC [protected]\fP"

.PP
Definition at line 123 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.OnDisable ()\fC [protected]\fP"

.PP
Definition at line 118 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.OnEnable ()\fC [protected]\fP"

.PP
Definition at line 113 of file RenderModel\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.OnHandInitialized (int deviceIndex)\fC [virtual]\fP"

.PP
Definition at line 140 of file RenderModel\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.OnSkeletonActiveChange (\fBSteamVR_Action_Skeleton\fP changedAction, bool newState)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 101 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.ResetTemporarySkeletonRangeOfMotion (float blendOverSeconds = \fC0\&.1f\fP)"

.PP
Definition at line 376 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetAnimationState (int stateValue)"

.PP
Definition at line 384 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetControllerMaterial (Material material)"

.PP
Definition at line 232 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetControllerVisibility (bool state, bool permanent = \fCfalse\fP)"

.PP
Definition at line 254 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetHandMaterial (Material material)"

.PP
Definition at line 246 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetHandPosition (Vector3 newPosition)"

.PP
Definition at line 155 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetHandRotation (Quaternion newRotation)"

.PP
Definition at line 163 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetHandVisibility (bool state, bool permanent = \fCfalse\fP)"

.PP
Definition at line 268 of file RenderModel\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetInputSource (\fBSteamVR_Input_Sources\fP newInputSource)\fC [virtual]\fP"

.PP
Definition at line 133 of file RenderModel\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetMaterial (Material material)\fC [virtual]\fP"

.PP
Definition at line 226 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetSkeletonRangeOfMotion (\fBEVRSkeletalMotionRange\fP newRangeOfMotion, float blendOverSeconds = \fC0\&.1f\fP)"

.PP
Definition at line 349 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetTemporarySkeletonRangeOfMotion (\fBSkeletalMotionRangeChange\fP temporaryRangeOfMotionChange, float blendOverSeconds = \fC0\&.1f\fP)"

.PP
Definition at line 368 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.SetVisibility (bool state, bool overrideDefault = \fCfalse\fP)"

.PP
Definition at line 207 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.Show (bool overrideDefault = \fCfalse\fP)"

.PP
Definition at line 216 of file RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.RenderModel\&.StopAnimation ()"

.PP
Definition at line 396 of file RenderModel\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Valve\&.VR\&.InteractionSystem\&.RenderModel\&.animatorParameterStateName = 'AnimationState'\fC [protected]\fP"

.PP
Definition at line 18 of file RenderModel\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.RenderModel\&.controllerInstance\fC [protected]\fP"

.PP
Definition at line 24 of file RenderModel\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.RenderModel\&.controllerPrefab"

.PP
Definition at line 23 of file RenderModel\&.cs\&.
.SS "Renderer [] Valve\&.VR\&.InteractionSystem\&.RenderModel\&.controllerRenderers\fC [protected]\fP"

.PP
Definition at line 25 of file RenderModel\&.cs\&.
.SS "\fBSteamVR_RenderModel\fP Valve\&.VR\&.InteractionSystem\&.RenderModel\&.controllerRenderModel\fC [protected]\fP"

.PP
Definition at line 26 of file RenderModel\&.cs\&.
.SS "Material Valve\&.VR\&.InteractionSystem\&.RenderModel\&.delayedSetMaterial\fC [protected]\fP"

.PP
Definition at line 28 of file RenderModel\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.RenderModel\&.displayControllerByDefault = true"

.PP
Definition at line 27 of file RenderModel\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.RenderModel\&.displayHandByDefault = true"

.PP
Definition at line 14 of file RenderModel\&.cs\&.
.SS "Animator Valve\&.VR\&.InteractionSystem\&.RenderModel\&.handAnimator\fC [protected]\fP"

.PP
Definition at line 16 of file RenderModel\&.cs\&.
.SS "int Valve\&.VR\&.InteractionSystem\&.RenderModel\&.handAnimatorStateId = \-1\fC [protected]\fP"

.PP
Definition at line 19 of file RenderModel\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.RenderModel\&.handInstance\fC [protected]\fP"

.PP
Definition at line 12 of file RenderModel\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.RenderModel\&.handPrefab"

.PP
Definition at line 11 of file RenderModel\&.cs\&.
.SS "Renderer [] Valve\&.VR\&.InteractionSystem\&.RenderModel\&.handRenderers\fC [protected]\fP"

.PP
Definition at line 13 of file RenderModel\&.cs\&.
.SS "\fBSteamVR_Behaviour_Skeleton\fP Valve\&.VR\&.InteractionSystem\&.RenderModel\&.handSkeleton\fC [protected]\fP"

.PP
Definition at line 15 of file RenderModel\&.cs\&.
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.InteractionSystem\&.RenderModel\&.inputSource\fC [protected]\fP"

.PP
Definition at line 34 of file RenderModel\&.cs\&.
.SS "\fBSteamVR_Events\&.Action\fP Valve\&.VR\&.InteractionSystem\&.RenderModel\&.renderModelLoadedAction\fC [protected]\fP"

.PP
Definition at line 32 of file RenderModel\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBEVRSkeletalMotionRange\fP Valve\&.VR\&.InteractionSystem\&.RenderModel\&.GetSkeletonRangeOfMotion\fC [get]\fP"

.PP
Definition at line 358 of file RenderModel\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "Action Valve\&.VR\&.InteractionSystem\&.RenderModel\&.onControllerLoaded"

.PP
Definition at line 30 of file RenderModel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
