.TH "Valve.VR.InteractionSystem.Hand" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Hand
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAttachedObject\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAttachmentFlags\fP { \fBAttachmentFlags\&.SnapOnAttach\fP = 1 << 0, \fBAttachmentFlags\&.DetachOthers\fP = 1 << 1, \fBAttachmentFlags\&.DetachFromOtherHand\fP = 1 << 2, \fBAttachmentFlags\&.ParentToHand\fP = 1 << 3, \fBAttachmentFlags\&.VelocityMovement\fP = 1 << 4, \fBAttachmentFlags\&.TurnOnKinematic\fP = 1 << 5, \fBAttachmentFlags\&.TurnOffGravity\fP = 1 << 6, \fBAttachmentFlags\&.AllowSidegrade\fP = 1 << 7 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShowController\fP (bool permanent=false)"
.br
.ti -1c
.RI "void \fBHideController\fP (bool permanent=false)"
.br
.ti -1c
.RI "void \fBShowSkeleton\fP (bool permanent=false)"
.br
.ti -1c
.RI "void \fBHideSkeleton\fP (bool permanent=false)"
.br
.ti -1c
.RI "bool \fBHasSkeleton\fP ()"
.br
.ti -1c
.RI "void \fBShow\fP ()"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.ti -1c
.RI "void \fBSetVisibility\fP (bool visible)"
.br
.ti -1c
.RI "void \fBSetSkeletonRangeOfMotion\fP (\fBEVRSkeletalMotionRange\fP newRangeOfMotion, float blendOverSeconds=0\&.1f)"
.br
.ti -1c
.RI "void \fBSetTemporarySkeletonRangeOfMotion\fP (\fBSkeletalMotionRangeChange\fP temporaryRangeOfMotionChange, float blendOverSeconds=0\&.1f)"
.br
.ti -1c
.RI "void \fBResetTemporarySkeletonRangeOfMotion\fP (float blendOverSeconds=0\&.1f)"
.br
.ti -1c
.RI "void \fBSetAnimationState\fP (int stateValue)"
.br
.ti -1c
.RI "void \fBStopAnimation\fP ()"
.br
.ti -1c
.RI "void \fBAttachObject\fP (GameObject objectToAttach, \fBGrabTypes\fP grabbedWithType, \fBAttachmentFlags\fP flags=\fBdefaultAttachmentFlags\fP, Transform attachmentOffset=null)"
.br
.ti -1c
.RI "bool \fBObjectIsAttached\fP (GameObject go)"
.br
.ti -1c
.RI "void \fBForceHoverUnlock\fP ()"
.br
.ti -1c
.RI "void \fBDetachObject\fP (GameObject objectToDetach, bool restoreOriginalParent=true)"
.br
.ti -1c
.RI "Vector3 \fBGetTrackedObjectVelocity\fP (float timeOffset=0)"
.br
.ti -1c
.RI "Vector3 \fBGetTrackedObjectAngularVelocity\fP (float timeOffset=0)"
.br
.ti -1c
.RI "void \fBGetEstimatedPeakVelocities\fP (out Vector3 velocity, out Vector3 angularVelocity)"
.br
.ti -1c
.RI "bool \fBIsStillHovering\fP (\fBInteractable\fP interactable)"
.br
.RI "Returns true when the hand is currently hovering over the interactable passed in "
.ti -1c
.RI "void \fBHoverLock\fP (\fBInteractable\fP interactable)"
.br
.ti -1c
.RI "void \fBHoverUnlock\fP (\fBInteractable\fP interactable)"
.br
.ti -1c
.RI "void \fBTriggerHapticPulse\fP (ushort microSecondsDuration)"
.br
.ti -1c
.RI "void \fBTriggerHapticPulse\fP (float duration, float frequency, float amplitude)"
.br
.ti -1c
.RI "void \fBShowGrabHint\fP ()"
.br
.ti -1c
.RI "void \fBHideGrabHint\fP ()"
.br
.ti -1c
.RI "void \fBShowGrabHint\fP (string text)"
.br
.ti -1c
.RI "\fBGrabTypes\fP \fBGetGrabStarting\fP (\fBGrabTypes\fP explicitType=\fBGrabTypes\&.None\fP)"
.br
.ti -1c
.RI "\fBGrabTypes\fP \fBGetGrabEnding\fP (\fBGrabTypes\fP explicitType=\fBGrabTypes\&.None\fP)"
.br
.ti -1c
.RI "bool \fBIsGrabEnding\fP (GameObject attachedObject)"
.br
.ti -1c
.RI "bool \fBIsGrabbingWithType\fP (\fBGrabTypes\fP type)"
.br
.ti -1c
.RI "bool \fBIsGrabbingWithOppositeType\fP (\fBGrabTypes\fP type)"
.br
.ti -1c
.RI "\fBGrabTypes\fP \fBGetBestGrabbingType\fP ()"
.br
.ti -1c
.RI "\fBGrabTypes\fP \fBGetBestGrabbingType\fP (\fBGrabTypes\fP preferred, bool forcePreference=false)"
.br
.ti -1c
.RI "void \fBSetRenderModel\fP (GameObject prefab)"
.br
.ti -1c
.RI "void \fBSetHoverRenderModel\fP (\fBRenderModel\fP hoverRenderModel)"
.br
.ti -1c
.RI "int \fBGetDeviceIndex\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBAttachmentFlags\fP \fBdefaultAttachmentFlags\fP"
.br
.ti -1c
.RI "\fBHand\fP \fBotherHand\fP"
.br
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBhandType\fP"
.br
.ti -1c
.RI "\fBSteamVR_Behaviour_Pose\fP \fBtrackedObject\fP"
.br
.ti -1c
.RI "\fBSteamVR_Action_Boolean\fP \fBgrabPinchAction\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('GrabPinch')"
.br
.ti -1c
.RI "\fBSteamVR_Action_Boolean\fP \fBgrabGripAction\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('GrabGrip')"
.br
.ti -1c
.RI "\fBSteamVR_Action_Vibration\fP \fBhapticAction\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Vibration\fP>('Haptic')"
.br
.ti -1c
.RI "\fBSteamVR_Action_Boolean\fP \fBuiInteractAction\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('InteractUI')"
.br
.ti -1c
.RI "bool \fBuseHoverSphere\fP = true"
.br
.ti -1c
.RI "Transform \fBhoverSphereTransform\fP"
.br
.ti -1c
.RI "float \fBhoverSphereRadius\fP = 0\&.05f"
.br
.ti -1c
.RI "LayerMask \fBhoverLayerMask\fP = \-1"
.br
.ti -1c
.RI "float \fBhoverUpdateInterval\fP = 0\&.1f"
.br
.ti -1c
.RI "bool \fBuseControllerHoverComponent\fP = true"
.br
.ti -1c
.RI "string \fBcontrollerHoverComponent\fP = 'tip'"
.br
.ti -1c
.RI "float \fBcontrollerHoverRadius\fP = 0\&.075f"
.br
.ti -1c
.RI "bool \fBuseFingerJointHover\fP = true"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_JointIndexEnum\fP \fBfingerJointHover\fP = \fBSteamVR_Skeleton_JointIndexEnum\&.indexTip\fP"
.br
.ti -1c
.RI "float \fBfingerJointHoverRadius\fP = 0\&.025f"
.br
.ti -1c
.RI "Transform \fBobjectAttachmentPoint\fP"
.br
.ti -1c
.RI "Camera \fBnoSteamVRFallbackCamera\fP"
.br
.ti -1c
.RI "float \fBnoSteamVRFallbackMaxDistanceNoItem\fP = 10\&.0f"
.br
.ti -1c
.RI "float \fBnoSteamVRFallbackMaxDistanceWithItem\fP = 0\&.5f"
.br
.ti -1c
.RI "GameObject \fBrenderModelPrefab\fP"
.br
.ti -1c
.RI "bool \fBshowDebugText\fP = false"
.br
.ti -1c
.RI "bool \fBspewDebugText\fP = false"
.br
.ti -1c
.RI "bool \fBshowDebugInteractables\fP = false"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnTransformUpdated\fP (\fBSteamVR_Behaviour_Pose\fP updatedPose, \fBSteamVR_Input_Sources\fP updatedSource)"
.br
.ti -1c
.RI "virtual IEnumerator \fBStart\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdateHovering\fP ()"
.br
.ti -1c
.RI "virtual bool \fBCheckHoveringForTransform\fP (Vector3 hoverPosition, float hoverRadius, ref float closestDistance, ref \fBInteractable\fP closestInteractable, Color debugColor)"
.br
.ti -1c
.RI "virtual void \fBUpdateNoSteamVRFallback\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBHandFollowUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBFixedUpdate\fP ()"
.br
.ti -1c
.RI "void \fBUpdateAttachedVelocity\fP (\fBAttachedObject\fP attachedObjectInfo)"
.br
.ti -1c
.RI "Vector3 \fBTargetItemPosition\fP (\fBAttachedObject\fP attachedObject)"
.br
.ti -1c
.RI "Quaternion \fBTargetItemRotation\fP (\fBAttachedObject\fP attachedObject)"
.br
.ti -1c
.RI "bool \fBGetUpdatedAttachedVelocities\fP (\fBAttachedObject\fP attachedObjectInfo, out Vector3 velocityTarget, out Vector3 angularTarget)"
.br
.ti -1c
.RI "virtual void \fBOnInputFocus\fP (bool hasFocus)"
.br
.ti -1c
.RI "virtual void \fBOnDrawGizmos\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "List< \fBRenderModel\fP > \fBrenderModels\fP = new List<\fBRenderModel\fP>()"
.br
.ti -1c
.RI "\fBRenderModel\fP \fBmainRenderModel\fP"
.br
.ti -1c
.RI "\fBRenderModel\fP \fBhoverhighlightRenderModel\fP"
.br
.ti -1c
.RI "const float \fBMaxVelocityChange\fP = 10f"
.br
.ti -1c
.RI "const float \fBVelocityMagic\fP = 6000f"
.br
.ti -1c
.RI "const float \fBAngularVelocityMagic\fP = 50f"
.br
.ti -1c
.RI "const float \fBMaxAngularVelocityChange\fP = 20f"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ReadOnlyCollection< \fBAttachedObject\fP > \fBAttachedObjects\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBhoverLocked\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBisActive\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBisPoseValid\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBInteractable\fP \fBhoveringInteractable\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "GameObject \fBcurrentAttachedObject\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBAttachedObject\fP? \fBcurrentAttachedObjectInfo\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBSteamVR_Behaviour_Skeleton\fP \fBskeleton\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Hand\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.InteractionSystem\&.Hand\&.AttachmentFlags\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISnapOnAttach \fP\fP
.TP
\fB\fIDetachOthers \fP\fP
.TP
\fB\fIDetachFromOtherHand \fP\fP
.TP
\fB\fIParentToHand \fP\fP
.TP
\fB\fIVelocityMovement \fP\fP
.TP
\fB\fITurnOnKinematic \fP\fP
.TP
\fB\fITurnOffGravity \fP\fP
.TP
\fB\fIAllowSidegrade \fP\fP
.PP
Definition at line 25 of file Hand\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.AttachObject (GameObject objectToAttach, \fBGrabTypes\fP grabbedWithType, \fBAttachmentFlags\fP flags = \fC\fBdefaultAttachmentFlags\fP\fP, Transform attachmentOffset = \fCnull\fP)"

.PP
Definition at line 347 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.Awake ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 760 of file Hand\&.cs\&.
.SS "virtual bool Valve\&.VR\&.InteractionSystem\&.Hand\&.CheckHoveringForTransform (Vector3 hoverPosition, float hoverRadius, ref float closestDistance, ref \fBInteractable\fP closestInteractable, Color debugColor)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 871 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.DetachObject (GameObject objectToDetach, bool restoreOriginalParent = \fCtrue\fP)"

.PP
Definition at line 584 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.FixedUpdate ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1159 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.ForceHoverUnlock ()"

.PP
Definition at line 574 of file Hand\&.cs\&.
.SS "\fBGrabTypes\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.GetBestGrabbingType ()"

.PP
Definition at line 1536 of file Hand\&.cs\&.
.SS "\fBGrabTypes\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.GetBestGrabbingType (\fBGrabTypes\fP preferred, bool forcePreference = \fCfalse\fP)"

.PP
Definition at line 1541 of file Hand\&.cs\&.
.SS "int Valve\&.VR\&.InteractionSystem\&.Hand\&.GetDeviceIndex ()"

.PP
Definition at line 1629 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.GetEstimatedPeakVelocities (out Vector3 velocity, out Vector3 angularVelocity)"

.PP
Definition at line 744 of file Hand\&.cs\&.
.SS "\fBGrabTypes\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.GetGrabEnding (\fBGrabTypes\fP explicitType = \fC\fBGrabTypes\&.None\fP\fP)"

.PP
Definition at line 1449 of file Hand\&.cs\&.
.SS "\fBGrabTypes\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.GetGrabStarting (\fBGrabTypes\fP explicitType = \fC\fBGrabTypes\&.None\fP\fP)"

.PP
Definition at line 1417 of file Hand\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.Hand\&.GetTrackedObjectAngularVelocity (float timeOffset = \fC0\fP)"

.PP
Definition at line 718 of file Hand\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.Hand\&.GetTrackedObjectVelocity (float timeOffset = \fC0\fP)"

.PP
Definition at line 688 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.GetUpdatedAttachedVelocities (\fBAttachedObject\fP attachedObjectInfo, out Vector3 velocityTarget, out Vector3 angularTarget)\fC [protected]\fP"

.PP
Definition at line 1257 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.HandFollowUpdate ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1100 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.HasSkeleton ()"

.PP
Definition at line 278 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.Hide ()"

.PP
Definition at line 288 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.HideController (bool permanent = \fCfalse\fP)"

.PP
Definition at line 251 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.HideGrabHint ()"

.PP
Definition at line 1407 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.HideSkeleton (bool permanent = \fCfalse\fP)"

.PP
Definition at line 269 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.HoverLock (\fBInteractable\fP interactable)"

.PP
Definition at line 1366 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.HoverUnlock (\fBInteractable\fP interactable)"

.PP
Definition at line 1380 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.IsGrabbingWithOppositeType (\fBGrabTypes\fP type)"

.PP
Definition at line 1515 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.IsGrabbingWithType (\fBGrabTypes\fP type)"

.PP
Definition at line 1494 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.IsGrabEnding (GameObject attachedObject)"

.PP
Definition at line 1481 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.IsStillHovering (\fBInteractable\fP interactable)"

.PP
Returns true when the hand is currently hovering over the interactable passed in 
.PP
Definition at line 1095 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.ObjectIsAttached (GameObject go)"

.PP
Definition at line 563 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.OnDestroy ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 783 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.OnDisable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1067 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.OnDrawGizmos ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1326 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.OnEnable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1055 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.OnInputFocus (bool hasFocus)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1308 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.OnTransformUpdated (\fBSteamVR_Behaviour_Pose\fP updatedPose, \fBSteamVR_Input_Sources\fP updatedSource)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 791 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.ResetTemporarySkeletonRangeOfMotion (float blendOverSeconds = \fC0\&.1f\fP)"

.PP
Definition at line 315 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.SetAnimationState (int stateValue)"

.PP
Definition at line 323 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.SetHoverRenderModel (\fBRenderModel\fP hoverRenderModel)"

.PP
Definition at line 1623 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.SetRenderModel (GameObject prefab)"

.PP
Definition at line 1615 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.SetSkeletonRangeOfMotion (\fBEVRSkeletalMotionRange\fP newRangeOfMotion, float blendOverSeconds = \fC0\&.1f\fP)"

.PP
Definition at line 299 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.SetTemporarySkeletonRangeOfMotion (\fBSkeletalMotionRangeChange\fP temporaryRangeOfMotionChange, float blendOverSeconds = \fC0\&.1f\fP)"

.PP
Definition at line 307 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.SetVisibility (bool visible)"

.PP
Definition at line 293 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.Show ()"

.PP
Definition at line 283 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.ShowController (bool permanent = \fCfalse\fP)"

.PP
Definition at line 242 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.ShowGrabHint ()"

.PP
Definition at line 1402 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.ShowGrabHint (string text)"

.PP
Definition at line 1412 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.ShowSkeleton (bool permanent = \fCfalse\fP)"

.PP
Definition at line 260 of file Hand\&.cs\&.
.SS "virtual IEnumerator Valve\&.VR\&.InteractionSystem\&.Hand\&.Start ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 797 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.StopAnimation ()"

.PP
Definition at line 331 of file Hand\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.Hand\&.TargetItemPosition (\fBAttachedObject\fP attachedObject)\fC [protected]\fP"

.PP
Definition at line 1230 of file Hand\&.cs\&.
.SS "Quaternion Valve\&.VR\&.InteractionSystem\&.Hand\&.TargetItemRotation (\fBAttachedObject\fP attachedObject)\fC [protected]\fP"

.PP
Definition at line 1244 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.TriggerHapticPulse (ushort microSecondsDuration)"

.PP
Definition at line 1391 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.TriggerHapticPulse (float duration, float frequency, float amplitude)"

.PP
Definition at line 1397 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.Update ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1076 of file Hand\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Hand\&.UpdateAttachedVelocity (\fBAttachedObject\fP attachedObjectInfo)\fC [protected]\fP"

.PP
Definition at line 1215 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.UpdateHovering ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 833 of file Hand\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Hand\&.UpdateNoSteamVRFallback ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 959 of file Hand\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const float Valve\&.VR\&.InteractionSystem\&.Hand\&.AngularVelocityMagic = 50f\fC [protected]\fP"

.PP
Definition at line 1212 of file Hand\&.cs\&.
.SS "string Valve\&.VR\&.InteractionSystem\&.Hand\&.controllerHoverComponent = 'tip'"

.PP
Definition at line 63 of file Hand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Hand\&.controllerHoverRadius = 0\&.075f"

.PP
Definition at line 64 of file Hand\&.cs\&.
.SS "const \fBAttachmentFlags\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.defaultAttachmentFlags"
\fBInitial value:\fP
.PP
.nf
= AttachmentFlags\&.ParentToHand |
                                                              AttachmentFlags\&.DetachOthers |
                                                              AttachmentFlags\&.DetachFromOtherHand |
                                                              AttachmentFlags\&.TurnOnKinematic |
                                                              AttachmentFlags\&.SnapOnAttach
.fi
.PP
Definition at line 37 of file Hand\&.cs\&.
.SS "\fBSteamVR_Skeleton_JointIndexEnum\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.fingerJointHover = \fBSteamVR_Skeleton_JointIndexEnum\&.indexTip\fP"

.PP
Definition at line 67 of file Hand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Hand\&.fingerJointHoverRadius = 0\&.025f"

.PP
Definition at line 68 of file Hand\&.cs\&.
.SS "\fBSteamVR_Action_Boolean\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.grabGripAction = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('GrabGrip')"

.PP
Definition at line 50 of file Hand\&.cs\&.
.SS "\fBSteamVR_Action_Boolean\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.grabPinchAction = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('GrabPinch')"

.PP
Definition at line 48 of file Hand\&.cs\&.
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.handType"

.PP
Definition at line 44 of file Hand\&.cs\&.
.SS "\fBSteamVR_Action_Vibration\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.hapticAction = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Vibration\fP>('Haptic')"

.PP
Definition at line 52 of file Hand\&.cs\&.
.SS "\fBRenderModel\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.hoverhighlightRenderModel\fC [protected]\fP"

.PP
Definition at line 81 of file Hand\&.cs\&.
.SS "LayerMask Valve\&.VR\&.InteractionSystem\&.Hand\&.hoverLayerMask = \-1"

.PP
Definition at line 59 of file Hand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Hand\&.hoverSphereRadius = 0\&.05f"

.PP
Definition at line 58 of file Hand\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Hand\&.hoverSphereTransform"

.PP
Definition at line 57 of file Hand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Hand\&.hoverUpdateInterval = 0\&.1f"

.PP
Definition at line 60 of file Hand\&.cs\&.
.SS "\fBRenderModel\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.mainRenderModel\fC [protected]\fP"

.PP
Definition at line 80 of file Hand\&.cs\&.
.SS "const float Valve\&.VR\&.InteractionSystem\&.Hand\&.MaxAngularVelocityChange = 20f\fC [protected]\fP"

.PP
Definition at line 1213 of file Hand\&.cs\&.
.SS "const float Valve\&.VR\&.InteractionSystem\&.Hand\&.MaxVelocityChange = 10f\fC [protected]\fP"

.PP
Definition at line 1210 of file Hand\&.cs\&.
.SS "Camera Valve\&.VR\&.InteractionSystem\&.Hand\&.noSteamVRFallbackCamera"

.PP
Definition at line 73 of file Hand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Hand\&.noSteamVRFallbackMaxDistanceNoItem = 10\&.0f"

.PP
Definition at line 74 of file Hand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Hand\&.noSteamVRFallbackMaxDistanceWithItem = 0\&.5f"

.PP
Definition at line 75 of file Hand\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Hand\&.objectAttachmentPoint"

.PP
Definition at line 71 of file Hand\&.cs\&.
.SS "\fBHand\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.otherHand"

.PP
Definition at line 43 of file Hand\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.Hand\&.renderModelPrefab"

.PP
Definition at line 78 of file Hand\&.cs\&.
.SS "List<\fBRenderModel\fP> Valve\&.VR\&.InteractionSystem\&.Hand\&.renderModels = new List<\fBRenderModel\fP>()\fC [protected]\fP"

.PP
Definition at line 79 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.showDebugInteractables = false"

.PP
Definition at line 85 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.showDebugText = false"

.PP
Definition at line 83 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.spewDebugText = false"

.PP
Definition at line 84 of file Hand\&.cs\&.
.SS "\fBSteamVR_Behaviour_Pose\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.trackedObject"

.PP
Definition at line 46 of file Hand\&.cs\&.
.SS "\fBSteamVR_Action_Boolean\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.uiInteractAction = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('InteractUI')"

.PP
Definition at line 54 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.useControllerHoverComponent = true"

.PP
Definition at line 62 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.useFingerJointHover = true"

.PP
Definition at line 66 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.useHoverSphere = true"

.PP
Definition at line 56 of file Hand\&.cs\&.
.SS "const float Valve\&.VR\&.InteractionSystem\&.Hand\&.VelocityMagic = 6000f\fC [protected]\fP"

.PP
Definition at line 1211 of file Hand\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "ReadOnlyCollection<\fBAttachedObject\fP> Valve\&.VR\&.InteractionSystem\&.Hand\&.AttachedObjects\fC [get]\fP"

.PP
Definition at line 116 of file Hand\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.Hand\&.currentAttachedObject\fC [get]\fP"

.PP
Definition at line 202 of file Hand\&.cs\&.
.SS "\fBAttachedObject\fP? Valve\&.VR\&.InteractionSystem\&.Hand\&.currentAttachedObjectInfo\fC [get]\fP"

.PP
Definition at line 217 of file Hand\&.cs\&.
.SS "\fBInteractable\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.hoveringInteractable\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 160 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.hoverLocked\fC [get]\fP"

.PP
Definition at line 120 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.isActive\fC [get]\fP"

.PP
Definition at line 137 of file Hand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Hand\&.isPoseValid\fC [get]\fP"

.PP
Definition at line 148 of file Hand\&.cs\&.
.SS "\fBSteamVR_Behaviour_Skeleton\fP Valve\&.VR\&.InteractionSystem\&.Hand\&.skeleton\fC [get]\fP"

.PP
Definition at line 232 of file Hand\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
