.TH "Valve.VR.NotificationBitmap_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.NotificationBitmap_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IntPtr \fBm_pImageData\fP"
.br
.ti -1c
.RI "int \fBm_nWidth\fP"
.br
.ti -1c
.RI "int \fBm_nHeight\fP"
.br
.ti -1c
.RI "int \fBm_nBytesPerPixel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5511 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int Valve\&.VR\&.NotificationBitmap_t\&.m_nBytesPerPixel"

.PP
Definition at line 5516 of file openvr_api\&.cs\&.
.SS "int Valve\&.VR\&.NotificationBitmap_t\&.m_nHeight"

.PP
Definition at line 5515 of file openvr_api\&.cs\&.
.SS "int Valve\&.VR\&.NotificationBitmap_t\&.m_nWidth"

.PP
Definition at line 5514 of file openvr_api\&.cs\&.
.SS "IntPtr Valve\&.VR\&.NotificationBitmap_t\&.m_pImageData"

.PP
Definition at line 5513 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
