.TH "Valve.VR.SteamVR_Action_Pose" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Action_Pose \- Pose actions represent a position, rotation, and velocities inside the tracked space\&. \fBSteamVR\fP keeps a log of past poses so you can retrieve old poses with GetPoseAtTimeOffset or GetVelocitiesAtTimeOffset\&. You can also pass in times in the future to these methods for \fBSteamVR\fP's best prediction of where the pose will be at that time\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_Action_Pose_Base< SteamVR_Action_Pose_Source_Map< SteamVR_Action_Pose_Source >, SteamVR_Action_Pose_Source >\fP, and ISerializationCallbackReceiver\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBActiveChangeHandler\fP (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool active)"
.br
.ti -1c
.RI "delegate void \fBChangeHandler\fP (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource)"
.br
.ti -1c
.RI "delegate void \fBUpdateHandler\fP (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource)"
.br
.ti -1c
.RI "delegate void \fBTrackingChangeHandler\fP (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, \fBETrackingResult\fP \fBtrackingState\fP)"
.br
.ti -1c
.RI "delegate void \fBValidPoseChangeHandler\fP (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool validPose)"
.br
.ti -1c
.RI "delegate void \fBDeviceConnectedChangeHandler\fP (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool deviceConnected)"
.br
.ti -1c
.RI "void \fBAddOnDeviceConnectedChanged\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBDeviceConnectedChangeHandler\fP functionToCall)"
.br
.RI "Fires an event when a device is connected or disconnected\&. "
.ti -1c
.RI "void \fBRemoveOnDeviceConnectedChanged\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBDeviceConnectedChangeHandler\fP functionToStopCalling)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.ti -1c
.RI "void \fBAddOnTrackingChanged\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBTrackingChangeHandler\fP functionToCall)"
.br
.RI "Fires an event when the tracking of the device has changed "
.ti -1c
.RI "void \fBRemoveOnTrackingChanged\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBTrackingChangeHandler\fP functionToStopCalling)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.ti -1c
.RI "void \fBAddOnValidPoseChanged\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBValidPoseChangeHandler\fP functionToCall)"
.br
.RI "Fires an event when the device now has a valid pose or no longer has a valid pose "
.ti -1c
.RI "void \fBRemoveOnValidPoseChanged\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBValidPoseChangeHandler\fP functionToStopCalling)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.ti -1c
.RI "void \fBAddOnActiveChangeListener\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBActiveChangeHandler\fP functionToCall)"
.br
.RI "Executes a function when this action's bound state changes "
.ti -1c
.RI "void \fBRemoveOnActiveChangeListener\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBActiveChangeHandler\fP functionToStopCalling)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.ti -1c
.RI "void \fBAddOnChangeListener\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBChangeHandler\fP functionToCall)"
.br
.RI "Executes a function when the state of this action (with the specified inputSource) changes "
.ti -1c
.RI "void \fBRemoveOnChangeListener\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBChangeHandler\fP functionToStopCalling)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.ti -1c
.RI "void \fBAddOnUpdateListener\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBUpdateHandler\fP functionToCall)"
.br
.RI "Executes a function when the state of this action (with the specified inputSource) is updated\&. "
.ti -1c
.RI "void \fBRemoveOnUpdateListener\fP (\fBSteamVR_Input_Sources\fP inputSource, \fBUpdateHandler\fP functionToStopCalling)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetTrackingUniverseOrigin\fP (\fBETrackingUniverseOrigin\fP newOrigin)"
.br
.RI "Sets all pose and skeleton actions to use the specified universe origin\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBActiveChangeHandler\fP \fBonActiveChange\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the active state (ActionSet active and binding active) changes "
.ti -1c
.RI "\fBActiveChangeHandler\fP \fBonActiveBindingChange\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the active state of the binding changes "
.ti -1c
.RI "\fBChangeHandler\fP \fBonChange\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the orientation of the pose changes more than the changeTolerance "
.ti -1c
.RI "\fBUpdateHandler\fP \fBonUpdate\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the action is updated "
.ti -1c
.RI "\fBTrackingChangeHandler\fP \fBonTrackingChanged\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the state of the tracking has changed "
.ti -1c
.RI "\fBValidPoseChangeHandler\fP \fBonValidPoseChanged\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the validity of the pose has changed "
.ti -1c
.RI "\fBDeviceConnectedChangeHandler\fP \fBonDeviceConnectedChanged\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the device bound to this pose is connected or disconnected "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Pose actions represent a position, rotation, and velocities inside the tracked space\&. \fBSteamVR\fP keeps a log of past poses so you can retrieve old poses with GetPoseAtTimeOffset or GetVelocitiesAtTimeOffset\&. You can also pass in times in the future to these methods for \fBSteamVR\fP's best prediction of where the pose will be at that time\&. 


.PP
Definition at line 18 of file SteamVR_Action_Pose\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "delegate void Valve\&.VR\&.SteamVR_Action_Pose\&.ActiveChangeHandler (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool active)"

.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.AddOnActiveChangeListener (\fBSteamVR_Input_Sources\fP inputSource, \fBActiveChangeHandler\fP functionToCall)"

.PP
Executes a function when this action's bound state changes 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 108 of file SteamVR_Action_Pose\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.AddOnChangeListener (\fBSteamVR_Input_Sources\fP inputSource, \fBChangeHandler\fP functionToCall)"

.PP
Executes a function when the state of this action (with the specified inputSource) changes 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToCall\fP A local function that receives the boolean action who's state has changed, the corresponding input source, and the new value
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 124 of file SteamVR_Action_Pose\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.AddOnDeviceConnectedChanged (\fBSteamVR_Input_Sources\fP inputSource, \fBDeviceConnectedChangeHandler\fP functionToCall)"

.PP
Fires an event when a device is connected or disconnected\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to add an event to\&. Any if the action is not device specific\&.
.br
\fIfunctionToCall\fP The method you would like to be called when a device is connected\&. Should take a \fBSteamVR_Action_Pose\fP as a param
.RE
.PP

.PP
Definition at line 58 of file SteamVR_Action_Pose\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.AddOnTrackingChanged (\fBSteamVR_Input_Sources\fP inputSource, \fBTrackingChangeHandler\fP functionToCall)"

.PP
Fires an event when the tracking of the device has changed 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to add an event to\&. Any if the action is not device specific\&.
.br
\fIfunctionToCall\fP The method you would like to be called when tracking has changed\&. Should take a \fBSteamVR_Action_Pose\fP as a param
.RE
.PP

.PP
Definition at line 75 of file SteamVR_Action_Pose\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.AddOnUpdateListener (\fBSteamVR_Input_Sources\fP inputSource, \fBUpdateHandler\fP functionToCall)"

.PP
Executes a function when the state of this action (with the specified inputSource) is updated\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToCall\fP A local function that receives the boolean action who's state has changed, the corresponding input source, and the new value
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 140 of file SteamVR_Action_Pose\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.AddOnValidPoseChanged (\fBSteamVR_Input_Sources\fP inputSource, \fBValidPoseChangeHandler\fP functionToCall)"

.PP
Fires an event when the device now has a valid pose or no longer has a valid pose 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to add an event to\&. Any if the action is not device specific\&.
.br
\fIfunctionToCall\fP The method you would like to be called when the pose has become valid or invalid\&. Should take a \fBSteamVR_Action_Pose\fP as a param
.RE
.PP

.PP
Definition at line 92 of file SteamVR_Action_Pose\&.cs\&.
.SS "delegate void Valve\&.VR\&.SteamVR_Action_Pose\&.ChangeHandler (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource)"

.SS "delegate void Valve\&.VR\&.SteamVR_Action_Pose\&.DeviceConnectedChangeHandler (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool deviceConnected)"

.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.RemoveOnActiveChangeListener (\fBSteamVR_Input_Sources\fP inputSource, \fBActiveChangeHandler\fP functionToStopCalling)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive update events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 116 of file SteamVR_Action_Pose\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.RemoveOnChangeListener (\fBSteamVR_Input_Sources\fP inputSource, \fBChangeHandler\fP functionToStopCalling)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive on change events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 132 of file SteamVR_Action_Pose\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.RemoveOnDeviceConnectedChanged (\fBSteamVR_Input_Sources\fP inputSource, \fBDeviceConnectedChangeHandler\fP functionToStopCalling)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to remove an event from\&. Any if the action is not device specific\&.
.br
\fIfunctionToStopCalling\fP The method you would like to stop calling when a device is connected\&. Should take a \fBSteamVR_Action_Pose\fP as a param
.RE
.PP

.PP
Definition at line 66 of file SteamVR_Action_Pose\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.RemoveOnTrackingChanged (\fBSteamVR_Input_Sources\fP inputSource, \fBTrackingChangeHandler\fP functionToStopCalling)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to remove an event from\&. Any if the action is not device specific\&.
.br
\fIfunctionToStopCalling\fP The method you would like to stop calling when tracking has changed\&. Should take a \fBSteamVR_Action_Pose\fP as a param
.RE
.PP

.PP
Definition at line 83 of file SteamVR_Action_Pose\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.RemoveOnUpdateListener (\fBSteamVR_Input_Sources\fP inputSource, \fBUpdateHandler\fP functionToStopCalling)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive update events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 148 of file SteamVR_Action_Pose\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Pose\&.RemoveOnValidPoseChanged (\fBSteamVR_Input_Sources\fP inputSource, \fBValidPoseChangeHandler\fP functionToStopCalling)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to remove an event from\&. Any if the action is not device specific\&.
.br
\fIfunctionToStopCalling\fP The method you would like to stop calling when the pose has become valid or invalid\&. Should take a \fBSteamVR_Action_Pose\fP as a param
.RE
.PP

.PP
Definition at line 100 of file SteamVR_Action_Pose\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Action_Pose\&.SetTrackingUniverseOrigin (\fBETrackingUniverseOrigin\fP newOrigin)\fC [static]\fP"

.PP
Sets all pose and skeleton actions to use the specified universe origin\&. 
.PP
Definition at line 163 of file SteamVR_Action_Pose\&.cs\&.
.SS "delegate void Valve\&.VR\&.SteamVR_Action_Pose\&.TrackingChangeHandler (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, \fBETrackingResult\fP trackingState)"

.SS "delegate void Valve\&.VR\&.SteamVR_Action_Pose\&.UpdateHandler (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource)"

.SS "delegate void Valve\&.VR\&.SteamVR_Action_Pose\&.ValidPoseChangeHandler (\fBSteamVR_Action_Pose\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool validPose)"

.SH "Property Documentation"
.PP 
.SS "\fBActiveChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Pose\&.onActiveBindingChange\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the active state of the binding changes 
.PP
Definition at line 33 of file SteamVR_Action_Pose\&.cs\&.
.SS "\fBActiveChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Pose\&.onActiveChange\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the active state (ActionSet active and binding active) changes 
.PP
Definition at line 29 of file SteamVR_Action_Pose\&.cs\&.
.SS "\fBChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Pose\&.onChange\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the orientation of the pose changes more than the changeTolerance 
.PP
Definition at line 37 of file SteamVR_Action_Pose\&.cs\&.
.SS "\fBDeviceConnectedChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Pose\&.onDeviceConnectedChanged\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the device bound to this pose is connected or disconnected 
.PP
Definition at line 53 of file SteamVR_Action_Pose\&.cs\&.
.SS "\fBTrackingChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Pose\&.onTrackingChanged\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the state of the tracking has changed 
.PP
Definition at line 45 of file SteamVR_Action_Pose\&.cs\&.
.SS "\fBUpdateHandler\fP Valve\&.VR\&.SteamVR_Action_Pose\&.onUpdate\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the action is updated 
.PP
Definition at line 41 of file SteamVR_Action_Pose\&.cs\&.
.SS "\fBValidPoseChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Pose\&.onValidPoseChanged\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the validity of the pose has changed 
.PP
Definition at line 49 of file SteamVR_Action_Pose\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
