.TH "Valve.VR.SteamVR_Input" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBPosesUpdatedHandler\fP (bool skipSendingEvents)"
.br
.ti -1c
.RI "delegate void \fBSkeletonsUpdatedHandler\fP (bool skipSendingEvents)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBForcePreinitialize\fP ()"
.br
.ti -1c
.RI "static void \fBInitialize\fP (bool force=false)"
.br
.RI "Get all the handles for actions and action sets\&. Initialize our dictionaries of action / action set names\&. Setup the tracking space universe origin "
.ti -1c
.RI "static void \fBPreinitializeFinishActionSets\fP ()"
.br
.ti -1c
.RI "static void \fBPreinitializeActionSetDictionaries\fP ()"
.br
.ti -1c
.RI "static void \fBPreinitializeActionDictionaries\fP ()"
.br
.ti -1c
.RI "static void \fBUpdate\fP ()"
.br
.RI "Gets called by \fBSteamVR_Behaviour\fP every Update and updates actions if the steamvr settings are configured to update then\&. "
.ti -1c
.RI "static void \fBLateUpdate\fP ()"
.br
.RI "Gets called by \fBSteamVR_Behaviour\fP every LateUpdate and updates actions if the steamvr settings are configured to update then\&. Also updates skeletons regardless of settings are configured to so we can account for animations on the skeletons\&. "
.ti -1c
.RI "static void \fBFixedUpdate\fP ()"
.br
.RI "Gets called by \fBSteamVR_Behaviour\fP every FixedUpdate and updates actions if the steamvr settings are configured to update then\&. "
.ti -1c
.RI "static void \fBOnPreCull\fP ()"
.br
.RI "Gets called by \fBSteamVR_Behaviour\fP every OnPreCull and updates actions if the steamvr settings are configured to update then\&. "
.ti -1c
.RI "static void \fBUpdateVisualActions\fP (bool skipStateAndEventUpdates=false)"
.br
.RI "Updates the states of all the visual actions (pose / skeleton) "
.ti -1c
.RI "static void \fBUpdatePoseActions\fP (bool skipSendingEvents=false)"
.br
.RI "Updates the states of all the pose actions "
.ti -1c
.RI "static void \fBUpdateSkeletonActions\fP (bool skipSendingEvents=false)"
.br
.RI "Updates the states of all the skeleton actions "
.ti -1c
.RI "static void \fBUpdateNonVisualActions\fP ()"
.br
.RI "Updates the states of all the non visual actions (boolean, single, vector2, vector3) "
.ti -1c
.RI "static T \fBGetActionDataFromPath< T >\fP (string path, bool caseSensitive=false)"
.br
.RI "Get an action's action data by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_ActionSet_Data\fP \fBGetActionSetDataFromPath\fP (string path, bool caseSensitive=false)"
.br
.RI "Get an action set's data by the full path to that action\&. Action set paths are in the format /actions/[actionSet] "
.ti -1c
.RI "static T \fBGetActionFromPath< T >\fP (string path, bool caseSensitive=false, bool returnNulls=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action\fP \fBGetBaseActionFromPath\fP (string path, bool caseSensitive=false)"
.br
.ti -1c
.RI "static bool \fBHasActionPath\fP (string path, bool caseSensitive=false)"
.br
.ti -1c
.RI "static bool \fBHasAction\fP (string actionName, bool caseSensitive=false)"
.br
.ti -1c
.RI "static bool \fBHasAction\fP (string actionSetName, string actionName, bool caseSensitive=false)"
.br
.ti -1c
.RI "static \fBSteamVR_Action_Boolean\fP \fBGetBooleanActionFromPath\fP (string path, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Single\fP \fBGetSingleActionFromPath\fP (string path, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Vector2\fP \fBGetVector2ActionFromPath\fP (string path, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Vector3\fP \fBGetVector3ActionFromPath\fP (string path, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Vibration\fP \fBGetVibrationActionFromPath\fP (string path, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Pose\fP \fBGetPoseActionFromPath\fP (string path, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Skeleton\fP \fBGetSkeletonActionFromPath\fP (string path, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static T \fBGetAction< T >\fP (string actionSetName, string actionName, bool caseSensitive=false, bool returnNulls=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action\fP \fBGetBaseAction\fP (string actionSetName, string actionName, bool caseSensitive=false)"
.br
.ti -1c
.RI "static T \fBGetAction< T >\fP (string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Boolean\fP \fBGetBooleanAction\fP (string actionSetName, string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Boolean\fP \fBGetBooleanAction\fP (string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Single\fP \fBGetSingleAction\fP (string actionSetName, string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Single\fP \fBGetSingleAction\fP (string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Vector2\fP \fBGetVector2Action\fP (string actionSetName, string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Vector2\fP \fBGetVector2Action\fP (string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Vector3\fP \fBGetVector3Action\fP (string actionSetName, string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Vector3\fP \fBGetVector3Action\fP (string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Pose\fP \fBGetPoseAction\fP (string actionSetName, string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Pose\fP \fBGetPoseAction\fP (string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Skeleton\fP \fBGetSkeletonAction\fP (string actionSetName, string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Skeleton\fP \fBGetSkeletonAction\fP (string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Vibration\fP \fBGetVibrationAction\fP (string actionSetName, string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static \fBSteamVR_Action_Vibration\fP \fBGetVibrationAction\fP (string actionName, bool caseSensitive=false)"
.br
.RI "Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] "
.ti -1c
.RI "static T \fBGetActionSet< T >\fP (string actionSetName, bool caseSensitive=false, bool returnNulls=false)"
.br
.RI "Get an action set by the full path to that action set\&. Action set paths are in the format /actions/[actionSet] "
.ti -1c
.RI "static \fBSteamVR_ActionSet\fP \fBGetActionSet\fP (string actionSetName, bool caseSensitive=false, bool returnsNulls=false)"
.br
.RI "Get an action set by the full path to that action set\&. Action set paths are in the format /actions/[actionSet] "
.ti -1c
.RI "static T \fBGetActionSetFromPath< T >\fP (string path, bool caseSensitive=false, bool returnsNulls=false)"
.br
.RI "Get an action set by the full path to that action set\&. Action set paths are in the format /actions/[actionSet] "
.ti -1c
.RI "static \fBSteamVR_ActionSet\fP \fBGetActionSetFromPath\fP (string path, bool caseSensitive=false)"
.br
.RI "Get an action set by the full path to that action set\&. Action set paths are in the format /actions/[actionSet] "
.ti -1c
.RI "static bool \fBGetState\fP (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the state of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results) "
.ti -1c
.RI "static bool \fBGetState\fP (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the state of an action by the action name and input source\&. Optionally case sensitive (for faster results) "
.ti -1c
.RI "static bool \fBGetStateDown\fP (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the state down of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results) "
.ti -1c
.RI "static bool \fBGetStateDown\fP (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the state down of an action by the action name and input source\&. Optionally case sensitive (for faster results) "
.ti -1c
.RI "static bool \fBGetStateUp\fP (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the state up of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results) "
.ti -1c
.RI "static bool \fBGetStateUp\fP (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the state up of an action by the action name and input source\&. Optionally case sensitive (for faster results) "
.ti -1c
.RI "static float \fBGetFloat\fP (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the float value of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results)\&. (same as GetSingle) "
.ti -1c
.RI "static float \fBGetFloat\fP (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the float value of an action by the action name and input source\&. Optionally case sensitive (for faster results)\&. (same as GetSingle) "
.ti -1c
.RI "static float \fBGetSingle\fP (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the float value of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results)\&. (same as GetFloat) "
.ti -1c
.RI "static float \fBGetSingle\fP (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the float value of an action by the action name and input source\&. Optionally case sensitive (for faster results)\&. (same as GetFloat) "
.ti -1c
.RI "static Vector2 \fBGetVector2\fP (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the Vector2 value of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results) "
.ti -1c
.RI "static Vector2 \fBGetVector2\fP (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the Vector2 value of an action by the action name and input source\&. Optionally case sensitive (for faster results) "
.ti -1c
.RI "static Vector3 \fBGetVector3\fP (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the Vector3 value of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results) "
.ti -1c
.RI "static Vector3 \fBGetVector3\fP (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive=false)"
.br
.RI "Get the Vector3 value of an action by the action name and input source\&. Optionally case sensitive (for faster results) "
.ti -1c
.RI "static \fBSteamVR_ActionSet\fP [] \fBGetActionSets\fP ()"
.br
.RI "Returns all of the action sets\&. If we're in the editor, doesn't rely on the actionSets field being filled\&. "
.ti -1c
.RI "static T [] \fBGetActions< T >\fP ()"
.br
.RI "Returns all of the actions of the specified type\&. If we're in the editor, doesn't rely on the arrays being filled\&. "
.ti -1c
.RI "static string \fBGetLocalizedName\fP (ulong originHandle, params \fBEVRInputStringBits\fP[] localizedParts)"
.br
.RI "Gets the localized name of the device that the action corresponds to\&. "
.ti -1c
.RI "static void \fBIdentifyActionsFile\fP (bool showLogs=true)"
.br
.RI "Tell \fBSteamVR\fP that we're using the actions file at the path defined in \fBSteamVR_Settings\fP\&. "
.ti -1c
.RI "static bool \fBHasFileInMemoryBeenModified\fP ()"
.br
.RI "Does the actions file in memory differ from the one on disk as determined by a md5 hash "
.ti -1c
.RI "static bool \fBCreateEmptyActionsFile\fP (bool completelyEmpty=false)"
.br
.ti -1c
.RI "static bool \fBDoesActionsFileExist\fP ()"
.br
.ti -1c
.RI "static bool \fBInitializeFile\fP (bool force=false, bool showErrors=true)"
.br
.RI "Load from disk and deserialize the actions file "
.ti -1c
.RI "static bool \fBDeleteManifestAndBindings\fP ()"
.br
.RI "Deletes the action manifest file and all the default bindings it had listed in the default bindings section "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBdefaultInputGameObjectName\fP = '[SteamVR Input]'"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBactionsFilePath\fP"
.br
.ti -1c
.RI "static bool \fBfileInitialized\fP = false"
.br
.RI "True if the actions file has been initialized "
.ti -1c
.RI "static bool \fBinitialized\fP = false"
.br
.RI "True if the steamvr input system initialization process has completed successfully "
.ti -1c
.RI "static bool \fBpreInitialized\fP = false"
.br
.RI "True if the preinitialization process (setting up dictionaries, etc) has completed successfully "
.ti -1c
.RI "static \fBSteamVR_Input_ActionFile\fP \fBactionFile\fP"
.br
.RI "The serialized version of the actions file we're currently using (only used in editor) "
.ti -1c
.RI "static string \fBactionFileHash\fP"
.br
.RI "The hash of the current action file on disk "
.ti -1c
.RI "static \fBSteamVR_ActionSet\fP [] \fBactionSets\fP"
.br
.RI "An array of all action sets "
.ti -1c
.RI "static \fBSteamVR_Action\fP [] \fBactions\fP"
.br
.RI "An array of all actions (in all action sets) "
.ti -1c
.RI "static \fBISteamVR_Action_In\fP [] \fBactionsIn\fP"
.br
.RI "An array of all input actions "
.ti -1c
.RI "static \fBISteamVR_Action_Out\fP [] \fBactionsOut\fP"
.br
.RI "An array of all output actions (haptic) "
.ti -1c
.RI "static \fBSteamVR_Action_Boolean\fP [] \fBactionsBoolean\fP"
.br
.RI "An array of all the boolean actions "
.ti -1c
.RI "static \fBSteamVR_Action_Single\fP [] \fBactionsSingle\fP"
.br
.RI "An array of all the single actions "
.ti -1c
.RI "static \fBSteamVR_Action_Vector2\fP [] \fBactionsVector2\fP"
.br
.RI "An array of all the vector2 actions "
.ti -1c
.RI "static \fBSteamVR_Action_Vector3\fP [] \fBactionsVector3\fP"
.br
.RI "An array of all the vector3 actions "
.ti -1c
.RI "static \fBSteamVR_Action_Pose\fP [] \fBactionsPose\fP"
.br
.RI "An array of all the pose actions "
.ti -1c
.RI "static \fBSteamVR_Action_Skeleton\fP [] \fBactionsSkeleton\fP"
.br
.RI "An array of all the skeleton actions "
.ti -1c
.RI "static \fBSteamVR_Action_Vibration\fP [] \fBactionsVibration\fP"
.br
.RI "An array of all the vibration (haptic) actions "
.ti -1c
.RI "static \fBISteamVR_Action_In\fP [] \fBactionsNonPoseNonSkeletonIn\fP"
.br
.RI "An array of all the input actions that are not pose or skeleton actions (boolean, single, vector2, vector3) "
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBHasActionSet\fP (string name, bool caseSensitive=false)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static bool \fBinitializing\fP = false"
.br
.ti -1c
.RI "static int \fBstartupFrame\fP = 0"
.br
.ti -1c
.RI "static Dictionary< string, \fBSteamVR_ActionSet\fP > \fBactionSetsByPath\fP = new Dictionary<string, \fBSteamVR_ActionSet\fP>()"
.br
.ti -1c
.RI "static Dictionary< string, \fBSteamVR_ActionSet\fP > \fBactionSetsByPathLowered\fP = new Dictionary<string, \fBSteamVR_ActionSet\fP>()"
.br
.ti -1c
.RI "static Dictionary< string, \fBSteamVR_Action\fP > \fBactionsByPath\fP = new Dictionary<string, \fBSteamVR_Action\fP>()"
.br
.ti -1c
.RI "static Dictionary< string, \fBSteamVR_Action\fP > \fBactionsByPathLowered\fP = new Dictionary<string, \fBSteamVR_Action\fP>()"
.br
.ti -1c
.RI "static Dictionary< string, \fBSteamVR_ActionSet\fP > \fBactionSetsByPathCache\fP = new Dictionary<string, \fBSteamVR_ActionSet\fP>()"
.br
.ti -1c
.RI "static Dictionary< string, \fBSteamVR_Action\fP > \fBactionsByPathCache\fP = new Dictionary<string, \fBSteamVR_Action\fP>()"
.br
.ti -1c
.RI "static Dictionary< string, \fBSteamVR_Action\fP > \fBactionsByNameCache\fP = new Dictionary<string, \fBSteamVR_Action\fP>()"
.br
.ti -1c
.RI "static Dictionary< string, \fBSteamVR_ActionSet\fP > \fBactionSetsByNameCache\fP = new Dictionary<string, \fBSteamVR_ActionSet\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBisStartupFrame\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static Action \fBonNonVisualActionsUpdated\fP"
.br
.RI "An event that fires when the non visual actions (everything except poses / skeletons) have been updated "
.ti -1c
.RI "static \fBPosesUpdatedHandler\fP \fBonPosesUpdated\fP"
.br
.RI "An event that fires when the pose actions have been updated "
.ti -1c
.RI "static \fBSkeletonsUpdatedHandler\fP \fBonSkeletonsUpdated\fP"
.br
.RI "An event that fires when the skeleton actions have been updated "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file SteamVR_Input\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.CreateEmptyActionsFile (bool completelyEmpty = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 1316 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.DeleteManifestAndBindings ()\fC [static]\fP"

.PP
Deletes the action manifest file and all the default bindings it had listed in the default bindings section 
.PP
\fBReturns:\fP
.RS 4
True if we deleted an action file, false if not\&.
.RE
.PP

.PP
Definition at line 1401 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.DoesActionsFileExist ()\fC [static]\fP"

.PP
Definition at line 1347 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.FixedUpdate ()\fC [static]\fP"

.PP
Gets called by \fBSteamVR_Behaviour\fP every FixedUpdate and updates actions if the steamvr settings are configured to update then\&. 
.PP
Definition at line 274 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.ForcePreinitialize ()\fC [static]\fP"

.PP
Definition at line 117 of file SteamVR_Input\&.cs\&.
.SS "static T Valve\&.VR\&.SteamVR_Input\&.GetAction< T > (string actionSetName, string actionName, bool caseSensitive = \fCfalse\fP, bool returnNulls = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.br
\fIreturnNulls\fP returns null if the action does not exist
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fISteamVR_Action\fP
.TP
\fIT\fP : \fInew()\fP
.PP
Definition at line 577 of file SteamVR_Input\&.cs\&.
.SS "static T Valve\&.VR\&.SteamVR_Input\&.GetAction< T > (string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fISteamVR_Action\fP
.TP
\fIT\fP : \fInew()\fP
.PP
Definition at line 660 of file SteamVR_Input\&.cs\&.
.SS "static T Valve\&.VR\&.SteamVR_Input\&.GetActionDataFromPath< T > (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action's action data by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fISteamVR_Action_Source_Map\fP
.PP
Definition at line 394 of file SteamVR_Input\&.cs\&.
.SS "static T Valve\&.VR\&.SteamVR_Input\&.GetActionFromPath< T > (string path, bool caseSensitive = \fCfalse\fP, bool returnNulls = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fISteamVR_Action\fP
.TP
\fIT\fP : \fInew()\fP
.PP
Definition at line 428 of file SteamVR_Input\&.cs\&.
.SS "static T [] Valve\&.VR\&.SteamVR_Input\&.GetActions< T > ()\fC [static]\fP"

.PP
Returns all of the actions of the specified type\&. If we're in the editor, doesn't rely on the arrays being filled\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of actions you want to get
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fISteamVR_Action\fP
.PP
Definition at line 1169 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_ActionSet\fP Valve\&.VR\&.SteamVR_Input\&.GetActionSet (string actionSetName, bool caseSensitive = \fCfalse\fP, bool returnsNulls = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action set by the full path to that action set\&. Action set paths are in the format /actions/[actionSet] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action set you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIactionSetName\fP The name to the action set you want
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 862 of file SteamVR_Input\&.cs\&.
.SS "static T \fBValve\&.VR\&.SteamVR_Input\&.GetActionSet\fP< T > (string actionSetName, bool caseSensitive = \fCfalse\fP, bool returnNulls = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action set by the full path to that action set\&. Action set paths are in the format /actions/[actionSet] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action set you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIactionSetName\fP The name to the action set you want
.br
\fIcaseSensitive\fP case sensitive searches are faster
.br
\fIreturnNulls\fP returns a null if the set does not exist
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fISteamVR_ActionSet\fP
.TP
\fIT\fP : \fInew()\fP
.PP
Definition at line 826 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_ActionSet_Data\fP Valve\&.VR\&.SteamVR_Input\&.GetActionSetDataFromPath (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action set's data by the full path to that action\&. Action set paths are in the format /actions/[actionSet] 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action set paths are in the format /actions/[actionSet])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 411 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_ActionSet\fP Valve\&.VR\&.SteamVR_Input\&.GetActionSetFromPath (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action set by the full path to that action set\&. Action set paths are in the format /actions/[actionSet] 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action set you want (Action paths are in the format /actions/[actionSet])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 937 of file SteamVR_Input\&.cs\&.
.SS "static T \fBValve\&.VR\&.SteamVR_Input\&.GetActionSetFromPath\fP< T > (string path, bool caseSensitive = \fCfalse\fP, bool returnsNulls = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action set by the full path to that action set\&. Action set paths are in the format /actions/[actionSet] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action set you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action set you want (Action paths are in the format /actions/[actionSet])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fISteamVR_ActionSet\fP
.TP
\fIT\fP : \fInew()\fP
.PP
Definition at line 879 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_ActionSet\fP [] Valve\&.VR\&.SteamVR_Input\&.GetActionSets ()\fC [static]\fP"

.PP
Returns all of the action sets\&. If we're in the editor, doesn't rely on the actionSets field being filled\&. 
.PP
Definition at line 1160 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action\fP Valve\&.VR\&.SteamVR_Input\&.GetBaseAction (string actionSetName, string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 589 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action\fP Valve\&.VR\&.SteamVR_Input\&.GetBaseActionFromPath (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 441 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Boolean\fP Valve\&.VR\&.SteamVR_Input\&.GetBooleanAction (string actionSetName, string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 671 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Boolean\fP Valve\&.VR\&.SteamVR_Input\&.GetBooleanAction (string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 682 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Boolean\fP Valve\&.VR\&.SteamVR_Input\&.GetBooleanActionFromPath (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 505 of file SteamVR_Input\&.cs\&.
.SS "static float Valve\&.VR\&.SteamVR_Input\&.GetFloat (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the float value of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results)\&. (same as GetSingle) 
.PP
\fBParameters:\fP
.RS 4
\fIactionSet\fP The name of the action set the action is contained in
.br
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP

.PP
Definition at line 1045 of file SteamVR_Input\&.cs\&.
.SS "static float Valve\&.VR\&.SteamVR_Input\&.GetFloat (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the float value of an action by the action name and input source\&. Optionally case sensitive (for faster results)\&. (same as GetSingle) 
.PP
\fBParameters:\fP
.RS 4
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP

.PP
Definition at line 1062 of file SteamVR_Input\&.cs\&.
.SS "static string Valve\&.VR\&.SteamVR_Input\&.GetLocalizedName (ulong originHandle, params \fBEVRInputStringBits\fP [] localizedParts)\fC [static]\fP"

.PP
Gets the localized name of the device that the action corresponds to\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP 
.br
\fIlocalizedParts\fP 
.PD 0

.IP "\(bu" 2
VRInputString_Hand - Which hand the origin is in\&. E\&.g\&. 'Left Hand' 
.IP "\(bu" 2
VRInputString_ControllerType - What kind of controller the user has in that hand\&.E\&.g\&. 'Vive Controller' 
.IP "\(bu" 2
VRInputString_InputSource - What part of that controller is the origin\&. E\&.g\&. 'Trackpad' 
.IP "\(bu" 2
VRInputString_All - All of the above\&. E\&.g\&. 'Left Hand Vive Controller Trackpad' 
.PP
.RE
.PP

.PP
Definition at line 1233 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Pose\fP Valve\&.VR\&.SteamVR_Input\&.GetPoseAction (string actionSetName, string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 759 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Pose\fP Valve\&.VR\&.SteamVR_Input\&.GetPoseAction (string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 770 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Pose\fP Valve\&.VR\&.SteamVR_Input\&.GetPoseActionFromPath (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 555 of file SteamVR_Input\&.cs\&.
.SS "static float Valve\&.VR\&.SteamVR_Input\&.GetSingle (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the float value of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results)\&. (same as GetFloat) 
.PP
\fBParameters:\fP
.RS 4
\fIactionSet\fP The name of the action set the action is contained in
.br
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP

.PP
Definition at line 1074 of file SteamVR_Input\&.cs\&.
.SS "static float Valve\&.VR\&.SteamVR_Input\&.GetSingle (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the float value of an action by the action name and input source\&. Optionally case sensitive (for faster results)\&. (same as GetFloat) 
.PP
\fBParameters:\fP
.RS 4
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP

.PP
Definition at line 1091 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Single\fP Valve\&.VR\&.SteamVR_Input\&.GetSingleAction (string actionSetName, string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 693 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Single\fP Valve\&.VR\&.SteamVR_Input\&.GetSingleAction (string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 704 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Single\fP Valve\&.VR\&.SteamVR_Input\&.GetSingleActionFromPath (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 515 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Skeleton\fP Valve\&.VR\&.SteamVR_Input\&.GetSkeletonAction (string actionSetName, string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 781 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Skeleton\fP Valve\&.VR\&.SteamVR_Input\&.GetSkeletonAction (string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 792 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Skeleton\fP Valve\&.VR\&.SteamVR_Input\&.GetSkeletonActionFromPath (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 565 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.GetState (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the state of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results) 
.PP
\fBParameters:\fP
.RS 4
\fIactionSet\fP The name of the action set the action is contained in
.br
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP

.PP
Definition at line 951 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.GetState (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the state of an action by the action name and input source\&. Optionally case sensitive (for faster results) 
.PP
\fBParameters:\fP
.RS 4
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP

.PP
Definition at line 968 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.GetStateDown (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the state down of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results) 
.PP
\fBParameters:\fP
.RS 4
\fIactionSet\fP The name of the action set the action is contained in
.br
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP
\fBReturns:\fP
.RS 4
True when the action was false last update and is now true\&. Returns false again afterwards\&.
.RE
.PP

.PP
Definition at line 981 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.GetStateDown (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the state down of an action by the action name and input source\&. Optionally case sensitive (for faster results) 
.PP
\fBParameters:\fP
.RS 4
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP
\fBReturns:\fP
.RS 4
True when the action was false last update and is now true\&. Returns false again afterwards\&.
.RE
.PP

.PP
Definition at line 999 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.GetStateUp (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the state up of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results) 
.PP
\fBParameters:\fP
.RS 4
\fIactionSet\fP The name of the action set the action is contained in
.br
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP
\fBReturns:\fP
.RS 4
True when the action was true last update and is now false\&. Returns false again afterwards\&.
.RE
.PP

.PP
Definition at line 1012 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.GetStateUp (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the state up of an action by the action name and input source\&. Optionally case sensitive (for faster results) 
.PP
\fBParameters:\fP
.RS 4
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP
\fBReturns:\fP
.RS 4
True when the action was true last update and is now false\&. Returns false again afterwards\&.
.RE
.PP

.PP
Definition at line 1031 of file SteamVR_Input\&.cs\&.
.SS "static Vector2 Valve\&.VR\&.SteamVR_Input\&.GetVector2 (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the Vector2 value of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results) 
.PP
\fBParameters:\fP
.RS 4
\fIactionSet\fP The name of the action set the action is contained in
.br
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP

.PP
Definition at line 1103 of file SteamVR_Input\&.cs\&.
.SS "static Vector2 Valve\&.VR\&.SteamVR_Input\&.GetVector2 (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the Vector2 value of an action by the action name and input source\&. Optionally case sensitive (for faster results) 
.PP
\fBParameters:\fP
.RS 4
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP

.PP
Definition at line 1120 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Vector2\fP Valve\&.VR\&.SteamVR_Input\&.GetVector2Action (string actionSetName, string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 715 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Vector2\fP Valve\&.VR\&.SteamVR_Input\&.GetVector2Action (string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 726 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Vector2\fP Valve\&.VR\&.SteamVR_Input\&.GetVector2ActionFromPath (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 525 of file SteamVR_Input\&.cs\&.
.SS "static Vector3 Valve\&.VR\&.SteamVR_Input\&.GetVector3 (string actionSet, string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the Vector3 value of an action by the action set name, action name, and input source\&. Optionally case sensitive (for faster results) 
.PP
\fBParameters:\fP
.RS 4
\fIactionSet\fP The name of the action set the action is contained in
.br
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP

.PP
Definition at line 1132 of file SteamVR_Input\&.cs\&.
.SS "static Vector3 Valve\&.VR\&.SteamVR_Input\&.GetVector3 (string action, \fBSteamVR_Input_Sources\fP inputSource, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get the Vector3 value of an action by the action name and input source\&. Optionally case sensitive (for faster results) 
.PP
\fBParameters:\fP
.RS 4
\fIaction\fP The name of the action to get the state of
.br
\fIinputSource\fP The input source to get the action state from
.br
\fIcaseSensitive\fP Whether or not the action set and action name searches should be case sensitive (case sensitive searches are faster)
.RE
.PP

.PP
Definition at line 1149 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Vector3\fP Valve\&.VR\&.SteamVR_Input\&.GetVector3Action (string actionSetName, string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 737 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Vector3\fP Valve\&.VR\&.SteamVR_Input\&.GetVector3Action (string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 748 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Vector3\fP Valve\&.VR\&.SteamVR_Input\&.GetVector3ActionFromPath (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 535 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Vibration\fP Valve\&.VR\&.SteamVR_Input\&.GetVibrationAction (string actionSetName, string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 803 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Vibration\fP Valve\&.VR\&.SteamVR_Input\&.GetVibrationAction (string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of action you're expecting to get back
.RE
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 814 of file SteamVR_Input\&.cs\&.
.SS "static \fBSteamVR_Action_Vibration\fP Valve\&.VR\&.SteamVR_Input\&.GetVibrationActionFromPath (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Get an action by the full path to that action\&. Action paths are in the format /actions/[actionSet]/[direction]/[actionName] 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The full path to the action you want (Action paths are in the format /actions/[actionSet]/[direction]/[actionName])
.br
\fIcaseSensitive\fP case sensitive searches are faster
.RE
.PP

.PP
Definition at line 545 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.HasAction (string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 488 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.HasAction (string actionSetName, string actionName, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 494 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.HasActionPath (string path, bool caseSensitive = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 482 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.HasActionSet (string name, bool caseSensitive = \fCfalse\fP)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 867 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.HasFileInMemoryBeenModified ()\fC [static]\fP"

.PP
Does the actions file in memory differ from the one on disk as determined by a md5 hash 
.PP
Definition at line 1289 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.IdentifyActionsFile (bool showLogs = \fCtrue\fP)\fC [static]\fP"

.PP
Tell \fBSteamVR\fP that we're using the actions file at the path defined in \fBSteamVR_Settings\fP\&. 
.PP
Definition at line 1248 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.Initialize (bool force = \fCfalse\fP)\fC [static]\fP"

.PP
Get all the handles for actions and action sets\&. Initialize our dictionaries of action / action set names\&. Setup the tracking space universe origin 
.PP
Definition at line 146 of file SteamVR_Input\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Input\&.InitializeFile (bool force = \fCfalse\fP, bool showErrors = \fCtrue\fP)\fC [static]\fP"

.PP
Load from disk and deserialize the actions file 
.PP
\fBParameters:\fP
.RS 4
\fIforce\fP Force a refresh of this file from disk
.RE
.PP

.PP
Definition at line 1361 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.LateUpdate ()\fC [static]\fP"

.PP
Gets called by \fBSteamVR_Behaviour\fP every LateUpdate and updates actions if the steamvr settings are configured to update then\&. Also updates skeletons regardless of settings are configured to so we can account for animations on the skeletons\&. 
.PP
Definition at line 251 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.OnPreCull ()\fC [static]\fP"

.PP
Gets called by \fBSteamVR_Behaviour\fP every OnPreCull and updates actions if the steamvr settings are configured to update then\&. 
.PP
Definition at line 291 of file SteamVR_Input\&.cs\&.
.SS "delegate void Valve\&.VR\&.SteamVR_Input\&.PosesUpdatedHandler (bool skipSendingEvents)"

.SS "static void Valve\&.VR\&.SteamVR_Input\&.PreinitializeActionDictionaries ()\fC [static]\fP"

.PP
Definition at line 217 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.PreinitializeActionSetDictionaries ()\fC [static]\fP"

.PP
Definition at line 203 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.PreinitializeFinishActionSets ()\fC [static]\fP"

.PP
Definition at line 194 of file SteamVR_Input\&.cs\&.
.SS "delegate void Valve\&.VR\&.SteamVR_Input\&.SkeletonsUpdatedHandler (bool skipSendingEvents)"

.SS "static void Valve\&.VR\&.SteamVR_Input\&.Update ()\fC [static]\fP"

.PP
Gets called by \fBSteamVR_Behaviour\fP every Update and updates actions if the steamvr settings are configured to update then\&. 
.PP
Definition at line 232 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.UpdateNonVisualActions ()\fC [static]\fP"

.PP
Updates the states of all the non visual actions (boolean, single, vector2, vector3) 
.PP
Definition at line 366 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.UpdatePoseActions (bool skipSendingEvents = \fCfalse\fP)\fC [static]\fP"

.PP
Updates the states of all the pose actions 
.PP
\fBParameters:\fP
.RS 4
\fIskipSendingEvents\fP Controls whether or not events are fired from this update call
.RE
.PP

.PP
Definition at line 326 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.UpdateSkeletonActions (bool skipSendingEvents = \fCfalse\fP)\fC [static]\fP"

.PP
Updates the states of all the skeleton actions 
.PP
\fBParameters:\fP
.RS 4
\fIskipSendingEvents\fP Controls whether or not events are fired from this update call
.RE
.PP

.PP
Definition at line 346 of file SteamVR_Input\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input\&.UpdateVisualActions (bool skipStateAndEventUpdates = \fCfalse\fP)\fC [static]\fP"

.PP
Updates the states of all the visual actions (pose / skeleton) 
.PP
\fBParameters:\fP
.RS 4
\fIskipStateAndEventUpdates\fP Controls whether or not events are fired from this update call
.RE
.PP

.PP
Definition at line 310 of file SteamVR_Input\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSteamVR_Input_ActionFile\fP Valve\&.VR\&.SteamVR_Input\&.actionFile\fC [static]\fP"

.PP
The serialized version of the actions file we're currently using (only used in editor) 
.PP
Definition at line 31 of file SteamVR_Input\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input\&.actionFileHash\fC [static]\fP"

.PP
The hash of the current action file on disk 
.PP
Definition at line 34 of file SteamVR_Input\&.cs\&.
.SS "\fBSteamVR_Action\fP [] Valve\&.VR\&.SteamVR_Input\&.actions\fC [static]\fP"

.PP
An array of all actions (in all action sets) 
.PP
Definition at line 63 of file SteamVR_Input\&.cs\&.
.SS "\fBSteamVR_Action_Boolean\fP [] Valve\&.VR\&.SteamVR_Input\&.actionsBoolean\fC [static]\fP"

.PP
An array of all the boolean actions 
.PP
Definition at line 72 of file SteamVR_Input\&.cs\&.
.SS "Dictionary<string, \fBSteamVR_Action\fP> Valve\&.VR\&.SteamVR_Input\&.actionsByNameCache = new Dictionary<string, \fBSteamVR_Action\fP>()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 103 of file SteamVR_Input\&.cs\&.
.SS "Dictionary<string, \fBSteamVR_Action\fP> Valve\&.VR\&.SteamVR_Input\&.actionsByPath = new Dictionary<string, \fBSteamVR_Action\fP>()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 97 of file SteamVR_Input\&.cs\&.
.SS "Dictionary<string, \fBSteamVR_Action\fP> Valve\&.VR\&.SteamVR_Input\&.actionsByPathCache = new Dictionary<string, \fBSteamVR_Action\fP>()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 101 of file SteamVR_Input\&.cs\&.
.SS "Dictionary<string, \fBSteamVR_Action\fP> Valve\&.VR\&.SteamVR_Input\&.actionsByPathLowered = new Dictionary<string, \fBSteamVR_Action\fP>()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 98 of file SteamVR_Input\&.cs\&.
.SS "\fBSteamVR_ActionSet\fP [] Valve\&.VR\&.SteamVR_Input\&.actionSets\fC [static]\fP"

.PP
An array of all action sets 
.PP
Definition at line 60 of file SteamVR_Input\&.cs\&.
.SS "Dictionary<string, \fBSteamVR_ActionSet\fP> Valve\&.VR\&.SteamVR_Input\&.actionSetsByNameCache = new Dictionary<string, \fBSteamVR_ActionSet\fP>()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 104 of file SteamVR_Input\&.cs\&.
.SS "Dictionary<string, \fBSteamVR_ActionSet\fP> Valve\&.VR\&.SteamVR_Input\&.actionSetsByPath = new Dictionary<string, \fBSteamVR_ActionSet\fP>()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 95 of file SteamVR_Input\&.cs\&.
.SS "Dictionary<string, \fBSteamVR_ActionSet\fP> Valve\&.VR\&.SteamVR_Input\&.actionSetsByPathCache = new Dictionary<string, \fBSteamVR_ActionSet\fP>()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 100 of file SteamVR_Input\&.cs\&.
.SS "Dictionary<string, \fBSteamVR_ActionSet\fP> Valve\&.VR\&.SteamVR_Input\&.actionSetsByPathLowered = new Dictionary<string, \fBSteamVR_ActionSet\fP>()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 96 of file SteamVR_Input\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input\&.actionsFilePath\fC [static]\fP"

.PP
Definition at line 19 of file SteamVR_Input\&.cs\&.
.SS "\fBISteamVR_Action_In\fP [] Valve\&.VR\&.SteamVR_Input\&.actionsIn\fC [static]\fP"

.PP
An array of all input actions 
.PP
Definition at line 66 of file SteamVR_Input\&.cs\&.
.SS "\fBISteamVR_Action_In\fP [] Valve\&.VR\&.SteamVR_Input\&.actionsNonPoseNonSkeletonIn\fC [static]\fP"

.PP
An array of all the input actions that are not pose or skeleton actions (boolean, single, vector2, vector3) 
.PP
Definition at line 93 of file SteamVR_Input\&.cs\&.
.SS "\fBISteamVR_Action_Out\fP [] Valve\&.VR\&.SteamVR_Input\&.actionsOut\fC [static]\fP"

.PP
An array of all output actions (haptic) 
.PP
Definition at line 69 of file SteamVR_Input\&.cs\&.
.SS "\fBSteamVR_Action_Pose\fP [] Valve\&.VR\&.SteamVR_Input\&.actionsPose\fC [static]\fP"

.PP
An array of all the pose actions 
.PP
Definition at line 84 of file SteamVR_Input\&.cs\&.
.SS "\fBSteamVR_Action_Single\fP [] Valve\&.VR\&.SteamVR_Input\&.actionsSingle\fC [static]\fP"

.PP
An array of all the single actions 
.PP
Definition at line 75 of file SteamVR_Input\&.cs\&.
.SS "\fBSteamVR_Action_Skeleton\fP [] Valve\&.VR\&.SteamVR_Input\&.actionsSkeleton\fC [static]\fP"

.PP
An array of all the skeleton actions 
.PP
Definition at line 87 of file SteamVR_Input\&.cs\&.
.SS "\fBSteamVR_Action_Vector2\fP [] Valve\&.VR\&.SteamVR_Input\&.actionsVector2\fC [static]\fP"

.PP
An array of all the vector2 actions 
.PP
Definition at line 78 of file SteamVR_Input\&.cs\&.
.SS "\fBSteamVR_Action_Vector3\fP [] Valve\&.VR\&.SteamVR_Input\&.actionsVector3\fC [static]\fP"

.PP
An array of all the vector3 actions 
.PP
Definition at line 81 of file SteamVR_Input\&.cs\&.
.SS "\fBSteamVR_Action_Vibration\fP [] Valve\&.VR\&.SteamVR_Input\&.actionsVibration\fC [static]\fP"

.PP
An array of all the vibration (haptic) actions 
.PP
Definition at line 90 of file SteamVR_Input\&.cs\&.
.SS "const string Valve\&.VR\&.SteamVR_Input\&.defaultInputGameObjectName = '[SteamVR Input]'"

.PP
Definition at line 17 of file SteamVR_Input\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Input\&.fileInitialized = false\fC [static]\fP"

.PP
True if the actions file has been initialized 
.PP
Definition at line 22 of file SteamVR_Input\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Input\&.initialized = false\fC [static]\fP"

.PP
True if the steamvr input system initialization process has completed successfully 
.PP
Definition at line 25 of file SteamVR_Input\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Input\&.initializing = false\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 47 of file SteamVR_Input\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Input\&.preInitialized = false\fC [static]\fP"

.PP
True if the preinitialization process (setting up dictionaries, etc) has completed successfully 
.PP
Definition at line 28 of file SteamVR_Input\&.cs\&.
.SS "int Valve\&.VR\&.SteamVR_Input\&.startupFrame = 0\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 49 of file SteamVR_Input\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_Input\&.isStartupFrame\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 51 of file SteamVR_Input\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "Action Valve\&.VR\&.SteamVR_Input\&.onNonVisualActionsUpdated\fC [static]\fP"

.PP
An event that fires when the non visual actions (everything except poses / skeletons) have been updated 
.PP
Definition at line 37 of file SteamVR_Input\&.cs\&.
.SS "\fBPosesUpdatedHandler\fP Valve\&.VR\&.SteamVR_Input\&.onPosesUpdated\fC [static]\fP"

.PP
An event that fires when the pose actions have been updated 
.PP
Definition at line 40 of file SteamVR_Input\&.cs\&.
.SS "\fBSkeletonsUpdatedHandler\fP Valve\&.VR\&.SteamVR_Input\&.onSkeletonsUpdated\fC [static]\fP"

.PP
An event that fires when the skeleton actions have been updated 
.PP
Definition at line 44 of file SteamVR_Input\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
