.TH "Valve.VR.InteractionSystem.TeleportArea" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.TeleportArea
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "override bool \fBShouldActivate\fP (Vector3 playerPosition)"
.br
.ti -1c
.RI "override bool \fBShouldMovePlayer\fP ()"
.br
.ti -1c
.RI "override void \fBHighlight\fP (bool highlight)"
.br
.ti -1c
.RI "override void \fBSetAlpha\fP (float tintAlpha, float alphaPercent)"
.br
.ti -1c
.RI "override void \fBUpdateVisuals\fP ()"
.br
.ti -1c
.RI "void \fBUpdateVisualsInEditor\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Bounds \fBmeshBounds\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file TeleportArea\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportArea\&.Awake ()"

.PP
Definition at line 29 of file TeleportArea\&.cs\&.
.SS "override void Valve\&.VR\&.InteractionSystem\&.TeleportArea\&.Highlight (bool highlight)\fC [virtual]\fP"

.PP
Implements \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.PP
Definition at line 63 of file TeleportArea\&.cs\&.
.SS "override void Valve\&.VR\&.InteractionSystem\&.TeleportArea\&.SetAlpha (float tintAlpha, float alphaPercent)\fC [virtual]\fP"

.PP
Implements \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.PP
Definition at line 82 of file TeleportArea\&.cs\&.
.SS "override bool Valve\&.VR\&.InteractionSystem\&.TeleportArea\&.ShouldActivate (Vector3 playerPosition)\fC [virtual]\fP"

.PP
Implements \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.PP
Definition at line 49 of file TeleportArea\&.cs\&.
.SS "override bool Valve\&.VR\&.InteractionSystem\&.TeleportArea\&.ShouldMovePlayer ()\fC [virtual]\fP"

.PP
Implements \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.PP
Definition at line 56 of file TeleportArea\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportArea\&.Start ()"

.PP
Definition at line 40 of file TeleportArea\&.cs\&.
.SS "override void Valve\&.VR\&.InteractionSystem\&.TeleportArea\&.UpdateVisuals ()\fC [virtual]\fP"

.PP
Implements \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.PP
Definition at line 91 of file TeleportArea\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportArea\&.UpdateVisualsInEditor ()"

.PP
Definition at line 105 of file TeleportArea\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Bounds Valve\&.VR\&.InteractionSystem\&.TeleportArea\&.meshBounds\fC [get]\fP"

.PP
Definition at line 18 of file TeleportArea\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
