.TH "Valve.VR.SteamVREnumEqualityComparer< TEnum >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVREnumEqualityComparer< TEnum >
.SH SYNOPSIS
.br
.PP
.PP
Inherits IEqualityComparer< TEnum >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBoxAvoidance\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBEquals\fP (TEnum firstEnum, TEnum secondEnum)"
.br
.ti -1c
.RI "int \fBGetHashCode\fP (TEnum firstEnum)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fITEnum\fP : \fIstruct\fP
.PP
Definition at line 9 of file SteamVR_EnumEqualityComparer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool \fBValve\&.VR\&.SteamVREnumEqualityComparer\fP< TEnum >\&.Equals (TEnum firstEnum, TEnum secondEnum)"

.PP
Definition at line 29 of file SteamVR_EnumEqualityComparer\&.cs\&.
.SS "int \fBValve\&.VR\&.SteamVREnumEqualityComparer\fP< TEnum >\&.GetHashCode (TEnum firstEnum)"

.PP
Definition at line 34 of file SteamVR_EnumEqualityComparer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
