.TH "Valve.VR.IVRNotifications" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.IVRNotifications
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal delegate \fBEVRNotificationError\fP \fB_CreateNotification\fP (ulong ulOverlayHandle, ulong ulUserValue, \fBEVRNotificationType\fP type, string pchText, \fBEVRNotificationStyle\fP style, ref \fBNotificationBitmap_t\fP pImage, ref uint pNotificationId)"
.br
.ti -1c
.RI "internal delegate \fBEVRNotificationError\fP \fB_RemoveNotification\fP (uint notificationId)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internal \fB_CreateNotification\fP \fBCreateNotification\fP"
.br
.ti -1c
.RI "internal \fB_RemoveNotification\fP \fBRemoveNotification\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1386 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "internal delegate \fBEVRNotificationError\fP Valve\&.VR\&.IVRNotifications\&._CreateNotification (ulong ulOverlayHandle, ulong ulUserValue, \fBEVRNotificationType\fP type, string pchText, \fBEVRNotificationStyle\fP style, ref \fBNotificationBitmap_t\fP pImage, ref uint pNotificationId)"

.SS "internal delegate \fBEVRNotificationError\fP Valve\&.VR\&.IVRNotifications\&._RemoveNotification (uint notificationId)"

.SH "Member Data Documentation"
.PP 
.SS "internal \fB_CreateNotification\fP Valve\&.VR\&.IVRNotifications\&.CreateNotification"

.PP
Definition at line 1391 of file openvr_api\&.cs\&.
.SS "internal \fB_RemoveNotification\fP Valve\&.VR\&.IVRNotifications\&.RemoveNotification"

.PP
Definition at line 1396 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
