.TH "Valve.VR.AppOverrideKeys_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.AppOverrideKeys_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IntPtr \fBpchKey\fP"
.br
.ti -1c
.RI "IntPtr \fBpchValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5352 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "IntPtr Valve\&.VR\&.AppOverrideKeys_t\&.pchKey"

.PP
Definition at line 5354 of file openvr_api\&.cs\&.
.SS "IntPtr Valve\&.VR\&.AppOverrideKeys_t\&.pchValue"

.PP
Definition at line 5355 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
