.TH "Valve.VR.InteractionSystem.Sample.RenderModelChangerUI" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Sample.RenderModelChangerUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.InteractionSystem\&.UIElement\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBleftPrefab\fP"
.br
.ti -1c
.RI "GameObject \fBrightPrefab\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.ti -1c
.RI "override void \fBOnButtonClick\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSkeletonUIOptions\fP \fBui\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file RenderModelChangerUI\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Valve\&.VR\&.InteractionSystem\&.Sample\&.RenderModelChangerUI\&.Awake ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBValve\&.VR\&.InteractionSystem\&.UIElement\fP\&.
.PP
Definition at line 15 of file RenderModelChangerUI\&.cs\&.
.SS "override void Valve\&.VR\&.InteractionSystem\&.Sample\&.RenderModelChangerUI\&.OnButtonClick ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBValve\&.VR\&.InteractionSystem\&.UIElement\fP\&.
.PP
Definition at line 22 of file RenderModelChangerUI\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.Sample\&.RenderModelChangerUI\&.leftPrefab"

.PP
Definition at line 10 of file RenderModelChangerUI\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.Sample\&.RenderModelChangerUI\&.rightPrefab"

.PP
Definition at line 11 of file RenderModelChangerUI\&.cs\&.
.SS "\fBSkeletonUIOptions\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.RenderModelChangerUI\&.ui\fC [protected]\fP"

.PP
Definition at line 13 of file RenderModelChangerUI\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
