.TH "Valve.VR.SteamVR_Input_BindingFile_ActionList" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_BindingFile_ActionList
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBSteamVR_Input_BindingFile_Chord\fP > \fBchords\fP = new List<\fBSteamVR_Input_BindingFile_Chord\fP>()"
.br
.ti -1c
.RI "List< \fBSteamVR_Input_BindingFile_Pose\fP > \fBposes\fP = new List<\fBSteamVR_Input_BindingFile_Pose\fP>()"
.br
.ti -1c
.RI "List< \fBSteamVR_Input_BindingFile_Haptic\fP > \fBhaptics\fP = new List<\fBSteamVR_Input_BindingFile_Haptic\fP>()"
.br
.ti -1c
.RI "List< \fBSteamVR_Input_BindingFile_Source\fP > \fBsources\fP = new List<\fBSteamVR_Input_BindingFile_Source\fP>()"
.br
.ti -1c
.RI "List< \fBSteamVR_Input_BindingFile_Skeleton\fP > \fBskeleton\fP = new List<\fBSteamVR_Input_BindingFile_Skeleton\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file SteamVR_Input_BindingFile\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBSteamVR_Input_BindingFile_Chord\fP> Valve\&.VR\&.SteamVR_Input_BindingFile_ActionList\&.chords = new List<\fBSteamVR_Input_BindingFile_Chord\fP>()"

.PP
Definition at line 26 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "List<\fBSteamVR_Input_BindingFile_Haptic\fP> Valve\&.VR\&.SteamVR_Input_BindingFile_ActionList\&.haptics = new List<\fBSteamVR_Input_BindingFile_Haptic\fP>()"

.PP
Definition at line 28 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "List<\fBSteamVR_Input_BindingFile_Pose\fP> Valve\&.VR\&.SteamVR_Input_BindingFile_ActionList\&.poses = new List<\fBSteamVR_Input_BindingFile_Pose\fP>()"

.PP
Definition at line 27 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "List<\fBSteamVR_Input_BindingFile_Skeleton\fP> Valve\&.VR\&.SteamVR_Input_BindingFile_ActionList\&.skeleton = new List<\fBSteamVR_Input_BindingFile_Skeleton\fP>()"

.PP
Definition at line 30 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "List<\fBSteamVR_Input_BindingFile_Source\fP> Valve\&.VR\&.SteamVR_Input_BindingFile_ActionList\&.sources = new List<\fBSteamVR_Input_BindingFile_Source\fP>()"

.PP
Definition at line 29 of file SteamVR_Input_BindingFile\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
