.TH "Valve.VR.InteractionSystem.LinearDrive" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.LinearDrive
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBstartPosition\fP"
.br
.ti -1c
.RI "Transform \fBendPosition\fP"
.br
.ti -1c
.RI "\fBLinearMapping\fP \fBlinearMapping\fP"
.br
.ti -1c
.RI "bool \fBrepositionGameObject\fP = true"
.br
.ti -1c
.RI "bool \fBmaintainMomemntum\fP = true"
.br
.ti -1c
.RI "float \fBmomemtumDampenRate\fP = 5\&.0f"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.ti -1c
.RI "virtual void \fBStart\fP ()"
.br
.ti -1c
.RI "virtual void \fBHandHoverUpdate\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "virtual void \fBHandAttachedUpdate\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "virtual void \fBOnDetachedFromHand\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "void \fBCalculateMappingChangeRate\fP ()"
.br
.ti -1c
.RI "void \fBUpdateLinearMapping\fP (Transform updateTransform)"
.br
.ti -1c
.RI "float \fBCalculateLinearMapping\fP (Transform updateTransform)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBHand\&.AttachmentFlags\fP \fBattachmentFlags\fP = \fBHand\&.AttachmentFlags\&.DetachFromOtherHand\fP"
.br
.ti -1c
.RI "float \fBinitialMappingOffset\fP"
.br
.ti -1c
.RI "int \fBnumMappingChangeSamples\fP = 5"
.br
.ti -1c
.RI "float [] \fBmappingChangeSamples\fP"
.br
.ti -1c
.RI "float \fBprevMapping\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBmappingChangeRate\fP"
.br
.ti -1c
.RI "int \fBsampleCount\fP = 0"
.br
.ti -1c
.RI "\fBInteractable\fP \fBinteractable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file LinearDrive\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.Awake ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 35 of file LinearDrive\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.CalculateLinearMapping (Transform updateTransform)\fC [protected]\fP"

.PP
Definition at line 120 of file LinearDrive\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.CalculateMappingChangeRate ()\fC [protected]\fP"

.PP
Definition at line 91 of file LinearDrive\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.HandAttachedUpdate (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 75 of file LinearDrive\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.HandHoverUpdate (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 61 of file LinearDrive\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.OnDetachedFromHand (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 85 of file LinearDrive\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.Start ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 41 of file LinearDrive\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.Update ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 132 of file LinearDrive\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.UpdateLinearMapping (Transform updateTransform)\fC [protected]\fP"

.PP
Definition at line 106 of file LinearDrive\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHand\&.AttachmentFlags\fP Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.attachmentFlags = \fBHand\&.AttachmentFlags\&.DetachFromOtherHand\fP\fC [protected]\fP"

.PP
Definition at line 23 of file LinearDrive\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.endPosition"

.PP
Definition at line 17 of file LinearDrive\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.initialMappingOffset\fC [protected]\fP"

.PP
Definition at line 25 of file LinearDrive\&.cs\&.
.SS "\fBInteractable\fP Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.interactable\fC [protected]\fP"

.PP
Definition at line 32 of file LinearDrive\&.cs\&.
.SS "\fBLinearMapping\fP Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.linearMapping"

.PP
Definition at line 18 of file LinearDrive\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.maintainMomemntum = true"

.PP
Definition at line 20 of file LinearDrive\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.mappingChangeRate\fC [protected]\fP"

.PP
Definition at line 29 of file LinearDrive\&.cs\&.
.SS "float [] Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.mappingChangeSamples\fC [protected]\fP"

.PP
Definition at line 27 of file LinearDrive\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.momemtumDampenRate = 5\&.0f"

.PP
Definition at line 21 of file LinearDrive\&.cs\&.
.SS "int Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.numMappingChangeSamples = 5\fC [protected]\fP"

.PP
Definition at line 26 of file LinearDrive\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.prevMapping = 0\&.0f\fC [protected]\fP"

.PP
Definition at line 28 of file LinearDrive\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.repositionGameObject = true"

.PP
Definition at line 19 of file LinearDrive\&.cs\&.
.SS "int Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.sampleCount = 0\fC [protected]\fP"

.PP
Definition at line 30 of file LinearDrive\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.LinearDrive\&.startPosition"

.PP
Definition at line 16 of file LinearDrive\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
