.TH "Valve.VR.SteamVR_Input_ActionManifest_Manager" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_ActionManifest_Manager
.SH SYNOPSIS
.br
.PP
.PP
Inherits AssetPostprocessor\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCreatePartial\fP (string name, int version, bool overwriteOld, bool removeUnused)"
.br
.ti -1c
.RI "static void \fBCleanBindings\fP (bool verbose=false)"
.br
.ti -1c
.RI "static Dictionary< string, List< \fBSteamVR_PartialInputBindings\fP > > \fBScanForPartials\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBpartialManifestFilename\fP = 'steamvr_partial_manifest\&.json'"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static string \fBFindLanguageInDictionary\fP (Dictionary< string, string > dictionary)"
.br
.ti -1c
.RI "static int \fBImportLocalization\fP (\fBSteamVR_Input_ActionFile\fP currentActionsFile, \fBSteamVR_Input_ActionFile\fP newActionsFile, \fBSteamVR_PartialInputBindings\fP partialBinding)"
.br
.ti -1c
.RI "static int \fBImportActionSets\fP (\fBSteamVR_Input_ActionFile\fP currentActionsFile, \fBSteamVR_Input_ActionFile\fP newActionsFile)"
.br
.ti -1c
.RI "static int \fBImportActions\fP (\fBSteamVR_Input_ActionFile\fP currentActionsFile, \fBSteamVR_Input_ActionFile\fP newActionsFile)"
.br
.ti -1c
.RI "static \fBSteamVR_Input_BindingFile\fP \fBGetBindingFileObject\fP (string path)"
.br
.ti -1c
.RI "static void \fBWriteBindingFileObject\fP (\fBSteamVR_Input_BindingFile\fP currentBindingFile, string currentBindingPath)"
.br
.ti -1c
.RI "static void \fBImportBindings\fP (\fBSteamVR_Input_ActionFile\fP currentActionsFile, \fBSteamVR_Input_ActionFile\fP newActionsFile, string directory)"
.br
.ti -1c
.RI "static void \fBImportPartialBinding\fP (\fBSteamVR_PartialInputBindings\fP partialBinding)"
.br
.ti -1c
.RI "static void \fBReplaceBinding\fP (\fBSteamVR_PartialInputBindings\fP partialBinding)"
.br
.ti -1c
.RI "static T \fBReadJson< T >\fP (string path)"
.br
.ti -1c
.RI "static List< \fBSteamVR_Input_ActionFile_Action\fP > \fBRemoveOldActions\fP (List< \fBSteamVR_PartialInputBindings\fP > partialBindingList)"
.br
.ti -1c
.RI "static List< \fBSteamVR_Input_ActionFile_ActionSet\fP > \fBRemoveOldActionSets\fP (List< \fBSteamVR_PartialInputBindings\fP > partialBindingList)"
.br
.ti -1c
.RI "static int \fBRemoveOldLocalizations\fP (List< \fBSteamVR_Input_ActionFile_Action\fP > removedActionList)"
.br
.ti -1c
.RI "static void \fBRemoveOldActionsAndSetsFromBindings\fP (List< \fBSteamVR_Input_ActionFile_ActionSet\fP > setsToRemove, List< \fBSteamVR_Input_ActionFile_Action\fP > actionsToRemove)"
.br
.ti -1c
.RI "static void \fBRemoveOldPartialBindings\fP (List< \fBSteamVR_PartialInputBindings\fP > partialBindingList)"
.br
.ti -1c
.RI "static void \fBConfirmImport\fP (List< \fBSteamVR_PartialInputBindings\fP > partialBindingList)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const string \fBdontAskAgainTemplate\fP = '{0}_{1}_DontAskAgain'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.CleanBindings (bool verbose = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 329 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.ConfirmImport (List< \fBSteamVR_PartialInputBindings\fP > partialBindingList)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 764 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.CreatePartial (string name, int version, bool overwriteOld, bool removeUnused)\fC [static]\fP"

.PP
Definition at line 37 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static string Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.FindLanguageInDictionary (Dictionary< string, string > dictionary)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 86 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static \fBSteamVR_Input_BindingFile\fP Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.GetBindingFileObject (string path)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 199 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static int Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.ImportActions (\fBSteamVR_Input_ActionFile\fP currentActionsFile, \fBSteamVR_Input_ActionFile\fP newActionsFile)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 173 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static int Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.ImportActionSets (\fBSteamVR_Input_ActionFile\fP currentActionsFile, \fBSteamVR_Input_ActionFile\fP newActionsFile)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 157 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.ImportBindings (\fBSteamVR_Input_ActionFile\fP currentActionsFile, \fBSteamVR_Input_ActionFile\fP newActionsFile, string directory)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 230 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static int Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.ImportLocalization (\fBSteamVR_Input_ActionFile\fP currentActionsFile, \fBSteamVR_Input_ActionFile\fP newActionsFile, \fBSteamVR_PartialInputBindings\fP partialBinding)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 97 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.ImportPartialBinding (\fBSteamVR_PartialInputBindings\fP partialBinding)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 475 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static T Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.ReadJson< T > (string path)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 558 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static List<\fBSteamVR_Input_ActionFile_Action\fP> Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.RemoveOldActions (List< \fBSteamVR_PartialInputBindings\fP > partialBindingList)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 569 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.RemoveOldActionsAndSetsFromBindings (List< \fBSteamVR_Input_ActionFile_ActionSet\fP > setsToRemove, List< \fBSteamVR_Input_ActionFile_Action\fP > actionsToRemove)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 644 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static List<\fBSteamVR_Input_ActionFile_ActionSet\fP> Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.RemoveOldActionSets (List< \fBSteamVR_PartialInputBindings\fP > partialBindingList)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 598 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static int Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.RemoveOldLocalizations (List< \fBSteamVR_Input_ActionFile_Action\fP > removedActionList)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 627 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.RemoveOldPartialBindings (List< \fBSteamVR_PartialInputBindings\fP > partialBindingList)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 737 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.ReplaceBinding (\fBSteamVR_PartialInputBindings\fP partialBinding)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 520 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static Dictionary<string, List<\fBSteamVR_PartialInputBindings\fP> > Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.ScanForPartials ()\fC [static]\fP"

.PP
Definition at line 804 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.WriteBindingFileObject (\fBSteamVR_Input_BindingFile\fP currentBindingFile, string currentBindingPath)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 215 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.dontAskAgainTemplate = '{0}_{1}_DontAskAgain'\fC [protected]\fP"

.PP
Definition at line 763 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.
.SS "const string Valve\&.VR\&.SteamVR_Input_ActionManifest_Manager\&.partialManifestFilename = 'steamvr_partial_manifest\&.json'"

.PP
Definition at line 36 of file SteamVR_Input_ActionManifest_Manager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
