.TH "Valve.VR.VRTextureDepthInfo_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VRTextureDepthInfo_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IntPtr \fBhandle\fP"
.br
.ti -1c
.RI "\fBHmdMatrix44_t\fP \fBmProjection\fP"
.br
.ti -1c
.RI "\fBHmdVector2_t\fP \fBvRange\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5010 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "IntPtr Valve\&.VR\&.VRTextureDepthInfo_t\&.handle"

.PP
Definition at line 5012 of file openvr_api\&.cs\&.
.SS "\fBHmdMatrix44_t\fP Valve\&.VR\&.VRTextureDepthInfo_t\&.mProjection"

.PP
Definition at line 5013 of file openvr_api\&.cs\&.
.SS "\fBHmdVector2_t\fP Valve\&.VR\&.VRTextureDepthInfo_t\&.vRange"

.PP
Definition at line 5014 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
