.TH "Valve.VR.InteractionSystem.DistanceHaptics" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.DistanceHaptics
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBfirstTransform\fP"
.br
.ti -1c
.RI "Transform \fBsecondTransform\fP"
.br
.ti -1c
.RI "AnimationCurve \fBdistanceIntensityCurve\fP = \fBAnimationCurve\&.Linear\fP( 0\&.0f, 800\&.0f, 1\&.0f, 800\&.0f )"
.br
.ti -1c
.RI "AnimationCurve \fBpulseIntervalCurve\fP = \fBAnimationCurve\&.Linear\fP( 0\&.0f, 0\&.01f, 1\&.0f, 0\&.0f )"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file DistanceHaptics\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "AnimationCurve Valve\&.VR\&.InteractionSystem\&.DistanceHaptics\&.distanceIntensityCurve = \fBAnimationCurve\&.Linear\fP( 0\&.0f, 800\&.0f, 1\&.0f, 800\&.0f )"

.PP
Definition at line 18 of file DistanceHaptics\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.DistanceHaptics\&.firstTransform"

.PP
Definition at line 15 of file DistanceHaptics\&.cs\&.
.SS "AnimationCurve Valve\&.VR\&.InteractionSystem\&.DistanceHaptics\&.pulseIntervalCurve = \fBAnimationCurve\&.Linear\fP( 0\&.0f, 0\&.01f, 1\&.0f, 0\&.0f )"

.PP
Definition at line 19 of file DistanceHaptics\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.DistanceHaptics\&.secondTransform"

.PP
Definition at line 16 of file DistanceHaptics\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
