.TH "Valve.VR.SteamVR_RingBuffer< T >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_RingBuffer< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSteamVR_RingBuffer\fP (int size)"
.br
.ti -1c
.RI "void \fBAdd\fP (T newElement)"
.br
.ti -1c
.RI "virtual void \fBStepForward\fP ()"
.br
.ti -1c
.RI "virtual T \fBGetAtIndex\fP (int atIndex)"
.br
.ti -1c
.RI "virtual T \fBGetLast\fP ()"
.br
.ti -1c
.RI "virtual int \fBGetLastIndex\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "T [] \fBbuffer\fP"
.br
.ti -1c
.RI "int \fBcurrentIndex\fP"
.br
.ti -1c
.RI "T \fBlastElement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file SteamVR_RingBuffer\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBValve\&.VR\&.SteamVR_RingBuffer\fP< T >\&.\fBSteamVR_RingBuffer\fP (int size)"

.PP
Definition at line 14 of file SteamVR_RingBuffer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBValve\&.VR\&.SteamVR_RingBuffer\fP< T >\&.Add (T newElement)"

.PP
Definition at line 20 of file SteamVR_RingBuffer\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_RingBuffer\fP< T >\&.Clear ()"

.PP
Definition at line 61 of file SteamVR_RingBuffer\&.cs\&.
.SS "virtual T \fBValve\&.VR\&.SteamVR_RingBuffer\fP< T >\&.GetAtIndex (int atIndex)\fC [virtual]\fP"

.PP
Definition at line 38 of file SteamVR_RingBuffer\&.cs\&.
.SS "virtual T \fBValve\&.VR\&.SteamVR_RingBuffer\fP< T >\&.GetLast ()\fC [virtual]\fP"

.PP
Definition at line 46 of file SteamVR_RingBuffer\&.cs\&.
.SS "virtual int \fBValve\&.VR\&.SteamVR_RingBuffer\fP< T >\&.GetLastIndex ()\fC [virtual]\fP"

.PP
Definition at line 51 of file SteamVR_RingBuffer\&.cs\&.
.SS "virtual void \fBValve\&.VR\&.SteamVR_RingBuffer\fP< T >\&.StepForward ()\fC [virtual]\fP"

.PP
Definition at line 27 of file SteamVR_RingBuffer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "T [] \fBValve\&.VR\&.SteamVR_RingBuffer\fP< T >\&.buffer\fC [protected]\fP"

.PP
Definition at line 10 of file SteamVR_RingBuffer\&.cs\&.
.SS "int \fBValve\&.VR\&.SteamVR_RingBuffer\fP< T >\&.currentIndex\fC [protected]\fP"

.PP
Definition at line 11 of file SteamVR_RingBuffer\&.cs\&.
.SS "T \fBValve\&.VR\&.SteamVR_RingBuffer\fP< T >\&.lastElement\fC [protected]\fP"

.PP
Definition at line 12 of file SteamVR_RingBuffer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
