.TH "Valve.VR.SteamVR_Behaviour_Vector2" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Behaviour_Vector2 \- Simplifies the use of the Vector2 action\&. Provides an onChange event that fires whenever the vector2 changes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetLocalizedName\fP (params \fBEVRInputStringBits\fP[] localizedParts)"
.br
.RI "Gets the localized name of the device that the action corresponds to\&. "
.ti -1c
.RI "delegate void \fBAxisHandler\fP (\fBSteamVR_Behaviour_Vector2\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, Vector2 newAxis, Vector2 newDelta)"
.br
.ti -1c
.RI "delegate void \fBChangeHandler\fP (\fBSteamVR_Behaviour_Vector2\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, Vector2 newAxis, Vector2 newDelta)"
.br
.ti -1c
.RI "delegate void \fBUpdateHandler\fP (\fBSteamVR_Behaviour_Vector2\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, Vector2 newAxis, Vector2 newDelta)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_Action_Vector2\fP \fBvector2Action\fP"
.br
.RI "The vector2 action to get data from "
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBinputSource\fP"
.br
.RI "The device this action applies to\&. Any if the action is not device specific\&. "
.ti -1c
.RI "\fBSteamVR_Behaviour_Vector2Event\fP \fBonChange\fP"
.br
.RI "Unity event that fires whenever the action's value has changed since the last update\&. "
.ti -1c
.RI "\fBSteamVR_Behaviour_Vector2Event\fP \fBonUpdate\fP"
.br
.RI "Unity event that fires whenever the action's value has been updated "
.ti -1c
.RI "\fBSteamVR_Behaviour_Vector2Event\fP \fBonAxis\fP"
.br
.RI "Unity event that fires whenever the action's value has been updated and is non-zero "
.ti -1c
.RI "\fBChangeHandler\fP \fBonChangeEvent\fP"
.br
.RI "C# event that fires whenever the action's value has changed since the last update\&. "
.ti -1c
.RI "\fBUpdateHandler\fP \fBonUpdateEvent\fP"
.br
.RI "C# event that fires whenever the action's value has been updated "
.ti -1c
.RI "\fBAxisHandler\fP \fBonAxisEvent\fP"
.br
.RI "C# event that fires whenever the action's value has been updated and is non-zero "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBAddHandlers\fP ()"
.br
.ti -1c
.RI "void \fBRemoveHandlers\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBisActive\fP\fC [get]\fP"
.br
.RI "Returns whether this action is bound and the action set is active "
.in -1c
.SH "Detailed Description"
.PP 
Simplifies the use of the Vector2 action\&. Provides an onChange event that fires whenever the vector2 changes\&. 


.PP
Definition at line 16 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.AddHandlers ()\fC [protected]\fP"

.PP
Definition at line 65 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "delegate void Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.AxisHandler (\fBSteamVR_Behaviour_Vector2\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, Vector2 newAxis, Vector2 newDelta)"

.SS "delegate void Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.ChangeHandler (\fBSteamVR_Behaviour_Vector2\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, Vector2 newAxis, Vector2 newDelta)"

.SS "string Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.GetLocalizedName (params \fBEVRInputStringBits\fP [] localizedParts)"

.PP
Gets the localized name of the device that the action corresponds to\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlocalizedParts\fP 
.PD 0

.IP "\(bu" 2
VRInputString_Hand - Which hand the origin is in\&. E\&.g\&. 'Left Hand' 
.IP "\(bu" 2
VRInputString_ControllerType - What kind of controller the user has in that hand\&.E\&.g\&. 'Vive Controller' 
.IP "\(bu" 2
VRInputString_InputSource - What part of that controller is the origin\&. E\&.g\&. 'Trackpad' 
.IP "\(bu" 2
VRInputString_All - All of the above\&. E\&.g\&. 'Left Hand Vive Controller Trackpad' 
.PP
.RE
.PP

.PP
Definition at line 129 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "virtual void Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.OnDisable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 60 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "virtual void Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.OnEnable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 49 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.RemoveHandlers ()\fC [protected]\fP"

.PP
Definition at line 72 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "delegate void Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.UpdateHandler (\fBSteamVR_Behaviour_Vector2\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, Vector2 newAxis, Vector2 newDelta)"

.SH "Member Data Documentation"
.PP 
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.inputSource"

.PP
The device this action applies to\&. Any if the action is not device specific\&. 
.PP
Definition at line 23 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "\fBSteamVR_Behaviour_Vector2Event\fP Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.onAxis"

.PP
Unity event that fires whenever the action's value has been updated and is non-zero 
.PP
Definition at line 35 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "\fBAxisHandler\fP Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.onAxisEvent"

.PP
C# event that fires whenever the action's value has been updated and is non-zero 
.PP
Definition at line 44 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "\fBSteamVR_Behaviour_Vector2Event\fP Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.onChange"

.PP
Unity event that fires whenever the action's value has changed since the last update\&. 
.PP
Definition at line 27 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "\fBChangeHandler\fP Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.onChangeEvent"

.PP
C# event that fires whenever the action's value has changed since the last update\&. 
.PP
Definition at line 38 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "\fBSteamVR_Behaviour_Vector2Event\fP Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.onUpdate"

.PP
Unity event that fires whenever the action's value has been updated 
.PP
Definition at line 31 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "\fBUpdateHandler\fP Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.onUpdateEvent"

.PP
C# event that fires whenever the action's value has been updated 
.PP
Definition at line 41 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SS "\fBSteamVR_Action_Vector2\fP Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.vector2Action"

.PP
The vector2 action to get data from 
.PP
Definition at line 19 of file SteamVR_Behaviour_Vector2\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_Behaviour_Vector2\&.isActive\fC [get]\fP"

.PP
Returns whether this action is bound and the action set is active 
.PP
Definition at line 47 of file SteamVR_Behaviour_Vector2\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
