.TH "Valve.VR.InteractionSystem.Sample.CustomSkeletonHelper" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Sample.CustomSkeletonHelper
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFinger\fP"
.br
.ti -1c
.RI "class \fBRetargetable\fP"
.br
.ti -1c
.RI "class \fBThumb\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMirrorType\fP { \fBMirrorType\&.None\fP, \fBMirrorType\&.LeftToRight\fP, \fBMirrorType\&.RightToLeft\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRetargetable\fP \fBwrist\fP"
.br
.ti -1c
.RI "\fBFinger\fP [] \fBfingers\fP"
.br
.ti -1c
.RI "\fBThumb\fP [] \fBthumbs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file CustomSkeletonHelper\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.InteractionSystem\&.Sample\&.CustomSkeletonHelper\&.MirrorType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fILeftToRight \fP\fP
.TP
\fB\fIRightToLeft \fP\fP
.PP
Definition at line 39 of file CustomSkeletonHelper\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFinger\fP [] Valve\&.VR\&.InteractionSystem\&.Sample\&.CustomSkeletonHelper\&.fingers"

.PP
Definition at line 14 of file CustomSkeletonHelper\&.cs\&.
.SS "\fBThumb\fP [] Valve\&.VR\&.InteractionSystem\&.Sample\&.CustomSkeletonHelper\&.thumbs"

.PP
Definition at line 15 of file CustomSkeletonHelper\&.cs\&.
.SS "\fBRetargetable\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.CustomSkeletonHelper\&.wrist"

.PP
Definition at line 12 of file CustomSkeletonHelper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
