.TH "Valve.VR.OpenVR" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.OpenVR
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint \fBInitInternal\fP (ref \fBEVRInitError\fP peError, \fBEVRApplicationType\fP eApplicationType)"
.br
.ti -1c
.RI "static uint \fBInitInternal2\fP (ref \fBEVRInitError\fP peError, \fBEVRApplicationType\fP eApplicationType, string pchStartupInfo)"
.br
.ti -1c
.RI "static void \fBShutdownInternal\fP ()"
.br
.ti -1c
.RI "static bool \fBIsHmdPresent\fP ()"
.br
.ti -1c
.RI "static bool \fBIsRuntimeInstalled\fP ()"
.br
.ti -1c
.RI "static string \fBRuntimePath\fP ()"
.br
.ti -1c
.RI "static string \fBGetStringForHmdError\fP (\fBEVRInitError\fP error)"
.br
.ti -1c
.RI "static IntPtr \fBGetGenericInterface\fP (string pchInterfaceVersion, ref \fBEVRInitError\fP peError)"
.br
.ti -1c
.RI "static bool \fBIsInterfaceVersionValid\fP (string pchInterfaceVersion)"
.br
.ti -1c
.RI "static uint \fBGetInitToken\fP ()"
.br
.ti -1c
.RI "static \fBCVRSystem\fP \fBInit\fP (ref \fBEVRInitError\fP peError, \fBEVRApplicationType\fP eApplicationType=\fBEVRApplicationType\&.VRApplication_Scene\fP, string pchStartupInfo='')"
.br
.ti -1c
.RI "static void \fBShutdown\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const uint \fBk_nDriverNone\fP = 4294967295"
.br
.ti -1c
.RI "const uint \fBk_unMaxDriverDebugResponseSize\fP = 32768"
.br
.ti -1c
.RI "const uint \fBk_unTrackedDeviceIndex_Hmd\fP = 0"
.br
.ti -1c
.RI "const uint \fBk_unMaxTrackedDeviceCount\fP = 64"
.br
.ti -1c
.RI "const uint \fBk_unTrackedDeviceIndexOther\fP = 4294967294"
.br
.ti -1c
.RI "const uint \fBk_unTrackedDeviceIndexInvalid\fP = 4294967295"
.br
.ti -1c
.RI "const ulong \fBk_ulInvalidPropertyContainer\fP = 0"
.br
.ti -1c
.RI "const uint \fBk_unInvalidPropertyTag\fP = 0"
.br
.ti -1c
.RI "const ulong \fBk_ulInvalidDriverHandle\fP = 0"
.br
.ti -1c
.RI "const uint \fBk_unFloatPropertyTag\fP = 1"
.br
.ti -1c
.RI "const uint \fBk_unInt32PropertyTag\fP = 2"
.br
.ti -1c
.RI "const uint \fBk_unUint64PropertyTag\fP = 3"
.br
.ti -1c
.RI "const uint \fBk_unBoolPropertyTag\fP = 4"
.br
.ti -1c
.RI "const uint \fBk_unStringPropertyTag\fP = 5"
.br
.ti -1c
.RI "const uint \fBk_unHmdMatrix34PropertyTag\fP = 20"
.br
.ti -1c
.RI "const uint \fBk_unHmdMatrix44PropertyTag\fP = 21"
.br
.ti -1c
.RI "const uint \fBk_unHmdVector3PropertyTag\fP = 22"
.br
.ti -1c
.RI "const uint \fBk_unHmdVector4PropertyTag\fP = 23"
.br
.ti -1c
.RI "const uint \fBk_unHmdVector2PropertyTag\fP = 24"
.br
.ti -1c
.RI "const uint \fBk_unHmdQuadPropertyTag\fP = 25"
.br
.ti -1c
.RI "const uint \fBk_unHiddenAreaPropertyTag\fP = 30"
.br
.ti -1c
.RI "const uint \fBk_unPathHandleInfoTag\fP = 31"
.br
.ti -1c
.RI "const uint \fBk_unActionPropertyTag\fP = 32"
.br
.ti -1c
.RI "const uint \fBk_unInputValuePropertyTag\fP = 33"
.br
.ti -1c
.RI "const uint \fBk_unWildcardPropertyTag\fP = 34"
.br
.ti -1c
.RI "const uint \fBk_unHapticVibrationPropertyTag\fP = 35"
.br
.ti -1c
.RI "const uint \fBk_unSkeletonPropertyTag\fP = 36"
.br
.ti -1c
.RI "const uint \fBk_unSpatialAnchorPosePropertyTag\fP = 40"
.br
.ti -1c
.RI "const uint \fBk_unJsonPropertyTag\fP = 41"
.br
.ti -1c
.RI "const uint \fBk_unActiveActionSetPropertyTag\fP = 42"
.br
.ti -1c
.RI "const uint \fBk_unOpenVRInternalReserved_Start\fP = 1000"
.br
.ti -1c
.RI "const uint \fBk_unOpenVRInternalReserved_End\fP = 10000"
.br
.ti -1c
.RI "const uint \fBk_unMaxPropertyStringSize\fP = 32768"
.br
.ti -1c
.RI "const ulong \fBk_ulInvalidActionHandle\fP = 0"
.br
.ti -1c
.RI "const ulong \fBk_ulInvalidActionSetHandle\fP = 0"
.br
.ti -1c
.RI "const ulong \fBk_ulInvalidInputValueHandle\fP = 0"
.br
.ti -1c
.RI "const uint \fBk_unControllerStateAxisCount\fP = 5"
.br
.ti -1c
.RI "const ulong \fBk_ulOverlayHandleInvalid\fP = 0"
.br
.ti -1c
.RI "const uint \fBk_unMaxDistortionFunctionParameters\fP = 8"
.br
.ti -1c
.RI "const uint \fBk_unScreenshotHandleInvalid\fP = 0"
.br
.ti -1c
.RI "const string \fBIVRSystem_Version\fP = 'IVRSystem_019'"
.br
.ti -1c
.RI "const string \fBIVRExtendedDisplay_Version\fP = 'IVRExtendedDisplay_001'"
.br
.ti -1c
.RI "const string \fBIVRTrackedCamera_Version\fP = 'IVRTrackedCamera_005'"
.br
.ti -1c
.RI "const uint \fBk_unMaxApplicationKeyLength\fP = 128"
.br
.ti -1c
.RI "const string \fBk_pch_MimeType_HomeApp\fP = 'vr/home'"
.br
.ti -1c
.RI "const string \fBk_pch_MimeType_GameTheater\fP = 'vr/game_theater'"
.br
.ti -1c
.RI "const string \fBIVRApplications_Version\fP = 'IVRApplications_006'"
.br
.ti -1c
.RI "const string \fBIVRChaperone_Version\fP = 'IVRChaperone_003'"
.br
.ti -1c
.RI "const string \fBIVRChaperoneSetup_Version\fP = 'IVRChaperoneSetup_006'"
.br
.ti -1c
.RI "const string \fBIVRCompositor_Version\fP = 'IVRCompositor_022'"
.br
.ti -1c
.RI "const uint \fBk_unVROverlayMaxKeyLength\fP = 128"
.br
.ti -1c
.RI "const uint \fBk_unVROverlayMaxNameLength\fP = 128"
.br
.ti -1c
.RI "const uint \fBk_unMaxOverlayCount\fP = 64"
.br
.ti -1c
.RI "const uint \fBk_unMaxOverlayIntersectionMaskPrimitivesCount\fP = 32"
.br
.ti -1c
.RI "const string \fBIVROverlay_Version\fP = 'IVROverlay_019'"
.br
.ti -1c
.RI "const string \fBk_pch_Controller_Component_GDC2015\fP = 'gdc2015'"
.br
.ti -1c
.RI "const string \fBk_pch_Controller_Component_Base\fP = 'base'"
.br
.ti -1c
.RI "const string \fBk_pch_Controller_Component_Tip\fP = 'tip'"
.br
.ti -1c
.RI "const string \fBk_pch_Controller_Component_HandGrip\fP = 'handgrip'"
.br
.ti -1c
.RI "const string \fBk_pch_Controller_Component_Status\fP = 'status'"
.br
.ti -1c
.RI "const string \fBIVRRenderModels_Version\fP = 'IVRRenderModels_006'"
.br
.ti -1c
.RI "const uint \fBk_unNotificationTextMaxSize\fP = 256"
.br
.ti -1c
.RI "const string \fBIVRNotifications_Version\fP = 'IVRNotifications_002'"
.br
.ti -1c
.RI "const uint \fBk_unMaxSettingsKeyLength\fP = 128"
.br
.ti -1c
.RI "const string \fBIVRSettings_Version\fP = 'IVRSettings_002'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_Section\fP = 'steamvr'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_RequireHmd_String\fP = 'requireHmd'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_ForcedDriverKey_String\fP = 'forcedDriver'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_ForcedHmdKey_String\fP = 'forcedHmd'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_DisplayDebug_Bool\fP = 'displayDebug'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_DebugProcessPipe_String\fP = 'debugProcessPipe'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_DisplayDebugX_Int32\fP = 'displayDebugX'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_DisplayDebugY_Int32\fP = 'displayDebugY'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_SendSystemButtonToAllApps_Bool\fP = 'sendSystemButtonToAllApps'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_LogLevel_Int32\fP = 'loglevel'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_IPD_Float\fP = 'ipd'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_Background_String\fP = 'background'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_BackgroundUseDomeProjection_Bool\fP = 'backgroundUseDomeProjection'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_BackgroundCameraHeight_Float\fP = 'backgroundCameraHeight'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_BackgroundDomeRadius_Float\fP = 'backgroundDomeRadius'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_GridColor_String\fP = 'gridColor'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_PlayAreaColor_String\fP = 'playAreaColor'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_ShowStage_Bool\fP = 'showStage'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_ActivateMultipleDrivers_Bool\fP = 'activateMultipleDrivers'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_UsingSpeakers_Bool\fP = 'usingSpeakers'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_SpeakersForwardYawOffsetDegrees_Float\fP = 'speakersForwardYawOffsetDegrees'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_BaseStationPowerManagement_Bool\fP = 'basestationPowerManagement'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_NeverKillProcesses_Bool\fP = 'neverKillProcesses'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_SupersampleScale_Float\fP = 'supersampleScale'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_MaxRecommendedResolution_Int32\fP = 'maxRecommendedResolution'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_MotionSmoothing_Bool\fP = 'motionSmoothing'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_MotionSmoothingOverride_Int32\fP = 'motionSmoothingOverride'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_ForceFadeOnBadTracking_Bool\fP = 'forceFadeOnBadTracking'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_DefaultMirrorView_Int32\fP = 'mirrorView'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_ShowMirrorView_Bool\fP = 'showMirrorView'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_MirrorViewGeometry_String\fP = 'mirrorViewGeometry'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_MirrorViewGeometryMaximized_String\fP = 'mirrorViewGeometryMaximized'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_StartMonitorFromAppLaunch\fP = 'startMonitorFromAppLaunch'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_StartCompositorFromAppLaunch_Bool\fP = 'startCompositorFromAppLaunch'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_StartDashboardFromAppLaunch_Bool\fP = 'startDashboardFromAppLaunch'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_StartOverlayAppsFromDashboard_Bool\fP = 'startOverlayAppsFromDashboard'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_EnableHomeApp\fP = 'enableHomeApp'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_CycleBackgroundImageTimeSec_Int32\fP = 'CycleBackgroundImageTimeSec'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_RetailDemo_Bool\fP = 'retailDemo'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_IpdOffset_Float\fP = 'ipdOffset'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_AllowSupersampleFiltering_Bool\fP = 'allowSupersampleFiltering'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_SupersampleManualOverride_Bool\fP = 'supersampleManualOverride'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_EnableLinuxVulkanAsync_Bool\fP = 'enableLinuxVulkanAsync'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_AllowDisplayLockedMode_Bool\fP = 'allowDisplayLockedMode'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_HaveStartedTutorialForNativeChaperoneDriver_Bool\fP = 'haveStartedTutorialForNativeChaperoneDriver'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_ForceWindows32bitVRMonitor\fP = 'forceWindows32BitVRMonitor'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_DebugInput\fP = 'debugInput'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_DebugInputBinding\fP = 'debugInputBinding'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_InputBindingUIBlock\fP = 'inputBindingUI'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_RenderCameraMode\fP = 'renderCameraMode'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_EnableSharedResourceJournaling\fP = 'enableSharedResourceJournaling'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_EnableSafeMode\fP = 'enableSafeMode'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_PreferredRefreshRate\fP = 'preferredRefreshRate'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_LastVersionNotice\fP = 'lastVersionNotice'"
.br
.ti -1c
.RI "const string \fBk_pch_SteamVR_LastVersionNoticeDate\fP = 'lastVersionNoticeDate'"
.br
.ti -1c
.RI "const string \fBk_pch_DirectMode_Section\fP = 'direct_mode'"
.br
.ti -1c
.RI "const string \fBk_pch_DirectMode_Enable_Bool\fP = 'enable'"
.br
.ti -1c
.RI "const string \fBk_pch_DirectMode_Count_Int32\fP = 'count'"
.br
.ti -1c
.RI "const string \fBk_pch_DirectMode_EdidVid_Int32\fP = 'edidVid'"
.br
.ti -1c
.RI "const string \fBk_pch_DirectMode_EdidPid_Int32\fP = 'edidPid'"
.br
.ti -1c
.RI "const string \fBk_pch_Lighthouse_Section\fP = 'driver_lighthouse'"
.br
.ti -1c
.RI "const string \fBk_pch_Lighthouse_DisableIMU_Bool\fP = 'disableimu'"
.br
.ti -1c
.RI "const string \fBk_pch_Lighthouse_DisableIMUExceptHMD_Bool\fP = 'disableimuexcepthmd'"
.br
.ti -1c
.RI "const string \fBk_pch_Lighthouse_UseDisambiguation_String\fP = 'usedisambiguation'"
.br
.ti -1c
.RI "const string \fBk_pch_Lighthouse_DisambiguationDebug_Int32\fP = 'disambiguationdebug'"
.br
.ti -1c
.RI "const string \fBk_pch_Lighthouse_PrimaryBasestation_Int32\fP = 'primarybasestation'"
.br
.ti -1c
.RI "const string \fBk_pch_Lighthouse_DBHistory_Bool\fP = 'dbhistory'"
.br
.ti -1c
.RI "const string \fBk_pch_Lighthouse_EnableBluetooth_Bool\fP = 'enableBluetooth'"
.br
.ti -1c
.RI "const string \fBk_pch_Lighthouse_PowerManagedBaseStations_String\fP = 'PowerManagedBaseStations'"
.br
.ti -1c
.RI "const string \fBk_pch_Lighthouse_PowerManagedBaseStations2_String\fP = 'PowerManagedBaseStations2'"
.br
.ti -1c
.RI "const string \fBk_pch_Lighthouse_EnableImuFallback_Bool\fP = 'enableImuFallback'"
.br
.ti -1c
.RI "const string \fBk_pch_Null_Section\fP = 'driver_null'"
.br
.ti -1c
.RI "const string \fBk_pch_Null_SerialNumber_String\fP = 'serialNumber'"
.br
.ti -1c
.RI "const string \fBk_pch_Null_ModelNumber_String\fP = 'modelNumber'"
.br
.ti -1c
.RI "const string \fBk_pch_Null_WindowX_Int32\fP = 'windowX'"
.br
.ti -1c
.RI "const string \fBk_pch_Null_WindowY_Int32\fP = 'windowY'"
.br
.ti -1c
.RI "const string \fBk_pch_Null_WindowWidth_Int32\fP = 'windowWidth'"
.br
.ti -1c
.RI "const string \fBk_pch_Null_WindowHeight_Int32\fP = 'windowHeight'"
.br
.ti -1c
.RI "const string \fBk_pch_Null_RenderWidth_Int32\fP = 'renderWidth'"
.br
.ti -1c
.RI "const string \fBk_pch_Null_RenderHeight_Int32\fP = 'renderHeight'"
.br
.ti -1c
.RI "const string \fBk_pch_Null_SecondsFromVsyncToPhotons_Float\fP = 'secondsFromVsyncToPhotons'"
.br
.ti -1c
.RI "const string \fBk_pch_Null_DisplayFrequency_Float\fP = 'displayFrequency'"
.br
.ti -1c
.RI "const string \fBk_pch_UserInterface_Section\fP = 'userinterface'"
.br
.ti -1c
.RI "const string \fBk_pch_UserInterface_StatusAlwaysOnTop_Bool\fP = 'StatusAlwaysOnTop'"
.br
.ti -1c
.RI "const string \fBk_pch_UserInterface_MinimizeToTray_Bool\fP = 'MinimizeToTray'"
.br
.ti -1c
.RI "const string \fBk_pch_UserInterface_HidePopupsWhenStatusMinimized_Bool\fP = 'HidePopupsWhenStatusMinimized'"
.br
.ti -1c
.RI "const string \fBk_pch_UserInterface_Screenshots_Bool\fP = 'screenshots'"
.br
.ti -1c
.RI "const string \fBk_pch_UserInterface_ScreenshotType_Int\fP = 'screenshotType'"
.br
.ti -1c
.RI "const string \fBk_pch_Notifications_Section\fP = 'notifications'"
.br
.ti -1c
.RI "const string \fBk_pch_Notifications_DoNotDisturb_Bool\fP = 'DoNotDisturb'"
.br
.ti -1c
.RI "const string \fBk_pch_Keyboard_Section\fP = 'keyboard'"
.br
.ti -1c
.RI "const string \fBk_pch_Keyboard_TutorialCompletions\fP = 'TutorialCompletions'"
.br
.ti -1c
.RI "const string \fBk_pch_Keyboard_ScaleX\fP = 'ScaleX'"
.br
.ti -1c
.RI "const string \fBk_pch_Keyboard_ScaleY\fP = 'ScaleY'"
.br
.ti -1c
.RI "const string \fBk_pch_Keyboard_OffsetLeftX\fP = 'OffsetLeftX'"
.br
.ti -1c
.RI "const string \fBk_pch_Keyboard_OffsetRightX\fP = 'OffsetRightX'"
.br
.ti -1c
.RI "const string \fBk_pch_Keyboard_OffsetY\fP = 'OffsetY'"
.br
.ti -1c
.RI "const string \fBk_pch_Keyboard_Smoothing\fP = 'Smoothing'"
.br
.ti -1c
.RI "const string \fBk_pch_Perf_Section\fP = 'perfcheck'"
.br
.ti -1c
.RI "const string \fBk_pch_Perf_PerfGraphInHMD_Bool\fP = 'perfGraphInHMD'"
.br
.ti -1c
.RI "const string \fBk_pch_Perf_AllowTimingStore_Bool\fP = 'allowTimingStore'"
.br
.ti -1c
.RI "const string \fBk_pch_Perf_SaveTimingsOnExit_Bool\fP = 'saveTimingsOnExit'"
.br
.ti -1c
.RI "const string \fBk_pch_Perf_TestData_Float\fP = 'perfTestData'"
.br
.ti -1c
.RI "const string \fBk_pch_Perf_LinuxGPUProfiling_Bool\fP = 'linuxGPUProfiling'"
.br
.ti -1c
.RI "const string \fBk_pch_CollisionBounds_Section\fP = 'collisionBounds'"
.br
.ti -1c
.RI "const string \fBk_pch_CollisionBounds_Style_Int32\fP = 'CollisionBoundsStyle'"
.br
.ti -1c
.RI "const string \fBk_pch_CollisionBounds_GroundPerimeterOn_Bool\fP = 'CollisionBoundsGroundPerimeterOn'"
.br
.ti -1c
.RI "const string \fBk_pch_CollisionBounds_CenterMarkerOn_Bool\fP = 'CollisionBoundsCenterMarkerOn'"
.br
.ti -1c
.RI "const string \fBk_pch_CollisionBounds_PlaySpaceOn_Bool\fP = 'CollisionBoundsPlaySpaceOn'"
.br
.ti -1c
.RI "const string \fBk_pch_CollisionBounds_FadeDistance_Float\fP = 'CollisionBoundsFadeDistance'"
.br
.ti -1c
.RI "const string \fBk_pch_CollisionBounds_ColorGammaR_Int32\fP = 'CollisionBoundsColorGammaR'"
.br
.ti -1c
.RI "const string \fBk_pch_CollisionBounds_ColorGammaG_Int32\fP = 'CollisionBoundsColorGammaG'"
.br
.ti -1c
.RI "const string \fBk_pch_CollisionBounds_ColorGammaB_Int32\fP = 'CollisionBoundsColorGammaB'"
.br
.ti -1c
.RI "const string \fBk_pch_CollisionBounds_ColorGammaA_Int32\fP = 'CollisionBoundsColorGammaA'"
.br
.ti -1c
.RI "const string \fBk_pch_Camera_Section\fP = 'camera'"
.br
.ti -1c
.RI "const string \fBk_pch_Camera_EnableCamera_Bool\fP = 'enableCamera'"
.br
.ti -1c
.RI "const string \fBk_pch_Camera_EnableCameraInDashboard_Bool\fP = 'enableCameraInDashboard'"
.br
.ti -1c
.RI "const string \fBk_pch_Camera_EnableCameraForCollisionBounds_Bool\fP = 'enableCameraForCollisionBounds'"
.br
.ti -1c
.RI "const string \fBk_pch_Camera_EnableCameraForRoomView_Bool\fP = 'enableCameraForRoomView'"
.br
.ti -1c
.RI "const string \fBk_pch_Camera_BoundsColorGammaR_Int32\fP = 'cameraBoundsColorGammaR'"
.br
.ti -1c
.RI "const string \fBk_pch_Camera_BoundsColorGammaG_Int32\fP = 'cameraBoundsColorGammaG'"
.br
.ti -1c
.RI "const string \fBk_pch_Camera_BoundsColorGammaB_Int32\fP = 'cameraBoundsColorGammaB'"
.br
.ti -1c
.RI "const string \fBk_pch_Camera_BoundsColorGammaA_Int32\fP = 'cameraBoundsColorGammaA'"
.br
.ti -1c
.RI "const string \fBk_pch_Camera_BoundsStrength_Int32\fP = 'cameraBoundsStrength'"
.br
.ti -1c
.RI "const string \fBk_pch_Camera_RoomViewMode_Int32\fP = 'cameraRoomViewMode'"
.br
.ti -1c
.RI "const string \fBk_pch_audio_Section\fP = 'audio'"
.br
.ti -1c
.RI "const string \fBk_pch_audio_OnPlaybackDevice_String\fP = 'onPlaybackDevice'"
.br
.ti -1c
.RI "const string \fBk_pch_audio_OnRecordDevice_String\fP = 'onRecordDevice'"
.br
.ti -1c
.RI "const string \fBk_pch_audio_OnPlaybackMirrorDevice_String\fP = 'onPlaybackMirrorDevice'"
.br
.ti -1c
.RI "const string \fBk_pch_audio_OffPlaybackDevice_String\fP = 'offPlaybackDevice'"
.br
.ti -1c
.RI "const string \fBk_pch_audio_OffRecordDevice_String\fP = 'offRecordDevice'"
.br
.ti -1c
.RI "const string \fBk_pch_audio_VIVEHDMIGain\fP = 'viveHDMIGain'"
.br
.ti -1c
.RI "const string \fBk_pch_Power_Section\fP = 'power'"
.br
.ti -1c
.RI "const string \fBk_pch_Power_PowerOffOnExit_Bool\fP = 'powerOffOnExit'"
.br
.ti -1c
.RI "const string \fBk_pch_Power_TurnOffScreensTimeout_Float\fP = 'turnOffScreensTimeout'"
.br
.ti -1c
.RI "const string \fBk_pch_Power_TurnOffControllersTimeout_Float\fP = 'turnOffControllersTimeout'"
.br
.ti -1c
.RI "const string \fBk_pch_Power_ReturnToWatchdogTimeout_Float\fP = 'returnToWatchdogTimeout'"
.br
.ti -1c
.RI "const string \fBk_pch_Power_AutoLaunchSteamVROnButtonPress\fP = 'autoLaunchSteamVROnButtonPress'"
.br
.ti -1c
.RI "const string \fBk_pch_Power_PauseCompositorOnStandby_Bool\fP = 'pauseCompositorOnStandby'"
.br
.ti -1c
.RI "const string \fBk_pch_Dashboard_Section\fP = 'dashboard'"
.br
.ti -1c
.RI "const string \fBk_pch_Dashboard_EnableDashboard_Bool\fP = 'enableDashboard'"
.br
.ti -1c
.RI "const string \fBk_pch_Dashboard_ArcadeMode_Bool\fP = 'arcadeMode'"
.br
.ti -1c
.RI "const string \fBk_pch_Dashboard_EnableWebUI\fP = 'webUI'"
.br
.ti -1c
.RI "const string \fBk_pch_Dashboard_EnableWebUIDevTools\fP = 'webUIDevTools'"
.br
.ti -1c
.RI "const string \fBk_pch_Dashboard_EnableWebUIDashboardReplacement\fP = 'webUIDashboard'"
.br
.ti -1c
.RI "const string \fBk_pch_modelskin_Section\fP = 'modelskins'"
.br
.ti -1c
.RI "const string \fBk_pch_Driver_Enable_Bool\fP = 'enable'"
.br
.ti -1c
.RI "const string \fBk_pch_WebInterface_Section\fP = 'WebInterface'"
.br
.ti -1c
.RI "const string \fBk_pch_WebInterface_WebEnable_Bool\fP = 'WebEnable'"
.br
.ti -1c
.RI "const string \fBk_pch_WebInterface_WebPort_String\fP = 'WebPort'"
.br
.ti -1c
.RI "const string \fBk_pch_VRWebHelper_Section\fP = 'VRWebHelper'"
.br
.ti -1c
.RI "const string \fBk_pch_VRWebHelper_DebuggerEnabled_Bool\fP = 'DebuggerEnabled'"
.br
.ti -1c
.RI "const string \fBk_pch_VRWebHelper_DebuggerPort_Int32\fP = 'DebuggerPort'"
.br
.ti -1c
.RI "const string \fBk_pch_TrackingOverride_Section\fP = 'TrackingOverrides'"
.br
.ti -1c
.RI "const string \fBk_pch_App_BindingAutosaveURLSuffix_String\fP = 'AutosaveURL'"
.br
.ti -1c
.RI "const string \fBk_pch_App_BindingCurrentURLSuffix_String\fP = 'CurrentURL'"
.br
.ti -1c
.RI "const string \fBk_pch_App_NeedToUpdateAutosaveSuffix_Bool\fP = 'NeedToUpdateAutosave'"
.br
.ti -1c
.RI "const string \fBk_pch_Trackers_Section\fP = 'trackers'"
.br
.ti -1c
.RI "const string \fBk_pch_DesktopUI_Section\fP = 'DesktopUI'"
.br
.ti -1c
.RI "const string \fBk_pch_LastKnown_Section\fP = 'LastKnown'"
.br
.ti -1c
.RI "const string \fBk_pch_LastKnown_HMDManufacturer_String\fP = 'HMDManufacturer'"
.br
.ti -1c
.RI "const string \fBk_pch_LastKnown_HMDModel_String\fP = 'HMDModel'"
.br
.ti -1c
.RI "const string \fBk_pch_DismissedWarnings_Section\fP = 'DismissedWarnings'"
.br
.ti -1c
.RI "const string \fBIVRScreenshots_Version\fP = 'IVRScreenshots_001'"
.br
.ti -1c
.RI "const string \fBIVRResources_Version\fP = 'IVRResources_001'"
.br
.ti -1c
.RI "const string \fBIVRDriverManager_Version\fP = 'IVRDriverManager_001'"
.br
.ti -1c
.RI "const uint \fBk_unMaxActionNameLength\fP = 64"
.br
.ti -1c
.RI "const uint \fBk_unMaxActionSetNameLength\fP = 64"
.br
.ti -1c
.RI "const uint \fBk_unMaxActionOriginCount\fP = 16"
.br
.ti -1c
.RI "const uint \fBk_unMaxBoneNameLength\fP = 32"
.br
.ti -1c
.RI "const string \fBIVRInput_Version\fP = 'IVRInput_005'"
.br
.ti -1c
.RI "const ulong \fBk_ulInvalidIOBufferHandle\fP = 0"
.br
.ti -1c
.RI "const string \fBIVRIOBuffer_Version\fP = 'IVRIOBuffer_002'"
.br
.ti -1c
.RI "const uint \fBk_ulInvalidSpatialAnchorHandle\fP = 0"
.br
.ti -1c
.RI "const string \fBIVRSpatialAnchors_Version\fP = 'IVRSpatialAnchors_001'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBCVRSystem\fP \fBSystem\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVRChaperone\fP \fBChaperone\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVRChaperoneSetup\fP \fBChaperoneSetup\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVRCompositor\fP \fBCompositor\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVROverlay\fP \fBOverlay\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVRRenderModels\fP \fBRenderModels\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVRExtendedDisplay\fP \fBExtendedDisplay\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVRSettings\fP \fBSettings\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVRApplications\fP \fBApplications\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVRScreenshots\fP \fBScreenshots\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVRTrackedCamera\fP \fBTrackedCamera\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVRInput\fP \fBInput\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBCVRSpatialAnchors\fP \fBSpatialAnchors\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5745 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static IntPtr Valve\&.VR\&.OpenVR\&.GetGenericInterface (string pchInterfaceVersion, ref \fBEVRInitError\fP peError)\fC [static]\fP"

.PP
Definition at line 5783 of file openvr_api\&.cs\&.
.SS "static uint Valve\&.VR\&.OpenVR\&.GetInitToken ()\fC [static]\fP"

.PP
Definition at line 5793 of file openvr_api\&.cs\&.
.SS "static string Valve\&.VR\&.OpenVR\&.GetStringForHmdError (\fBEVRInitError\fP error)\fC [static]\fP"

.PP
Definition at line 5778 of file openvr_api\&.cs\&.
.SS "static \fBCVRSystem\fP Valve\&.VR\&.OpenVR\&.Init (ref \fBEVRInitError\fP peError, \fBEVRApplicationType\fP eApplicationType = \fC\fBEVRApplicationType\&.VRApplication_Scene\fP\fP, string pchStartupInfo = \fC''\fP)\fC [static]\fP"
Finds the active installation of vrclient\&.dll and initializes it 
.PP
Definition at line 6283 of file openvr_api\&.cs\&.
.SS "static uint Valve\&.VR\&.OpenVR\&.InitInternal (ref \fBEVRInitError\fP peError, \fBEVRApplicationType\fP eApplicationType)\fC [static]\fP"

.PP
Definition at line 5748 of file openvr_api\&.cs\&.
.SS "static uint Valve\&.VR\&.OpenVR\&.InitInternal2 (ref \fBEVRInitError\fP peError, \fBEVRApplicationType\fP eApplicationType, string pchStartupInfo)\fC [static]\fP"

.PP
Definition at line 5753 of file openvr_api\&.cs\&.
.SS "static bool Valve\&.VR\&.OpenVR\&.IsHmdPresent ()\fC [static]\fP"

.PP
Definition at line 5763 of file openvr_api\&.cs\&.
.SS "static bool Valve\&.VR\&.OpenVR\&.IsInterfaceVersionValid (string pchInterfaceVersion)\fC [static]\fP"

.PP
Definition at line 5788 of file openvr_api\&.cs\&.
.SS "static bool Valve\&.VR\&.OpenVR\&.IsRuntimeInstalled ()\fC [static]\fP"

.PP
Definition at line 5768 of file openvr_api\&.cs\&.
.SS "static string Valve\&.VR\&.OpenVR\&.RuntimePath ()\fC [static]\fP"

.PP
Definition at line 5773 of file openvr_api\&.cs\&.
.SS "static void Valve\&.VR\&.OpenVR\&.Shutdown ()\fC [static]\fP"
unloads vrclient\&.dll\&. Any interface pointers from the interface are invalid after this point 
.PP
Definition at line 6312 of file openvr_api\&.cs\&.
.SS "static void Valve\&.VR\&.OpenVR\&.ShutdownInternal ()\fC [static]\fP"

.PP
Definition at line 5758 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Valve\&.VR\&.OpenVR\&.IVRApplications_Version = 'IVRApplications_006'"

.PP
Definition at line 5844 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRChaperone_Version = 'IVRChaperone_003'"

.PP
Definition at line 5845 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRChaperoneSetup_Version = 'IVRChaperoneSetup_006'"

.PP
Definition at line 5846 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRCompositor_Version = 'IVRCompositor_022'"

.PP
Definition at line 5847 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRDriverManager_Version = 'IVRDriverManager_001'"

.PP
Definition at line 6028 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRExtendedDisplay_Version = 'IVRExtendedDisplay_001'"

.PP
Definition at line 5839 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRInput_Version = 'IVRInput_005'"

.PP
Definition at line 6033 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRIOBuffer_Version = 'IVRIOBuffer_002'"

.PP
Definition at line 6035 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRNotifications_Version = 'IVRNotifications_002'"

.PP
Definition at line 5860 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVROverlay_Version = 'IVROverlay_019'"

.PP
Definition at line 5852 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRRenderModels_Version = 'IVRRenderModels_006'"

.PP
Definition at line 5858 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRResources_Version = 'IVRResources_001'"

.PP
Definition at line 6027 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRScreenshots_Version = 'IVRScreenshots_001'"

.PP
Definition at line 6026 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRSettings_Version = 'IVRSettings_002'"

.PP
Definition at line 5862 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRSpatialAnchors_Version = 'IVRSpatialAnchors_001'"

.PP
Definition at line 6037 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRSystem_Version = 'IVRSystem_019'"

.PP
Definition at line 5838 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.IVRTrackedCamera_Version = 'IVRTrackedCamera_005'"

.PP
Definition at line 5840 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_nDriverNone = 4294967295"

.PP
Definition at line 5798 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_App_BindingAutosaveURLSuffix_String = 'AutosaveURL'"

.PP
Definition at line 6017 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_App_BindingCurrentURLSuffix_String = 'CurrentURL'"

.PP
Definition at line 6018 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_App_NeedToUpdateAutosaveSuffix_Bool = 'NeedToUpdateAutosave'"

.PP
Definition at line 6019 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_audio_OffPlaybackDevice_String = 'offPlaybackDevice'"

.PP
Definition at line 5992 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_audio_OffRecordDevice_String = 'offRecordDevice'"

.PP
Definition at line 5993 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_audio_OnPlaybackDevice_String = 'onPlaybackDevice'"

.PP
Definition at line 5989 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_audio_OnPlaybackMirrorDevice_String = 'onPlaybackMirrorDevice'"

.PP
Definition at line 5991 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_audio_OnRecordDevice_String = 'onRecordDevice'"

.PP
Definition at line 5990 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_audio_Section = 'audio'"

.PP
Definition at line 5988 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_audio_VIVEHDMIGain = 'viveHDMIGain'"

.PP
Definition at line 5994 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Camera_BoundsColorGammaA_Int32 = 'cameraBoundsColorGammaA'"

.PP
Definition at line 5985 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Camera_BoundsColorGammaB_Int32 = 'cameraBoundsColorGammaB'"

.PP
Definition at line 5984 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Camera_BoundsColorGammaG_Int32 = 'cameraBoundsColorGammaG'"

.PP
Definition at line 5983 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Camera_BoundsColorGammaR_Int32 = 'cameraBoundsColorGammaR'"

.PP
Definition at line 5982 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Camera_BoundsStrength_Int32 = 'cameraBoundsStrength'"

.PP
Definition at line 5986 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Camera_EnableCamera_Bool = 'enableCamera'"

.PP
Definition at line 5978 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Camera_EnableCameraForCollisionBounds_Bool = 'enableCameraForCollisionBounds'"

.PP
Definition at line 5980 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Camera_EnableCameraForRoomView_Bool = 'enableCameraForRoomView'"

.PP
Definition at line 5981 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Camera_EnableCameraInDashboard_Bool = 'enableCameraInDashboard'"

.PP
Definition at line 5979 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Camera_RoomViewMode_Int32 = 'cameraRoomViewMode'"

.PP
Definition at line 5987 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Camera_Section = 'camera'"

.PP
Definition at line 5977 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_CollisionBounds_CenterMarkerOn_Bool = 'CollisionBoundsCenterMarkerOn'"

.PP
Definition at line 5970 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_CollisionBounds_ColorGammaA_Int32 = 'CollisionBoundsColorGammaA'"

.PP
Definition at line 5976 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_CollisionBounds_ColorGammaB_Int32 = 'CollisionBoundsColorGammaB'"

.PP
Definition at line 5975 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_CollisionBounds_ColorGammaG_Int32 = 'CollisionBoundsColorGammaG'"

.PP
Definition at line 5974 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_CollisionBounds_ColorGammaR_Int32 = 'CollisionBoundsColorGammaR'"

.PP
Definition at line 5973 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_CollisionBounds_FadeDistance_Float = 'CollisionBoundsFadeDistance'"

.PP
Definition at line 5972 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_CollisionBounds_GroundPerimeterOn_Bool = 'CollisionBoundsGroundPerimeterOn'"

.PP
Definition at line 5969 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_CollisionBounds_PlaySpaceOn_Bool = 'CollisionBoundsPlaySpaceOn'"

.PP
Definition at line 5971 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_CollisionBounds_Section = 'collisionBounds'"

.PP
Definition at line 5967 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_CollisionBounds_Style_Int32 = 'CollisionBoundsStyle'"

.PP
Definition at line 5968 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Controller_Component_Base = 'base'"

.PP
Definition at line 5854 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Controller_Component_GDC2015 = 'gdc2015'"

.PP
Definition at line 5853 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Controller_Component_HandGrip = 'handgrip'"

.PP
Definition at line 5856 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Controller_Component_Status = 'status'"

.PP
Definition at line 5857 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Controller_Component_Tip = 'tip'"

.PP
Definition at line 5855 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Dashboard_ArcadeMode_Bool = 'arcadeMode'"

.PP
Definition at line 6004 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Dashboard_EnableDashboard_Bool = 'enableDashboard'"

.PP
Definition at line 6003 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Dashboard_EnableWebUI = 'webUI'"

.PP
Definition at line 6005 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Dashboard_EnableWebUIDashboardReplacement = 'webUIDashboard'"

.PP
Definition at line 6007 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Dashboard_EnableWebUIDevTools = 'webUIDevTools'"

.PP
Definition at line 6006 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Dashboard_Section = 'dashboard'"

.PP
Definition at line 6002 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_DesktopUI_Section = 'DesktopUI'"

.PP
Definition at line 6021 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_DirectMode_Count_Int32 = 'count'"

.PP
Definition at line 5920 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_DirectMode_EdidPid_Int32 = 'edidPid'"

.PP
Definition at line 5922 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_DirectMode_EdidVid_Int32 = 'edidVid'"

.PP
Definition at line 5921 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_DirectMode_Enable_Bool = 'enable'"

.PP
Definition at line 5919 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_DirectMode_Section = 'direct_mode'"

.PP
Definition at line 5918 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_DismissedWarnings_Section = 'DismissedWarnings'"

.PP
Definition at line 6025 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Driver_Enable_Bool = 'enable'"

.PP
Definition at line 6009 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Keyboard_OffsetLeftX = 'OffsetLeftX'"

.PP
Definition at line 5957 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Keyboard_OffsetRightX = 'OffsetRightX'"

.PP
Definition at line 5958 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Keyboard_OffsetY = 'OffsetY'"

.PP
Definition at line 5959 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Keyboard_ScaleX = 'ScaleX'"

.PP
Definition at line 5955 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Keyboard_ScaleY = 'ScaleY'"

.PP
Definition at line 5956 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Keyboard_Section = 'keyboard'"

.PP
Definition at line 5953 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Keyboard_Smoothing = 'Smoothing'"

.PP
Definition at line 5960 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Keyboard_TutorialCompletions = 'TutorialCompletions'"

.PP
Definition at line 5954 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_LastKnown_HMDManufacturer_String = 'HMDManufacturer'"

.PP
Definition at line 6023 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_LastKnown_HMDModel_String = 'HMDModel'"

.PP
Definition at line 6024 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_LastKnown_Section = 'LastKnown'"

.PP
Definition at line 6022 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Lighthouse_DBHistory_Bool = 'dbhistory'"

.PP
Definition at line 5929 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Lighthouse_DisableIMU_Bool = 'disableimu'"

.PP
Definition at line 5924 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Lighthouse_DisableIMUExceptHMD_Bool = 'disableimuexcepthmd'"

.PP
Definition at line 5925 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Lighthouse_DisambiguationDebug_Int32 = 'disambiguationdebug'"

.PP
Definition at line 5927 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Lighthouse_EnableBluetooth_Bool = 'enableBluetooth'"

.PP
Definition at line 5930 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Lighthouse_EnableImuFallback_Bool = 'enableImuFallback'"

.PP
Definition at line 5933 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Lighthouse_PowerManagedBaseStations2_String = 'PowerManagedBaseStations2'"

.PP
Definition at line 5932 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Lighthouse_PowerManagedBaseStations_String = 'PowerManagedBaseStations'"

.PP
Definition at line 5931 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Lighthouse_PrimaryBasestation_Int32 = 'primarybasestation'"

.PP
Definition at line 5928 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Lighthouse_Section = 'driver_lighthouse'"

.PP
Definition at line 5923 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Lighthouse_UseDisambiguation_String = 'usedisambiguation'"

.PP
Definition at line 5926 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_MimeType_GameTheater = 'vr/game_theater'"

.PP
Definition at line 5843 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_MimeType_HomeApp = 'vr/home'"

.PP
Definition at line 5842 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_modelskin_Section = 'modelskins'"

.PP
Definition at line 6008 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Notifications_DoNotDisturb_Bool = 'DoNotDisturb'"

.PP
Definition at line 5952 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Notifications_Section = 'notifications'"

.PP
Definition at line 5951 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Null_DisplayFrequency_Float = 'displayFrequency'"

.PP
Definition at line 5944 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Null_ModelNumber_String = 'modelNumber'"

.PP
Definition at line 5936 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Null_RenderHeight_Int32 = 'renderHeight'"

.PP
Definition at line 5942 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Null_RenderWidth_Int32 = 'renderWidth'"

.PP
Definition at line 5941 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Null_SecondsFromVsyncToPhotons_Float = 'secondsFromVsyncToPhotons'"

.PP
Definition at line 5943 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Null_Section = 'driver_null'"

.PP
Definition at line 5934 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Null_SerialNumber_String = 'serialNumber'"

.PP
Definition at line 5935 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Null_WindowHeight_Int32 = 'windowHeight'"

.PP
Definition at line 5940 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Null_WindowWidth_Int32 = 'windowWidth'"

.PP
Definition at line 5939 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Null_WindowX_Int32 = 'windowX'"

.PP
Definition at line 5937 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Null_WindowY_Int32 = 'windowY'"

.PP
Definition at line 5938 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Perf_AllowTimingStore_Bool = 'allowTimingStore'"

.PP
Definition at line 5963 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Perf_LinuxGPUProfiling_Bool = 'linuxGPUProfiling'"

.PP
Definition at line 5966 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Perf_PerfGraphInHMD_Bool = 'perfGraphInHMD'"

.PP
Definition at line 5962 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Perf_SaveTimingsOnExit_Bool = 'saveTimingsOnExit'"

.PP
Definition at line 5964 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Perf_Section = 'perfcheck'"

.PP
Definition at line 5961 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Perf_TestData_Float = 'perfTestData'"

.PP
Definition at line 5965 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Power_AutoLaunchSteamVROnButtonPress = 'autoLaunchSteamVROnButtonPress'"

.PP
Definition at line 6000 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Power_PauseCompositorOnStandby_Bool = 'pauseCompositorOnStandby'"

.PP
Definition at line 6001 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Power_PowerOffOnExit_Bool = 'powerOffOnExit'"

.PP
Definition at line 5996 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Power_ReturnToWatchdogTimeout_Float = 'returnToWatchdogTimeout'"

.PP
Definition at line 5999 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Power_Section = 'power'"

.PP
Definition at line 5995 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Power_TurnOffControllersTimeout_Float = 'turnOffControllersTimeout'"

.PP
Definition at line 5998 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Power_TurnOffScreensTimeout_Float = 'turnOffScreensTimeout'"

.PP
Definition at line 5997 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_ActivateMultipleDrivers_Bool = 'activateMultipleDrivers'"

.PP
Definition at line 5881 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_AllowDisplayLockedMode_Bool = 'allowDisplayLockedMode'"

.PP
Definition at line 5906 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_AllowSupersampleFiltering_Bool = 'allowSupersampleFiltering'"

.PP
Definition at line 5903 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_Background_String = 'background'"

.PP
Definition at line 5874 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_BackgroundCameraHeight_Float = 'backgroundCameraHeight'"

.PP
Definition at line 5876 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_BackgroundDomeRadius_Float = 'backgroundDomeRadius'"

.PP
Definition at line 5877 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_BackgroundUseDomeProjection_Bool = 'backgroundUseDomeProjection'"

.PP
Definition at line 5875 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_BaseStationPowerManagement_Bool = 'basestationPowerManagement'"

.PP
Definition at line 5884 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_CycleBackgroundImageTimeSec_Int32 = 'CycleBackgroundImageTimeSec'"

.PP
Definition at line 5900 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_DebugInput = 'debugInput'"

.PP
Definition at line 5909 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_DebugInputBinding = 'debugInputBinding'"

.PP
Definition at line 5910 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_DebugProcessPipe_String = 'debugProcessPipe'"

.PP
Definition at line 5868 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_DefaultMirrorView_Int32 = 'mirrorView'"

.PP
Definition at line 5891 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_DisplayDebug_Bool = 'displayDebug'"

.PP
Definition at line 5867 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_DisplayDebugX_Int32 = 'displayDebugX'"

.PP
Definition at line 5869 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_DisplayDebugY_Int32 = 'displayDebugY'"

.PP
Definition at line 5870 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_EnableHomeApp = 'enableHomeApp'"

.PP
Definition at line 5899 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_EnableLinuxVulkanAsync_Bool = 'enableLinuxVulkanAsync'"

.PP
Definition at line 5905 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_EnableSafeMode = 'enableSafeMode'"

.PP
Definition at line 5914 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_EnableSharedResourceJournaling = 'enableSharedResourceJournaling'"

.PP
Definition at line 5913 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_ForcedDriverKey_String = 'forcedDriver'"

.PP
Definition at line 5865 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_ForcedHmdKey_String = 'forcedHmd'"

.PP
Definition at line 5866 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_ForceFadeOnBadTracking_Bool = 'forceFadeOnBadTracking'"

.PP
Definition at line 5890 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_ForceWindows32bitVRMonitor = 'forceWindows32BitVRMonitor'"

.PP
Definition at line 5908 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_GridColor_String = 'gridColor'"

.PP
Definition at line 5878 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_HaveStartedTutorialForNativeChaperoneDriver_Bool = 'haveStartedTutorialForNativeChaperoneDriver'"

.PP
Definition at line 5907 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_InputBindingUIBlock = 'inputBindingUI'"

.PP
Definition at line 5911 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_IPD_Float = 'ipd'"

.PP
Definition at line 5873 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_IpdOffset_Float = 'ipdOffset'"

.PP
Definition at line 5902 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_LastVersionNotice = 'lastVersionNotice'"

.PP
Definition at line 5916 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_LastVersionNoticeDate = 'lastVersionNoticeDate'"

.PP
Definition at line 5917 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_LogLevel_Int32 = 'loglevel'"

.PP
Definition at line 5872 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_MaxRecommendedResolution_Int32 = 'maxRecommendedResolution'"

.PP
Definition at line 5887 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_MirrorViewGeometry_String = 'mirrorViewGeometry'"

.PP
Definition at line 5893 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_MirrorViewGeometryMaximized_String = 'mirrorViewGeometryMaximized'"

.PP
Definition at line 5894 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_MotionSmoothing_Bool = 'motionSmoothing'"

.PP
Definition at line 5888 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_MotionSmoothingOverride_Int32 = 'motionSmoothingOverride'"

.PP
Definition at line 5889 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_NeverKillProcesses_Bool = 'neverKillProcesses'"

.PP
Definition at line 5885 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_PlayAreaColor_String = 'playAreaColor'"

.PP
Definition at line 5879 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_PreferredRefreshRate = 'preferredRefreshRate'"

.PP
Definition at line 5915 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_RenderCameraMode = 'renderCameraMode'"

.PP
Definition at line 5912 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_RequireHmd_String = 'requireHmd'"

.PP
Definition at line 5864 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_RetailDemo_Bool = 'retailDemo'"

.PP
Definition at line 5901 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_Section = 'steamvr'"

.PP
Definition at line 5863 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_SendSystemButtonToAllApps_Bool = 'sendSystemButtonToAllApps'"

.PP
Definition at line 5871 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_ShowMirrorView_Bool = 'showMirrorView'"

.PP
Definition at line 5892 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_ShowStage_Bool = 'showStage'"

.PP
Definition at line 5880 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_SpeakersForwardYawOffsetDegrees_Float = 'speakersForwardYawOffsetDegrees'"

.PP
Definition at line 5883 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_StartCompositorFromAppLaunch_Bool = 'startCompositorFromAppLaunch'"

.PP
Definition at line 5896 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_StartDashboardFromAppLaunch_Bool = 'startDashboardFromAppLaunch'"

.PP
Definition at line 5897 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_StartMonitorFromAppLaunch = 'startMonitorFromAppLaunch'"

.PP
Definition at line 5895 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_StartOverlayAppsFromDashboard_Bool = 'startOverlayAppsFromDashboard'"

.PP
Definition at line 5898 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_SupersampleManualOverride_Bool = 'supersampleManualOverride'"

.PP
Definition at line 5904 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_SupersampleScale_Float = 'supersampleScale'"

.PP
Definition at line 5886 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_SteamVR_UsingSpeakers_Bool = 'usingSpeakers'"

.PP
Definition at line 5882 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_Trackers_Section = 'trackers'"

.PP
Definition at line 6020 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_TrackingOverride_Section = 'TrackingOverrides'"

.PP
Definition at line 6016 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_UserInterface_HidePopupsWhenStatusMinimized_Bool = 'HidePopupsWhenStatusMinimized'"

.PP
Definition at line 5948 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_UserInterface_MinimizeToTray_Bool = 'MinimizeToTray'"

.PP
Definition at line 5947 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_UserInterface_Screenshots_Bool = 'screenshots'"

.PP
Definition at line 5949 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_UserInterface_ScreenshotType_Int = 'screenshotType'"

.PP
Definition at line 5950 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_UserInterface_Section = 'userinterface'"

.PP
Definition at line 5945 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_UserInterface_StatusAlwaysOnTop_Bool = 'StatusAlwaysOnTop'"

.PP
Definition at line 5946 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_VRWebHelper_DebuggerEnabled_Bool = 'DebuggerEnabled'"

.PP
Definition at line 6014 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_VRWebHelper_DebuggerPort_Int32 = 'DebuggerPort'"

.PP
Definition at line 6015 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_VRWebHelper_Section = 'VRWebHelper'"

.PP
Definition at line 6013 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_WebInterface_Section = 'WebInterface'"

.PP
Definition at line 6010 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_WebInterface_WebEnable_Bool = 'WebEnable'"

.PP
Definition at line 6011 of file openvr_api\&.cs\&.
.SS "const string Valve\&.VR\&.OpenVR\&.k_pch_WebInterface_WebPort_String = 'WebPort'"

.PP
Definition at line 6012 of file openvr_api\&.cs\&.
.SS "const ulong Valve\&.VR\&.OpenVR\&.k_ulInvalidActionHandle = 0"

.PP
Definition at line 5831 of file openvr_api\&.cs\&.
.SS "const ulong Valve\&.VR\&.OpenVR\&.k_ulInvalidActionSetHandle = 0"

.PP
Definition at line 5832 of file openvr_api\&.cs\&.
.SS "const ulong Valve\&.VR\&.OpenVR\&.k_ulInvalidDriverHandle = 0"

.PP
Definition at line 5806 of file openvr_api\&.cs\&.
.SS "const ulong Valve\&.VR\&.OpenVR\&.k_ulInvalidInputValueHandle = 0"

.PP
Definition at line 5833 of file openvr_api\&.cs\&.
.SS "const ulong Valve\&.VR\&.OpenVR\&.k_ulInvalidIOBufferHandle = 0"

.PP
Definition at line 6034 of file openvr_api\&.cs\&.
.SS "const ulong Valve\&.VR\&.OpenVR\&.k_ulInvalidPropertyContainer = 0"

.PP
Definition at line 5804 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_ulInvalidSpatialAnchorHandle = 0"

.PP
Definition at line 6036 of file openvr_api\&.cs\&.
.SS "const ulong Valve\&.VR\&.OpenVR\&.k_ulOverlayHandleInvalid = 0"

.PP
Definition at line 5835 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unActionPropertyTag = 32"

.PP
Definition at line 5820 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unActiveActionSetPropertyTag = 42"

.PP
Definition at line 5827 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unBoolPropertyTag = 4"

.PP
Definition at line 5810 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unControllerStateAxisCount = 5"

.PP
Definition at line 5834 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unFloatPropertyTag = 1"

.PP
Definition at line 5807 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unHapticVibrationPropertyTag = 35"

.PP
Definition at line 5823 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unHiddenAreaPropertyTag = 30"

.PP
Definition at line 5818 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unHmdMatrix34PropertyTag = 20"

.PP
Definition at line 5812 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unHmdMatrix44PropertyTag = 21"

.PP
Definition at line 5813 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unHmdQuadPropertyTag = 25"

.PP
Definition at line 5817 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unHmdVector2PropertyTag = 24"

.PP
Definition at line 5816 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unHmdVector3PropertyTag = 22"

.PP
Definition at line 5814 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unHmdVector4PropertyTag = 23"

.PP
Definition at line 5815 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unInputValuePropertyTag = 33"

.PP
Definition at line 5821 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unInt32PropertyTag = 2"

.PP
Definition at line 5808 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unInvalidPropertyTag = 0"

.PP
Definition at line 5805 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unJsonPropertyTag = 41"

.PP
Definition at line 5826 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxActionNameLength = 64"

.PP
Definition at line 6029 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxActionOriginCount = 16"

.PP
Definition at line 6031 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxActionSetNameLength = 64"

.PP
Definition at line 6030 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxApplicationKeyLength = 128"

.PP
Definition at line 5841 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxBoneNameLength = 32"

.PP
Definition at line 6032 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxDistortionFunctionParameters = 8"

.PP
Definition at line 5836 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxDriverDebugResponseSize = 32768"

.PP
Definition at line 5799 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxOverlayCount = 64"

.PP
Definition at line 5850 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxOverlayIntersectionMaskPrimitivesCount = 32"

.PP
Definition at line 5851 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxPropertyStringSize = 32768"

.PP
Definition at line 5830 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxSettingsKeyLength = 128"

.PP
Definition at line 5861 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unMaxTrackedDeviceCount = 64"

.PP
Definition at line 5801 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unNotificationTextMaxSize = 256"

.PP
Definition at line 5859 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unOpenVRInternalReserved_End = 10000"

.PP
Definition at line 5829 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unOpenVRInternalReserved_Start = 1000"

.PP
Definition at line 5828 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unPathHandleInfoTag = 31"

.PP
Definition at line 5819 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unScreenshotHandleInvalid = 0"

.PP
Definition at line 5837 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unSkeletonPropertyTag = 36"

.PP
Definition at line 5824 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unSpatialAnchorPosePropertyTag = 40"

.PP
Definition at line 5825 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unStringPropertyTag = 5"

.PP
Definition at line 5811 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unTrackedDeviceIndex_Hmd = 0"

.PP
Definition at line 5800 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unTrackedDeviceIndexInvalid = 4294967295"

.PP
Definition at line 5803 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unTrackedDeviceIndexOther = 4294967294"

.PP
Definition at line 5802 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unUint64PropertyTag = 3"

.PP
Definition at line 5809 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unVROverlayMaxKeyLength = 128"

.PP
Definition at line 5848 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unVROverlayMaxNameLength = 128"

.PP
Definition at line 5849 of file openvr_api\&.cs\&.
.SS "const uint Valve\&.VR\&.OpenVR\&.k_unWildcardPropertyTag = 34"

.PP
Definition at line 5822 of file openvr_api\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBCVRApplications\fP Valve\&.VR\&.OpenVR\&.Applications\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6276 of file openvr_api\&.cs\&.
.SS "\fBCVRChaperone\fP Valve\&.VR\&.OpenVR\&.Chaperone\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6269 of file openvr_api\&.cs\&.
.SS "\fBCVRChaperoneSetup\fP Valve\&.VR\&.OpenVR\&.ChaperoneSetup\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6270 of file openvr_api\&.cs\&.
.SS "\fBCVRCompositor\fP Valve\&.VR\&.OpenVR\&.Compositor\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6271 of file openvr_api\&.cs\&.
.SS "\fBCVRExtendedDisplay\fP Valve\&.VR\&.OpenVR\&.ExtendedDisplay\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6274 of file openvr_api\&.cs\&.
.SS "\fBCVRInput\fP Valve\&.VR\&.OpenVR\&.Input\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6279 of file openvr_api\&.cs\&.
.SS "\fBCVROverlay\fP Valve\&.VR\&.OpenVR\&.Overlay\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6272 of file openvr_api\&.cs\&.
.SS "\fBCVRRenderModels\fP Valve\&.VR\&.OpenVR\&.RenderModels\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6273 of file openvr_api\&.cs\&.
.SS "\fBCVRScreenshots\fP Valve\&.VR\&.OpenVR\&.Screenshots\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6277 of file openvr_api\&.cs\&.
.SS "\fBCVRSettings\fP Valve\&.VR\&.OpenVR\&.Settings\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6275 of file openvr_api\&.cs\&.
.SS "\fBCVRSpatialAnchors\fP Valve\&.VR\&.OpenVR\&.SpatialAnchors\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6280 of file openvr_api\&.cs\&.
.SS "\fBCVRSystem\fP Valve\&.VR\&.OpenVR\&.System\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6268 of file openvr_api\&.cs\&.
.SS "\fBCVRTrackedCamera\fP Valve\&.VR\&.OpenVR\&.TrackedCamera\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 6278 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
