.TH "Valve.VR.SteamVR_Behaviour_Single" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Behaviour_Single \- \fBSteamVR_Behaviour_Single\fP simplifies the use of single actions\&. It gives an event to subscribe to for when the action has changed\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetLocalizedName\fP (params \fBEVRInputStringBits\fP[] localizedParts)"
.br
.RI "Gets the localized name of the device that the action corresponds to\&. "
.ti -1c
.RI "delegate void \fBAxisHandler\fP (\fBSteamVR_Behaviour_Single\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, float newAxis, float newDelta)"
.br
.ti -1c
.RI "delegate void \fBChangeHandler\fP (\fBSteamVR_Behaviour_Single\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, float newAxis, float newDelta)"
.br
.ti -1c
.RI "delegate void \fBUpdateHandler\fP (\fBSteamVR_Behaviour_Single\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, float newAxis, float newDelta)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_Action_Single\fP \fBsingleAction\fP"
.br
.RI "The single action to get data from\&. "
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBinputSource\fP"
.br
.RI "The device this action applies to\&. Any if the action is not device specific\&. "
.ti -1c
.RI "\fBSteamVR_Behaviour_SingleEvent\fP \fBonChange\fP"
.br
.RI "Unity event that Fires whenever the action's value has changed since the last update\&. "
.ti -1c
.RI "\fBSteamVR_Behaviour_SingleEvent\fP \fBonUpdate\fP"
.br
.RI "Unity event that Fires whenever the action's value has been updated "
.ti -1c
.RI "\fBSteamVR_Behaviour_SingleEvent\fP \fBonAxis\fP"
.br
.RI "Unity event that Fires whenever the action's value has been updated and is non-zero "
.ti -1c
.RI "\fBChangeHandler\fP \fBonChangeEvent\fP"
.br
.RI "C# event that fires whenever the action's value has changed since the last update\&. "
.ti -1c
.RI "\fBUpdateHandler\fP \fBonUpdateEvent\fP"
.br
.RI "C# event that fires whenever the action's value has been updated "
.ti -1c
.RI "\fBAxisHandler\fP \fBonAxisEvent\fP"
.br
.RI "C# event that fires whenever the action's value has been updated and is non-zero "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBAddHandlers\fP ()"
.br
.ti -1c
.RI "void \fBRemoveHandlers\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBisActive\fP\fC [get]\fP"
.br
.RI "Returns whether this action is bound and the action set is active "
.in -1c
.SH "Detailed Description"
.PP 
\fBSteamVR_Behaviour_Single\fP simplifies the use of single actions\&. It gives an event to subscribe to for when the action has changed\&. 


.PP
Definition at line 17 of file SteamVR_Behaviour_Single\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Behaviour_Single\&.AddHandlers ()\fC [protected]\fP"

.PP
Definition at line 66 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "delegate void Valve\&.VR\&.SteamVR_Behaviour_Single\&.AxisHandler (\fBSteamVR_Behaviour_Single\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, float newAxis, float newDelta)"

.SS "delegate void Valve\&.VR\&.SteamVR_Behaviour_Single\&.ChangeHandler (\fBSteamVR_Behaviour_Single\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, float newAxis, float newDelta)"

.SS "string Valve\&.VR\&.SteamVR_Behaviour_Single\&.GetLocalizedName (params \fBEVRInputStringBits\fP [] localizedParts)"

.PP
Gets the localized name of the device that the action corresponds to\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlocalizedParts\fP 
.PD 0

.IP "\(bu" 2
VRInputString_Hand - Which hand the origin is in\&. E\&.g\&. 'Left Hand' 
.IP "\(bu" 2
VRInputString_ControllerType - What kind of controller the user has in that hand\&.E\&.g\&. 'Vive Controller' 
.IP "\(bu" 2
VRInputString_InputSource - What part of that controller is the origin\&. E\&.g\&. 'Trackpad' 
.IP "\(bu" 2
VRInputString_All - All of the above\&. E\&.g\&. 'Left Hand Vive Controller Trackpad' 
.PP
.RE
.PP

.PP
Definition at line 134 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "virtual void Valve\&.VR\&.SteamVR_Behaviour_Single\&.OnDisable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 61 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "virtual void Valve\&.VR\&.SteamVR_Behaviour_Single\&.OnEnable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 50 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Behaviour_Single\&.RemoveHandlers ()\fC [protected]\fP"

.PP
Definition at line 73 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "delegate void Valve\&.VR\&.SteamVR_Behaviour_Single\&.UpdateHandler (\fBSteamVR_Behaviour_Single\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, float newAxis, float newDelta)"

.SH "Member Data Documentation"
.PP 
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.SteamVR_Behaviour_Single\&.inputSource"

.PP
The device this action applies to\&. Any if the action is not device specific\&. 
.PP
Definition at line 24 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "\fBSteamVR_Behaviour_SingleEvent\fP Valve\&.VR\&.SteamVR_Behaviour_Single\&.onAxis"

.PP
Unity event that Fires whenever the action's value has been updated and is non-zero 
.PP
Definition at line 36 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "\fBAxisHandler\fP Valve\&.VR\&.SteamVR_Behaviour_Single\&.onAxisEvent"

.PP
C# event that fires whenever the action's value has been updated and is non-zero 
.PP
Definition at line 45 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "\fBSteamVR_Behaviour_SingleEvent\fP Valve\&.VR\&.SteamVR_Behaviour_Single\&.onChange"

.PP
Unity event that Fires whenever the action's value has changed since the last update\&. 
.PP
Definition at line 28 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "\fBChangeHandler\fP Valve\&.VR\&.SteamVR_Behaviour_Single\&.onChangeEvent"

.PP
C# event that fires whenever the action's value has changed since the last update\&. 
.PP
Definition at line 39 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "\fBSteamVR_Behaviour_SingleEvent\fP Valve\&.VR\&.SteamVR_Behaviour_Single\&.onUpdate"

.PP
Unity event that Fires whenever the action's value has been updated 
.PP
Definition at line 32 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "\fBUpdateHandler\fP Valve\&.VR\&.SteamVR_Behaviour_Single\&.onUpdateEvent"

.PP
C# event that fires whenever the action's value has been updated 
.PP
Definition at line 42 of file SteamVR_Behaviour_Single\&.cs\&.
.SS "\fBSteamVR_Action_Single\fP Valve\&.VR\&.SteamVR_Behaviour_Single\&.singleAction"

.PP
The single action to get data from\&. 
.PP
Definition at line 20 of file SteamVR_Behaviour_Single\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_Behaviour_Single\&.isActive\fC [get]\fP"

.PP
Returns whether this action is bound and the action set is active 
.PP
Definition at line 48 of file SteamVR_Behaviour_Single\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
