.TH "Valve.VR.InteractionSystem.SoundPlayOneshot" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.SoundPlayOneshot
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPlay\fP ()"
.br
.ti -1c
.RI "void \fBPause\fP ()"
.br
.ti -1c
.RI "void \fBUnPause\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AudioClip [] \fBwaveFiles\fP"
.br
.ti -1c
.RI "float \fBvolMin\fP"
.br
.ti -1c
.RI "float \fBvolMax\fP"
.br
.ti -1c
.RI "float \fBpitchMin\fP"
.br
.ti -1c
.RI "float \fBpitchMax\fP"
.br
.ti -1c
.RI "bool \fBplayOnAwake\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file SoundPlayOneshot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.SoundPlayOneshot\&.Pause ()"

.PP
Definition at line 57 of file SoundPlayOneshot\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.SoundPlayOneshot\&.Play ()"

.PP
Definition at line 40 of file SoundPlayOneshot\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.SoundPlayOneshot\&.UnPause ()"

.PP
Definition at line 67 of file SoundPlayOneshot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.InteractionSystem\&.SoundPlayOneshot\&.pitchMax"

.PP
Definition at line 22 of file SoundPlayOneshot\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.SoundPlayOneshot\&.pitchMin"

.PP
Definition at line 21 of file SoundPlayOneshot\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.SoundPlayOneshot\&.playOnAwake"

.PP
Definition at line 24 of file SoundPlayOneshot\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.SoundPlayOneshot\&.volMax"

.PP
Definition at line 19 of file SoundPlayOneshot\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.SoundPlayOneshot\&.volMin"

.PP
Definition at line 18 of file SoundPlayOneshot\&.cs\&.
.SS "AudioClip [] Valve\&.VR\&.InteractionSystem\&.SoundPlayOneshot\&.waveFiles"

.PP
Definition at line 15 of file SoundPlayOneshot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
