.TH "Valve.VR.SteamVR_Action_Pose_Source_Map< Source >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Action_Pose_Source_Map< Source > \- Boolean actions are either true or false\&. There is an onStateUp and onStateDown event for the rising and falling edge\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_Action_In_Source_Map< Source >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetTrackingUniverseOrigin\fP (\fBETrackingUniverseOrigin\fP newOrigin)"
.br
.RI "Sets all pose (and skeleton) actions to use the specified universe origin without going through the sourcemap indexer "
.ti -1c
.RI "virtual void \fBUpdateValues\fP (bool skipStateAndEventUpdates)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Boolean actions are either true or false\&. There is an onStateUp and onStateDown event for the rising and falling edge\&. 


.PP
\fBType Constraints\fP
.TP
\fISource\fP : \fI\fBSteamVR_Action_Pose_Source\fP\fP
.TP
\fISource\fP : \fInew()\fP
.PP
Definition at line 383 of file SteamVR_Action_Pose\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBValve\&.VR\&.SteamVR_Action_Pose_Source_Map\fP< Source >\&.SetTrackingUniverseOrigin (\fBETrackingUniverseOrigin\fP newOrigin)"

.PP
Sets all pose (and skeleton) actions to use the specified universe origin without going through the sourcemap indexer 
.PP
Definition at line 389 of file SteamVR_Action_Pose\&.cs\&.
.SS "virtual void \fBValve\&.VR\&.SteamVR_Action_Pose_Source_Map\fP< Source >\&.UpdateValues (bool skipStateAndEventUpdates)\fC [virtual]\fP"

.PP
Definition at line 399 of file SteamVR_Action_Pose\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
