.TH "Valve.VR.SteamVR_Skeleton_Poser.PoseBlendingBehaviour" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Skeleton_Poser.PoseBlendingBehaviour \- A filter applied to the base pose\&. Blends to a secondary pose by a certain weight\&. Can be masked per-finger  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBBlenderTypes\fP { \fBBlenderTypes\&.Manual\fP, \fBBlenderTypes\&.AnalogAction\fP, \fBBlenderTypes\&.BooleanAction\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP (float deltaTime, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Performs smoothing based on deltaTime parameter\&. "
.ti -1c
.RI "void \fBApplyBlending\fP (\fBSteamVR_Skeleton_PoseSnapshot\fP snapshot, \fBSkeletonBlendablePose\fP[] blendPoses, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Apply blending to this behaviour's pose to an existing snapshot\&. "
.ti -1c
.RI "\fBPoseBlendingBehaviour\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP = true"
.br
.ti -1c
.RI "float \fBinfluence\fP = 1"
.br
.ti -1c
.RI "int \fBpose\fP = 1"
.br
.ti -1c
.RI "float \fBvalue\fP = 0"
.br
.ti -1c
.RI "\fBSteamVR_Action_Single\fP \fBaction_single\fP"
.br
.ti -1c
.RI "\fBSteamVR_Action_Boolean\fP \fBaction_bool\fP"
.br
.ti -1c
.RI "float \fBsmoothingSpeed\fP = 0"
.br
.ti -1c
.RI "\fBBlenderTypes\fP \fBtype\fP"
.br
.ti -1c
.RI "bool \fBuseMask\fP"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_HandMask\fP \fBmask\fP = new \fBSteamVR_Skeleton_HandMask\fP()"
.br
.ti -1c
.RI "bool \fBpreviewEnabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A filter applied to the base pose\&. Blends to a secondary pose by a certain weight\&. Can be masked per-finger 


.PP
Definition at line 355 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.BlenderTypes\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIManual \fP\fP
.TP
\fB\fIAnalogAction \fP\fP
.TP
\fB\fIBooleanAction \fP\fP
.PP
Definition at line 424 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.PoseBlendingBehaviour ()"

.PP
Definition at line 418 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.ApplyBlending (\fBSteamVR_Skeleton_PoseSnapshot\fP snapshot, \fBSkeletonBlendablePose\fP [] blendPoses, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Apply blending to this behaviour's pose to an existing snapshot\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsnapshot\fP Snapshot to modify
.br
\fIblendPoses\fP List of blend poses to get the target pose
.br
\fIinputSource\fP Which hand to receive input from
.RE
.PP

.PP
Definition at line 398 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.Update (float deltaTime, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Performs smoothing based on deltaTime parameter\&. 
.PP
Definition at line 374 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSteamVR_Action_Boolean\fP Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.action_bool"

.PP
Definition at line 363 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "\fBSteamVR_Action_Single\fP Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.action_single"

.PP
Definition at line 362 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.enabled = true"

.PP
Definition at line 358 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.influence = 1"

.PP
Definition at line 359 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "\fBSteamVR_Skeleton_HandMask\fP Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.mask = new \fBSteamVR_Skeleton_HandMask\fP()"

.PP
Definition at line 367 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.name"

.PP
Definition at line 357 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "int Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.pose = 1"

.PP
Definition at line 360 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.previewEnabled"

.PP
Definition at line 369 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.smoothingSpeed = 0"

.PP
Definition at line 364 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "\fBBlenderTypes\fP Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.type"

.PP
Definition at line 365 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.useMask"

.PP
Definition at line 366 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Skeleton_Poser\&.PoseBlendingBehaviour\&.value = 0"

.PP
Definition at line 361 of file SteamVR_Skeleton_Poser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
