.TH "Valve.VR.InteractionSystem.Sample.SquishyToy" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Sample.SquishyToy
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInteractable\fP \fBinteractable\fP"
.br
.ti -1c
.RI "new SkinnedMeshRenderer \fBrenderer\fP"
.br
.ti -1c
.RI "bool \fBaffectMaterial\fP = true"
.br
.ti -1c
.RI "\fBSteamVR_Action_Single\fP \fBgripSqueeze\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Single\fP>('Squeeze')"
.br
.ti -1c
.RI "\fBSteamVR_Action_Single\fP \fBpinchSqueeze\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Single\fP>('Squeeze')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file SquishyToy\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.Sample\&.SquishyToy\&.affectMaterial = true"

.PP
Definition at line 14 of file SquishyToy\&.cs\&.
.SS "\fBSteamVR_Action_Single\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.SquishyToy\&.gripSqueeze = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Single\fP>('Squeeze')"

.PP
Definition at line 16 of file SquishyToy\&.cs\&.
.SS "\fBInteractable\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.SquishyToy\&.interactable"

.PP
Definition at line 11 of file SquishyToy\&.cs\&.
.SS "\fBSteamVR_Action_Single\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.SquishyToy\&.pinchSqueeze = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Single\fP>('Squeeze')"

.PP
Definition at line 18 of file SquishyToy\&.cs\&.
.SS "new SkinnedMeshRenderer Valve\&.VR\&.InteractionSystem\&.Sample\&.SquishyToy\&.renderer"

.PP
Definition at line 12 of file SquishyToy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
