.TH "Valve.VR.InteractionSystem.Sample.ProceduralHats" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Sample.ProceduralHats
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject [] \fBhats\fP"
.br
.ti -1c
.RI "float \fBhatSwitchTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ProceduralHats\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject [] Valve\&.VR\&.InteractionSystem\&.Sample\&.ProceduralHats\&.hats"

.PP
Definition at line 9 of file ProceduralHats\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Sample\&.ProceduralHats\&.hatSwitchTime"

.PP
Definition at line 11 of file ProceduralHats\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
