.TH "Valve.VR.InteractionSystem.PlaySound" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.PlaySound
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPlay\fP ()"
.br
.ti -1c
.RI "void \fBPlayWithDelay\fP (float delayTime)"
.br
.ti -1c
.RI "AudioClip \fBPlayOneShotSound\fP ()"
.br
.ti -1c
.RI "AudioClip \fBPlayLooping\fP ()"
.br
.ti -1c
.RI "void \fBDisable\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AudioClip [] \fBwaveFile\fP"
.br
.ti -1c
.RI "bool \fBstopOnPlay\fP"
.br
.ti -1c
.RI "bool \fBdisableOnEnd\fP"
.br
.ti -1c
.RI "bool \fBlooping\fP"
.br
.ti -1c
.RI "bool \fBstopOnEnd\fP"
.br
.ti -1c
.RI "bool \fBplayOnAwakeWithDelay\fP"
.br
.ti -1c
.RI "bool \fBuseRandomVolume\fP = true"
.br
.ti -1c
.RI "float \fBvolMin\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBvolMax\fP = 1\&.0f"
.br
.ti -1c
.RI "bool \fBuseRandomPitch\fP = true"
.br
.ti -1c
.RI "float \fBpitchMin\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBpitchMax\fP = 1\&.0f"
.br
.ti -1c
.RI "bool \fBuseRetriggerTime\fP = false"
.br
.ti -1c
.RI "float \fBtimeInitial\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBtimeMin\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBtimeMax\fP = 0\&.0f"
.br
.ti -1c
.RI "bool \fBuseRandomSilence\fP = false"
.br
.ti -1c
.RI "float \fBpercentToNotPlay\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBdelayOffsetTime\fP = 0\&.0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file PlaySound\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.PlaySound\&.Disable ()"

.PP
Definition at line 175 of file PlaySound\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.PlaySound\&.Play ()"

.PP
Definition at line 114 of file PlaySound\&.cs\&.
.SS "AudioClip Valve\&.VR\&.InteractionSystem\&.PlaySound\&.PlayLooping ()"

.PP
Definition at line 155 of file PlaySound\&.cs\&.
.SS "AudioClip Valve\&.VR\&.InteractionSystem\&.PlaySound\&.PlayOneShotSound ()"

.PP
Definition at line 139 of file PlaySound\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.PlaySound\&.PlayWithDelay (float delayTime)"

.PP
Definition at line 127 of file PlaySound\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.PlaySound\&.Stop ()"

.PP
Definition at line 182 of file PlaySound\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.InteractionSystem\&.PlaySound\&.delayOffsetTime = 0\&.0f"

.PP
Definition at line 70 of file PlaySound\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.PlaySound\&.disableOnEnd"

.PP
Definition at line 21 of file PlaySound\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.PlaySound\&.looping"

.PP
Definition at line 23 of file PlaySound\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.PlaySound\&.percentToNotPlay = 0\&.0f"

.PP
Definition at line 66 of file PlaySound\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.PlaySound\&.pitchMax = 1\&.0f"

.PP
Definition at line 46 of file PlaySound\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.PlaySound\&.pitchMin = 1\&.0f"

.PP
Definition at line 43 of file PlaySound\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.PlaySound\&.playOnAwakeWithDelay"

.PP
Definition at line 27 of file PlaySound\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.PlaySound\&.stopOnEnd"

.PP
Definition at line 25 of file PlaySound\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.PlaySound\&.stopOnPlay"

.PP
Definition at line 19 of file PlaySound\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.PlaySound\&.timeInitial = 0\&.0f"

.PP
Definition at line 53 of file PlaySound\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.PlaySound\&.timeMax = 0\&.0f"

.PP
Definition at line 59 of file PlaySound\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.PlaySound\&.timeMin = 0\&.0f"

.PP
Definition at line 56 of file PlaySound\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.PlaySound\&.useRandomPitch = true"

.PP
Definition at line 40 of file PlaySound\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.PlaySound\&.useRandomSilence = false"

.PP
Definition at line 63 of file PlaySound\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.PlaySound\&.useRandomVolume = true"

.PP
Definition at line 30 of file PlaySound\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.PlaySound\&.useRetriggerTime = false"

.PP
Definition at line 50 of file PlaySound\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.PlaySound\&.volMax = 1\&.0f"

.PP
Definition at line 36 of file PlaySound\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.PlaySound\&.volMin = 1\&.0f"

.PP
Definition at line 33 of file PlaySound\&.cs\&.
.SS "AudioClip [] Valve\&.VR\&.InteractionSystem\&.PlaySound\&.waveFile"

.PP
Definition at line 17 of file PlaySound\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
