.TH "Valve.VR.InteractionSystem.InteractableDebug" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.InteractableDebug
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Collider [] \fBGetColliders\fP ()"
.br
.ti -1c
.RI "void \fBIgnoreObject\fP (\fBInteractableDebug\fP otherInteractable)"
.br
.ti -1c
.RI "void \fBSetIsSimulation\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHand\fP \fBattachedToHand\fP"
.br
.ti -1c
.RI "float \fBsimulateReleasesForXSecondsAroundRelease\fP = 0"
.br
.ti -1c
.RI "float \fBsimulateReleasesEveryXSeconds\fP = 0\&.005f"
.br
.ti -1c
.RI "bool \fBsetPositionsForSimulations\fP = false"
.br
.ti -1c
.RI "new Rigidbody \fBrigidbody\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBHandAttachedUpdate\fP (\fBHand\fP hand)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file InteractableDebug\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Collider [] Valve\&.VR\&.InteractionSystem\&.InteractableDebug\&.GetColliders ()"

.PP
Definition at line 123 of file InteractableDebug\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.InteractableDebug\&.HandAttachedUpdate (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 53 of file InteractableDebug\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.InteractableDebug\&.IgnoreObject (\fBInteractableDebug\fP otherInteractable)"

.PP
Definition at line 128 of file InteractableDebug\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.InteractableDebug\&.SetIsSimulation ()"

.PP
Definition at line 142 of file InteractableDebug\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHand\fP Valve\&.VR\&.InteractionSystem\&.InteractableDebug\&.attachedToHand"

.PP
Definition at line 18 of file InteractableDebug\&.cs\&.
.SS "new Rigidbody Valve\&.VR\&.InteractionSystem\&.InteractableDebug\&.rigidbody"

.PP
Definition at line 35 of file InteractableDebug\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.InteractableDebug\&.setPositionsForSimulations = false"

.PP
Definition at line 22 of file InteractableDebug\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.InteractableDebug\&.simulateReleasesEveryXSeconds = 0\&.005f"

.PP
Definition at line 21 of file InteractableDebug\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.InteractableDebug\&.simulateReleasesForXSecondsAroundRelease = 0"

.PP
Definition at line 20 of file InteractableDebug\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
