.TH "Valve.VR.SteamVR_RenderModel.RenderModelInterfaceHolder" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_RenderModel.RenderModelInterfaceHolder
.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBCVRRenderModels\fP \fBinstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file SteamVR_RenderModel\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_RenderModel\&.RenderModelInterfaceHolder\&.Dispose ()"

.PP
Definition at line 102 of file SteamVR_RenderModel\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBCVRRenderModels\fP Valve\&.VR\&.SteamVR_RenderModel\&.RenderModelInterfaceHolder\&.instance\fC [get]\fP"

.PP
Definition at line 84 of file SteamVR_RenderModel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
