.TH "Valve.VR.InteractionSystem" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSample\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAfterTimer_Component\fP"
.br
.ti -1c
.RI "class \fBAllowTeleportWhileAttachedToHand\fP"
.br
.ti -1c
.RI "class \fBArcheryTarget\fP"
.br
.ti -1c
.RI "class \fBArrow\fP"
.br
.ti -1c
.RI "class \fBArrowHand\fP"
.br
.ti -1c
.RI "class \fBArrowheadRotation\fP"
.br
.ti -1c
.RI "class \fBBalloon\fP"
.br
.ti -1c
.RI "class \fBBalloonColliders\fP"
.br
.ti -1c
.RI "class \fBBalloonHapticBump\fP"
.br
.ti -1c
.RI "class \fBBalloonSpawner\fP"
.br
.ti -1c
.RI "class \fBBodyCollider\fP"
.br
.ti -1c
.RI "class \fBChaperoneInfo\fP"
.br
.ti -1c
.RI "class \fBCircularDrive\fP"
.br
.ti -1c
.RI "class \fBComplexThrowable\fP"
.br
.ti -1c
.RI "class \fBControllerButtonHints\fP"
.br
.ti -1c
.RI "class \fBControllerHoverHighlight\fP"
.br
.ti -1c
.RI "class \fBCustomEvents\fP"
.br
.ti -1c
.RI "class \fBDebugUI\fP"
.br
.ti -1c
.RI "class \fBDestroyOnDetachedFromHand\fP"
.br
.ti -1c
.RI "class \fBDestroyOnParticleSystemDeath\fP"
.br
.ti -1c
.RI "class \fBDestroyOnTriggerEnter\fP"
.br
.ti -1c
.RI "class \fBDistanceHaptics\fP"
.br
.ti -1c
.RI "class \fBDontDestroyOnLoad\fP"
.br
.ti -1c
.RI "class \fBEnumFlags\fP"
.br
.ti -1c
.RI "class \fBEquippable\fP"
.br
.ti -1c
.RI "class \fBExplosionWobble\fP"
.br
.ti -1c
.RI "class \fBFallbackCameraController\fP"
.br
.ti -1c
.RI "class \fBFireSource\fP"
.br
.ti -1c
.RI "class \fBHand\fP"
.br
.ti -1c
.RI "class \fBHandEvent\fP"
.br
.ti -1c
.RI "class \fBHapticRack\fP"
.br
.ti -1c
.RI "class \fBHideOnHandFocusLost\fP"
.br
.ti -1c
.RI "class \fBHoverButton\fP"
.br
.ti -1c
.RI "class \fBIgnoreHovering\fP"
.br
.ti -1c
.RI "class \fBIgnoreTeleportTrace\fP"
.br
.ti -1c
.RI "class \fBInputModule\fP"
.br
.ti -1c
.RI "class \fBInteractable\fP"
.br
.ti -1c
.RI "class \fBInteractableDebug\fP"
.br
.ti -1c
.RI "class \fBInteractableHoverEvents\fP"
.br
.ti -1c
.RI "class \fBItemPackage\fP"
.br
.ti -1c
.RI "class \fBItemPackageReference\fP"
.br
.ti -1c
.RI "class \fBItemPackageSpawner\fP"
.br
.ti -1c
.RI "class \fBLinearAnimation\fP"
.br
.ti -1c
.RI "class \fBLinearAnimator\fP"
.br
.ti -1c
.RI "class \fBLinearAudioPitch\fP"
.br
.ti -1c
.RI "class \fBLinearBlendshape\fP"
.br
.ti -1c
.RI "class \fBLinearDisplacement\fP"
.br
.ti -1c
.RI "class \fBLinearDrive\fP"
.br
.ti -1c
.RI "class \fBLinearMapping\fP"
.br
.ti -1c
.RI "class \fBLongbow\fP"
.br
.ti -1c
.RI "class \fBModalThrowable\fP"
.br
.ti -1c
.RI "class \fBPlayer\fP"
.br
.ti -1c
.RI "class \fBPlaySound\fP"
.br
.ti -1c
.RI "class \fBRenderModel\fP"
.br
.ti -1c
.RI "class \fBSeeThru\fP"
.br
.ti -1c
.RI "class \fBSleepOnAwake\fP"
.br
.ti -1c
.RI "class \fBSoundBowClick\fP"
.br
.ti -1c
.RI "class \fBSoundDeparent\fP"
.br
.ti -1c
.RI "class \fBSoundPlayOneshot\fP"
.br
.ti -1c
.RI "class \fBSpawnAndAttachAfterControllerIsTracking\fP"
.br
.ti -1c
.RI "class \fBSpawnAndAttachToHand\fP"
.br
.ti -1c
.RI "class \fBTeleport\fP"
.br
.ti -1c
.RI "class \fBTeleportArc\fP"
.br
.ti -1c
.RI "class \fBTeleportArea\fP"
.br
.ti -1c
.RI "class \fBTeleportMarkerBase\fP"
.br
.ti -1c
.RI "class \fBTeleportPoint\fP"
.br
.ti -1c
.RI "class \fBThrowable\fP"
.br
.ti -1c
.RI "class \fBUIElement\fP"
.br
.ti -1c
.RI "class \fBUnparent\fP"
.br
.ti -1c
.RI "class \fBUtil\fP"
.br
.ti -1c
.RI "class \fBVelocityEstimator\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBWhichHand\fP { \fBWhichHand\&.Left\fP, \fBWhichHand\&.Right\fP }"
.br
.ti -1c
.RI "enum \fBGrabTypes\fP { \fBGrabTypes\&.None\fP, \fBGrabTypes\&.Trigger\fP, \fBGrabTypes\&.Pinch\fP, \fBGrabTypes\&.Grip\fP, \fBGrabTypes\&.Scripted\fP }"
.br
.ti -1c
.RI "enum \fBReleaseStyle\fP { \fBReleaseStyle\&.NoChange\fP, \fBReleaseStyle\&.GetFromHand\fP, \fBReleaseStyle\&.ShortEstimation\fP, \fBReleaseStyle\&.AdvancedEstimation\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.InteractionSystem\&.GrabTypes\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fITrigger \fP\fP
.TP
\fB\fIPinch \fP\fP
.TP
\fB\fIGrip \fP\fP
.TP
\fB\fIScripted \fP\fP
.PP
Definition at line 10 of file GrabTypes\&.cs\&.
.SS "enum \fBValve\&.VR\&.InteractionSystem\&.ReleaseStyle\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINoChange \fP\fP
.TP
\fB\fIGetFromHand \fP\fP
.TP
\fB\fIShortEstimation \fP\fP
.TP
\fB\fIAdvancedEstimation \fP\fP
.PP
Definition at line 255 of file Throwable\&.cs\&.
.SS "enum \fBValve\&.VR\&.InteractionSystem\&.WhichHand\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILeft \fP\fP
.TP
\fB\fIRight \fP\fP
.PP
Definition at line 14 of file Equippable\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
