.TH "Valve.VR.SteamVR_RenderModel.RenderModel" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_RenderModel.RenderModel
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderModel\fP (Mesh \fBmesh\fP, Material \fBmaterial\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Mesh \fBmesh\fP\fC [get]\fP"
.br
.ti -1c
.RI "Material \fBmaterial\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file SteamVR_RenderModel\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.SteamVR_RenderModel\&.RenderModel\&.RenderModel (Mesh mesh, Material material)"

.PP
Definition at line 66 of file SteamVR_RenderModel\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Material Valve\&.VR\&.SteamVR_RenderModel\&.RenderModel\&.material\fC [get]\fP"

.PP
Definition at line 72 of file SteamVR_RenderModel\&.cs\&.
.SS "Mesh Valve\&.VR\&.SteamVR_RenderModel\&.RenderModel\&.mesh\fC [get]\fP"

.PP
Definition at line 71 of file SteamVR_RenderModel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
