.TH "Valve.VR.InteractionSystem.TeleportArc" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.TeleportArc
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetArcData\fP (Vector3 position, Vector3 velocity, bool gravity, bool pointerAtBadAngle)"
.br
.ti -1c
.RI "void \fBShow\fP ()"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.ti -1c
.RI "bool \fBDrawArc\fP (out RaycastHit hitInfo)"
.br
.ti -1c
.RI "void \fBSetColor\fP (Color color)"
.br
.ti -1c
.RI "Vector3 \fBGetArcPositionAtTime\fP (float time)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsegmentCount\fP = 60"
.br
.ti -1c
.RI "float \fBthickness\fP = 0\&.01f"
.br
.ti -1c
.RI "float \fBarcDuration\fP = 3\&.0f"
.br
.ti -1c
.RI "float \fBsegmentBreak\fP = 0\&.025f"
.br
.ti -1c
.RI "float \fBarcSpeed\fP = 0\&.2f"
.br
.ti -1c
.RI "Material \fBmaterial\fP"
.br
.ti -1c
.RI "int \fBtraceLayerMask\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file TeleportArc\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.DrawArc (out RaycastHit hitInfo)"

.PP
Definition at line 146 of file TeleportArc\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.GetArcPositionAtTime (float time)"

.PP
Definition at line 290 of file TeleportArc\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.Hide ()"

.PP
Definition at line 132 of file TeleportArc\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.SetArcData (Vector3 position, Vector3 velocity, bool gravity, bool pointerAtBadAngle)"

.PP
Definition at line 106 of file TeleportArc\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.SetColor (Color color)"

.PP
Definition at line 242 of file TeleportArc\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.Show ()"

.PP
Definition at line 121 of file TeleportArc\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.arcDuration = 3\&.0f"

.PP
Definition at line 18 of file TeleportArc\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.arcSpeed = 0\&.2f"

.PP
Definition at line 24 of file TeleportArc\&.cs\&.
.SS "Material Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.material"

.PP
Definition at line 26 of file TeleportArc\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.segmentBreak = 0\&.025f"

.PP
Definition at line 21 of file TeleportArc\&.cs\&.
.SS "int Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.segmentCount = 60"

.PP
Definition at line 14 of file TeleportArc\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.thickness = 0\&.01f"

.PP
Definition at line 15 of file TeleportArc\&.cs\&.
.SS "int Valve\&.VR\&.InteractionSystem\&.TeleportArc\&.traceLayerMask = 0"

.PP
Definition at line 29 of file TeleportArc\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
