.TH "Valve.VR.CVRResources" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.CVRResources
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint \fBLoadSharedResource\fP (string pchResourceName, string pchBuffer, uint unBufferLen)"
.br
.ti -1c
.RI "uint \fBGetResourceFullPath\fP (string pchResourceName, string pchResourceTypeDirectory, System\&.Text\&.StringBuilder pchPathBuffer, uint unBufferLen)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3415 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "uint Valve\&.VR\&.CVRResources\&.GetResourceFullPath (string pchResourceName, string pchResourceTypeDirectory, System\&.Text\&.StringBuilder pchPathBuffer, uint unBufferLen)"

.PP
Definition at line 3427 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVRResources\&.LoadSharedResource (string pchResourceName, string pchBuffer, uint unBufferLen)"

.PP
Definition at line 3422 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
