.TH "Valve.VR.SteamVR_LoadLevel" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_LoadLevel
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTrigger\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBBegin\fP (string \fBlevelName\fP, bool \fBshowGrid\fP=false, float \fBfadeOutTime\fP=0\&.5f, float r=0\&.0f, float g=0\&.0f, float b=0\&.0f, float a=1\&.0f)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBlevelName\fP"
.br
.ti -1c
.RI "string \fBinternalProcessPath\fP"
.br
.ti -1c
.RI "string \fBinternalProcessArgs\fP"
.br
.ti -1c
.RI "bool \fBloadAdditive\fP"
.br
.ti -1c
.RI "bool \fBloadAsync\fP = true"
.br
.ti -1c
.RI "Texture \fBloadingScreen\fP"
.br
.ti -1c
.RI "Texture \fBprogressBarEmpty\fP"
.br
.ti -1c
.RI "float \fBloadingScreenWidthInMeters\fP = 6\&.0f"
.br
.ti -1c
.RI "float \fBprogressBarWidthInMeters\fP = 3\&.0f"
.br
.ti -1c
.RI "float \fBloadingScreenDistance\fP = 0\&.0f"
.br
.ti -1c
.RI "Transform \fBloadingScreenTransform\fP"
.br
.ti -1c
.RI "Texture \fBfront\fP"
.br
.ti -1c
.RI "Color \fBbackgroundColor\fP = Color\&.black"
.br
.ti -1c
.RI "bool \fBshowGrid\fP = false"
.br
.ti -1c
.RI "float \fBfadeOutTime\fP = 0\&.5f"
.br
.ti -1c
.RI "float \fBfadeInTime\fP = 0\&.5f"
.br
.ti -1c
.RI "float \fBpostLoadSettleTime\fP = 0\&.0f"
.br
.ti -1c
.RI "float \fBloadingScreenFadeInTime\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBloadingScreenFadeOutTime\fP = 0\&.25f"
.br
.ti -1c
.RI "bool \fBautoTriggerOnEnable\fP = false"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBloading\fP\fC [get]\fP"
.br
.ti -1c
.RI "static float? \fBprogress\fP\fC [get]\fP"
.br
.ti -1c
.RI "static Texture? \fBprogressTexture\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file SteamVR_LoadLevel\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Valve\&.VR\&.SteamVR_LoadLevel\&.Begin (string levelName, bool showGrid = \fCfalse\fP, float fadeOutTime = \fC0\&.5f\fP, float r = \fC0\&.0f\fP, float g = \fC0\&.0f\fP, float b = \fC0\&.0f\fP, float a = \fC1\&.0f\fP)\fC [static]\fP"

.PP
Definition at line 106 of file SteamVR_LoadLevel\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_LoadLevel\&.Trigger ()"

.PP
Definition at line 99 of file SteamVR_LoadLevel\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_LoadLevel\&.autoTriggerOnEnable = false"

.PP
Definition at line 91 of file SteamVR_LoadLevel\&.cs\&.
.SS "Color Valve\&.VR\&.SteamVR_LoadLevel\&.backgroundColor = Color\&.black"

.PP
Definition at line 63 of file SteamVR_LoadLevel\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_LoadLevel\&.fadeInTime = 0\&.5f"

.PP
Definition at line 71 of file SteamVR_LoadLevel\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_LoadLevel\&.fadeOutTime = 0\&.5f"

.PP
Definition at line 70 of file SteamVR_LoadLevel\&.cs\&.
.SS "Texture Valve\&.VR\&.SteamVR_LoadLevel\&.front"

.PP
Definition at line 60 of file SteamVR_LoadLevel\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_LoadLevel\&.internalProcessArgs"

.PP
Definition at line 34 of file SteamVR_LoadLevel\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_LoadLevel\&.internalProcessPath"

.PP
Definition at line 31 of file SteamVR_LoadLevel\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_LoadLevel\&.levelName"

.PP
Definition at line 28 of file SteamVR_LoadLevel\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_LoadLevel\&.loadAdditive"

.PP
Definition at line 37 of file SteamVR_LoadLevel\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_LoadLevel\&.loadAsync = true"

.PP
Definition at line 40 of file SteamVR_LoadLevel\&.cs\&.
.SS "Texture Valve\&.VR\&.SteamVR_LoadLevel\&.loadingScreen"

.PP
Definition at line 43 of file SteamVR_LoadLevel\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_LoadLevel\&.loadingScreenDistance = 0\&.0f"

.PP
Definition at line 53 of file SteamVR_LoadLevel\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_LoadLevel\&.loadingScreenFadeInTime = 1\&.0f"

.PP
Definition at line 79 of file SteamVR_LoadLevel\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_LoadLevel\&.loadingScreenFadeOutTime = 0\&.25f"

.PP
Definition at line 80 of file SteamVR_LoadLevel\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_LoadLevel\&.loadingScreenTransform"

.PP
Definition at line 57 of file SteamVR_LoadLevel\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_LoadLevel\&.loadingScreenWidthInMeters = 6\&.0f"

.PP
Definition at line 49 of file SteamVR_LoadLevel\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_LoadLevel\&.postLoadSettleTime = 0\&.0f"

.PP
Definition at line 76 of file SteamVR_LoadLevel\&.cs\&.
.SS "Texture Valve\&.VR\&.SteamVR_LoadLevel\&.progressBarEmpty"

.PP
Definition at line 46 of file SteamVR_LoadLevel\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_LoadLevel\&.progressBarWidthInMeters = 3\&.0f"

.PP
Definition at line 50 of file SteamVR_LoadLevel\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_LoadLevel\&.showGrid = false"

.PP
Definition at line 67 of file SteamVR_LoadLevel\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_LoadLevel\&.loading\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 17 of file SteamVR_LoadLevel\&.cs\&.
.SS "float? Valve\&.VR\&.SteamVR_LoadLevel\&.progress\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 19 of file SteamVR_LoadLevel\&.cs\&.
.SS "Texture? Valve\&.VR\&.SteamVR_LoadLevel\&.progressTexture\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 23 of file SteamVR_LoadLevel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
