.TH "Valve.VR.IVRExtendedDisplay" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.IVRExtendedDisplay
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal delegate void \fB_GetWindowBounds\fP (ref int pnX, ref int pnY, ref uint pnWidth, ref uint pnHeight)"
.br
.ti -1c
.RI "internal delegate void \fB_GetEyeOutputViewport\fP (\fBEVREye\fP eEye, ref uint pnX, ref uint pnY, ref uint pnWidth, ref uint pnHeight)"
.br
.ti -1c
.RI "internal delegate void \fB_GetDXGIOutputInfo\fP (ref int pnAdapterIndex, ref int pnAdapterOutputIndex)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internal \fB_GetWindowBounds\fP \fBGetWindowBounds\fP"
.br
.ti -1c
.RI "internal \fB_GetEyeOutputViewport\fP \fBGetEyeOutputViewport\fP"
.br
.ti -1c
.RI "internal \fB_GetDXGIOutputInfo\fP \fBGetDXGIOutputInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 256 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "internal delegate void Valve\&.VR\&.IVRExtendedDisplay\&._GetDXGIOutputInfo (ref int pnAdapterIndex, ref int pnAdapterOutputIndex)"

.SS "internal delegate void Valve\&.VR\&.IVRExtendedDisplay\&._GetEyeOutputViewport (\fBEVREye\fP eEye, ref uint pnX, ref uint pnY, ref uint pnWidth, ref uint pnHeight)"

.SS "internal delegate void Valve\&.VR\&.IVRExtendedDisplay\&._GetWindowBounds (ref int pnX, ref int pnY, ref uint pnWidth, ref uint pnHeight)"

.SH "Member Data Documentation"
.PP 
.SS "internal \fB_GetDXGIOutputInfo\fP Valve\&.VR\&.IVRExtendedDisplay\&.GetDXGIOutputInfo"

.PP
Definition at line 271 of file openvr_api\&.cs\&.
.SS "internal \fB_GetEyeOutputViewport\fP Valve\&.VR\&.IVRExtendedDisplay\&.GetEyeOutputViewport"

.PP
Definition at line 266 of file openvr_api\&.cs\&.
.SS "internal \fB_GetWindowBounds\fP Valve\&.VR\&.IVRExtendedDisplay\&.GetWindowBounds"

.PP
Definition at line 261 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
