.TH "Valve.VR.SteamVR_Behaviour_SkeletonCustom" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Behaviour_SkeletonCustom \- The major difference between this component and the standard \fBSteamVR_Behaviour_Skeleton\fP is this one lets you only use the joints you care about\&. You can set the transforms you're concerned with and ignore the ones you're not\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_Behaviour_Skeleton\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAssignBonesArray\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Transform \fB_wrist\fP"
.br
.ti -1c
.RI "Transform \fB_thumbMetacarpal\fP"
.br
.ti -1c
.RI "Transform \fB_thumbProximal\fP"
.br
.ti -1c
.RI "Transform \fB_thumbMiddle\fP"
.br
.ti -1c
.RI "Transform \fB_thumbDistal\fP"
.br
.ti -1c
.RI "Transform \fB_thumbTip\fP"
.br
.ti -1c
.RI "Transform \fB_thumbAux\fP"
.br
.ti -1c
.RI "Transform \fB_indexMetacarpal\fP"
.br
.ti -1c
.RI "Transform \fB_indexProximal\fP"
.br
.ti -1c
.RI "Transform \fB_indexMiddle\fP"
.br
.ti -1c
.RI "Transform \fB_indexDistal\fP"
.br
.ti -1c
.RI "Transform \fB_indexTip\fP"
.br
.ti -1c
.RI "Transform \fB_indexAux\fP"
.br
.ti -1c
.RI "Transform \fB_middleMetacarpal\fP"
.br
.ti -1c
.RI "Transform \fB_middleProximal\fP"
.br
.ti -1c
.RI "Transform \fB_middleMiddle\fP"
.br
.ti -1c
.RI "Transform \fB_middleDistal\fP"
.br
.ti -1c
.RI "Transform \fB_middleTip\fP"
.br
.ti -1c
.RI "Transform \fB_middleAux\fP"
.br
.ti -1c
.RI "Transform \fB_ringMetacarpal\fP"
.br
.ti -1c
.RI "Transform \fB_ringProximal\fP"
.br
.ti -1c
.RI "Transform \fB_ringMiddle\fP"
.br
.ti -1c
.RI "Transform \fB_ringDistal\fP"
.br
.ti -1c
.RI "Transform \fB_ringTip\fP"
.br
.ti -1c
.RI "Transform \fB_ringAux\fP"
.br
.ti -1c
.RI "Transform \fB_pinkyMetacarpal\fP"
.br
.ti -1c
.RI "Transform \fB_pinkyProximal\fP"
.br
.ti -1c
.RI "Transform \fB_pinkyMiddle\fP"
.br
.ti -1c
.RI "Transform \fB_pinkyDistal\fP"
.br
.ti -1c
.RI "Transform \fB_pinkyTip\fP"
.br
.ti -1c
.RI "Transform \fB_pinkyAux\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The major difference between this component and the standard \fBSteamVR_Behaviour_Skeleton\fP is this one lets you only use the joints you care about\&. You can set the transforms you're concerned with and ignore the ones you're not\&. 


.PP
Definition at line 12 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&.AssignBonesArray ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBValve\&.VR\&.SteamVR_Behaviour_Skeleton\fP\&.
.PP
Definition at line 108 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._indexAux\fC [protected]\fP"

.PP
Definition at line 51 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._indexDistal\fC [protected]\fP"

.PP
Definition at line 45 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._indexMetacarpal\fC [protected]\fP"

.PP
Definition at line 36 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._indexMiddle\fC [protected]\fP"

.PP
Definition at line 42 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._indexProximal\fC [protected]\fP"

.PP
Definition at line 39 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._indexTip\fC [protected]\fP"

.PP
Definition at line 48 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._middleAux\fC [protected]\fP"

.PP
Definition at line 69 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._middleDistal\fC [protected]\fP"

.PP
Definition at line 63 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._middleMetacarpal\fC [protected]\fP"

.PP
Definition at line 54 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._middleMiddle\fC [protected]\fP"

.PP
Definition at line 60 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._middleProximal\fC [protected]\fP"

.PP
Definition at line 57 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._middleTip\fC [protected]\fP"

.PP
Definition at line 66 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._pinkyAux\fC [protected]\fP"

.PP
Definition at line 105 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._pinkyDistal\fC [protected]\fP"

.PP
Definition at line 99 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._pinkyMetacarpal\fC [protected]\fP"

.PP
Definition at line 90 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._pinkyMiddle\fC [protected]\fP"

.PP
Definition at line 96 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._pinkyProximal\fC [protected]\fP"

.PP
Definition at line 93 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._pinkyTip\fC [protected]\fP"

.PP
Definition at line 102 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._ringAux\fC [protected]\fP"

.PP
Definition at line 87 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._ringDistal\fC [protected]\fP"

.PP
Definition at line 81 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._ringMetacarpal\fC [protected]\fP"

.PP
Definition at line 72 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._ringMiddle\fC [protected]\fP"

.PP
Definition at line 78 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._ringProximal\fC [protected]\fP"

.PP
Definition at line 75 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._ringTip\fC [protected]\fP"

.PP
Definition at line 84 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._thumbAux\fC [protected]\fP"

.PP
Definition at line 33 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._thumbDistal\fC [protected]\fP"

.PP
Definition at line 27 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._thumbMetacarpal\fC [protected]\fP"

.PP
Definition at line 18 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._thumbMiddle\fC [protected]\fP"

.PP
Definition at line 24 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._thumbProximal\fC [protected]\fP"

.PP
Definition at line 21 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._thumbTip\fC [protected]\fP"

.PP
Definition at line 30 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_Behaviour_SkeletonCustom\&._wrist\fC [protected]\fP"

.PP
Definition at line 15 of file SteamVR_Behaviour_SkeletonCustom\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
