.TH "Valve.VR.SteamVR_Skeleton_PoseSnapshot" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Skeleton_PoseSnapshot \- PoseSnapshots hold a skeleton pose for one hand, as well as storing which hand they contain\&. They have several functions for combining BlendablePoses\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSteamVR_Skeleton_PoseSnapshot\fP (int boneCount, \fBSteamVR_Input_Sources\fP source)"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (\fBSteamVR_Skeleton_PoseSnapshot\fP source)"
.br
.RI "Perform a deep copy from one poseSnapshot to another\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBinputSource\fP"
.br
.ti -1c
.RI "Vector3 \fBposition\fP"
.br
.ti -1c
.RI "Quaternion \fBrotation\fP"
.br
.ti -1c
.RI "Vector3 [] \fBbonePositions\fP"
.br
.ti -1c
.RI "Quaternion [] \fBboneRotations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
PoseSnapshots hold a skeleton pose for one hand, as well as storing which hand they contain\&. They have several functions for combining BlendablePoses\&. 


.PP
Definition at line 435 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.SteamVR_Skeleton_PoseSnapshot\&.SteamVR_Skeleton_PoseSnapshot (int boneCount, \fBSteamVR_Input_Sources\fP source)"

.PP
Definition at line 445 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Skeleton_PoseSnapshot\&.CopyFrom (\fBSteamVR_Skeleton_PoseSnapshot\fP source)"

.PP
Perform a deep copy from one poseSnapshot to another\&. 
.PP
Definition at line 457 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 [] Valve\&.VR\&.SteamVR_Skeleton_PoseSnapshot\&.bonePositions"

.PP
Definition at line 442 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "Quaternion [] Valve\&.VR\&.SteamVR_Skeleton_PoseSnapshot\&.boneRotations"

.PP
Definition at line 443 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.SteamVR_Skeleton_PoseSnapshot\&.inputSource"

.PP
Definition at line 437 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "Vector3 Valve\&.VR\&.SteamVR_Skeleton_PoseSnapshot\&.position"

.PP
Definition at line 439 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "Quaternion Valve\&.VR\&.SteamVR_Skeleton_PoseSnapshot\&.rotation"

.PP
Definition at line 440 of file SteamVR_Skeleton_Poser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
