.TH "Valve.VR.VREvent_Screenshot_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VREvent_Screenshot_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint \fBhandle\fP"
.br
.ti -1c
.RI "uint \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5140 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "uint Valve\&.VR\&.VREvent_Screenshot_t\&.handle"

.PP
Definition at line 5142 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.VREvent_Screenshot_t\&.type"

.PP
Definition at line 5143 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
