.TH "Valve.VR.InteractionSystem.Unparent" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Unparent
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Transform \fBGetOldParent\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file Unparent\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Unparent\&.GetOldParent ()"

.PP
Definition at line 35 of file Unparent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
