.TH "Valve.VR.InputSkeletalActionData_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InputSkeletalActionData_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBbActive\fP"
.br
.ti -1c
.RI "ulong \fBactiveOrigin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5553 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "ulong Valve\&.VR\&.InputSkeletalActionData_t\&.activeOrigin"

.PP
Definition at line 5557 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.InputSkeletalActionData_t\&.bActive"

.PP
Definition at line 5556 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
