.TH "Valve.VR.InputPoseActionData_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InputPoseActionData_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBbActive\fP"
.br
.ti -1c
.RI "ulong \fBactiveOrigin\fP"
.br
.ti -1c
.RI "\fBTrackedDevicePose_t\fP \fBpose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5546 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "ulong Valve\&.VR\&.InputPoseActionData_t\&.activeOrigin"

.PP
Definition at line 5550 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.InputPoseActionData_t\&.bActive"

.PP
Definition at line 5549 of file openvr_api\&.cs\&.
.SS "\fBTrackedDevicePose_t\fP Valve\&.VR\&.InputPoseActionData_t\&.pose"

.PP
Definition at line 5551 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
