.TH "Valve.VR.InteractionSystem.AllowTeleportWhileAttachedToHand" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.AllowTeleportWhileAttachedToHand
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBteleportAllowed\fP = true"
.br
.ti -1c
.RI "bool \fBoverrideHoverLock\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file AllowTeleportWhileAttachedToHand\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.AllowTeleportWhileAttachedToHand\&.overrideHoverLock = true"

.PP
Definition at line 16 of file AllowTeleportWhileAttachedToHand\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.AllowTeleportWhileAttachedToHand\&.teleportAllowed = true"

.PP
Definition at line 15 of file AllowTeleportWhileAttachedToHand\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
