.TH "Valve.VR.IVRChaperoneSetup" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.IVRChaperoneSetup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal delegate bool \fB_CommitWorkingCopy\fP (\fBEChaperoneConfigFile\fP configFile)"
.br
.ti -1c
.RI "internal delegate void \fB_RevertWorkingCopy\fP ()"
.br
.ti -1c
.RI "internal delegate bool \fB_GetWorkingPlayAreaSize\fP (ref float pSizeX, ref float pSizeZ)"
.br
.ti -1c
.RI "internal delegate bool \fB_GetWorkingPlayAreaRect\fP (ref \fBHmdQuad_t\fP rect)"
.br
.ti -1c
.RI "internal delegate bool \fB_GetWorkingCollisionBoundsInfo\fP ([\fBIn\fP, \fBOut\fP] \fBHmdQuad_t\fP[] pQuadsBuffer, ref uint punQuadsCount)"
.br
.ti -1c
.RI "internal delegate bool \fB_GetLiveCollisionBoundsInfo\fP ([\fBIn\fP, \fBOut\fP] \fBHmdQuad_t\fP[] pQuadsBuffer, ref uint punQuadsCount)"
.br
.ti -1c
.RI "internal delegate bool \fB_GetWorkingSeatedZeroPoseToRawTrackingPose\fP (ref \fBHmdMatrix34_t\fP pmatSeatedZeroPoseToRawTrackingPose)"
.br
.ti -1c
.RI "internal delegate bool \fB_GetWorkingStandingZeroPoseToRawTrackingPose\fP (ref \fBHmdMatrix34_t\fP pmatStandingZeroPoseToRawTrackingPose)"
.br
.ti -1c
.RI "internal delegate void \fB_SetWorkingPlayAreaSize\fP (float sizeX, float sizeZ)"
.br
.ti -1c
.RI "internal delegate void \fB_SetWorkingCollisionBoundsInfo\fP ([\fBIn\fP, \fBOut\fP] \fBHmdQuad_t\fP[] pQuadsBuffer, uint unQuadsCount)"
.br
.ti -1c
.RI "internal delegate void \fB_SetWorkingPerimeter\fP ([\fBIn\fP, \fBOut\fP] \fBHmdVector2_t\fP[] pPointBuffer, uint unPointCount)"
.br
.ti -1c
.RI "internal delegate void \fB_SetWorkingSeatedZeroPoseToRawTrackingPose\fP (ref \fBHmdMatrix34_t\fP pMatSeatedZeroPoseToRawTrackingPose)"
.br
.ti -1c
.RI "internal delegate void \fB_SetWorkingStandingZeroPoseToRawTrackingPose\fP (ref \fBHmdMatrix34_t\fP pMatStandingZeroPoseToRawTrackingPose)"
.br
.ti -1c
.RI "internal delegate void \fB_ReloadFromDisk\fP (\fBEChaperoneConfigFile\fP configFile)"
.br
.ti -1c
.RI "internal delegate bool \fB_GetLiveSeatedZeroPoseToRawTrackingPose\fP (ref \fBHmdMatrix34_t\fP pmatSeatedZeroPoseToRawTrackingPose)"
.br
.ti -1c
.RI "internal delegate bool \fB_ExportLiveToBuffer\fP (System\&.Text\&.StringBuilder pBuffer, ref uint pnBufferLength)"
.br
.ti -1c
.RI "internal delegate bool \fB_ImportFromBufferToWorking\fP (string pBuffer, uint nImportFlags)"
.br
.ti -1c
.RI "internal delegate void \fB_ShowWorkingSetPreview\fP ()"
.br
.ti -1c
.RI "internal delegate void \fB_HideWorkingSetPreview\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internal \fB_CommitWorkingCopy\fP \fBCommitWorkingCopy\fP"
.br
.ti -1c
.RI "internal \fB_RevertWorkingCopy\fP \fBRevertWorkingCopy\fP"
.br
.ti -1c
.RI "internal \fB_GetWorkingPlayAreaSize\fP \fBGetWorkingPlayAreaSize\fP"
.br
.ti -1c
.RI "internal \fB_GetWorkingPlayAreaRect\fP \fBGetWorkingPlayAreaRect\fP"
.br
.ti -1c
.RI "internal \fB_GetWorkingCollisionBoundsInfo\fP \fBGetWorkingCollisionBoundsInfo\fP"
.br
.ti -1c
.RI "internal \fB_GetLiveCollisionBoundsInfo\fP \fBGetLiveCollisionBoundsInfo\fP"
.br
.ti -1c
.RI "internal \fB_GetWorkingSeatedZeroPoseToRawTrackingPose\fP \fBGetWorkingSeatedZeroPoseToRawTrackingPose\fP"
.br
.ti -1c
.RI "internal \fB_GetWorkingStandingZeroPoseToRawTrackingPose\fP \fBGetWorkingStandingZeroPoseToRawTrackingPose\fP"
.br
.ti -1c
.RI "internal \fB_SetWorkingPlayAreaSize\fP \fBSetWorkingPlayAreaSize\fP"
.br
.ti -1c
.RI "internal \fB_SetWorkingCollisionBoundsInfo\fP \fBSetWorkingCollisionBoundsInfo\fP"
.br
.ti -1c
.RI "internal \fB_SetWorkingPerimeter\fP \fBSetWorkingPerimeter\fP"
.br
.ti -1c
.RI "internal \fB_SetWorkingSeatedZeroPoseToRawTrackingPose\fP \fBSetWorkingSeatedZeroPoseToRawTrackingPose\fP"
.br
.ti -1c
.RI "internal \fB_SetWorkingStandingZeroPoseToRawTrackingPose\fP \fBSetWorkingStandingZeroPoseToRawTrackingPose\fP"
.br
.ti -1c
.RI "internal \fB_ReloadFromDisk\fP \fBReloadFromDisk\fP"
.br
.ti -1c
.RI "internal \fB_GetLiveSeatedZeroPoseToRawTrackingPose\fP \fBGetLiveSeatedZeroPoseToRawTrackingPose\fP"
.br
.ti -1c
.RI "internal \fB_ExportLiveToBuffer\fP \fBExportLiveToBuffer\fP"
.br
.ti -1c
.RI "internal \fB_ImportFromBufferToWorking\fP \fBImportFromBufferToWorking\fP"
.br
.ti -1c
.RI "internal \fB_ShowWorkingSetPreview\fP \fBShowWorkingSetPreview\fP"
.br
.ti -1c
.RI "internal \fB_HideWorkingSetPreview\fP \fBHideWorkingSetPreview\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 546 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "internal delegate bool Valve\&.VR\&.IVRChaperoneSetup\&._CommitWorkingCopy (\fBEChaperoneConfigFile\fP configFile)"

.SS "internal delegate bool Valve\&.VR\&.IVRChaperoneSetup\&._ExportLiveToBuffer (System\&.Text\&.StringBuilder pBuffer, ref uint pnBufferLength)"

.SS "internal delegate bool Valve\&.VR\&.IVRChaperoneSetup\&._GetLiveCollisionBoundsInfo ([In, Out] \fBHmdQuad_t\fP [] pQuadsBuffer, ref uint punQuadsCount)"

.SS "internal delegate bool Valve\&.VR\&.IVRChaperoneSetup\&._GetLiveSeatedZeroPoseToRawTrackingPose (ref \fBHmdMatrix34_t\fP pmatSeatedZeroPoseToRawTrackingPose)"

.SS "internal delegate bool Valve\&.VR\&.IVRChaperoneSetup\&._GetWorkingCollisionBoundsInfo ([In, Out] \fBHmdQuad_t\fP [] pQuadsBuffer, ref uint punQuadsCount)"

.SS "internal delegate bool Valve\&.VR\&.IVRChaperoneSetup\&._GetWorkingPlayAreaRect (ref \fBHmdQuad_t\fP rect)"

.SS "internal delegate bool Valve\&.VR\&.IVRChaperoneSetup\&._GetWorkingPlayAreaSize (ref float pSizeX, ref float pSizeZ)"

.SS "internal delegate bool Valve\&.VR\&.IVRChaperoneSetup\&._GetWorkingSeatedZeroPoseToRawTrackingPose (ref \fBHmdMatrix34_t\fP pmatSeatedZeroPoseToRawTrackingPose)"

.SS "internal delegate bool Valve\&.VR\&.IVRChaperoneSetup\&._GetWorkingStandingZeroPoseToRawTrackingPose (ref \fBHmdMatrix34_t\fP pmatStandingZeroPoseToRawTrackingPose)"

.SS "internal delegate void Valve\&.VR\&.IVRChaperoneSetup\&._HideWorkingSetPreview ()"

.SS "internal delegate bool Valve\&.VR\&.IVRChaperoneSetup\&._ImportFromBufferToWorking (string pBuffer, uint nImportFlags)"

.SS "internal delegate void Valve\&.VR\&.IVRChaperoneSetup\&._ReloadFromDisk (\fBEChaperoneConfigFile\fP configFile)"

.SS "internal delegate void Valve\&.VR\&.IVRChaperoneSetup\&._RevertWorkingCopy ()"

.SS "internal delegate void Valve\&.VR\&.IVRChaperoneSetup\&._SetWorkingCollisionBoundsInfo ([In, Out] \fBHmdQuad_t\fP [] pQuadsBuffer, uint unQuadsCount)"

.SS "internal delegate void Valve\&.VR\&.IVRChaperoneSetup\&._SetWorkingPerimeter ([In, Out] \fBHmdVector2_t\fP [] pPointBuffer, uint unPointCount)"

.SS "internal delegate void Valve\&.VR\&.IVRChaperoneSetup\&._SetWorkingPlayAreaSize (float sizeX, float sizeZ)"

.SS "internal delegate void Valve\&.VR\&.IVRChaperoneSetup\&._SetWorkingSeatedZeroPoseToRawTrackingPose (ref \fBHmdMatrix34_t\fP pMatSeatedZeroPoseToRawTrackingPose)"

.SS "internal delegate void Valve\&.VR\&.IVRChaperoneSetup\&._SetWorkingStandingZeroPoseToRawTrackingPose (ref \fBHmdMatrix34_t\fP pMatStandingZeroPoseToRawTrackingPose)"

.SS "internal delegate void Valve\&.VR\&.IVRChaperoneSetup\&._ShowWorkingSetPreview ()"

.SH "Member Data Documentation"
.PP 
.SS "internal \fB_CommitWorkingCopy\fP Valve\&.VR\&.IVRChaperoneSetup\&.CommitWorkingCopy"

.PP
Definition at line 551 of file openvr_api\&.cs\&.
.SS "internal \fB_ExportLiveToBuffer\fP Valve\&.VR\&.IVRChaperoneSetup\&.ExportLiveToBuffer"

.PP
Definition at line 626 of file openvr_api\&.cs\&.
.SS "internal \fB_GetLiveCollisionBoundsInfo\fP Valve\&.VR\&.IVRChaperoneSetup\&.GetLiveCollisionBoundsInfo"

.PP
Definition at line 576 of file openvr_api\&.cs\&.
.SS "internal \fB_GetLiveSeatedZeroPoseToRawTrackingPose\fP Valve\&.VR\&.IVRChaperoneSetup\&.GetLiveSeatedZeroPoseToRawTrackingPose"

.PP
Definition at line 621 of file openvr_api\&.cs\&.
.SS "internal \fB_GetWorkingCollisionBoundsInfo\fP Valve\&.VR\&.IVRChaperoneSetup\&.GetWorkingCollisionBoundsInfo"

.PP
Definition at line 571 of file openvr_api\&.cs\&.
.SS "internal \fB_GetWorkingPlayAreaRect\fP Valve\&.VR\&.IVRChaperoneSetup\&.GetWorkingPlayAreaRect"

.PP
Definition at line 566 of file openvr_api\&.cs\&.
.SS "internal \fB_GetWorkingPlayAreaSize\fP Valve\&.VR\&.IVRChaperoneSetup\&.GetWorkingPlayAreaSize"

.PP
Definition at line 561 of file openvr_api\&.cs\&.
.SS "internal \fB_GetWorkingSeatedZeroPoseToRawTrackingPose\fP Valve\&.VR\&.IVRChaperoneSetup\&.GetWorkingSeatedZeroPoseToRawTrackingPose"

.PP
Definition at line 581 of file openvr_api\&.cs\&.
.SS "internal \fB_GetWorkingStandingZeroPoseToRawTrackingPose\fP Valve\&.VR\&.IVRChaperoneSetup\&.GetWorkingStandingZeroPoseToRawTrackingPose"

.PP
Definition at line 586 of file openvr_api\&.cs\&.
.SS "internal \fB_HideWorkingSetPreview\fP Valve\&.VR\&.IVRChaperoneSetup\&.HideWorkingSetPreview"

.PP
Definition at line 641 of file openvr_api\&.cs\&.
.SS "internal \fB_ImportFromBufferToWorking\fP Valve\&.VR\&.IVRChaperoneSetup\&.ImportFromBufferToWorking"

.PP
Definition at line 631 of file openvr_api\&.cs\&.
.SS "internal \fB_ReloadFromDisk\fP Valve\&.VR\&.IVRChaperoneSetup\&.ReloadFromDisk"

.PP
Definition at line 616 of file openvr_api\&.cs\&.
.SS "internal \fB_RevertWorkingCopy\fP Valve\&.VR\&.IVRChaperoneSetup\&.RevertWorkingCopy"

.PP
Definition at line 556 of file openvr_api\&.cs\&.
.SS "internal \fB_SetWorkingCollisionBoundsInfo\fP Valve\&.VR\&.IVRChaperoneSetup\&.SetWorkingCollisionBoundsInfo"

.PP
Definition at line 596 of file openvr_api\&.cs\&.
.SS "internal \fB_SetWorkingPerimeter\fP Valve\&.VR\&.IVRChaperoneSetup\&.SetWorkingPerimeter"

.PP
Definition at line 601 of file openvr_api\&.cs\&.
.SS "internal \fB_SetWorkingPlayAreaSize\fP Valve\&.VR\&.IVRChaperoneSetup\&.SetWorkingPlayAreaSize"

.PP
Definition at line 591 of file openvr_api\&.cs\&.
.SS "internal \fB_SetWorkingSeatedZeroPoseToRawTrackingPose\fP Valve\&.VR\&.IVRChaperoneSetup\&.SetWorkingSeatedZeroPoseToRawTrackingPose"

.PP
Definition at line 606 of file openvr_api\&.cs\&.
.SS "internal \fB_SetWorkingStandingZeroPoseToRawTrackingPose\fP Valve\&.VR\&.IVRChaperoneSetup\&.SetWorkingStandingZeroPoseToRawTrackingPose"

.PP
Definition at line 611 of file openvr_api\&.cs\&.
.SS "internal \fB_ShowWorkingSetPreview\fP Valve\&.VR\&.IVRChaperoneSetup\&.ShowWorkingSetPreview"

.PP
Definition at line 636 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
