.TH "Valve.VR.InteractionSystem.Longbow" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Longbow
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBHandedness\fP { \fBHandedness\&.Left\fP, \fBHandedness\&.Right\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBArrowReleased\fP ()"
.br
.ti -1c
.RI "float \fBGetArrowVelocity\fP ()"
.br
.ti -1c
.RI "void \fBStartRotationLerp\fP ()"
.br
.ti -1c
.RI "void \fBStartNock\fP (\fBArrowHand\fP currentArrowHand)"
.br
.ti -1c
.RI "void \fBArrowInPosition\fP ()"
.br
.ti -1c
.RI "void \fBReleaseNock\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHandedness\fP \fBcurrentHandGuess\fP = \fBHandedness\&.Left\fP"
.br
.ti -1c
.RI "Transform \fBpivotTransform\fP"
.br
.ti -1c
.RI "Transform \fBhandleTransform\fP"
.br
.ti -1c
.RI "Transform \fBnockTransform\fP"
.br
.ti -1c
.RI "Transform \fBnockRestTransform\fP"
.br
.ti -1c
.RI "bool \fBautoSpawnArrowHand\fP = true"
.br
.ti -1c
.RI "\fBItemPackage\fP \fBarrowHandItemPackage\fP"
.br
.ti -1c
.RI "GameObject \fBarrowHandPrefab\fP"
.br
.ti -1c
.RI "bool \fBnocked\fP"
.br
.ti -1c
.RI "bool \fBpulled\fP"
.br
.ti -1c
.RI "float \fBarrowMinVelocity\fP = 3f"
.br
.ti -1c
.RI "float \fBarrowMaxVelocity\fP = 30f"
.br
.ti -1c
.RI "float \fBdrawOffset\fP = 0\&.06f"
.br
.ti -1c
.RI "\fBLinearMapping\fP \fBbowDrawLinearMapping\fP"
.br
.ti -1c
.RI "\fBSoundBowClick\fP \fBdrawSound\fP"
.br
.ti -1c
.RI "\fBSoundPlayOneshot\fP \fBarrowSlideSound\fP"
.br
.ti -1c
.RI "\fBSoundPlayOneshot\fP \fBreleaseSound\fP"
.br
.ti -1c
.RI "\fBSoundPlayOneshot\fP \fBnockSound\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Longbow\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.InteractionSystem\&.Longbow\&.Handedness\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILeft \fP\fP
.TP
\fB\fIRight \fP\fP
.PP
Definition at line 17 of file Longbow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.Longbow\&.ArrowInPosition ()"

.PP
Definition at line 328 of file Longbow\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Longbow\&.ArrowReleased ()"

.PP
Definition at line 191 of file Longbow\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Longbow\&.GetArrowVelocity ()"

.PP
Definition at line 226 of file Longbow\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Longbow\&.ReleaseNock ()"

.PP
Definition at line 340 of file Longbow\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Longbow\&.StartNock (\fBArrowHand\fP currentArrowHand)"

.PP
Definition at line 244 of file Longbow\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Longbow\&.StartRotationLerp ()"

.PP
Definition at line 233 of file Longbow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBItemPackage\fP Valve\&.VR\&.InteractionSystem\&.Longbow\&.arrowHandItemPackage"

.PP
Definition at line 34 of file Longbow\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.Longbow\&.arrowHandPrefab"

.PP
Definition at line 35 of file Longbow\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Longbow\&.arrowMaxVelocity = 30f"

.PP
Definition at line 50 of file Longbow\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Longbow\&.arrowMinVelocity = 3f"

.PP
Definition at line 49 of file Longbow\&.cs\&.
.SS "\fBSoundPlayOneshot\fP Valve\&.VR\&.InteractionSystem\&.Longbow\&.arrowSlideSound"

.PP
Definition at line 75 of file Longbow\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Longbow\&.autoSpawnArrowHand = true"

.PP
Definition at line 33 of file Longbow\&.cs\&.
.SS "\fBLinearMapping\fP Valve\&.VR\&.InteractionSystem\&.Longbow\&.bowDrawLinearMapping"

.PP
Definition at line 68 of file Longbow\&.cs\&.
.SS "\fBHandedness\fP Valve\&.VR\&.InteractionSystem\&.Longbow\&.currentHandGuess = \fBHandedness\&.Left\fP"

.PP
Definition at line 19 of file Longbow\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Longbow\&.drawOffset = 0\&.06f"

.PP
Definition at line 66 of file Longbow\&.cs\&.
.SS "\fBSoundBowClick\fP Valve\&.VR\&.InteractionSystem\&.Longbow\&.drawSound"

.PP
Definition at line 73 of file Longbow\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Longbow\&.handleTransform"

.PP
Definition at line 25 of file Longbow\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Longbow\&.nocked"

.PP
Definition at line 37 of file Longbow\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Longbow\&.nockRestTransform"

.PP
Definition at line 31 of file Longbow\&.cs\&.
.SS "\fBSoundPlayOneshot\fP Valve\&.VR\&.InteractionSystem\&.Longbow\&.nockSound"

.PP
Definition at line 77 of file Longbow\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Longbow\&.nockTransform"

.PP
Definition at line 30 of file Longbow\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Longbow\&.pivotTransform"

.PP
Definition at line 24 of file Longbow\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Longbow\&.pulled"

.PP
Definition at line 38 of file Longbow\&.cs\&.
.SS "\fBSoundPlayOneshot\fP Valve\&.VR\&.InteractionSystem\&.Longbow\&.releaseSound"

.PP
Definition at line 76 of file Longbow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
