.TH "Valve.VR.IVRDriverManager" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.IVRDriverManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal delegate uint \fB_GetDriverCount\fP ()"
.br
.ti -1c
.RI "internal delegate uint \fB_GetDriverName\fP (uint nDriver, System\&.Text\&.StringBuilder pchValue, uint unBufferSize)"
.br
.ti -1c
.RI "internal delegate ulong \fB_GetDriverHandle\fP (string pchDriverName)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internal \fB_GetDriverCount\fP \fBGetDriverCount\fP"
.br
.ti -1c
.RI "internal \fB_GetDriverName\fP \fBGetDriverName\fP"
.br
.ti -1c
.RI "internal \fB_GetDriverHandle\fP \fBGetDriverHandle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1521 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "internal delegate uint Valve\&.VR\&.IVRDriverManager\&._GetDriverCount ()"

.SS "internal delegate ulong Valve\&.VR\&.IVRDriverManager\&._GetDriverHandle (string pchDriverName)"

.SS "internal delegate uint Valve\&.VR\&.IVRDriverManager\&._GetDriverName (uint nDriver, System\&.Text\&.StringBuilder pchValue, uint unBufferSize)"

.SH "Member Data Documentation"
.PP 
.SS "internal \fB_GetDriverCount\fP Valve\&.VR\&.IVRDriverManager\&.GetDriverCount"

.PP
Definition at line 1526 of file openvr_api\&.cs\&.
.SS "internal \fB_GetDriverHandle\fP Valve\&.VR\&.IVRDriverManager\&.GetDriverHandle"

.PP
Definition at line 1536 of file openvr_api\&.cs\&.
.SS "internal \fB_GetDriverName\fP Valve\&.VR\&.IVRDriverManager\&.GetDriverName"

.PP
Definition at line 1531 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
