.TH "Valve.VR.SteamVR_Input_ActionSetPropertyEditor" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_ActionSetPropertyEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyDrawer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override float \fBGetPropertyHeight\fP (SerializedProperty property, GUIContent label)"
.br
.ti -1c
.RI "override void \fBOnGUI\fP (Rect position, SerializedProperty property, GUIContent label)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBselectedIndex\fP = \fBnotInitializedIndex\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_ActionSet\fP [] \fBactionSets\fP"
.br
.ti -1c
.RI "string [] \fBenumItems\fP"
.br
.ti -1c
.RI "const int \fBnotInitializedIndex\fP = \-1"
.br
.ti -1c
.RI "const int \fBnoneIndex\fP = 0"
.br
.ti -1c
.RI "int \fBaddIndex\fP = 1"
.br
.ti -1c
.RI "const string \fBdefaultPathTemplate\fP = ' \\u26A0 Missing action set: {0}'"
.br
.ti -1c
.RI "string \fBdefaultPathLabel\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Input_ActionSetPropertyEditor\&.Awake ()\fC [protected]\fP"

.PP
Definition at line 32 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.
.SS "override float Valve\&.VR\&.SteamVR_Input_ActionSetPropertyEditor\&.GetPropertyHeight (SerializedProperty property, GUIContent label)"

.PP
Definition at line 63 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.
.SS "override void Valve\&.VR\&.SteamVR_Input_ActionSetPropertyEditor\&.OnGUI (Rect position, SerializedProperty property, GUIContent label)"

.PP
Definition at line 78 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSteamVR_ActionSet\fP [] Valve\&.VR\&.SteamVR_Input_ActionSetPropertyEditor\&.actionSets\fC [protected]\fP"

.PP
Definition at line 21 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.
.SS "int Valve\&.VR\&.SteamVR_Input_ActionSetPropertyEditor\&.addIndex = 1\fC [protected]\fP"

.PP
Definition at line 27 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input_ActionSetPropertyEditor\&.defaultPathLabel = null\fC [protected]\fP"

.PP
Definition at line 30 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.
.SS "const string Valve\&.VR\&.SteamVR_Input_ActionSetPropertyEditor\&.defaultPathTemplate = ' \\u26A0 Missing action set: {0}'\fC [protected]\fP"

.PP
Definition at line 29 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.
.SS "string [] Valve\&.VR\&.SteamVR_Input_ActionSetPropertyEditor\&.enumItems\fC [protected]\fP"

.PP
Definition at line 22 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.
.SS "const int Valve\&.VR\&.SteamVR_Input_ActionSetPropertyEditor\&.noneIndex = 0\fC [protected]\fP"

.PP
Definition at line 26 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.
.SS "const int Valve\&.VR\&.SteamVR_Input_ActionSetPropertyEditor\&.notInitializedIndex = \-1\fC [protected]\fP"

.PP
Definition at line 25 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.
.SS "int Valve\&.VR\&.SteamVR_Input_ActionSetPropertyEditor\&.selectedIndex = \fBnotInitializedIndex\fP"

.PP
Definition at line 23 of file SteamVR_Input_ActionSetPropertyEditor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
