.TH "Valve.VR.InteractionSystem.TeleportPoint" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.TeleportPoint
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTeleportPointType\fP { \fBTeleportPointType\&.MoveToLocation\fP, \fBTeleportPointType\&.SwitchToNewScene\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBShouldActivate\fP (Vector3 playerPosition)"
.br
.ti -1c
.RI "override bool \fBShouldMovePlayer\fP ()"
.br
.ti -1c
.RI "override void \fBHighlight\fP (bool highlight)"
.br
.ti -1c
.RI "override void \fBUpdateVisuals\fP ()"
.br
.ti -1c
.RI "override void \fBSetAlpha\fP (float tintAlpha, float alphaPercent)"
.br
.ti -1c
.RI "void \fBSetMeshMaterials\fP (Material material, Color textColor)"
.br
.ti -1c
.RI "void \fBTeleportToScene\fP ()"
.br
.ti -1c
.RI "void \fBGetRelevantComponents\fP ()"
.br
.ti -1c
.RI "void \fBReleaseRelevantComponents\fP ()"
.br
.ti -1c
.RI "void \fBUpdateVisualsInEditor\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTeleportPointType\fP \fBteleportType\fP = \fBTeleportPointType\&.MoveToLocation\fP"
.br
.ti -1c
.RI "string \fBtitle\fP"
.br
.ti -1c
.RI "string \fBswitchToScene\fP"
.br
.ti -1c
.RI "Color \fBtitleVisibleColor\fP"
.br
.ti -1c
.RI "Color \fBtitleHighlightedColor\fP"
.br
.ti -1c
.RI "Color \fBtitleLockedColor\fP"
.br
.ti -1c
.RI "bool \fBplayerSpawnPoint\fP = false"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBshowReticle\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file TeleportPoint\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.InteractionSystem\&.TeleportPoint\&.TeleportPointType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMoveToLocation \fP\fP
.TP
\fB\fISwitchToNewScene \fP\fP
.PP
Definition at line 18 of file TeleportPoint\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.GetRelevantComponents ()"

.PP
Definition at line 234 of file TeleportPoint\&.cs\&.
.SS "override void Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.Highlight (bool highlight)\fC [virtual]\fP"

.PP
Implements \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.PP
Definition at line 119 of file TeleportPoint\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.ReleaseRelevantComponents ()"

.PP
Definition at line 249 of file TeleportPoint\&.cs\&.
.SS "override void Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.SetAlpha (float tintAlpha, float alphaPercent)\fC [virtual]\fP"

.PP
Implements \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.PP
Definition at line 190 of file TeleportPoint\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.SetMeshMaterials (Material material, Color textColor)"

.PP
Definition at line 206 of file TeleportPoint\&.cs\&.
.SS "override bool Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.ShouldActivate (Vector3 playerPosition)\fC [virtual]\fP"

.PP
Implements \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.PP
Definition at line 105 of file TeleportPoint\&.cs\&.
.SS "override bool Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.ShouldMovePlayer ()\fC [virtual]\fP"

.PP
Implements \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.PP
Definition at line 112 of file TeleportPoint\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.TeleportToScene ()"

.PP
Definition at line 220 of file TeleportPoint\&.cs\&.
.SS "override void Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.UpdateVisuals ()\fC [virtual]\fP"

.PP
Implements \fBValve\&.VR\&.InteractionSystem\&.TeleportMarkerBase\fP\&.
.PP
Definition at line 147 of file TeleportPoint\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.UpdateVisualsInEditor ()"

.PP
Definition at line 261 of file TeleportPoint\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.playerSpawnPoint = false"

.PP
Definition at line 31 of file TeleportPoint\&.cs\&.
.SS "string Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.switchToScene"

.PP
Definition at line 27 of file TeleportPoint\&.cs\&.
.SS "\fBTeleportPointType\fP Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.teleportType = \fBTeleportPointType\&.MoveToLocation\fP"

.PP
Definition at line 25 of file TeleportPoint\&.cs\&.
.SS "string Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.title"

.PP
Definition at line 26 of file TeleportPoint\&.cs\&.
.SS "Color Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.titleHighlightedColor"

.PP
Definition at line 29 of file TeleportPoint\&.cs\&.
.SS "Color Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.titleLockedColor"

.PP
Definition at line 30 of file TeleportPoint\&.cs\&.
.SS "Color Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.titleVisibleColor"

.PP
Definition at line 28 of file TeleportPoint\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override bool Valve\&.VR\&.InteractionSystem\&.TeleportPoint\&.showReticle\fC [get]\fP"

.PP
Definition at line 58 of file TeleportPoint\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
