.TH "Valve.VR.InteractionSystem.DebugUI" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.DebugUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBDebugUI\fP \fBinstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file DebugUI\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBDebugUI\fP Valve\&.VR\&.InteractionSystem\&.DebugUI\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 21 of file DebugUI\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
