.TH "Valve.VR.InteractionSystem.Equippable" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Equippable
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform [] \fBantiFlip\fP"
.br
.ti -1c
.RI "\fBWhichHand\fP \fBdefaultHand\fP = \fBWhichHand\&.Right\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBattachedHandType\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Equippable\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform [] Valve\&.VR\&.InteractionSystem\&.Equippable\&.antiFlip"

.PP
Definition at line 26 of file Equippable\&.cs\&.
.SS "\fBWhichHand\fP Valve\&.VR\&.InteractionSystem\&.Equippable\&.defaultHand = \fBWhichHand\&.Right\fP"

.PP
Definition at line 28 of file Equippable\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.InteractionSystem\&.Equippable\&.attachedHandType\fC [get]\fP"

.PP
Definition at line 35 of file Equippable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
