.TH "Valve.VR.Extras.SteamVR_LaserPointer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.Extras.SteamVR_LaserPointer
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnPointerIn\fP (\fBPointerEventArgs\fP e)"
.br
.ti -1c
.RI "virtual void \fBOnPointerClick\fP (\fBPointerEventArgs\fP e)"
.br
.ti -1c
.RI "virtual void \fBOnPointerOut\fP (\fBPointerEventArgs\fP e)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_Behaviour_Pose\fP \fBpose\fP"
.br
.ti -1c
.RI "\fBSteamVR_Action_Boolean\fP \fBinteractWithUI\fP = \fBSteamVR_Input\&.GetBooleanAction\fP('InteractUI')"
.br
.ti -1c
.RI "bool \fBactive\fP = true"
.br
.ti -1c
.RI "Color \fBcolor\fP"
.br
.ti -1c
.RI "float \fBthickness\fP = 0\&.002f"
.br
.ti -1c
.RI "Color \fBclickColor\fP = Color\&.green"
.br
.ti -1c
.RI "GameObject \fBholder\fP"
.br
.ti -1c
.RI "GameObject \fBpointer\fP"
.br
.ti -1c
.RI "bool \fBaddRigidBody\fP = false"
.br
.ti -1c
.RI "Transform \fBreference\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "\fBPointerEventHandler\fP \fBPointerIn\fP"
.br
.ti -1c
.RI "\fBPointerEventHandler\fP \fBPointerOut\fP"
.br
.ti -1c
.RI "\fBPointerEventHandler\fP \fBPointerClick\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file SteamVR_LaserPointer\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.OnPointerClick (\fBPointerEventArgs\fP e)\fC [virtual]\fP"

.PP
Definition at line 79 of file SteamVR_LaserPointer\&.cs\&.
.SS "virtual void Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.OnPointerIn (\fBPointerEventArgs\fP e)\fC [virtual]\fP"

.PP
Definition at line 73 of file SteamVR_LaserPointer\&.cs\&.
.SS "virtual void Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.OnPointerOut (\fBPointerEventArgs\fP e)\fC [virtual]\fP"

.PP
Definition at line 85 of file SteamVR_LaserPointer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.active = true"

.PP
Definition at line 14 of file SteamVR_LaserPointer\&.cs\&.
.SS "bool Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.addRigidBody = false"

.PP
Definition at line 21 of file SteamVR_LaserPointer\&.cs\&.
.SS "Color Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.clickColor = Color\&.green"

.PP
Definition at line 17 of file SteamVR_LaserPointer\&.cs\&.
.SS "Color Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.color"

.PP
Definition at line 15 of file SteamVR_LaserPointer\&.cs\&.
.SS "GameObject Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.holder"

.PP
Definition at line 18 of file SteamVR_LaserPointer\&.cs\&.
.SS "\fBSteamVR_Action_Boolean\fP Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.interactWithUI = \fBSteamVR_Input\&.GetBooleanAction\fP('InteractUI')"

.PP
Definition at line 12 of file SteamVR_LaserPointer\&.cs\&.
.SS "GameObject Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.pointer"

.PP
Definition at line 19 of file SteamVR_LaserPointer\&.cs\&.
.SS "\fBSteamVR_Behaviour_Pose\fP Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.pose"

.PP
Definition at line 9 of file SteamVR_LaserPointer\&.cs\&.
.SS "Transform Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.reference"

.PP
Definition at line 22 of file SteamVR_LaserPointer\&.cs\&.
.SS "float Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.thickness = 0\&.002f"

.PP
Definition at line 16 of file SteamVR_LaserPointer\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "\fBPointerEventHandler\fP Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.PointerClick"

.PP
Definition at line 25 of file SteamVR_LaserPointer\&.cs\&.
.SS "\fBPointerEventHandler\fP Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.PointerIn"

.PP
Definition at line 23 of file SteamVR_LaserPointer\&.cs\&.
.SS "\fBPointerEventHandler\fP Valve\&.VR\&.Extras\&.SteamVR_LaserPointer\&.PointerOut"

.PP
Definition at line 24 of file SteamVR_LaserPointer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
