.TH "Valve.VR.InteractionSystem.LinearMapping" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.LinearMapping
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file LinearMapping\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.InteractionSystem\&.LinearMapping\&.value"

.PP
Definition at line 15 of file LinearMapping\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
