.TH "Valve.VR.InteractionSystem.Arrow" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Arrow
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBArrowReleased\fP (float inputVelocity)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ParticleSystem \fBglintParticle\fP"
.br
.ti -1c
.RI "Rigidbody \fBarrowHeadRB\fP"
.br
.ti -1c
.RI "Rigidbody \fBshaftRB\fP"
.br
.ti -1c
.RI "PhysicMaterial \fBtargetPhysMaterial\fP"
.br
.ti -1c
.RI "\fBSoundPlayOneshot\fP \fBfireReleaseSound\fP"
.br
.ti -1c
.RI "\fBSoundPlayOneshot\fP \fBairReleaseSound\fP"
.br
.ti -1c
.RI "\fBSoundPlayOneshot\fP \fBhitTargetSound\fP"
.br
.ti -1c
.RI "\fBPlaySound\fP \fBhitGroundSound\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetCollisionMode\fP (CollisionDetectionMode newMode, bool force=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file Arrow\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.Arrow\&.ArrowReleased (float inputVelocity)"

.PP
Definition at line 63 of file Arrow\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.Arrow\&.SetCollisionMode (CollisionDetectionMode newMode, bool force = \fCfalse\fP)\fC [protected]\fP"

.PP
Definition at line 102 of file Arrow\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSoundPlayOneshot\fP Valve\&.VR\&.InteractionSystem\&.Arrow\&.airReleaseSound"

.PP
Definition at line 27 of file Arrow\&.cs\&.
.SS "Rigidbody Valve\&.VR\&.InteractionSystem\&.Arrow\&.arrowHeadRB"

.PP
Definition at line 16 of file Arrow\&.cs\&.
.SS "\fBSoundPlayOneshot\fP Valve\&.VR\&.InteractionSystem\&.Arrow\&.fireReleaseSound"

.PP
Definition at line 26 of file Arrow\&.cs\&.
.SS "ParticleSystem Valve\&.VR\&.InteractionSystem\&.Arrow\&.glintParticle"

.PP
Definition at line 15 of file Arrow\&.cs\&.
.SS "\fBPlaySound\fP Valve\&.VR\&.InteractionSystem\&.Arrow\&.hitGroundSound"

.PP
Definition at line 30 of file Arrow\&.cs\&.
.SS "\fBSoundPlayOneshot\fP Valve\&.VR\&.InteractionSystem\&.Arrow\&.hitTargetSound"

.PP
Definition at line 28 of file Arrow\&.cs\&.
.SS "Rigidbody Valve\&.VR\&.InteractionSystem\&.Arrow\&.shaftRB"

.PP
Definition at line 17 of file Arrow\&.cs\&.
.SS "PhysicMaterial Valve\&.VR\&.InteractionSystem\&.Arrow\&.targetPhysMaterial"

.PP
Definition at line 19 of file Arrow\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
