.TH "Valve.VR.SteamVR_Input_ActionSet_default" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_ActionSet_default
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_ActionSet\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBSteamVR_Action_Boolean\fP \fBInteractUI\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBSteamVR_Action_Boolean\fP \fBTeleport\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBSteamVR_Action_Boolean\fP \fBGrabPinch\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBSteamVR_Action_Boolean\fP \fBGrabGrip\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBSteamVR_Action_Pose\fP \fBPose\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBSteamVR_Action_Skeleton\fP \fBSkeletonLeftHand\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBSteamVR_Action_Skeleton\fP \fBSkeletonRightHand\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBSteamVR_Action_Single\fP \fBSqueeze\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBSteamVR_Action_Boolean\fP \fBHeadsetOnHead\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBSteamVR_Action_Vibration\fP \fBHaptic\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file SteamVR_Input_ActionSet_default\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual \fBSteamVR_Action_Boolean\fP Valve\&.VR\&.SteamVR_Input_ActionSet_default\&.GrabGrip\fC [get]\fP"

.PP
Definition at line 45 of file SteamVR_Input_ActionSet_default\&.cs\&.
.SS "virtual \fBSteamVR_Action_Boolean\fP Valve\&.VR\&.SteamVR_Input_ActionSet_default\&.GrabPinch\fC [get]\fP"

.PP
Definition at line 37 of file SteamVR_Input_ActionSet_default\&.cs\&.
.SS "virtual \fBSteamVR_Action_Vibration\fP Valve\&.VR\&.SteamVR_Input_ActionSet_default\&.Haptic\fC [get]\fP"

.PP
Definition at line 93 of file SteamVR_Input_ActionSet_default\&.cs\&.
.SS "virtual \fBSteamVR_Action_Boolean\fP Valve\&.VR\&.SteamVR_Input_ActionSet_default\&.HeadsetOnHead\fC [get]\fP"

.PP
Definition at line 85 of file SteamVR_Input_ActionSet_default\&.cs\&.
.SS "virtual \fBSteamVR_Action_Boolean\fP Valve\&.VR\&.SteamVR_Input_ActionSet_default\&.InteractUI\fC [get]\fP"

.PP
Definition at line 21 of file SteamVR_Input_ActionSet_default\&.cs\&.
.SS "virtual \fBSteamVR_Action_Pose\fP Valve\&.VR\&.SteamVR_Input_ActionSet_default\&.Pose\fC [get]\fP"

.PP
Definition at line 53 of file SteamVR_Input_ActionSet_default\&.cs\&.
.SS "virtual \fBSteamVR_Action_Skeleton\fP Valve\&.VR\&.SteamVR_Input_ActionSet_default\&.SkeletonLeftHand\fC [get]\fP"

.PP
Definition at line 61 of file SteamVR_Input_ActionSet_default\&.cs\&.
.SS "virtual \fBSteamVR_Action_Skeleton\fP Valve\&.VR\&.SteamVR_Input_ActionSet_default\&.SkeletonRightHand\fC [get]\fP"

.PP
Definition at line 69 of file SteamVR_Input_ActionSet_default\&.cs\&.
.SS "virtual \fBSteamVR_Action_Single\fP Valve\&.VR\&.SteamVR_Input_ActionSet_default\&.Squeeze\fC [get]\fP"

.PP
Definition at line 77 of file SteamVR_Input_ActionSet_default\&.cs\&.
.SS "virtual \fBSteamVR_Action_Boolean\fP Valve\&.VR\&.SteamVR_Input_ActionSet_default\&.Teleport\fC [get]\fP"

.PP
Definition at line 29 of file SteamVR_Input_ActionSet_default\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
