.TH "Valve.VR.SteamVR_Input_ActionFile" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_ActionFile
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeHelperLists\fP ()"
.br
.ti -1c
.RI "void \fBSaveHelperLists\fP ()"
.br
.ti -1c
.RI "string [] \fBGetFilesToCopy\fP (bool throwErrors=false)"
.br
.ti -1c
.RI "void \fBCopyFilesToPath\fP (string toPath, bool overwrite)"
.br
.ti -1c
.RI "bool \fBIsInStreamingAssets\fP ()"
.br
.ti -1c
.RI "void \fBSave\fP (string path)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetShortName\fP (string name)"
.br
.ti -1c
.RI "static string \fBGetCodeFriendlyName\fP (string name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBSteamVR_Input_ActionFile_Action\fP > \fBactions\fP = new List<\fBSteamVR_Input_ActionFile_Action\fP>()"
.br
.ti -1c
.RI "List< \fBSteamVR_Input_ActionFile_ActionSet\fP > \fBaction_sets\fP = new List<\fBSteamVR_Input_ActionFile_ActionSet\fP>()"
.br
.ti -1c
.RI "List< \fBSteamVR_Input_ActionFile_DefaultBinding\fP > \fBdefault_bindings\fP = new List<\fBSteamVR_Input_ActionFile_DefaultBinding\fP>()"
.br
.ti -1c
.RI "List< Dictionary< string, string > > \fBlocalization\fP = new List<Dictionary<string, string>>()"
.br
.ti -1c
.RI "List< \fBSteamVR_Input_ActionFile_LocalizationItem\fP > \fBlocalizationHelperList\fP = new List<\fBSteamVR_Input_ActionFile_LocalizationItem\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file SteamVR_Input_ActionFile\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Input_ActionFile\&.CopyFilesToPath (string toPath, bool overwrite)"

.PP
Definition at line 139 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "static string Valve\&.VR\&.SteamVR_Input_ActionFile\&.GetCodeFriendlyName (string name)\fC [static]\fP"

.PP
Definition at line 93 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "string [] Valve\&.VR\&.SteamVR_Input_ActionFile\&.GetFilesToCopy (bool throwErrors = \fCfalse\fP)"

.PP
Definition at line 112 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "static string Valve\&.VR\&.SteamVR_Input_ActionFile\&.GetShortName (string name)\fC [static]\fP"

.PP
Definition at line 72 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Input_ActionFile\&.InitializeHelperLists ()"

.PP
Definition at line 24 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Input_ActionFile\&.IsInStreamingAssets ()"

.PP
Definition at line 183 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Input_ActionFile\&.Save (string path)"

.PP
Definition at line 221 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Input_ActionFile\&.SaveHelperLists ()"

.PP
Definition at line 39 of file SteamVR_Input_ActionFile\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBSteamVR_Input_ActionFile_ActionSet\fP> Valve\&.VR\&.SteamVR_Input_ActionFile\&.action_sets = new List<\fBSteamVR_Input_ActionFile_ActionSet\fP>()"

.PP
Definition at line 17 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "List<\fBSteamVR_Input_ActionFile_Action\fP> Valve\&.VR\&.SteamVR_Input_ActionFile\&.actions = new List<\fBSteamVR_Input_ActionFile_Action\fP>()"

.PP
Definition at line 16 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "List<\fBSteamVR_Input_ActionFile_DefaultBinding\fP> Valve\&.VR\&.SteamVR_Input_ActionFile\&.default_bindings = new List<\fBSteamVR_Input_ActionFile_DefaultBinding\fP>()"

.PP
Definition at line 18 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "List<Dictionary<string, string> > Valve\&.VR\&.SteamVR_Input_ActionFile\&.localization = new List<Dictionary<string, string>>()"

.PP
Definition at line 19 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "List<\fBSteamVR_Input_ActionFile_LocalizationItem\fP> Valve\&.VR\&.SteamVR_Input_ActionFile\&.localizationHelperList = new List<\fBSteamVR_Input_ActionFile_LocalizationItem\fP>()"

.PP
Definition at line 22 of file SteamVR_Input_ActionFile\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
