.TH "Valve.VR.ISteamVR_Action_Boolean" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.ISteamVR_Action_Boolean
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.ISteamVR_Action_In_Source\fP\&.
.PP
Inherited by \fBValve\&.VR\&.SteamVR_Action_Boolean\fP, and \fBValve\&.VR\&.SteamVR_Action_Boolean_Source\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBstate\fP\fC [get]\fP"
.br
.RI "The current value of the boolean action\&. Note: Will only return true if the action is also active\&. "
.ti -1c
.RI "bool \fBstateDown\fP\fC [get]\fP"
.br
.RI "True when the action's state changes from false to true\&. Note: Will only return true if the action is also active\&. "
.ti -1c
.RI "bool \fBstateUp\fP\fC [get]\fP"
.br
.RI "True when the action's state changes from true to false\&. Note: Will only return true if the action is also active\&. "
.ti -1c
.RI "bool \fBlastState\fP\fC [get]\fP"
.br
.RI "The value of the action's 'state' during the previous update "
.ti -1c
.RI "bool \fBlastStateDown\fP\fC [get]\fP"
.br
.RI "The value of the action's 'stateDown' during the previous update "
.ti -1c
.RI "bool \fBlastStateUp\fP\fC [get]\fP"
.br
.RI "The value of the action's 'stateUp' during the previous update "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 386 of file SteamVR_Action_Boolean\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Valve\&.VR\&.ISteamVR_Action_Boolean\&.lastState\fC [get]\fP"

.PP
The value of the action's 'state' during the previous update Always returns the previous update state
.PP
Definition at line 399 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.ISteamVR_Action_Boolean\&.lastStateDown\fC [get]\fP"

.PP
The value of the action's 'stateDown' during the previous update Always returns the previous update state
.PP
Definition at line 403 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.ISteamVR_Action_Boolean\&.lastStateUp\fC [get]\fP"

.PP
The value of the action's 'stateUp' during the previous update Always returns the previous update state
.PP
Definition at line 407 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.ISteamVR_Action_Boolean\&.state\fC [get]\fP"

.PP
The current value of the boolean action\&. Note: Will only return true if the action is also active\&. 
.PP
Definition at line 389 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.ISteamVR_Action_Boolean\&.stateDown\fC [get]\fP"

.PP
True when the action's state changes from false to true\&. Note: Will only return true if the action is also active\&. 
.PP
Definition at line 392 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.ISteamVR_Action_Boolean\&.stateUp\fC [get]\fP"

.PP
True when the action's state changes from true to false\&. Note: Will only return true if the action is also active\&. 
.PP
Definition at line 395 of file SteamVR_Action_Boolean\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
