.TH "Valve.VR.IVRResources" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.IVRResources
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal delegate uint \fB_LoadSharedResource\fP (string pchResourceName, string pchBuffer, uint unBufferLen)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetResourceFullPath\fP (string pchResourceName, string pchResourceTypeDirectory, System\&.Text\&.StringBuilder pchPathBuffer, uint unBufferLen)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internal \fB_LoadSharedResource\fP \fBLoadSharedResource\fP"
.br
.ti -1c
.RI "internal \fB_GetResourceFullPath\fP \fBGetResourceFullPath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1506 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "internal delegate uint Valve\&.VR\&.IVRResources\&._GetResourceFullPath (string pchResourceName, string pchResourceTypeDirectory, System\&.Text\&.StringBuilder pchPathBuffer, uint unBufferLen)"

.SS "internal delegate uint Valve\&.VR\&.IVRResources\&._LoadSharedResource (string pchResourceName, string pchBuffer, uint unBufferLen)"

.SH "Member Data Documentation"
.PP 
.SS "internal \fB_GetResourceFullPath\fP Valve\&.VR\&.IVRResources\&.GetResourceFullPath"

.PP
Definition at line 1516 of file openvr_api\&.cs\&.
.SS "internal \fB_LoadSharedResource\fP Valve\&.VR\&.IVRResources\&.LoadSharedResource"

.PP
Definition at line 1511 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
