.TH "Valve.VR.SteamVR_Settings" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Settings
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsInputUpdateMode\fP (\fBSteamVR_UpdateModes\fP tocheck)"
.br
.ti -1c
.RI "bool \fBIsPoseUpdateMode\fP (\fBSteamVR_UpdateModes\fP tocheck)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBVerifyScriptableObject\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBpauseGameWhenDashboardVisible\fP = true"
.br
.ti -1c
.RI "bool \fBlockPhysicsUpdateRateToRenderFrequency\fP = true"
.br
.ti -1c
.RI "\fBValve\&.VR\&.ETrackingUniverseOrigin\fP \fBtrackingSpace\fP = \fBValve\&.VR\&.ETrackingUniverseOrigin\&.TrackingUniverseStanding\fP"
.br
.ti -1c
.RI "string \fBactionsFilePath\fP = 'actions\&.json'"
.br
.ti -1c
.RI "string \fBsteamVRInputPath\fP = 'SteamVR_Input'"
.br
.ti -1c
.RI "\fBSteamVR_UpdateModes\fP \fBinputUpdateMode\fP = \fBSteamVR_UpdateModes\&.OnUpdate\fP"
.br
.ti -1c
.RI "\fBSteamVR_UpdateModes\fP \fBposeUpdateMode\fP = \fBSteamVR_UpdateModes\&.OnPreCull\fP"
.br
.ti -1c
.RI "bool \fBactivateFirstActionSetOnStart\fP = true"
.br
.ti -1c
.RI "string \fBeditorAppKey\fP"
.br
.ti -1c
.RI "bool \fBautoEnableVR\fP = true"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSteamVR_Settings\fP \fBinstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file SteamVR_Settings\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_Settings\&.IsInputUpdateMode (\fBSteamVR_UpdateModes\fP tocheck)"

.PP
Definition at line 44 of file SteamVR_Settings\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Settings\&.IsPoseUpdateMode (\fBSteamVR_UpdateModes\fP tocheck)"

.PP
Definition at line 48 of file SteamVR_Settings\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Settings\&.VerifyScriptableObject ()\fC [static]\fP"

.PP
Definition at line 53 of file SteamVR_Settings\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Valve\&.VR\&.SteamVR_Settings\&.actionsFilePath = 'actions\&.json'"

.PP
Definition at line 28 of file SteamVR_Settings\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Settings\&.activateFirstActionSetOnStart = true"

.PP
Definition at line 36 of file SteamVR_Settings\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Settings\&.autoEnableVR = true"

.PP
Definition at line 42 of file SteamVR_Settings\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Settings\&.editorAppKey"

.PP
Definition at line 39 of file SteamVR_Settings\&.cs\&.
.SS "\fBSteamVR_UpdateModes\fP Valve\&.VR\&.SteamVR_Settings\&.inputUpdateMode = \fBSteamVR_UpdateModes\&.OnUpdate\fP"

.PP
Definition at line 33 of file SteamVR_Settings\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Settings\&.lockPhysicsUpdateRateToRenderFrequency = true"

.PP
Definition at line 24 of file SteamVR_Settings\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Settings\&.pauseGameWhenDashboardVisible = true"

.PP
Definition at line 23 of file SteamVR_Settings\&.cs\&.
.SS "\fBSteamVR_UpdateModes\fP Valve\&.VR\&.SteamVR_Settings\&.poseUpdateMode = \fBSteamVR_UpdateModes\&.OnPreCull\fP"

.PP
Definition at line 34 of file SteamVR_Settings\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Settings\&.steamVRInputPath = 'SteamVR_Input'"

.PP
Definition at line 31 of file SteamVR_Settings\&.cs\&.
.SS "\fBValve\&.VR\&.ETrackingUniverseOrigin\fP Valve\&.VR\&.SteamVR_Settings\&.trackingSpace = \fBValve\&.VR\&.ETrackingUniverseOrigin\&.TrackingUniverseStanding\fP"

.PP
Definition at line 25 of file SteamVR_Settings\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBSteamVR_Settings\fP Valve\&.VR\&.SteamVR_Settings\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 14 of file SteamVR_Settings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
