.TH "Valve.VR.CVRApplications" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.CVRApplications
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEVRApplicationError\fP \fBAddApplicationManifest\fP (string pchApplicationManifestFullPath, bool bTemporary)"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBRemoveApplicationManifest\fP (string pchApplicationManifestFullPath)"
.br
.ti -1c
.RI "bool \fBIsApplicationInstalled\fP (string pchAppKey)"
.br
.ti -1c
.RI "uint \fBGetApplicationCount\fP ()"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBGetApplicationKeyByIndex\fP (uint unApplicationIndex, System\&.Text\&.StringBuilder pchAppKeyBuffer, uint unAppKeyBufferLen)"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBGetApplicationKeyByProcessId\fP (uint unProcessId, System\&.Text\&.StringBuilder pchAppKeyBuffer, uint unAppKeyBufferLen)"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBLaunchApplication\fP (string pchAppKey)"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBLaunchTemplateApplication\fP (string pchTemplateAppKey, string pchNewAppKey, \fBAppOverrideKeys_t\fP [] pKeys)"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBLaunchApplicationFromMimeType\fP (string pchMimeType, string pchArgs)"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBLaunchDashboardOverlay\fP (string pchAppKey)"
.br
.ti -1c
.RI "bool \fBCancelApplicationLaunch\fP (string pchAppKey)"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBIdentifyApplication\fP (uint unProcessId, string pchAppKey)"
.br
.ti -1c
.RI "uint \fBGetApplicationProcessId\fP (string pchAppKey)"
.br
.ti -1c
.RI "string \fBGetApplicationsErrorNameFromEnum\fP (\fBEVRApplicationError\fP error)"
.br
.ti -1c
.RI "uint \fBGetApplicationPropertyString\fP (string pchAppKey, \fBEVRApplicationProperty\fP eProperty, System\&.Text\&.StringBuilder pchPropertyValueBuffer, uint unPropertyValueBufferLen, ref \fBEVRApplicationError\fP peError)"
.br
.ti -1c
.RI "bool \fBGetApplicationPropertyBool\fP (string pchAppKey, \fBEVRApplicationProperty\fP eProperty, ref \fBEVRApplicationError\fP peError)"
.br
.ti -1c
.RI "ulong \fBGetApplicationPropertyUint64\fP (string pchAppKey, \fBEVRApplicationProperty\fP eProperty, ref \fBEVRApplicationError\fP peError)"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBSetApplicationAutoLaunch\fP (string pchAppKey, bool bAutoLaunch)"
.br
.ti -1c
.RI "bool \fBGetApplicationAutoLaunch\fP (string pchAppKey)"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBSetDefaultApplicationForMimeType\fP (string pchAppKey, string pchMimeType)"
.br
.ti -1c
.RI "bool \fBGetDefaultApplicationForMimeType\fP (string pchMimeType, System\&.Text\&.StringBuilder pchAppKeyBuffer, uint unAppKeyBufferLen)"
.br
.ti -1c
.RI "bool \fBGetApplicationSupportedMimeTypes\fP (string pchAppKey, System\&.Text\&.StringBuilder pchMimeTypesBuffer, uint unMimeTypesBuffer)"
.br
.ti -1c
.RI "uint \fBGetApplicationsThatSupportMimeType\fP (string pchMimeType, System\&.Text\&.StringBuilder pchAppKeysThatSupportBuffer, uint unAppKeysThatSupportBuffer)"
.br
.ti -1c
.RI "uint \fBGetApplicationLaunchArguments\fP (uint unHandle, System\&.Text\&.StringBuilder pchArgs, uint unArgs)"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBGetStartingApplication\fP (System\&.Text\&.StringBuilder pchAppKeyBuffer, uint unAppKeyBufferLen)"
.br
.ti -1c
.RI "\fBEVRApplicationTransitionState\fP \fBGetTransitionState\fP ()"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBPerformApplicationPrelaunchCheck\fP (string pchAppKey)"
.br
.ti -1c
.RI "string \fBGetApplicationsTransitionStateNameFromEnum\fP (\fBEVRApplicationTransitionState\fP state)"
.br
.ti -1c
.RI "bool \fBIsQuitUserPromptRequested\fP ()"
.br
.ti -1c
.RI "\fBEVRApplicationError\fP \fBLaunchInternalProcess\fP (string pchBinaryPath, string pchArguments, string pchWorkingDirectory)"
.br
.ti -1c
.RI "uint \fBGetCurrentSceneProcessId\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2159 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.AddApplicationManifest (string pchApplicationManifestFullPath, bool bTemporary)"

.PP
Definition at line 2166 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRApplications\&.CancelApplicationLaunch (string pchAppKey)"

.PP
Definition at line 2216 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRApplications\&.GetApplicationAutoLaunch (string pchAppKey)"

.PP
Definition at line 2256 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVRApplications\&.GetApplicationCount ()"

.PP
Definition at line 2181 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.GetApplicationKeyByIndex (uint unApplicationIndex, System\&.Text\&.StringBuilder pchAppKeyBuffer, uint unAppKeyBufferLen)"

.PP
Definition at line 2186 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.GetApplicationKeyByProcessId (uint unProcessId, System\&.Text\&.StringBuilder pchAppKeyBuffer, uint unAppKeyBufferLen)"

.PP
Definition at line 2191 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVRApplications\&.GetApplicationLaunchArguments (uint unHandle, System\&.Text\&.StringBuilder pchArgs, uint unArgs)"

.PP
Definition at line 2281 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVRApplications\&.GetApplicationProcessId (string pchAppKey)"

.PP
Definition at line 2226 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRApplications\&.GetApplicationPropertyBool (string pchAppKey, \fBEVRApplicationProperty\fP eProperty, ref \fBEVRApplicationError\fP peError)"

.PP
Definition at line 2241 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVRApplications\&.GetApplicationPropertyString (string pchAppKey, \fBEVRApplicationProperty\fP eProperty, System\&.Text\&.StringBuilder pchPropertyValueBuffer, uint unPropertyValueBufferLen, ref \fBEVRApplicationError\fP peError)"

.PP
Definition at line 2236 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.CVRApplications\&.GetApplicationPropertyUint64 (string pchAppKey, \fBEVRApplicationProperty\fP eProperty, ref \fBEVRApplicationError\fP peError)"

.PP
Definition at line 2246 of file openvr_api\&.cs\&.
.SS "string Valve\&.VR\&.CVRApplications\&.GetApplicationsErrorNameFromEnum (\fBEVRApplicationError\fP error)"

.PP
Definition at line 2231 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVRApplications\&.GetApplicationsThatSupportMimeType (string pchMimeType, System\&.Text\&.StringBuilder pchAppKeysThatSupportBuffer, uint unAppKeysThatSupportBuffer)"

.PP
Definition at line 2276 of file openvr_api\&.cs\&.
.SS "string Valve\&.VR\&.CVRApplications\&.GetApplicationsTransitionStateNameFromEnum (\fBEVRApplicationTransitionState\fP state)"

.PP
Definition at line 2301 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRApplications\&.GetApplicationSupportedMimeTypes (string pchAppKey, System\&.Text\&.StringBuilder pchMimeTypesBuffer, uint unMimeTypesBuffer)"

.PP
Definition at line 2271 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVRApplications\&.GetCurrentSceneProcessId ()"

.PP
Definition at line 2316 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRApplications\&.GetDefaultApplicationForMimeType (string pchMimeType, System\&.Text\&.StringBuilder pchAppKeyBuffer, uint unAppKeyBufferLen)"

.PP
Definition at line 2266 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.GetStartingApplication (System\&.Text\&.StringBuilder pchAppKeyBuffer, uint unAppKeyBufferLen)"

.PP
Definition at line 2286 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationTransitionState\fP Valve\&.VR\&.CVRApplications\&.GetTransitionState ()"

.PP
Definition at line 2291 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.IdentifyApplication (uint unProcessId, string pchAppKey)"

.PP
Definition at line 2221 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRApplications\&.IsApplicationInstalled (string pchAppKey)"

.PP
Definition at line 2176 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRApplications\&.IsQuitUserPromptRequested ()"

.PP
Definition at line 2306 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.LaunchApplication (string pchAppKey)"

.PP
Definition at line 2196 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.LaunchApplicationFromMimeType (string pchMimeType, string pchArgs)"

.PP
Definition at line 2206 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.LaunchDashboardOverlay (string pchAppKey)"

.PP
Definition at line 2211 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.LaunchInternalProcess (string pchBinaryPath, string pchArguments, string pchWorkingDirectory)"

.PP
Definition at line 2311 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.LaunchTemplateApplication (string pchTemplateAppKey, string pchNewAppKey, \fBAppOverrideKeys_t\fP [] pKeys)"

.PP
Definition at line 2201 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.PerformApplicationPrelaunchCheck (string pchAppKey)"

.PP
Definition at line 2296 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.RemoveApplicationManifest (string pchApplicationManifestFullPath)"

.PP
Definition at line 2171 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.SetApplicationAutoLaunch (string pchAppKey, bool bAutoLaunch)"

.PP
Definition at line 2251 of file openvr_api\&.cs\&.
.SS "\fBEVRApplicationError\fP Valve\&.VR\&.CVRApplications\&.SetDefaultApplicationForMimeType (string pchAppKey, string pchMimeType)"

.PP
Definition at line 2261 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
