.TH "Valve.VR.SteamVR_TrackedCamera" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_TrackedCamera
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVideoStreamTexture\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBVideoStreamTexture\fP \fBDistorted\fP (int deviceIndex=(int) \fBOpenVR\&.k_unTrackedDeviceIndex_Hmd\fP)"
.br
.ti -1c
.RI "static \fBVideoStreamTexture\fP \fBUndistorted\fP (int deviceIndex=(int) \fBOpenVR\&.k_unTrackedDeviceIndex_Hmd\fP)"
.br
.ti -1c
.RI "static \fBVideoStreamTexture\fP \fBSource\fP (bool undistorted, int deviceIndex=(int) \fBOpenVR\&.k_unTrackedDeviceIndex_Hmd\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file SteamVR_TrackedCamera\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBVideoStreamTexture\fP Valve\&.VR\&.SteamVR_TrackedCamera\&.Distorted (int deviceIndex = \fC(int)\fBOpenVR\&.k_unTrackedDeviceIndex_Hmd\fP\fP)\fC [static]\fP"

.PP
Definition at line 137 of file SteamVR_TrackedCamera\&.cs\&.
.SS "static \fBVideoStreamTexture\fP Valve\&.VR\&.SteamVR_TrackedCamera\&.Source (bool undistorted, int deviceIndex = \fC(int)\fBOpenVR\&.k_unTrackedDeviceIndex_Hmd\fP\fP)\fC [static]\fP"

.PP
Definition at line 155 of file SteamVR_TrackedCamera\&.cs\&.
.SS "static \fBVideoStreamTexture\fP Valve\&.VR\&.SteamVR_TrackedCamera\&.Undistorted (int deviceIndex = \fC(int)\fBOpenVR\&.k_unTrackedDeviceIndex_Hmd\fP\fP)\fC [static]\fP"

.PP
Definition at line 146 of file SteamVR_TrackedCamera\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
