.TH "Valve.VR.SteamVR_Input_BindingFile_Source" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_BindingFile_Source
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetOutput\fP ()"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBpath\fP"
.br
.ti -1c
.RI "string \fBmode\fP"
.br
.ti -1c
.RI "\fBSteamVR_Input_BindingFile_Source_Input_StringDictionary\fP \fBparameters\fP = new \fBSteamVR_Input_BindingFile_Source_Input_StringDictionary\fP()"
.br
.ti -1c
.RI "\fBSteamVR_Input_BindingFile_Source_Input\fP \fBinputs\fP = new \fBSteamVR_Input_BindingFile_Source_Input\fP()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const string \fBoutputKeyName\fP = 'output'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 154 of file SteamVR_Input_BindingFile\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Valve\&.VR\&.SteamVR_Input_BindingFile_Source\&.Equals (object obj)"

.PP
Definition at line 179 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "override int Valve\&.VR\&.SteamVR_Input_BindingFile_Source\&.GetHashCode ()"

.PP
Definition at line 216 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input_BindingFile_Source\&.GetOutput ()"

.PP
Definition at line 163 of file SteamVR_Input_BindingFile\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSteamVR_Input_BindingFile_Source_Input\fP Valve\&.VR\&.SteamVR_Input_BindingFile_Source\&.inputs = new \fBSteamVR_Input_BindingFile_Source_Input\fP()"

.PP
Definition at line 159 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input_BindingFile_Source\&.mode"

.PP
Definition at line 157 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "const string Valve\&.VR\&.SteamVR_Input_BindingFile_Source\&.outputKeyName = 'output'\fC [protected]\fP"

.PP
Definition at line 161 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "\fBSteamVR_Input_BindingFile_Source_Input_StringDictionary\fP Valve\&.VR\&.SteamVR_Input_BindingFile_Source\&.parameters = new \fBSteamVR_Input_BindingFile_Source_Input_StringDictionary\fP()"

.PP
Definition at line 158 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input_BindingFile_Source\&.path"

.PP
Definition at line 156 of file SteamVR_Input_BindingFile\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
