.TH "Valve.VR.Compositor_FrameTiming" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.Compositor_FrameTiming
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint \fBm_nSize\fP"
.br
.ti -1c
.RI "uint \fBm_nFrameIndex\fP"
.br
.ti -1c
.RI "uint \fBm_nNumFramePresents\fP"
.br
.ti -1c
.RI "uint \fBm_nNumMisPresented\fP"
.br
.ti -1c
.RI "uint \fBm_nNumDroppedFrames\fP"
.br
.ti -1c
.RI "uint \fBm_nReprojectionFlags\fP"
.br
.ti -1c
.RI "double \fBm_flSystemTimeInSeconds\fP"
.br
.ti -1c
.RI "float \fBm_flPreSubmitGpuMs\fP"
.br
.ti -1c
.RI "float \fBm_flPostSubmitGpuMs\fP"
.br
.ti -1c
.RI "float \fBm_flTotalRenderGpuMs\fP"
.br
.ti -1c
.RI "float \fBm_flCompositorRenderGpuMs\fP"
.br
.ti -1c
.RI "float \fBm_flCompositorRenderCpuMs\fP"
.br
.ti -1c
.RI "float \fBm_flCompositorIdleCpuMs\fP"
.br
.ti -1c
.RI "float \fBm_flClientFrameIntervalMs\fP"
.br
.ti -1c
.RI "float \fBm_flPresentCallCpuMs\fP"
.br
.ti -1c
.RI "float \fBm_flWaitForPresentCpuMs\fP"
.br
.ti -1c
.RI "float \fBm_flSubmitFrameMs\fP"
.br
.ti -1c
.RI "float \fBm_flWaitGetPosesCalledMs\fP"
.br
.ti -1c
.RI "float \fBm_flNewPosesReadyMs\fP"
.br
.ti -1c
.RI "float \fBm_flNewFrameReadyMs\fP"
.br
.ti -1c
.RI "float \fBm_flCompositorUpdateStartMs\fP"
.br
.ti -1c
.RI "float \fBm_flCompositorUpdateEndMs\fP"
.br
.ti -1c
.RI "float \fBm_flCompositorRenderStartMs\fP"
.br
.ti -1c
.RI "\fBTrackedDevicePose_t\fP \fBm_HmdPose\fP"
.br
.ti -1c
.RI "uint \fBm_nNumVSyncsReadyForUse\fP"
.br
.ti -1c
.RI "uint \fBm_nNumVSyncsToFirstView\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5357 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flClientFrameIntervalMs"

.PP
Definition at line 5372 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flCompositorIdleCpuMs"

.PP
Definition at line 5371 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flCompositorRenderCpuMs"

.PP
Definition at line 5370 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flCompositorRenderGpuMs"

.PP
Definition at line 5369 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flCompositorRenderStartMs"

.PP
Definition at line 5381 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flCompositorUpdateEndMs"

.PP
Definition at line 5380 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flCompositorUpdateStartMs"

.PP
Definition at line 5379 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flNewFrameReadyMs"

.PP
Definition at line 5378 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flNewPosesReadyMs"

.PP
Definition at line 5377 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flPostSubmitGpuMs"

.PP
Definition at line 5367 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flPresentCallCpuMs"

.PP
Definition at line 5373 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flPreSubmitGpuMs"

.PP
Definition at line 5366 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flSubmitFrameMs"

.PP
Definition at line 5375 of file openvr_api\&.cs\&.
.SS "double Valve\&.VR\&.Compositor_FrameTiming\&.m_flSystemTimeInSeconds"

.PP
Definition at line 5365 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flTotalRenderGpuMs"

.PP
Definition at line 5368 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flWaitForPresentCpuMs"

.PP
Definition at line 5374 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.Compositor_FrameTiming\&.m_flWaitGetPosesCalledMs"

.PP
Definition at line 5376 of file openvr_api\&.cs\&.
.SS "\fBTrackedDevicePose_t\fP Valve\&.VR\&.Compositor_FrameTiming\&.m_HmdPose"

.PP
Definition at line 5382 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_FrameTiming\&.m_nFrameIndex"

.PP
Definition at line 5360 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_FrameTiming\&.m_nNumDroppedFrames"

.PP
Definition at line 5363 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_FrameTiming\&.m_nNumFramePresents"

.PP
Definition at line 5361 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_FrameTiming\&.m_nNumMisPresented"

.PP
Definition at line 5362 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_FrameTiming\&.m_nNumVSyncsReadyForUse"

.PP
Definition at line 5383 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_FrameTiming\&.m_nNumVSyncsToFirstView"

.PP
Definition at line 5384 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_FrameTiming\&.m_nReprojectionFlags"

.PP
Definition at line 5364 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.Compositor_FrameTiming\&.m_nSize"

.PP
Definition at line 5359 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
