.TH "Valve.VR.IVRIOBuffer" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.IVRIOBuffer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal delegate \fBEIOBufferError\fP \fB_Open\fP (string pchPath, \fBEIOBufferMode\fP mode, uint unElementSize, uint unElements, ref ulong pulBuffer)"
.br
.ti -1c
.RI "internal delegate \fBEIOBufferError\fP \fB_Close\fP (ulong ulBuffer)"
.br
.ti -1c
.RI "internal delegate \fBEIOBufferError\fP \fB_Read\fP (ulong ulBuffer, IntPtr pDst, uint unBytes, ref uint punRead)"
.br
.ti -1c
.RI "internal delegate \fBEIOBufferError\fP \fB_Write\fP (ulong ulBuffer, IntPtr pSrc, uint unBytes)"
.br
.ti -1c
.RI "internal delegate ulong \fB_PropertyContainer\fP (ulong ulBuffer)"
.br
.ti -1c
.RI "internal delegate bool \fB_HasReaders\fP (ulong ulBuffer)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internal \fB_Open\fP \fBOpen\fP"
.br
.ti -1c
.RI "internal \fB_Close\fP \fBClose\fP"
.br
.ti -1c
.RI "internal \fB_Read\fP \fBRead\fP"
.br
.ti -1c
.RI "internal \fB_Write\fP \fBWrite\fP"
.br
.ti -1c
.RI "internal \fB_PropertyContainer\fP \fBPropertyContainer\fP"
.br
.ti -1c
.RI "internal \fB_HasReaders\fP \fBHasReaders\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1666 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "internal delegate \fBEIOBufferError\fP Valve\&.VR\&.IVRIOBuffer\&._Close (ulong ulBuffer)"

.SS "internal delegate bool Valve\&.VR\&.IVRIOBuffer\&._HasReaders (ulong ulBuffer)"

.SS "internal delegate \fBEIOBufferError\fP Valve\&.VR\&.IVRIOBuffer\&._Open (string pchPath, \fBEIOBufferMode\fP mode, uint unElementSize, uint unElements, ref ulong pulBuffer)"

.SS "internal delegate ulong Valve\&.VR\&.IVRIOBuffer\&._PropertyContainer (ulong ulBuffer)"

.SS "internal delegate \fBEIOBufferError\fP Valve\&.VR\&.IVRIOBuffer\&._Read (ulong ulBuffer, IntPtr pDst, uint unBytes, ref uint punRead)"

.SS "internal delegate \fBEIOBufferError\fP Valve\&.VR\&.IVRIOBuffer\&._Write (ulong ulBuffer, IntPtr pSrc, uint unBytes)"

.SH "Member Data Documentation"
.PP 
.SS "internal \fB_Close\fP Valve\&.VR\&.IVRIOBuffer\&.Close"

.PP
Definition at line 1676 of file openvr_api\&.cs\&.
.SS "internal \fB_HasReaders\fP Valve\&.VR\&.IVRIOBuffer\&.HasReaders"

.PP
Definition at line 1696 of file openvr_api\&.cs\&.
.SS "internal \fB_Open\fP Valve\&.VR\&.IVRIOBuffer\&.Open"

.PP
Definition at line 1671 of file openvr_api\&.cs\&.
.SS "internal \fB_PropertyContainer\fP Valve\&.VR\&.IVRIOBuffer\&.PropertyContainer"

.PP
Definition at line 1691 of file openvr_api\&.cs\&.
.SS "internal \fB_Read\fP Valve\&.VR\&.IVRIOBuffer\&.Read"

.PP
Definition at line 1681 of file openvr_api\&.cs\&.
.SS "internal \fB_Write\fP Valve\&.VR\&.IVRIOBuffer\&.Write"

.PP
Definition at line 1686 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
