.TH "Valve.VR.SteamVR_Events.Event< T0, T1, T2 >" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Events.Event< T0, T1, T2 >
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEvent, UnityEvent< T0, T1 >, UnityEvent< T0, T1, T2 >, and UnityEvent< T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBListen\fP (UnityAction action)"
.br
.ti -1c
.RI "void \fBRemove\fP (UnityAction action)"
.br
.ti -1c
.RI "void \fBSend\fP ()"
.br
.ti -1c
.RI "void \fBListen\fP (UnityAction< T > action)"
.br
.ti -1c
.RI "void \fBRemove\fP (UnityAction< T > action)"
.br
.ti -1c
.RI "void \fBSend\fP (T arg0)"
.br
.ti -1c
.RI "void \fBListen\fP (UnityAction< T0, T1 > action)"
.br
.ti -1c
.RI "void \fBRemove\fP (UnityAction< T0, T1 > action)"
.br
.ti -1c
.RI "void \fBSend\fP (T0 arg0, T1 arg1)"
.br
.ti -1c
.RI "void \fBListen\fP (UnityAction< T0, T1, T2 > action)"
.br
.ti -1c
.RI "void \fBRemove\fP (UnityAction< T0, T1, T2 > action)"
.br
.ti -1c
.RI "void \fBSend\fP (T0 arg0, T1 arg1, T2 arg2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 139 of file SteamVR_Events\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Listen (UnityAction action)"

.PP
Definition at line 120 of file SteamVR_Events\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Listen (UnityAction< T > action)"

.PP
Definition at line 127 of file SteamVR_Events\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Listen (UnityAction< T0, T1 > action)"

.PP
Definition at line 134 of file SteamVR_Events\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Listen (UnityAction< T0, T1, T2 > action)"

.PP
Definition at line 141 of file SteamVR_Events\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Remove (UnityAction action)"

.PP
Definition at line 121 of file SteamVR_Events\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Remove (UnityAction< T > action)"

.PP
Definition at line 128 of file SteamVR_Events\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Remove (UnityAction< T0, T1 > action)"

.PP
Definition at line 135 of file SteamVR_Events\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Remove (UnityAction< T0, T1, T2 > action)"

.PP
Definition at line 142 of file SteamVR_Events\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Send ()"

.PP
Definition at line 122 of file SteamVR_Events\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Send (T arg0)"

.PP
Definition at line 129 of file SteamVR_Events\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Send (T0 arg0, T1 arg1)"

.PP
Definition at line 136 of file SteamVR_Events\&.cs\&.
.SS "void \fBValve\&.VR\&.SteamVR_Events\&.Event\fP< T0, T1, T2 >\&.Send (T0 arg0, T1 arg1, T2 arg2)"

.PP
Definition at line 143 of file SteamVR_Events\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
