.TH "Valve.VR.InteractionSystem.VelocityEstimator" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.VelocityEstimator
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBeginEstimatingVelocity\fP ()"
.br
.ti -1c
.RI "void \fBFinishEstimatingVelocity\fP ()"
.br
.ti -1c
.RI "Vector3 \fBGetVelocityEstimate\fP ()"
.br
.ti -1c
.RI "Vector3 \fBGetAngularVelocityEstimate\fP ()"
.br
.ti -1c
.RI "Vector3 \fBGetAccelerationEstimate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvelocityAverageFrames\fP = 5"
.br
.ti -1c
.RI "int \fBangularVelocityAverageFrames\fP = 11"
.br
.ti -1c
.RI "bool \fBestimateOnAwake\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file VelocityEstimator\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.VelocityEstimator\&.BeginEstimatingVelocity ()"

.PP
Definition at line 29 of file VelocityEstimator\&.cs\&.
.SS "void Valve\&.VR\&.InteractionSystem\&.VelocityEstimator\&.FinishEstimatingVelocity ()"

.PP
Definition at line 38 of file VelocityEstimator\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.VelocityEstimator\&.GetAccelerationEstimate ()"

.PP
Definition at line 87 of file VelocityEstimator\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.VelocityEstimator\&.GetAngularVelocityEstimate ()"

.PP
Definition at line 68 of file VelocityEstimator\&.cs\&.
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.VelocityEstimator\&.GetVelocityEstimate ()"

.PP
Definition at line 49 of file VelocityEstimator\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int Valve\&.VR\&.InteractionSystem\&.VelocityEstimator\&.angularVelocityAverageFrames = 11"

.PP
Definition at line 18 of file VelocityEstimator\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.VelocityEstimator\&.estimateOnAwake = false"

.PP
Definition at line 20 of file VelocityEstimator\&.cs\&.
.SS "int Valve\&.VR\&.InteractionSystem\&.VelocityEstimator\&.velocityAverageFrames = 5"

.PP
Definition at line 16 of file VelocityEstimator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
