.TH "Valve.VR.SteamVR_Action_Vibration_Source_Map" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Action_Vibration_Source_Map
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_Action_Source_Map< SteamVR_Action_Vibration_Source >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsUpdating\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 127 of file SteamVR_Action_Vibration\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_Action_Vibration_Source_Map\&.IsUpdating (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
Definition at line 129 of file SteamVR_Action_Vibration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
