.TH "Valve.VR.SteamVR_Windows_Editor_Helper" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Windows_Editor_Helper
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBBrowserApplication\fP { \fBBrowserApplication\&.Unknown\fP, \fBBrowserApplication\&.InternetExplorer\fP, \fBBrowserApplication\&.Firefox\fP, \fBBrowserApplication\&.Chrome\fP, \fBBrowserApplication\&.Opera\fP, \fBBrowserApplication\&.Safari\fP, \fBBrowserApplication\&.Edge\fP }"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBBrowserApplication\fP \fBGetDefaultBrowser\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file SteamVR_Windows_Editor_Helper\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.SteamVR_Windows_Editor_Helper\&.BrowserApplication\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUnknown \fP\fP
.TP
\fB\fIInternetExplorer \fP\fP
.TP
\fB\fIFirefox \fP\fP
.TP
\fB\fIChrome \fP\fP
.TP
\fB\fIOpera \fP\fP
.TP
\fB\fISafari \fP\fP
.TP
\fB\fIEdge \fP\fP
.PP
Definition at line 8 of file SteamVR_Windows_Editor_Helper\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBBrowserApplication\fP Valve\&.VR\&.SteamVR_Windows_Editor_Helper\&.GetDefaultBrowser ()\fC [static]\fP"

.PP
Definition at line 19 of file SteamVR_Windows_Editor_Helper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
