.TH "Valve.VR.SteamVR_Input_ManifestFile_ApplicationString" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_ManifestFile_ApplicationString
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 589 of file SteamVR_Input_ActionFile\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Valve\&.VR\&.SteamVR_Input_ManifestFile_ApplicationString\&.name"

.PP
Definition at line 591 of file SteamVR_Input_ActionFile\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
