.TH "Valve.VR.IVRInput" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.IVRInput
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_SetActionManifestPath\fP (string pchActionManifestPath)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetActionSetHandle\fP (string pchActionSetName, ref ulong pHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetActionHandle\fP (string pchActionName, ref ulong pHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetInputSourceHandle\fP (string pchInputSourcePath, ref ulong pHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_UpdateActionState\fP ([\fBIn\fP, \fBOut\fP] \fBVRActiveActionSet_t\fP[] pSets, uint unSizeOfVRSelectedActionSet_t, uint unSetCount)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetDigitalActionData\fP (ulong action, ref \fBInputDigitalActionData_t\fP pActionData, uint unActionDataSize, ulong ulRestrictToDevice)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetAnalogActionData\fP (ulong action, ref \fBInputAnalogActionData_t\fP pActionData, uint unActionDataSize, ulong ulRestrictToDevice)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetPoseActionData\fP (ulong action, \fBETrackingUniverseOrigin\fP eOrigin, float fPredictedSecondsFromNow, ref \fBInputPoseActionData_t\fP pActionData, uint unActionDataSize, ulong ulRestrictToDevice)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetSkeletalActionData\fP (ulong action, ref \fBInputSkeletalActionData_t\fP pActionData, uint unActionDataSize)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetBoneCount\fP (ulong action, ref uint pBoneCount)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetBoneHierarchy\fP (ulong action, [\fBIn\fP, \fBOut\fP] int[] pParentIndices, uint unIndexArayCount)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetBoneName\fP (ulong action, int nBoneIndex, System\&.Text\&.StringBuilder pchBoneName, uint unNameBufferSize)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetSkeletalReferenceTransforms\fP (ulong action, \fBEVRSkeletalTransformSpace\fP eTransformSpace, \fBEVRSkeletalReferencePose\fP eReferencePose, [\fBIn\fP, \fBOut\fP] \fBVRBoneTransform_t\fP[] pTransformArray, uint unTransformArrayCount)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetSkeletalTrackingLevel\fP (ulong action, ref \fBEVRSkeletalTrackingLevel\fP pSkeletalTrackingLevel)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetSkeletalBoneData\fP (ulong action, \fBEVRSkeletalTransformSpace\fP eTransformSpace, \fBEVRSkeletalMotionRange\fP eMotionRange, [\fBIn\fP, \fBOut\fP] \fBVRBoneTransform_t\fP[] pTransformArray, uint unTransformArrayCount)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetSkeletalSummaryData\fP (ulong action, ref \fBVRSkeletalSummaryData_t\fP pSkeletalSummaryData)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetSkeletalBoneDataCompressed\fP (ulong action, \fBEVRSkeletalMotionRange\fP eMotionRange, IntPtr pvCompressedData, uint unCompressedSize, ref uint punRequiredCompressedSize)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_DecompressSkeletalBoneData\fP (IntPtr pvCompressedBuffer, uint unCompressedBufferSize, \fBEVRSkeletalTransformSpace\fP eTransformSpace, [\fBIn\fP, \fBOut\fP] \fBVRBoneTransform_t\fP[] pTransformArray, uint unTransformArrayCount)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_TriggerHapticVibrationAction\fP (ulong action, float fStartSecondsFromNow, float fDurationSeconds, float fFrequency, float fAmplitude, ulong ulRestrictToDevice)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetActionOrigins\fP (ulong actionSetHandle, ulong digitalActionHandle, [\fBIn\fP, \fBOut\fP] ulong[] originsOut, uint originOutCount)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetOriginLocalizedName\fP (ulong origin, System\&.Text\&.StringBuilder pchNameArray, uint unNameArraySize, int unStringSectionsToInclude)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_GetOriginTrackedDeviceInfo\fP (ulong origin, ref \fBInputOriginInfo_t\fP pOriginInfo, uint unOriginInfoSize)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_ShowActionOrigins\fP (ulong actionSetHandle, ulong ulActionHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVRInputError\fP \fB_ShowBindingsForActionSet\fP ([\fBIn\fP, \fBOut\fP] \fBVRActiveActionSet_t\fP[] pSets, uint unSizeOfVRSelectedActionSet_t, uint unSetCount, ulong originToHighlight)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internal \fB_SetActionManifestPath\fP \fBSetActionManifestPath\fP"
.br
.ti -1c
.RI "internal \fB_GetActionSetHandle\fP \fBGetActionSetHandle\fP"
.br
.ti -1c
.RI "internal \fB_GetActionHandle\fP \fBGetActionHandle\fP"
.br
.ti -1c
.RI "internal \fB_GetInputSourceHandle\fP \fBGetInputSourceHandle\fP"
.br
.ti -1c
.RI "internal \fB_UpdateActionState\fP \fBUpdateActionState\fP"
.br
.ti -1c
.RI "internal \fB_GetDigitalActionData\fP \fBGetDigitalActionData\fP"
.br
.ti -1c
.RI "internal \fB_GetAnalogActionData\fP \fBGetAnalogActionData\fP"
.br
.ti -1c
.RI "internal \fB_GetPoseActionData\fP \fBGetPoseActionData\fP"
.br
.ti -1c
.RI "internal \fB_GetSkeletalActionData\fP \fBGetSkeletalActionData\fP"
.br
.ti -1c
.RI "internal \fB_GetBoneCount\fP \fBGetBoneCount\fP"
.br
.ti -1c
.RI "internal \fB_GetBoneHierarchy\fP \fBGetBoneHierarchy\fP"
.br
.ti -1c
.RI "internal \fB_GetBoneName\fP \fBGetBoneName\fP"
.br
.ti -1c
.RI "internal \fB_GetSkeletalReferenceTransforms\fP \fBGetSkeletalReferenceTransforms\fP"
.br
.ti -1c
.RI "internal \fB_GetSkeletalTrackingLevel\fP \fBGetSkeletalTrackingLevel\fP"
.br
.ti -1c
.RI "internal \fB_GetSkeletalBoneData\fP \fBGetSkeletalBoneData\fP"
.br
.ti -1c
.RI "internal \fB_GetSkeletalSummaryData\fP \fBGetSkeletalSummaryData\fP"
.br
.ti -1c
.RI "internal \fB_GetSkeletalBoneDataCompressed\fP \fBGetSkeletalBoneDataCompressed\fP"
.br
.ti -1c
.RI "internal \fB_DecompressSkeletalBoneData\fP \fBDecompressSkeletalBoneData\fP"
.br
.ti -1c
.RI "internal \fB_TriggerHapticVibrationAction\fP \fBTriggerHapticVibrationAction\fP"
.br
.ti -1c
.RI "internal \fB_GetActionOrigins\fP \fBGetActionOrigins\fP"
.br
.ti -1c
.RI "internal \fB_GetOriginLocalizedName\fP \fBGetOriginLocalizedName\fP"
.br
.ti -1c
.RI "internal \fB_GetOriginTrackedDeviceInfo\fP \fBGetOriginTrackedDeviceInfo\fP"
.br
.ti -1c
.RI "internal \fB_ShowActionOrigins\fP \fBShowActionOrigins\fP"
.br
.ti -1c
.RI "internal \fB_ShowBindingsForActionSet\fP \fBShowBindingsForActionSet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1541 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._DecompressSkeletalBoneData (IntPtr pvCompressedBuffer, uint unCompressedBufferSize, \fBEVRSkeletalTransformSpace\fP eTransformSpace, [In, Out] \fBVRBoneTransform_t\fP [] pTransformArray, uint unTransformArrayCount)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetActionHandle (string pchActionName, ref ulong pHandle)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetActionOrigins (ulong actionSetHandle, ulong digitalActionHandle, [In, Out] ulong [] originsOut, uint originOutCount)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetActionSetHandle (string pchActionSetName, ref ulong pHandle)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetAnalogActionData (ulong action, ref \fBInputAnalogActionData_t\fP pActionData, uint unActionDataSize, ulong ulRestrictToDevice)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetBoneCount (ulong action, ref uint pBoneCount)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetBoneHierarchy (ulong action, [In, Out] int [] pParentIndices, uint unIndexArayCount)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetBoneName (ulong action, int nBoneIndex, System\&.Text\&.StringBuilder pchBoneName, uint unNameBufferSize)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetDigitalActionData (ulong action, ref \fBInputDigitalActionData_t\fP pActionData, uint unActionDataSize, ulong ulRestrictToDevice)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetInputSourceHandle (string pchInputSourcePath, ref ulong pHandle)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetOriginLocalizedName (ulong origin, System\&.Text\&.StringBuilder pchNameArray, uint unNameArraySize, int unStringSectionsToInclude)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetOriginTrackedDeviceInfo (ulong origin, ref \fBInputOriginInfo_t\fP pOriginInfo, uint unOriginInfoSize)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetPoseActionData (ulong action, \fBETrackingUniverseOrigin\fP eOrigin, float fPredictedSecondsFromNow, ref \fBInputPoseActionData_t\fP pActionData, uint unActionDataSize, ulong ulRestrictToDevice)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetSkeletalActionData (ulong action, ref \fBInputSkeletalActionData_t\fP pActionData, uint unActionDataSize)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetSkeletalBoneData (ulong action, \fBEVRSkeletalTransformSpace\fP eTransformSpace, \fBEVRSkeletalMotionRange\fP eMotionRange, [In, Out] \fBVRBoneTransform_t\fP [] pTransformArray, uint unTransformArrayCount)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetSkeletalBoneDataCompressed (ulong action, \fBEVRSkeletalMotionRange\fP eMotionRange, IntPtr pvCompressedData, uint unCompressedSize, ref uint punRequiredCompressedSize)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetSkeletalReferenceTransforms (ulong action, \fBEVRSkeletalTransformSpace\fP eTransformSpace, \fBEVRSkeletalReferencePose\fP eReferencePose, [In, Out] \fBVRBoneTransform_t\fP [] pTransformArray, uint unTransformArrayCount)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetSkeletalSummaryData (ulong action, ref \fBVRSkeletalSummaryData_t\fP pSkeletalSummaryData)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._GetSkeletalTrackingLevel (ulong action, ref \fBEVRSkeletalTrackingLevel\fP pSkeletalTrackingLevel)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._SetActionManifestPath (string pchActionManifestPath)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._ShowActionOrigins (ulong actionSetHandle, ulong ulActionHandle)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._ShowBindingsForActionSet ([In, Out] \fBVRActiveActionSet_t\fP [] pSets, uint unSizeOfVRSelectedActionSet_t, uint unSetCount, ulong originToHighlight)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._TriggerHapticVibrationAction (ulong action, float fStartSecondsFromNow, float fDurationSeconds, float fFrequency, float fAmplitude, ulong ulRestrictToDevice)"

.SS "internal delegate \fBEVRInputError\fP Valve\&.VR\&.IVRInput\&._UpdateActionState ([In, Out] \fBVRActiveActionSet_t\fP [] pSets, uint unSizeOfVRSelectedActionSet_t, uint unSetCount)"

.SH "Member Data Documentation"
.PP 
.SS "internal \fB_DecompressSkeletalBoneData\fP Valve\&.VR\&.IVRInput\&.DecompressSkeletalBoneData"

.PP
Definition at line 1631 of file openvr_api\&.cs\&.
.SS "internal \fB_GetActionHandle\fP Valve\&.VR\&.IVRInput\&.GetActionHandle"

.PP
Definition at line 1556 of file openvr_api\&.cs\&.
.SS "internal \fB_GetActionOrigins\fP Valve\&.VR\&.IVRInput\&.GetActionOrigins"

.PP
Definition at line 1641 of file openvr_api\&.cs\&.
.SS "internal \fB_GetActionSetHandle\fP Valve\&.VR\&.IVRInput\&.GetActionSetHandle"

.PP
Definition at line 1551 of file openvr_api\&.cs\&.
.SS "internal \fB_GetAnalogActionData\fP Valve\&.VR\&.IVRInput\&.GetAnalogActionData"

.PP
Definition at line 1576 of file openvr_api\&.cs\&.
.SS "internal \fB_GetBoneCount\fP Valve\&.VR\&.IVRInput\&.GetBoneCount"

.PP
Definition at line 1591 of file openvr_api\&.cs\&.
.SS "internal \fB_GetBoneHierarchy\fP Valve\&.VR\&.IVRInput\&.GetBoneHierarchy"

.PP
Definition at line 1596 of file openvr_api\&.cs\&.
.SS "internal \fB_GetBoneName\fP Valve\&.VR\&.IVRInput\&.GetBoneName"

.PP
Definition at line 1601 of file openvr_api\&.cs\&.
.SS "internal \fB_GetDigitalActionData\fP Valve\&.VR\&.IVRInput\&.GetDigitalActionData"

.PP
Definition at line 1571 of file openvr_api\&.cs\&.
.SS "internal \fB_GetInputSourceHandle\fP Valve\&.VR\&.IVRInput\&.GetInputSourceHandle"

.PP
Definition at line 1561 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOriginLocalizedName\fP Valve\&.VR\&.IVRInput\&.GetOriginLocalizedName"

.PP
Definition at line 1646 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOriginTrackedDeviceInfo\fP Valve\&.VR\&.IVRInput\&.GetOriginTrackedDeviceInfo"

.PP
Definition at line 1651 of file openvr_api\&.cs\&.
.SS "internal \fB_GetPoseActionData\fP Valve\&.VR\&.IVRInput\&.GetPoseActionData"

.PP
Definition at line 1581 of file openvr_api\&.cs\&.
.SS "internal \fB_GetSkeletalActionData\fP Valve\&.VR\&.IVRInput\&.GetSkeletalActionData"

.PP
Definition at line 1586 of file openvr_api\&.cs\&.
.SS "internal \fB_GetSkeletalBoneData\fP Valve\&.VR\&.IVRInput\&.GetSkeletalBoneData"

.PP
Definition at line 1616 of file openvr_api\&.cs\&.
.SS "internal \fB_GetSkeletalBoneDataCompressed\fP Valve\&.VR\&.IVRInput\&.GetSkeletalBoneDataCompressed"

.PP
Definition at line 1626 of file openvr_api\&.cs\&.
.SS "internal \fB_GetSkeletalReferenceTransforms\fP Valve\&.VR\&.IVRInput\&.GetSkeletalReferenceTransforms"

.PP
Definition at line 1606 of file openvr_api\&.cs\&.
.SS "internal \fB_GetSkeletalSummaryData\fP Valve\&.VR\&.IVRInput\&.GetSkeletalSummaryData"

.PP
Definition at line 1621 of file openvr_api\&.cs\&.
.SS "internal \fB_GetSkeletalTrackingLevel\fP Valve\&.VR\&.IVRInput\&.GetSkeletalTrackingLevel"

.PP
Definition at line 1611 of file openvr_api\&.cs\&.
.SS "internal \fB_SetActionManifestPath\fP Valve\&.VR\&.IVRInput\&.SetActionManifestPath"

.PP
Definition at line 1546 of file openvr_api\&.cs\&.
.SS "internal \fB_ShowActionOrigins\fP Valve\&.VR\&.IVRInput\&.ShowActionOrigins"

.PP
Definition at line 1656 of file openvr_api\&.cs\&.
.SS "internal \fB_ShowBindingsForActionSet\fP Valve\&.VR\&.IVRInput\&.ShowBindingsForActionSet"

.PP
Definition at line 1661 of file openvr_api\&.cs\&.
.SS "internal \fB_TriggerHapticVibrationAction\fP Valve\&.VR\&.IVRInput\&.TriggerHapticVibrationAction"

.PP
Definition at line 1636 of file openvr_api\&.cs\&.
.SS "internal \fB_UpdateActionState\fP Valve\&.VR\&.IVRInput\&.UpdateActionState"

.PP
Definition at line 1566 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
