.TH "Valve.VR.D3D12TextureData_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.D3D12TextureData_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IntPtr \fBm_pResource\fP"
.br
.ti -1c
.RI "IntPtr \fBm_pCommandQueue\fP"
.br
.ti -1c
.RI "uint \fBm_nNodeMask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5037 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "uint Valve\&.VR\&.D3D12TextureData_t\&.m_nNodeMask"

.PP
Definition at line 5041 of file openvr_api\&.cs\&.
.SS "IntPtr Valve\&.VR\&.D3D12TextureData_t\&.m_pCommandQueue"

.PP
Definition at line 5040 of file openvr_api\&.cs\&.
.SS "IntPtr Valve\&.VR\&.D3D12TextureData_t\&.m_pResource"

.PP
Definition at line 5039 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
