.TH "Valve.VR.SteamVR_Input_ActionFile_LocalizationItem" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_ActionFile_LocalizationItem
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSteamVR_Input_ActionFile_LocalizationItem\fP (string newLanguage)"
.br
.ti -1c
.RI "\fBSteamVR_Input_ActionFile_LocalizationItem\fP (Dictionary< string, string > dictionary)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBlanguageTagKeyName\fP = 'language_tag'"
.br
.ti -1c
.RI "string \fBlanguage\fP"
.br
.ti -1c
.RI "Dictionary< string, string > \fBitems\fP = new Dictionary<string, string>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 525 of file SteamVR_Input_ActionFile\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.SteamVR_Input_ActionFile_LocalizationItem\&.SteamVR_Input_ActionFile_LocalizationItem (string newLanguage)"

.PP
Definition at line 532 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "Valve\&.VR\&.SteamVR_Input_ActionFile_LocalizationItem\&.SteamVR_Input_ActionFile_LocalizationItem (Dictionary< string, string > dictionary)"

.PP
Definition at line 537 of file SteamVR_Input_ActionFile\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, string> Valve\&.VR\&.SteamVR_Input_ActionFile_LocalizationItem\&.items = new Dictionary<string, string>()"

.PP
Definition at line 530 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input_ActionFile_LocalizationItem\&.language"

.PP
Definition at line 529 of file SteamVR_Input_ActionFile\&.cs\&.
.SS "const string Valve\&.VR\&.SteamVR_Input_ActionFile_LocalizationItem\&.languageTagKeyName = 'language_tag'"

.PP
Definition at line 527 of file SteamVR_Input_ActionFile\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
