.TH "Valve.VR.RenderModel_TextureMap_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.RenderModel_TextureMap_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ushort \fBunWidth\fP"
.br
.ti -1c
.RI "ushort \fBunHeight\fP"
.br
.ti -1c
.RI "IntPtr \fBrubTextureMapData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5448 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "IntPtr Valve\&.VR\&.RenderModel_TextureMap_t\&.rubTextureMapData"

.PP
Definition at line 5452 of file openvr_api\&.cs\&.
.SS "ushort Valve\&.VR\&.RenderModel_TextureMap_t\&.unHeight"

.PP
Definition at line 5451 of file openvr_api\&.cs\&.
.SS "ushort Valve\&.VR\&.RenderModel_TextureMap_t\&.unWidth"

.PP
Definition at line 5450 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
