.TH "Valve.VR.DistortionCoordinates_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.DistortionCoordinates_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBrfRed0\fP"
.br
.ti -1c
.RI "float \fBrfRed1\fP"
.br
.ti -1c
.RI "float \fBrfGreen0\fP"
.br
.ti -1c
.RI "float \fBrfGreen1\fP"
.br
.ti -1c
.RI "float \fBrfBlue0\fP"
.br
.ti -1c
.RI "float \fBrfBlue1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4973 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.DistortionCoordinates_t\&.rfBlue0"

.PP
Definition at line 4979 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.DistortionCoordinates_t\&.rfBlue1"

.PP
Definition at line 4980 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.DistortionCoordinates_t\&.rfGreen0"

.PP
Definition at line 4977 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.DistortionCoordinates_t\&.rfGreen1"

.PP
Definition at line 4978 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.DistortionCoordinates_t\&.rfRed0"

.PP
Definition at line 4975 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.DistortionCoordinates_t\&.rfRed1"

.PP
Definition at line 4976 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
