.TH "Valve.VR.VREvent_t_Packed" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VREvent_t_Packed
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVREvent_t_Packed\fP (\fBVREvent_t\fP unpacked)"
.br
.ti -1c
.RI "void \fBUnpack\fP (ref \fBVREvent_t\fP unpacked)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint \fBeventType\fP"
.br
.ti -1c
.RI "uint \fBtrackedDeviceIndex\fP"
.br
.ti -1c
.RI "float \fBeventAgeSeconds\fP"
.br
.ti -1c
.RI "\fBVREvent_Data_t\fP \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5227 of file openvr_api\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.VREvent_t_Packed\&.VREvent_t_Packed (\fBVREvent_t\fP unpacked)"

.PP
Definition at line 5233 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.VREvent_t_Packed\&.Unpack (ref \fBVREvent_t\fP unpacked)"

.PP
Definition at line 5240 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBVREvent_Data_t\fP Valve\&.VR\&.VREvent_t_Packed\&.data"

.PP
Definition at line 5232 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.VREvent_t_Packed\&.eventAgeSeconds"

.PP
Definition at line 5231 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.VREvent_t_Packed\&.eventType"

.PP
Definition at line 5229 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.VREvent_t_Packed\&.trackedDeviceIndex"

.PP
Definition at line 5230 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
