.TH "Valve.VR.VREvent_Scroll_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VREvent_Scroll_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBxdelta\fP"
.br
.ti -1c
.RI "float \fBydelta\fP"
.br
.ti -1c
.RI "uint \fBrepeatCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5053 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "uint Valve\&.VR\&.VREvent_Scroll_t\&.repeatCount"

.PP
Definition at line 5057 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.VREvent_Scroll_t\&.xdelta"

.PP
Definition at line 5055 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.VREvent_Scroll_t\&.ydelta"

.PP
Definition at line 5056 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
