.TH "Valve.VR.SteamVR_HistoryStep" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_HistoryStep
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBposition\fP"
.br
.ti -1c
.RI "Quaternion \fBrotation\fP"
.br
.ti -1c
.RI "Vector3 \fBvelocity\fP"
.br
.ti -1c
.RI "Vector3 \fBangularVelocity\fP"
.br
.ti -1c
.RI "long \fBtimeInTicks\fP = \-1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 213 of file SteamVR_RingBuffer\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 Valve\&.VR\&.SteamVR_HistoryStep\&.angularVelocity"

.PP
Definition at line 220 of file SteamVR_RingBuffer\&.cs\&.
.SS "Vector3 Valve\&.VR\&.SteamVR_HistoryStep\&.position"

.PP
Definition at line 215 of file SteamVR_RingBuffer\&.cs\&.
.SS "Quaternion Valve\&.VR\&.SteamVR_HistoryStep\&.rotation"

.PP
Definition at line 216 of file SteamVR_RingBuffer\&.cs\&.
.SS "long Valve\&.VR\&.SteamVR_HistoryStep\&.timeInTicks = \-1"

.PP
Definition at line 222 of file SteamVR_RingBuffer\&.cs\&.
.SS "Vector3 Valve\&.VR\&.SteamVR_HistoryStep\&.velocity"

.PP
Definition at line 218 of file SteamVR_RingBuffer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
