.TH "Valve.VR.SteamVR_Skeleton_Poser" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Skeleton_Poser
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPoseBlendingBehaviour\fP"
.br
.RI "A filter applied to the base pose\&. Blends to a secondary pose by a certain weight\&. Can be masked per-finger "
.ti -1c
.RI "class \fBSkeletonBlendablePose\fP"
.br
.RI "A \fBSkeletonBlendablePose\fP holds a reference to a Skeleton_Pose scriptableObject, and also contains some helper functions\&. Also handles pose-specific animation like additive finger motion\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetBlendingBehaviourValue\fP (string behaviourName, float value)"
.br
.RI "Set the blending value of a blendingBehaviour\&. Works best on Manual type behaviours\&. "
.ti -1c
.RI "float \fBGetBlendingBehaviourValue\fP (string behaviourName)"
.br
.RI "Get the blending value of a blendingBehaviour\&. "
.ti -1c
.RI "void \fBSetBlendingBehaviourEnabled\fP (string behaviourName, bool value)"
.br
.RI "Enable or disable a blending behaviour\&. "
.ti -1c
.RI "bool \fBGetBlendingBehaviourEnabled\fP (string behaviourName)"
.br
.RI "Check if a blending behaviour is enabled\&. "
.ti -1c
.RI "\fBPoseBlendingBehaviour\fP \fBGetBlendingBehaviour\fP (string behaviourName)"
.br
.RI "Get a blending behaviour by name\&. "
.ti -1c
.RI "\fBSteamVR_Skeleton_Pose\fP \fBGetPoseByIndex\fP (int \fBindex\fP)"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_PoseSnapshot\fP \fBGetBlendedPose\fP (\fBSteamVR_Action_Skeleton\fP skeletonAction, \fBSteamVR_Input_Sources\fP handType)"
.br
.RI "Retrieve the final animated pose, to be applied to a hand skeleton "
.ti -1c
.RI "\fBSteamVR_Skeleton_PoseSnapshot\fP \fBGetBlendedPose\fP (\fBSteamVR_Behaviour_Skeleton\fP skeletonBehaviour)"
.br
.RI "Retrieve the final animated pose, to be applied to a hand skeleton "
.ti -1c
.RI "void \fBUpdatePose\fP (\fBSteamVR_Action_Skeleton\fP skeletonAction, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Updates all pose animation and blending\&. Can be called from different places without performance concerns, as it will only let itself run once per frame\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBposeEditorExpanded\fP = true"
.br
.ti -1c
.RI "bool \fBblendEditorExpanded\fP = true"
.br
.ti -1c
.RI "string [] \fBposeNames\fP"
.br
.ti -1c
.RI "GameObject \fBpreviewLeftHandPrefab\fP"
.br
.ti -1c
.RI "GameObject \fBpreviewRightHandPrefab\fP"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_Pose\fP \fBskeletonMainPose\fP"
.br
.ti -1c
.RI "List< \fBSteamVR_Skeleton_Pose\fP > \fBskeletonAdditionalPoses\fP = new List<\fBSteamVR_Skeleton_Pose\fP>()"
.br
.ti -1c
.RI "List< \fBPoseBlendingBehaviour\fP > \fBblendingBehaviours\fP = new List<\fBPoseBlendingBehaviour\fP>()"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_PoseSnapshot\fP \fBblendedSnapshotL\fP"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_PoseSnapshot\fP \fBblendedSnapshotR\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBApplyBlenderBehaviours\fP (\fBSteamVR_Action_Skeleton\fP skeletonAction, \fBSteamVR_Input_Sources\fP inputSource, \fBSteamVR_Skeleton_PoseSnapshot\fP snapshot)"
.br
.ti -1c
.RI "void \fBLateUpdate\fP ()"
.br
.ti -1c
.RI "Vector3 \fBBlendVectors\fP (Vector3[] vectors, float[] weights)"
.br
.RI "Weighted average of n vector3s "
.ti -1c
.RI "Quaternion \fBBlendQuaternions\fP (Quaternion[] quaternions, float[] weights)"
.br
.RI "Weighted average of n quaternions "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBshowLeftPreview\fP = false"
.br
.ti -1c
.RI "bool \fBshowRightPreview\fP = true"
.br
.ti -1c
.RI "GameObject \fBpreviewLeftInstance\fP"
.br
.ti -1c
.RI "GameObject \fBpreviewRightInstance\fP"
.br
.ti -1c
.RI "int \fBpreviewPoseSelection\fP = 0"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBblendPoseCount\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Skeleton_Poser\&.ApplyBlenderBehaviours (\fBSteamVR_Action_Skeleton\fP skeletonAction, \fBSteamVR_Input_Sources\fP inputSource, \fBSteamVR_Skeleton_PoseSnapshot\fP snapshot)\fC [protected]\fP"

.PP
Definition at line 217 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Skeleton_Poser\&.Awake ()\fC [protected]\fP"

.PP
Definition at line 57 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "Quaternion Valve\&.VR\&.SteamVR_Skeleton_Poser\&.BlendQuaternions (Quaternion [] quaternions, float [] weights)\fC [protected]\fP"

.PP
Weighted average of n quaternions 
.PP
Definition at line 257 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "Vector3 Valve\&.VR\&.SteamVR_Skeleton_Poser\&.BlendVectors (Vector3 [] vectors, float [] weights)\fC [protected]\fP"

.PP
Weighted average of n vector3s 
.PP
Definition at line 246 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "\fBSteamVR_Skeleton_PoseSnapshot\fP Valve\&.VR\&.SteamVR_Skeleton_Poser\&.GetBlendedPose (\fBSteamVR_Action_Skeleton\fP skeletonAction, \fBSteamVR_Input_Sources\fP handType)"

.PP
Retrieve the final animated pose, to be applied to a hand skeleton 
.PP
\fBParameters:\fP
.RS 4
\fIforAction\fP The skeleton action you want to blend between
.br
\fIhandType\fP If this is for the left or right hand
.RE
.PP

.PP
Definition at line 175 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "\fBSteamVR_Skeleton_PoseSnapshot\fP Valve\&.VR\&.SteamVR_Skeleton_Poser\&.GetBlendedPose (\fBSteamVR_Behaviour_Skeleton\fP skeletonBehaviour)"

.PP
Retrieve the final animated pose, to be applied to a hand skeleton 
.PP
\fBParameters:\fP
.RS 4
\fIskeletonBehaviour\fP The skeleton behaviour you want to get the action/input source from to blend between
.RE
.PP

.PP
Definition at line 185 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "\fBPoseBlendingBehaviour\fP Valve\&.VR\&.SteamVR_Skeleton_Poser\&.GetBlendingBehaviour (string behaviourName)"

.PP
Get a blending behaviour by name\&. 
.PP
Definition at line 142 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_Poser\&.GetBlendingBehaviourEnabled (string behaviourName)"

.PP
Check if a blending behaviour is enabled\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbehaviourName\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 129 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Skeleton_Poser\&.GetBlendingBehaviourValue (string behaviourName)"

.PP
Get the blending value of a blendingBehaviour\&. 
.PP
Definition at line 100 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "\fBSteamVR_Skeleton_Pose\fP Valve\&.VR\&.SteamVR_Skeleton_Poser\&.GetPoseByIndex (int index)"

.PP
Definition at line 156 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Skeleton_Poser\&.LateUpdate ()\fC [protected]\fP"

.PP
Definition at line 239 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Skeleton_Poser\&.SetBlendingBehaviourEnabled (string behaviourName, bool value)"

.PP
Enable or disable a blending behaviour\&. 
.PP
Definition at line 114 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Skeleton_Poser\&.SetBlendingBehaviourValue (string behaviourName, float value)"

.PP
Set the blending value of a blendingBehaviour\&. Works best on Manual type behaviours\&. 
.PP
Definition at line 83 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Skeleton_Poser\&.UpdatePose (\fBSteamVR_Action_Skeleton\fP skeletonAction, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Updates all pose animation and blending\&. Can be called from different places without performance concerns, as it will only let itself run once per frame\&. 
.PP
Definition at line 194 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_Poser\&.blendEditorExpanded = true"

.PP
Definition at line 16 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "\fBSteamVR_Skeleton_PoseSnapshot\fP Valve\&.VR\&.SteamVR_Skeleton_Poser\&.blendedSnapshotL"

.PP
Definition at line 45 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "\fBSteamVR_Skeleton_PoseSnapshot\fP Valve\&.VR\&.SteamVR_Skeleton_Poser\&.blendedSnapshotR"

.PP
Definition at line 46 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "List<\fBPoseBlendingBehaviour\fP> Valve\&.VR\&.SteamVR_Skeleton_Poser\&.blendingBehaviours = new List<\fBPoseBlendingBehaviour\fP>()"

.PP
Definition at line 43 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_Poser\&.poseEditorExpanded = true"

.PP
Definition at line 15 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "string [] Valve\&.VR\&.SteamVR_Skeleton_Poser\&.poseNames"

.PP
Definition at line 17 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "GameObject Valve\&.VR\&.SteamVR_Skeleton_Poser\&.previewLeftHandPrefab"

.PP
Definition at line 20 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "GameObject Valve\&.VR\&.SteamVR_Skeleton_Poser\&.previewLeftInstance\fC [protected]\fP"

.PP
Definition at line 33 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "int Valve\&.VR\&.SteamVR_Skeleton_Poser\&.previewPoseSelection = 0\fC [protected]\fP"

.PP
Definition at line 39 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "GameObject Valve\&.VR\&.SteamVR_Skeleton_Poser\&.previewRightHandPrefab"

.PP
Definition at line 21 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "GameObject Valve\&.VR\&.SteamVR_Skeleton_Poser\&.previewRightInstance\fC [protected]\fP"

.PP
Definition at line 36 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Skeleton_Poser\&.scale"

.PP
Definition at line 54 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_Poser\&.showLeftPreview = false\fC [protected]\fP"

.PP
Definition at line 27 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_Poser\&.showRightPreview = true\fC [protected]\fP"

.PP
Definition at line 30 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "List<\fBSteamVR_Skeleton_Pose\fP> Valve\&.VR\&.SteamVR_Skeleton_Poser\&.skeletonAdditionalPoses = new List<\fBSteamVR_Skeleton_Pose\fP>()"

.PP
Definition at line 24 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "\fBSteamVR_Skeleton_Pose\fP Valve\&.VR\&.SteamVR_Skeleton_Poser\&.skeletonMainPose"

.PP
Definition at line 23 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Valve\&.VR\&.SteamVR_Skeleton_Poser\&.blendPoseCount\fC [get]\fP"

.PP
Definition at line 41 of file SteamVR_Skeleton_Poser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
