.TH "Valve.VR.CVRSpatialAnchors" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.CVRSpatialAnchors
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEVRSpatialAnchorError\fP \fBCreateSpatialAnchorFromDescriptor\fP (string pchDescriptor, ref uint pHandleOut)"
.br
.ti -1c
.RI "\fBEVRSpatialAnchorError\fP \fBCreateSpatialAnchorFromPose\fP (uint unDeviceIndex, \fBETrackingUniverseOrigin\fP eOrigin, ref \fBSpatialAnchorPose_t\fP pPose, ref uint pHandleOut)"
.br
.ti -1c
.RI "\fBEVRSpatialAnchorError\fP \fBGetSpatialAnchorPose\fP (uint unHandle, \fBETrackingUniverseOrigin\fP eOrigin, ref \fBSpatialAnchorPose_t\fP pPoseOut)"
.br
.ti -1c
.RI "\fBEVRSpatialAnchorError\fP \fBGetSpatialAnchorDescriptor\fP (uint unHandle, System\&.Text\&.StringBuilder pchDescriptorOut, ref uint punDescriptorBufferLenInOut)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3637 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEVRSpatialAnchorError\fP Valve\&.VR\&.CVRSpatialAnchors\&.CreateSpatialAnchorFromDescriptor (string pchDescriptor, ref uint pHandleOut)"

.PP
Definition at line 3644 of file openvr_api\&.cs\&.
.SS "\fBEVRSpatialAnchorError\fP Valve\&.VR\&.CVRSpatialAnchors\&.CreateSpatialAnchorFromPose (uint unDeviceIndex, \fBETrackingUniverseOrigin\fP eOrigin, ref \fBSpatialAnchorPose_t\fP pPose, ref uint pHandleOut)"

.PP
Definition at line 3650 of file openvr_api\&.cs\&.
.SS "\fBEVRSpatialAnchorError\fP Valve\&.VR\&.CVRSpatialAnchors\&.GetSpatialAnchorDescriptor (uint unHandle, System\&.Text\&.StringBuilder pchDescriptorOut, ref uint punDescriptorBufferLenInOut)"

.PP
Definition at line 3661 of file openvr_api\&.cs\&.
.SS "\fBEVRSpatialAnchorError\fP Valve\&.VR\&.CVRSpatialAnchors\&.GetSpatialAnchorPose (uint unHandle, \fBETrackingUniverseOrigin\fP eOrigin, ref \fBSpatialAnchorPose_t\fP pPoseOut)"

.PP
Definition at line 3656 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
