.TH "Valve.VR.InteractionSystem.Sample.TargetMeasurement" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Sample.TargetMeasurement
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBvisualWrapper\fP"
.br
.ti -1c
.RI "Transform \fBmeasurementTape\fP"
.br
.ti -1c
.RI "Transform \fBendPoint\fP"
.br
.ti -1c
.RI "Text \fBmeasurementTextM\fP"
.br
.ti -1c
.RI "Text \fBmeasurementTextFT\fP"
.br
.ti -1c
.RI "float \fBmaxDistanceToDraw\fP = 6f"
.br
.ti -1c
.RI "bool \fBdrawTape\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file TargetMeasurement\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.Sample\&.TargetMeasurement\&.drawTape = false"

.PP
Definition at line 20 of file TargetMeasurement\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Sample\&.TargetMeasurement\&.endPoint"

.PP
Definition at line 14 of file TargetMeasurement\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Sample\&.TargetMeasurement\&.maxDistanceToDraw = 6f"

.PP
Definition at line 18 of file TargetMeasurement\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Sample\&.TargetMeasurement\&.measurementTape"

.PP
Definition at line 12 of file TargetMeasurement\&.cs\&.
.SS "Text Valve\&.VR\&.InteractionSystem\&.Sample\&.TargetMeasurement\&.measurementTextFT"

.PP
Definition at line 16 of file TargetMeasurement\&.cs\&.
.SS "Text Valve\&.VR\&.InteractionSystem\&.Sample\&.TargetMeasurement\&.measurementTextM"

.PP
Definition at line 15 of file TargetMeasurement\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.Sample\&.TargetMeasurement\&.visualWrapper"

.PP
Definition at line 11 of file TargetMeasurement\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
