.TH "Valve.VR.SteamVR_Input_BindingFile" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_BindingFile
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBapp_key\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBSteamVR_Input_BindingFile_ActionList\fP > \fBbindings\fP = new Dictionary<string, \fBSteamVR_Input_BindingFile_ActionList\fP>()"
.br
.ti -1c
.RI "string \fBcontroller_type\fP"
.br
.ti -1c
.RI "string \fBdescription\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file SteamVR_Input_BindingFile\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Valve\&.VR\&.SteamVR_Input_BindingFile\&.app_key"

.PP
Definition at line 16 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "Dictionary<string, \fBSteamVR_Input_BindingFile_ActionList\fP> Valve\&.VR\&.SteamVR_Input_BindingFile\&.bindings = new Dictionary<string, \fBSteamVR_Input_BindingFile_ActionList\fP>()"

.PP
Definition at line 17 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input_BindingFile\&.controller_type"

.PP
Definition at line 18 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input_BindingFile\&.description"

.PP
Definition at line 19 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input_BindingFile\&.name"

.PP
Definition at line 20 of file SteamVR_Input_BindingFile\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
