.TH "Valve.VR.InteractionSystem.LinearDisplacement" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.LinearDisplacement
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBdisplacement\fP"
.br
.ti -1c
.RI "\fBLinearMapping\fP \fBlinearMapping\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file LinearDisplacement\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.LinearDisplacement\&.displacement"

.PP
Definition at line 15 of file LinearDisplacement\&.cs\&.
.SS "\fBLinearMapping\fP Valve\&.VR\&.InteractionSystem\&.LinearDisplacement\&.linearMapping"

.PP
Definition at line 16 of file LinearDisplacement\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
