.TH "Valve.VR.VREvent_SeatedZeroPoseReset_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VREvent_SeatedZeroPoseReset_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBbResetBySystemMenu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5135 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.VREvent_SeatedZeroPoseReset_t\&.bResetBySystemMenu"

.PP
Definition at line 5138 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
