.TH "Valve.VR.InteractionSystem.Sample.TargetHitEffect" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Sample.TargetHitEffect
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Collider \fBtargetCollider\fP"
.br
.ti -1c
.RI "GameObject \fBspawnObjectOnCollision\fP"
.br
.ti -1c
.RI "bool \fBcolorSpawnedObject\fP = true"
.br
.ti -1c
.RI "bool \fBdestroyOnTargetCollision\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file TargetHitEffect\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.Sample\&.TargetHitEffect\&.colorSpawnedObject = true"

.PP
Definition at line 14 of file TargetHitEffect\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Sample\&.TargetHitEffect\&.destroyOnTargetCollision = true"

.PP
Definition at line 16 of file TargetHitEffect\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.Sample\&.TargetHitEffect\&.spawnObjectOnCollision"

.PP
Definition at line 12 of file TargetHitEffect\&.cs\&.
.SS "Collider Valve\&.VR\&.InteractionSystem\&.Sample\&.TargetHitEffect\&.targetCollider"

.PP
Definition at line 10 of file TargetHitEffect\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
