.TH "Valve.VR.InteractionSystem.ArcheryTarget" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.ArcheryTarget
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBonTakeDamage\fP"
.br
.ti -1c
.RI "bool \fBonceOnly\fP = false"
.br
.ti -1c
.RI "Transform \fBtargetCenter\fP"
.br
.ti -1c
.RI "Transform \fBbaseTransform\fP"
.br
.ti -1c
.RI "Transform \fBfallenDownTransform\fP"
.br
.ti -1c
.RI "float \fBfallTime\fP = 0\&.5f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file ArcheryTarget\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform Valve\&.VR\&.InteractionSystem\&.ArcheryTarget\&.baseTransform"

.PP
Definition at line 21 of file ArcheryTarget\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.ArcheryTarget\&.fallenDownTransform"

.PP
Definition at line 22 of file ArcheryTarget\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.ArcheryTarget\&.fallTime = 0\&.5f"

.PP
Definition at line 23 of file ArcheryTarget\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.ArcheryTarget\&.onceOnly = false"

.PP
Definition at line 18 of file ArcheryTarget\&.cs\&.
.SS "UnityEvent Valve\&.VR\&.InteractionSystem\&.ArcheryTarget\&.onTakeDamage"

.PP
Definition at line 16 of file ArcheryTarget\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.ArcheryTarget\&.targetCenter"

.PP
Definition at line 19 of file ArcheryTarget\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
