.TH "Valve.VR.HmdQuaternion_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.HmdQuaternion_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBw\fP"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4940 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "double Valve\&.VR\&.HmdQuaternion_t\&.w"

.PP
Definition at line 4942 of file openvr_api\&.cs\&.
.SS "double Valve\&.VR\&.HmdQuaternion_t\&.x"

.PP
Definition at line 4943 of file openvr_api\&.cs\&.
.SS "double Valve\&.VR\&.HmdQuaternion_t\&.y"

.PP
Definition at line 4944 of file openvr_api\&.cs\&.
.SS "double Valve\&.VR\&.HmdQuaternion_t\&.z"

.PP
Definition at line 4945 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
