.TH "Valve.VR.IVRRenderModels" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.IVRRenderModels
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal delegate \fBEVRRenderModelError\fP \fB_LoadRenderModel_Async\fP (string pchRenderModelName, ref IntPtr ppRenderModel)"
.br
.ti -1c
.RI "internal delegate void \fB_FreeRenderModel\fP (IntPtr pRenderModel)"
.br
.ti -1c
.RI "internal delegate \fBEVRRenderModelError\fP \fB_LoadTexture_Async\fP (int textureId, ref IntPtr ppTexture)"
.br
.ti -1c
.RI "internal delegate void \fB_FreeTexture\fP (IntPtr pTexture)"
.br
.ti -1c
.RI "internal delegate \fBEVRRenderModelError\fP \fB_LoadTextureD3D11_Async\fP (int textureId, IntPtr pD3D11Device, ref IntPtr ppD3D11Texture2D)"
.br
.ti -1c
.RI "internal delegate \fBEVRRenderModelError\fP \fB_LoadIntoTextureD3D11_Async\fP (int textureId, IntPtr pDstTexture)"
.br
.ti -1c
.RI "internal delegate void \fB_FreeTextureD3D11\fP (IntPtr pD3D11Texture2D)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetRenderModelName\fP (uint unRenderModelIndex, System\&.Text\&.StringBuilder pchRenderModelName, uint unRenderModelNameLen)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetRenderModelCount\fP ()"
.br
.ti -1c
.RI "internal delegate uint \fB_GetComponentCount\fP (string pchRenderModelName)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetComponentName\fP (string pchRenderModelName, uint unComponentIndex, System\&.Text\&.StringBuilder pchComponentName, uint unComponentNameLen)"
.br
.ti -1c
.RI "internal delegate ulong \fB_GetComponentButtonMask\fP (string pchRenderModelName, string pchComponentName)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetComponentRenderModelName\fP (string pchRenderModelName, string pchComponentName, System\&.Text\&.StringBuilder pchComponentRenderModelName, uint unComponentRenderModelNameLen)"
.br
.ti -1c
.RI "internal delegate bool \fB_GetComponentStateForDevicePath\fP (string pchRenderModelName, string pchComponentName, ulong devicePath, ref \fBRenderModel_ControllerMode_State_t\fP pState, ref \fBRenderModel_ComponentState_t\fP pComponentState)"
.br
.ti -1c
.RI "internal delegate bool \fB_GetComponentState\fP (string pchRenderModelName, string pchComponentName, ref \fBVRControllerState_t\fP pControllerState, ref \fBRenderModel_ControllerMode_State_t\fP pState, ref \fBRenderModel_ComponentState_t\fP pComponentState)"
.br
.ti -1c
.RI "internal delegate bool \fB_RenderModelHasComponent\fP (string pchRenderModelName, string pchComponentName)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetRenderModelThumbnailURL\fP (string pchRenderModelName, System\&.Text\&.StringBuilder pchThumbnailURL, uint unThumbnailURLLen, ref \fBEVRRenderModelError\fP peError)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetRenderModelOriginalPath\fP (string pchRenderModelName, System\&.Text\&.StringBuilder pchOriginalPath, uint unOriginalPathLen, ref \fBEVRRenderModelError\fP peError)"
.br
.ti -1c
.RI "internal delegate IntPtr \fB_GetRenderModelErrorNameFromEnum\fP (\fBEVRRenderModelError\fP error)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internal \fB_LoadRenderModel_Async\fP \fBLoadRenderModel_Async\fP"
.br
.ti -1c
.RI "internal \fB_FreeRenderModel\fP \fBFreeRenderModel\fP"
.br
.ti -1c
.RI "internal \fB_LoadTexture_Async\fP \fBLoadTexture_Async\fP"
.br
.ti -1c
.RI "internal \fB_FreeTexture\fP \fBFreeTexture\fP"
.br
.ti -1c
.RI "internal \fB_LoadTextureD3D11_Async\fP \fBLoadTextureD3D11_Async\fP"
.br
.ti -1c
.RI "internal \fB_LoadIntoTextureD3D11_Async\fP \fBLoadIntoTextureD3D11_Async\fP"
.br
.ti -1c
.RI "internal \fB_FreeTextureD3D11\fP \fBFreeTextureD3D11\fP"
.br
.ti -1c
.RI "internal \fB_GetRenderModelName\fP \fBGetRenderModelName\fP"
.br
.ti -1c
.RI "internal \fB_GetRenderModelCount\fP \fBGetRenderModelCount\fP"
.br
.ti -1c
.RI "internal \fB_GetComponentCount\fP \fBGetComponentCount\fP"
.br
.ti -1c
.RI "internal \fB_GetComponentName\fP \fBGetComponentName\fP"
.br
.ti -1c
.RI "internal \fB_GetComponentButtonMask\fP \fBGetComponentButtonMask\fP"
.br
.ti -1c
.RI "internal \fB_GetComponentRenderModelName\fP \fBGetComponentRenderModelName\fP"
.br
.ti -1c
.RI "internal \fB_GetComponentStateForDevicePath\fP \fBGetComponentStateForDevicePath\fP"
.br
.ti -1c
.RI "internal \fB_GetComponentState\fP \fBGetComponentState\fP"
.br
.ti -1c
.RI "internal \fB_RenderModelHasComponent\fP \fBRenderModelHasComponent\fP"
.br
.ti -1c
.RI "internal \fB_GetRenderModelThumbnailURL\fP \fBGetRenderModelThumbnailURL\fP"
.br
.ti -1c
.RI "internal \fB_GetRenderModelOriginalPath\fP \fBGetRenderModelOriginalPath\fP"
.br
.ti -1c
.RI "internal \fB_GetRenderModelErrorNameFromEnum\fP \fBGetRenderModelErrorNameFromEnum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1286 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "internal delegate void Valve\&.VR\&.IVRRenderModels\&._FreeRenderModel (IntPtr pRenderModel)"

.SS "internal delegate void Valve\&.VR\&.IVRRenderModels\&._FreeTexture (IntPtr pTexture)"

.SS "internal delegate void Valve\&.VR\&.IVRRenderModels\&._FreeTextureD3D11 (IntPtr pD3D11Texture2D)"

.SS "internal delegate ulong Valve\&.VR\&.IVRRenderModels\&._GetComponentButtonMask (string pchRenderModelName, string pchComponentName)"

.SS "internal delegate uint Valve\&.VR\&.IVRRenderModels\&._GetComponentCount (string pchRenderModelName)"

.SS "internal delegate uint Valve\&.VR\&.IVRRenderModels\&._GetComponentName (string pchRenderModelName, uint unComponentIndex, System\&.Text\&.StringBuilder pchComponentName, uint unComponentNameLen)"

.SS "internal delegate uint Valve\&.VR\&.IVRRenderModels\&._GetComponentRenderModelName (string pchRenderModelName, string pchComponentName, System\&.Text\&.StringBuilder pchComponentRenderModelName, uint unComponentRenderModelNameLen)"

.SS "internal delegate bool Valve\&.VR\&.IVRRenderModels\&._GetComponentState (string pchRenderModelName, string pchComponentName, ref \fBVRControllerState_t\fP pControllerState, ref \fBRenderModel_ControllerMode_State_t\fP pState, ref \fBRenderModel_ComponentState_t\fP pComponentState)"

.SS "internal delegate bool Valve\&.VR\&.IVRRenderModels\&._GetComponentStateForDevicePath (string pchRenderModelName, string pchComponentName, ulong devicePath, ref \fBRenderModel_ControllerMode_State_t\fP pState, ref \fBRenderModel_ComponentState_t\fP pComponentState)"

.SS "internal delegate uint Valve\&.VR\&.IVRRenderModels\&._GetRenderModelCount ()"

.SS "internal delegate IntPtr Valve\&.VR\&.IVRRenderModels\&._GetRenderModelErrorNameFromEnum (\fBEVRRenderModelError\fP error)"

.SS "internal delegate uint Valve\&.VR\&.IVRRenderModels\&._GetRenderModelName (uint unRenderModelIndex, System\&.Text\&.StringBuilder pchRenderModelName, uint unRenderModelNameLen)"

.SS "internal delegate uint Valve\&.VR\&.IVRRenderModels\&._GetRenderModelOriginalPath (string pchRenderModelName, System\&.Text\&.StringBuilder pchOriginalPath, uint unOriginalPathLen, ref \fBEVRRenderModelError\fP peError)"

.SS "internal delegate uint Valve\&.VR\&.IVRRenderModels\&._GetRenderModelThumbnailURL (string pchRenderModelName, System\&.Text\&.StringBuilder pchThumbnailURL, uint unThumbnailURLLen, ref \fBEVRRenderModelError\fP peError)"

.SS "internal delegate \fBEVRRenderModelError\fP Valve\&.VR\&.IVRRenderModels\&._LoadIntoTextureD3D11_Async (int textureId, IntPtr pDstTexture)"

.SS "internal delegate \fBEVRRenderModelError\fP Valve\&.VR\&.IVRRenderModels\&._LoadRenderModel_Async (string pchRenderModelName, ref IntPtr ppRenderModel)"

.SS "internal delegate \fBEVRRenderModelError\fP Valve\&.VR\&.IVRRenderModels\&._LoadTexture_Async (int textureId, ref IntPtr ppTexture)"

.SS "internal delegate \fBEVRRenderModelError\fP Valve\&.VR\&.IVRRenderModels\&._LoadTextureD3D11_Async (int textureId, IntPtr pD3D11Device, ref IntPtr ppD3D11Texture2D)"

.SS "internal delegate bool Valve\&.VR\&.IVRRenderModels\&._RenderModelHasComponent (string pchRenderModelName, string pchComponentName)"

.SH "Member Data Documentation"
.PP 
.SS "internal \fB_FreeRenderModel\fP Valve\&.VR\&.IVRRenderModels\&.FreeRenderModel"

.PP
Definition at line 1296 of file openvr_api\&.cs\&.
.SS "internal \fB_FreeTexture\fP Valve\&.VR\&.IVRRenderModels\&.FreeTexture"

.PP
Definition at line 1306 of file openvr_api\&.cs\&.
.SS "internal \fB_FreeTextureD3D11\fP Valve\&.VR\&.IVRRenderModels\&.FreeTextureD3D11"

.PP
Definition at line 1321 of file openvr_api\&.cs\&.
.SS "internal \fB_GetComponentButtonMask\fP Valve\&.VR\&.IVRRenderModels\&.GetComponentButtonMask"

.PP
Definition at line 1346 of file openvr_api\&.cs\&.
.SS "internal \fB_GetComponentCount\fP Valve\&.VR\&.IVRRenderModels\&.GetComponentCount"

.PP
Definition at line 1336 of file openvr_api\&.cs\&.
.SS "internal \fB_GetComponentName\fP Valve\&.VR\&.IVRRenderModels\&.GetComponentName"

.PP
Definition at line 1341 of file openvr_api\&.cs\&.
.SS "internal \fB_GetComponentRenderModelName\fP Valve\&.VR\&.IVRRenderModels\&.GetComponentRenderModelName"

.PP
Definition at line 1351 of file openvr_api\&.cs\&.
.SS "internal \fB_GetComponentState\fP Valve\&.VR\&.IVRRenderModels\&.GetComponentState"

.PP
Definition at line 1361 of file openvr_api\&.cs\&.
.SS "internal \fB_GetComponentStateForDevicePath\fP Valve\&.VR\&.IVRRenderModels\&.GetComponentStateForDevicePath"

.PP
Definition at line 1356 of file openvr_api\&.cs\&.
.SS "internal \fB_GetRenderModelCount\fP Valve\&.VR\&.IVRRenderModels\&.GetRenderModelCount"

.PP
Definition at line 1331 of file openvr_api\&.cs\&.
.SS "internal \fB_GetRenderModelErrorNameFromEnum\fP Valve\&.VR\&.IVRRenderModels\&.GetRenderModelErrorNameFromEnum"

.PP
Definition at line 1381 of file openvr_api\&.cs\&.
.SS "internal \fB_GetRenderModelName\fP Valve\&.VR\&.IVRRenderModels\&.GetRenderModelName"

.PP
Definition at line 1326 of file openvr_api\&.cs\&.
.SS "internal \fB_GetRenderModelOriginalPath\fP Valve\&.VR\&.IVRRenderModels\&.GetRenderModelOriginalPath"

.PP
Definition at line 1376 of file openvr_api\&.cs\&.
.SS "internal \fB_GetRenderModelThumbnailURL\fP Valve\&.VR\&.IVRRenderModels\&.GetRenderModelThumbnailURL"

.PP
Definition at line 1371 of file openvr_api\&.cs\&.
.SS "internal \fB_LoadIntoTextureD3D11_Async\fP Valve\&.VR\&.IVRRenderModels\&.LoadIntoTextureD3D11_Async"

.PP
Definition at line 1316 of file openvr_api\&.cs\&.
.SS "internal \fB_LoadRenderModel_Async\fP Valve\&.VR\&.IVRRenderModels\&.LoadRenderModel_Async"

.PP
Definition at line 1291 of file openvr_api\&.cs\&.
.SS "internal \fB_LoadTexture_Async\fP Valve\&.VR\&.IVRRenderModels\&.LoadTexture_Async"

.PP
Definition at line 1301 of file openvr_api\&.cs\&.
.SS "internal \fB_LoadTextureD3D11_Async\fP Valve\&.VR\&.IVRRenderModels\&.LoadTextureD3D11_Async"

.PP
Definition at line 1311 of file openvr_api\&.cs\&.
.SS "internal \fB_RenderModelHasComponent\fP Valve\&.VR\&.IVRRenderModels\&.RenderModelHasComponent"

.PP
Definition at line 1366 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
