.TH "Valve.VR.InteractionSystem.ChaperoneInfo" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.ChaperoneInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSteamVR_Events\&.Action\fP \fBInitializedAction\fP (UnityAction action)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBSteamVR_Events\&.Event\fP \fBInitialized\fP = new \fBSteamVR_Events\&.Event\fP()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBinitialized\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBplayAreaSizeX\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBplayAreaSizeZ\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBroomscale\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBChaperoneInfo\fP \fBinstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file ChaperoneInfo\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBSteamVR_Events\&.Action\fP Valve\&.VR\&.InteractionSystem\&.ChaperoneInfo\&.InitializedAction (UnityAction action)\fC [static]\fP"

.PP
Definition at line 22 of file ChaperoneInfo\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSteamVR_Events\&.Event\fP Valve\&.VR\&.InteractionSystem\&.ChaperoneInfo\&.Initialized = new \fBSteamVR_Events\&.Event\fP()\fC [static]\fP"

.PP
Definition at line 21 of file ChaperoneInfo\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.ChaperoneInfo\&.initialized\fC [get]\fP"

.PP
Definition at line 16 of file ChaperoneInfo\&.cs\&.
.SS "\fBChaperoneInfo\fP Valve\&.VR\&.InteractionSystem\&.ChaperoneInfo\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 27 of file ChaperoneInfo\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.ChaperoneInfo\&.playAreaSizeX\fC [get]\fP"

.PP
Definition at line 17 of file ChaperoneInfo\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.ChaperoneInfo\&.playAreaSizeZ\fC [get]\fP"

.PP
Definition at line 18 of file ChaperoneInfo\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.ChaperoneInfo\&.roomscale\fC [get]\fP"

.PP
Definition at line 19 of file ChaperoneInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
