.TH "Valve.VR.IVROverlay" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.IVROverlay
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_FindOverlay\fP (string pchOverlayKey, ref ulong pOverlayHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_CreateOverlay\fP (string pchOverlayKey, string pchOverlayName, ref ulong pOverlayHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_DestroyOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetHighQualityOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "internal delegate ulong \fB_GetHighQualityOverlay\fP ()"
.br
.ti -1c
.RI "internal delegate uint \fB_GetOverlayKey\fP (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBEVROverlayError\fP pError)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetOverlayName\fP (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBEVROverlayError\fP pError)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayName\fP (ulong ulOverlayHandle, string pchName)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayImageData\fP (ulong ulOverlayHandle, IntPtr pvBuffer, uint unBufferSize, ref uint punWidth, ref uint punHeight)"
.br
.ti -1c
.RI "internal delegate IntPtr \fB_GetOverlayErrorNameFromEnum\fP (\fBEVROverlayError\fP error)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayRenderingPid\fP (ulong ulOverlayHandle, uint unPID)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetOverlayRenderingPid\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayFlag\fP (ulong ulOverlayHandle, \fBVROverlayFlags\fP eOverlayFlag, bool bEnabled)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayFlag\fP (ulong ulOverlayHandle, \fBVROverlayFlags\fP eOverlayFlag, ref bool pbEnabled)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayColor\fP (ulong ulOverlayHandle, float fRed, float fGreen, float fBlue)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayColor\fP (ulong ulOverlayHandle, ref float pfRed, ref float pfGreen, ref float pfBlue)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayAlpha\fP (ulong ulOverlayHandle, float fAlpha)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayAlpha\fP (ulong ulOverlayHandle, ref float pfAlpha)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayTexelAspect\fP (ulong ulOverlayHandle, float fTexelAspect)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayTexelAspect\fP (ulong ulOverlayHandle, ref float pfTexelAspect)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlaySortOrder\fP (ulong ulOverlayHandle, uint unSortOrder)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlaySortOrder\fP (ulong ulOverlayHandle, ref uint punSortOrder)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayWidthInMeters\fP (ulong ulOverlayHandle, float fWidthInMeters)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayWidthInMeters\fP (ulong ulOverlayHandle, ref float pfWidthInMeters)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayAutoCurveDistanceRangeInMeters\fP (ulong ulOverlayHandle, float fMinDistanceInMeters, float fMaxDistanceInMeters)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayAutoCurveDistanceRangeInMeters\fP (ulong ulOverlayHandle, ref float pfMinDistanceInMeters, ref float pfMaxDistanceInMeters)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayTextureColorSpace\fP (ulong ulOverlayHandle, \fBEColorSpace\fP eTextureColorSpace)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayTextureColorSpace\fP (ulong ulOverlayHandle, ref \fBEColorSpace\fP peTextureColorSpace)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayTextureBounds\fP (ulong ulOverlayHandle, ref \fBVRTextureBounds_t\fP pOverlayTextureBounds)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayTextureBounds\fP (ulong ulOverlayHandle, ref \fBVRTextureBounds_t\fP pOverlayTextureBounds)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetOverlayRenderModel\fP (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBHmdColor_t\fP pColor, ref \fBEVROverlayError\fP pError)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayRenderModel\fP (ulong ulOverlayHandle, string pchRenderModel, ref \fBHmdColor_t\fP pColor)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayTransformType\fP (ulong ulOverlayHandle, ref \fBVROverlayTransformType\fP peTransformType)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayTransformAbsolute\fP (ulong ulOverlayHandle, \fBETrackingUniverseOrigin\fP eTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToOverlayTransform)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayTransformAbsolute\fP (ulong ulOverlayHandle, ref \fBETrackingUniverseOrigin\fP peTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToOverlayTransform)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayTransformTrackedDeviceRelative\fP (ulong ulOverlayHandle, uint unTrackedDevice, ref \fBHmdMatrix34_t\fP pmatTrackedDeviceToOverlayTransform)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayTransformTrackedDeviceRelative\fP (ulong ulOverlayHandle, ref uint punTrackedDevice, ref \fBHmdMatrix34_t\fP pmatTrackedDeviceToOverlayTransform)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayTransformTrackedDeviceComponent\fP (ulong ulOverlayHandle, uint unDeviceIndex, string pchComponentName)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayTransformTrackedDeviceComponent\fP (ulong ulOverlayHandle, ref uint punDeviceIndex, System\&.Text\&.StringBuilder pchComponentName, uint unComponentNameSize)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayTransformOverlayRelative\fP (ulong ulOverlayHandle, ref ulong ulOverlayHandleParent, ref \fBHmdMatrix34_t\fP pmatParentOverlayToOverlayTransform)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayTransformOverlayRelative\fP (ulong ulOverlayHandle, ulong ulOverlayHandleParent, ref \fBHmdMatrix34_t\fP pmatParentOverlayToOverlayTransform)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_ShowOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_HideOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "internal delegate bool \fB_IsOverlayVisible\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetTransformForOverlayCoordinates\fP (ulong ulOverlayHandle, \fBETrackingUniverseOrigin\fP eTrackingOrigin, \fBHmdVector2_t\fP coordinatesInOverlay, ref \fBHmdMatrix34_t\fP pmatTransform)"
.br
.ti -1c
.RI "internal delegate bool \fB_PollNextOverlayEvent\fP (ulong ulOverlayHandle, ref \fBVREvent_t\fP pEvent, uint uncbVREvent)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayInputMethod\fP (ulong ulOverlayHandle, ref \fBVROverlayInputMethod\fP peInputMethod)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayInputMethod\fP (ulong ulOverlayHandle, \fBVROverlayInputMethod\fP eInputMethod)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayMouseScale\fP (ulong ulOverlayHandle, ref \fBHmdVector2_t\fP pvecMouseScale)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayMouseScale\fP (ulong ulOverlayHandle, ref \fBHmdVector2_t\fP pvecMouseScale)"
.br
.ti -1c
.RI "internal delegate bool \fB_ComputeOverlayIntersection\fP (ulong ulOverlayHandle, ref \fBVROverlayIntersectionParams_t\fP pParams, ref \fBVROverlayIntersectionResults_t\fP pResults)"
.br
.ti -1c
.RI "internal delegate bool \fB_IsHoverTargetOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "internal delegate ulong \fB_GetGamepadFocusOverlay\fP ()"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetGamepadFocusOverlay\fP (ulong ulNewFocusOverlay)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayNeighbor\fP (\fBEOverlayDirection\fP eDirection, ulong ulFrom, ulong ulTo)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_MoveGamepadFocusToNeighbor\fP (\fBEOverlayDirection\fP eDirection, ulong ulFrom)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayDualAnalogTransform\fP (ulong ulOverlay, \fBEDualAnalogWhich\fP eWhich, ref \fBHmdVector2_t\fP pvCenter, float fRadius)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayDualAnalogTransform\fP (ulong ulOverlay, \fBEDualAnalogWhich\fP eWhich, ref \fBHmdVector2_t\fP pvCenter, ref float pfRadius)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayTexture\fP (ulong ulOverlayHandle, ref \fBTexture_t\fP pTexture)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_ClearOverlayTexture\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayRaw\fP (ulong ulOverlayHandle, IntPtr pvBuffer, uint unWidth, uint unHeight, uint unDepth)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayFromFile\fP (ulong ulOverlayHandle, string pchFilePath)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayTexture\fP (ulong ulOverlayHandle, ref IntPtr pNativeTextureHandle, IntPtr pNativeTextureRef, ref uint pWidth, ref uint pHeight, ref uint pNativeFormat, ref \fBETextureType\fP pAPIType, ref \fBEColorSpace\fP pColorSpace, ref \fBVRTextureBounds_t\fP pTextureBounds)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_ReleaseNativeOverlayHandle\fP (ulong ulOverlayHandle, IntPtr pNativeTextureHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayTextureSize\fP (ulong ulOverlayHandle, ref uint pWidth, ref uint pHeight)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_CreateDashboardOverlay\fP (string pchOverlayKey, string pchOverlayFriendlyName, ref ulong pMainHandle, ref ulong pThumbnailHandle)"
.br
.ti -1c
.RI "internal delegate bool \fB_IsDashboardVisible\fP ()"
.br
.ti -1c
.RI "internal delegate bool \fB_IsActiveDashboardOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetDashboardOverlaySceneProcess\fP (ulong ulOverlayHandle, uint unProcessId)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetDashboardOverlaySceneProcess\fP (ulong ulOverlayHandle, ref uint punProcessId)"
.br
.ti -1c
.RI "internal delegate void \fB_ShowDashboard\fP (string pchOverlayToShow)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetPrimaryDashboardDevice\fP ()"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_ShowKeyboard\fP (int eInputMode, int eLineInputMode, string pchDescription, uint unCharMax, string pchExistingText, bool bUseMinimalMode, ulong uUserValue)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_ShowKeyboardForOverlay\fP (ulong ulOverlayHandle, int eInputMode, int eLineInputMode, string pchDescription, uint unCharMax, string pchExistingText, bool bUseMinimalMode, ulong uUserValue)"
.br
.ti -1c
.RI "internal delegate uint \fB_GetKeyboardText\fP (System\&.Text\&.StringBuilder pchText, uint cchText)"
.br
.ti -1c
.RI "internal delegate void \fB_HideKeyboard\fP ()"
.br
.ti -1c
.RI "internal delegate void \fB_SetKeyboardTransformAbsolute\fP (\fBETrackingUniverseOrigin\fP eTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToKeyboardTransform)"
.br
.ti -1c
.RI "internal delegate void \fB_SetKeyboardPositionForOverlay\fP (ulong ulOverlayHandle, \fBHmdRect2_t\fP avoidRect)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_SetOverlayIntersectionMask\fP (ulong ulOverlayHandle, ref \fBVROverlayIntersectionMaskPrimitive_t\fP pMaskPrimitives, uint unNumMaskPrimitives, uint unPrimitiveSize)"
.br
.ti -1c
.RI "internal delegate \fBEVROverlayError\fP \fB_GetOverlayFlags\fP (ulong ulOverlayHandle, ref uint pFlags)"
.br
.ti -1c
.RI "internal delegate \fBVRMessageOverlayResponse\fP \fB_ShowMessageOverlay\fP (string pchText, string pchCaption, string pchButton0Text, string pchButton1Text, string pchButton2Text, string pchButton3Text)"
.br
.ti -1c
.RI "internal delegate void \fB_CloseMessageOverlay\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internal \fB_FindOverlay\fP \fBFindOverlay\fP"
.br
.ti -1c
.RI "internal \fB_CreateOverlay\fP \fBCreateOverlay\fP"
.br
.ti -1c
.RI "internal \fB_DestroyOverlay\fP \fBDestroyOverlay\fP"
.br
.ti -1c
.RI "internal \fB_SetHighQualityOverlay\fP \fBSetHighQualityOverlay\fP"
.br
.ti -1c
.RI "internal \fB_GetHighQualityOverlay\fP \fBGetHighQualityOverlay\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayKey\fP \fBGetOverlayKey\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayName\fP \fBGetOverlayName\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayName\fP \fBSetOverlayName\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayImageData\fP \fBGetOverlayImageData\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayErrorNameFromEnum\fP \fBGetOverlayErrorNameFromEnum\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayRenderingPid\fP \fBSetOverlayRenderingPid\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayRenderingPid\fP \fBGetOverlayRenderingPid\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayFlag\fP \fBSetOverlayFlag\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayFlag\fP \fBGetOverlayFlag\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayColor\fP \fBSetOverlayColor\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayColor\fP \fBGetOverlayColor\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayAlpha\fP \fBSetOverlayAlpha\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayAlpha\fP \fBGetOverlayAlpha\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayTexelAspect\fP \fBSetOverlayTexelAspect\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayTexelAspect\fP \fBGetOverlayTexelAspect\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlaySortOrder\fP \fBSetOverlaySortOrder\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlaySortOrder\fP \fBGetOverlaySortOrder\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayWidthInMeters\fP \fBSetOverlayWidthInMeters\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayWidthInMeters\fP \fBGetOverlayWidthInMeters\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayAutoCurveDistanceRangeInMeters\fP \fBSetOverlayAutoCurveDistanceRangeInMeters\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayAutoCurveDistanceRangeInMeters\fP \fBGetOverlayAutoCurveDistanceRangeInMeters\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayTextureColorSpace\fP \fBSetOverlayTextureColorSpace\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayTextureColorSpace\fP \fBGetOverlayTextureColorSpace\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayTextureBounds\fP \fBSetOverlayTextureBounds\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayTextureBounds\fP \fBGetOverlayTextureBounds\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayRenderModel\fP \fBGetOverlayRenderModel\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayRenderModel\fP \fBSetOverlayRenderModel\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayTransformType\fP \fBGetOverlayTransformType\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayTransformAbsolute\fP \fBSetOverlayTransformAbsolute\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayTransformAbsolute\fP \fBGetOverlayTransformAbsolute\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayTransformTrackedDeviceRelative\fP \fBSetOverlayTransformTrackedDeviceRelative\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayTransformTrackedDeviceRelative\fP \fBGetOverlayTransformTrackedDeviceRelative\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayTransformTrackedDeviceComponent\fP \fBSetOverlayTransformTrackedDeviceComponent\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayTransformTrackedDeviceComponent\fP \fBGetOverlayTransformTrackedDeviceComponent\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayTransformOverlayRelative\fP \fBGetOverlayTransformOverlayRelative\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayTransformOverlayRelative\fP \fBSetOverlayTransformOverlayRelative\fP"
.br
.ti -1c
.RI "internal \fB_ShowOverlay\fP \fBShowOverlay\fP"
.br
.ti -1c
.RI "internal \fB_HideOverlay\fP \fBHideOverlay\fP"
.br
.ti -1c
.RI "internal \fB_IsOverlayVisible\fP \fBIsOverlayVisible\fP"
.br
.ti -1c
.RI "internal \fB_GetTransformForOverlayCoordinates\fP \fBGetTransformForOverlayCoordinates\fP"
.br
.ti -1c
.RI "internal \fB_PollNextOverlayEvent\fP \fBPollNextOverlayEvent\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayInputMethod\fP \fBGetOverlayInputMethod\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayInputMethod\fP \fBSetOverlayInputMethod\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayMouseScale\fP \fBGetOverlayMouseScale\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayMouseScale\fP \fBSetOverlayMouseScale\fP"
.br
.ti -1c
.RI "internal \fB_ComputeOverlayIntersection\fP \fBComputeOverlayIntersection\fP"
.br
.ti -1c
.RI "internal \fB_IsHoverTargetOverlay\fP \fBIsHoverTargetOverlay\fP"
.br
.ti -1c
.RI "internal \fB_GetGamepadFocusOverlay\fP \fBGetGamepadFocusOverlay\fP"
.br
.ti -1c
.RI "internal \fB_SetGamepadFocusOverlay\fP \fBSetGamepadFocusOverlay\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayNeighbor\fP \fBSetOverlayNeighbor\fP"
.br
.ti -1c
.RI "internal \fB_MoveGamepadFocusToNeighbor\fP \fBMoveGamepadFocusToNeighbor\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayDualAnalogTransform\fP \fBSetOverlayDualAnalogTransform\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayDualAnalogTransform\fP \fBGetOverlayDualAnalogTransform\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayTexture\fP \fBSetOverlayTexture\fP"
.br
.ti -1c
.RI "internal \fB_ClearOverlayTexture\fP \fBClearOverlayTexture\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayRaw\fP \fBSetOverlayRaw\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayFromFile\fP \fBSetOverlayFromFile\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayTexture\fP \fBGetOverlayTexture\fP"
.br
.ti -1c
.RI "internal \fB_ReleaseNativeOverlayHandle\fP \fBReleaseNativeOverlayHandle\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayTextureSize\fP \fBGetOverlayTextureSize\fP"
.br
.ti -1c
.RI "internal \fB_CreateDashboardOverlay\fP \fBCreateDashboardOverlay\fP"
.br
.ti -1c
.RI "internal \fB_IsDashboardVisible\fP \fBIsDashboardVisible\fP"
.br
.ti -1c
.RI "internal \fB_IsActiveDashboardOverlay\fP \fBIsActiveDashboardOverlay\fP"
.br
.ti -1c
.RI "internal \fB_SetDashboardOverlaySceneProcess\fP \fBSetDashboardOverlaySceneProcess\fP"
.br
.ti -1c
.RI "internal \fB_GetDashboardOverlaySceneProcess\fP \fBGetDashboardOverlaySceneProcess\fP"
.br
.ti -1c
.RI "internal \fB_ShowDashboard\fP \fBShowDashboard\fP"
.br
.ti -1c
.RI "internal \fB_GetPrimaryDashboardDevice\fP \fBGetPrimaryDashboardDevice\fP"
.br
.ti -1c
.RI "internal \fB_ShowKeyboard\fP \fBShowKeyboard\fP"
.br
.ti -1c
.RI "internal \fB_ShowKeyboardForOverlay\fP \fBShowKeyboardForOverlay\fP"
.br
.ti -1c
.RI "internal \fB_GetKeyboardText\fP \fBGetKeyboardText\fP"
.br
.ti -1c
.RI "internal \fB_HideKeyboard\fP \fBHideKeyboard\fP"
.br
.ti -1c
.RI "internal \fB_SetKeyboardTransformAbsolute\fP \fBSetKeyboardTransformAbsolute\fP"
.br
.ti -1c
.RI "internal \fB_SetKeyboardPositionForOverlay\fP \fBSetKeyboardPositionForOverlay\fP"
.br
.ti -1c
.RI "internal \fB_SetOverlayIntersectionMask\fP \fBSetOverlayIntersectionMask\fP"
.br
.ti -1c
.RI "internal \fB_GetOverlayFlags\fP \fBGetOverlayFlags\fP"
.br
.ti -1c
.RI "internal \fB_ShowMessageOverlay\fP \fBShowMessageOverlay\fP"
.br
.ti -1c
.RI "internal \fB_CloseMessageOverlay\fP \fBCloseMessageOverlay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 871 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._ClearOverlayTexture (ulong ulOverlayHandle)"

.SS "internal delegate void Valve\&.VR\&.IVROverlay\&._CloseMessageOverlay ()"

.SS "internal delegate bool Valve\&.VR\&.IVROverlay\&._ComputeOverlayIntersection (ulong ulOverlayHandle, ref \fBVROverlayIntersectionParams_t\fP pParams, ref \fBVROverlayIntersectionResults_t\fP pResults)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._CreateDashboardOverlay (string pchOverlayKey, string pchOverlayFriendlyName, ref ulong pMainHandle, ref ulong pThumbnailHandle)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._CreateOverlay (string pchOverlayKey, string pchOverlayName, ref ulong pOverlayHandle)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._DestroyOverlay (ulong ulOverlayHandle)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._FindOverlay (string pchOverlayKey, ref ulong pOverlayHandle)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetDashboardOverlaySceneProcess (ulong ulOverlayHandle, ref uint punProcessId)"

.SS "internal delegate ulong Valve\&.VR\&.IVROverlay\&._GetGamepadFocusOverlay ()"

.SS "internal delegate ulong Valve\&.VR\&.IVROverlay\&._GetHighQualityOverlay ()"

.SS "internal delegate uint Valve\&.VR\&.IVROverlay\&._GetKeyboardText (System\&.Text\&.StringBuilder pchText, uint cchText)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayAlpha (ulong ulOverlayHandle, ref float pfAlpha)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayAutoCurveDistanceRangeInMeters (ulong ulOverlayHandle, ref float pfMinDistanceInMeters, ref float pfMaxDistanceInMeters)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayColor (ulong ulOverlayHandle, ref float pfRed, ref float pfGreen, ref float pfBlue)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayDualAnalogTransform (ulong ulOverlay, \fBEDualAnalogWhich\fP eWhich, ref \fBHmdVector2_t\fP pvCenter, ref float pfRadius)"

.SS "internal delegate IntPtr Valve\&.VR\&.IVROverlay\&._GetOverlayErrorNameFromEnum (\fBEVROverlayError\fP error)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayFlag (ulong ulOverlayHandle, \fBVROverlayFlags\fP eOverlayFlag, ref bool pbEnabled)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayFlags (ulong ulOverlayHandle, ref uint pFlags)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayImageData (ulong ulOverlayHandle, IntPtr pvBuffer, uint unBufferSize, ref uint punWidth, ref uint punHeight)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayInputMethod (ulong ulOverlayHandle, ref \fBVROverlayInputMethod\fP peInputMethod)"

.SS "internal delegate uint Valve\&.VR\&.IVROverlay\&._GetOverlayKey (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBEVROverlayError\fP pError)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayMouseScale (ulong ulOverlayHandle, ref \fBHmdVector2_t\fP pvecMouseScale)"

.SS "internal delegate uint Valve\&.VR\&.IVROverlay\&._GetOverlayName (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBEVROverlayError\fP pError)"

.SS "internal delegate uint Valve\&.VR\&.IVROverlay\&._GetOverlayRenderingPid (ulong ulOverlayHandle)"

.SS "internal delegate uint Valve\&.VR\&.IVROverlay\&._GetOverlayRenderModel (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBHmdColor_t\fP pColor, ref \fBEVROverlayError\fP pError)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlaySortOrder (ulong ulOverlayHandle, ref uint punSortOrder)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayTexelAspect (ulong ulOverlayHandle, ref float pfTexelAspect)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayTexture (ulong ulOverlayHandle, ref IntPtr pNativeTextureHandle, IntPtr pNativeTextureRef, ref uint pWidth, ref uint pHeight, ref uint pNativeFormat, ref \fBETextureType\fP pAPIType, ref \fBEColorSpace\fP pColorSpace, ref \fBVRTextureBounds_t\fP pTextureBounds)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayTextureBounds (ulong ulOverlayHandle, ref \fBVRTextureBounds_t\fP pOverlayTextureBounds)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayTextureColorSpace (ulong ulOverlayHandle, ref \fBEColorSpace\fP peTextureColorSpace)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayTextureSize (ulong ulOverlayHandle, ref uint pWidth, ref uint pHeight)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayTransformAbsolute (ulong ulOverlayHandle, ref \fBETrackingUniverseOrigin\fP peTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToOverlayTransform)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayTransformOverlayRelative (ulong ulOverlayHandle, ref ulong ulOverlayHandleParent, ref \fBHmdMatrix34_t\fP pmatParentOverlayToOverlayTransform)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayTransformTrackedDeviceComponent (ulong ulOverlayHandle, ref uint punDeviceIndex, System\&.Text\&.StringBuilder pchComponentName, uint unComponentNameSize)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayTransformTrackedDeviceRelative (ulong ulOverlayHandle, ref uint punTrackedDevice, ref \fBHmdMatrix34_t\fP pmatTrackedDeviceToOverlayTransform)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayTransformType (ulong ulOverlayHandle, ref \fBVROverlayTransformType\fP peTransformType)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetOverlayWidthInMeters (ulong ulOverlayHandle, ref float pfWidthInMeters)"

.SS "internal delegate uint Valve\&.VR\&.IVROverlay\&._GetPrimaryDashboardDevice ()"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._GetTransformForOverlayCoordinates (ulong ulOverlayHandle, \fBETrackingUniverseOrigin\fP eTrackingOrigin, \fBHmdVector2_t\fP coordinatesInOverlay, ref \fBHmdMatrix34_t\fP pmatTransform)"

.SS "internal delegate void Valve\&.VR\&.IVROverlay\&._HideKeyboard ()"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._HideOverlay (ulong ulOverlayHandle)"

.SS "internal delegate bool Valve\&.VR\&.IVROverlay\&._IsActiveDashboardOverlay (ulong ulOverlayHandle)"

.SS "internal delegate bool Valve\&.VR\&.IVROverlay\&._IsDashboardVisible ()"

.SS "internal delegate bool Valve\&.VR\&.IVROverlay\&._IsHoverTargetOverlay (ulong ulOverlayHandle)"

.SS "internal delegate bool Valve\&.VR\&.IVROverlay\&._IsOverlayVisible (ulong ulOverlayHandle)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._MoveGamepadFocusToNeighbor (\fBEOverlayDirection\fP eDirection, ulong ulFrom)"

.SS "internal delegate bool Valve\&.VR\&.IVROverlay\&._PollNextOverlayEvent (ulong ulOverlayHandle, ref \fBVREvent_t\fP pEvent, uint uncbVREvent)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._ReleaseNativeOverlayHandle (ulong ulOverlayHandle, IntPtr pNativeTextureHandle)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetDashboardOverlaySceneProcess (ulong ulOverlayHandle, uint unProcessId)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetGamepadFocusOverlay (ulong ulNewFocusOverlay)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetHighQualityOverlay (ulong ulOverlayHandle)"

.SS "internal delegate void Valve\&.VR\&.IVROverlay\&._SetKeyboardPositionForOverlay (ulong ulOverlayHandle, \fBHmdRect2_t\fP avoidRect)"

.SS "internal delegate void Valve\&.VR\&.IVROverlay\&._SetKeyboardTransformAbsolute (\fBETrackingUniverseOrigin\fP eTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToKeyboardTransform)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayAlpha (ulong ulOverlayHandle, float fAlpha)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayAutoCurveDistanceRangeInMeters (ulong ulOverlayHandle, float fMinDistanceInMeters, float fMaxDistanceInMeters)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayColor (ulong ulOverlayHandle, float fRed, float fGreen, float fBlue)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayDualAnalogTransform (ulong ulOverlay, \fBEDualAnalogWhich\fP eWhich, ref \fBHmdVector2_t\fP pvCenter, float fRadius)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayFlag (ulong ulOverlayHandle, \fBVROverlayFlags\fP eOverlayFlag, bool bEnabled)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayFromFile (ulong ulOverlayHandle, string pchFilePath)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayInputMethod (ulong ulOverlayHandle, \fBVROverlayInputMethod\fP eInputMethod)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayIntersectionMask (ulong ulOverlayHandle, ref \fBVROverlayIntersectionMaskPrimitive_t\fP pMaskPrimitives, uint unNumMaskPrimitives, uint unPrimitiveSize)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayMouseScale (ulong ulOverlayHandle, ref \fBHmdVector2_t\fP pvecMouseScale)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayName (ulong ulOverlayHandle, string pchName)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayNeighbor (\fBEOverlayDirection\fP eDirection, ulong ulFrom, ulong ulTo)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayRaw (ulong ulOverlayHandle, IntPtr pvBuffer, uint unWidth, uint unHeight, uint unDepth)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayRenderingPid (ulong ulOverlayHandle, uint unPID)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayRenderModel (ulong ulOverlayHandle, string pchRenderModel, ref \fBHmdColor_t\fP pColor)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlaySortOrder (ulong ulOverlayHandle, uint unSortOrder)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayTexelAspect (ulong ulOverlayHandle, float fTexelAspect)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayTexture (ulong ulOverlayHandle, ref \fBTexture_t\fP pTexture)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayTextureBounds (ulong ulOverlayHandle, ref \fBVRTextureBounds_t\fP pOverlayTextureBounds)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayTextureColorSpace (ulong ulOverlayHandle, \fBEColorSpace\fP eTextureColorSpace)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayTransformAbsolute (ulong ulOverlayHandle, \fBETrackingUniverseOrigin\fP eTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToOverlayTransform)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayTransformOverlayRelative (ulong ulOverlayHandle, ulong ulOverlayHandleParent, ref \fBHmdMatrix34_t\fP pmatParentOverlayToOverlayTransform)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayTransformTrackedDeviceComponent (ulong ulOverlayHandle, uint unDeviceIndex, string pchComponentName)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayTransformTrackedDeviceRelative (ulong ulOverlayHandle, uint unTrackedDevice, ref \fBHmdMatrix34_t\fP pmatTrackedDeviceToOverlayTransform)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._SetOverlayWidthInMeters (ulong ulOverlayHandle, float fWidthInMeters)"

.SS "internal delegate void Valve\&.VR\&.IVROverlay\&._ShowDashboard (string pchOverlayToShow)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._ShowKeyboard (int eInputMode, int eLineInputMode, string pchDescription, uint unCharMax, string pchExistingText, bool bUseMinimalMode, ulong uUserValue)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._ShowKeyboardForOverlay (ulong ulOverlayHandle, int eInputMode, int eLineInputMode, string pchDescription, uint unCharMax, string pchExistingText, bool bUseMinimalMode, ulong uUserValue)"

.SS "internal delegate \fBVRMessageOverlayResponse\fP Valve\&.VR\&.IVROverlay\&._ShowMessageOverlay (string pchText, string pchCaption, string pchButton0Text, string pchButton1Text, string pchButton2Text, string pchButton3Text)"

.SS "internal delegate \fBEVROverlayError\fP Valve\&.VR\&.IVROverlay\&._ShowOverlay (ulong ulOverlayHandle)"

.SH "Member Data Documentation"
.PP 
.SS "internal \fB_ClearOverlayTexture\fP Valve\&.VR\&.IVROverlay\&.ClearOverlayTexture"

.PP
Definition at line 1171 of file openvr_api\&.cs\&.
.SS "internal \fB_CloseMessageOverlay\fP Valve\&.VR\&.IVROverlay\&.CloseMessageOverlay"

.PP
Definition at line 1281 of file openvr_api\&.cs\&.
.SS "internal \fB_ComputeOverlayIntersection\fP Valve\&.VR\&.IVROverlay\&.ComputeOverlayIntersection"

.PP
Definition at line 1126 of file openvr_api\&.cs\&.
.SS "internal \fB_CreateDashboardOverlay\fP Valve\&.VR\&.IVROverlay\&.CreateDashboardOverlay"

.PP
Definition at line 1201 of file openvr_api\&.cs\&.
.SS "internal \fB_CreateOverlay\fP Valve\&.VR\&.IVROverlay\&.CreateOverlay"

.PP
Definition at line 881 of file openvr_api\&.cs\&.
.SS "internal \fB_DestroyOverlay\fP Valve\&.VR\&.IVROverlay\&.DestroyOverlay"

.PP
Definition at line 886 of file openvr_api\&.cs\&.
.SS "internal \fB_FindOverlay\fP Valve\&.VR\&.IVROverlay\&.FindOverlay"

.PP
Definition at line 876 of file openvr_api\&.cs\&.
.SS "internal \fB_GetDashboardOverlaySceneProcess\fP Valve\&.VR\&.IVROverlay\&.GetDashboardOverlaySceneProcess"

.PP
Definition at line 1221 of file openvr_api\&.cs\&.
.SS "internal \fB_GetGamepadFocusOverlay\fP Valve\&.VR\&.IVROverlay\&.GetGamepadFocusOverlay"

.PP
Definition at line 1136 of file openvr_api\&.cs\&.
.SS "internal \fB_GetHighQualityOverlay\fP Valve\&.VR\&.IVROverlay\&.GetHighQualityOverlay"

.PP
Definition at line 896 of file openvr_api\&.cs\&.
.SS "internal \fB_GetKeyboardText\fP Valve\&.VR\&.IVROverlay\&.GetKeyboardText"

.PP
Definition at line 1246 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayAlpha\fP Valve\&.VR\&.IVROverlay\&.GetOverlayAlpha"

.PP
Definition at line 961 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayAutoCurveDistanceRangeInMeters\fP Valve\&.VR\&.IVROverlay\&.GetOverlayAutoCurveDistanceRangeInMeters"

.PP
Definition at line 1001 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayColor\fP Valve\&.VR\&.IVROverlay\&.GetOverlayColor"

.PP
Definition at line 951 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayDualAnalogTransform\fP Valve\&.VR\&.IVROverlay\&.GetOverlayDualAnalogTransform"

.PP
Definition at line 1161 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayErrorNameFromEnum\fP Valve\&.VR\&.IVROverlay\&.GetOverlayErrorNameFromEnum"

.PP
Definition at line 921 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayFlag\fP Valve\&.VR\&.IVROverlay\&.GetOverlayFlag"

.PP
Definition at line 941 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayFlags\fP Valve\&.VR\&.IVROverlay\&.GetOverlayFlags"

.PP
Definition at line 1271 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayImageData\fP Valve\&.VR\&.IVROverlay\&.GetOverlayImageData"

.PP
Definition at line 916 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayInputMethod\fP Valve\&.VR\&.IVROverlay\&.GetOverlayInputMethod"

.PP
Definition at line 1106 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayKey\fP Valve\&.VR\&.IVROverlay\&.GetOverlayKey"

.PP
Definition at line 901 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayMouseScale\fP Valve\&.VR\&.IVROverlay\&.GetOverlayMouseScale"

.PP
Definition at line 1116 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayName\fP Valve\&.VR\&.IVROverlay\&.GetOverlayName"

.PP
Definition at line 906 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayRenderingPid\fP Valve\&.VR\&.IVROverlay\&.GetOverlayRenderingPid"

.PP
Definition at line 931 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayRenderModel\fP Valve\&.VR\&.IVROverlay\&.GetOverlayRenderModel"

.PP
Definition at line 1026 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlaySortOrder\fP Valve\&.VR\&.IVROverlay\&.GetOverlaySortOrder"

.PP
Definition at line 981 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayTexelAspect\fP Valve\&.VR\&.IVROverlay\&.GetOverlayTexelAspect"

.PP
Definition at line 971 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayTexture\fP Valve\&.VR\&.IVROverlay\&.GetOverlayTexture"

.PP
Definition at line 1186 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayTextureBounds\fP Valve\&.VR\&.IVROverlay\&.GetOverlayTextureBounds"

.PP
Definition at line 1021 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayTextureColorSpace\fP Valve\&.VR\&.IVROverlay\&.GetOverlayTextureColorSpace"

.PP
Definition at line 1011 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayTextureSize\fP Valve\&.VR\&.IVROverlay\&.GetOverlayTextureSize"

.PP
Definition at line 1196 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayTransformAbsolute\fP Valve\&.VR\&.IVROverlay\&.GetOverlayTransformAbsolute"

.PP
Definition at line 1046 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayTransformOverlayRelative\fP Valve\&.VR\&.IVROverlay\&.GetOverlayTransformOverlayRelative"

.PP
Definition at line 1071 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayTransformTrackedDeviceComponent\fP Valve\&.VR\&.IVROverlay\&.GetOverlayTransformTrackedDeviceComponent"

.PP
Definition at line 1066 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayTransformTrackedDeviceRelative\fP Valve\&.VR\&.IVROverlay\&.GetOverlayTransformTrackedDeviceRelative"

.PP
Definition at line 1056 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayTransformType\fP Valve\&.VR\&.IVROverlay\&.GetOverlayTransformType"

.PP
Definition at line 1036 of file openvr_api\&.cs\&.
.SS "internal \fB_GetOverlayWidthInMeters\fP Valve\&.VR\&.IVROverlay\&.GetOverlayWidthInMeters"

.PP
Definition at line 991 of file openvr_api\&.cs\&.
.SS "internal \fB_GetPrimaryDashboardDevice\fP Valve\&.VR\&.IVROverlay\&.GetPrimaryDashboardDevice"

.PP
Definition at line 1231 of file openvr_api\&.cs\&.
.SS "internal \fB_GetTransformForOverlayCoordinates\fP Valve\&.VR\&.IVROverlay\&.GetTransformForOverlayCoordinates"

.PP
Definition at line 1096 of file openvr_api\&.cs\&.
.SS "internal \fB_HideKeyboard\fP Valve\&.VR\&.IVROverlay\&.HideKeyboard"

.PP
Definition at line 1251 of file openvr_api\&.cs\&.
.SS "internal \fB_HideOverlay\fP Valve\&.VR\&.IVROverlay\&.HideOverlay"

.PP
Definition at line 1086 of file openvr_api\&.cs\&.
.SS "internal \fB_IsActiveDashboardOverlay\fP Valve\&.VR\&.IVROverlay\&.IsActiveDashboardOverlay"

.PP
Definition at line 1211 of file openvr_api\&.cs\&.
.SS "internal \fB_IsDashboardVisible\fP Valve\&.VR\&.IVROverlay\&.IsDashboardVisible"

.PP
Definition at line 1206 of file openvr_api\&.cs\&.
.SS "internal \fB_IsHoverTargetOverlay\fP Valve\&.VR\&.IVROverlay\&.IsHoverTargetOverlay"

.PP
Definition at line 1131 of file openvr_api\&.cs\&.
.SS "internal \fB_IsOverlayVisible\fP Valve\&.VR\&.IVROverlay\&.IsOverlayVisible"

.PP
Definition at line 1091 of file openvr_api\&.cs\&.
.SS "internal \fB_MoveGamepadFocusToNeighbor\fP Valve\&.VR\&.IVROverlay\&.MoveGamepadFocusToNeighbor"

.PP
Definition at line 1151 of file openvr_api\&.cs\&.
.SS "internal \fB_PollNextOverlayEvent\fP Valve\&.VR\&.IVROverlay\&.PollNextOverlayEvent"

.PP
Definition at line 1101 of file openvr_api\&.cs\&.
.SS "internal \fB_ReleaseNativeOverlayHandle\fP Valve\&.VR\&.IVROverlay\&.ReleaseNativeOverlayHandle"

.PP
Definition at line 1191 of file openvr_api\&.cs\&.
.SS "internal \fB_SetDashboardOverlaySceneProcess\fP Valve\&.VR\&.IVROverlay\&.SetDashboardOverlaySceneProcess"

.PP
Definition at line 1216 of file openvr_api\&.cs\&.
.SS "internal \fB_SetGamepadFocusOverlay\fP Valve\&.VR\&.IVROverlay\&.SetGamepadFocusOverlay"

.PP
Definition at line 1141 of file openvr_api\&.cs\&.
.SS "internal \fB_SetHighQualityOverlay\fP Valve\&.VR\&.IVROverlay\&.SetHighQualityOverlay"

.PP
Definition at line 891 of file openvr_api\&.cs\&.
.SS "internal \fB_SetKeyboardPositionForOverlay\fP Valve\&.VR\&.IVROverlay\&.SetKeyboardPositionForOverlay"

.PP
Definition at line 1261 of file openvr_api\&.cs\&.
.SS "internal \fB_SetKeyboardTransformAbsolute\fP Valve\&.VR\&.IVROverlay\&.SetKeyboardTransformAbsolute"

.PP
Definition at line 1256 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayAlpha\fP Valve\&.VR\&.IVROverlay\&.SetOverlayAlpha"

.PP
Definition at line 956 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayAutoCurveDistanceRangeInMeters\fP Valve\&.VR\&.IVROverlay\&.SetOverlayAutoCurveDistanceRangeInMeters"

.PP
Definition at line 996 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayColor\fP Valve\&.VR\&.IVROverlay\&.SetOverlayColor"

.PP
Definition at line 946 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayDualAnalogTransform\fP Valve\&.VR\&.IVROverlay\&.SetOverlayDualAnalogTransform"

.PP
Definition at line 1156 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayFlag\fP Valve\&.VR\&.IVROverlay\&.SetOverlayFlag"

.PP
Definition at line 936 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayFromFile\fP Valve\&.VR\&.IVROverlay\&.SetOverlayFromFile"

.PP
Definition at line 1181 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayInputMethod\fP Valve\&.VR\&.IVROverlay\&.SetOverlayInputMethod"

.PP
Definition at line 1111 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayIntersectionMask\fP Valve\&.VR\&.IVROverlay\&.SetOverlayIntersectionMask"

.PP
Definition at line 1266 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayMouseScale\fP Valve\&.VR\&.IVROverlay\&.SetOverlayMouseScale"

.PP
Definition at line 1121 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayName\fP Valve\&.VR\&.IVROverlay\&.SetOverlayName"

.PP
Definition at line 911 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayNeighbor\fP Valve\&.VR\&.IVROverlay\&.SetOverlayNeighbor"

.PP
Definition at line 1146 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayRaw\fP Valve\&.VR\&.IVROverlay\&.SetOverlayRaw"

.PP
Definition at line 1176 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayRenderingPid\fP Valve\&.VR\&.IVROverlay\&.SetOverlayRenderingPid"

.PP
Definition at line 926 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayRenderModel\fP Valve\&.VR\&.IVROverlay\&.SetOverlayRenderModel"

.PP
Definition at line 1031 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlaySortOrder\fP Valve\&.VR\&.IVROverlay\&.SetOverlaySortOrder"

.PP
Definition at line 976 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayTexelAspect\fP Valve\&.VR\&.IVROverlay\&.SetOverlayTexelAspect"

.PP
Definition at line 966 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayTexture\fP Valve\&.VR\&.IVROverlay\&.SetOverlayTexture"

.PP
Definition at line 1166 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayTextureBounds\fP Valve\&.VR\&.IVROverlay\&.SetOverlayTextureBounds"

.PP
Definition at line 1016 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayTextureColorSpace\fP Valve\&.VR\&.IVROverlay\&.SetOverlayTextureColorSpace"

.PP
Definition at line 1006 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayTransformAbsolute\fP Valve\&.VR\&.IVROverlay\&.SetOverlayTransformAbsolute"

.PP
Definition at line 1041 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayTransformOverlayRelative\fP Valve\&.VR\&.IVROverlay\&.SetOverlayTransformOverlayRelative"

.PP
Definition at line 1076 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayTransformTrackedDeviceComponent\fP Valve\&.VR\&.IVROverlay\&.SetOverlayTransformTrackedDeviceComponent"

.PP
Definition at line 1061 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayTransformTrackedDeviceRelative\fP Valve\&.VR\&.IVROverlay\&.SetOverlayTransformTrackedDeviceRelative"

.PP
Definition at line 1051 of file openvr_api\&.cs\&.
.SS "internal \fB_SetOverlayWidthInMeters\fP Valve\&.VR\&.IVROverlay\&.SetOverlayWidthInMeters"

.PP
Definition at line 986 of file openvr_api\&.cs\&.
.SS "internal \fB_ShowDashboard\fP Valve\&.VR\&.IVROverlay\&.ShowDashboard"

.PP
Definition at line 1226 of file openvr_api\&.cs\&.
.SS "internal \fB_ShowKeyboard\fP Valve\&.VR\&.IVROverlay\&.ShowKeyboard"

.PP
Definition at line 1236 of file openvr_api\&.cs\&.
.SS "internal \fB_ShowKeyboardForOverlay\fP Valve\&.VR\&.IVROverlay\&.ShowKeyboardForOverlay"

.PP
Definition at line 1241 of file openvr_api\&.cs\&.
.SS "internal \fB_ShowMessageOverlay\fP Valve\&.VR\&.IVROverlay\&.ShowMessageOverlay"

.PP
Definition at line 1276 of file openvr_api\&.cs\&.
.SS "internal \fB_ShowOverlay\fP Valve\&.VR\&.IVROverlay\&.ShowOverlay"

.PP
Definition at line 1081 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
