.TH "Valve.VR.InteractionSystem.ComplexThrowable" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.ComplexThrowable
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAttachMode\fP { \fBAttachMode\&.FixedJoint\fP, \fBAttachMode\&.Force\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBattachForce\fP = 800\&.0f"
.br
.ti -1c
.RI "float \fBattachForceDamper\fP = 25\&.0f"
.br
.ti -1c
.RI "\fBAttachMode\fP \fBattachMode\fP = \fBAttachMode\&.FixedJoint\fP"
.br
.ti -1c
.RI "\fBHand\&.AttachmentFlags\fP \fBattachmentFlags\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file ComplexThrowable\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.InteractionSystem\&.ComplexThrowable\&.AttachMode\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFixedJoint \fP\fP
.TP
\fB\fIForce \fP\fP
.PP
Definition at line 17 of file ComplexThrowable\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.InteractionSystem\&.ComplexThrowable\&.attachForce = 800\&.0f"

.PP
Definition at line 23 of file ComplexThrowable\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.ComplexThrowable\&.attachForceDamper = 25\&.0f"

.PP
Definition at line 24 of file ComplexThrowable\&.cs\&.
.SS "\fBHand\&.AttachmentFlags\fP Valve\&.VR\&.InteractionSystem\&.ComplexThrowable\&.attachmentFlags = 0"

.PP
Definition at line 29 of file ComplexThrowable\&.cs\&.
.SS "\fBAttachMode\fP Valve\&.VR\&.InteractionSystem\&.ComplexThrowable\&.attachMode = \fBAttachMode\&.FixedJoint\fP"

.PP
Definition at line 26 of file ComplexThrowable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
