.TH "Valve.VR.InteractionSystem.Sample.JoeJeffController" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Sample.JoeJeffController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBJoystick\fP"
.br
.ti -1c
.RI "float \fBjoyMove\fP = 0\&.1f"
.br
.ti -1c
.RI "\fBSteamVR_Action_Vector2\fP \fBmoveAction\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Vector2\fP>('platformer', 'Move')"
.br
.ti -1c
.RI "\fBSteamVR_Action_Boolean\fP \fBjumpAction\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('platformer', 'Jump')"
.br
.ti -1c
.RI "\fBJoeJeff\fP \fBcharacter\fP"
.br
.ti -1c
.RI "Renderer \fBjumpHighlight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file JoeJeffController\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBJoeJeff\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.JoeJeffController\&.character"

.PP
Definition at line 16 of file JoeJeffController\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Sample\&.JoeJeffController\&.joyMove = 0\&.1f"

.PP
Definition at line 11 of file JoeJeffController\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.Sample\&.JoeJeffController\&.Joystick"

.PP
Definition at line 10 of file JoeJeffController\&.cs\&.
.SS "\fBSteamVR_Action_Boolean\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.JoeJeffController\&.jumpAction = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Boolean\fP>('platformer', 'Jump')"

.PP
Definition at line 14 of file JoeJeffController\&.cs\&.
.SS "Renderer Valve\&.VR\&.InteractionSystem\&.Sample\&.JoeJeffController\&.jumpHighlight"

.PP
Definition at line 18 of file JoeJeffController\&.cs\&.
.SS "\fBSteamVR_Action_Vector2\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.JoeJeffController\&.moveAction = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Vector2\fP>('platformer', 'Move')"

.PP
Definition at line 13 of file JoeJeffController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
