.TH "Valve.VR.SteamVR_Behaviour_Vector2Event" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Behaviour_Vector2Event
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEvent< SteamVR_Behaviour_Vector2, SteamVR_Input_Sources, Vector2, Vector2 >\&.
.SH "Detailed Description"
.PP 
Definition at line 10 of file SteamVR_Behaviour_Vector2Event\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
