.TH "Valve.VR.SteamVR_Skeleton_HandMask" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Skeleton_HandMask \- Simple mask for fingers  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetFinger\fP (int i, bool value)"
.br
.ti -1c
.RI "bool \fBGetFinger\fP (int i)"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_HandMask\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.RI "All elements on "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBpalm\fP"
.br
.ti -1c
.RI "bool \fBthumb\fP"
.br
.ti -1c
.RI "bool \fBindex\fP"
.br
.ti -1c
.RI "bool \fBmiddle\fP"
.br
.ti -1c
.RI "bool \fBring\fP"
.br
.ti -1c
.RI "bool \fBpinky\fP"
.br
.ti -1c
.RI "bool [] \fBvalues\fP = new bool[6]"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBSteamVR_Skeleton_HandMask\fP \fBfullMask\fP = new \fBSteamVR_Skeleton_HandMask\fP()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBApply\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simple mask for fingers 


.PP
Definition at line 474 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.SteamVR_Skeleton_HandMask ()"

.PP
Definition at line 495 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.Apply ()\fC [protected]\fP"

.PP
Definition at line 514 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.GetFinger (int i)"

.PP
Definition at line 490 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.Reset ()"

.PP
All elements on 
.PP
Definition at line 504 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.SetFinger (int i, bool value)"

.PP
Definition at line 484 of file SteamVR_Skeleton_Poser\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBSteamVR_Skeleton_HandMask\fP Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.fullMask = new \fBSteamVR_Skeleton_HandMask\fP()\fC [static]\fP"

.PP
Definition at line 524 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.index"

.PP
Definition at line 478 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.middle"

.PP
Definition at line 479 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.palm"

.PP
Definition at line 476 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.pinky"

.PP
Definition at line 481 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.ring"

.PP
Definition at line 480 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.thumb"

.PP
Definition at line 477 of file SteamVR_Skeleton_Poser\&.cs\&.
.SS "bool [] Valve\&.VR\&.SteamVR_Skeleton_HandMask\&.values = new bool[6]"

.PP
Definition at line 482 of file SteamVR_Skeleton_Poser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
