.TH "Valve.VR.SteamVR_Ears" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Ears
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_Camera\fP \fBvrcam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file SteamVR_Ears\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSteamVR_Camera\fP Valve\&.VR\&.SteamVR_Ears\&.vrcam"

.PP
Definition at line 15 of file SteamVR_Ears\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
