.TH "Valve.VR.VREvent_Process_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VREvent_Process_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint \fBpid\fP"
.br
.ti -1c
.RI "uint \fBoldPid\fP"
.br
.ti -1c
.RI "bool \fBbForced\fP"
.br
.ti -1c
.RI "bool \fBbConnectionLost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5074 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.VREvent_Process_t\&.bConnectionLost"

.PP
Definition at line 5081 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.VREvent_Process_t\&.bForced"

.PP
Definition at line 5079 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.VREvent_Process_t\&.oldPid"

.PP
Definition at line 5077 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.VREvent_Process_t\&.pid"

.PP
Definition at line 5076 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
