.TH "Valve.VR.CVRTrackedCamera" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.CVRTrackedCamera
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetCameraErrorNameFromEnum\fP (\fBEVRTrackedCameraError\fP eCameraError)"
.br
.ti -1c
.RI "\fBEVRTrackedCameraError\fP \fBHasCamera\fP (uint nDeviceIndex, ref bool pHasCamera)"
.br
.ti -1c
.RI "\fBEVRTrackedCameraError\fP \fBGetCameraFrameSize\fP (uint nDeviceIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref uint pnWidth, ref uint pnHeight, ref uint pnFrameBufferSize)"
.br
.ti -1c
.RI "\fBEVRTrackedCameraError\fP \fBGetCameraIntrinsics\fP (uint nDeviceIndex, uint nCameraIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref \fBHmdVector2_t\fP pFocalLength, ref \fBHmdVector2_t\fP pCenter)"
.br
.ti -1c
.RI "\fBEVRTrackedCameraError\fP \fBGetCameraProjection\fP (uint nDeviceIndex, uint nCameraIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, float flZNear, float flZFar, ref \fBHmdMatrix44_t\fP pProjection)"
.br
.ti -1c
.RI "\fBEVRTrackedCameraError\fP \fBAcquireVideoStreamingService\fP (uint nDeviceIndex, ref ulong pHandle)"
.br
.ti -1c
.RI "\fBEVRTrackedCameraError\fP \fBReleaseVideoStreamingService\fP (ulong hTrackedCamera)"
.br
.ti -1c
.RI "\fBEVRTrackedCameraError\fP \fBGetVideoStreamFrameBuffer\fP (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, IntPtr pFrameBuffer, uint nFrameBufferSize, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"
.br
.ti -1c
.RI "\fBEVRTrackedCameraError\fP \fBGetVideoStreamTextureSize\fP (uint nDeviceIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref \fBVRTextureBounds_t\fP pTextureBounds, ref uint pnWidth, ref uint pnHeight)"
.br
.ti -1c
.RI "\fBEVRTrackedCameraError\fP \fBGetVideoStreamTextureD3D11\fP (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, IntPtr pD3D11DeviceOrResource, ref IntPtr ppD3D11ShaderResourceView, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"
.br
.ti -1c
.RI "\fBEVRTrackedCameraError\fP \fBGetVideoStreamTextureGL\fP (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, ref uint pglTextureId, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"
.br
.ti -1c
.RI "\fBEVRTrackedCameraError\fP \fBReleaseVideoStreamTextureGL\fP (ulong hTrackedCamera, uint glTextureId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2081 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEVRTrackedCameraError\fP Valve\&.VR\&.CVRTrackedCamera\&.AcquireVideoStreamingService (uint nDeviceIndex, ref ulong pHandle)"

.PP
Definition at line 2117 of file openvr_api\&.cs\&.
.SS "string Valve\&.VR\&.CVRTrackedCamera\&.GetCameraErrorNameFromEnum (\fBEVRTrackedCameraError\fP eCameraError)"

.PP
Definition at line 2088 of file openvr_api\&.cs\&.
.SS "\fBEVRTrackedCameraError\fP Valve\&.VR\&.CVRTrackedCamera\&.GetCameraFrameSize (uint nDeviceIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref uint pnWidth, ref uint pnHeight, ref uint pnFrameBufferSize)"

.PP
Definition at line 2099 of file openvr_api\&.cs\&.
.SS "\fBEVRTrackedCameraError\fP Valve\&.VR\&.CVRTrackedCamera\&.GetCameraIntrinsics (uint nDeviceIndex, uint nCameraIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref \fBHmdVector2_t\fP pFocalLength, ref \fBHmdVector2_t\fP pCenter)"

.PP
Definition at line 2107 of file openvr_api\&.cs\&.
.SS "\fBEVRTrackedCameraError\fP Valve\&.VR\&.CVRTrackedCamera\&.GetCameraProjection (uint nDeviceIndex, uint nCameraIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, float flZNear, float flZFar, ref \fBHmdMatrix44_t\fP pProjection)"

.PP
Definition at line 2112 of file openvr_api\&.cs\&.
.SS "\fBEVRTrackedCameraError\fP Valve\&.VR\&.CVRTrackedCamera\&.GetVideoStreamFrameBuffer (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, IntPtr pFrameBuffer, uint nFrameBufferSize, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"

.PP
Definition at line 2128 of file openvr_api\&.cs\&.
.SS "\fBEVRTrackedCameraError\fP Valve\&.VR\&.CVRTrackedCamera\&.GetVideoStreamTextureD3D11 (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, IntPtr pD3D11DeviceOrResource, ref IntPtr ppD3D11ShaderResourceView, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"

.PP
Definition at line 2140 of file openvr_api\&.cs\&.
.SS "\fBEVRTrackedCameraError\fP Valve\&.VR\&.CVRTrackedCamera\&.GetVideoStreamTextureGL (ulong hTrackedCamera, \fBEVRTrackedCameraFrameType\fP eFrameType, ref uint pglTextureId, ref \fBCameraVideoStreamFrameHeader_t\fP pFrameHeader, uint nFrameHeaderSize)"

.PP
Definition at line 2145 of file openvr_api\&.cs\&.
.SS "\fBEVRTrackedCameraError\fP Valve\&.VR\&.CVRTrackedCamera\&.GetVideoStreamTextureSize (uint nDeviceIndex, \fBEVRTrackedCameraFrameType\fP eFrameType, ref \fBVRTextureBounds_t\fP pTextureBounds, ref uint pnWidth, ref uint pnHeight)"

.PP
Definition at line 2133 of file openvr_api\&.cs\&.
.SS "\fBEVRTrackedCameraError\fP Valve\&.VR\&.CVRTrackedCamera\&.HasCamera (uint nDeviceIndex, ref bool pHasCamera)"

.PP
Definition at line 2093 of file openvr_api\&.cs\&.
.SS "\fBEVRTrackedCameraError\fP Valve\&.VR\&.CVRTrackedCamera\&.ReleaseVideoStreamingService (ulong hTrackedCamera)"

.PP
Definition at line 2123 of file openvr_api\&.cs\&.
.SS "\fBEVRTrackedCameraError\fP Valve\&.VR\&.CVRTrackedCamera\&.ReleaseVideoStreamTextureGL (ulong hTrackedCamera, uint glTextureId)"

.PP
Definition at line 2151 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
