.TH "Valve.VR.InteractionSystem.UIElement" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.UIElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBValve\&.VR\&.InteractionSystem\&.Sample\&.RenderModelChangerUI\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCustomEvents\&.UnityEventHand\fP \fBonHandClick\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnHandHoverBegin\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "virtual void \fBOnHandHoverEnd\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "virtual void \fBHandHoverUpdate\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "virtual void \fBOnButtonClick\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBHand\fP \fBcurrentHand\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file UIElement\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.UIElement\&.Awake ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBValve\&.VR\&.InteractionSystem\&.Sample\&.RenderModelChangerUI\fP\&.
.PP
Definition at line 23 of file UIElement\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.UIElement\&.HandHoverUpdate (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 52 of file UIElement\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.UIElement\&.OnButtonClick ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBValve\&.VR\&.InteractionSystem\&.Sample\&.RenderModelChangerUI\fP\&.
.PP
Definition at line 63 of file UIElement\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.UIElement\&.OnHandHoverBegin (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 34 of file UIElement\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.UIElement\&.OnHandHoverEnd (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 43 of file UIElement\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHand\fP Valve\&.VR\&.InteractionSystem\&.UIElement\&.currentHand\fC [protected]\fP"

.PP
Definition at line 20 of file UIElement\&.cs\&.
.SS "\fBCustomEvents\&.UnityEventHand\fP Valve\&.VR\&.InteractionSystem\&.UIElement\&.onHandClick"

.PP
Definition at line 18 of file UIElement\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
