.TH "Valve.VR.SteamVR_TrackedCamera.VideoStreamTexture" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_TrackedCamera.VideoStreamTexture
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVideoStreamTexture\fP (uint \fBdeviceIndex\fP, bool \fBundistorted\fP)"
.br
.ti -1c
.RI "\fBTrackedDevicePose_t\fP \fBGetPose\fP ()"
.br
.ti -1c
.RI "ulong \fBAcquire\fP ()"
.br
.ti -1c
.RI "ulong \fBRelease\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBundistorted\fP\fC [get]\fP"
.br
.ti -1c
.RI "uint \fBdeviceIndex\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBhasCamera\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBhasTracking\fP\fC [get]\fP"
.br
.ti -1c
.RI "uint \fBframeId\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBVRTextureBounds_t\fP \fBframeBounds\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBEVRTrackedCameraFrameType\fP? \fBframeType\fP\fC [get]\fP"
.br
.ti -1c
.RI "Texture2D \fBtexture\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBSteamVR_Utils\&.RigidTransform\fP \fBtransform\fP\fC [get]\fP"
.br
.ti -1c
.RI "Vector3 \fBvelocity\fP\fC [get]\fP"
.br
.ti -1c
.RI "Vector3 \fBangularVelocity\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file SteamVR_TrackedCamera\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.VideoStreamTexture (uint deviceIndex, bool undistorted)"

.PP
Definition at line 32 of file SteamVR_TrackedCamera\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "ulong Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.Acquire ()"

.PP
Definition at line 54 of file SteamVR_TrackedCamera\&.cs\&.
.SS "\fBTrackedDevicePose_t\fP Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.GetPose ()"

.PP
Definition at line 52 of file SteamVR_TrackedCamera\&.cs\&.
.SS "ulong Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.Release ()"

.PP
Definition at line 58 of file SteamVR_TrackedCamera\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Vector3 Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.angularVelocity\fC [get]\fP"

.PP
Definition at line 50 of file SteamVR_TrackedCamera\&.cs\&.
.SS "uint Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.deviceIndex\fC [get]\fP"

.PP
Definition at line 38 of file SteamVR_TrackedCamera\&.cs\&.
.SS "\fBVRTextureBounds_t\fP Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.frameBounds\fC [get]\fP"

.PP
Definition at line 42 of file SteamVR_TrackedCamera\&.cs\&.
.SS "uint Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.frameId\fC [get]\fP"

.PP
Definition at line 41 of file SteamVR_TrackedCamera\&.cs\&.
.SS "\fBEVRTrackedCameraFrameType\fP? Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.frameType\fC [get]\fP"

.PP
Definition at line 43 of file SteamVR_TrackedCamera\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.hasCamera\fC [get]\fP"

.PP
Definition at line 39 of file SteamVR_TrackedCamera\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.hasTracking\fC [get]\fP"

.PP
Definition at line 40 of file SteamVR_TrackedCamera\&.cs\&.
.SS "Texture2D Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.texture\fC [get]\fP"

.PP
Definition at line 46 of file SteamVR_TrackedCamera\&.cs\&.
.SS "\fBSteamVR_Utils\&.RigidTransform\fP Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.transform\fC [get]\fP"

.PP
Definition at line 48 of file SteamVR_TrackedCamera\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.undistorted\fC [get]\fP"

.PP
Definition at line 37 of file SteamVR_TrackedCamera\&.cs\&.
.SS "Vector3 Valve\&.VR\&.SteamVR_TrackedCamera\&.VideoStreamTexture\&.velocity\fC [get]\fP"

.PP
Definition at line 49 of file SteamVR_TrackedCamera\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
