.TH "Valve.VR.SteamVR_Input_BindingFile_Haptic" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Input_BindingFile_Haptic
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBoutput\fP"
.br
.ti -1c
.RI "string \fBpath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 104 of file SteamVR_Input_BindingFile\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Valve\&.VR\&.SteamVR_Input_BindingFile_Haptic\&.Equals (object obj)"

.PP
Definition at line 109 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "override int Valve\&.VR\&.SteamVR_Input_BindingFile_Haptic\&.GetHashCode ()"

.PP
Definition at line 122 of file SteamVR_Input_BindingFile\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string Valve\&.VR\&.SteamVR_Input_BindingFile_Haptic\&.output"

.PP
Definition at line 106 of file SteamVR_Input_BindingFile\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Input_BindingFile_Haptic\&.path"

.PP
Definition at line 107 of file SteamVR_Input_BindingFile\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
