.TH "Valve.VR.InteractionSystem.ModalThrowable" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.ModalThrowable
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.InteractionSystem\&.Throwable\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBgripOffset\fP"
.br
.ti -1c
.RI "Transform \fBpinchOffset\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBHandHoverUpdate\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "override void \fBHandAttachedUpdate\fP (\fBHand\fP hand)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file ModalThrowable\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Valve\&.VR\&.InteractionSystem\&.ModalThrowable\&.HandAttachedUpdate (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBValve\&.VR\&.InteractionSystem\&.Throwable\fP\&.
.PP
Definition at line 43 of file ModalThrowable\&.cs\&.
.SS "override void Valve\&.VR\&.InteractionSystem\&.ModalThrowable\&.HandHoverUpdate (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBValve\&.VR\&.InteractionSystem\&.Throwable\fP\&.
.PP
Definition at line 21 of file ModalThrowable\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform Valve\&.VR\&.InteractionSystem\&.ModalThrowable\&.gripOffset"

.PP
Definition at line 16 of file ModalThrowable\&.cs\&.
.SS "Transform Valve\&.VR\&.InteractionSystem\&.ModalThrowable\&.pinchOffset"

.PP
Definition at line 19 of file ModalThrowable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
