.TH "Valve.VR.SteamVR_Behaviour" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Behaviour
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeSteamVR\fP (bool forceUnityVRToOpenVR=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitialize\fP (bool forceUnityVRToOpenVR=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBinitializeSteamVROnAwake\fP = true"
.br
.ti -1c
.RI "bool \fBdoNotDestroy\fP = true"
.br
.ti -1c
.RI "\fBSteamVR_Render\fP \fBsteamvr_render\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBforcingInitialization\fP = false"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBOnCameraPreCull\fP (\fBCamera\fP cam)"
.br
.ti -1c
.RI "void \fBPreCull\fP ()"
.br
.ti -1c
.RI "void \fBFixedUpdate\fP ()"
.br
.ti -1c
.RI "void \fBLateUpdate\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnQuit\fP (\fBVREvent_t\fP vrEvent)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static int \fBlastFrameCount\fP = \-1"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSteamVR_Behaviour\fP \fBinstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file SteamVR_Behaviour\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR_Behaviour\&.Awake ()\fC [protected]\fP"

.PP
Definition at line 94 of file SteamVR_Behaviour\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Behaviour\&.FixedUpdate ()\fC [protected]\fP"

.PP
Definition at line 212 of file SteamVR_Behaviour\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Behaviour\&.Initialize (bool forceUnityVRToOpenVR = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 45 of file SteamVR_Behaviour\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Behaviour\&.InitializeSteamVR (bool forceUnityVRToOpenVR = \fCfalse\fP)"

.PP
Definition at line 100 of file SteamVR_Behaviour\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Behaviour\&.LateUpdate ()\fC [protected]\fP"

.PP
Definition at line 217 of file SteamVR_Behaviour\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Behaviour\&.OnCameraPreCull (\fBCamera\fP cam)\fC [protected]\fP"

.PP
Definition at line 191 of file SteamVR_Behaviour\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Behaviour\&.OnDisable ()\fC [protected]\fP"

.PP
Definition at line 186 of file SteamVR_Behaviour\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Behaviour\&.OnEnable ()\fC [protected]\fP"

.PP
Definition at line 181 of file SteamVR_Behaviour\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Behaviour\&.OnQuit (\fBVREvent_t\fP vrEvent)\fC [protected]\fP"

.PP
Definition at line 227 of file SteamVR_Behaviour\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Behaviour\&.PreCull ()\fC [protected]\fP"

.PP
Definition at line 201 of file SteamVR_Behaviour\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Behaviour\&.Update ()\fC [protected]\fP"

.PP
Definition at line 222 of file SteamVR_Behaviour\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_Behaviour\&.doNotDestroy = true"

.PP
Definition at line 38 of file SteamVR_Behaviour\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Behaviour\&.forcingInitialization = false\fC [static]\fP"

.PP
Definition at line 20 of file SteamVR_Behaviour\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Behaviour\&.initializeSteamVROnAwake = true"

.PP
Definition at line 36 of file SteamVR_Behaviour\&.cs\&.
.SS "int Valve\&.VR\&.SteamVR_Behaviour\&.lastFrameCount = \-1\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 200 of file SteamVR_Behaviour\&.cs\&.
.SS "\fBSteamVR_Render\fP Valve\&.VR\&.SteamVR_Behaviour\&.steamvr_render"

.PP
Definition at line 41 of file SteamVR_Behaviour\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBSteamVR_Behaviour\fP Valve\&.VR\&.SteamVR_Behaviour\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 24 of file SteamVR_Behaviour\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
