.TH "Valve.VR.InteractionSystem.LinearAudioPitch" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.LinearAudioPitch
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLinearMapping\fP \fBlinearMapping\fP"
.br
.ti -1c
.RI "AnimationCurve \fBpitchCurve\fP"
.br
.ti -1c
.RI "float \fBminPitch\fP"
.br
.ti -1c
.RI "float \fBmaxPitch\fP"
.br
.ti -1c
.RI "bool \fBapplyContinuously\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file LinearAudioPitch\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.LinearAudioPitch\&.applyContinuously = true"

.PP
Definition at line 20 of file LinearAudioPitch\&.cs\&.
.SS "\fBLinearMapping\fP Valve\&.VR\&.InteractionSystem\&.LinearAudioPitch\&.linearMapping"

.PP
Definition at line 16 of file LinearAudioPitch\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.LinearAudioPitch\&.maxPitch"

.PP
Definition at line 19 of file LinearAudioPitch\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.LinearAudioPitch\&.minPitch"

.PP
Definition at line 18 of file LinearAudioPitch\&.cs\&.
.SS "AnimationCurve Valve\&.VR\&.InteractionSystem\&.LinearAudioPitch\&.pitchCurve"

.PP
Definition at line 17 of file LinearAudioPitch\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
