.TH "Valve.VR.InteractionSystem.SoundBowClick" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.SoundBowClick
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPlayBowTensionClicks\fP (float normalizedTension)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AudioClip \fBbowClick\fP"
.br
.ti -1c
.RI "AnimationCurve \fBpitchTensionCurve\fP"
.br
.ti -1c
.RI "float \fBminPitch\fP"
.br
.ti -1c
.RI "float \fBmaxPitch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file SoundBowClick\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.InteractionSystem\&.SoundBowClick\&.PlayBowTensionClicks (float normalizedTension)"

.PP
Definition at line 30 of file SoundBowClick\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "AudioClip Valve\&.VR\&.InteractionSystem\&.SoundBowClick\&.bowClick"

.PP
Definition at line 15 of file SoundBowClick\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.SoundBowClick\&.maxPitch"

.PP
Definition at line 18 of file SoundBowClick\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.SoundBowClick\&.minPitch"

.PP
Definition at line 17 of file SoundBowClick\&.cs\&.
.SS "AnimationCurve Valve\&.VR\&.InteractionSystem\&.SoundBowClick\&.pitchTensionCurve"

.PP
Definition at line 16 of file SoundBowClick\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
