.TH "Valve.VR.InteractionSystem.Interactable" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Interactable
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBOnAttachedToHandDelegate\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "delegate void \fBOnDetachedFromHandDelegate\fP (\fBHand\fP hand)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_ActionSet\fP \fBactivateActionSetOnAttach\fP"
.br
.ti -1c
.RI "bool \fBhideHandOnAttach\fP = true"
.br
.ti -1c
.RI "bool \fBhideSkeletonOnAttach\fP = false"
.br
.ti -1c
.RI "bool \fBhideControllerOnAttach\fP = false"
.br
.ti -1c
.RI "int \fBhandAnimationOnPickup\fP = 0"
.br
.ti -1c
.RI "\fBSkeletalMotionRangeChange\fP \fBsetRangeOfMotionOnPickup\fP = \fBSkeletalMotionRangeChange\&.None\fP"
.br
.ti -1c
.RI "bool \fBuseHandObjectAttachmentPoint\fP = true"
.br
.ti -1c
.RI "bool \fBattachEaseIn\fP = false"
.br
.ti -1c
.RI "AnimationCurve \fBsnapAttachEaseInCurve\fP = AnimationCurve\&.EaseInOut(0\&.0f, 0\&.0f, 1\&.0f, 1\&.0f)"
.br
.ti -1c
.RI "float \fBsnapAttachEaseInTime\fP = 0\&.15f"
.br
.ti -1c
.RI "bool \fBsnapAttachEaseInCompleted\fP = false"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_Poser\fP \fBskeletonPoser\fP"
.br
.ti -1c
.RI "bool \fBhandFollowTransform\fP = true"
.br
.ti -1c
.RI "bool \fBhighlightOnHover\fP = true"
.br
.ti -1c
.RI "GameObject [] \fBhideHighlight\fP"
.br
.ti -1c
.RI "\fBHand\fP \fBattachedToHand\fP"
.br
.ti -1c
.RI "\fBHand\fP \fBhoveringHand\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBStart\fP ()"
.br
.ti -1c
.RI "virtual bool \fBShouldIgnoreHighlight\fP (Component component)"
.br
.ti -1c
.RI "virtual bool \fBShouldIgnore\fP (GameObject check)"
.br
.ti -1c
.RI "virtual void \fBCreateHighlightRenderers\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdateHighlightRenderers\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnHandHoverBegin\fP (\fBHand\fP hand)"
.br
.RI "Called when a \fBHand\fP starts hovering over this object "
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnAttachedToHand\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "virtual void \fBOnDetachedFromHand\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "virtual void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDisable\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "MeshRenderer [] \fBhighlightRenderers\fP"
.br
.ti -1c
.RI "MeshRenderer [] \fBexistingRenderers\fP"
.br
.ti -1c
.RI "GameObject \fBhighlightHolder\fP"
.br
.ti -1c
.RI "SkinnedMeshRenderer [] \fBhighlightSkinnedRenderers\fP"
.br
.ti -1c
.RI "SkinnedMeshRenderer [] \fBexistingSkinnedRenderers\fP"
.br
.ti -1c
.RI "float \fBblendToPoseTime\fP = 0\&.1f"
.br
.ti -1c
.RI "float \fBreleasePoseBlendTime\fP = 0\&.2f"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static Material \fBhighlightMat\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBisDestroying\fP\fC [get, protected set]\fP"
.br
.ti -1c
.RI "bool \fBisHovering\fP\fC [get, protected set]\fP"
.br
.ti -1c
.RI "bool \fBwasHovering\fP\fC [get, protected set]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "\fBOnAttachedToHandDelegate\fP \fBonAttachedToHand\fP"
.br
.ti -1c
.RI "\fBOnDetachedFromHandDelegate\fP \fBonDetachedFromHand\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Interactable\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Interactable\&.CreateHighlightRenderers ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 122 of file Interactable\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Interactable\&.OnAttachedToHand (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 274 of file Interactable\&.cs\&.
.SS "delegate void Valve\&.VR\&.InteractionSystem\&.Interactable\&.OnAttachedToHandDelegate (\fBHand\fP hand)"

.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Interactable\&.OnDestroy ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 319 of file Interactable\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Interactable\&.OnDetachedFromHand (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 292 of file Interactable\&.cs\&.
.SS "delegate void Valve\&.VR\&.InteractionSystem\&.Interactable\&.OnDetachedFromHandDelegate (\fBHand\fP hand)"

.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Interactable\&.OnDisable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 335 of file Interactable\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Interactable\&.OnHandHoverBegin (\fBHand\fP hand)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Called when a \fBHand\fP starts hovering over this object 
.PP
Definition at line 232 of file Interactable\&.cs\&.
.SS "virtual bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.ShouldIgnore (GameObject check)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 111 of file Interactable\&.cs\&.
.SS "virtual bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.ShouldIgnoreHighlight (Component component)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 106 of file Interactable\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Interactable\&.Start ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 89 of file Interactable\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Interactable\&.Update ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 259 of file Interactable\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.Interactable\&.UpdateHighlightRenderers ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 183 of file Interactable\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSteamVR_ActionSet\fP Valve\&.VR\&.InteractionSystem\&.Interactable\&.activateActionSetOnAttach"

.PP
Definition at line 18 of file Interactable\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.attachEaseIn = false"

.PP
Definition at line 45 of file Interactable\&.cs\&.
.SS "\fBHand\fP Valve\&.VR\&.InteractionSystem\&.Interactable\&.attachedToHand"

.PP
Definition at line 74 of file Interactable\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Interactable\&.blendToPoseTime = 0\&.1f\fC [protected]\fP"

.PP
Definition at line 271 of file Interactable\&.cs\&.
.SS "MeshRenderer [] Valve\&.VR\&.InteractionSystem\&.Interactable\&.existingRenderers\fC [protected]\fP"

.PP
Definition at line 64 of file Interactable\&.cs\&.
.SS "SkinnedMeshRenderer [] Valve\&.VR\&.InteractionSystem\&.Interactable\&.existingSkinnedRenderers\fC [protected]\fP"

.PP
Definition at line 67 of file Interactable\&.cs\&.
.SS "int Valve\&.VR\&.InteractionSystem\&.Interactable\&.handAnimationOnPickup = 0"

.PP
Definition at line 30 of file Interactable\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.handFollowTransform = true"

.PP
Definition at line 58 of file Interactable\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.hideControllerOnAttach = false"

.PP
Definition at line 27 of file Interactable\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.hideHandOnAttach = true"

.PP
Definition at line 21 of file Interactable\&.cs\&.
.SS "GameObject [] Valve\&.VR\&.InteractionSystem\&.Interactable\&.hideHighlight"

.PP
Definition at line 70 of file Interactable\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.hideSkeletonOnAttach = false"

.PP
Definition at line 24 of file Interactable\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.Interactable\&.highlightHolder\fC [protected]\fP"

.PP
Definition at line 65 of file Interactable\&.cs\&.
.SS "Material Valve\&.VR\&.InteractionSystem\&.Interactable\&.highlightMat\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 68 of file Interactable\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.highlightOnHover = true"

.PP
Definition at line 62 of file Interactable\&.cs\&.
.SS "MeshRenderer [] Valve\&.VR\&.InteractionSystem\&.Interactable\&.highlightRenderers\fC [protected]\fP"

.PP
Definition at line 63 of file Interactable\&.cs\&.
.SS "SkinnedMeshRenderer [] Valve\&.VR\&.InteractionSystem\&.Interactable\&.highlightSkinnedRenderers\fC [protected]\fP"

.PP
Definition at line 66 of file Interactable\&.cs\&.
.SS "\fBHand\fP Valve\&.VR\&.InteractionSystem\&.Interactable\&.hoveringHand"

.PP
Definition at line 77 of file Interactable\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Interactable\&.releasePoseBlendTime = 0\&.2f\fC [protected]\fP"

.PP
Definition at line 272 of file Interactable\&.cs\&.
.SS "\fBSkeletalMotionRangeChange\fP Valve\&.VR\&.InteractionSystem\&.Interactable\&.setRangeOfMotionOnPickup = \fBSkeletalMotionRangeChange\&.None\fP"

.PP
Definition at line 33 of file Interactable\&.cs\&.
.SS "\fBSteamVR_Skeleton_Poser\fP Valve\&.VR\&.InteractionSystem\&.Interactable\&.skeletonPoser"

.PP
Definition at line 55 of file Interactable\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.snapAttachEaseInCompleted = false"

.PP
Definition at line 50 of file Interactable\&.cs\&.
.SS "AnimationCurve Valve\&.VR\&.InteractionSystem\&.Interactable\&.snapAttachEaseInCurve = AnimationCurve\&.EaseInOut(0\&.0f, 0\&.0f, 1\&.0f, 1\&.0f)"

.PP
Definition at line 47 of file Interactable\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Interactable\&.snapAttachEaseInTime = 0\&.15f"

.PP
Definition at line 48 of file Interactable\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.useHandObjectAttachmentPoint = true"

.PP
Definition at line 43 of file Interactable\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.isDestroying\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line 79 of file Interactable\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.isHovering\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line 80 of file Interactable\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.Interactable\&.wasHovering\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line 81 of file Interactable\&.cs\&.
.SH "Event Documentation"
.PP 
.SS "\fBOnAttachedToHandDelegate\fP Valve\&.VR\&.InteractionSystem\&.Interactable\&.onAttachedToHand"

.PP
Definition at line 38 of file Interactable\&.cs\&.
.SS "\fBOnDetachedFromHandDelegate\fP Valve\&.VR\&.InteractionSystem\&.Interactable\&.onDetachedFromHand"

.PP
Definition at line 39 of file Interactable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
