.TH "Valve.VR.SteamVR_Action_Boolean" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Action_Boolean \- Boolean actions are either true or false\&. There are a variety of helper events included that will fire for the given input source\&. They're prefixed with 'on'\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_Action_In< SteamVR_Action_Boolean_Source_Map, SteamVR_Action_Boolean_Source >\fP, \fBValve\&.VR\&.ISteamVR_Action_Boolean\fP, and ISerializationCallbackReceiver\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBStateDownHandler\fP (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource)"
.br
.ti -1c
.RI "delegate void \fBStateUpHandler\fP (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource)"
.br
.ti -1c
.RI "delegate void \fBStateHandler\fP (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource)"
.br
.ti -1c
.RI "delegate void \fBActiveChangeHandler\fP (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool \fBactive\fP)"
.br
.ti -1c
.RI "delegate void \fBChangeHandler\fP (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool newState)"
.br
.ti -1c
.RI "delegate void \fBUpdateHandler\fP (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool newState)"
.br
.ti -1c
.RI "\fBSteamVR_Action_Boolean\fP ()"
.br
.ti -1c
.RI "bool \fBGetStateDown\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Returns true if the value of the action has been changed to true (from false) in the most recent update\&. "
.ti -1c
.RI "bool \fBGetStateUp\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Returns true if the value of the action has been changed to false (from true) in the most recent update\&. "
.ti -1c
.RI "bool \fBGetState\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Returns true if the value of the action (state) is currently true "
.ti -1c
.RI "bool \fBGetLastStateDown\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "[For the previous update] Returns true if the value of the action has been set to true (from false)\&. "
.ti -1c
.RI "bool \fBGetLastStateUp\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "[For the previous update] Returns true if the value of the action has been set to false (from true)\&. "
.ti -1c
.RI "bool \fBGetLastState\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "[For the previous update] Returns true if the value of the action was true\&. "
.ti -1c
.RI "void \fBAddOnActiveChangeListener\fP (\fBActiveChangeHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Executes a function when the \fIfunctional\fP active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound, or when the ActionSet changes state\&. "
.ti -1c
.RI "void \fBRemoveOnActiveChangeListener\fP (\fBActiveChangeHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Stops executing a function when the \fIfunctional\fP active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound, or when the ActionSet changes state\&. "
.ti -1c
.RI "void \fBAddOnActiveBindingChangeListener\fP (\fBActiveChangeHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Executes a function when the active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound "
.ti -1c
.RI "void \fBRemoveOnActiveBindingChangeListener\fP (\fBActiveChangeHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.ti -1c
.RI "void \fBAddOnChangeListener\fP (\fBChangeHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Executes a function when the state of this action (with the specified inputSource) changes "
.ti -1c
.RI "void \fBRemoveOnChangeListener\fP (\fBChangeHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.ti -1c
.RI "void \fBAddOnUpdateListener\fP (\fBUpdateHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Executes a function when the state of this action (with the specified inputSource) is updated\&. "
.ti -1c
.RI "void \fBRemoveOnUpdateListener\fP (\fBUpdateHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.ti -1c
.RI "void \fBAddOnStateDownListener\fP (\fBStateDownHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Executes a function when the state of this action (with the specified inputSource) changes to true (from false)\&. "
.ti -1c
.RI "void \fBRemoveOnStateDownListener\fP (\fBStateDownHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.ti -1c
.RI "void \fBAddOnStateUpListener\fP (\fBStateUpHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Executes a function when the state of this action (with the specified inputSource) changes to false (from true)\&. "
.ti -1c
.RI "void \fBRemoveOnStateUpListener\fP (\fBStateUpHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBChangeHandler\fP \fBonChange\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever a state changes from false to true or true to false "
.ti -1c
.RI "\fBUpdateHandler\fP \fBonUpdate\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever the action is updated "
.ti -1c
.RI "\fBStateHandler\fP \fBonState\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever the boolean action is true and gets updated "
.ti -1c
.RI "\fBStateDownHandler\fP \fBonStateDown\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever the state of the boolean action has changed from false to true in the most recent update "
.ti -1c
.RI "\fBStateUpHandler\fP \fBonStateUp\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever the state of the boolean action has changed from true to false in the most recent update "
.ti -1c
.RI "\fBActiveChangeHandler\fP \fBonActiveChange\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the active state (ActionSet active and binding active) changes "
.ti -1c
.RI "\fBActiveChangeHandler\fP \fBonActiveBindingChange\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the bound state of the binding changes "
.ti -1c
.RI "bool \fBstate\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True when the boolean action is true "
.ti -1c
.RI "bool \fBstateDown\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True when the boolean action is true and the last state was false "
.ti -1c
.RI "bool \fBstateUp\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True when the boolean action is false and the last state was true "
.ti -1c
.RI "bool \fBlastState\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP (previous update) True when the boolean action is true "
.ti -1c
.RI "bool \fBlastStateDown\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP (previous update) True when the boolean action is true and the last state was false "
.ti -1c
.RI "bool \fBlastStateUp\fP\fC [get]\fP"
.br
.RI "\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP (previous update) True when the boolean action is false and the last state was true "
.in -1c
.SH "Detailed Description"
.PP 
Boolean actions are either true or false\&. There are a variety of helper events included that will fire for the given input source\&. They're prefixed with 'on'\&. 


.PP
Definition at line 16 of file SteamVR_Action_Boolean\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.SteamVR_Action_Boolean\&.SteamVR_Action_Boolean ()"

.PP
Definition at line 74 of file SteamVR_Action_Boolean\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "delegate void Valve\&.VR\&.SteamVR_Action_Boolean\&.ActiveChangeHandler (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool active)"

.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.AddOnActiveBindingChangeListener (\fBActiveChangeHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Executes a function when the active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToCall\fP A local function that receives the boolean action who's active state changes and the corresponding input source
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 139 of file SteamVR_Action_Boolean\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.AddOnActiveChangeListener (\fBActiveChangeHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Executes a function when the \fIfunctional\fP active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound, or when the ActionSet changes state\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToCall\fP A local function that receives the boolean action who's active state changes and the corresponding input source
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 122 of file SteamVR_Action_Boolean\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.AddOnChangeListener (\fBChangeHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Executes a function when the state of this action (with the specified inputSource) changes 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToCall\fP A local function that receives the boolean action who's state has changed, the corresponding input source, and the new value
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 155 of file SteamVR_Action_Boolean\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.AddOnStateDownListener (\fBStateDownHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Executes a function when the state of this action (with the specified inputSource) changes to true (from false)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToCall\fP A local function that receives the boolean action who's state has changed, the corresponding input source, and the new value
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 187 of file SteamVR_Action_Boolean\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.AddOnStateUpListener (\fBStateUpHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Executes a function when the state of this action (with the specified inputSource) changes to false (from true)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToCall\fP A local function that receives the boolean action who's state has changed, the corresponding input source, and the new value
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 203 of file SteamVR_Action_Boolean\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.AddOnUpdateListener (\fBUpdateHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Executes a function when the state of this action (with the specified inputSource) is updated\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToCall\fP A local function that receives the boolean action who's state has changed, the corresponding input source, and the new value
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 171 of file SteamVR_Action_Boolean\&.cs\&.
.SS "delegate void Valve\&.VR\&.SteamVR_Action_Boolean\&.ChangeHandler (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool newState)"

.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.GetLastState (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
[For the previous update] Returns true if the value of the action was true\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 113 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.GetLastStateDown (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
[For the previous update] Returns true if the value of the action has been set to true (from false)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 99 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.GetLastStateUp (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
[For the previous update] Returns true if the value of the action has been set to false (from true)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 106 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.GetState (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
Returns true if the value of the action (state) is currently true 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 92 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.GetStateDown (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
Returns true if the value of the action has been changed to true (from false) in the most recent update\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 78 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.GetStateUp (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
Returns true if the value of the action has been changed to false (from true) in the most recent update\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 85 of file SteamVR_Action_Boolean\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.RemoveOnActiveBindingChangeListener (\fBActiveChangeHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive update events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 147 of file SteamVR_Action_Boolean\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.RemoveOnActiveChangeListener (\fBActiveChangeHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Stops executing a function when the \fIfunctional\fP active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound, or when the ActionSet changes state\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive update events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 131 of file SteamVR_Action_Boolean\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.RemoveOnChangeListener (\fBChangeHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive on change events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 163 of file SteamVR_Action_Boolean\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.RemoveOnStateDownListener (\fBStateDownHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive update events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 195 of file SteamVR_Action_Boolean\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.RemoveOnStateUpListener (\fBStateUpHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 211 of file SteamVR_Action_Boolean\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Boolean\&.RemoveOnUpdateListener (\fBUpdateHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive update events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 179 of file SteamVR_Action_Boolean\&.cs\&.
.SS "delegate void Valve\&.VR\&.SteamVR_Action_Boolean\&.StateDownHandler (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource)"

.SS "delegate void Valve\&.VR\&.SteamVR_Action_Boolean\&.StateHandler (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource)"

.SS "delegate void Valve\&.VR\&.SteamVR_Action_Boolean\&.StateUpHandler (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource)"

.SS "delegate void Valve\&.VR\&.SteamVR_Action_Boolean\&.UpdateHandler (\fBSteamVR_Action_Boolean\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool newState)"

.SH "Property Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.lastState\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP (previous update) True when the boolean action is true 
.PP
Definition at line 65 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.lastStateDown\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP (previous update) True when the boolean action is true and the last state was false 
.PP
Definition at line 68 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.lastStateUp\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP (previous update) True when the boolean action is false and the last state was true 
.PP
Definition at line 71 of file SteamVR_Action_Boolean\&.cs\&.
.SS "\fBActiveChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Boolean\&.onActiveBindingChange\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the bound state of the binding changes 
.PP
Definition at line 51 of file SteamVR_Action_Boolean\&.cs\&.
.SS "\fBActiveChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Boolean\&.onActiveChange\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP Event fires when the active state (ActionSet active and binding active) changes 
.PP
Definition at line 47 of file SteamVR_Action_Boolean\&.cs\&.
.SS "\fBChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Boolean\&.onChange\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever a state changes from false to true or true to false 
.PP
Definition at line 27 of file SteamVR_Action_Boolean\&.cs\&.
.SS "\fBStateHandler\fP Valve\&.VR\&.SteamVR_Action_Boolean\&.onState\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever the boolean action is true and gets updated 
.PP
Definition at line 35 of file SteamVR_Action_Boolean\&.cs\&.
.SS "\fBStateDownHandler\fP Valve\&.VR\&.SteamVR_Action_Boolean\&.onStateDown\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever the state of the boolean action has changed from false to true in the most recent update 
.PP
Definition at line 39 of file SteamVR_Action_Boolean\&.cs\&.
.SS "\fBStateUpHandler\fP Valve\&.VR\&.SteamVR_Action_Boolean\&.onStateUp\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever the state of the boolean action has changed from true to false in the most recent update 
.PP
Definition at line 43 of file SteamVR_Action_Boolean\&.cs\&.
.SS "\fBUpdateHandler\fP Valve\&.VR\&.SteamVR_Action_Boolean\&.onUpdate\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever the action is updated 
.PP
Definition at line 31 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.state\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True when the boolean action is true 
.PP
Definition at line 55 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.stateDown\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True when the boolean action is true and the last state was false 
.PP
Definition at line 58 of file SteamVR_Action_Boolean\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Action_Boolean\&.stateUp\fC [get]\fP"

.PP
\fB[Shortcut to: \fBSteamVR_Input_Sources\&.Any\fP]\fP True when the boolean action is false and the last state was true 
.PP
Definition at line 61 of file SteamVR_Action_Boolean\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
