.TH "Valve.VR.VREvent_Reserved_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VREvent_Reserved_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ulong \fBreserved0\fP"
.br
.ti -1c
.RI "ulong \fBreserved1\fP"
.br
.ti -1c
.RI "ulong \fBreserved2\fP"
.br
.ti -1c
.RI "ulong \fBreserved3\fP"
.br
.ti -1c
.RI "ulong \fBreserved4\fP"
.br
.ti -1c
.RI "ulong \fBreserved5\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5122 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "ulong Valve\&.VR\&.VREvent_Reserved_t\&.reserved0"

.PP
Definition at line 5124 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VREvent_Reserved_t\&.reserved1"

.PP
Definition at line 5125 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VREvent_Reserved_t\&.reserved2"

.PP
Definition at line 5126 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VREvent_Reserved_t\&.reserved3"

.PP
Definition at line 5127 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VREvent_Reserved_t\&.reserved4"

.PP
Definition at line 5128 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.VREvent_Reserved_t\&.reserved5"

.PP
Definition at line 5129 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
