.TH "Valve.VR.SteamVR_Utils.RigidTransform" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Utils.RigidTransform
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRigidTransform\fP (Vector3 position, Quaternion rotation)"
.br
.ti -1c
.RI "\fBRigidTransform\fP (Transform fromTransform)"
.br
.ti -1c
.RI "\fBRigidTransform\fP (Transform from, Transform to)"
.br
.ti -1c
.RI "\fBRigidTransform\fP (\fBHmdMatrix34_t\fP pose)"
.br
.ti -1c
.RI "\fBRigidTransform\fP (\fBHmdMatrix44_t\fP pose)"
.br
.ti -1c
.RI "\fBHmdMatrix44_t\fP \fBToHmdMatrix44\fP ()"
.br
.ti -1c
.RI "\fBHmdMatrix34_t\fP \fBToHmdMatrix34\fP ()"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object other)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.ti -1c
.RI "void \fBInverse\fP ()"
.br
.ti -1c
.RI "\fBRigidTransform\fP \fBGetInverse\fP ()"
.br
.ti -1c
.RI "void \fBMultiply\fP (\fBRigidTransform\fP a, \fBRigidTransform\fP b)"
.br
.ti -1c
.RI "Vector3 \fBInverseTransformPoint\fP (Vector3 point)"
.br
.ti -1c
.RI "Vector3 \fBTransformPoint\fP (Vector3 point)"
.br
.ti -1c
.RI "void \fBInterpolate\fP (\fBRigidTransform\fP to, float t)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRigidTransform\fP \fBFromLocal\fP (Transform fromTransform)"
.br
.ti -1c
.RI "static bool \fBoperator==\fP (\fBRigidTransform\fP a, \fBRigidTransform\fP b)"
.br
.ti -1c
.RI "static bool \fBoperator !=\fP (\fBRigidTransform\fP a, \fBRigidTransform\fP b)"
.br
.ti -1c
.RI "static \fBRigidTransform\fP \fBoperator *\fP (\fBRigidTransform\fP a, \fBRigidTransform\fP b)"
.br
.ti -1c
.RI "static Vector3 \fBoperator *\fP (\fBRigidTransform\fP t, Vector3 v)"
.br
.ti -1c
.RI "static \fBRigidTransform\fP \fBInterpolate\fP (\fBRigidTransform\fP a, \fBRigidTransform\fP b, float t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBpos\fP"
.br
.ti -1c
.RI "Quaternion \fBrot\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBRigidTransform\fP \fBidentity\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 164 of file SteamVR_Utils\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.RigidTransform (Vector3 position, Quaternion rotation)"

.PP
Definition at line 179 of file SteamVR_Utils\&.cs\&.
.SS "Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.RigidTransform (Transform fromTransform)"

.PP
Definition at line 185 of file SteamVR_Utils\&.cs\&.
.SS "Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.RigidTransform (Transform from, Transform to)"

.PP
Definition at line 191 of file SteamVR_Utils\&.cs\&.
.SS "Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.RigidTransform (\fBHmdMatrix34_t\fP pose)"

.PP
Definition at line 198 of file SteamVR_Utils\&.cs\&.
.SS "Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.RigidTransform (\fBHmdMatrix44_t\fP pose)"

.PP
Definition at line 221 of file SteamVR_Utils\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.Equals (object other)"

.PP
Definition at line 300 of file SteamVR_Utils\&.cs\&.
.SS "static \fBRigidTransform\fP Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.FromLocal (Transform fromTransform)\fC [static]\fP"

.PP
Definition at line 174 of file SteamVR_Utils\&.cs\&.
.SS "override int Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.GetHashCode ()"

.PP
Definition at line 310 of file SteamVR_Utils\&.cs\&.
.SS "\fBRigidTransform\fP Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.GetInverse ()"

.PP
Definition at line 340 of file SteamVR_Utils\&.cs\&.
.SS "static \fBRigidTransform\fP Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.Interpolate (\fBRigidTransform\fP a, \fBRigidTransform\fP b, float t)\fC [static]\fP"

.PP
Definition at line 368 of file SteamVR_Utils\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.Interpolate (\fBRigidTransform\fP to, float t)"

.PP
Definition at line 373 of file SteamVR_Utils\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.Inverse ()"

.PP
Definition at line 334 of file SteamVR_Utils\&.cs\&.
.SS "Vector3 Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.InverseTransformPoint (Vector3 point)"

.PP
Definition at line 353 of file SteamVR_Utils\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.Multiply (\fBRigidTransform\fP a, \fBRigidTransform\fP b)"

.PP
Definition at line 347 of file SteamVR_Utils\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.operator != (\fBRigidTransform\fP a, \fBRigidTransform\fP b)\fC [static]\fP"

.PP
Definition at line 320 of file SteamVR_Utils\&.cs\&.
.SS "static \fBRigidTransform\fP Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.operator * (\fBRigidTransform\fP a, \fBRigidTransform\fP b)\fC [static]\fP"

.PP
Definition at line 325 of file SteamVR_Utils\&.cs\&.
.SS "static Vector3 Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.operator * (\fBRigidTransform\fP t, Vector3 v)\fC [static]\fP"

.PP
Definition at line 363 of file SteamVR_Utils\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.operator== (\fBRigidTransform\fP a, \fBRigidTransform\fP b)\fC [static]\fP"

.PP
Definition at line 315 of file SteamVR_Utils\&.cs\&.
.SS "\fBHmdMatrix34_t\fP Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.ToHmdMatrix34 ()"

.PP
Definition at line 277 of file SteamVR_Utils\&.cs\&.
.SS "\fBHmdMatrix44_t\fP Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.ToHmdMatrix44 ()"

.PP
Definition at line 249 of file SteamVR_Utils\&.cs\&.
.SS "Vector3 Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.TransformPoint (Vector3 point)"

.PP
Definition at line 358 of file SteamVR_Utils\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.pos"

.PP
Definition at line 166 of file SteamVR_Utils\&.cs\&.
.SS "Quaternion Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.rot"

.PP
Definition at line 167 of file SteamVR_Utils\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBRigidTransform\fP Valve\&.VR\&.SteamVR_Utils\&.RigidTransform\&.identity\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 170 of file SteamVR_Utils\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
