.TH "Valve.VR.InteractionSystem.ItemPackageSpawner" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.ItemPackageSpawner
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBItemPackage\fP \fB_itemPackage\fP"
.br
.ti -1c
.RI "bool \fBrequireGrabActionToTake\fP = false"
.br
.ti -1c
.RI "bool \fBrequireReleaseActionToReturn\fP = false"
.br
.ti -1c
.RI "bool \fBshowTriggerHint\fP = false"
.br
.ti -1c
.RI "\fBHand\&.AttachmentFlags\fP \fBattachmentFlags\fP = \fBHand\&.defaultAttachmentFlags\fP"
.br
.ti -1c
.RI "bool \fBtakeBackItem\fP = false"
.br
.ti -1c
.RI "bool \fBacceptDifferentItems\fP = false"
.br
.ti -1c
.RI "UnityEvent \fBpickupEvent\fP"
.br
.ti -1c
.RI "UnityEvent \fBdropEvent\fP"
.br
.ti -1c
.RI "bool \fBjustPickedUpItem\fP = false"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBItemPackage\fP \fBitemPackage\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file ItemPackageSpawner\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBItemPackage\fP Valve\&.VR\&.InteractionSystem\&.ItemPackageSpawner\&._itemPackage"

.PP
Definition at line 34 of file ItemPackageSpawner\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.ItemPackageSpawner\&.acceptDifferentItems = false"

.PP
Definition at line 49 of file ItemPackageSpawner\&.cs\&.
.SS "\fBHand\&.AttachmentFlags\fP Valve\&.VR\&.InteractionSystem\&.ItemPackageSpawner\&.attachmentFlags = \fBHand\&.defaultAttachmentFlags\fP"

.PP
Definition at line 45 of file ItemPackageSpawner\&.cs\&.
.SS "UnityEvent Valve\&.VR\&.InteractionSystem\&.ItemPackageSpawner\&.dropEvent"

.PP
Definition at line 55 of file ItemPackageSpawner\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.ItemPackageSpawner\&.justPickedUpItem = false"

.PP
Definition at line 57 of file ItemPackageSpawner\&.cs\&.
.SS "UnityEvent Valve\&.VR\&.InteractionSystem\&.ItemPackageSpawner\&.pickupEvent"

.PP
Definition at line 54 of file ItemPackageSpawner\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.ItemPackageSpawner\&.requireGrabActionToTake = false"

.PP
Definition at line 40 of file ItemPackageSpawner\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.ItemPackageSpawner\&.requireReleaseActionToReturn = false"

.PP
Definition at line 41 of file ItemPackageSpawner\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.ItemPackageSpawner\&.showTriggerHint = false"

.PP
Definition at line 42 of file ItemPackageSpawner\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.ItemPackageSpawner\&.takeBackItem = false"

.PP
Definition at line 47 of file ItemPackageSpawner\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBItemPackage\fP Valve\&.VR\&.InteractionSystem\&.ItemPackageSpawner\&.itemPackage\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 23 of file ItemPackageSpawner\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
