.TH "Valve.VR.SteamVR_Behaviour_Pose_TrackingChangedEvent" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Behaviour_Pose_TrackingChangedEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEvent< SteamVR_Behaviour_Pose, SteamVR_Input_Sources, ETrackingResult >\&.
.SH "Detailed Description"
.PP 
Definition at line 9 of file SteamVR_Behaviour_Pose_TrackingChangedEvent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
