.TH "Valve.VR.CVRChaperone" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.CVRChaperone
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChaperoneCalibrationState\fP \fBGetCalibrationState\fP ()"
.br
.ti -1c
.RI "bool \fBGetPlayAreaSize\fP (ref float pSizeX, ref float pSizeZ)"
.br
.ti -1c
.RI "bool \fBGetPlayAreaRect\fP (ref \fBHmdQuad_t\fP rect)"
.br
.ti -1c
.RI "void \fBReloadInfo\fP ()"
.br
.ti -1c
.RI "void \fBSetSceneColor\fP (\fBHmdColor_t\fP color)"
.br
.ti -1c
.RI "void \fBGetBoundsColor\fP (ref \fBHmdColor_t\fP pOutputColorArray, int nNumOutputColors, float flCollisionBoundsFadeDistance, ref \fBHmdColor_t\fP pOutputCameraColor)"
.br
.ti -1c
.RI "bool \fBAreBoundsVisible\fP ()"
.br
.ti -1c
.RI "void \fBForceBoundsVisible\fP (bool bForce)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2324 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Valve\&.VR\&.CVRChaperone\&.AreBoundsVisible ()"

.PP
Definition at line 2360 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperone\&.ForceBoundsVisible (bool bForce)"

.PP
Definition at line 2365 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperone\&.GetBoundsColor (ref \fBHmdColor_t\fP pOutputColorArray, int nNumOutputColors, float flCollisionBoundsFadeDistance, ref \fBHmdColor_t\fP pOutputCameraColor)"

.PP
Definition at line 2356 of file openvr_api\&.cs\&.
.SS "\fBChaperoneCalibrationState\fP Valve\&.VR\&.CVRChaperone\&.GetCalibrationState ()"

.PP
Definition at line 2331 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRChaperone\&.GetPlayAreaRect (ref \fBHmdQuad_t\fP rect)"

.PP
Definition at line 2343 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVRChaperone\&.GetPlayAreaSize (ref float pSizeX, ref float pSizeZ)"

.PP
Definition at line 2336 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperone\&.ReloadInfo ()"

.PP
Definition at line 2348 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVRChaperone\&.SetSceneColor (\fBHmdColor_t\fP color)"

.PP
Definition at line 2352 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
