.TH "Valve.VR.SteamVR" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR
.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBInitializedStates\fP { \fBInitializedStates\&.None\fP, \fBInitializedStates\&.Initializing\fP, \fBInitializedStates\&.InitializeSuccess\fP, \fBInitializedStates\&.InitializeFailure\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetTrackedDeviceString\fP (uint deviceId)"
.br
.ti -1c
.RI "string \fBGetStringProperty\fP (\fBETrackedDeviceProperty\fP prop, uint deviceId=\fBOpenVR\&.k_unTrackedDeviceIndex_Hmd\fP)"
.br
.ti -1c
.RI "float \fBGetFloatProperty\fP (\fBETrackedDeviceProperty\fP prop, uint deviceId=\fBOpenVR\&.k_unTrackedDeviceIndex_Hmd\fP)"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitialize\fP (bool forceUnityVRMode=false)"
.br
.ti -1c
.RI "static bool \fBInitializeTemporarySession\fP (bool initInput=false)"
.br
.ti -1c
.RI "static void \fBExitTemporarySession\fP ()"
.br
.ti -1c
.RI "static string \fBGenerateAppKey\fP ()"
.br
.ti -1c
.RI "static string \fBGenerateCleanProductName\fP ()"
.br
.ti -1c
.RI "static void \fBSafeDispose\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBETextureType\fP \fBtextureType\fP"
.br
.ti -1c
.RI "const string \fBdefaultUnityAppKeyTemplate\fP = 'application\&.generated\&.unity\&.{0}\&.exe'"
.br
.ti -1c
.RI "const string \fBdefaultAppKeyTemplate\fP = 'application\&.generated\&.{0}'"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBInitializedStates\fP \fBinitializedState\fP = \fBInitializedStates\&.None\fP"
.br
.ti -1c
.RI "static bool [] \fBconnected\fP = new bool[\fBOpenVR\&.k_unMaxTrackedDeviceCount\fP]"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBactive\fP\fC [get]\fP"
.br
.ti -1c
.RI "static bool \fBenabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "static \fBSteamVR\fP \fBinstance\fP\fC [get]\fP"
.br
.ti -1c
.RI "static bool \fBusingNativeSupport\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBSteamVR_Settings\fP \fBsettings\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBCVRSystem\fP \fBhmd\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBCVRCompositor\fP \fBcompositor\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBCVROverlay\fP \fBoverlay\fP\fC [get]\fP"
.br
.ti -1c
.RI "static bool \fBinitializing\fP\fC [get]\fP"
.br
.ti -1c
.RI "static bool \fBcalibrating\fP\fC [get]\fP"
.br
.ti -1c
.RI "static bool \fBoutOfRange\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBsceneWidth\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBsceneHeight\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBaspect\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBfieldOfView\fP\fC [get]\fP"
.br
.ti -1c
.RI "Vector2 \fBtanHalfFov\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBVRTextureBounds_t\fP [] \fBtextureBounds\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBSteamVR_Utils\&.RigidTransform\fP [] \fBeyes\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBhmd_TrackingSystemName\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBhmd_ModelNumber\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBhmd_SerialNumber\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBhmd_SecondsFromVsyncToPhotons\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBhmd_DisplayFrequency\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file SteamVR\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.SteamVR\&.InitializedStates\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIInitializing \fP\fP
.TP
\fB\fIInitializeSuccess \fP\fP
.TP
\fB\fIInitializeFailure \fP\fP
.PP
Definition at line 77 of file SteamVR\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Valve\&.VR\&.SteamVR\&.Dispose ()"

.PP
Definition at line 694 of file SteamVR\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR\&.ExitTemporarySession ()\fC [static]\fP"

.PP
Definition at line 328 of file SteamVR\&.cs\&.
.SS "static string Valve\&.VR\&.SteamVR\&.GenerateAppKey ()\fC [static]\fP"

.PP
Definition at line 407 of file SteamVR\&.cs\&.
.SS "static string Valve\&.VR\&.SteamVR\&.GenerateCleanProductName ()\fC [static]\fP"

.PP
Definition at line 414 of file SteamVR\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR\&.GetFloatProperty (\fBETrackedDeviceProperty\fP prop, uint deviceId = \fC\fBOpenVR\&.k_unTrackedDeviceIndex_Hmd\fP\fP)"

.PP
Definition at line 281 of file SteamVR\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR\&.GetStringProperty (\fBETrackedDeviceProperty\fP prop, uint deviceId = \fC\fBOpenVR\&.k_unTrackedDeviceIndex_Hmd\fP\fP)"

.PP
Definition at line 268 of file SteamVR\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR\&.GetTrackedDeviceString (uint deviceId)"

.PP
Definition at line 255 of file SteamVR\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR\&.Initialize (bool forceUnityVRMode = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 87 of file SteamVR\&.cs\&.
.SS "static bool Valve\&.VR\&.SteamVR\&.InitializeTemporarySession (bool initInput = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 289 of file SteamVR\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR\&.SafeDispose ()\fC [static]\fP"

.PP
Definition at line 712 of file SteamVR\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool [] Valve\&.VR\&.SteamVR\&.connected = new bool[\fBOpenVR\&.k_unMaxTrackedDeviceCount\fP]\fC [static]\fP"

.PP
Definition at line 235 of file SteamVR\&.cs\&.
.SS "const string Valve\&.VR\&.SteamVR\&.defaultAppKeyTemplate = 'application\&.generated\&.{0}'"

.PP
Definition at line 405 of file SteamVR\&.cs\&.
.SS "const string Valve\&.VR\&.SteamVR\&.defaultUnityAppKeyTemplate = 'application\&.generated\&.unity\&.{0}\&.exe'"

.PP
Definition at line 404 of file SteamVR\&.cs\&.
.SS "\fBInitializedStates\fP Valve\&.VR\&.SteamVR\&.initializedState = \fBInitializedStates\&.None\fP\fC [static]\fP"

.PP
Definition at line 85 of file SteamVR\&.cs\&.
.SS "\fBETextureType\fP Valve\&.VR\&.SteamVR\&.textureType"

.PP
Definition at line 245 of file SteamVR\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR\&.active\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 25 of file SteamVR\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR\&.aspect\fC [get]\fP"

.PP
Definition at line 240 of file SteamVR\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR\&.calibrating\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 232 of file SteamVR\&.cs\&.
.SS "\fBCVRCompositor\fP Valve\&.VR\&.SteamVR\&.compositor\fC [get]\fP"

.PP
Definition at line 227 of file SteamVR\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR\&.enabled\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 30 of file SteamVR\&.cs\&.
.SS "\fBSteamVR_Utils\&.RigidTransform\fP [] Valve\&.VR\&.SteamVR\&.eyes\fC [get]\fP"

.PP
Definition at line 244 of file SteamVR\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR\&.fieldOfView\fC [get]\fP"

.PP
Definition at line 241 of file SteamVR\&.cs\&.
.SS "\fBCVRSystem\fP Valve\&.VR\&.SteamVR\&.hmd\fC [get]\fP"

.PP
Definition at line 226 of file SteamVR\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR\&.hmd_DisplayFrequency\fC [get]\fP"

.PP
Definition at line 253 of file SteamVR\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR\&.hmd_ModelNumber\fC [get]\fP"

.PP
Definition at line 249 of file SteamVR\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR\&.hmd_SecondsFromVsyncToPhotons\fC [get]\fP"

.PP
Definition at line 252 of file SteamVR\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR\&.hmd_SerialNumber\fC [get]\fP"

.PP
Definition at line 250 of file SteamVR\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR\&.hmd_TrackingSystemName\fC [get]\fP"

.PP
Definition at line 248 of file SteamVR\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR\&.initializing\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 231 of file SteamVR\&.cs\&.
.SS "\fBSteamVR\fP Valve\&.VR\&.SteamVR\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 54 of file SteamVR\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR\&.outOfRange\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 233 of file SteamVR\&.cs\&.
.SS "\fBCVROverlay\fP Valve\&.VR\&.SteamVR\&.overlay\fC [get]\fP"

.PP
Definition at line 228 of file SteamVR\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR\&.sceneHeight\fC [get]\fP"

.PP
Definition at line 239 of file SteamVR\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR\&.sceneWidth\fC [get]\fP"

.PP
Definition at line 238 of file SteamVR\&.cs\&.
.SS "\fBSteamVR_Settings\fP Valve\&.VR\&.SteamVR\&.settings\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 113 of file SteamVR\&.cs\&.
.SS "Vector2 Valve\&.VR\&.SteamVR\&.tanHalfFov\fC [get]\fP"

.PP
Definition at line 242 of file SteamVR\&.cs\&.
.SS "\fBVRTextureBounds_t\fP [] Valve\&.VR\&.SteamVR\&.textureBounds\fC [get]\fP"

.PP
Definition at line 243 of file SteamVR\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR\&.usingNativeSupport\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line 109 of file SteamVR\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
