.TH "Valve.VR.InteractionSystem.Sample.FloppyHand" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.Sample.FloppyHand
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFinger\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_Action_Single\fP \fBsqueezyAction\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Single\fP>('Squeeze')"
.br
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBinputSource\fP"
.br
.ti -1c
.RI "\fBFinger\fP [] \fBfingers\fP"
.br
.ti -1c
.RI "Vector3 \fBconstforce\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBfingerFlexAngle\fP = 140"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file FloppyHand\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.constforce"

.PP
Definition at line 210 of file FloppyHand\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.fingerFlexAngle = 140\fC [protected]\fP"

.PP
Definition at line 10 of file FloppyHand\&.cs\&.
.SS "\fBFinger\fP [] Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.fingers"

.PP
Definition at line 208 of file FloppyHand\&.cs\&.
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.inputSource"

.PP
Definition at line 13 of file FloppyHand\&.cs\&.
.SS "\fBSteamVR_Action_Single\fP Valve\&.VR\&.InteractionSystem\&.Sample\&.FloppyHand\&.squeezyAction = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Single\fP>('Squeeze')"

.PP
Definition at line 12 of file FloppyHand\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
