.TH "Valve.VR.VREvent_TouchPadMove_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VREvent_TouchPadMove_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBbFingerDown\fP"
.br
.ti -1c
.RI "float \fBflSecondsFingerDown\fP"
.br
.ti -1c
.RI "float \fBfValueXFirst\fP"
.br
.ti -1c
.RI "float \fBfValueYFirst\fP"
.br
.ti -1c
.RI "float \fBfValueXRaw\fP"
.br
.ti -1c
.RI "float \fBfValueYRaw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5059 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Valve\&.VR\&.VREvent_TouchPadMove_t\&.bFingerDown"

.PP
Definition at line 5062 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.VREvent_TouchPadMove_t\&.flSecondsFingerDown"

.PP
Definition at line 5063 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.VREvent_TouchPadMove_t\&.fValueXFirst"

.PP
Definition at line 5064 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.VREvent_TouchPadMove_t\&.fValueXRaw"

.PP
Definition at line 5066 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.VREvent_TouchPadMove_t\&.fValueYFirst"

.PP
Definition at line 5065 of file openvr_api\&.cs\&.
.SS "float Valve\&.VR\&.VREvent_TouchPadMove_t\&.fValueYRaw"

.PP
Definition at line 5067 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
