.TH "Valve.VR.SteamVR_IK" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_IK
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBSolve\fP (Vector3 \fBstart\fP, Vector3 end, Vector3 \fBpoleVector\fP, float jointDist, float targetDist, ref Vector3 result, out Vector3 forward, out Vector3 up)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBtarget\fP"
.br
.ti -1c
.RI "Transform \fBstart\fP"
.br
.ti -1c
.RI "Transform \fBpoleVector\fP"
.br
.ti -1c
.RI "float \fBblendPct\fP = 1\&.0f"
.br
.ti -1c
.RI "Transform \fBstartXform\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file SteamVR_IK\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool Valve\&.VR\&.SteamVR_IK\&.Solve (Vector3 start, Vector3 end, Vector3 poleVector, float jointDist, float targetDist, ref Vector3 result, out Vector3 forward, out Vector3 up)\fC [static]\fP"

.PP
Definition at line 111 of file SteamVR_IK\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.SteamVR_IK\&.blendPct = 1\&.0f"

.PP
Definition at line 17 of file SteamVR_IK\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_IK\&.poleVector"

.PP
Definition at line 15 of file SteamVR_IK\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_IK\&.start"

.PP
Definition at line 14 of file SteamVR_IK\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_IK\&.startXform"

.PP
Definition at line 20 of file SteamVR_IK\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_IK\&.target"

.PP
Definition at line 13 of file SteamVR_IK\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
