.TH "Valve.VR.SteamVR_Action_In_Source" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Action_In_Source \- In actions are all input type actions\&. Boolean, Single, Vector2, Vector3, Skeleton, and Pose\&. This class fires onChange and onUpdate events\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_Action_Source\fP, and \fBValve\&.VR\&.ISteamVR_Action_In_Source\fP\&.
.PP
Inherited by \fBValve\&.VR\&.SteamVR_Action_Boolean_Source\fP, \fBValve\&.VR\&.SteamVR_Action_Pose_Source\fP, \fBValve\&.VR\&.SteamVR_Action_Single_Source\fP, \fBValve\&.VR\&.SteamVR_Action_Vector2_Source\fP, and \fBValve\&.VR\&.SteamVR_Action_Vector3_Source\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBUpdateValue\fP ()"
.br
.RI "\fB[Should not be called by user code]\fP Updates the data for this action and this input source "
.ti -1c
.RI "override void \fBInitialize\fP ()"
.br
.RI "\fB[Should not be called by user code]\fP Initializes the handle for the action, the size of the InputOriginInfo struct, and any other related \fBSteamVR\fP data\&. "
.ti -1c
.RI "string \fBGetLocalizedOriginPart\fP (params \fBEVRInputStringBits\fP[] localizedParts)"
.br
.RI "Gets the localized name of the device that the action corresponds to\&. Include as many EVRInputStringBits as you want to add to the localized string "
.ti -1c
.RI "string \fBGetLocalizedOrigin\fP ()"
.br
.RI "Gets the localized full name of the device that the action was updated by\&. ex: 'Left Hand Vive Controller Trackpad' "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateOriginTrackedDeviceInfo\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBInputOriginInfo_t\fP \fBinputOriginInfo\fP = new \fBInputOriginInfo_t\fP()"
.br
.ti -1c
.RI "\fBInputOriginInfo_t\fP \fBlastInputOriginInfo\fP = new \fBInputOriginInfo_t\fP()"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static uint \fBinputOriginInfo_size\fP = 0"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBisUpdating\fP\fC [get, set]\fP"
.br
.RI "\fB[Should not be called by user code]\fP Forces the system to start updating the data for this action and the specified input source\&. Should only be used if you've set \fBSteamVR_Action\&.startUpdatingSourceOnAccess\fP to false\&. "
.ti -1c
.RI "float \fBupdateTime\fP\fC [get, protected set]\fP"
.br
.RI "The time the action was updated (Time\&.realtimeSinceStartup) "
.ti -1c
.RI "abstract ulong \fBactiveOrigin\fP\fC [get]\fP"
.br
.RI "The handle to the component that triggered the action to be changed "
.ti -1c
.RI "abstract ulong \fBlastActiveOrigin\fP\fC [get]\fP"
.br
.RI "The handle to the component that triggered the action to be changed in the previous update "
.ti -1c
.RI "abstract bool \fBchanged\fP\fC [get, protected set]\fP"
.br
.RI "Returns true if the action has been changed since the previous update "
.ti -1c
.RI "abstract bool \fBlastChanged\fP\fC [get, protected set]\fP"
.br
.RI "Returns true if the action was changed for the previous update cycle "
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBactiveDevice\fP\fC [get]\fP"
.br
.RI "The input source that triggered the action to be updated "
.ti -1c
.RI "uint \fBtrackedDeviceIndex\fP\fC [get]\fP"
.br
.RI "The device index (used by Render Models) used by the device that triggered the action to be updated "
.ti -1c
.RI "string \fBrenderModelComponentName\fP\fC [get]\fP"
.br
.RI "The name of the component on the render model that caused the action to be updated (not localized) "
.ti -1c
.RI "string \fBlocalizedOriginName\fP\fC [get]\fP"
.br
.RI "Gets the localized full name of the device that the action was updated by\&. ex: 'Left Hand Vive Controller Trackpad' "
.ti -1c
.RI "float \fBchangedTime\fP\fC [get, protected set]\fP"
.br
.RI "The Time\&.realtimeSinceStartup that this action was last changed\&. "
.ti -1c
.RI "int \fBlastOriginGetFrame\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
In actions are all input type actions\&. Boolean, Single, Vector2, Vector3, Skeleton, and Pose\&. This class fires onChange and onUpdate events\&. 


.PP
Definition at line 219 of file SteamVR_Action_In\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string Valve\&.VR\&.SteamVR_Action_In_Source\&.GetLocalizedOrigin ()"

.PP
Gets the localized full name of the device that the action was updated by\&. ex: 'Left Hand Vive Controller Trackpad' 
.PP
Definition at line 323 of file SteamVR_Action_In\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Action_In_Source\&.GetLocalizedOriginPart (params \fBEVRInputStringBits\fP [] localizedParts)"

.PP
Gets the localized name of the device that the action corresponds to\&. Include as many EVRInputStringBits as you want to add to the localized string 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP 
.br
\fIlocalizedParts\fP 
.PD 0

.IP "\(bu" 2
VRInputString_Hand - Which hand the origin is in\&. ex: 'Left Hand'\&.  
.IP "\(bu" 2
VRInputString_ControllerType - What kind of controller the user has in that hand\&. ex: 'Vive Controller'\&.  
.IP "\(bu" 2
VRInputString_InputSource - What part of that controller is the origin\&. ex: 'Trackpad'\&.  
.IP "\(bu" 2
VRInputString_All - All of the above\&. ex: 'Left Hand Vive Controller Trackpad'\&.  
.PP
.RE
.PP

.PP
Definition at line 308 of file SteamVR_Action_In\&.cs\&.
.SS "override void Valve\&.VR\&.SteamVR_Action_In_Source\&.Initialize ()\fC [virtual]\fP"

.PP
\fB[Should not be called by user code]\fP Initializes the handle for the action, the size of the InputOriginInfo struct, and any other related \fBSteamVR\fP data\&. 
.PP
Reimplemented from \fBValve\&.VR\&.SteamVR_Action_Source\fP\&.
.PP
Reimplemented in \fBValve\&.VR\&.SteamVR_Action_Skeleton_Source\fP, \fBValve\&.VR\&.SteamVR_Action_Pose_Source\fP, \fBValve\&.VR\&.SteamVR_Action_Vector2_Source\fP, \fBValve\&.VR\&.SteamVR_Action_Vector3_Source\fP, and \fBValve\&.VR\&.SteamVR_Action_Single_Source\fP\&.
.PP
Definition at line 274 of file SteamVR_Action_In\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_In_Source\&.UpdateOriginTrackedDeviceInfo ()\fC [protected]\fP"

.PP
Definition at line 282 of file SteamVR_Action_In\&.cs\&.
.SS "abstract void Valve\&.VR\&.SteamVR_Action_In_Source\&.UpdateValue ()\fC [pure virtual]\fP"

.PP
\fB[Should not be called by user code]\fP Updates the data for this action and this input source 
.PP
Implemented in \fBValve\&.VR\&.SteamVR_Action_Skeleton_Source\fP, \fBValve\&.VR\&.SteamVR_Action_Pose_Source\fP, \fBValve\&.VR\&.SteamVR_Action_Boolean_Source\fP, \fBValve\&.VR\&.SteamVR_Action_Vector2_Source\fP, \fBValve\&.VR\&.SteamVR_Action_Vector3_Source\fP, and \fBValve\&.VR\&.SteamVR_Action_Single_Source\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBInputOriginInfo_t\fP Valve\&.VR\&.SteamVR_Action_In_Source\&.inputOriginInfo = new \fBInputOriginInfo_t\fP()\fC [protected]\fP"

.PP
Definition at line 265 of file SteamVR_Action_In\&.cs\&.
.SS "uint Valve\&.VR\&.SteamVR_Action_In_Source\&.inputOriginInfo_size = 0\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 221 of file SteamVR_Action_In\&.cs\&.
.SS "\fBInputOriginInfo_t\fP Valve\&.VR\&.SteamVR_Action_In_Source\&.lastInputOriginInfo = new \fBInputOriginInfo_t\fP()\fC [protected]\fP"

.PP
Definition at line 266 of file SteamVR_Action_In\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.SteamVR_Action_In_Source\&.activeDevice\fC [get]\fP"

.PP
The input source that triggered the action to be updated 
.PP
Definition at line 246 of file SteamVR_Action_In\&.cs\&.
.SS "abstract ulong Valve\&.VR\&.SteamVR_Action_In_Source\&.activeOrigin\fC [get]\fP"

.PP
The handle to the component that triggered the action to be changed 
.PP
Definition at line 234 of file SteamVR_Action_In\&.cs\&.
.SS "abstract bool Valve\&.VR\&.SteamVR_Action_In_Source\&.changed\fC [get]\fP, \fC [protected set]\fP"

.PP
Returns true if the action has been changed since the previous update 
.PP
Definition at line 240 of file SteamVR_Action_In\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Action_In_Source\&.changedTime\fC [get]\fP, \fC [protected set]\fP"

.PP
The Time\&.realtimeSinceStartup that this action was last changed\&. 
.PP
Definition at line 261 of file SteamVR_Action_In\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Action_In_Source\&.isUpdating\fC [get]\fP, \fC [set]\fP"

.PP
\fB[Should not be called by user code]\fP Forces the system to start updating the data for this action and the specified input source\&. Should only be used if you've set \fBSteamVR_Action\&.startUpdatingSourceOnAccess\fP to false\&. 
.PP
Definition at line 228 of file SteamVR_Action_In\&.cs\&.
.SS "abstract ulong Valve\&.VR\&.SteamVR_Action_In_Source\&.lastActiveOrigin\fC [get]\fP"

.PP
The handle to the component that triggered the action to be changed in the previous update 
.PP
Definition at line 237 of file SteamVR_Action_In\&.cs\&.
.SS "abstract bool Valve\&.VR\&.SteamVR_Action_In_Source\&.lastChanged\fC [get]\fP, \fC [protected set]\fP"

.PP
Returns true if the action was changed for the previous update cycle 
.PP
Definition at line 243 of file SteamVR_Action_In\&.cs\&.
.SS "int Valve\&.VR\&.SteamVR_Action_In_Source\&.lastOriginGetFrame\fC [get]\fP, \fC [set]\fP, \fC [protected]\fP"

.PP
Definition at line 263 of file SteamVR_Action_In\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Action_In_Source\&.localizedOriginName\fC [get]\fP"

.PP
Gets the localized full name of the device that the action was updated by\&. ex: 'Left Hand Vive Controller Trackpad' 
.PP
Definition at line 257 of file SteamVR_Action_In\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_Action_In_Source\&.renderModelComponentName\fC [get]\fP"

.PP
The name of the component on the render model that caused the action to be updated (not localized) 
.PP
Definition at line 252 of file SteamVR_Action_In\&.cs\&.
.SS "uint Valve\&.VR\&.SteamVR_Action_In_Source\&.trackedDeviceIndex\fC [get]\fP"

.PP
The device index (used by Render Models) used by the device that triggered the action to be updated 
.PP
Definition at line 249 of file SteamVR_Action_In\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Action_In_Source\&.updateTime\fC [get]\fP, \fC [protected set]\fP"

.PP
The time the action was updated (Time\&.realtimeSinceStartup) 
.PP
Definition at line 231 of file SteamVR_Action_In\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
