.TH "Valve.VR.SteamVR_Action_Vibration" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Action_Vibration \- Vibration actions are used to trigger haptic feedback in vr controllers\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValve\&.VR\&.SteamVR_Action_Out< SteamVR_Action_Vibration_Source_Map, SteamVR_Action_Vibration_Source >\fP, and ISerializationCallbackReceiver\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBActiveChangeHandler\fP (\fBSteamVR_Action_Vibration\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool active)"
.br
.ti -1c
.RI "delegate void \fBExecuteHandler\fP (\fBSteamVR_Action_Vibration\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, float secondsFromNow, float durationSeconds, float frequency, float amplitude)"
.br
.ti -1c
.RI "\fBSteamVR_Action_Vibration\fP ()"
.br
.ti -1c
.RI "void \fBExecute\fP (float secondsFromNow, float durationSeconds, float frequency, float amplitude, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Trigger the haptics at a certain time for a certain length "
.ti -1c
.RI "void \fBAddOnActiveChangeListener\fP (\fBActiveChangeHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Executes a function when the \fIfunctional\fP active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound, or when the ActionSet changes state\&. "
.ti -1c
.RI "void \fBRemoveOnActiveChangeListener\fP (\fBActiveChangeHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Stops executing a function when the \fIfunctional\fP active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound, or when the ActionSet changes state\&. "
.ti -1c
.RI "void \fBAddOnActiveBindingChangeListener\fP (\fBActiveChangeHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Executes a function when the active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound "
.ti -1c
.RI "void \fBRemoveOnActiveBindingChangeListener\fP (\fBActiveChangeHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.ti -1c
.RI "void \fBAddOnExecuteListener\fP (\fBExecuteHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Executes a function when the execute method of this action (with the specified inputSource) is called\&. This happens when the action is bound or unbound "
.ti -1c
.RI "void \fBRemoveOnExecuteListener\fP (\fBExecuteHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Stops executing the function setup by the corresponding AddListener "
.ti -1c
.RI "override float \fBGetTimeLastChanged\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.RI "Returns the last time this action was executed "
.ti -1c
.RI "override bool \fBIsUpdating\fP (\fBSteamVR_Input_Sources\fP inputSource)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBActiveChangeHandler\fP \fBonActiveChange\fP"
.br
.RI "\fB[\fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever a change happens in the action "
.ti -1c
.RI "\fBActiveChangeHandler\fP \fBonActiveBindingChange\fP"
.br
.RI "\fB[\fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever a change happens in the action "
.ti -1c
.RI "\fBExecuteHandler\fP \fBonExecute\fP"
.br
.RI "\fB[\fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever this action is executed "
.in -1c
.SH "Detailed Description"
.PP 
Vibration actions are used to trigger haptic feedback in vr controllers\&. 


.PP
Definition at line 18 of file SteamVR_Action_Vibration\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.SteamVR_Action_Vibration\&.SteamVR_Action_Vibration ()"

.PP
Definition at line 36 of file SteamVR_Action_Vibration\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "delegate void Valve\&.VR\&.SteamVR_Action_Vibration\&.ActiveChangeHandler (\fBSteamVR_Action_Vibration\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, bool active)"

.SS "void Valve\&.VR\&.SteamVR_Action_Vibration\&.AddOnActiveBindingChangeListener (\fBActiveChangeHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Executes a function when the active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToCall\fP A local function that receives the boolean action who's active state changes and the corresponding input source
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 74 of file SteamVR_Action_Vibration\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Vibration\&.AddOnActiveChangeListener (\fBActiveChangeHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Executes a function when the \fIfunctional\fP active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound, or when the ActionSet changes state\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToCall\fP A local function that receives the boolean action who's active state changes and the corresponding input source
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 57 of file SteamVR_Action_Vibration\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Vibration\&.AddOnExecuteListener (\fBExecuteHandler\fP functionToCall, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Executes a function when the execute method of this action (with the specified inputSource) is called\&. This happens when the action is bound or unbound 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToCall\fP A local function that receives the boolean action who's active state changes and the corresponding input source
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 90 of file SteamVR_Action_Vibration\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Vibration\&.Execute (float secondsFromNow, float durationSeconds, float frequency, float amplitude, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Trigger the haptics at a certain time for a certain length 
.PP
\fBParameters:\fP
.RS 4
\fIsecondsFromNow\fP How long from the current time to execute the action (in seconds - can be 0)
.br
\fIdurationSeconds\fP How long the haptic action should last (in seconds)
.br
\fIfrequency\fP How often the haptic motor should bounce (0 - 320 in hz\&. The lower end being more useful)
.br
\fIamplitude\fP How intense the haptic action should be (0 - 1)
.br
\fIinputSource\fP The device you would like to execute the haptic action\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 47 of file SteamVR_Action_Vibration\&.cs\&.
.SS "delegate void Valve\&.VR\&.SteamVR_Action_Vibration\&.ExecuteHandler (\fBSteamVR_Action_Vibration\fP fromAction, \fBSteamVR_Input_Sources\fP fromSource, float secondsFromNow, float durationSeconds, float frequency, float amplitude)"

.SS "override float Valve\&.VR\&.SteamVR_Action_Vibration\&.GetTimeLastChanged (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
Returns the last time this action was executed 
.PP
\fBParameters:\fP
.RS 4
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 107 of file SteamVR_Action_Vibration\&.cs\&.
.SS "override bool Valve\&.VR\&.SteamVR_Action_Vibration\&.IsUpdating (\fBSteamVR_Input_Sources\fP inputSource)"

.PP
Definition at line 121 of file SteamVR_Action_Vibration\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Vibration\&.RemoveOnActiveBindingChangeListener (\fBActiveChangeHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive update events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 82 of file SteamVR_Action_Vibration\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Vibration\&.RemoveOnActiveChangeListener (\fBActiveChangeHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Stops executing a function when the \fIfunctional\fP active state of this action (with the specified inputSource) changes\&. This happens when the action is bound or unbound, or when the ActionSet changes state\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive update events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 66 of file SteamVR_Action_Vibration\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Action_Vibration\&.RemoveOnExecuteListener (\fBExecuteHandler\fP functionToStopCalling, \fBSteamVR_Input_Sources\fP inputSource)"

.PP
Stops executing the function setup by the corresponding AddListener 
.PP
\fBParameters:\fP
.RS 4
\fIfunctionToStopCalling\fP The local function that you've setup to receive update events
.br
\fIinputSource\fP The device you would like to get data from\&. Any if the action is not device specific\&.
.RE
.PP

.PP
Definition at line 98 of file SteamVR_Action_Vibration\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBActiveChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Vibration\&.onActiveBindingChange\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[\fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever a change happens in the action 
.PP
Definition at line 29 of file SteamVR_Action_Vibration\&.cs\&.
.SS "\fBActiveChangeHandler\fP Valve\&.VR\&.SteamVR_Action_Vibration\&.onActiveChange\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[\fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever a change happens in the action 
.PP
Definition at line 25 of file SteamVR_Action_Vibration\&.cs\&.
.SS "\fBExecuteHandler\fP Valve\&.VR\&.SteamVR_Action_Vibration\&.onExecute\fC [add]\fP, \fC [remove]\fP"

.PP
\fB[\fBSteamVR_Input_Sources\&.Any\fP]\fP This event fires whenever this action is executed 
.PP
Definition at line 33 of file SteamVR_Action_Vibration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
