.TH "Valve.VR.VREvent_Data_t" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.VREvent_Data_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVREvent_Reserved_t\fP \fBreserved\fP"
.br
.ti -1c
.RI "\fBVREvent_Controller_t\fP \fBcontroller\fP"
.br
.ti -1c
.RI "\fBVREvent_Mouse_t\fP \fBmouse\fP"
.br
.ti -1c
.RI "\fBVREvent_Scroll_t\fP \fBscroll\fP"
.br
.ti -1c
.RI "\fBVREvent_Process_t\fP \fBprocess\fP"
.br
.ti -1c
.RI "\fBVREvent_Notification_t\fP \fBnotification\fP"
.br
.ti -1c
.RI "\fBVREvent_Overlay_t\fP \fBoverlay\fP"
.br
.ti -1c
.RI "\fBVREvent_Status_t\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBVREvent_Ipd_t\fP \fBipd\fP"
.br
.ti -1c
.RI "\fBVREvent_Chaperone_t\fP \fBchaperone\fP"
.br
.ti -1c
.RI "\fBVREvent_PerformanceTest_t\fP \fBperformanceTest\fP"
.br
.ti -1c
.RI "\fBVREvent_TouchPadMove_t\fP \fBtouchPadMove\fP"
.br
.ti -1c
.RI "\fBVREvent_SeatedZeroPoseReset_t\fP \fBseatedZeroPoseReset\fP"
.br
.ti -1c
.RI "\fBVREvent_Screenshot_t\fP \fBscreenshot\fP"
.br
.ti -1c
.RI "\fBVREvent_ScreenshotProgress_t\fP \fBscreenshotProgress\fP"
.br
.ti -1c
.RI "\fBVREvent_ApplicationLaunch_t\fP \fBapplicationLaunch\fP"
.br
.ti -1c
.RI "\fBVREvent_EditingCameraSurface_t\fP \fBcameraSurface\fP"
.br
.ti -1c
.RI "\fBVREvent_MessageOverlay_t\fP \fBmessageOverlay\fP"
.br
.ti -1c
.RI "\fBVREvent_Property_t\fP \fBproperty\fP"
.br
.ti -1c
.RI "\fBVREvent_DualAnalog_t\fP \fBdualAnalog\fP"
.br
.ti -1c
.RI "\fBVREvent_HapticVibration_t\fP \fBhapticVibration\fP"
.br
.ti -1c
.RI "\fBVREvent_WebConsole_t\fP \fBwebConsole\fP"
.br
.ti -1c
.RI "\fBVREvent_InputBindingLoad_t\fP \fBinputBinding\fP"
.br
.ti -1c
.RI "\fBVREvent_SpatialAnchor_t\fP \fBspatialAnchor\fP"
.br
.ti -1c
.RI "\fBVREvent_InputActionManifestLoad_t\fP \fBactionManifest\fP"
.br
.ti -1c
.RI "\fBVREvent_ProgressUpdate_t\fP \fBprogressUpdate\fP"
.br
.ti -1c
.RI "\fBVREvent_ShowUI_t\fP \fBshowUi\fP"
.br
.ti -1c
.RI "\fBVREvent_Keyboard_t\fP \fBkeyboard\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4831 of file openvr_api\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBVREvent_InputActionManifestLoad_t\fP Valve\&.VR\&.VREvent_Data_t\&.actionManifest"

.PP
Definition at line 4857 of file openvr_api\&.cs\&.
.SS "\fBVREvent_ApplicationLaunch_t\fP Valve\&.VR\&.VREvent_Data_t\&.applicationLaunch"

.PP
Definition at line 4848 of file openvr_api\&.cs\&.
.SS "\fBVREvent_EditingCameraSurface_t\fP Valve\&.VR\&.VREvent_Data_t\&.cameraSurface"

.PP
Definition at line 4849 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Chaperone_t\fP Valve\&.VR\&.VREvent_Data_t\&.chaperone"

.PP
Definition at line 4842 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Controller_t\fP Valve\&.VR\&.VREvent_Data_t\&.controller"

.PP
Definition at line 4834 of file openvr_api\&.cs\&.
.SS "\fBVREvent_DualAnalog_t\fP Valve\&.VR\&.VREvent_Data_t\&.dualAnalog"

.PP
Definition at line 4852 of file openvr_api\&.cs\&.
.SS "\fBVREvent_HapticVibration_t\fP Valve\&.VR\&.VREvent_Data_t\&.hapticVibration"

.PP
Definition at line 4853 of file openvr_api\&.cs\&.
.SS "\fBVREvent_InputBindingLoad_t\fP Valve\&.VR\&.VREvent_Data_t\&.inputBinding"

.PP
Definition at line 4855 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Ipd_t\fP Valve\&.VR\&.VREvent_Data_t\&.ipd"

.PP
Definition at line 4841 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Keyboard_t\fP Valve\&.VR\&.VREvent_Data_t\&.keyboard"

.PP
Definition at line 4860 of file openvr_api\&.cs\&.
.SS "\fBVREvent_MessageOverlay_t\fP Valve\&.VR\&.VREvent_Data_t\&.messageOverlay"

.PP
Definition at line 4850 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Mouse_t\fP Valve\&.VR\&.VREvent_Data_t\&.mouse"

.PP
Definition at line 4835 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Notification_t\fP Valve\&.VR\&.VREvent_Data_t\&.notification"

.PP
Definition at line 4838 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Overlay_t\fP Valve\&.VR\&.VREvent_Data_t\&.overlay"

.PP
Definition at line 4839 of file openvr_api\&.cs\&.
.SS "\fBVREvent_PerformanceTest_t\fP Valve\&.VR\&.VREvent_Data_t\&.performanceTest"

.PP
Definition at line 4843 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Process_t\fP Valve\&.VR\&.VREvent_Data_t\&.process"

.PP
Definition at line 4837 of file openvr_api\&.cs\&.
.SS "\fBVREvent_ProgressUpdate_t\fP Valve\&.VR\&.VREvent_Data_t\&.progressUpdate"

.PP
Definition at line 4858 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Property_t\fP Valve\&.VR\&.VREvent_Data_t\&.property"

.PP
Definition at line 4851 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Reserved_t\fP Valve\&.VR\&.VREvent_Data_t\&.reserved"

.PP
Definition at line 4833 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Screenshot_t\fP Valve\&.VR\&.VREvent_Data_t\&.screenshot"

.PP
Definition at line 4846 of file openvr_api\&.cs\&.
.SS "\fBVREvent_ScreenshotProgress_t\fP Valve\&.VR\&.VREvent_Data_t\&.screenshotProgress"

.PP
Definition at line 4847 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Scroll_t\fP Valve\&.VR\&.VREvent_Data_t\&.scroll"

.PP
Definition at line 4836 of file openvr_api\&.cs\&.
.SS "\fBVREvent_SeatedZeroPoseReset_t\fP Valve\&.VR\&.VREvent_Data_t\&.seatedZeroPoseReset"

.PP
Definition at line 4845 of file openvr_api\&.cs\&.
.SS "\fBVREvent_ShowUI_t\fP Valve\&.VR\&.VREvent_Data_t\&.showUi"

.PP
Definition at line 4859 of file openvr_api\&.cs\&.
.SS "\fBVREvent_SpatialAnchor_t\fP Valve\&.VR\&.VREvent_Data_t\&.spatialAnchor"

.PP
Definition at line 4856 of file openvr_api\&.cs\&.
.SS "\fBVREvent_Status_t\fP Valve\&.VR\&.VREvent_Data_t\&.status"

.PP
Definition at line 4840 of file openvr_api\&.cs\&.
.SS "\fBVREvent_TouchPadMove_t\fP Valve\&.VR\&.VREvent_Data_t\&.touchPadMove"

.PP
Definition at line 4844 of file openvr_api\&.cs\&.
.SS "\fBVREvent_WebConsole_t\fP Valve\&.VR\&.VREvent_Data_t\&.webConsole"

.PP
Definition at line 4854 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
