.TH "Valve.VR.SteamVR_RenderModel" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_RenderModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRenderModel\fP"
.br
.ti -1c
.RI "class \fBRenderModelInterfaceHolder\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetMeshRendererState\fP (bool state)"
.br
.ti -1c
.RI "void \fBUpdateModel\fP ()"
.br
.ti -1c
.RI "Transform \fBFindTransformByName\fP (string componentName, Transform inTransform=null)"
.br
.ti -1c
.RI "Transform \fBGetComponentTransform\fP (string componentName)"
.br
.ti -1c
.RI "void \fBUpdateComponents\fP (\fBCVRRenderModels\fP renderModels)"
.br
.ti -1c
.RI "void \fBSetDeviceIndex\fP (int newIndex)"
.br
.ti -1c
.RI "void \fBSetInputSource\fP (\fBSteamVR_Input_Sources\fP newInputSource)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_TrackedObject\&.EIndex\fP \fBindex\fP = \fBSteamVR_TrackedObject\&.EIndex\&.None\fP"
.br
.ti -1c
.RI "const string \fBmodelOverrideWarning\fP"
.br
.ti -1c
.RI "string \fBmodelOverride\fP"
.br
.ti -1c
.RI "Shader \fBshader\fP"
.br
.ti -1c
.RI "bool \fBverbose\fP = false"
.br
.ti -1c
.RI "bool \fBcreateComponents\fP = true"
.br
.ti -1c
.RI "bool \fBupdateDynamically\fP = true"
.br
.ti -1c
.RI "\fBRenderModel_ControllerMode_State_t\fP \fBcontrollerModeState\fP"
.br
.ti -1c
.RI "const string \fBk_localTransformName\fP = 'attach'"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Hashtable \fBmodels\fP = new Hashtable()"
.br
.ti -1c
.RI "static Hashtable \fBmaterials\fP = new Hashtable()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBinputSource\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBrenderModelName\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBinitializedAttachPoints\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file SteamVR_RenderModel\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Transform Valve\&.VR\&.SteamVR_RenderModel\&.FindTransformByName (string componentName, Transform inTransform = \fCnull\fP)"

.PP
Definition at line 492 of file SteamVR_RenderModel\&.cs\&.
.SS "Transform Valve\&.VR\&.SteamVR_RenderModel\&.GetComponentTransform (string componentName)"

.PP
Definition at line 507 of file SteamVR_RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_RenderModel\&.SetDeviceIndex (int newIndex)"

.PP
Definition at line 801 of file SteamVR_RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_RenderModel\&.SetInputSource (\fBSteamVR_Input_Sources\fP newInputSource)"

.PP
Definition at line 813 of file SteamVR_RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_RenderModel\&.SetMeshRendererState (bool state)"

.PP
Definition at line 118 of file SteamVR_RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_RenderModel\&.UpdateComponents (\fBCVRRenderModels\fP renderModels)"

.PP
Definition at line 739 of file SteamVR_RenderModel\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_RenderModel\&.UpdateModel ()"

.PP
Definition at line 145 of file SteamVR_RenderModel\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRenderModel_ControllerMode_State_t\fP Valve\&.VR\&.SteamVR_RenderModel\&.controllerModeState"

.PP
Definition at line 41 of file SteamVR_RenderModel\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_RenderModel\&.createComponents = true"

.PP
Definition at line 35 of file SteamVR_RenderModel\&.cs\&.
.SS "\fBSteamVR_TrackedObject\&.EIndex\fP Valve\&.VR\&.SteamVR_RenderModel\&.index = \fBSteamVR_TrackedObject\&.EIndex\&.None\fP"

.PP
Definition at line 18 of file SteamVR_RenderModel\&.cs\&.
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.SteamVR_RenderModel\&.inputSource\fC [protected]\fP"

.PP
Definition at line 19 of file SteamVR_RenderModel\&.cs\&.
.SS "const string Valve\&.VR\&.SteamVR_RenderModel\&.k_localTransformName = 'attach'"

.PP
Definition at line 44 of file SteamVR_RenderModel\&.cs\&.
.SS "Hashtable Valve\&.VR\&.SteamVR_RenderModel\&.materials = new Hashtable()\fC [static]\fP"

.PP
Definition at line 76 of file SteamVR_RenderModel\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_RenderModel\&.modelOverride"

.PP
Definition at line 26 of file SteamVR_RenderModel\&.cs\&.
.SS "const string Valve\&.VR\&.SteamVR_RenderModel\&.modelOverrideWarning"
\fBInitial value:\fP
.PP
.nf
= "Model override is really only meant to be used in " +
            "the scene view for lining things up; using it at runtime is discouraged\&.  Use tracked device " +
            "index instead to ensure the correct model is displayed for all users\&."
.fi
.PP
Definition at line 21 of file SteamVR_RenderModel\&.cs\&.
.SS "Hashtable Valve\&.VR\&.SteamVR_RenderModel\&.models = new Hashtable()\fC [static]\fP"

.PP
Definition at line 75 of file SteamVR_RenderModel\&.cs\&.
.SS "Shader Valve\&.VR\&.SteamVR_RenderModel\&.shader"

.PP
Definition at line 29 of file SteamVR_RenderModel\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_RenderModel\&.updateDynamically = true"

.PP
Definition at line 38 of file SteamVR_RenderModel\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_RenderModel\&.verbose = false"

.PP
Definition at line 32 of file SteamVR_RenderModel\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Valve\&.VR\&.SteamVR_RenderModel\&.initializedAttachPoints\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line 49 of file SteamVR_RenderModel\&.cs\&.
.SS "string Valve\&.VR\&.SteamVR_RenderModel\&.renderModelName\fC [get]\fP"

.PP
Definition at line 47 of file SteamVR_RenderModel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
