.TH "Valve.VR.SteamVR_Skeleton_Pose_Hand" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Skeleton_Pose_Hand
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSteamVR_Skeleton_FingerExtensionTypes\fP \fBGetFingerExtensionType\fP (int finger)"
.br
.RI "Get extension type for a particular finger\&. Thumb is 0, Index is 1, etc\&. "
.ti -1c
.RI "\fBSteamVR_Skeleton_Pose_Hand\fP (\fBSteamVR_Input_Sources\fP source)"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_FingerExtensionTypes\fP \fBGetMovementTypeForBone\fP (int boneIndex)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBinputSource\fP"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_FingerExtensionTypes\fP \fBthumbFingerMovementType\fP = \fBSteamVR_Skeleton_FingerExtensionTypes\&.Static\fP"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_FingerExtensionTypes\fP \fBindexFingerMovementType\fP = \fBSteamVR_Skeleton_FingerExtensionTypes\&.Static\fP"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_FingerExtensionTypes\fP \fBmiddleFingerMovementType\fP = \fBSteamVR_Skeleton_FingerExtensionTypes\&.Static\fP"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_FingerExtensionTypes\fP \fBringFingerMovementType\fP = \fBSteamVR_Skeleton_FingerExtensionTypes\&.Static\fP"
.br
.ti -1c
.RI "\fBSteamVR_Skeleton_FingerExtensionTypes\fP \fBpinkyFingerMovementType\fP = \fBSteamVR_Skeleton_FingerExtensionTypes\&.Static\fP"
.br
.ti -1c
.RI "bool \fBignoreRootPoseData\fP = true"
.br
.ti -1c
.RI "bool \fBignoreWristPoseData\fP = true"
.br
.ti -1c
.RI "Vector3 \fBposition\fP"
.br
.ti -1c
.RI "Quaternion \fBrotation\fP"
.br
.ti -1c
.RI "Vector3 [] \fBbonePositions\fP"
.br
.ti -1c
.RI "Quaternion [] \fBboneRotations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file SteamVR_Skeleton_Pose\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.SteamVR_Skeleton_Pose_Hand (\fBSteamVR_Input_Sources\fP source)"

.PP
Definition at line 80 of file SteamVR_Skeleton_Pose\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSteamVR_Skeleton_FingerExtensionTypes\fP Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.GetFingerExtensionType (int finger)"

.PP
Get extension type for a particular finger\&. Thumb is 0, Index is 1, etc\&. 
.PP
Definition at line 53 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "\fBSteamVR_Skeleton_FingerExtensionTypes\fP Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.GetMovementTypeForBone (int boneIndex)"

.PP
Definition at line 85 of file SteamVR_Skeleton_Pose\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 [] Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.bonePositions"

.PP
Definition at line 77 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "Quaternion [] Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.boneRotations"

.PP
Definition at line 78 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.ignoreRootPoseData = true"

.PP
Definition at line 71 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "bool Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.ignoreWristPoseData = true"

.PP
Definition at line 72 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "\fBSteamVR_Skeleton_FingerExtensionTypes\fP Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.indexFingerMovementType = \fBSteamVR_Skeleton_FingerExtensionTypes\&.Static\fP"

.PP
Definition at line 45 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.inputSource"

.PP
Definition at line 42 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "\fBSteamVR_Skeleton_FingerExtensionTypes\fP Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.middleFingerMovementType = \fBSteamVR_Skeleton_FingerExtensionTypes\&.Static\fP"

.PP
Definition at line 46 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "\fBSteamVR_Skeleton_FingerExtensionTypes\fP Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.pinkyFingerMovementType = \fBSteamVR_Skeleton_FingerExtensionTypes\&.Static\fP"

.PP
Definition at line 48 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "Vector3 Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.position"

.PP
Definition at line 74 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "\fBSteamVR_Skeleton_FingerExtensionTypes\fP Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.ringFingerMovementType = \fBSteamVR_Skeleton_FingerExtensionTypes\&.Static\fP"

.PP
Definition at line 47 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "Quaternion Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.rotation"

.PP
Definition at line 75 of file SteamVR_Skeleton_Pose\&.cs\&.
.SS "\fBSteamVR_Skeleton_FingerExtensionTypes\fP Valve\&.VR\&.SteamVR_Skeleton_Pose_Hand\&.thumbFingerMovementType = \fBSteamVR_Skeleton_FingerExtensionTypes\&.Static\fP"

.PP
Definition at line 44 of file SteamVR_Skeleton_Pose\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
