.TH "Valve.VR.SteamVR_Skybox" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.SteamVR_Skybox
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCellSize\fP { \fBCellSize\&.x1024\fP, \fBCellSize\&.x64\fP, \fBCellSize\&.x32\fP, \fBCellSize\&.x16\fP, \fBCellSize\&.x8\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetTextureByIndex\fP (int i, Texture t)"
.br
.ti -1c
.RI "Texture \fBGetTextureByIndex\fP (int i)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetOverride\fP (Texture \fBfront\fP=null, Texture back=null, Texture left=null, Texture right=null, Texture top=null, Texture bottom=null)"
.br
.ti -1c
.RI "static void \fBClearOverride\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Texture \fBfront\fP"
.br
.ti -1c
.RI "\fBCellSize\fP \fBStereoCellSize\fP = \fBCellSize\&.x32\fP"
.br
.ti -1c
.RI "float \fBStereoIpdMm\fP = 64\&.0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file SteamVR_Skybox\&.cs\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBValve\&.VR\&.SteamVR_Skybox\&.CellSize\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIx1024 \fP\fP
.TP
\fB\fIx64 \fP\fP
.TP
\fB\fIx32 \fP\fP
.TP
\fB\fIx16 \fP\fP
.TP
\fB\fIx8 \fP\fP
.PP
Definition at line 17 of file SteamVR_Skybox\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Valve\&.VR\&.SteamVR_Skybox\&.ClearOverride ()\fC [static]\fP"

.PP
Definition at line 101 of file SteamVR_Skybox\&.cs\&.
.SS "Texture Valve\&.VR\&.SteamVR_Skybox\&.GetTextureByIndex (int i)"

.PP
Definition at line 50 of file SteamVR_Skybox\&.cs\&.
.SS "static void Valve\&.VR\&.SteamVR_Skybox\&.SetOverride (Texture front = \fCnull\fP, Texture back = \fCnull\fP, Texture left = \fCnull\fP, Texture right = \fCnull\fP, Texture top = \fCnull\fP, Texture bottom = \fCnull\fP)\fC [static]\fP"

.PP
Definition at line 70 of file SteamVR_Skybox\&.cs\&.
.SS "void Valve\&.VR\&.SteamVR_Skybox\&.SetTextureByIndex (int i, Texture t)"

.PP
Definition at line 25 of file SteamVR_Skybox\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Texture Valve\&.VR\&.SteamVR_Skybox\&.front"

.PP
Definition at line 15 of file SteamVR_Skybox\&.cs\&.
.SS "\fBCellSize\fP Valve\&.VR\&.SteamVR_Skybox\&.StereoCellSize = \fBCellSize\&.x32\fP"

.PP
Definition at line 21 of file SteamVR_Skybox\&.cs\&.
.SS "float Valve\&.VR\&.SteamVR_Skybox\&.StereoIpdMm = 64\&.0f"

.PP
Definition at line 23 of file SteamVR_Skybox\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
