.TH "Valve.VR.InteractionSystem.ControllerButtonHints" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.ControllerButtonHints
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetInputSource\fP (\fBSteamVR_Input_Sources\fP newInputSource)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShowButtonHint\fP (\fBHand\fP hand, params \fBISteamVR_Action_In_Source\fP[] actions)"
.br
.ti -1c
.RI "static void \fBHideButtonHint\fP (\fBHand\fP hand, params \fBISteamVR_Action_In_Source\fP[] actions)"
.br
.ti -1c
.RI "static void \fBHideAllButtonHints\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "static bool \fBIsButtonHintActive\fP (\fBHand\fP hand, \fBISteamVR_Action_In_Source\fP action)"
.br
.ti -1c
.RI "static void \fBShowTextHint\fP (\fBHand\fP hand, \fBISteamVR_Action_In_Source\fP action, string text, bool highlightButton=true)"
.br
.ti -1c
.RI "static void \fBHideTextHint\fP (\fBHand\fP hand, \fBISteamVR_Action_In_Source\fP action)"
.br
.ti -1c
.RI "static void \fBHideAllTextHints\fP (\fBHand\fP hand)"
.br
.ti -1c
.RI "static string \fBGetActiveHintText\fP (\fBHand\fP hand, \fBISteamVR_Action_In_Source\fP action)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Material \fBcontrollerMaterial\fP"
.br
.ti -1c
.RI "Color \fBflashColor\fP = new Color( 1\&.0f, 0\&.557f, 0\&.0f )"
.br
.ti -1c
.RI "GameObject \fBtextHintPrefab\fP"
.br
.ti -1c
.RI "\fBSteamVR_Action_Vibration\fP \fBhapticFlash\fP = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Vibration\fP>('Haptic')"
.br
.ti -1c
.RI "bool \fBdebugHints\fP = false"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSteamVR_Input_Sources\fP \fBinputSource\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBinitialized\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file ControllerButtonHints\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static string Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.GetActiveHintText (\fBHand\fP hand, \fBISteamVR_Action_In_Source\fP action)\fC [static]\fP"

.PP
Definition at line 826 of file ControllerButtonHints\&.cs\&.
.SS "static void Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.HideAllButtonHints (\fBHand\fP hand)\fC [static]\fP"

.PP
Definition at line 769 of file ControllerButtonHints\&.cs\&.
.SS "static void Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.HideAllTextHints (\fBHand\fP hand)\fC [static]\fP"

.PP
Definition at line 815 of file ControllerButtonHints\&.cs\&.
.SS "static void Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.HideButtonHint (\fBHand\fP hand, params \fBISteamVR_Action_In_Source\fP [] actions)\fC [static]\fP"

.PP
Definition at line 758 of file ControllerButtonHints\&.cs\&.
.SS "static void Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.HideTextHint (\fBHand\fP hand, \fBISteamVR_Action_In_Source\fP action)\fC [static]\fP"

.PP
Definition at line 804 of file ControllerButtonHints\&.cs\&.
.SS "static bool Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.IsButtonHintActive (\fBHand\fP hand, \fBISteamVR_Action_In_Source\fP action)\fC [static]\fP"

.PP
Definition at line 780 of file ControllerButtonHints\&.cs\&.
.SS "virtual void Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.SetInputSource (\fBSteamVR_Input_Sources\fP newInputSource)\fC [virtual]\fP"

.PP
Definition at line 127 of file ControllerButtonHints\&.cs\&.
.SS "static void Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.ShowButtonHint (\fBHand\fP hand, params \fBISteamVR_Action_In_Source\fP [] actions)\fC [static]\fP"

.PP
Definition at line 747 of file ControllerButtonHints\&.cs\&.
.SS "static void Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.ShowTextHint (\fBHand\fP hand, \fBISteamVR_Action_In_Source\fP action, string text, bool highlightButton = \fCtrue\fP)\fC [static]\fP"

.PP
Definition at line 793 of file ControllerButtonHints\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "Material Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.controllerMaterial"

.PP
Definition at line 18 of file ControllerButtonHints\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.debugHints = false"

.PP
Definition at line 25 of file ControllerButtonHints\&.cs\&.
.SS "Color Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.flashColor = new Color( 1\&.0f, 0\&.557f, 0\&.0f )"

.PP
Definition at line 19 of file ControllerButtonHints\&.cs\&.
.SS "\fBSteamVR_Action_Vibration\fP Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.hapticFlash = SteamVR_Input\&.GetAction<\fBSteamVR_Action_Vibration\fP>('Haptic')"

.PP
Definition at line 22 of file ControllerButtonHints\&.cs\&.
.SS "\fBSteamVR_Input_Sources\fP Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.inputSource\fC [protected]\fP"

.PP
Definition at line 76 of file ControllerButtonHints\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.textHintPrefab"

.PP
Definition at line 20 of file ControllerButtonHints\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Valve\&.VR\&.InteractionSystem\&.ControllerButtonHints\&.initialized\fC [get]\fP"

.PP
Definition at line 71 of file ControllerButtonHints\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
