.TH "Valve.VR.InteractionSystem.FireSource" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.InteractionSystem.FireSource
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBfireParticlePrefab\fP"
.br
.ti -1c
.RI "bool \fBstartActive\fP"
.br
.ti -1c
.RI "ParticleSystem \fBcustomParticles\fP"
.br
.ti -1c
.RI "bool \fBisBurning\fP"
.br
.ti -1c
.RI "float \fBburnTime\fP"
.br
.ti -1c
.RI "float \fBignitionDelay\fP = 0"
.br
.ti -1c
.RI "AudioSource \fBignitionSound\fP"
.br
.ti -1c
.RI "bool \fBcanSpreadFromThisSource\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file FireSource\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "float Valve\&.VR\&.InteractionSystem\&.FireSource\&.burnTime"

.PP
Definition at line 23 of file FireSource\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.FireSource\&.canSpreadFromThisSource = true"

.PP
Definition at line 31 of file FireSource\&.cs\&.
.SS "ParticleSystem Valve\&.VR\&.InteractionSystem\&.FireSource\&.customParticles"

.PP
Definition at line 19 of file FireSource\&.cs\&.
.SS "GameObject Valve\&.VR\&.InteractionSystem\&.FireSource\&.fireParticlePrefab"

.PP
Definition at line 15 of file FireSource\&.cs\&.
.SS "float Valve\&.VR\&.InteractionSystem\&.FireSource\&.ignitionDelay = 0"

.PP
Definition at line 24 of file FireSource\&.cs\&.
.SS "AudioSource Valve\&.VR\&.InteractionSystem\&.FireSource\&.ignitionSound"

.PP
Definition at line 29 of file FireSource\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.FireSource\&.isBurning"

.PP
Definition at line 21 of file FireSource\&.cs\&.
.SS "bool Valve\&.VR\&.InteractionSystem\&.FireSource\&.startActive"

.PP
Definition at line 16 of file FireSource\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
