.TH "Valve.VR.CVROverlay" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valve.VR.CVROverlay
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEVROverlayError\fP \fBFindOverlay\fP (string pchOverlayKey, ref ulong pOverlayHandle)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBCreateOverlay\fP (string pchOverlayKey, string pchOverlayName, ref ulong pOverlayHandle)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBDestroyOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetHighQualityOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "ulong \fBGetHighQualityOverlay\fP ()"
.br
.ti -1c
.RI "uint \fBGetOverlayKey\fP (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBEVROverlayError\fP pError)"
.br
.ti -1c
.RI "uint \fBGetOverlayName\fP (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBEVROverlayError\fP pError)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayName\fP (ulong ulOverlayHandle, string pchName)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayImageData\fP (ulong ulOverlayHandle, IntPtr pvBuffer, uint unBufferSize, ref uint punWidth, ref uint punHeight)"
.br
.ti -1c
.RI "string \fBGetOverlayErrorNameFromEnum\fP (\fBEVROverlayError\fP error)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayRenderingPid\fP (ulong ulOverlayHandle, uint unPID)"
.br
.ti -1c
.RI "uint \fBGetOverlayRenderingPid\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayFlag\fP (ulong ulOverlayHandle, \fBVROverlayFlags\fP eOverlayFlag, bool bEnabled)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayFlag\fP (ulong ulOverlayHandle, \fBVROverlayFlags\fP eOverlayFlag, ref bool pbEnabled)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayColor\fP (ulong ulOverlayHandle, float fRed, float fGreen, float fBlue)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayColor\fP (ulong ulOverlayHandle, ref float pfRed, ref float pfGreen, ref float pfBlue)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayAlpha\fP (ulong ulOverlayHandle, float fAlpha)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayAlpha\fP (ulong ulOverlayHandle, ref float pfAlpha)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayTexelAspect\fP (ulong ulOverlayHandle, float fTexelAspect)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayTexelAspect\fP (ulong ulOverlayHandle, ref float pfTexelAspect)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlaySortOrder\fP (ulong ulOverlayHandle, uint unSortOrder)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlaySortOrder\fP (ulong ulOverlayHandle, ref uint punSortOrder)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayWidthInMeters\fP (ulong ulOverlayHandle, float fWidthInMeters)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayWidthInMeters\fP (ulong ulOverlayHandle, ref float pfWidthInMeters)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayAutoCurveDistanceRangeInMeters\fP (ulong ulOverlayHandle, float fMinDistanceInMeters, float fMaxDistanceInMeters)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayAutoCurveDistanceRangeInMeters\fP (ulong ulOverlayHandle, ref float pfMinDistanceInMeters, ref float pfMaxDistanceInMeters)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayTextureColorSpace\fP (ulong ulOverlayHandle, \fBEColorSpace\fP eTextureColorSpace)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayTextureColorSpace\fP (ulong ulOverlayHandle, ref \fBEColorSpace\fP peTextureColorSpace)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayTextureBounds\fP (ulong ulOverlayHandle, ref \fBVRTextureBounds_t\fP pOverlayTextureBounds)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayTextureBounds\fP (ulong ulOverlayHandle, ref \fBVRTextureBounds_t\fP pOverlayTextureBounds)"
.br
.ti -1c
.RI "uint \fBGetOverlayRenderModel\fP (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBHmdColor_t\fP pColor, ref \fBEVROverlayError\fP pError)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayRenderModel\fP (ulong ulOverlayHandle, string pchRenderModel, ref \fBHmdColor_t\fP pColor)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayTransformType\fP (ulong ulOverlayHandle, ref \fBVROverlayTransformType\fP peTransformType)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayTransformAbsolute\fP (ulong ulOverlayHandle, \fBETrackingUniverseOrigin\fP eTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToOverlayTransform)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayTransformAbsolute\fP (ulong ulOverlayHandle, ref \fBETrackingUniverseOrigin\fP peTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToOverlayTransform)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayTransformTrackedDeviceRelative\fP (ulong ulOverlayHandle, uint unTrackedDevice, ref \fBHmdMatrix34_t\fP pmatTrackedDeviceToOverlayTransform)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayTransformTrackedDeviceRelative\fP (ulong ulOverlayHandle, ref uint punTrackedDevice, ref \fBHmdMatrix34_t\fP pmatTrackedDeviceToOverlayTransform)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayTransformTrackedDeviceComponent\fP (ulong ulOverlayHandle, uint unDeviceIndex, string pchComponentName)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayTransformTrackedDeviceComponent\fP (ulong ulOverlayHandle, ref uint punDeviceIndex, System\&.Text\&.StringBuilder pchComponentName, uint unComponentNameSize)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayTransformOverlayRelative\fP (ulong ulOverlayHandle, ref ulong ulOverlayHandleParent, ref \fBHmdMatrix34_t\fP pmatParentOverlayToOverlayTransform)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayTransformOverlayRelative\fP (ulong ulOverlayHandle, ulong ulOverlayHandleParent, ref \fBHmdMatrix34_t\fP pmatParentOverlayToOverlayTransform)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBShowOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBHideOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "bool \fBIsOverlayVisible\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetTransformForOverlayCoordinates\fP (ulong ulOverlayHandle, \fBETrackingUniverseOrigin\fP eTrackingOrigin, \fBHmdVector2_t\fP coordinatesInOverlay, ref \fBHmdMatrix34_t\fP pmatTransform)"
.br
.ti -1c
.RI "bool \fBPollNextOverlayEvent\fP (ulong ulOverlayHandle, ref \fBVREvent_t\fP pEvent, uint uncbVREvent)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayInputMethod\fP (ulong ulOverlayHandle, ref \fBVROverlayInputMethod\fP peInputMethod)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayInputMethod\fP (ulong ulOverlayHandle, \fBVROverlayInputMethod\fP eInputMethod)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayMouseScale\fP (ulong ulOverlayHandle, ref \fBHmdVector2_t\fP pvecMouseScale)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayMouseScale\fP (ulong ulOverlayHandle, ref \fBHmdVector2_t\fP pvecMouseScale)"
.br
.ti -1c
.RI "bool \fBComputeOverlayIntersection\fP (ulong ulOverlayHandle, ref \fBVROverlayIntersectionParams_t\fP pParams, ref \fBVROverlayIntersectionResults_t\fP pResults)"
.br
.ti -1c
.RI "bool \fBIsHoverTargetOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "ulong \fBGetGamepadFocusOverlay\fP ()"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetGamepadFocusOverlay\fP (ulong ulNewFocusOverlay)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayNeighbor\fP (\fBEOverlayDirection\fP eDirection, ulong ulFrom, ulong ulTo)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBMoveGamepadFocusToNeighbor\fP (\fBEOverlayDirection\fP eDirection, ulong ulFrom)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayDualAnalogTransform\fP (ulong ulOverlay, \fBEDualAnalogWhich\fP eWhich, ref \fBHmdVector2_t\fP pvCenter, float fRadius)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayDualAnalogTransform\fP (ulong ulOverlay, \fBEDualAnalogWhich\fP eWhich, ref \fBHmdVector2_t\fP pvCenter, ref float pfRadius)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayTexture\fP (ulong ulOverlayHandle, ref \fBTexture_t\fP pTexture)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBClearOverlayTexture\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayRaw\fP (ulong ulOverlayHandle, IntPtr pvBuffer, uint unWidth, uint unHeight, uint unDepth)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayFromFile\fP (ulong ulOverlayHandle, string pchFilePath)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayTexture\fP (ulong ulOverlayHandle, ref IntPtr pNativeTextureHandle, IntPtr pNativeTextureRef, ref uint pWidth, ref uint pHeight, ref uint pNativeFormat, ref \fBETextureType\fP pAPIType, ref \fBEColorSpace\fP pColorSpace, ref \fBVRTextureBounds_t\fP pTextureBounds)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBReleaseNativeOverlayHandle\fP (ulong ulOverlayHandle, IntPtr pNativeTextureHandle)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayTextureSize\fP (ulong ulOverlayHandle, ref uint pWidth, ref uint pHeight)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBCreateDashboardOverlay\fP (string pchOverlayKey, string pchOverlayFriendlyName, ref ulong pMainHandle, ref ulong pThumbnailHandle)"
.br
.ti -1c
.RI "bool \fBIsDashboardVisible\fP ()"
.br
.ti -1c
.RI "bool \fBIsActiveDashboardOverlay\fP (ulong ulOverlayHandle)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetDashboardOverlaySceneProcess\fP (ulong ulOverlayHandle, uint unProcessId)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetDashboardOverlaySceneProcess\fP (ulong ulOverlayHandle, ref uint punProcessId)"
.br
.ti -1c
.RI "void \fBShowDashboard\fP (string pchOverlayToShow)"
.br
.ti -1c
.RI "uint \fBGetPrimaryDashboardDevice\fP ()"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBShowKeyboard\fP (int eInputMode, int eLineInputMode, string pchDescription, uint unCharMax, string pchExistingText, bool bUseMinimalMode, ulong uUserValue)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBShowKeyboardForOverlay\fP (ulong ulOverlayHandle, int eInputMode, int eLineInputMode, string pchDescription, uint unCharMax, string pchExistingText, bool bUseMinimalMode, ulong uUserValue)"
.br
.ti -1c
.RI "uint \fBGetKeyboardText\fP (System\&.Text\&.StringBuilder pchText, uint cchText)"
.br
.ti -1c
.RI "void \fBHideKeyboard\fP ()"
.br
.ti -1c
.RI "void \fBSetKeyboardTransformAbsolute\fP (\fBETrackingUniverseOrigin\fP eTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToKeyboardTransform)"
.br
.ti -1c
.RI "void \fBSetKeyboardPositionForOverlay\fP (ulong ulOverlayHandle, \fBHmdRect2_t\fP avoidRect)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBSetOverlayIntersectionMask\fP (ulong ulOverlayHandle, ref \fBVROverlayIntersectionMaskPrimitive_t\fP pMaskPrimitives, uint unNumMaskPrimitives, uint unPrimitiveSize)"
.br
.ti -1c
.RI "\fBEVROverlayError\fP \fBGetOverlayFlags\fP (ulong ulOverlayHandle, ref uint pFlags)"
.br
.ti -1c
.RI "\fBVRMessageOverlayResponse\fP \fBShowMessageOverlay\fP (string pchText, string pchCaption, string pchButton0Text, string pchButton1Text, string pchButton2Text, string pchButton3Text)"
.br
.ti -1c
.RI "void \fBCloseMessageOverlay\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2688 of file openvr_api\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.ClearOverlayTexture (ulong ulOverlayHandle)"

.PP
Definition at line 3034 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVROverlay\&.CloseMessageOverlay ()"

.PP
Definition at line 3149 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVROverlay\&.ComputeOverlayIntersection (ulong ulOverlayHandle, ref \fBVROverlayIntersectionParams_t\fP pParams, ref \fBVROverlayIntersectionResults_t\fP pResults)"

.PP
Definition at line 2988 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.CreateDashboardOverlay (string pchOverlayKey, string pchOverlayFriendlyName, ref ulong pMainHandle, ref ulong pThumbnailHandle)"

.PP
Definition at line 3069 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.CreateOverlay (string pchOverlayKey, string pchOverlayName, ref ulong pOverlayHandle)"

.PP
Definition at line 2701 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.DestroyOverlay (ulong ulOverlayHandle)"

.PP
Definition at line 2707 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.FindOverlay (string pchOverlayKey, ref ulong pOverlayHandle)"

.PP
Definition at line 2695 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetDashboardOverlaySceneProcess (ulong ulOverlayHandle, ref uint punProcessId)"

.PP
Definition at line 3091 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.CVROverlay\&.GetGamepadFocusOverlay ()"

.PP
Definition at line 2998 of file openvr_api\&.cs\&.
.SS "ulong Valve\&.VR\&.CVROverlay\&.GetHighQualityOverlay ()"

.PP
Definition at line 2717 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVROverlay\&.GetKeyboardText (System\&.Text\&.StringBuilder pchText, uint cchText)"

.PP
Definition at line 3116 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayAlpha (ulong ulOverlayHandle, ref float pfAlpha)"

.PP
Definition at line 2788 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayAutoCurveDistanceRangeInMeters (ulong ulOverlayHandle, ref float pfMinDistanceInMeters, ref float pfMaxDistanceInMeters)"

.PP
Definition at line 2832 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayColor (ulong ulOverlayHandle, ref float pfRed, ref float pfGreen, ref float pfBlue)"

.PP
Definition at line 2775 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayDualAnalogTransform (ulong ulOverlay, \fBEDualAnalogWhich\fP eWhich, ref \fBHmdVector2_t\fP pvCenter, ref float pfRadius)"

.PP
Definition at line 3023 of file openvr_api\&.cs\&.
.SS "string Valve\&.VR\&.CVROverlay\&.GetOverlayErrorNameFromEnum (\fBEVROverlayError\fP error)"

.PP
Definition at line 2744 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayFlag (ulong ulOverlayHandle, \fBVROverlayFlags\fP eOverlayFlag, ref bool pbEnabled)"

.PP
Definition at line 2764 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayFlags (ulong ulOverlayHandle, ref uint pFlags)"

.PP
Definition at line 3138 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayImageData (ulong ulOverlayHandle, IntPtr pvBuffer, uint unBufferSize, ref uint punWidth, ref uint punHeight)"

.PP
Definition at line 2737 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayInputMethod (ulong ulOverlayHandle, ref \fBVROverlayInputMethod\fP peInputMethod)"

.PP
Definition at line 2968 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVROverlay\&.GetOverlayKey (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBEVROverlayError\fP pError)"

.PP
Definition at line 2722 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayMouseScale (ulong ulOverlayHandle, ref \fBHmdVector2_t\fP pvecMouseScale)"

.PP
Definition at line 2978 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVROverlay\&.GetOverlayName (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBEVROverlayError\fP pError)"

.PP
Definition at line 2727 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVROverlay\&.GetOverlayRenderingPid (ulong ulOverlayHandle)"

.PP
Definition at line 2754 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVROverlay\&.GetOverlayRenderModel (ulong ulOverlayHandle, System\&.Text\&.StringBuilder pchValue, uint unBufferSize, ref \fBHmdColor_t\fP pColor, ref \fBEVROverlayError\fP pError)"

.PP
Definition at line 2859 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlaySortOrder (ulong ulOverlayHandle, ref uint punSortOrder)"

.PP
Definition at line 2810 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayTexelAspect (ulong ulOverlayHandle, ref float pfTexelAspect)"

.PP
Definition at line 2799 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayTexture (ulong ulOverlayHandle, ref IntPtr pNativeTextureHandle, IntPtr pNativeTextureRef, ref uint pWidth, ref uint pHeight, ref uint pNativeFormat, ref \fBETextureType\fP pAPIType, ref \fBEColorSpace\fP pColorSpace, ref \fBVRTextureBounds_t\fP pTextureBounds)"

.PP
Definition at line 3049 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayTextureBounds (ulong ulOverlayHandle, ref \fBVRTextureBounds_t\fP pOverlayTextureBounds)"

.PP
Definition at line 2854 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayTextureColorSpace (ulong ulOverlayHandle, ref \fBEColorSpace\fP peTextureColorSpace)"

.PP
Definition at line 2844 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayTextureSize (ulong ulOverlayHandle, ref uint pWidth, ref uint pHeight)"

.PP
Definition at line 3062 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayTransformAbsolute (ulong ulOverlayHandle, ref \fBETrackingUniverseOrigin\fP peTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToOverlayTransform)"

.PP
Definition at line 2879 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayTransformOverlayRelative (ulong ulOverlayHandle, ref ulong ulOverlayHandleParent, ref \fBHmdMatrix34_t\fP pmatParentOverlayToOverlayTransform)"

.PP
Definition at line 2906 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayTransformTrackedDeviceComponent (ulong ulOverlayHandle, ref uint punDeviceIndex, System\&.Text\&.StringBuilder pchComponentName, uint unComponentNameSize)"

.PP
Definition at line 2900 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayTransformTrackedDeviceRelative (ulong ulOverlayHandle, ref uint punTrackedDevice, ref \fBHmdMatrix34_t\fP pmatTrackedDeviceToOverlayTransform)"

.PP
Definition at line 2889 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayTransformType (ulong ulOverlayHandle, ref \fBVROverlayTransformType\fP peTransformType)"

.PP
Definition at line 2869 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetOverlayWidthInMeters (ulong ulOverlayHandle, ref float pfWidthInMeters)"

.PP
Definition at line 2821 of file openvr_api\&.cs\&.
.SS "uint Valve\&.VR\&.CVROverlay\&.GetPrimaryDashboardDevice ()"

.PP
Definition at line 3101 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.GetTransformForOverlayCoordinates (ulong ulOverlayHandle, \fBETrackingUniverseOrigin\fP eTrackingOrigin, \fBHmdVector2_t\fP coordinatesInOverlay, ref \fBHmdMatrix34_t\fP pmatTransform)"

.PP
Definition at line 2932 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVROverlay\&.HideKeyboard ()"

.PP
Definition at line 3121 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.HideOverlay (ulong ulOverlayHandle)"

.PP
Definition at line 2922 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVROverlay\&.IsActiveDashboardOverlay (ulong ulOverlayHandle)"

.PP
Definition at line 3081 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVROverlay\&.IsDashboardVisible ()"

.PP
Definition at line 3076 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVROverlay\&.IsHoverTargetOverlay (ulong ulOverlayHandle)"

.PP
Definition at line 2993 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVROverlay\&.IsOverlayVisible (ulong ulOverlayHandle)"

.PP
Definition at line 2927 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.MoveGamepadFocusToNeighbor (\fBEOverlayDirection\fP eDirection, ulong ulFrom)"

.PP
Definition at line 3013 of file openvr_api\&.cs\&.
.SS "bool Valve\&.VR\&.CVROverlay\&.PollNextOverlayEvent (ulong ulOverlayHandle, ref \fBVREvent_t\fP pEvent, uint uncbVREvent)"

.PP
Definition at line 2949 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.ReleaseNativeOverlayHandle (ulong ulOverlayHandle, IntPtr pNativeTextureHandle)"

.PP
Definition at line 3057 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetDashboardOverlaySceneProcess (ulong ulOverlayHandle, uint unProcessId)"

.PP
Definition at line 3086 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetGamepadFocusOverlay (ulong ulNewFocusOverlay)"

.PP
Definition at line 3003 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetHighQualityOverlay (ulong ulOverlayHandle)"

.PP
Definition at line 2712 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVROverlay\&.SetKeyboardPositionForOverlay (ulong ulOverlayHandle, \fBHmdRect2_t\fP avoidRect)"

.PP
Definition at line 3129 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVROverlay\&.SetKeyboardTransformAbsolute (\fBETrackingUniverseOrigin\fP eTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToKeyboardTransform)"

.PP
Definition at line 3125 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayAlpha (ulong ulOverlayHandle, float fAlpha)"

.PP
Definition at line 2783 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayAutoCurveDistanceRangeInMeters (ulong ulOverlayHandle, float fMinDistanceInMeters, float fMaxDistanceInMeters)"

.PP
Definition at line 2827 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayColor (ulong ulOverlayHandle, float fRed, float fGreen, float fBlue)"

.PP
Definition at line 2770 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayDualAnalogTransform (ulong ulOverlay, \fBEDualAnalogWhich\fP eWhich, ref \fBHmdVector2_t\fP pvCenter, float fRadius)"

.PP
Definition at line 3018 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayFlag (ulong ulOverlayHandle, \fBVROverlayFlags\fP eOverlayFlag, bool bEnabled)"

.PP
Definition at line 2759 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayFromFile (ulong ulOverlayHandle, string pchFilePath)"

.PP
Definition at line 3044 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayInputMethod (ulong ulOverlayHandle, \fBVROverlayInputMethod\fP eInputMethod)"

.PP
Definition at line 2973 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayIntersectionMask (ulong ulOverlayHandle, ref \fBVROverlayIntersectionMaskPrimitive_t\fP pMaskPrimitives, uint unNumMaskPrimitives, uint unPrimitiveSize)"

.PP
Definition at line 3133 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayMouseScale (ulong ulOverlayHandle, ref \fBHmdVector2_t\fP pvecMouseScale)"

.PP
Definition at line 2983 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayName (ulong ulOverlayHandle, string pchName)"

.PP
Definition at line 2732 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayNeighbor (\fBEOverlayDirection\fP eDirection, ulong ulFrom, ulong ulTo)"

.PP
Definition at line 3008 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayRaw (ulong ulOverlayHandle, IntPtr pvBuffer, uint unWidth, uint unHeight, uint unDepth)"

.PP
Definition at line 3039 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayRenderingPid (ulong ulOverlayHandle, uint unPID)"

.PP
Definition at line 2749 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayRenderModel (ulong ulOverlayHandle, string pchRenderModel, ref \fBHmdColor_t\fP pColor)"

.PP
Definition at line 2864 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlaySortOrder (ulong ulOverlayHandle, uint unSortOrder)"

.PP
Definition at line 2805 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayTexelAspect (ulong ulOverlayHandle, float fTexelAspect)"

.PP
Definition at line 2794 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayTexture (ulong ulOverlayHandle, ref \fBTexture_t\fP pTexture)"

.PP
Definition at line 3029 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayTextureBounds (ulong ulOverlayHandle, ref \fBVRTextureBounds_t\fP pOverlayTextureBounds)"

.PP
Definition at line 2849 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayTextureColorSpace (ulong ulOverlayHandle, \fBEColorSpace\fP eTextureColorSpace)"

.PP
Definition at line 2839 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayTransformAbsolute (ulong ulOverlayHandle, \fBETrackingUniverseOrigin\fP eTrackingOrigin, ref \fBHmdMatrix34_t\fP pmatTrackingOriginToOverlayTransform)"

.PP
Definition at line 2874 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayTransformOverlayRelative (ulong ulOverlayHandle, ulong ulOverlayHandleParent, ref \fBHmdMatrix34_t\fP pmatParentOverlayToOverlayTransform)"

.PP
Definition at line 2912 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayTransformTrackedDeviceComponent (ulong ulOverlayHandle, uint unDeviceIndex, string pchComponentName)"

.PP
Definition at line 2895 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayTransformTrackedDeviceRelative (ulong ulOverlayHandle, uint unTrackedDevice, ref \fBHmdMatrix34_t\fP pmatTrackedDeviceToOverlayTransform)"

.PP
Definition at line 2884 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.SetOverlayWidthInMeters (ulong ulOverlayHandle, float fWidthInMeters)"

.PP
Definition at line 2816 of file openvr_api\&.cs\&.
.SS "void Valve\&.VR\&.CVROverlay\&.ShowDashboard (string pchOverlayToShow)"

.PP
Definition at line 3097 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.ShowKeyboard (int eInputMode, int eLineInputMode, string pchDescription, uint unCharMax, string pchExistingText, bool bUseMinimalMode, ulong uUserValue)"

.PP
Definition at line 3106 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.ShowKeyboardForOverlay (ulong ulOverlayHandle, int eInputMode, int eLineInputMode, string pchDescription, uint unCharMax, string pchExistingText, bool bUseMinimalMode, ulong uUserValue)"

.PP
Definition at line 3111 of file openvr_api\&.cs\&.
.SS "\fBVRMessageOverlayResponse\fP Valve\&.VR\&.CVROverlay\&.ShowMessageOverlay (string pchText, string pchCaption, string pchButton0Text, string pchButton1Text, string pchButton2Text, string pchButton3Text)"

.PP
Definition at line 3144 of file openvr_api\&.cs\&.
.SS "\fBEVROverlayError\fP Valve\&.VR\&.CVROverlay\&.ShowOverlay (ulong ulOverlayHandle)"

.PP
Definition at line 2917 of file openvr_api\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
