.TH "VoiceChecker" 3 "Sat Jul 20 2019" "Version https://github.com/Saurabhbagh/Multi-User-VR-Viewer--10th-July/" "Multi User Vr Viewer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VoiceChecker \- Voice Check works in a walky talky manner\&. You press the grip button and it will transfer your voice to other player / clients in the network\&. You will not be able hear your own voice\&. Here you convert the voice to float and then to byte to send it on the network\&. Once the other non local player who receives it will do the reverse of it \&. There it will get converted from byte to float and then to Audio Clip  

.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSoundOut\fP (byte[] bytedata)"
.br
.RI "This methods is taking the byte voice data and converting into float and then to voice again using Audio\&.create "
.ti -1c
.RI "void \fBCmdSendData\fP (byte[] data)"
.br
.RI "Send data for comvertion from byte to voice\&. "
.ti -1c
.RI "void \fBRpcSendAudioToClients\fP (byte[] bytedata)"
.br
.RI "To send data from server to client "
.in -1c
.SH "Detailed Description"
.PP 
Voice Check works in a walky talky manner\&. You press the grip button and it will transfer your voice to other player / clients in the network\&. You will not be able hear your own voice\&. Here you convert the voice to float and then to byte to send it on the network\&. Once the other non local player who receives it will do the reverse of it \&. There it will get converted from byte to float and then to Audio Clip 


.PP
Definition at line 13 of file VoiceChecker\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void VoiceChecker\&.CmdSendData (byte [] data)"

.PP
Send data for comvertion from byte to voice\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbytedata\fP 
.RE
.PP

.PP
Definition at line 115 of file VoiceChecker\&.cs\&.
.SS "void VoiceChecker\&.RpcSendAudioToClients (byte [] bytedata)"

.PP
To send data from server to client 
.PP
\fBParameters:\fP
.RS 4
\fIbytedata\fP 
.RE
.PP

.PP
Definition at line 126 of file VoiceChecker\&.cs\&.
.SS "void VoiceChecker\&.SoundOut (byte [] bytedata)"

.PP
This methods is taking the byte voice data and converting into float and then to voice again using Audio\&.create 
.PP
\fBParameters:\fP
.RS 4
\fIbytedata\fP Byte form of voice 
.RE
.PP
converting to float 
.PP
Definition at line 91 of file VoiceChecker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Multi User Vr Viewer from the source code\&.
